"""Curated Q&A for 10-Astrophysics leaves."""
ASTRO = {
"10-Astrophysics/01-Accretion-Disk-Modeling": [
("What is an accretion disk?",
 "A rotating disk of gas spiraling toward the black hole, heated and radiating as centrifugal support is lost to turbulence - the image's light source."),
("What governs the disk structure?",
 "Conservation of mass/angular momentum (transport via turbulence/stress), energy balance (cooling), and the vertical hydrostatic equilibrium - the disk equations."),
("What is the thin-disk (Novikov-Thorne) model?",
 "The analytic steady-state approximation: geometrically thin, optically thick disk with inner edge at ISCO and blackbody-like emission - the classic baseline."),
("What sets the disk's temperature profile?",
 "Dissipation rate ~ Mdot^0.5 r^-3/4-ish scaling (thin-disk T(r) = T_star (r/rin)^{-3/4}); the emission then follows a multi-temperature blackbody."),
("What is the role of the MRI in the disk?",
 "The magnetorotational instability drives the turbulence that transports angular momentum - the physical 'alpha-viscosity' source in real disks."),
("How does GRMHD improve on the thin disk?",
 "It computes the actual stress tensor, evolution, and plunging region - correcting the ISCO-edge and adding magnetic fields the thin model lacks."),
("What is the disk's vertical structure?",
 "Height H(r) from pressure balance; hot thick flows (H/r ~ 0.3-1) show in images differently than cold thin (H/r ~ 0.01) - a big visual and physics lever."),
("How does disk density fall with radius?",
 "Peaks near the inner region and decays outward (roughly a power law with the turbulence profile); the profile sets the emissivity radial distribution."),
("What does the disk's spin interaction do?",
 "Prograde spins truncate disks closer (ISCO drops) and heat the inner edge; retrograde widen and cool - spin controls the ring-gap geometry."),
("What is the 'plunging region'?",
 "Inside ISCO, the gas in-spirals without stable orbits - barely radiating but magnetically stressed; its emission is a distinct thin feature near the ring."),
("How is the disk's density scaled for rendering?",
 "Absolute density n_e is set by the accretion rate normalization - the image brightness that a telescope measures depends on using physical Mdot."),
("What is the disk's temperature estimate for a real source?",
 "T ~ 1e7-1e8 K in the inner region of a bright AGN disk; the M87-ish hot flow sits nearer electron temperatures 1e10-1e11 K - orders matter for emissivity."),
("How do you choose the disk model for a render?",
 "Thin-disk analytic for speed and starfield images; GRMHD snapshot for realism (the M87-class ring) - the model switch is a CLI flag, not a code branch."),
("What is the summary?",
 "Accretion-disk modeling ties the turbulence-transport physics to the emission field - the thin-disk or GRMHD choice sets every ring observable you render."),
],
"10-Astrophysics/02-Temperature-Profiles": [
("What is the temperature profile of the disk?",
 "The radial run of temperature: thin disks follow T(r) ~ r^-3/4 (viscous); hot GRMHD flows carry an electron temperature set by heating/cooling balance."),
("Why does temperature matter so much?",
 "Synchrotron emissivity is extremely temperature-sensitive (via the electron gamma distribution) - the ring's brightness and color follow T_e primarily."),
("What is the ion vs electron temperature split?",
 "Magnetic dissipation heats ions preferentially; electrons cool faster; the ratio T_e/T_i ~ 0.1-1 depends on the heating prescription (Rbeta, or set models)."),
("How is the electron temperature obtained?",
 "From a closure: fraction of the dissipation to electrons (Rbeta), a scaling on the magnetic energy density, or a plasma-beta relation - the model's choice."),
("What is the radial profile's inner hotness?",
 "In the innermost radii gas reaches the virial temperature ~ GM m_p/(r R) - the steep inward heating that lights the ring."),
("What does the vertical temperature profile look like?",
 "Colder near the midplane of a thin disk, hotter in the corona - the corona-vs-disk contrast shows in the image's limb structure."),
("What is the effect of temperature on the spectrum?",
 "Higher T_e shifts the synchrotron turnover to higher frequency and steepens the emitted bands - temperature IS the color knob of the renderer."),
("How does the temperature drive SSA?",
 "The optically-thin/thick transition scales with T (via spectral slope); a hotter inner region can become self-absorbed at lower bands - a coupled effect."),
("What are typical electron temperatures rendered?",
 "For M87-class flows ~ 1e10-1e11 K in the ring; the renderer must sample the local T_e robustly near the ISCO where the profile is steep."),
("How do you validate a temperature model?",
 "The emitted SED's slope/peak must match the observed (for fits) or the analytic expectation for a given T(r) - the temperature-to-observable chain tested end-to-end."),
("What is the summary?",
 "Temperature profiles are the emissivity's thermostat - ion/electron closures set radial and vertical T_e; the renderer inherits ring brightness and color from them."),
],
"10-Astrophysics/03-Density-and-Pressure": [
("What is the density structure of the inner disk?",
 "A peak near the ISCO and a decaying outward to the outer boundary; below a floor density the code interpolates - the density field is the emissivity's volume weight."),
("Why does density matter to the image?",
 "Synchrotron emissivity scales ~ n_e B^2-ish; the density times field product sets brightness - dense regions and B-peaks both light up."),
("How does pressure determine the flow?",
 "Gas+magetic pressure sets the height/profile and the turbulence state (beta); the density/pressure/B relationship is the GRMHD's internal equilibrium."),
("What is the plasma-beta map?",
 "beta = p_gas/p_B varies from beta>>1 in the disk body to beta~1 near the plunging edge - the image's contrast between disk and magnetized funnel."),
("What is the outer-atmosphere behavior?",
 "The floor density halo fills the domain edges; its presence biases outer-ray images - report the floor with every density-relevant render."),
("How is density scaled to real n_e?",
 "n_e is derived from the code density times a normalization determined by the accretion rate model - the 'mass scale' factor converting code units."),
("What is the 'density floor' artifact?",
 "The ad-hoc minimum density inflates emission in vacuum (funnel/jet); the code flags floor-affected cells in the emissivity map - transparent rendering."),
("How does density peak with the plunging region?",
 "The near-ISCO density max concentrates the ring emission - exactly why the ring hugs the horizon scale rather than the thin-disk 6M edge."),
("What is the relation to Mdot?",
 "Mdot = 2 pi r rho v at the ISCO; the density profile and velocity normalize each other - a consistency check the model must obey."),
("How do you validate density in the render?",
 "The radially-integrated column density and total flux from a snapshot must match an independent 1-D calculation - the density-to-light pipeline test."),
("What is the summary?",
 "Density and pressure set WHERE and HOW MUCH the disk glows: n_e is the volume weight, beta the morphology, floors the honest artifact flag."),
],
"10-Astrophysics/04-MRI-Turbulence": [
("What is the MRI?",
 "The magnetorotational instability: differential rotation stretches magnetic fields, driving turbulent angular-momentum transport - the engine of accretion."),
("Why is the disk turbulent (not laminar)?",
 "Keplerian profiles are Rayleigh-stable hydrodynamically but unstable with even a weak seed field - turbulence is the equilibrium state of magnetized accretion."),
("How does the MRI transport angular momentum?",
 "The Reynolds and Maxwell stresses (B_r B_phi terms) torque the gas outward - the source of the effective viscosity feeding inward."),
("What is the alpha parameter?",
 "alpha = (stress)/(pressure) ~ 0.01-0.1 from MRI simulations - the modern replacement for the Shakura-Sunyaev 'viscosity' with a physical origin."),
("How is alpha measured in a GRMHD run?",
 "Time-and-volume-average the stress tensor components against pressure over the saturated-turbulence window - the single most useful diagnostic number."),
("What does turbulence do to density?",
 "It spawns the intermittent clumps/spiral patterns in the disk - the emissivity's peppered texture that differentiates a GRMHD image from a smooth model."),
("How does the MRI set the disk's emission?",
 "The turbulence's magnetic amplification concentrates B in intermittent patches - synchrotron lights up the variable, non-azimuthally-symmetric emission."),
("What is MRI's saturation mechanism?",
 "The turbulence saturates when the dynamo's growth matches numerical/physical dissipation - maintaining the stress against reconnection and diffusion."),
("Why do thin disks need resolving the MRI?",
 "The fastest-growing wavelength scales with sqrt(v_A^2/Omega^2); under-resolved grids kill the instability and the disk becomes artificially laminar."),
("How does the MRI appear in images?",
 "Migrating bright clumps and azimuthal brightness variation - the 'flickering files' with orbital-period structure, a distinguishing dynamical signature."),
("What is the summary?",
 "MRI turbulence transports angular momentum physically, textures the density field, and sets the disk's variability - the reason GRMHD images wiggle and flare."),
],
"10-Astrophysics/05-Jets-and-Outflows": [
("What are relativistic jets?",
 "Collimated outflows of plasma and Poynting flux along the spin axis, powered by the spinning hole (Blandford-Znajek) and the disk (Blandford-Payne)."),
("How are jets launched?",
 "Magnetic field lines anchored to the rotating hole/disk fling plasma outward (magnetocentrifugal slingshot) - the field's spin power becomes directed flow."),
("What is the Blandford-Znajek (BZ) mechanism?",
 "The spinning magnetic field of the hole's ergosphere couples to plasma, extracting rotational energy as Poynting flux - the primary strong-spin jet engine."),
("What is the Blandford-Payne (BP) mechanism?",
 "The disk's own rotation slings off gas along field lines if they tilt outward - a lower-power disk-driven complement to BZ."),
("What determines jet power?",
 "Spin a squared times the horizon flux squared: P_jet ~ a^2 Phi^2 - the (a, MAD flux) combination sets jet luminosity and speed."),
("What is a MAD jet vs SANE jet?",
 "MAD threads the horizon with a strong field -> powerful, stable jet; SANE's weak field -> weak/intermittent jet - visibly different in the render."),
("How do jets appear in glowing renders?",
 "Relativistic doppler beaming lights the approaching jet strongly; the funnel's low-density fast flow renders as a dim, beamed spine and a bright counter-jet shadow interplay."),
("What is the jet speed and beaming?",
 "Bulk Lorentz factors 2-10 (sub-mm to X-ray blobs); the beaming contrast between approaching/receding jet dominates the image's top-bottom asymmetry."),
("What does the funnel region look like?",
 "A low-density, magnetically-dominated chamber above/below the hole - the jet's spine; in images it appears darker than the disk but Doppler-limb brightened."),
("How does the jet connect to the ring?",
 "The jet's base sits at the hole's pole; light crossing it is lensed around the shadow - the jet structure threads through the ring/arch geometry."),
("What is the observed fingerprint?",
 "The 1.3mm M87 jet emerges from the ring's south; matching the simulated jet angle/parallax is part of the horizon-scale fit."),
("What is the summary?",
 "Jets are the spin's magnetic exhaust - BZ/BP physics sets power and speed; the renderer turns them into beamed polar spines around the shadow."),
],
"10-Astrophysics/06-M87-Event-Horizon-Telescope": [
("What did the EHT image of M87* show?",
 "The first black-hole image: a ring of ~42 +- 3 microarcsec diameter enclosing a dark shadow - the photon-ring/horizon-scale signature of a spinning hole."),
("What is M87*?",
 "The supermassive black hole (~6.5e9 solar masses) in the galaxy M87, at ~55 Mly - the largest-angular-size horizon in the sky, hence the EHT's prime target."),
("What does the 2019 image reveal about spin?",
 "The asymmetry (bright crescent to the south) is consistent with a bright approaching-side Doppler-boosted disk - consistent with modest spin and a viewing angle ~17 deg."),
("What is the 1.3mm (230 GHz) observing band?",
 "Where the disk's synchrotron is optically thin and the ring's photon-ring dominates - the physical window the EHT observes."),
("How does the raytracer reproduce M87*?",
 "Render a GRMHD (MAD-family) disk at a~0.9, inclination ~17 deg, with electron-heating closure, then blur to the EHT's ~20-25 microarcsec beam."),
("What is the ring's physical size?",
 "~5.2 M for a Schwarzschild photon-sphere edge (projected); for M87*, 42 microarcsec maps to ~9.5 M in diameter at the distance - the shadow-observable link."),
("What parts of the image are robust?",
 "The ring DIAMETER is robust to emission details (geometry-set); the asymmetric brightness and inner-faintness are model-dependent - the fit's lever arm."),
("What is the EHT's resolution/how achieved?",
 "Very-long-baseline interferometry (VLBI) with telescopes across the planet forming a ~12,000 km baseline - resolution ~20 microarcsec, enough for the ring."),
("What did follow-up (2018+, 2024) add?",
 "The ring persists with polarization maps (magnetic fields at the ring) and a hinted jet rotation - the same ray-traced geometry extended to Q/U channels."),
("How does a renderer 'fit' the EHT image?",
 "Run a grid of (a, inclination, model) renders, convolve with the beam, compare residuals to the observed image - the forward-model fitting loop."),
("What is the summary?",
 "M87* defined the observable: a ~5M diameter ring with a Doppler-asymmetric crescent; your raytracer renders exactly that from Kerr GRMHD disks and matches it against 1.3mm data."),
],
"10-Astrophysics/07-SgrA-Event-Horizon-Telescope": [
("What did the EHT image of Sgr A* show?",
 "A ring of ~51.8 +- 2.3 microarcsec diameter around a shadow - the Milky Way's central black hole, with the same geometric physics at ~4 million solar masses."),
("What is Sgr A*?",
 "Sagittarius A* - the ~4.15e6 solar-mass black hole at the Galactic Center, 8.2 kpc away, seen through a turbulent scattering screen."),
("How does Sgr A* differ from M87*?",
 "~1500x less massive, faster forcing and variability (minutes-hours vs days), and viewed through interstellar scattering - a harder image with a richer time-domain."),
("What is the scattering-screen issue?",
 "The line of sight diffracts in the interstellar medium - smears/blurs the image below ~0.2 arcsec-ish and adds a red noise; the renderer must account for it in comparisons."),
("What is the fit result?",
 "The ring diameter ~51 microarcsec is spin-compatible; the image fluctuates between frames consistent with a hot, compact disk seen at moderate inclination."),
("How does the image support the black-hole hypothesis?",
 "The shadow size matches a Kerr horizon at the parallax-measured mass/distance - a clean geometric confirmation of the Schwarzschild/Kerr expectations."),
("What do the time-variable images show?",
 "Fast brightness clumps orbiting within minutes - the MRI turbulence/dirty-blobs of GRMHD models become a time-domain observable at the Galaxy's center."),
("How do you compare a renderer to Sgr A*?",
 "Render at 230GHz with interstellar-scattering convolution and a short movie cadence; compare the 'signature image' ensembles, not one snapshot."),
("What is the role of the crescent parameterization?",
 "The m-ring (asymmetric ring) decomposition parametrizes radius, width, and asymmetry - the compact summary both renders and data report."),
("What is the summary?",
 "Sgr A* is the dynamic M87-class target - a ~51-microarcsec ring, blurred by scattering, fluctuating on minute scales; your raytracer replicates that with hot GRMHD disks and movie-mode light curves."),
],
"10-Astrophysics/08-Interstellar-Gargantua": [
("What is Gargantua?",
 "The fictional supermassive black hole (10^8 M_sun) from Interstellar, rendered by Double Negative (DNEG) with a bespoke GR raytracer - the cinematic icon."),
("Did the movie use real Kerr raytracing?",
 "Yes: DNEG wrote a physical ray tracer (backwards photon mapping through Kerr geodesics) driven by the project physicists (Thorne) - base realism for the visuals."),
("What is the disk appearance?",
 "The accretion disk is bright, thin, and warped (tilted), imaged edge-on: the far side wraps over and under the shadow (the lensed 'arch'), near side bright - the signature shot."),
("What is the gravitational lensing displayed?",
 "The lensed halo of the disk around the shadow: the light bending wraps the disk's image multiple times (the bright 'photon ring' and sub-rings)."),
("What is the famous image sequence?",
 "The camera passes into the lensing region, wraps around the hole, and the disk's image spirals - a choreographed demonstration of strong-field geodesics."),
("What physics was hand-tuned for cinema?",
 "Colors/intensity obey physical spectra but adjusted for cinematic readability; accretion-rate parameters etc. dramatized - realism with cinematography as the master."),
("What GR effects are visible?",
 "Doppler beaming (crescent asymmetry), gravitational redshift (dimming/reddening into the shadow), and the photon-ring's nested image series."),
("What is the code's relation to a scientific raytracer?",
 "DNEG's renderer IS a Kerr ray tracer (Geodesic59() etc.); a production-grade pipeline like this project shares the same core equations."),
("What is the 'accel disk' vs 'hot-spot' modeling?",
 "The movie's disk uses a temperature/brightness model plus hot spots; scientific pipelines use GRMHD snapshots - the difference is the emission source, not the geometry."),
("What does Gargantua teach this project?",
 "It validates the exact visual language (wrapped disk, crescent, photon ring) that faithful Kerr ray tracing produces - the aesthetic goals are physical ones."),
("What is the summary?",
 "Gargantua is the producer-grade proof of Kerr ray tracing: same geodesic physics, cinematic emission; your project is the scientific sibling of that raster."),
],
"10-Astrophysics/09-Photon-Ring-Signatures": [
("What is the photon ring?",
 "The sharp, magnified image of the black hole's unstable photon sphere - a thin annulus just outside the shadow boundary produced by photon orbits that wind around the hole."),
("What is its mathematical nature?",
 "A caustic/leak region: rays with impact parameter in a narrow band around b_crit wind many times and pile up in the image - an exponential-approach bright edge."),
("How thin/bright is it?",
 "The ring's width shrinks and intensity grows toward the critical orbit (self-similar sub-rings); at high resolution the photon ring is a few % of the shadow width."),
("How does it differ from the disk image's outer ring?",
 "The disk's own Doppler-brightened ring is the accretion flow's image; the PHOTON ring is the geometry's caustic - the two can co-locate visually but have distinct scalings."),
("What is the sub-ring (demagnification) ladder?",
 "Null geodesics winding n half-turns appear as n faint copies demagnified by ~e^{-pi} per half-turn - the 'onion' near the shadow boundary."),
("How is the photon ring measured?",
 "Its diameter and fractional width (relative to the shadow) are the robust fingerprints; ring width is spin/inclination-dependent (smaller-ratio at high a)."),
("Why is the photon ring great for tests of gravity?",
 "Its radius is mostly determined by the geometry (M, a) rather than emission details - a deviation from GR in the ring is a clean probe of exotic-gravity theories."),
("How does the ring respond to spin?",
 "Prograde ring shifts inward, retrograde outward -> an asymmetric ring width; measuring the ring's asymmetry pins a approximately."),
("What does the renderer output for the ring?",
 "A radial intensity cut across the image produces the ring-profile map - the diagnostics (radius, width, asymmetry) that feed model comparisons."),
("What is the ring's time behavior?",
 "The ring brightness flickers as the disk's inner emission varies, but its RADIUS stays fixed - separating geometry (stable) from emission (variable)."),
("What is the summary?",
 "The photon ring is a geometric caustic signature - sharp, self-similar, spin-sensitive, and emission-robust; it is the precision observable of horizon-scale images."),
],
"10-Astrophysics/10-Horizon-Scale-Imaging": [
("What is horizon-scale imaging?",
 "Observing/imaging the region within ~10 r_g of the horizon - the regime where strong-field GR effects (shadow, photon ring, beaming) dominate the picture."),
("What resolution is required?",
 "Angles ~ a few times M/D; for M87* that's ~10-40 microarcsec - beyond a single telescope, hence VLBI networks (EHT)."),
("What telescopes form the EHT?",
 "Millimeter (1.3mm) telescopes on 6+ continents (ALMA, NOEMA, SMT, etc.) acting as one Earth-sized interferometer - the aggregate aperture."),
("What is the array's limiting function (uv coverage)?",
 "The finite baselines truncate Fourier coverage -> a point-spread beam ~25-50 microarcsec; images are therefore blurred reconstructions, not raw snapshots."),
("Why chose 230 GHz (1.3mm)?",
 "At this band the inner disk is optically thin (sees the photon ring) while atmospheric opacity is still manageable - the sweet spot of the field."),
("What are the key VLBI challenges?",
 "Phase calibration, weather, array sensitivity, and scattering (Sgr A*) - the observing side of imaging; the theory side is your raytracer."),
("How does theory aid reconstruction?",
 "Forward-modeling: a GRMHD+raytracer ensemble predicts images; the EHT's reconstruction uses them as priors/constraints (the 'imaging' hands the PRIOR power)."),
("What is the 'image-domain' comparison?",
 "Blur the rendered frame to the array's beam and compare pixel-residuals with the observed image - the quantitative scientific face-off."),
("What is the shadow's observational status?",
 "The dark region's angular size matches the Kerr prediction for both M87* and Sgr A* - the most direct evidence for an event horizon to date."),
("What are the next-generation upgrades?",
 "ngEHT adds telescopes/bands for better uv coverage and movies - more frames, sharper rings, and ultimately the photon-ring peak measured directly."),
("What is the summary?",
 "Horizon-scale imaging is the observational arena of this project: VLBI-blurred renders compared to EHT images, with the photon ring and shadow as the theory-observation bridge."),
],
"10-Astrophysics/11-Simulated-vs-Observed": [
("How do you compare a render to a real EHT image?",
 "Run the raytracer, convolve with the observing beam, add noise/calibration, then compare in image space (residuals) or via summary statistics (m-ring, asymmetry)."),
("What is the beam convolution step?",
 "The observed image = render * PSF (Gaussian beam) + noise; this is the 'observability filter' that makes pixels fair to compare."),
("What are the image summary statistics?",
 "The m-ring decomposition (diameter, fractional width, asymmetry) and total flux - the compact, calibrated comparisons both sides report."),
("How do you handle model variance?",
 "Each GRMHD run has time-varying emission; the fit uses ensembles (a grid of snapshots) not one frame - reporting the mean/residual band."),
("What is a 'good fit' criterion?",
 "The model's blurred image should reproduce the ring diameter, flux ratio, and asymmetry within the measurement uncertainties - a chi-square in image space."),
("What are degeneracies to watch?",
 "Spin and inclination trade against emission-model parameters; the fit must marginalize over the (Te closure, MAD/SANE) - honest error bars require it."),
("What is the role of polarization comparisons?",
 "Q/U maps constrain the B-field geometry more tightly than intensity alone - a richer 'sim-vs-obs' channel once polarization is rendered."),
("How do you validate that a mismatch is physics (not a bug)?",
 "First establish the analytic validation suite passes (correct geometry/transfer); then any observed-vs-sim discrepancy is a model-space question."),
("What does a failed fit teach?",
 "Ring too tense/broad/offset -> spin, inclination, or emission model off; the forward-model loop literally scans the parameter space to learn."),
("What is the summary?",
 "Sim-vs-observed is a calibrated comparison - beam-convolve, summarize, ensemble-average, and marginalize degeneracies - turning your raytracer into a science instrument."),
],
"10-Astrophysics/12-Open-Data-Sources": [
("What are the open GRMHD data sources for testing?",
 "Published simulation snapshots (e.g., the GRMHD catalogue behind M87*/Sgr A* EHT papers, BHAC/KORAL/HARM model libraries, and ATOM/ASTOR archives) - check licences and steer."),
("Where does one find these datasets?",
 "EHT Collaborations' model-data release, the ERC/SKA community repositories, and the code-authors' websites - with the papers' supplementary material often the richest."),
("What is the 'epoch model grid' release?",
 "The EHT's 2019/2020 papers published suites of 1000s of GRMHD renders (models over {MAD/SANE, spin, inclination, Te}) - the public testbed for a raytracer."),
("How do you validate against public images?",
 "Download the published EHT model images (FITS), blur-comparison your render to theirs, and reproduce the ring diameter tables - an external cross-check."),
("What about open analytic data?",
 "Not data per se, but gold-standard codes (the EHT's GRTRANS, IPOLE, BHOSS) release numeric GRMHD->image pipelines whose outputs can be compared digitally."),
("How do you license/attribute?",
 "Check each dataset's terms (often CC-BY or cite-the-paper); record the dataset DOI + the exact snapshot tag in your run metadata - scientific hygiene."),
("What is a safe test snapshot approach?",
 "Start with a tiny GRMHD-like analytic scene (kept in-repo) for unit tests, then the public M87/SgrA model dumps for integration realism - two tiers of data."),
("How do converters ease ingestion?",
 "Write once a GRMHD->internal-field converter (HDF5/FITS -> the raytracer's blob) and add dataset-specific reader glue - reusing the same integration path."),
("What is the reproducibility bonus of open data?",
 "A public dataset + published render yields a numerical 'golden image' anyone can regenerate - the strongest scientific validation the project can get."),
("What is the summary?",
 "Open data (EHT model releases, code-author snapshots) gives realistic scenes and external reference images - cite, version-pin, and wire into converters."),
]}