"""Curated Q&A for 01-CUDA leaves."""
CUDA = {
"01-CUDA/01-What-is-GPU-Computing": [
("What is GPU computing and why is it needed for raytracing?",
 "GPU computing runs large parallel workloads on graphics processors with thousands of cores. Raytracing is embarrassingly parallel - each pixel ray is independent - so a GPU raytracer can trace millions of rays per frame instead of thousands on a CPU."),
("How does a GPU differ from a CPU in architecture?",
 "A CPU has a few powerful cores optimized for low-latency serial execution with large caches. A GPU has thousands of small, simple cores optimized for high-throughput parallel execution, relying on many concurrent threads to hide memory latency."),
("What does SIMT mean?",
 "Single Instruction, Multiple Thread. A warp of 32 threads executes the same instruction on different data, similar to SIMD but with independent lanes and scalar registers per thread."),
("Why is data parallelism the natural mapping for a raytracer?",
 "Every pixel's ray follows an independent trajectory with no shared state, so the problem maps 1:1 to threads. There is no need for communication between rays until pixels are written."),
("What is Flynn's taxonomy and where does a GPU fit?",
 "Flynn classifies architectures by instructions and data streams: SISD (CPU), SIMD, MISD, MIMD. GPUs are MIMD at block granularity and SIMT/SIMD at warp granularity - best understood as a hybrid."),
("What are the trade-offs of GPU vs CPU for numeric integration?",
 "GPUs win at throughput for massive independent rays but lose at latency for single trajectories; a CPU debug path is useful for validating one ray step-by-step."),
("What hardware vendors matter for GPU computing?",
 "NVIDIA (CUDA ecosystem, Nsight tools) dominates HPC raytracing; AMD (ROCm/HIP) and Intel (SYCL) are alternatives. CUDA is the de-facto starting point and portable via HIP."),
("What is the difference between GPGPU and graphics rendering APIs?",
 "Traditional graphics (OpenGL/Vulkan/DirectX) rasterize triangles; GPGPU (CUDA/ROCm) runs arbitrary compute kernels. A raytracer can run in either, but CUDA gives direct control over memory and numerics."),
("How many floating-point operations can a modern GPU do?",
 "Consumer GPUs exceed 50-100 TFLOPS FP32 (e.g., RTX 4090 ~82 TFLOPS); data centers like H100 approach 1000. Raw FLOPs overstate real raytracer speed, which is memory- and latency-bound."),
("What is host vs device in CUDA terminology?",
 "Host = CPU + system RAM; device = GPU + VRAM. Code and data move across the PCIe/ NVLink boundary via explicit copies, and kernel launches dispatch work to the device."),
("What is the typical speedup for a well-parallelized raytracer?",
 "10-100x over a single CPU core, depending on memory patterns and how well overlap hides latency; the theoretical speedup is limited by Amdahl's law on the serial fraction (import, transfers, encoding)."),
("What is Amdahl's law and how does it apply?",
 "Speedup is bounded by 1/(1-f + f/p), where f is the parallel fraction and p the parallelism. Pipeline serial stages like data import and tile merging cap the GPU's benefit, so they must be overlapped."),
("What is Gustafson's law and why is it more optimistic?",
 "Gustafson says speedup scales with problem size - rendering more rays/samples amortizes the serial fraction. It justifies 'just add more samples' scaling on larger frames."),
("Why is a GPU raytracer memory-bandwidth bound rather than compute bound?",
 "Each integration step needs metric evaluations and grid samples; code (arithmetic) is only a few operations, while data movement dominates, so DRAM bandwidth under Sustains throughput."),
("Where do the classic GPU numbers matter for a black-hole renderer?",
 "For a 4K frame with 100 samples you trace ~830 million rays; even at 100M rays/s with long paths that is seconds to minutes per frame - the budget is real and drives integrator design."),
("What is the development workflow difference with GPUs?",
 "You write kernels plus host orchestration, cannot easily step through a thousand threads with printf, and must reason about memory hierarchy - GPU work needs profiles and small-scale manufacturer tests."),
],
"01-CUDA/02-Thread-Hierarchy": [
("What is the CUDA thread hierarchy?",
 "Grid -> Blocks -> Threads. A grid is up to 2^31-1 blocks (x) and 65535 (y/z); each block has up to 1024 threads arranged in a 3D index; threads within a block share shared memory and can synchronize."),
("Why is the 3D indexing useful?",
 "It maps naturally onto image grids and voxel grids: image (x,y) pixels, (x,y,z) data cubes; the API gives you blockIdx and threadIdx for each axis."),
("What is the maximum number of threads in a block?",
 "1024 on all current NVIDIA architectures (this limit is per block, not per SM). Practical block sizes are 128-256 for raytracing to balance occupancy and register pressure."),
("What is the grid-stride loop pattern?",
 "Instead of launching one thread per element, launch a fixed number of threads and have each loop, striding by the grid size: for (i = tid; i < N; i += gridStride). This decouples launch config from problem size."),
("Why is launching one thread per pixel bad for very large images?",
 "Pixel counts (millions) exceed practical grid limits and tie kernel config to image size; the grid-stride loop lets one launch handle any resolution and reuses blocks for better scheduling."),
("How do you flatten a 2D image index?",
 "int idx = blockIdx.x * blockDim.x + threadIdx.x; using a 1D grid over w*h pixels, or use 2D blockIdx with (x,y) directly mapped to columns and rows."),
("What is a block's role in the hierarchy?",
 "A block is the unit of scheduling on a streaming multiprocessor (SM) and the unit of inter-thread cooperation: shared memory and __syncthreads() are block-scoped."),
("What happens when you launch more blocks than SMs?",
 "The scheduler runs blocks until the SMs fill, then queues the rest; blocks retire and new ones start, keeping the machine busy as long as there is queued work."),
("Can separate blocks synchronize?",
 "No - blocks are independent by design; cross-block coordination requires atomic flags, global memory spin-waits, or multiple kernel launches (separate synchronization 'phases')."),
("How do you choose block dimensions for a raytracer kernel?",
 "Prefer a multiple of 32 (warp size). Common choices: (256,1,1) or (16,16) tiles; benchmark occupancy and tail effects because ragged image sizes waste lanes."),
("What is the total thread limit per grid?",
 "Blocks per grid (x) up to 2^31-1, so the practical total is huge; the grid-stride loop means you rarely approach it anyway."),
("What does threadIdx.x do in a kernel?",
 "It identifies the thread within its block; combined with blockIdx and blockDim it produces a global id used to pick which ray to trace."),
("Why does thread and block indexing affect performance?",
 "IDs determine which pixels neighboring lanes in a warp process; keeping IDs spatially adjacent helps coalesced writes and cache-friendly reads of the same image rows."),
("What is the relationship between block size and register usage?",
 "Registers per thread times threads per block must fit the SM's register file; a big block with heavy per-thread state reduces the number of resident blocks."),
("When is one thread per pixel appropriate despite limits?",
 "When rays are extremely long-lived and registers/temps dominate, a 1:1 mapping with grid-stride over pixels is still flexible; the point is never to hard-wire the launch to a fixed resolution."),
],
"01-CUDA/03-Grid-and-Block-Configuration": [
("How do you decide grid and block size for an unknown GPU?",
 "Launch with an occupancy heuristic: query cudaOccupancyMaxActiveBlocksPerMultiprocessor, then multiply by the SM count; common solid default is block=256 and grid = ceil(N/256)."),
("What is cudaOccupancyMaxActiveBlockSizes?",
 "int numBlocks; cudaOccupancyMaxActiveBlocksPerMultiprocessor(&numBlocks, kernel, threadsPerBlock, smem); it predicts how many blocks fit per SM for a given kernel and shared memory."),
("Why tune block sizes at all?",
 "Too small a block underuses the SM and adds launch/scheduling overhead; too large may exceed resource limits; the sweet spot typically yields ~50-100% target occupancy with low tail effects."),
("What is the difference between gridDim and blockDim?",
 "gridDim is the number/bounds of blocks per axis; blockDim the threads per block per axis. The global thread id is blockIdx.x*blockDim.x + threadIdx.x."),
("How do you handle image width not divisible by block size?",
 "Compute grid = ceil(width*height / block); guard inside the kernel with if (idx < N) so the ragged tail threads no-op instead of reading out of bounds."),
("What is 'coalesced' block ordering in terms of grid layout?",
 "Blocks scheduled in x,y,z order; laying the image out so consecutive blockIdx.x pieces are horizontally contiguous keeps warps scanning adjacent memory."),
("How does tail effect waste threads?",
 "If N is not a multiple of the grid stride, the last blocks under-fill; with tiny grids the waste is negligible, with 4k frames it is a few percent - guard and move on."),
("Why is a 1D configuration common for image kernels?",
 "It keeps the code simple and lays out the grid along the fastest axis; the memory coalescing benefits come from within-block adjacency, not dimensionality."),
("What information does the 'maxThreadsPerBlock' query give?",
 "The hard limit (1024 on modern NV); use it as a sanity bound when your kernel would need more threads for cooperation."),
("How do you choose configuration when shared memory is used?",
 "Shared memory per block is a second limit: total smem per SM / requested per block caps concurrent blocks; the occupancy API accounts for both automates the math."),
("What does cudaGetDeviceProperties expose?",
 "maxThreadsPerMultiProcessor, multiProcessorCount, regsPerMultiprocessor, sharedMemPerBlock, warpSize, and memory clock - the constants for manual launch tuning."),
("Why is measuring achieved occupancy better than theory?",
 "Register scheduling, spills, and branch effects make theoretical occupancy optimistic; the profiler shows achieved occupancy and you tune to that."),
("What is the standard 'smallest fast config' for raytracing?",
 "block=(128 or 256), grid fitted by occupancy, one ray per thread, no shared memory initially - then increase complexity only when profiling demands it."),
("How do you re-launch for different resolutions?",
 "Keep launch parameters a function of (width,height) computed at runtime; store them in a LaunchConfig struct passed to the host wrapper so tests reuse it."),
("What happens if you launch >maxThreadsPerBlock?",
 "cudaErrorInvalidValue at launch - the failure is immediate and detectable, so always compute valid bounds or query them once at startup."),
],
"01-CUDA/04-Memory-Hierarchy": [
("What is the CUDA memory hierarchy?",
 "Registers (per-thread, fastest), shared memory (per-block, on-chip), global memory (device-wide, off-chip DRAM), plus constant, texture/read-only, and local memory (register spills)."),
("What is the trade-off between registers and shared memory?",
 "Both are on-chip; registers are per-thread and fastest but limited (~64K per SM on modern GPUs while ~255 per thread); shared is per-block, indexed, and lets threads exchange data."),
("Why is global memory latency so high?",
 "DRAM access takes 400-800 cycles; kernels hide it with concurrency (many warps), so throughput depends on having enough parallelism in flight to keep memory busy."),
("How does the L2 cache help a raytracer?",
 "L2 (tens of MB on modern GPUs) caches global reads across SMs; nearby rays sampling nearby grid cells hit it, so interpolation-heavy stages benefit when data fits L2."),
("What is the uniformity vs divergence of constant memory?",
 "__constant__ is cached and optimized for every thread reading the SAME address (uniform); it is ideal for metric parameters (mass, spin) and camera matrices since they are read uniformly."),
("When is texture/read-only memory useful?",
 "For linear interpolation of fields (density, temperature) with cache benefits and clamping/wrap modes; the read-only __ldg() loads also hint the compiler."),
("What is local memory?",
 "Per-thread spill space that lives in global DRAM; it is a performance trap for large per-thread arrays - prefer keeping ray state in registers."),
("What is the size of shared memory on current GPUs?",
 "Up to 228KB per block on H100-class (opt-in) and ~100KB typical on consumer; dynamically beyond static amounts requires cudaFuncSetAttribute."),
("How do printf and other host services interact with device memory?",
 "printf in kernels is supported but serializes output and can perturb timing; use it in debug kernels only and gate it behind a compile flag."),
("What is memory coalescing at the hardware level?",
 "The memory system groups a warp's 32 accesses into as few 32-byte sectors/transactions as possible when addresses are consecutive - coalesced reads move data once per cache line."),
("Why does padding matter for 2D/3D field arrays?",
 "Row widths that are exact multiples of cache lines avoid wasted sectors; strided access across rows is where padding reduces effective bandwidth loss."),
("How does zero-copy / managed memory fit the hierarchy?",
 "cudaMallocManaged pages migrate between host and device on demand - convenient but with fine-grained faults it can serialize; pinned+explicit copies are often faster for streaming data."),
("What is the correct order to optimize memory?",
 "Measure first, then fix access patterns (coalescing/padding), then add shared-memory tiling, then manual data reuse - each step targets a measured bottleneck."),
("How do atomics interact with the memory hierarchy?",
 "Atomics operate in L2 on global addresses; they serialize for conflicting addresses (e.g., multiple rays scattering into one pixel) - avoid whenever one thread can own one output."),
("What is the impact of FP32 vs FP64 throughput in the hierarchy sense?",
 "FP64 runs at 1/2 to 1/64 of FP32 rate on consumer GPUs (1/2 on data-center A100/H100 without special config); the memory pipeline cares about bytes moved, not the FMUL class."),
],
"01-CUDA/05-Kernel-Syntax-and-Launch": [
("What is the syntax for a CUDA kernel?",
 "__global__ void kernel(float* out, int n){ int i = blockIdx.x*blockDim.x + threadIdx.x; if(i<n) out[i]=compute(i); } and launch as kernel<<<grid, block>>>(out, n);"),
("What is the difference between __global__, __device__, and __host__?",
 "__global__ functions run on device and are callable from host (the kernel); __device__ functions run on device only; __host__ run on host only; __host__ __device__ runs on both."),
("What does cudaLaunchKernel add over the <<<>>> syntax?",
 "It is the underlying launch API taking a pointer and an explicit config with streams and attributes; the <<<>>> sugar compiles down to it and is preferred for readability."),
("What are kernel launch bounds?",
 "__launch_bounds__(maxThreadsPerBlock, minBlocksPerSM) tells the compiler to limit register usage to meet those occupancy targets, trading spills for concurrency."),
("Why do kernels need a guard on thread index?",
 "grid sizes rarely divide the data exactly; if(i<n) prevents out-of-bounds reads/writes on the ragged tail - the universal safety pattern."),
("What happens if you launch a kernel with no active threads?",
 "It returns an error (invalid grid/block dims) or runs trivially; empty launches are a code smell pointing to bad configuration math."),
("How do you pass arguments to a kernel?",
 "By value (scalars, pointers) via the launch config; kernels cannot accept C++ objects with constructors 'by value' unless trivially copyable - prefer plain structs or device-code copies."),
("What is the benefit of const-qualifying kernel parameters?",
 "It lets the compiler cache or hoist unchanged values (metric coefficients), increasing ILP and reducing recomputation in the hot loop."),
("What does a kernel returning, vs a void function, mean?",
 "All kernels return void; you communicate results exclusively through device memory pointers in the argument list - no return values by design."),
("Why can't you scatter-allocate inside a kernel?",
 "Malloc in device code is slow and fragmentation-prone; preallocate output buffers on the host and have the kernel write into indexed slots."),
("What is the cost of launching a kernel?",
 "A few microseconds of host-side launch overhead; for tiny workloads that dominate, use fewer, larger launches or CUDA graphs to batch the launch cost."),
("How do you time a kernel correctly?",
 "Use CUDA events around the launch and time the elapsed event deltas; rdtsc-style timing includes queueing delays and the launch is asynchronous."),
("Is kernel launch synchronous or asynchronous?",
 "Asynchronous: control returns to the host immediately; the kernel runs when scheduling permits. Synchronize explicitly with cudaDeviceSynchronize() (generally a debugging step, not a pipeline step)."),
("How do you catch launch failures?",
 "Always check the return of cudaGetLastError() after the launch and cudaDeviceSynchronize() in debug builds - a silent invalid launch hides a geometry bug immediately."),
("What is kernel inlining and why does it matter?",
 "CUDA inlines small __device__ functions aggressively; it removes call overhead but can bloat registers - mark some __noinline__ when spill exceeds benefit."),
],
"01-CUDA/06-Warp-Execution-Model": [
("What is a warp?",
 "A group of 32 threads that execute together on an SM in lockstep; all current NVIDIA GPUs use 32-lane warps and instructions are issued per warp."),
("How does a warp scheduler work?",
 "Each SM has 4-8 warp schedulers, each issuing instructions from eligible warps (registers ready, no dependency stall); the scheduler selects a different warp when the current one stalls."),
("What happens when a warp diverges on a branch?",
 "The warp executes each taken path serially, masking out lanes that did not take it - divergence adds time proportional to the number of distinct paths."),
("What is warp divergence in a raytracer?",
 "Long and short rays take different loop lengths (captured vs escaped), so lanes retire at different times; the warp runs until all lanes exit, wasting cycles on finished lanes."),
("How do you reduce ray divergence?",
 "Sort rays by similar path budget, use occupancy to absorb imbalance, or allow early per-lane exit only at whole-warp granularity - the SIMT model constrains you."),
("What is the difference between SIMT and SIMD?",
 "SIMD buses data in registers; SIMT threads are conceptually independent with scalar registers but share instruction fetch - masking makes them look convergent."),
("How does __syncwarp() differ from __syncthreads()?",
 "__syncwarp() synchronizes only the 32 lanes of the warp (cheap, no shared-memory guarantee needed); __syncthreads() syncs the whole block and is required before/after shared-memory writes by many threads."),
("What is warp-level vote functionality (__ballot_sync)?",
 "It gathers a 32-bit mask of which lanes satisfied a predicate - useful for compacting active rays and for reduction tricks inside a warp."),
("Why does the shfl (shuffle) instruction matter?",
 "__shfl_sync lets lanes exchange register values without shared memory, enabling warp-level reductions (sums, maxes) 32x faster than memory-based counterparts."),
("What is the relationship between warp size and block size?",
 "Block sizes should be multiples of 32 so every warp is full; a 96-thread block uses exactly 3 warps and no partial lanes."),
("How many warps can an SM hold?",
 "Up to the MAX_WARPS_PER_SM limit (64 on many architectures), governing the number of independent streams the scheduler can hide latency with."),
("What is the execution 'eligible warp' concept?",
 "A warp is eligible when its next instruction's data dependencies are resolved; stalled warps (waiting on memory) are ineligible, so enough resident warps keep the SM issued."),
("How does a divergent geodesic loop hurt the tree?",
 "differs by path: rays winding near the photon sphere take 10-100x more steps, so mixed scenes show high tail latency - consider sorting by impact parameter per tile."),
("What is warp-level predication?",
 "Instead of branching, the compiler may compute both sides and mask results; predication avoids divergence but wastes work - the compiler chooses per heuristics."),
("When should you NOT worry about divergence?",
 "When rays are `uniform-ish' (a plausible first frame) - divergence tuning matters after correctness and after profiling shows the sim is moment-bound."),
],
"01-CUDA/07-Branch-Divergence": [
("What causes branch divergence?",
 "A single if/else or loop whose condition differs across lanes of a warp; the hardware executes each branch path serially with masks, multiplying cost."),
("What is the cost formula for divergence?",
 "Time roughly proportional to the number of distinct paths taken: if half the warp takes each branch, the warp pays both branch bodies in sequence."),
("How does divergence manifest in a geodesic tracer?",
 "Rays terminate at different radii/step counts (disk hit, horizon capture, escape), producing divergence in every termination branch and loop count."),
("What is the idiom to avoid per-ray early-out?",
 "Instead of an early break per thread, set a 'dead ray' flag and let the warp continue; the loop increments for all lanes until the max budget, then exits once."),
("How do you implement the dead-ray mask?",
 "bool alive = true; in the loop: if (alive) { step }; alive &= (state != escaped); the warp still loops len(maxRay) times but only paying work for live lanes."),
("What is the trade-off of the mask approach?",
 "You pay the full loop length for the longest ray in the warp but only compute for live lanes; net win when path lengths are similar, loss when extreme."),
("How do you sort rays to reduce divergence?",
 "Bucket or sort rays by computed impact parameter or region before the kernel so warps contain similar-path rays - common in production tracers, costs a sort."),
("Why is dynamic termination cheaper than a branch?",
 "Some hardware supports 'convergent' or early-exit heuristics at the warp level; relying on them is compiler-dependent, so deterministic masks are the portable choice."),
("How does divergence interact with the scheduling?",
 "Divergence desynchronizes memory-access phases, potentially hurting coalescing; keeping warps homogeneous also keeps their memory stages aligned."),
("What is the predication alternative to loops?",
 "For short bodies, the compiler flattens branches to predicated selects; it removes divergence but always executes both sides - good for tiny geodesic steps."),
("When measuring divergence, what profile metric do you watch?",
 "Nsight's 'branch divergence' and SM 'warp stalls' counters; if divergence is small but stalls remain, memory latency rather than control flow is the issue."),
("How do you test that divergence handling is correct?",
 "Render scenes with mixed disk/bg rays and check images are identical to a CPU reference; divergence policy changes timing, never geometry results."),
("What is the memory consequence of divergent control?",
 "Divided warps issue divergent loads at different times, doubling the number of memory transactions for the same data - another hidden cost."),
("What is the recommended lane count for testing?",
 "Debug with warp-sized images (32 or 64 wide) so you can reason about every lane; scale up only after the killed-ray logic is proven."),
("When does divergence become irrelevant?",
 "When occupancy is high and scheduler slots idle anyway - divergence only matters once it starves issue or shows up as measured stalls."),
],
"01-CUDA/08-Occupancy": [
("What is occupancy?",
 "The ratio of active warps to the maximum warps an SM can support; it is a proxy for how well latency can be hidden, not a direct measure of throughput."),
("What limits occupancy?",
 "Registers per thread, shared memory per block, block count per SM, and the fixed max warps/SM - the first two usually bind a raytracer."),
("What is 'theoretical occupancy' formula?",
 "occupancy = activeWarpsPerSM / maxWarpsPerSM; derived from launch config and resource limits via the occupancy API, always an upper bound."),
("Why is high occupancy not always faster?",
 "Too many resident warps can thrash cache and spill registers; sometimes fewer, better-scheduled warps with more registers per thread win."),
("How does register usage per thread set occupancy?",
 "The SM has a fixed register file (e.g., 65536 regs); if your kernel uses 40 regs/thread, only ~1600 threads fit - occupancy drops if you then launch 1024-thread blocks."),
("How do you check spills?",
 "Nsight Compute reports local memory (spill) traffic and registers used; ptxas '-v' or the compiler log also print counts at compile time."),
("What is __launch_bounds__ and how does it control occupancy?",
 "Declaring __launch_bounds__(256, 2) forces the compiler to cap registers so 2 blocks of 256 fit per SM, at the price of possible spills."),
("How does shared memory per block reduce occupancy?",
 "Blocks allocate smem at launch; the SM divides its shared pool by requested smem per block. Requesting 48KB/block leaves room for only ~3 blocks on a 227KB pool."),
("What occupancy target is sensible for a raytracer?",
 "50-100% is the usual band; measure achieved occupancy and use it as a diagnostic - if achieved is far below theoretical, resources or scheduling are the cause."),
("How do you use cudaOccupancyMaxActiveBlocksPerMultiprocessor?",
 "int nb; cudaOccupancyMaxActiveBlocksPerMultiprocessor(&nb, kernel, blockSize, smem); then blocks = nb * deviceProps.multiProcessorCount."),
("What is the difference between kernel-time occupancy and memory-time occupancy?",
 "Nsight distinguishes occupancy during arithmetic vs during stalls; optimizing memory occupancy (overlap of loads) usually moves the needle more than raw active warps."),
("How does the launch config density interplay with tail effects?",
 "If the last partial block is small the SM may run one big unit late; launching many smaller blocks smooths the tail at slight scheduling cost."),
("What effect does keeping per-ray state in registers have?",
 "Geodesic state (x, p, redshift) is ~10-20 registers; that is cheap, so a tracer can afford high occupancy even with long per-ray loops."),
("How do you pick the block size that maximizes occupancy?",
 "For a known register count, an occupancy sweep (64..1024 threads) with cudaOccupancyMaxActiveBlocksPerMultiprocessor instantly reveals the plateau."),
("What is the golden rule for occupancy tuning?",
 "Decide rays, then measure achieved occupancy at three configs, then choose the fastest with identical output - never guess from theory alone."),
],
"01-CUDA/09-Error-Handling-in-CUDA": [
("How do you check a CUDA call failed?",
 "CUDA_SAFE(cudaFuncName(...)): wrap every call, inspect the cudaError_t return, and assert/print the cudaGetErrorString on failure."),
("How do you catch asynchronous kernel errors?",
 "Launch (async) + cudaGetLastError() catches launch-config errors; runtime errors from within the kernel surface at the next synchronization - always sync in debug."),
("What is cudaError_t representation?",
 "An enum of error codes; cudaSuccess == 0; strings come from cudaGetErrorString(code). Higher-level frameworks wrap them for log context."),
("How do you write a reusable CUDA_SAFE macro?",
 "#define CUDA_SAFE(x) do { cudaError_t e=(x); if(e!=cudaSuccess){ fprintf(stderr,\"%s at %s:%d\\n\",cudaGetErrorString(e),__FILE__,__LINE__); exit(1);} } while(0)"),
("What are the top error codes in a raytracer?",
 "cudaErrorInvalidValue (bad launch dims), cudaErrorInvalidDevicePointer (stale host ptr), cudaErrorMemoryAllocation (OOM), and cudaErrorLaunchFailure (kernel crashed)."),
("Why check cudaDeviceSynchronize in development?",
 "It surfaces device-side faults (out-of-bounds writes can corrupt, not crash) at a known point; ship builds use streams and events instead for performance."),
("What diagnostics help find memory corruption?",
 "Compute Sanitizer (compute-sanitizer --tool memcheck) flags illegal global/shared accesses by warp, making wild pointers found within minutes."),
("How do you handle an out-of-memory on large images?",
 "Allocate per-tile buffers instead of one giant array, degrade resolution, or use cudaMallocManaged with async prefetch; handle cudaErrorMemoryAllocation gracefully."),
("What is the difference between host and device error domains?",
 "Host-side runtime errors (allocation, API misuse) are returned synchronously; device-side errors (kernel faults) appear lazily - both funnel into the same cudaError_t."),
("What should a production error handler do?",
 "Log the message with context (function, kernel, frame), free GPU resources, and exit with a nonzero code; in interactive tools, present a human summary."),
("How do you unit-test error paths?",
 "Assert that invalid configs produce expected errors in tests (negative testing), so the error path itself is verified, not just happy path rendering."),
("What is a 'sticky' error?",
 "Once a device error occurs, subsequent CUDA calls return the same error until cudaGetLastError() is called; early detection avoids masking real failures."),
("How does CUDA_LAUNCH_BLOCKING help?",
 "Setting the __CUDA_LAUNCH_BLOCKING__ env var to 1 makes all launches synchronous - a debugging aid that turns async failures into immediate, localizable ones."),
("Why disable these checks in performance builds?",
 "Each check is cheap but thousands of checks on every frame add measurable overhead; compile-time macros turn them off for production (-DCUDA_NO_ERROR_CHECK)."),
("What is the correct ordering for resource cleanup?",
 "Free allocations in reverse, sync streams, then cudaDeviceReset() in tests only; leaking device memory is detected by compute-sanitizer --tool leaks."),
],
"01-CUDA/10-Debugging-CUDA-Kernels": [
("What tools debug CUDA kernels?",
 "cuda-gdb (break on device), Nsight Compute (kernel metrics), and printf with streams; compute-sanitizer for memory errors - each answers a different question."),
("How do you debug a single ray?",
 "Compile a CPU trace path that runs one pixel's geodesic on the host with the same integrator and prints each step - the fastest way to inspect a winding trajectory."),
("What is the golden-image debugging trick?",
 "Render a tiny 32x32 image with simple geometry and save it as a fixture; any change that breaks it is bisected by re-rendering - fast, deterministic triage."),
("How do you printf from a kernel?",
 "printf(\"%d\\n\", threadIdx.x) works in device code; gate behind a debug macro and restrict to thread 0 or single blocks to avoid thousands of lines."),
("What are the limits of printf in kernels?",
 "It is buffered, asynchronous, and serializes - output order is not guaranteed per thread; it slows timing and should never ship in the hot path."),
("What does compute-sanitizer catch?",
 "Out-of-bounds global/shared accesses, misaligned reads, invalid concurrency, race conditions (racecheck tool) - turning silent corruption into stack traces."),
("What is NaN/Inf triage?",
 "Print packed (x,p) state when a step produces NaN; walk the step back with smaller steps to find the blow-up, usually a sign error in the metric types evaluated."),
("How do you compare device vs host results at scale?",
 "Run the same parameters on CPU fallback and device, diff images bit-wise; any mismatch isolates whether the bug is in logic (both wrong) or device-specific code."),
("What is 'assert' in kernel code?",
 "assert(cond) halts all threads and flags the error at the faulting line in debug builds - cheap guard for invariants like r > horizon in the integration loop."),
("How do you inspect register spills?",
 "nvcc -Xptxas -v prints per-kernel register and local-memory counts; spills degrade sharply and Nsight ties them to occupancy drops."),
("What is the role of deterministic seeds in debugging?",
 "Fixed per-pixel RNG keeps runs reproducible - a buggy frame with seed 7 replays identically, making flaky-but-nondeterministic symptoms debuggable."),
("How do you debug a hang?",
 "Use a timeout watch: if a frame exceeds X seconds in debug, dump all warp program counters via cuda-gdb or the NVTX timeline to find the stuck loop."),
("What does NVTX add to debugging?",
 "Named ranges mark phases (import, trace, post); Nsight Systems shows their durations and where time is actually spent in multi-kernel pipelines."),
("What is a good first debugging configuration?",
 "One block, blockSize 32, image 32x32, fixed seed, CPU-fallback compile - minimal enough to step the whole kernel mentally."),
("How do you avoid debugging two things at once?",
 "Freeze the scene, config, and data hash when triaging a change; reproduce on the fixture, then unfreeze one variable at a time."),
],
"01-CUDA/11-NVCC-Compilation-Flow": [
("What does nvcc do?",
 "The NVIDIA CUDA compiler driver: it parses .cu files, splits host and device code, compiles device code with an internal backend, and orchestrates host compilation."),
("How does nvcc separate host and device compilation?",
 "It invokes a front end that splits the source, then passes host fragments to the system C++ compiler (g++/cl) and device fragments to ptxas/the CUDA backend."),
("What is the difference between -arch, -code, and -gencode?",
 "-arch specifies the virtual architecture (SM_xx, e.g. compute_80) that PTX targets; -code chooses real code (sm_80 or PTX); -gencode combines several of these for multi-GPU binaries."),
("How do you target multiple GPUs from one build?",
 "Use -gencode arch=compute_80,code=sm_80;gencode arch=compute_86,code=sm_86 with fatbin embedding so the driver picks the right cubin at runtime."),
("Why should code also embed PTX?",
 "Including -gencode arch=compute_xx,code=compute_xx ships PTX that JIT-compiles for NEWER GPUs than the build machine - forward compatibility without recompiling."),
("What is the separation of .cu and .cuh?",
 ".cu contains kernels and host wrappers (they may be compiled by nvcc); .cuh headers let other TU's include declarations; .cu files must never be split mid-compilation state."),
("How do you use nvcc with CMake?",
 "CMake's CUDA language finds nvcc, compiles .cu files, applies flags via target_compile_options, and links the CUDA runtime; it also sets the host compiler override."),
("What is ptxas?",
 "The PTX-to-SASS assembler invoked by nvcc; passing -Xptxas -v prints resource usage (registers, spills, smem) - the budget for occupancy tuning."),
("What does -O3 do to device code?",
 "Enables aggressive optimization (inline, unroll, constant folding); device optimization is enabled by default, and disabling it (for debugging) collapses occupancy hopes."),
("What does -lineinfo add?",
 "Embeds source mapping for Nsight/profilers so metrics map to source lines; costs a little binary size, near-zero runtime cost - include it in profiling builds."),
("How do you handle warnings from the host compiler?",
 "nvcc passes host compilation through; keep the host toolchain warnings clean separately, since a noisy host pass hides real device flag mistakes."),
("What is a relocatable device code (rdc) build?",
 "-rdc=true allows device functions to be compiled separately and linked (needed for device code libraries and some templating); adds a device link step."),
("What is Device-Link in the flow?",
 "After host compilation, nvcc links device code in the 'device link' step assembling cubins into globals + fatbin - required whenever multiple .cu files share kernels."),
("How do you configure includes and defines?",
 "Pass -I for include paths, -D for macros (e.g., -DDEBUG_TRACE) that gate device debugging code - keeps debug and release builds distinct binaries."),
("How do you validate that the toolchain is consistent?",
 "Synchronize CUDA toolkit, driver, host compiler ABI, and CMake CUDA_ARCHITECTURES; the classic pitfall is a stale driver rejecting a new cubin at runtime."),
],
"01-CUDA/12-Runtime-vs-Driver-API": [
("What is the difference between the CUDA runtime and driver API?",
 "The runtime API (cudaMemcpy, cudaLaunchKernel) is a higher-level wrapper; the driver API (cuMemAlloc, cuLaunchKernel) is lower level, exposing explicit contexts and modules."),
("Which API do most applications use?",
 "The runtime API - it is the default for kernels, error handling, and streams; driver APIs are used by frameworks, libraries, and when building custom runtimes."),
("What is a CUDA context in the driver API?",
 "A context owns the device's resources (memory, modules) for a host thread; ::cuCtxCreate manages it explicitly, while the runtime creates/handles a primary context automatically."),
("What is cuModuleLoad and how does it differ from kernels?",
 "Driver code loads compiled cubins as modules at runtime (cuModuleLoad, cuModuleGetFunction), enabling just-in-time or dynamically-loaded kernels - the runtime embeds them statically."),
("Can you mix runtime and driver calls?",
 "Yes, through the mapped variants (cudaMemcpy vs cuMemcpy, contexts via cudaDevicePrimaryCtx); mixing mismatched allocations or streams across APIs is an easy bug."),
("When would you choose the driver API for a raytracer?",
 "When you need runtime kernel loading (choose integrator per config), custom context management, or tight integration with Vulkan/D3D interop - niche, professional reasons."),
("What are the typical error-handling differences?",
 "Driver calls return CUresult same-ish; the runtime adds name convenience (cudaGetErrorString). Both require the same defensive checking discipline."),
("How does the driver API handle kernels compiled separately?",
 "You compile a .cubin/.ptx offline, load it as module at runtime, and call cuLaunchKernel with extracted pointers - this is how libraries ship kernels without source."),
("What is the primary context?",
 "The context the runtime manages per device automatically; cudaDeviceSetLimit etc. configure it, and it is lazily created on first use."),
("What is peer-to-peer access and its API coupling?",
 "cuDeviceCanAccessPeer/cudaDeviceEnablePeerAccess allow GPUs in the same node to read each other's memory directly, bypassing host copies - important for multi-GPU frames."),
("Why do deep learning frameworks use driver APIs?",
 "They JIT-compile kernels, manage explicit streams and memory pools, and integrate custom device plugins - capabilities living at the driver layer."),
("What is Unified Memory's API-level impact?",
 "cudaMallocManaged is runtime; driver users often prefer explicit pools (cuMemCreate) with better allocation control for streaming pipelines."),
("How does the driver API expose graphs?",
 "cuGraphCreate/cuGraphInstantiate let you build execution graphs with node dependencies explicitly - the driver exposes the full graph feature set."),
("What mental model helps decide?",
 "Runtime for writing your own kernels fast and safely; driver for building tools that load kernel code at runtime. A town raytracer stays on the runtime."),
("What is the recommended migration path?",
 "Start with runtime; if profiling shows context/module JIT overhead or you need runtime loading, add driver calls behind an abstraction that tests both."),
],
"01-CUDA/13-Float-vs-Double-Precision": [
("Why does precision matter in a raytracer?",
 "Geodesic integration accumulates rounding; near the photon sphere and long winding paths, FP64 error can shift impact parameters and blur the ring that FP32 numerics smear."),
("What is the FP64-to-FP32 ratio on consumer GPUs?",
 "Typically 1:64 on gaming cards (64 FP32 pipes per 1 FP64), while data-centre/HPC cards run 1:2 - so FP64 has a steep throughput tax outside A100/H100-class parts."),
("When is FP32 acceptable?",
 "For visualization-quality renders (not science), short integration without grazing orbits, and when the metric is analytic - many stylish demos are FP32 throughout."),
("When must you use FP64?",
 "When producing research-grade images of the photon ring, running long winding geodesics, or validating results - any place where FP32 drift changes pixels."),
("How do you measure the precision error?",
 "Render the same scene in FP32 and FP64, take the per-pixel relative difference, and threshold where deviations appear (usually the ring edge) - a quantitative acceptance test."),
("What is the FP64 throughput ratio algorithm-independent?",
 "It is a hardware property: the SM has a fixed number of FP64 units; check deviceProps.major/minor and singleToDoublePrecisionPerfRatio for your target."),
("How do you keep the state in double without paying everywhere?",
 "Store geodesic state (x, p) in double but metric coefficient expressions in float where safe; compilers and intrinsics let you mix at per-variable granularity."),
("What is the compiler's role in careless precision changes?",
 "nvcc honors -use_fast_math rules but never silently demotes double; your code chooses the type via the state struct at declaration time."),
("How does adaptive stepping interact with precision?",
 "Tighter tolerances with FP32 can keep error down at the cost of more steps; FP64 gives the same error with larger, cheaper steps - the real saving often comes from double."),
("What is the deterministic-bit issue?",
 "FP32 FMA ordering varies with vectorization; FP64 ordering is stable enough for reproducible goldens - another reason science runs use double."),
("When does lower precision visibly break images?",
 "The photon ring's thinest feature, the sub-horizon brightness floor, and long-lensed origins where small angular errors alias to dark speckle."),
("What is the 'precise divide' flag?",
 "-prec-div=true (default) prevents the compiler from replacing division with faster approximate reciprocals; keep it on in the tracer to avoid diagonal artifacts."),
("How do you choose a mixed-precision budget?",
 "Trace in FP64 (state + metric) while tone mapping and import use FP32; the geodesic is where error matters - the last pipeline stages are comfortably float."),
("How does preference show in CUDA libraries?",
 "Libraries like cuBLAS offer FP64 and FP32 variants; the ratio applies per kernel, so profile any library call you lean on."),
("What is the practical recommendation you give a beginner?",
 "Build correct and validated in double first; then and only then measure whether FP32 is acceptable for the target GPU and render."),
("Why do some GPUs differ in how they limit FP64 (e.g. locked ratios)?",
 "Consumer chips physically contain fewer double-precision units to save die area; the ratio is a marketing and architecture decision you cannot software-overclock away."),
],
"01-CUDA/14-Vector-Types": [
("What are CUDA vector types?",
 "Derived types like float2, float3, float4, dim3, and storage-backed structs that pack several scalars and enable aligned, vectorized memory access and SIMT-friendliness."),
("Why use float4 for color/position?",
 "A float4 is 16 bytes, aligning with 128-bit memory transactions and cache lines; writing pixels as float4 batches four writes into fewer transactions."),
("How big is the throughput difference for aligned loads?",
 "Loading float4 reduces the number of load instructions and transactions 4x versus scalar float, dramatically improving memory-bound kernels like ray-sample interpolation."),
("What is the alignment requirement of float4?",
 "16-byte aligned; allocate with cudaMalloc (which aligns) and keep struct offsets on 16-byte boundaries or the compiler inserts slow fixups or errors."),
("What are the swizzle/exponent operations on vector types?",
 "Access fields as .x .y .z .w (or .r .g .b .a); pieces like float2 have no automatic packing - grouping is up to you so bundling state keeps memory local."),
("When is a plain struct better than a vector type?",
 "For heterogeneous state (position, momentum, redshift, flags), a custom struct gives one register-cache-friendly blob; vector types shine for homogeneous homogeneous packs (positions, colors)."),
("What is the difference between float3 and float4 storage?",
 "float3 is 12 bytes (misaligned for some operations and padded to 16 in kernels); prefer float4 for output and align your arrays to 16."),
("How do vector types interact with coalescing?",
 "Averaging over lanes of a warp, a float4 stride consecutive addresses: each lane fetches 16B, total 512B per warp in one or two transactions - the ideal pattern."),
("What are half-precision types?",
 "half and half2 pack 16-bit FP (with half2 for 32-bit access); mainly for storage of values like sky textures where 11 mantissa bits suffice, not for geodesic integration."),
("What is dim3 used for?",
 "The 3D launch configuration: dim3 grid(64,64), dim3 block(16,16); it conveys blockIdx/threadIdx shapes for image or voxel kernels."),
("How do you convert a vector type to colors in the image buffer?",
 "A float4 pixel (r,g,b,a) writes directly; the import kernel then passes these to the tone-mapping kernel as float4 buffers end to end."),
("What memory-buttons do vector types hide?",
 "Intrinsics like __ldg (read-only cache) and the vector loads (v4) are compiler-generated; profile first, then consider __restrict and padding."),
("How do you make a vector-poC struct for the geodesic state?",
 "Store state as float4 (t, r, theta, phi) and float4 (pt, pr, ptH, pphi) - the whole state fits two 16-byte variables that stay in registers."),
("What is the alignment rule of thumb?",
 "Per-array stride must be a multiple of the natural alignment of the largest element; keep every stride at least 16 bytes and avoid odd padding in images."),
("When is it wrong to use vector types?",
 "When each lane stores a different quantity (a locate-equality where float4 wastes 3 lanes) - use scalar types then and rely on the compiler to assemble warps."),
],
"01-CUDA/15-Atomics": [
("What is a CUDA atomic operation?",
 "A read-modify-write to a memory location executed as an indivisible unit (e.g., atomicAdd), preventing data races when many threads update the same address."),
("Why might a raytracer need atomics?",
 "When the observation mapping is 1:1 (one thread per pixel) you need none; they appear when multiple rays accumulate into the same pixel or when building histograms."),
("What is atomicAdd's behavior on floats?",
 "atomicAdd(&f, val) performs a read-add-write atomically in L2; ordering is nondeterministic across threads, so summed results can vary run to run - a determinism concern."),
("What is the cost of atomics?",
 "For scattered updates to a single address, atomics serialize into contention; many rays adding into one pixel can bottleneck - the anti-pattern to avoid by construction."),
("When do you legitimately need atomicAdd in rendering?",
 "For Monte Carlo accumulating samples when screen-space mapping is not 1:1 (e.g., splatting), or building brightness histograms for exposure."),
("What is the alternative to atomics for pixel accumulation?",
 "Reserve per-pixel accumulators with one thread per pixel/racing through a grid-stride and writing its sample directly to its own slot - no atomics at all."),
("What is the memory visibility contract of atomics?",
 "Global atomics are visible after synchronization and imply coherence with other threads' reads of the same cache line; they do not order arbitrary memory - use __threadfence when needed."),
("What is atomicCAS and what can you build with it?",
 "Compare-and-swap is the primitive lock: you can implement counted reductions, locks, and lock-free data structures; common in particle/grid code rather than ray tracers."),
("What are the integer atomics on the GPU?",
 "atomicAdd/Sub/Max/Min/And/Or/Xor/Exch/CAS on int/long/unsigned; used for counting (rays per region) and grid-buffer bookkeeping without locks."),
("How does atomicAdd order affect Monte Carlo noise?",
 "Each sum order introduces rearrangement noise (a few ulps); for statistical renders it is invisible, for golden-image determinism it is disqualifying."),
("What is the L2-resident atomic behavior?",
 "Atomics operate on the L2 point of coherence; performance depends on whether the target addresses stay within one L2 slice and avoid DRAM traffic."),
("How do you get determinism with atomics anyway?",
 "Sort or generate the update order deterministically (e.g., write to a buffer then reduce with a fixed-order kernel) so the same values always land the same way."),
("When would a histogram need atomics?",
 "Tone mapping computes exposure from a brightness histogram; binning every pixel once via atomicAdd is cheap and monotonic enough - the canonical use."),
("What is the recommended policy for a black-hole renderer?",
 "Keep the geometry 1:1 (no accumulation atomics), reserve atomics for cheap metadata (ray counters, histogram bins, error buffers), and verify determinism in tests."),
("How do you detect accidental atomic races?",
 "compute-sanitizer --tool racecheck reports unsynchronized reads/writes; run it on small frames to fingerprint concurrency bugs."),
],
"01-CUDA/16-Common-Kernel-Patterns": [
("What are the canonical CUDA kernel patterns?",
 "Element-wise map, grid-stride-reduce, transpose/tile, stencil, scan, scatter/gather, and atomic-accumulate: the seven shapes most device kernels reduce to."),
("Which pattern does a raytracer use?",
 "Map plus gather: one thread per pixel samples state from a 3D field (gather) and writes one pixel (map) - embarrassingly parallel with zero communication."),
("What is the transpose/tile pattern?",
 "Reading a row and writing a column via shared-memory tiles to make both coalesced - the pattern behind rotation and blocked memory transforms (not used by the tracer)."),
("What is the stencil pattern?",
 "Each output depends on a neighborhood of inputs (e.g., box blur in tone mapping); it maps to a shared-memory tile with halo cells."),
("What is the reduction pattern?",
 "Pairwise combining (sum/max/min) over a block with shared memory or warp shuffles - used for histogram exposure and error metrics across the frame."),
("What is the scan (prefix-sum) pattern?",
 "Consecutive cumulative operations building exclusive/inclusive scans; used in stream compaction (e.g., keeping only surviving rays)."),
("What is gather vs scatter in raytracing?",
 "Gather: ray reads the field at interpolated cells (no writes to neighbors). Scatter: splat a photon into many pixels (needs atomics) - prefer gather by design."),
("How do you decouple geometry from the launch grid?",
 "The grid-stride loop lets any kernel run over any number of rays N regardless of gridDim, keeping pattern code reusable across resolutions."),
("Why structure kernels by pattern?",
 "Patterns carry known correctness and optimization templates (coalescing, tiling, reduction trees), so mapping your kernel to a pattern gives tested recipes."),
("How does the number of kernels grow in the pipeline?",
 "Import, sample-grid-build, trace, tone-map, reduce-exposure, write-PNG - six or seven small kernels, each one a small variant of a standard pattern."),
("What is a kernel launch batching pattern?",
 "Grouping multiple small transforms into fused kernels (trace+accumulate) to cut launch overheads when total kernel time approaches launch latency."),
("What is a scatter-free histogram pattern?",
 "Each thread bins a pixel with one atomicIncrement on a small fixed histogram - deterministic enough for exposure and far simpler than exact scans."),
("What is a warp-basis pattern benefit?",
 "Because all four of the warps run the same instruction stream on different data, patterns that align memory across the warp (coalesced) min transactions."),
("How do you keep pattern code testable?",
 "Expose each pattern as a pure function taking buffers and sizes, with host-side reference implementations of the same function for A/B validation."),
("What is the pipeline-stage pattern for animation?",
 "A fixed loop: (import frame i) async, (trace) while importing i+1, (tone) while tracing, (write) while toning - four stages overlapped like a factory line."),
]}