"""Curated Q&A for 11-End-to-End leaves."""
END = {
"11-End-to-End/01-Total-Pipeline-Overview": [
("What is the total end-to-end pipeline?",
 "GRMHD simulation data -> converter -> field volume on GPU -> camera setup -> geodesic ray tracing -> radiative transfer -> image/spectrum -> post-processing/analysis - a single data flow from MHD snapshot to science image."),
("What are the stages in order?",
 "1) Run/obtain the GRMHD simulation; 2) convert snapshots to the renderer's field format; 3) load fields + geometry onto the GPU; 4) trace geodesics per pixel; 5) integrate emission/transfer; 6) synthesize image/spectrum; 7) post-process and validate."),
("Where does each stage live in the repo?",
 "simulation: external (HARM/Athena++); converter: utils/grmhd2blob; GPU scene load: ray::Scene; tracing+transfer: ray::integrator/radiative; image: ray::render; analysis: tools/. Each has its own test surface."),
("What are the data contracts between stages?",
 "SCENE: (grid params, arrays, metadata); CAMERA: (position/aim/fov/bands); RAY-RESULT: (termination, redshift, I/Q/U/V); IMAGE: (bands, WCS, flags) - typed structs so stages compose cleanly."),
("What is the minimal useful pipeline?",
 "Analytic Schwarzschild scene -> geodesics -> shadow-only image (no emissivity) -> false-color frame - the honest 'nothing else works yet' baseline."),
("How do you verify the WHOLE pipeline once?",
 "Run a golden end-to-end: analytic scene at fixed seed; assert image checksum, ring radius, and spectral total match the checked-in golden - catches cross-stage slips."),
("What is the pipeline's error handling?",
 "Fail fast at validation (config/scene sanity), warn at runtime (tolerance, floor usage), and record everything in the run manifest - errors never silently corrupt."),
("How is the pipeline made cross-platform?",
 "CUDA for compute, CMake+ctest for build/test, ffmpeg/EXR for media, YAML for config - each stage's tool is a lexical boundary with a clear contract."),
("What is the pipeline's performance profile?",
 "Geodesics dominate wall time; transfer emission second; conversion/upload amortized. Budget ~10% to convert+upload, 70%-80% to tracing, 10%-20% to transfer+post."),
("How does the pipeline compose with real data?",
 "The converter reads HDF5/FITS from HARM/Athena++ and writes the internal blob - same render kernels, new data path - the design that future-proofs."),
("What is the summary?",
 "The end-to-end pipeline is a typed data flow from MHD state to telescope-ready image - validated at each contract, golden-tested end to end."),
],
"11-End-to-End/02-Importing-GRMHD-Data": [
("What files do you import?",
 "GRMHD dumps: (rho, u^i, B^i, p) + grid coordinates + metadata (M, a, units, time) - typically HDF5 or FITS from HARM/Athena++ output."),
("What does the converter do?",
 "Parse the dump, extract fields, map coordinates to the renderer's (log-r, theta, phi) grid, convert code units, and write the internal blob + a scene JSON."),
("How do you handle the staggered vs centered fields?",
 "HARM/Athena++ store some fields off-center (B on faces); either interpolate to cell centers at conversion or store both offsets - decide once, document."),
("What units must be converted?",
 "Code units -> physical: density via the mass scale, fields via sqrt(Mdot)-ish normalization, temperatures via the EOS - the mass/units map lives in one converter file."),
("How do you validate an import?",
 "Round-trip: the blob's interpolated field at cell centers must equal the original snapshot's cell values to tolerance (a histogram comparison) - the golden import test."),
("What metadata must ride with the blob?",
 "Simulation provenance (code, version, snapshot time), grid geometry, units, M/a, floors used, and the checksum - the scene record's mandatory fields."),
("What about out-of-domain cells?",
 "Cells outside the simulation grid (e.g., r < r+ or beyond r_max) get a 'background' policy (floor/zero) recorded per-cell in a mask - transparency in the render."),
("How do you handle multiple snapshots (movies)?",
 "Import once per snapshot into its own blob; a scene sequence JSON lists them with times - the movie mode reads times, not separate code paths."),
("What if the snapshot uses Kerr-Schild but you render BL?",
 "Either convert coordinates at import (BL cells = remapped KS) or carry the chart label and convert on interpolation - the coordinates must be machine-explicit in the blob."),
("What is the import's failure mode?",
 "A missing array, bad metadata, or unit mismatch surfaces as hard validation errors at load - never partial scenes."),
("What is the summary?",
 "Importing GRMHD data = convert dumps to a typed field blob with coordinates, units, and provenance - validated by round-trip and metadata checks."),
],
"11-End-to-End/03-Interpolating-Fields": [
("How are fields sampled along rays?",
 "Each ray quadrature point converts to grid coordinates, then trilinear (or octree) interpolation of rho, B, Te from the scene blob - the field-sampling core."),
("What fields does the raytracer need per sample?",
 "rho (density), B (3 spatial components + comoving b), T_e (electron temperature) - the three columns that drive emissivity; plus the velocity u^i for beaming."),
("What is the coordinate transform per sample?",
 "From the ray's (r, theta, phi) to the grid index space: log-r maps via dx = d(ln r), theta/phi linearly - three cheap index+fraction computations."),
("How accurate is the interpolation?",
 "Trilinear is 2nd-order; on well-resolved GRMHD grids the interpolation error is below the run's statistical noise - the mesh's resolution, not the sampler, dominates."),
("How do you handle the polar and inner boundaries?",
 "Pole: wrap phi/averaging; inner boundary (jump to horizon): clamp/mask; the policies are implemented once in the same 'field_policy' module as the import mask."),
("What does B-field interpolation need beyond scalars?",
 "Vector interpolation must keep b^mu a proper comoving field at the sample - interpolate the Cartesian-ish components then rebuild b at the point (no frame mixing)."),
("How is the field cached for performance?",
 "The blob lives as device 3D textures/arrays (filtrer-linear); the trilinear sampler chains hardware-fetched coordinates - the hot-loop field path."),
("How do you validate field sampling?",
 "Interpolate a synthetic analytic field (linear in coordinates) and assert exact recovery; sample actual snapshot cell centers and compare to the cell averages."),
("What is the octree/AMR field variant?",
 "If the sim exports an AMR tree, import it as an octree of leaves; sampling descends per-node bounding boxes (with the empty-cell pruning) - the sparse field path."),
("What is the summary?",
 "Field interpolation turns the blob into a smooth, queryable emission volume - trilinear/octree sampling, B-frame consistency, boundary policies, and validation by synthetic fields."),
],
"11-End-to-End/04-Fluid-to-Photon": [
("What is the fluid-to-photon step?",
 "Converting the sampled GRMHD state (rho, B, T_e, u) at each ray point into emissivity/absorption coefficients j_nu and alpha_nu - the physics bridge."),
("What emissivity models are supported?",
 "Thermal synchrotron (+ power-law/kappa tails), bremsstrahlung, and the hybrid mixture; selected by a --emission model flag - each a self-contained formula."),
("How does the rest-frame requirement appear?",
 "j and alpha are computed in the comoving frame from b^mu and T_e; the observed conversion uses the frame factor delta - the frame discipline from the 03-Relativity content."),
("What is the frequency dependence?",
 "j_nu and alpha_nu evaluated at the local emitted frequency (shifted from the observation band by the ray's redshift factor) - the frequency map rides the ray."),
("How do the GRMHD fields enter the emissivity?",
 "n_e from rho (+ EOS), B from the comoving field, T_e from the closure - the same three columns sampled along the ray, every quadrature point."),
("How are beaming and pollution applied?",
 "The delta factor boosts the rest-frame intensity; absorption accumulates as exp(-tau) - the formal solution of the RTE applied differentially per segment."),
("How do you validate a specific emissivity?",
 "In a uniform homogeneous cell: the code's j/alpha must match the analytic emissivity formula for that model to per-mille - a per-model unit test."),
("What is the frame-true check?",
 "A static isotropic emitter must render azimuth-INDEPENDENT intensity: any directional structure means a frame/beaming bug - the go-to fluid-to-photon gate."),
("How does the fluid-to-photon setting scale with resolution?",
 "Per-ray-point, not per-cell: cost ∝ quadrature points; the sampler's adaptive step size controls both geodesic accuracy and emission accuracy."),
("What is the summary?",
 "Fluid-to-photon is the physics adapter: rest-frame emissivity models fed by sampled fields at the shifted frequency, with the beaming/delta and absorption applied - validated per model and per frame."),
],
"11-End-to-End/05-Schwarzschild-Validation": [
("What does the Schwarzschild end-to-end validation prove?",
 "That metric, geodesic integrator, capture detection, and shadow rendering all agree with the closed-form Schwarzschild solution - the project's bedrock test."),
("What are the specific checkable quantities?",
 "Shadow boundary at b = 3 sqrt(3) M (circular), ring at the photon-sphere footprint, deflection 4M/b weak-field, and the redshift map z = sqrt(1-2M/r) for static emitters."),
("How do you check the shadow boundary numerically?",
 "Scan the image plane for the capture/scatter boundary at high supersampling; fit the closed circle - the radius must equal 3 sqrt(3) M to sub-pixel."),
("How do you validate the photon ring?",
 "Render the analytic scene and measure the ring diameter vs the analytic photon-sphere position; the second bright ring (~3-4x thinner) verifies the sub-ring ladder."),
("What is the deflection validation?",
 "Trace rays at large impact parameter b >> M and measure the arrival deflection against delta = 4M/b; the match to 1% in the weak field is the low-curvature gate."),
("What is the redshift validation?",
 "With a static emitter sphere, per-pixel 1+z must equal the analytic g_00 factor for the emitter's radius - the strongest check of the frame/shift machinery."),
("How do you validate the beaming-free case?",
 "A static, axisymmetric source renders azimuthally symmetric: any crescent asymmetry at a=0 is a Doppler/frame bug - the cleanest single-flag test."),
("What does the validation write for files?",
 "A JSON report: measured vs analytic shadow radius, ring ratios, deflection table, and redshift checksums - the machine-readable gate of the release pipeline."),
("How is the test wired?",
 "As a ctest case 'validate_schwarzschild' that fails unless all tolerances pass; it runs in CI on every merge - the physics stays honest by construction."),
("What is the summary?",
 "Schwarzschild validation is the closed-form anchor - shadow circle, photon ring, weak-field deflection, static redshift/beaming - all asserted numerically in CI."),
],
"11-End-to-End/06-Kerr-Validation": [
("What does the Kerr end-to-end validation prove?",
 "That spin geometry (frame dragging, ergosphere, asymmetric shadow, prograde/retrograde rings) renders correctly - the scientific core beyond Schwarzschild."),
("What are the Kerr-specific checks?",
 "Shadow shape (crescent offset/spin-image), prograde/retro photon-ring bands, ZAMO frame dragging, and the conservation of E, L, Q along integrated rays."),
("How do you check the Kerr shadow shape?",
 "The analytic boundary curve (via the Carter-potential b_crit(gamma) at spin a) overlaid on the render must match to sub-pixel across the full silhouette."),
("How do you validate the photon-ring asymmetry?",
 "The prograde ring radius < 3M < retrograde ring radius (a>0); measure both from a radial intensity cut and compare with the analytic r_ph(a) formula."),
("How is frame dragging tested?",
 "A ray launched with p_phi=0 at the equator must drift in phi by the ZAMO omega(r) dt along its path - the metric's t-phi term verified kinematically."),
("How do you validate the conserved quantities?",
 "E, L, Q drift must stay at integration tolerance along long rays - the integrator's correctness certificate that Kerr geodesics are integrable."),
("How do you test the ergosphere region?",
 "A probe with proper observer conditions inside the ergosphere must show the ZAMO's required omega exceeding the light-like speed bound - the ergosphere knows where it is."),
("What does the isco-change check confirm?",
 "At high spin, the innermost stable orbit shifts inward (prograde); the disk-truncation geometry in renders must follow the analytic ISCO(a) curve."),
("How is the spinning-version CI gate built?",
 "A 'validate_kerr' ctest (a=0.5, a=0.9) with the shadow ellipse fit, ring-ratio, and drift thresholds - runs alongside the Schwarzschild gate on every merge."),
("What is the 'any-spin mirrors a=0' check?",
 "At a=0 the Kerr pipeline must EXACTLY reproduce the Schwarzschild results (shadow circle, ring radius) - the continuity that guards a regression."),
("What is the summary?",
 "Kerr validation extends the closed-form anchors to spin: shadow boundary curve, ring asymmetry, frame dragging, invariants, ISCO, and the a=0 continuity limit."),
],
"11-End-to-End/07-Render-First-Frame": [
("What is the 'first frame' milestone?",
 "A single valid image from the pipeline on an analytic scene - shadow-on-starfield, no disk yet - proving the whole pipe from camera to image works end to end."),
("What is the recommended first scene?",
 "A Schwarzschild hole with a background star field: rays miss -> stars, capture -> shadow, near-critical -> ring - every termination type exercised."),
("What resolution/sample do you start with?",
 "512x512 at 4 samples/px on CPU (or 1 GPU) - a <10s render that still shows the ring and shadow; the shot is a debugging artifact, not production."),
("What should the first frame show?",
 "A perfect black circle (shadow) of radius 3 sqrt(3) M pixels with a thin bright ring outside, and undistorted stars beyond - each element verifies one pipeline stage."),
("What order do you debug in?",
 "Stars straight (M=0) -> shadow round (M>0, capture) -> ring thin (photon sphere) -> stars wrapped (lensing) - one observation per debug step."),
("How do you check correctness by eye?",
 "The shadow must be EXACTLY circular for a=0: an ellipse or offset is a metric/initialization bug; the ring must hug the shadow radius - eyeballs catch what CI covers slowly."),
("What metadata does the first frame carry?",
 "The full config hash, seed, resolution, and the attached validation numbers (shadow radius, ring position) - the image's birth certificate."),
("How is the first movie framed from there?",
 "Reuse the same scene with an orbiting camera or evolving emissivity - once the still is right, the dynamics inherit the same correctness."),
("What is the definition of 'first frame done'?",
 "The checked-in golden image passes asserts: shadow radius within 1e-6 relative, ring present, starfield distortion matches the analytic lensing - CI 'first_frame' green."),
("What is the summary?",
 "The first frame is the pipeline's baptism: shadow-on-starfield at 512x512, visually correct and CI-asserted, proving every stage before adding any disk emission."),
],
"11-End-to-End/08-Make-a-Movie": [
("How do you make a movie end to end?",
 "Render N frames (fixed camera rotating slowly, or evolving GRMHD snapshots), then ffmpeg-encode to mp4 - the frame loop + encoder both use the config system."),
("What camera path is standard for a first movie?",
 "An azimuthal orbit around the hole at constant radius/inclination over one orbit - beaming and ring dynamics read clearly without moving the physics."),
("What is the frame-to-frame budget?",
 "Each frame is a full render; reuse the static geometry (uploaded once) and only the emission/camera changes - 100 frames of 1024^2 is the sensible first movie."),
("How do you keep a movie stable?",
 "Fixed seed per frame (stratified supersampling), fixed config, and a manifest of times - otherwise inter-frame noise corrupts the science claims."),
("What temporal sampling matters for GRMHD?",
 "Frame cadence should resolve the innermost orbital timescale (~ 10-50 M); snapshot cadence from the sim must exceed it or the disk aliases."),
("How do you encode?",
 "24fps mp4 via libx264 CRF 16 for review; EXR/PPM sequence retained for science - the 'delivery vs master' split from the Production content."),
("What does the first movie show (Schwarzschild still)?",
 "The ring's brightness does NOT flicker with a static analytic disk - a baseline: movies gain dynamics only when emissivity or camera moves."),
("What is the checklist of a correct movie?",
 "No inter-frame flicker (fixed seed), shadow fixed at center, ring steady, disk features orbiting at the Keplerian rate - each checked over a few frames."),
("What is the summary?",
 "Making a movie = parameterized frame loop + encoding, with fixed seeds/per-frame manifests, and correct cadence relative to the disk's timescales."),
],
"11-End-to-End/09-Compare-to-Real-Images": [
("How do you compare your render to a real EHT image?",
 "Convolve the render with the array beam, in physical units (Jy/arcsec), then compute image-space residuals or the m-ring summary against the published image."),
("What is the first clean real-image to mimic?",
 "The M87* 2019 ring (230 GHz): a fit-quality target where renderers must reproduce the ~42 microarcsec diameter and crescent brightness within beam limits."),
("What summary statistics carry the comparison?",
 "Ring diameter, fractional width, total flux, asymmetry (bright-to-faint), and the polarization maps - the m-ring (radius/width/asymmetry) parametrization is standard."),
("How do you handle the ensemble nature?",
 "GRMHD is time-variable: compare the DISTRIBUTION of renders (over snapshots/model grid) to the observation, not one lucky frame - the honest statistical test."),
("What does a 'fit' actually tune?",
 "Spin a, inclination, electron-temperature closure, MAD/SANE choice, accretion rate - each shifts the ring/morphology in a distinct way the fit marginalizes."),
("What is the key null test?",
 "A Schwarzschild (a=0) face-on-ish render vs M87*'s crescent: a zero-spin model cannot reproduce the observed asymmetry - the fit's spin lever is cheap to test."),
("How do you quantify agreement?",
 "Residual chi-square over the image plane (beam-normalized) or the m-ring metrics' overlap - with a bootstrap on the sim snapshots for honest error bars."),
("What pitfalls bias the comparison?",
 "Wrong beam, missing scattering (Sgr A*), floors dominating the funnel, and single-frame overfitting - each has a documented mitigation in the pipeline."),
("What is the winning loop?",
 "Render -> blur -> summarize -> compare -> adjust (spin/inclination/model) -> repeat - an automated grid search once the pipeline is validated."),
("What is the summary?",
 "Comparing to real images is the scientific consummation - beam-honest, ensemble-aware, summary-statistic comparisons with degenerate-model marginalization."),
],
"11-End-to-End/10-Performance-Budgeting": [
("What is performance budgeting?",
 "Spending the render budget deliberately: resolution, supersampling, tolerance, and model choice each cost time/memory - the budget table is the engineering contract."),
("How much does each quality knob cost?",
 "Resolution: quadratic in pixels; supersample: linear in rays; tolerance trash: superlinear near the ring; emission model: per-ray-point cost - document the multipliers."),
("What is the reference budget for a still?",
 "1024^2 at 8 rays/px with adaptive RK45 (~1e-9): tens of seconds to ~2 min on a single data-center GPU - the anchor against which knobs are scaled."),
("What scales for a movie?",
 "Frames multiply linearly; the geometry/field upload amortizes to near-zero in the loop - a 100-frame movie ≈ 100 stills minus the single upload cost."),
("What is floor-cost analysis?",
 "Field upload (GBs) + start-up converter: minutes to load a big blob vs milliseconds to render - EFFICIENT caching/reuse is the difference between 'fast demo' and 'skipped'."),
("How do you measure and report?",
 "Per-stage timers (ingest, integrate, transfer, post) logged per run; a budget table per configuration in the report - performance measured, not assumed."),
("What leverages the biggest speedups?",
 "Geodesic reuse across frames (static geometry), octree empty-culls, reduced variable-count integration where valid, and single-upload blob architecture - order by impact."),
("What is the 'budget vs quality trade table'?",
 "A documented matrix: e.g., 512^2 at 4x = 'sketch'; 1024^2 8x = 'standard'; 4k 32x = 'archive' - users pick a tier, engineers protect the tiers' cost."),
("When do you accept approximation?",
 "Thin-limit transfer, spherical-source emissivity, coarse supersample in background pixels - each documented as an approximation with a bound, never silent."),
("What is the summary?",
 "Performance budgeting turns 'how fast' into a deliberate model: tiered quality/cost tables, per-stage timers, amortized uploads, and measured reports."),
],
"11-End-to-End/11-Milestone-Roadmap": [
("What is a sensible milestone roadmap for the project?",
 "M1 analytic shadow, M2 starfield lensing, M3 analytic disk, M4 real GRMHD scene, M5 spectra/polarization, M6 movies, M7 validation suite, M8 production packaging - shipped in that order."),
("What is M1 (analytic shadow)?",
 "Schwarzschild shadow + photon ring from a pure geodesic render: proves metric, integrator, capture, and image output - the physics foundation."),
("What is M2 (lensing)?",
 "Starfield + analytic bending: proves the far-field lensing/deflection and the sky-map - the visual heart before any emission is added."),
("What is M3 (emission)?",
 "An analytic emissivity model (thermal synchrotron on a simplified disk) with redshift/beaming: proves fluid-to-photon in a controlled setting."),
("What is M4 (GRMHD)?",
 "Ingest a real snapshot (HARM-like), run the emissivity on it, render: proves converters, interpolation, and volume emission - the scientific stage."),
("What is M5 (photons)?",
 "Spectra synthesis + polarization channels (Q/U/V, Faraday): proves the frequency and Stokes machinery beyond monochromatic intensity."),
("What is M6 (dynamics)?",
 "Movies from evolving snapshots with camera paths: proves multi-frame reuse, checkpointing, and the encode pipeline."),
("What is M7 (science suite)?",
 "Schwarzschild + Kerr analytic validation, convergence, determinism tests wired to CI: proves the tool is trustworthy for claims."),
("What is M8 (production)?",
 "Packaging: containers, CLI stability, docs, performance budgets, release artifacts: proves it is usable by others - the project's completion contract."),
("How do you sequence within a milestone?",
 "Each milestone ends with a shippable artifact and its test; never start M4-plus until M1-M3 pass the golden gates - dependency discipline."),
("What is the summary?",
 "The roadmap is M1..M8: geometry -> lensing -> emission -> real data -> spectra/polarization -> movies -> validation suite -> production packaging, each a tested milestone."),
],
"11-End-to-End/12-Glossary": [
("What is the affine parameter?",
 "A monotonic parameter (lambda) along a geodesic with no preferred scale for null rays; the integrator's independent variable."),
("What is the impact parameter?",
 "b = L/E - the ratio of angular momentum to energy; for null rays it parametrizes the orbit family and the image-plane radius."),
("What is the photon sphere?",
 "The unstable constant-r null orbit radius (3M for Schwarzschild, spin-split in Kerr) that produces the bright ring caustic."),
("What is the shadow?",
 "The image-plane region from which null rays are inevitably captured - appears dark against a bright background."),
("What is the ergosphere?",
 "The region outside the Kerr horizon where observers cannot remain static; the frame-dragging choreographer of the near field."),
("What is frame dragging?",
 "Inertial-frame rotation induced by angular momentum - the t-phi metric coupling that drags photon orbits and beaming."),
("What is a Boyer-Lindquist vs Kerr-Schild chart?",
 "Two coordinate systems for Kerr: BL standard for analytics but singular at the horizon; KS regularized for safe integration."),
("What is the Carter constant?",
 "The fourth invariant (besides E, L, mass) of Kerr geodesics, arising from the Hamilton-Jacobi separability."),
("What is the GRMHD state?",
 "The snapshot's primitive fields (rho, p, u^i, B^i) from the simulation - the renderer's base emission data."),
("What are the RTE quantities?",
 "j (emissivity), alpha (absorption), I (intensity), tau (optical depth), and the Stokes vector (I, Q, U, V) with Faraday rotation."),
("What is the Doppler factor?",
 "delta = 1/(gamma(1 - beta mu)) - relating observed to emitted frequency for a moving source; drives beaming and shift."),
("What is the synchrotron turnover/SSA?",
 "Where optically thin and self-absorbed emission cross - the spectral peak whose position encodes B and T_e."),
("What is MAD vs SANE?",
 "Magnetically arrested vs standard flows: the strong-field/weak-field regimes that set jet power and ring morphology."),
("What is ISCO?",
 "The innermost stable circular orbit (~6M Schwarzschild, spin-dependent in Kerr) - the inner edge of stable disk orbits."),
("What does the total glossary enable?",
 "A shared vocabulary from the Relativity to the Production modules - the reference the whole documentation and discussion converge on."),
]}