"""Curated Q&A for 04-GR-Ray-Tracing leaves."""
GRT = {
"04-GR-Ray-Tracing/01-Ray-as-Geodesic": [
("What is a ray in GR ray tracing?",
 "A null geodesic: the path of a photon through curved spacetime, a curve with ds^2 = 0 whose tangent vector is parallel transported along itself."),
("Why do we trace geodesics backwards from the camera?",
 "Rays originate from the camera and are run into the scene; backwards (retrograde) tracing guarantees each image pixel receives exactly one ray and avoids losing photons."),
("What is the relation between a worldline and a rendering?",
 "Each image pixel corresponds to a bundle of null geodesics leaving the camera; integrating one representative photon per pixel assembles the whole image, outer-nulled."),
("How do you initialize a ray?",
 "At the camera event set position and 4-momentum: p_mu computed from the pixel direction times a scale chosen so p^mu p_mu = 0; E fixed sets the overall scale."),
("What does the affine parameter represent for a photon?",
 "lambda parametrizes the traversal; it is not proper time (photons have none) but a monotonic coordinate along which positions and momenta evolve smoothly."),
("How do you detect the ray's end?",
 "The ray terminates on a hit (reaching the emitting surface/disk), capture (crossing the horizon), or miss (exiting a bounding sphere at r_max)."),
("What is the first requirement for an integrator?",
 "Preserving the null constraint p^2 = 0 within tolerance along the whole path - any drift in the null condition is evidence of numerical error, not physics."),
("How does the geodesic property translate to code?",
 "The tangent vector obeys the geodesic equation; integration advances (x^mu, p_mu) in tandem so the stated null/mass-shell condition stays satisfied."),
("What is the retrograde-scatter symmetry?",
 "Running rays backward from observer to source is equivalent to forward emission - the adaptive rays never know which direction is 'real' because null geometry is time-symmetric."),
("What precisely is meant by a geodesic in terms of the affine connection?",
 "A curve whose velocity u satisfies u^mu;nu u^nu = 0 - the parallel-transported velocity; in coordinates that is x'' + Gamma x'x' = 0."),
("What is a per-pixel bundle and supersampling?",
 "Each pixel samples its direction with multiple rays (e.g., stratified 4x) to average the chaotic lensing - the improvement that makes shadow edges smooth."),
("How do you know the ray 'reaches' the emitter?",
 "Intersections with the disk's 3-surface (e.g., equatorial theta=pi/2 + geodesics of radius r) are tested as the path steps; the first intersection wins."),
("What is the numerical termination condition near capture?",
 "When r < r_able (horizon radius in chart coordinates) plus a margin, the ray is marked 'captured', contributes to the shadow, and stepping halts."),
("Why must adaptive step sizes kick in near strong-field regions?",
 "The trajectory's curvature grows near the photon sphere; fixed-step tracing there produces systematic shadow-ring errors - adaptivity maintains accuracy."),
("What is a validation ray set?",
 "A golden grid: equatorial circular orbits, radial in/out, sky-scan impact parameters; each checks a closed-form relation (deflection, timers, shadow boundary)."),
("How many rays does a production frame need?",
 "With supersampling ~16-64 rays/pixel, a 4k frame is tens of millions of geodesics - the whole engine's cost centers on efficient null-geodesic stepping."),
],
"04-GR-Ray-Tracing/02-Lagrangian-Formulation": [
("What is the geodesic Lagrangian?",
 "L = (1/2) g_alpha,beta xdot^alpha xdot^beta (where dot = d/dlambda), whose Euler-Lagrange equations are precisely the geodesic equations."),
("What is the advantage of the Lagrangian for ray tracing?",
 "It yields the equations in a compact, index-free-to-write form and instantly exposes the cyclic coordinates (t, phi) that produce the conserved quantities."),
("Write the Euler-Lagrange equation for a cyclic coordinate.",
 "Since L is independent of x^cyclic, d/dlambda (dL/dxdot^cyclic) = 0, so p_cyclic = dL/dxdot^cyclic is constant - immediately giving E and L."),
("How do you derive r_twice from L for Kerr?",
 "L gives the second-order equations; substitute the Boyer-Lindquist g to get r'' = ... sigma terms; the two-integral-of-motion form then lowers order."),
("What is the null constraint in Lagrangian terms?",
 "2L = g_alpha,beta xdot^alpha xdot^beta = 0 for photons; the Lagrangian itself being zero is the on-shell null condition every valid path holds."),
("How does the Lagrangian handle massive particles?",
 "For massive particles 2L = -1 (with proper-time affine parameter); the same machinery covers them - used when tracing stellar orbits or rotation curves."),
("What is the variation principle statement?",
 "Geodesics extremize S = integral L dlambda among null curves; the Euler-Lagrange solutions are exactly the parallel-transport paths of GR."),
("What is the conserved energy from L?",
 "p_t = dL/dtdot = g_t,alpha xdot^alpha = -E (minus from signature); stationarity -> p_t constant along every null geodesic."),
("What is the conserved angular momentum from L?",
 "p_phi = dL/dphidot = g_phi,alpha xdot^alpha = L_phi-alpha (constant); axisymmetry -> p_phi constant."),
("How do you numerically integrate the L-form equations?",
 "Convert to a first-order ODE system by introducing momenta (Legendre transform) - i.e., pass to the Hamiltonian picture for step-differential integration."),
("What does L's 'recipe' break down at?",
 "Second-order form needs Gamma and is numerically stiff; but it remains the clearest human derivation - keep it for symbolic work and validation."),
("How does the Carter constant enter the L picture?",
 "L alone doesn't expose Q; the separation of the Hamilton-Jacobi equation (not the raw L) reveals the fourth constant - the deeper route to the effective potentials."),
("What is the 'action' of a null curve?",
 "S = integral (1/2) g xdot xdot dlambda = 0 on shell; variations of S = 0 give geodesics - the variational bedrock the finite-element ray methods approximate."),
("How do you define the affine parameter from L?",
 "Set p_affine = dL/dxdot; the momentum definition fixes the affine scale; requiring 2L = 0/eps leaves the scale free (a gauge choice for parametrization)."),
("What is the advantage to validating with L?",
 "The equations derived from L are guaranteed self-consistent (belonging to one action), so testing the numerical solution against conservation laws is a clean error gate."),
],
"04-GR-Ray-Tracing/03-Hamiltonian-Formulation": [
("Write the geodesic Hamiltonian.",
 "H = (1/2) g^mu,nu p_mu p_nu; Hamilton's equations dx^mu/dlambda = g^mu,nu p_nu and dp_mu/dlambda = -(1/2) dg^alpha,beta/dx^mu p_alpha p_beta - the 8-dimensional first-order system."),
("What is the advantage of the Hamiltonian over the Lagrangian?",
 "First-order form is directly RK4-adaptable, needs only the metric (not its Christoffels), and p_mu being states makes conserved quantities explicit and checkable."),
("What is the null condition in H?",
 "H = 0 on each null geodesic; the integrator's job is to keep H tiny, and H's drift is the canonical error metric."),
("How do the momentum equations encode gravity?",
 "dp_mu/dlambda depends on dg/dx^mu; where the metric varies (gravity), p changes - exactly the curve equation of the effective force."),
("What is the metric-gradient computation cost?",
 "Each step needs the 10 metric components and their gradients for the p update - the dominant arithmetic, so a precomputed analytic derivative set speeds integration dramatically."),
("How do you preserve the conserved quantities numerically?",
 "H good + stationarity keeps p_t/p_phi to machine drift; Q is conserved only in reduced form, so general-purpose H integration uses the full 8-D space."),
("How is the step control informed by p^2?",
 "The null residual |2H| = |p^2| bounds the integrator's allowed error per step - a physics-grounded adaptive error estimator."),
("What is the Hamiltonian-Jacobi (HJ) route?",
 "Assume separation S -> the fundamental equation in (r, theta) with constants (E, L, Q); integrating only 2 ODEs is the speedup behind ipole/grtrans-class codes."),
("How does initial-condition scaling work?",
 "The direction vector times E sets p; E only rescales the path parameter, so normalize E=1 and keep b=L ratio as the real variable."),
("What is the time-stepping ambiguity in H?",
 "Step in lambda, producing dt = g^t nu p_nu dlambda; for near-horizon rays dt grows - but the H-form refuses to care, integrating comfortably in lambda."),
("How do boundary conditions match geodesics?",
 "Starting from the camera (position fixed, momentum from pixel) the H system is an initial-value problem in lambda; reducing integration domain decides hits."),
("Why does H integration prefer the metric inverse?",
 "xdot = g^mu,nu p_nu needs the inverse; g and its inverse are paired functions in one analytic block - keep them together in the metric module."),
("What is the sign convention trap in H?",
 "Some authors write H = (1/2) 2p^2 or use signature for the null condition; every sign in H implementations must match the metric's signature sign."),
("How do you verify H integration?",
 "Integrated geodesics must keep p_t and p_phi constant (to double precision) and reproduce the analytic (r,phi) trajectories - the ultimate spot check."),
("What is the memory/efficiency profile?",
 "8 doubles per state x rays in flight: a few GB for millions of ray-cores; per-step cost dominated by metric+derivative evaluation cache hits."),
],
"04-GR-Ray-Tracing/04-Null-Geodesics": [
("What is a null geodesic?",
 "A geodesic with zero interval, ds^2 = 0, the path of a massless particle (photon); its tangent is lightlike at every event."),
("Why are all these effects described by null geodesics exclusively?",
 "Light is massless, so only null rays matter for imaging; massive trajectories (disks, orbits) are used for emission but are timelike geodesics instead."),
("What mathematical property makes null geodesics the basis?",
 "They are the extrema of the geometric path length among null curves; the physical statement is Fermat's principle in curved spacetime."),
("How is the null condition imposed on initial data?",
 "The photon's 4-momentum must satisfy g_mu,nu p^mu p^nu = 0; code constructs this by normalizing the spatial direction with E."),
("What does 'H=0' mean for the affine parameter?",
 "The affine parameter for null geodesics is only defined up to scale; H=0 forbids proper time, but that's fine - lambda remains a valid integration coordinate."),
("How do null geodesics specify the shadow?",
 "Null rays with low impact parameter cross the horizon (capture); the boundary between capture and escape in image space is the shadow edge."),
("What is the photon ring in null language?",
 "The unstable null orbits at r ~ 3M: null geodesics that linger there wind many times, producing the bright rings in images."),
("How do you numerically preserve nullness?",
 "Use symplectic/geodesic-accurate integrators and check |2H| per step; adaptive schemes keep the residual at roundoff, preserving the null shell."),
("What is the equivalence of null geodesics to bending?",
 "Every bending angle, multiple image, and redshift is a consequence of one family of null equations - no separate lensing model needed."),
("What happens to the null ray at the horizon?",
 "In smooth coordinates it crosses r+ with finite lambda; in Boyer-Lindquist its t and r coordinate flip, so the capture check must use r < r+."),
("What is the radial turning point for a null ray?",
 "The closest approach r0 where rdot = 0; solving the effective equation for r0 as function of b and the angle determines deflection - the lens map."),
("What is the 'impact parameter' - null geodesic dictionary?",
 "b = L/E; every observable (deflection, shadow boundary, ring position) is a function of b - the fundamental scalar of null geometry."),
("What is the self-similar ring structure?",
 "Null geodesics that wind n half-turns produce images n orders fainter; the ratio of successive ring radii tends to the large-winding geometric limit e^(-2pi)."),
("How do you validate null geodesics?",
 "Reproduce: deflection 4M/b (weak), circular orbit at r=3M (a=0), and the shadow boundary at b=3sqrt(3)M - the three canonical null tests."),
("What does polarization/null coupling add?",
 "Polarization is parallel-transported along the null ray (with the Faraday rotation in the GRMHD plasma); a fully physical code tracks the polarization basis along null geodesics."),
],
"04-GR-Ray-Tracing/05-Boyer-Lindquist-Coordinates": [
("What are Boyer-Lindquist coordinates?",
 "The standard (t, r, theta, phi) chart for Kerr spacetime, with the metric's familiar 5-component form; the workhorse for analytic Kerr geodesics."),
("What are the metric's nonzero components?",
 "g_tt, g_rr, g_theta,theta, g_phi,phi, and g_t,phi (plus symmetric mirror) - 5 independent; the t-phi term encodes frame dragging."),
("What is Delta and Sigma?",
 "Delta = r^2 - 2Mr + a^2, Sigma = r^2 + a^2 cos^2 theta; Delta vanishes at the horizons r_+/- (coordinate singularity), Sigma at r=0."),
("What is the Boyer-Lindquist horizon radius?",
 "r_+ = M + sqrt(M^2 - a^2); the code detects capture via r < r_+ in this chart."),
("What is the disadvantage of Boyer-Lindquist near the horizon?",
 "Delta -> 0 makes the r-coordinate path integrate slowly/cross-coupling; numerical integration typically switches to Kerr-Schild (toroidal) near r+."),
("What is the advantage for analytics?",
 "Every known closed-form (photonsphere, shadow, effective potential) is written in Boyer-Lindquist; keep them in this chart for validation."),
("Where is the ergosphere in these coordinates?",
 "g_tt = 0 at r_erg(theta) = M + sqrt(M^2 - a^2 cos^2 theta), the positive locus; the region between r+ and r_erg is the ergosphere."),
("How do you convert Kerr-Schild back to Boyer-Lindquist?",
 "Time t -> t - t_KS plus radius transform; implement the two named transforms as exact functions with unit tests (identity roundtrips)."),
("What are the angular coordinate conventions?",
 "theta in [0, pi], phi in [0, 2pi), singularity at the axis; images sample theta=pi/2 (equator) by default for the disk."),
("How does the code handle Delta zero-condition?",
 "Never divide by Delta directly in production integration; the t-phi r pieces either use the KS chart or skip via the cross terms - safe coding discipline."),
("What is the timelike/t = infinity limit?",
 "g_t,phi -> 0 and g -> Schwarzschild as a -> 0 and r >> M; both limits in one place - the metric's consistency gate."),
("How do you compute radial turning points in BL?",
 "V_r(L,E,Q) with BL's sigma factors; analytic roots pin the photon-sphere shadow boundary precisely in this chart."),
("What is the photon orbit in BL language?",
 "The solution rdot=0 with a double root; the equations give r_ph for prograde/retrograde at given a - used to predict ring positions."),
("What is the local frame in BL?",
 "The BL ZAMO has 4-velocity t-proportional with omega; frame-related quantities for beaming, density find it in this chart."),
("What are the standard validation numbers in BL?",
 "r+ at M=a=0.5 is 1 + sqrt(3)/2... ; shadow boundary, prograde/retro ring at known radii - the spreadsheet check of the chart implementation."),
],
"04-GR-Ray-Tracing/06-Kerr-Geodesic-Integration": [
("What is the challenge of integrating Kerr geodesics numerically?",
 "The metric couples r-theta strongly and near the photon sphere the solutions become hyper-sensitive (chaotic sensitivities) - integrators must be adaptive and quasi-symplectic."),
("What is the canonical integrator choice?",
 "An adaptive 4th/5th-order RK (Dormand-Prince) with step control from the null-residual, or symplectic schemes where affordable for long rays."),
("How is the step size controlled?",
 "Compute two estimates of (x, p) per step and shrink/expand via local tolerance; the null residual gives a physical error floor."),
("What variables are integrated?",
 "The 8 phase-space coordinates (x^mu, p_mu) over affine lambda; or the 2-OD reduced HJ pair in (r, theta) when separating."),
("How do you handle the equatorial case?",
 "theta=pi/2 reduces to 1-D (with sigma=r^2); the integrator then cross-checks the analytic solutions in 2D for fast, high-precision validation."),
("What is 'crossing the horizon' numerically?",
 "Detect r < r+ with chord sampling; tall rays that cross get marked captured - the flag is tested when the radial step crosses threshold."),
("What about the polar singularity?",
 "At theta ~ 0 the phi-derivatives blow up in BL; code must either cross via coordinate handling or keep r-del methods.\n"),
("What is the sensitivity near the photon ring?",
 "b near b_crit produces winding instability; error amplifies - hence high precision (long double / compensated) near the ring segment."),
("What is the usual adaptive error budget?",
 "Relative 1e-10-1e-12 with moderate oversampling keeps shadow/ring errors below a pixel; too-tight budgets blow cost near the ring."),
("How do you seed the ray's momenta for a given pixel?",
 "Convert the pixel's direction to Bishop frame components, obtain p_mu = g xdot with the null condition fixing the overall scale."),
("What is the scheme's symplecticity guarantee?",
 "The flow is Hamiltonian; non-symplectic RK drifts H slowly over many steps - symplectic/integrator variants preserve conserved quantities far longer."),
("What performance vs accuracy trade exists?",
 "Every rejection costs a re-step; near the ring rejection inflates cost, so a good predictor (e.g., analytic turning-point guess) is worth the code."),
("What output record does a ray produce?",
 "Hit or miss/capture, the t-arrival, the redshift, the accumulated polarization, and r_theta of hit - the building blocks of the sampler."),
("How do you recover analytic boundary geometry?",
 "The boundary separatrix in (b, gamma) that separates capture from scatter is double-root of V_r; numeric integration of its neighbors validates the code."),
("How do you test long integration stability?",
 "Integrate a closed orbit for hundreds of periods; trajectory closure and conserved p_t drift at 1e-12 = pass, drift = reset."),
],
"04-GR-Ray-Tracing/07-Carter-Constant": [
("What is the Carter constant?",
 "A fourth constant of Kerr geodesic motion (beyond E, L, and unit mass) arising from the separability of the Hamilton-Jacobi equation - it tames the theta-motion."),
("What is its explicit form for photons?",
 "Q = p_theta^2 + cos^2 theta (a^2 E^2 - L^2/sin^2 theta) (plus a mass term for massive particles); it is constant along null geodesics."),
("Why is it 'not trivial'?",
 "Unlike E and L (from symmetries), Q comes from a hidden separability symmetry - no corresponding Killing vector exists in general, only the Killing tensor."),
("How does Q constrain rays?",
 "With (E, L, Q) the r and theta equations separate into ordinary differential inequalities; the image is completely classified by the triple."),
("What is the Killing tensor's role?",
 "K^mu,nu p_mu p_nu = Q + (L - aE)^2; K is the conserved quantity of the Killing-Yano tensor - the deeper geometric origin."),
("How do you compute Q in code?",
 "From p_theta, p_phi, E at launch: Q = p_theta^2 + cos^2(theta)[...]; monitor it along integration as a built-in correctness check."),
("What happens to Q for equatorial rays?",
 "On theta=pi/2, Q = p_theta^2 = 0 - equatorial rays are the Q=0 family; the shadow's equatorial boundary corresponds to Q=0 hits."),
("How does Q map to image coordinates?",
 "The impact parameters b = L/E and gamma such that Q = E^2 (b-something)^2 maps image polar coordinates to (Q, L) - the shadow equation in those terms."),
("What is the separability trick?",
 "Reduced motion is governed by two independent 1-D potentials from Hamilton-Jacobi; the constants (E,L,Q) fix everything - used by separation-integration codes."),
("How does Q change with L for turning points?",
 "Theta turnarounds occur where the effective theta-eq Q_bounds switch sign; real geodesics exist iff Q is in the allowed interval at each r."),
("Why is Q so valuable for validation?",
 "Its conservation is a built-in error monitor: any drift in the Q-accurate trajectory is an integrator defect, not physics."),
("What is Q's sign/range?",
 "Q >= 0 for equatorial-type orbits (with L^2 >= 0 limit); some formalizations use the normalized, dimensionless auxiliaries leading to valid mapping."),
("How does the code use Q analytically?",
 "Radius solutions r_r of the effective potential depend on Q; the photon-sphere/ring positions for given (a, direction) are functions of Q - solving them predicts rings."),
("What is the Kerr shadow equation in Q/b terms?",
 "b_crit(L_or_Q) traces the boundary curve; the classic Stern-Gibson formula for the silhouette uses Q=0 for the equatorial boundary then the general Q."),
("What is the practical takeaway?",
 "Full 8-D integration conserves Q automatically to integration tolerance; reduced (separated) integration USES Q as an input - both paths are legitimate, documented choices."),
],
"04-GR-Ray-Tracing/08-Effective-Potential": [
("What is the effective potential for radial motion?",
 "For fixed (E, L, Q) the null condition reduces to rdot^2 = V_r(r); the allowed radial range is where V_r >= 0 - the potential determines the orbit's envelope."),
("What is V_r for Kerr (Boyer-Lindquist)?",
 "The full expression containing Delta and Sigma splits into a rational form; its boundary V_r=0 and critical points drive turning points and circular orbits."),
("What is the effective potential for the theta motion?",
 "The companion theta-potential fixes cottheta^2 bounds from Q; theta-motion is normalizable given Q in a bounded interval."),
("What are turning points?",
 "Radii where V_r = 0 (rdot=0) - the closest-approach r0 and possibly an outer bound; the ray bounces between these extremes."),
("What is a circular (photon) orbit?",
 "Where V_r has a critical point (V_r = V_r' = 0): a degenerate root - the photon sphere for given (E, Q, a), unstable in radial direction."),
("How does the potential encode capture?",
 "If no turning point exists for r > r+ consistent with V_r >= 0, the ray plunges to the horizon - capture is precisely 'no outgoing turning point'."),
("How do you compute the shadow from the potential?",
 "Scan the image plane (b, gamma); for each, solve V_r for turning points; those lacking escaping turning points fall in the shadow."),
("What is the photon-sphere equation from the potential?",
 "The double root condition V_r(r) = V_r'(r) = 0 yields r_ph and the critical b_ph - the hidden benefit of potential analysis."),
("What does the potential say about multiple images?",
 "Nested turning-point structures give multiple radial extrema - the source of the rays that wrap several layers of image."),
("How is the potential used to seed the integrator?",
 "Initial rdot computed from V_r directly; turning points predicted analytically so the integrator passes smoothly through r0 without sign flips."),
("What is a wavefront/family sweep in potential language?",
 "For fixed E, scanning L traces the potential family; the shadow boundary is where the potential maxima equal the incoming b - the nude surface."),
("How do you validate the potential?",
 "Move particles r flat: integrate and assert rdot from V_r matches the integration's own rdot; at photon sphere, V=0 with V'=0 reproduces r_ph=3M (a=0)."),
("What is the energy vs impact parameter relation?",
 "Scaled by E, everything depends on b and the polar angle gamma (via Q), so V_r is effectively a two-parameter family - the lens map's territory."),
("What caution about units?",
 "Potential formulas assume geometric units; mixing in G/c yields absolute turns - code keeps the pure M=1 forms and scales radii at I/O only."),
("Why is the potential the right mental model?",
 "It reduces the black hole's lensing to 1-D classical mechanics - the intuition of hills/valleys that makes capture, rings, and shadow all feel immediate."),
],
"04-GR-Ray-Tracing/09-Photon-Sphere": [
("What is the photon sphere?",
 "The surface where null circular orbits exist - for Schwarzschild at r=3M; in Kerr there are prograde and retrograde photon orbits at different radii."),
("Why is the orbit unstable?",
 "The effective potential has a maximum there - radially, V_r(r) is a maximum; small perturbations rocket the photon inward or outward (the ring is a razor)."),
("What does it do in images?",
 "Photons skimming the sphere wind many times, piling up near the boundary of the shadow - producing the characteristically bright, sharp ring."),
("What is the prograde vs retrograde radius?",
 "r_ph,prog < 3M < r_ph,retro for Kerr with a>0; the difference sets the asymmetric ring shape (crescent/D) - a spin probe."),
("What is the analytic radius?",
 "r_ph = 2M (1 + cos(2/3 arccos(+-|a|/M))) - the upper sign for prograde, lower for retrograde; verify against both limits (3M at a=0, ~M/(2) at a=M prograde) - code-check."),
("How does the sphere relate to the shadow?",
 "The shadow boundary consists of impact parameters that wind asymptotically to the sphere (b = b_crit(prog) and b_crit(retro)); the sphere IS the shadow's edge-set."),
("How many images does the ring produce?",
 "The sphere encodes an infinite ladder of winding angles; each multiple of the angle gives one more faint copy of the source on the ring - log-spaced."),
("What is the total magnification near the ring?",
 "As impact parameter approaches b_crit the ray's winding and travel time diverge, magnifying the source's intensity by factors of ~e^pi per loop."),
("How do you ensure numeric capture of ring photons?",
 "Those rays spend long affine time near r ~ r_ph; adaptive stepping and fine pixel scanning make the ring resolution robust (supersample the boundary)."),
("What is the caustic at the photon ring?",
 "A caustic: the focus of the lens detaches; the ring's intensity divergence is the null-lensing caustic analogue to gravitational microlensing peaks."),
("What is the ring's radial scaling?",
 "Successive ring images shrink by a factor ~e^(-2pi) approximately, giving the self-similar 'onion' observable banding in high-res images."),
("What does the sphere do to photon time delay?",
 "Rays near b_crit linger near 3M for a long affine time; the delay produces the 'late-time' red/infrared limbs of the ring."),
("How does the sphere interplay with the disk?",
 "Disk emission just inside/outside the sphere gets bent the most; the innermost ring samples emission from the entire disk silhouetted through multipass bending."),
("What is the validation of the sphere?",
 "Launch rays from r0=3M (a=0) with tangential momentum; they must stay at constant r for the whole integration - the golden null test."),
("What is the practical renderer's ring recipe?",
 "Trace fine impact-parameter sampling around b_crit plus supersample and clamp count - the ring is cheap to expose, hard to hide, easy to sharpen later."),
],
"04-GR-Ray-Tracing/10-Capture-and-Scatter": [
("What is capture?",
 "A ray whose impact parameter is small enough reaches the horizon and is trapped - ending as 'shadow' in the image."),
("What is scatter?",
 "A ray with large enough b avoids the hole and escapes to the observer, bringing with it lensed/scattered images of the source."),
("What is the capture boundary?",
 "The b_crit(gamma) curve in the image plane that separates capture from scatter - exactly the shadow silhouette."),
("How does b_crit depend on spin and angle?",
 "For a>0 the prograde b_crit is smaller than retrograde; the boundary becomes offset/asymmetric - visible as the crescent shadow."),
("How is capture detected in the ray loop?",
 "The integrator returns a flag when r crosses below r+ plus margin (capture) instead of a hit - pixels where all rays capture are pure shadow."),
("What is the half-angle resolution near the boundary?",
 "Rays exponentially closer to b_crit wind more; without adaptive sampling a dozen-pixel fuzz appears - mitigated by supersample and exact-boundary seeding."),
("What is the relation of capture to the disk emission?",
 "Nested images of the near disk all sit inside/around the ring; emission at the center of the shadow is entirely lensed disk up over the top (the secondary arch)."),
("What is scatter in scattering-language?",
 "Rays that pass r_min(b, gamma) with b > b_crit emerge deflected by (r_min-dependent) angle - the lens map's domain is the scattered parameter space."),
("How do you map captured fraction?",
 "Grid the image into (b, gamma) and test capture analytically (V_r discriminant) - the shadow equation can be solved without any integration."),
("What is the Doppler/capture interplay?",
 "Relativistic beaming tilts where the brightest capture-adjacent photons land (the bright crescent), but the SHADOW EDGE itself stays at b_crit - a clean separation."),
("What is a near-capture latency effect?",
 "Photons hugging b_crit have enormous arrival delays - the source appears stretched in time; relevant for variability of the innermost ring."),
("What is the spin-dependence test?",
 "At a=M, prograde b_crit approaches ~M^1/2-ish; the crescent boundary distorts maximally - the strongest spin-contrast observable."),
("How do you derive b_crit from V_r?",
 "Solve V_r = V_r' = 0 simultaneously for (r_ph, b_crit) and repeat over gamma via Q; the resulting closed path is the shadow silhouette formula."),
("How does a renderer decide supersampling?",
 "Only pixels near the smooth capture boundary need extra rays; the rest of the image-fire samples then - the cost-accuracy sweet spot."),
("How do you validate capture vs scatter?",
 "For known (b, gamma) predict the classification analytically (discriminant) and cross-check with 50% supersampled integrals - bug-free boundary code."),
],
"04-GR-Ray-Tracing/11-Gravitational-Lensing": [
("What is gravitational lensing in the ray-tracing context?",
 "The bending and focusing of light by the hole's spacetime geometry itself, producing multiple images, Einstein rings, and the shadow - all emergent from geodesic integration."),
("What is the basic quantity (the 'lens map')?",
 "A mapping from source coordinates to image coordinates (direction of arrival), induced by the geometry; strong lensing near the photon sphere is its wild limit."),
("What are the classic signatures?",
 "Deflection angles, magnification, multiple images (photon-ring copies), Einstein rings around lines-of-sight, and the central shadow."),
("What is critical/magnification contrast?",
 "Where the lens map folds (caustics/critical curves), the local magnification diverges - making ring/caustic folds the brightest structures in images."),
("How does a black hole lens differ from a galaxy lens?",
 "Galaxy-scale lensing multiplies thin lenses' potential; a hole's full strong-field geometry bends rays even within the shadow - the extreme multiplicity limit."),
("How does the photon-ring become a sequence of Einstein rings?",
 "Different winding numbers produce copies of the source at geometrically smaller radii - a chain of Einstein rings nested around the shadow boundary."),
("What is 'secondary' image?",
 "Light from the far side reaching the observer over the top/bottom of the hole - the bright 'arch' spanning the north of the shadow."),
("How does the observer's inclination matter?",
 "Edge-on views (i~90 deg) show the arch with maximal asymmetry; near-face-on (i~0) the shadow trends circular - inclination is a fit parameter of the image."),
("What is magnification in the intensity picture?",
 "The intensity ratio image/source equals the inverse Jacobian of the lens map; the code obtains it implicitly via the ray integral weighting."),
("How do you render lensed intensity?",
 "Each ray accumulates emissivity*transmission(redshift) along its path; magnification appears naturally as rays compress - no explicit Jacobian needed in Monte Carlo."),
("What makes the lensing observable 'robust'?",
 "The shadow/ring occur for ANY disk: their shape depends almost entirely on (M, a, inclination), not on the emitter - making them excellent event-horizon-telescope probes."),
("What is the effective distance scaling?",
 "Angles scale with M/D; ray-tracing naturally produces the geometry and the code only maps to the sky using the observed size (scaling)."),
("How do you fit a real EHT image in this code?",
 "Simulate the (a, i, M/D) portrait; the resulting shadow/ring parametrize the observed radiation - a forward model for parameter estimation."),
("What are the lensing qualitative tests for the visualizer?",
 "Verify: ring continuous, shadow boundary closed, far-side disk appears flipped (secondary), edge-on shows two distinct arcs - quick sanity of the geometry module."),
("What is the ultimate quality gate of lensing?",
 "Overlay analytic shadow silhouette (from V_r) on the rendered image: pixel-accurate match at b_crit is the definitive lensing validation."),
],
"04-GR-Ray-Tracing/12-Einstein-Rings": [
("What is an Einstein ring?",
 "The apparent circular image of a source when the observer, source, and lens (the hole) are aligned - light from the source bent into a full annulus."),
("What is the Einstein radius?",
 "For a point mass lens, theta_E = sqrt(4GM D_ls / (c^2 D_l D_s)) (small-angle); for the hole's strong field the ring is the photon-ring-scale annulus."),
("What happens in full strong-field alignment?",
 "The Einstein ring splits into the nested ring family around the photon sphere - the hole's scharacteristic multiple-ring annulus."),
("How does the code produce rings?",
 "Rays launched on trivial b_axis directions wind around the hole at constant-lambda geometry; aligned sources magnify into continuous annuli."),
("What is the caustic at perfect alignment?",
 "The lens map degenerates (infinite magnification along a circle) forming the ring - a critical-curve caustic; physically the annulus is an image of the whole source disc."),
("How large is the ring in units of M?",
 "On the sky the ring subtends ~ (5.2 M)/D radians; the EHT famously sees the M87 ring at ~ 42 +- 3 microarcsec."),
("What is the difference between the photon ring and the Einstein ring?",
 "The Einstein ring is the aligned-lens enhancement (first order); the photon ring is the physical orbit's shadow boundary - in images they coincide to first sight, separated by n-order copies."),
("Why is the ring insensitive to source details?",
 "Its radius is set by geometry (M, a) not emissivity, so it's the robust observable; emission shape changes brightness within the ring, not its edge."),
("What is the 'lensed ring' of the accretion disk?",
 "The disk itself forms multiple arcs/ring segments - the near edge looks like a thin arc, the far edge doubled, combined into the ring feature."),
("How do you render an artificial Einstein ring demo?",
 "Place a uniform spherical source behind the hole; its aligned image is a full annulus whose boundary you compare with the analytic ring radius."),
("What happens at high inclination?",
 "The ring is no longer circular on the sky: it brightens/sharpens toward the barycentered crescent - the classic observed asymmetry."),
("What is the ring's chromatic role?",
 "Doppler+gravity shift the ring's color (blue on prograde side); the radius is achromatic - geometry dominates color contrast."),
("How is the ring measured?",
 "Diameter at the ring brightness maximum - the EHT team's defining observable, robust to emission modeling - the code outputs diameter(b_crit portrait)."),
("What validation closes the ring loop?",
 "The rendered ring's diameter must match b_crit(portrait) to sub-pixel; that double-check links renderer to analytic backbone."),
("What is the resolution requirement?",
 "To resolve the ring you need 12+ pixels across the shadow; EHT used phased-array VLBI; in-simulation this is simply the sampling grid at b~5M."),
],
"04-GR-Ray-Tracing/13-Doppler-Beaming": [
("What is Doppler beaming?",
 "Relativistic motion sharpens emitted light into the direction of motion: approaching emitters appear brighter and bluer, receding ones fainter and redder."),
("What is the Doppler factor?",
 "delta = 1/(gamma(1 - beta cos theta)) where theta is the angle between emitter velocity and the photon direction in the emitter frame."),
("Why is the disk's approaching side brighter?",
 "Gas orbiting at the hole moves toward the observer on one side; beaming boosts its intensity and blueshifts spectra - the iconic hot crescent."),
("What is the code formula?",
 "The transfer factor includes (nu_obs/nu_emit)^2 (or ^3 depending on frame of emission) - related to the Doppler/cluster factor in intensity transfer."),
("How do you compute it from the integrated ray?",
 "At the hit site, form p.u_emit and p.u_obs; the redshift factor z = (p.u) ratios fold Doppler + gravitational into one scalar per hit."),
("What sets the Doppler strength?",
 "The orbital beta ~ 0.2-0.6 c for the innermost disk (Keplerian, prograde); the factor difference between sides reaches orders of magnitude at high inclination."),
("What is the angular dependence (edge-on vs face-on)?",
 "Face-on (i~0) sees almost no asymmetry (cos theta ~ 0); edge-on maximizes it - a key handle on inclination in fits."),
("How does beaming combine with gravitational redshift?",
 "Total shift factor = Doppler * gravitational; near the hole both operate and partially cancel, net producing the specific blue on prograde."),
("What does beaming do to the photon ring?",
 "The prograde ring sector is boosted (the hole spins, dragging light along) - the intensity asymmetry of the ring is layered on top of shape asymmetry."),
("How is the flux per frequency affected?",
 "I_obs(nu) = (delta)^k I_emit(nu/delta) with k depending on the angular distribution (k=2 for bolometric, k=3 for specific-intensity direction); code must pick and document k."),
("What does beaming do to the colors?",
 "The shift moves frequency; spectra (e.g., power-law) sampled at the shifted frequency produce the full chromatic result - measured as colors."),
("How do you validate beaming?",
 "Use a rigidly rotating, optically-thin annulus at radius r; apply the analytic delta to a known spectrum and check the image intensity/color at two azimuths."),
("What is the 'spotlight' alignment in movies?",
 "As a hot spot orbits, its Doppler-boosted image peaks when moving toward the observer - the periodic bright flash used to probe disk scale in time-domain imaging."),
("What pitfall hides beaming bugs?",
 "Using frame confusion: boosting with the wrong velocity (e.g., coordinate beta instead of ZAMO-frame) silently flips the asymmetry; always define the emitter's 4-velocity frame explicitly."),
("What is the beaming check image?",
 "Render a symmetric cold disk; the hot crescent must sit on the approaching (prograde) side for prograde spin - invert a, the crescent flips - self-evident smoke test."),
],
"04-GR-Ray-Tracing/14-Redshift-and-Blueshift-Mapping": [
("What is the redshift map?",
 "The per-pixel value of 1+z between the emitter and the observer - a scalar field over the image separating gravitational, Doppler, and lensing effects."),
("What are the components of total shift?",
 "1+z = (p.u_obs)/(p.u_emit) with the emitter's 4-velocity e_emit and observer e_obs; this single ratio captures every shift (gravity+Doppler) exactly."),
("How is the map computed per ray?",
 "Carry the combination as a state: at hit, read p.u_emit; the camera's p.u_obs is constant; total = ratio - display as false color."),
("What does a pure gravitational map look like?",
 "For a static (ZAMO-standing) source, 1+z = sqrt(g_tt_obs/g_tt_emit)-ish; azimuthally symmetric - a bull's-eye of increasing shift inward."),
("What does adding Keplerian motion do?",
 "The map gains azimuthal asymmetry: blueshifted (z<0) on the approaching side, heavier redshift on receding - the signature of rotation."),
("Why is the inner ring redshift-dominated despite beaming?",
 "Near the ISCO the orbital factor and deep potential compress; the net inner-edge may still be blue on prograde under strong a, but the plunge region reddens - the map shows the interplay."),
("How does the code convert shift to color?",
 "Sample the spectrum at nu_emit = nu_obs(1+z); a power-law/blackbody spectrum then yields literal chromatic rendering per pixel."),
("What is a 'spectral image'?",
 "Rendering at a fixed observation frequency (monochromatic); then each pixel's intensity is I(nu0) * (delta)^k - the direct observable maps."),
("How do you extract the map for a movie?",
 "Emit each frame; store a float channel per pixel holding 1+z; composite it as a fringe overlay/debug view for the pipeline."),
("What is the observational significance?",
 "Redshift maps are directly comparable to line-profile/imaging data; the map's asymmetry locks the combination (a, inclination) more tightly than shape alone."),
("What is the ~z picture of the shadow?",
 "The shadow pixels have an extreme (divergent/undefined) z - they are black; the true emission ends right at the ring where z saturates - use a mask."),
("How do you validate a redshift map?",
 "Static-source map must equal sqrt(1-2M/r) exactly; equatorial-Kepler map must match the analytic combined formula at selected pixels - numerical agreement in 1e-10."),
("What interplay does the map encode with length contraction?",
 "The fluid's 3-velocity direction as seen in the rest frame sets delta; length contraction reshapes the projected emissivity - both fold into the final color."),
("What post-processing keeps the map stable?",
 "Noiseless decimation with guard clamps at z extremes; the renderer writes the raw float frame before tone-mapping for color science."),
("What is the headline deliverable?",
 "A per-pixel (nu, I) or (I with z) datacube whose false-color shade is a physical map - the connection point between your raytracer and real observations."),
],
"04-GR-Ray-Tracing/15-Integration-Strategy": [
("What is the adaptive-step strategy?",
 "Step size selected from local error estimates (RK vs embedded, or null-residual size); doubling/halving keeps accuracy while bounding cost."),
("What scheme do production codes use?",
 "Dormand-Prince (rk45) or velocity-Verlet/symplectic variants; performance-tuned code compiles to AVX-512/FP16-GEMM kernels or uses graph-compiled engines at millions of rays/sec."),
("How do you choose the initial step?",
 "From the local inverse derivative scale (e.g., dlambda ~ h0 * M / |p|), then the controller quantifies; avoiding giant first jumps near the horizon matters."),
("What is the rejection loop?",
 "Each trial step compares two orders; on failure the step retries smaller - the near-ring rejection cost is the main accuracy/cost tradeoff of the code."),
("How is the derivative kernel vectorized?",
 "The metric+derivative evaluation is a pure function of (r, cos theta); batch it: SIMD across rays with fixed lambda, feeding the integrator per SIMD-lane."),
("What is the halo/threshold r_max for termination?",
 "Rays that reach r > r_out (e.g., 2000M) without a hit are 'missed' - termination guarantees linear cost, no wandering after the geometry does its work."),
("How are crossings found (disk/horizon)?",
 "Bracketing (sign change of r - r_isp or r - r+) between steps, then a bisection/regdsolve to refine the crossing - precise hit positions without extra integration."),
("What precision does the shadow need?",
 "Pixel-scale: relative errors 1e-6 keep ring boundary clean; the camera supersample covers the rest - no need for long double globally."),
("How do you reuse work across frames?",
 "Static-geometry cache: precompute b/phi maps and the capture table once per (a, i); only the emission/velocity changes per frame - the real production optimization."),
("What is the memory layout for ray batches?",
 "Structure-of-arrays: (r,theta,phi,p_r,p_theta,p_phi,t) as separate arrays so SIMD/L1 work flat; a batch = a warp of rays with a common adaptive step."),
("What is the stopping criterion on conserved residuals?",
 "Where H drift exceeds a threshold (indicating lost symplecticity), subdivide/re-seed the ray - the safety valve against silent integration drift."),
("How does the strategy adapt near the photon sphere?",
 "A cluster detector (rdot transitions, winding counter) triggers step reduction while within a factor of b_crit - the targeted way to resolve rings cheaply."),
("What about the affine parameter blowups in t?",
 "t integrates fine but grows; keep t saved as a separate offset double and only accumulate it at output to avoid losing precision."),
("What is the validation workflow of the integrator?",
 "A regression suite: circular orbit closure, deflection asymptotic, shadow boundary, beaming map - every refactor of integration strategy must re-pass."),
("What is the recommended architecture summary?",
 "Adaptive rk45 in SIMD-batched form, chart-switching to KS at the horizon, analytic shadow seeding, supersample only the boundary - the full strategy in one line."),
],
"04-GR-Ray-Tracing/16-Background-Sky-Mapping": [
("What is the background sky?",
 "The celestial sphere of distant stars/galaxies mapped to each pixel via ray propagation; an essential realism layer and a tool to expose lensing."),
("How do you map a sky to a pixel?",
 "The ray's initial direction gives the sky coordinate (equatorial/azimuthal angles); the far-field deflection maps arrival to emission direction - 'where did this photon come from'."),
("What is the 'sky map' transform?",
 "A map from image pixel (x,y) to source direction (theta_src, phi_src); for weak lensing it's nearly identity, near the hole it's wildly wrapped - visualized as star trails."),
("How do stars look near the shadow?",
 "Sources near the ring wrap multiple times - stars appear as winding arcs/smirches; the realistic starfield is the best intuitive lensing demo."),
("How do you attach a sky texture?",
 "Sample a cubemap/panorama from the far-field direction of a MISS ray; capture-mode rays get sky color, hit-mode rays get disk emission."),
("What credit does the sky give to the geometry?",
 "A uniform-grid starfield rotated by the lens, when compared to the analytic deflection map, validates the far-field behavior of the integrator."),
("How do you render a static background (no disk)?",
 "Classic: rays miss -> sky; capture -> black shadow. The resulting 'shadow-in-stars' image is the textbook demonstration of the code."),
("What is the isocenter of the sky magnification pattern?",
 "Just outside the shadow, sky regions are magnified (star trails expand); inside they're hidden - the map shows the classic Einstein-ring annulus of stars."),
("How do you handle very distant sources with lenses?",
 "The single deflection picture is enough: each star = one source ray; the code launches per-pixel rays and maps them - no extra lens equation needed."),
("What does high-L imaging give?",
 "The map wraps: sources at angles many M/D behind the hole appear at multiple image positions (the 'rail' of the photon ring in star maps)."),
("What is the practical texture format?",
 "Equirectangular 4096x2048 or cubemap; sampling at far-field theta/phi in float precision keeps aliasing away from the critical lines."),
("How do you add a CMB-like large-scale background?",
 "Use a gridded background sphere; the code maps all rays to it - providing the robust far-field anchor for ray-direction bookkeeping."),
("What is the visual paradox (ring of stars vs shadow)?",
 "The star trails form a ring at r_E just outside the shadow, AGREEING with the analytic Einstein ring; the shadow remains black - a self-checking display."),
("How does supersampling help the sky?",
 "Stars are point-like: without supersampling they alias. Multi-ray per pixel plus motion blur smears star arcs appropriately - a feature, not a bug."),
("What is the golden end-to-end test?",
 "Render 'shadow-on-starfield': compare the sky-mapped star positions analytically across a grid; any star displaced outside its analytic deflection = smash-bug."),
]}