"""Curated Q&A for 05-GRMHD and 06-Radiative-Transfer leaves."""
GRMHD = {
"05-GRMHD/01-MHD-Equations": [
("What are the MHD equations?",
 "The coupled conservation laws of ideal MHD - mass, momentum, energy (and with the flux-freezing constraint, magnetic flux) - describing plasma evolution in a background flow."),
("Write the ideal relativistic MHD (GRMHD) equations in conservation form.",
 "nabla_mu (rho u^mu) = 0, nabla_mu (T^mu\nu) = 0 with T^mu\nu = (rho h + b^2) u^mu u^\nu + (p + b^2/2) g^mu\nu - b^mu b^\nu, plus nabla_mu (*F^mu\nu) = 0 (induction)."),
("What are the primitive vs conservative variables?",
 "Primitives (rho, p, u^i, B^i) describe the physical state; conservatives (D, S_i, tau, B^i) are the numerically conserved quantities; the two sets interconvert via the primitive-recovery procedure."),
("What is the 3+1 split of GRMHD?",
 "Foliation into time slices with lapse alpha and shift beta^i; the evolution equations split into constraint (mass/flux) and evolution parts - the standard ADM-like formulation for codes like HARM."),
("What is the role of the magnetic field in the equations?",
 "The field contributes stress, pressure (b^2), and enforces Alfvenic transport; its flux is conserved by the induction equation and the divergence-free condition."),
("What is the equation for total energy density?",
 "tau = rho h u^0 u^0 - p - b^0 b^0 + 1/2 b^2 (in HARM's conservative set); the code conserves (D, S_i, tau) and the magnetic flux."),
("What are the units/normalization of the GRMHD code?",
 "Geometric units G=c=1; density/temperature are code units convertible via the mass scale - the code operates purely in these and scales at output."),
("What is the difficulty of the GRMHD system?",
 "Its hyperbolic character changes with state (acoustic+Alfven+fast modes), giving a wide eigenstructure that Riemann solvers must treat - the heart of its numerical challenge."),
("What is 'conservation form' and why does it matter?",
 "Conservative discretization guarantees all conserved mass/energy/momentum/flux only via boundary fluxes - the anti-shock-artifact and longstanding anti-physics guard."),
("What is the induction equation and its subtlety?",
 "The B evolution from nabla x (v x B); the divergence-free constraint nabla.B = 0 must be held (e.g., via constrained transport / divergence cleaning) or plasma blows up."),
("How does GRMHD closure the system?",
 "An equation of state p = p(rho, eps) (e.g., gamma-law); synchrotron codes also need electron temperature - closure approximations (electron fraction/ratio) enter."),
("What distinguishes ideal from resistive MHD?",
 "Ideal assumes infinite conductivity (flux frozen into plasma); resistive adds ohmic terms - relevant near the disk's innermost reconnection, a modelling choice."),
("How is the solution advanced in time?",
 "Conservative update with flux from a Riemann solver, reconstructed states, and a degenerate time step from the max characteristic speed (CFL)."),
("What are the sound/Alfven speeds roles?",
 "Their maxima set the CFL time step; near magnetized regions the fast magnetosonic speed dominates - the CFL-limited time step is what makes 3D runs slow."),
("How is the gas supposed to produce the disk?",
 "MHD turbulence (MRI) transports angular momentum, letting gas spiral in; the code's turbulence stats (alpha, stress) are the physical headlines of the simulation."),
],
"05-GRMHD/02-Ideal-MHD": [
("What is ideal MHD?",
 "The limit of infinite conductivity + nonrelativistic flow, where the field is frozen into the plasma; GRMHD is its relativistic, curved-spacetime generalization."),
("What does flux-freezing mean for a disk?",
 "Field lines are advected with the matter; a disk's B profile therefore follows the gas - the base of MRI-driven transport models."),
("What are the ideal MHD normal modes?",
 "Alfven, fast, and slow magnetosonic waves; their speeds are the state-dependent eigenvalues of the system - the Riemann solver must resolve all three."),
("What is the Alfven speed?",
 "v_A = B/sqrt(4 pi rho) (in nonrel form); in GRMHD, the relativistic b^2-weighted expression; it sets the anisotropic transport speed along field lines."),
("What is the equation of motion with B?",
 "rho dv/dt = -grad p + 1/(4pi)(curl B) x B; magnetic tension (curvature) and pressure (gradient) both accelerate the plasma."),
("What is the magnetic pressure?",
 "P_B = B^2/(8pi); it contributes to total pressure and to the energy budget - observations of jet collimation root in its dominance."),
("What is the beta parameter?",
 "beta = p_gas/p_B (plasma beta); beta >> 1 gas-dominated (typical disk), beta << 1 magnetically-dominated (jets, corona)."),
("What are the disagreements between ideal MHD and reality?",
 "It ignores resistivity, Hall, electron kinetics; real disks have reconnection - but ideal captures the large-scale dynamics of accretion+jets faithfully."),
("How do velocities compare (nonrel vs GR)?",
 "The GR version replaces v with the 4-velocity and spatial basis; the induction becomes d_iF = 0 with the full b^mu - a heavier algebra, same physics."),
("What is the 'magnetic field in the fluid frame'?",
 "b^mu = (1/2) u^nu *F^mu\nu (the co-moving projection); all forward-frame formulas (emissivity) use b (and its norm) rather than the lab B."),
("How does ideal MHD energy evolve?",
 "Polytropic (gamma-law) energy flux plus Poynting; in GRMHD the total energy-momentum is conserved as T^mu\nu - internal energy via p rho gamma(integral term)."),
("What are the limitations for disk simulations?",
 "Turbulent dissipation is numerical; true electron heating needs closure - a known KeR/ipole-hybrid gap the analyst must report."),
("What is the MRI threshold?",
 "For weak B, MRI linearly drives modes unless rotation profile is too stiff (the Lindblad/MRI criterion); codes must resolve the fastest-growing wavelength."),
("How does ideal MHD set the jet?",
 "Poynting flux along poloidal field: the plasma accelerated by magnetic slingshot - simulated jets are a successful ideal-MHD prediction."),
("What validation test is canonical?",
 "The 1D nonrelativistic shock tube / Orszag-Tang vortex; GR codes additionally test the stationary torus equilibrium - the 'artificial disk' stability run."),
],
"05-GRMHD/03-Relativistic-MHD-Conservative-Form": [
("Write the system in conservation form.",
 "dU/dt + dF^i/dx^i = 0, where U = (D, S_j, tau, B^j) in the 3+1 decomposition, with D=gamma rho, S_j from the momentum flux, and tau from total energy."),
("What are the conserved quantities HARM uses?",
 "D (rest mass density), Q_j = S_j (covariant momentum density), tau (energy density) computed from the stress tensor projections - the update loop conserves exactly these."),
("What is the numerical flux F?",
 "The spatial stress-energy components T^i\nu (and the electric field E from the induction), evaluated via a Riemann solver from reconstructed states."),
("What is the primitive-to-conservative (P2C) map?",
 "Compute D, S, tau from (rho, u^i, B^i, p) using the inverse metric and b^2 terms - a simple algebraic map; the hard direction is the inverse (recovery)."),
("What is the conservative-to-primitive (C2P) recovery?",
 "Invert the P2C equations for (rho, p, u^i) given (D, S, tau) - the famous inversion that fails for extreme states and needs floors/fallbacks."),
("Why is conservation form numerically vital?",
 "Weak solutions (shocks) are captured only in conservative form; non-conservative discretization destroys Rankine-Hugoniot jumps - shocks are everywhere in accretion."),
("What are the flux terms through a face?",
 "The Godunov scheme samples the Riemann problem: left/right states -> intercell state via a solver (HLL, HLLC, etc.) -> single conserved update."),
("What is the CFL condition in this form?",
 "Picking dt <= C * dx/c_max with c_max the largest eigenmode speed; unless C ~ 0.4-0.8, the scheme becomes unstable."),
("What are the floors in GRMHD codes?",
 "Numerical vacuums (rho->0, p->0) break recovery; codes clamp floors (rho_floor, p_floor) to keep primitives physical - the artifact budget of the simulation."),
("What is the total energy vs entropy form?",
 "Conserving total energy S_tau loses some temperature contrast; energy-conserving forms (vs entropy) are preferred for their accuracy on disks."),
("How does the code handle atmosphere?",
 "An outer low-density halo filled to floors keeps recovery from degeneracy and sets the jet's launching base physically."),
("What is the B-constraint coupling?",
 "Recovery must keep b^0 from B with the 'u x B' coupling; an inconsistent field causes recovery hotspots - codes enforce via proper b and grad(B) handling."),
("How do you test conservation?",
 "Run a shearing ring; total energy and charge/mass budgets must drift below 1e-8 over the run - conservation is the physical contract."),
("What is the shock-vs-contact resolution tradeoff?",
 "HLL (diffusive, robust) vs HLLC (adds contact, needs more state logic); production codes balance with limiters - the core discretization decision."),
("What annotations carry to analysis?",
 "Every output carries conserved+primitive states and the transfer Lagrangian - flux accuracy ties straight into accretion rates you measure."),
],
"05-GRMHD/04-Riemann-Solver": [
("What is the Riemann problem?",
 "The evolution of two constant states (left/right) separated by a discontinuity; Godunov schemes solve it at every intercell face each step."),
("What is an HLL solver?",
 "The Harten-Lax-van Leer approximate solver assuming two fastest waves; it satisfies conservation and positivity but smears contact discontinuities (needs a few cells)."),
("What is the HLLC solver?",
 "HLL with the contact wave added: sharper resolution of the contact (density jumps) - most modern GRMHD (HARM, Athena++) default to HLLC or its variants."),
("What are the fastest waves?",
 "The fast magnetosonic speeds c_+/- (along the face normal); a Riemann solver that bounds by them keeps the solution entropy-satisfying."),
("Why can't you use exact solution?",
 "The relativistic MHD Riemann problem is transcendental and expensive; approximate solvers give shocks to sufficient accuracy for displacement analysis."),
("What is the role of the eigenstructure?",
 "Fast/Alfven/slow waves determine characteristic speeds for flux splitting and for the CFL; their accuracy sets the effective dissipation."),
("What about moving/discontinuous grids?",
 "Uniform static grids skip grid-speed terms; AMR-with-refinement adds them - a detail more codes than not get subtly wrong."),
("What is the positivity region?",
 "For HLL the positivity of density/pressure is provable within the two-wave bound - the theoretical reason production codes prefer HLL for extreme states."),
("How is the solver vectorized?",
 "Per-face state evaluation, eigen-computation, and flux arithmetic are lock-step: SIMD across faces, with branch-free approximations for the wave speeds."),
("What is a total-variation-diminishing (TVD) pairing?",
 "Solver + limiter must keep total variation bounded; mismatched (oscillating) pairs create spurious oscillation in strong-field runs."),
("How does the solver relate to capturing jet shocks?",
 "Jet sheath shocks demand sharp contact + robust fast-wave treatment; over-diffusive solvers blunt the jet's collimation - a visible production-mismatch symptom."),
("What is a classic validation?",
 "The 1D relativistic MHD shock tube (Balsara & Spicer): reproduce exact wave speeds, jumps, and no oddi jumps - gods of the field."),
("How do you handle vacuum states?",
 "Floors and the solver's positivity gap: if one side hits floor, the scheme must survive (bounce/remap) - the vacuum catastrophe the fields guard against."),
("What coupling with the limiter matters?",
 "The limiter reconstructs left/right states; the solver consumes them; a muted limiter + HLL gives the least oscillation but thickens the jet - the tradeoff is documented."),
("What is the performance reality?",
 "The Riemann solver is 40-60% of GRMHD runtime; vectorization, cut-off logic, and low-precision paths elsewhere are the engineering payoff."),
],
"05-GRMHD/05-Limiters-and-Reconstruction": [
("What is reconstruction?",
 "Building sub-cell left/right states from cell averages before feeding the Riemann solver, enabling second/higher order accuracy beyond flat first order."),
("What is a limiter?",
 "A nonlinear controller that clamps reconstructed slopes to avoid new extrema/oscillations near shocks - the TVD/MUSCL family (minmod, van Leer, MC)."),
("What is the minmod limiter?",
 "The most diffusive common choice: slope = the CommonReflection of the left/right one-sided differences; maximal stability at cost of smearing."),
("What is the van Leer (MUSCL) reconstruction?",
 "Monotonic piecewise linear reconstruction with a harmonic-mean slope - sharper contacts than minmod while remaining TVD."),
("What is the MC (monotonized central) limiter?",
 "A blend of the central and minmod stencils - sharper than van Leer-ish variants with modest oscillation cost."),
("What is the piecewise parabolic method (PPM)?",
 "Higher-order (3rd) reconstruction with contact steepening; used in Athena++ for high-resolution shock capturing - costlier but crisper on disks."),
("What is the role of the limiter in a disk simulation?",
 "Disk turbulence is smooth, jets carry shocks: a limiter must not damp turbulence (over-diffuse) nor ring on shocks (under-limited) - the classic tradeoff."),
("What is 'shock-steepening vs turbulence' balance?",
 "Steep limiters sharpen shocks but also steepen numerical noise in a turbulent column; the balance is tuned by the resolve-in-time test."),
("How is reconstruction implemented efficiently?",
 "Per-direction passes with pre-staged face stencils; AVX gathers across cells and memory-order fuses with the flux kernel."),
("What is the flux error of first order vs MUSCL?",
 "First order adds numerical dissipation ~ c dx; MUSCL reduces it to ~ (Delta)^2 - visibly blunting the jet/disc contrast at moderate resolution."),
("What is the 'positive' reconstruction constraint?",
 "Reconstructed density/pressure must stay positive even near floors - the limiter's clamp is designed for that failure mode."),
("How does reconstruction interplay with the CFL?",
 "The effective scheme signal speed gets limited (MUSCL face slope constrains time step); coupled with the solver, this sets global dt."),
("What is a residual-based limiter?",
 "Clamps based on the residual smoothness estimator (like the 'Barth-Jespersen' in unstructured) - adaptive by region."),
("What validation isolates reconstruction?",
 "The advection of a smooth Gaussian: amplitude error order ~ 2 for MUSCL (no limiter); through-flow of a contact: minmod spreads > MC -> verifiable QoI."),
("What does the visualization look for?",
 "The jet spine sharpness, the disk's vorticity cascade, and the absence of the staircase (staircase = poor reconstruction) around shocks."),
],
"05-GRMHD/06-Grid-and-AMR": [
("What coordinate grids are used in GRMHD?",
 "Log-spaced radial, uniform/cosine theta, and cell-centered phi; or utilitarian mapped coordinates fitting the horizon - choices that set resolution where it matters."),
("What is a logarithmic radial grid?",
 "r_i at geometric spacing d r/r ~ const, packing resolution near the horizon where density gradients live; then spacing grows to the outer boundary."),
("What is the role of the radial boundary?",
 "Inner: horizon-inflow boundary; outer: free-flow or floor. Mismatches poison jets/disks, so boundary stencils must be tested like physics."),
("What is AMR (adaptive mesh refinement)?",
 "Refining regions (e.g., the disk midplane and jet) as needed, coarsening quiescent regions; Athena++ is built around a block-based AMR."),
("What triggers refinement?",
 "Gradient/smoothness estimators on density/pressure/B plus refinement zones tied to the physics (inner disk radius, jet spine)."),
("What are the challenges of AMR for GRMHD?",
 "Conservation across refinement boundaries, advancing rization of faces, and the cost of the tree - mature codes (Athena++) solve via ghost cells at fine/coarse interfaces."),
("What is a 'de-refine' criterion?",
 "Error estimator below a floor for several intervals - coarsen back; hysteresis prevents flapping between levels near critical radii."),
("How does grid choice affect numerical diffusion?",
 "The effective dissipation scales with the local cell size; a stretched log grid enlarges cells at r>100M where jets are - inevitably a compromise."),
("What is the equilibrium of resolution?",
 "Resolving MRI fastest-grow wavelength in the disk AND the jet sheath needs 100+ cells across each - the reason 3D GRMHD is a petascale sport."),
("How do you set grid parameters from physics?",
 "Match the MRI wavelength ~ sqrt(3)/Omega * v_A: cells <= that in the midplane; the jet's scale ~ RH of the hole - measured, not guessed."),
("What is the 'outer boundary prescription'?",
 "Floor-filled flat state + damping zone at the outer boundary (outflow b.c.); jets can reflect otherwise - a common simulation-fiddle artifact."),
("How is AMR verified?",
 "Run a fixed-resolution and an AMR run with the same effective max resolution; derived accretion rate/MRI quantities must agree to tolerance."),
("What is the storage implication?",
 "Multi-level AMR stores each level separately; transient I/O becomes a bottleneck - compress-level outputs and keep checkpoint/restart bare."),
("How does HARM differ in grid?",
 "HARM uses stationary analytic grids (often 'phi-normalized') coded directly, not a tree; it trades flexibility for tensor-managed simplicity."),
("What is the physics-correct grid slogan?",
 "Put cells where the gradients live (inner rho, disk midplane, jet spine) and let the metric do the rest - every resolution budget is spent there."),
],
"05-GRMHD/07-AthenaPlusPlus-Overview": [
("What is Athena++?",
 "A general-purpose block-structured AMR astrophysical code family for hydro/MHD/GRMHD, the modern C++ descendant of Athena - used widely for disks and jets."),
("What is its numerical foundation?",
 "Finite-volume Godunov schemes with Riemann solvers (HLLC etc.), MUSCL/PPM reconstruction, and constrained transport for the magnetic field."),
("How does AMR work in Athena++?",
 "Block-based octree AMR with ghost-cell exchange; the grid hierarchy is SMR/AMR capable over runs - blocks are load-balanced across ranks."),
("What MHD closures does it support?",
 "Several EOS, including tabulated and gamma-law; extension modules add radiation, dust, particles, and users' own physics."),
("Why is Athena++ favored for GRMHD?",
 "Explicit, conservative, well-tested, extensible - the 'general purpose' design lets a user specialize (e.g., add HARM-style recovery) without rewriting the core."),
("What is its parallelization model?",
 "MPI+X (e.g., MPI+OpenMP, MPI+CUDA via Kokkos) block decomposition; scaling to tens of thousands of cores for production runs."),
("How does it handle AMR ref/copath?",
 "Block-by-block refinement with conservative restriction/prolongation; the boundary between coarse/fine is internally consistent."),
("What boundary conditions does it offer?",
 "User-defined arrays + standard wall/out/inflow; the GR-specific horizon b.c. is left to the problem setup - documented entry point."),
("How does a GRMHD rate compare to a 3D run?",
 "Athena++ on a 3D GRMHD disk uses ~10^4-10^5 cells^3; 10^5-10^6 steps at extreme cost - production runs are the major use of the field's compute."),
("What observational outputs matter?",
 "Primitive/cons variables at cadence for ray tracing, plus analysis metrics (Mdot, torques, Poynting) - exporters feed the raytracer scene."),
("What is its relationship to HARM?",
 "HARM is simpler (static grids, built for single disks); Athena++ trades for generality - for a custom pipeline, both are viable source-code targets."),
("How do you validate an Athena++ run?",
 "The classic 1D shock/2D Orszag-Tang/3D MRI blocks, plus convergence checks on resolution for the specific disk setup."),
("What's the learning curve for a newcomer?",
 "Configuration XML, problem generation, dumping analysis: the docs are thorough; an expert spins up the disk + jet in days."),
("What is the version/durability reality?",
 "Actively maintained (Fromang, Stone community); extensions from the literature (radiative, PAO) mostly make good base for additions."),
("What is the practical advice?",
 "Match HARM or Athena++ to your needs: simple serendipity grids => HARM; scale + AMR + extras => Athena++ - or hand-roll a minimal setup with your own GHUD."),
],
"05-GRMHD/08-HARM-Overview": [
("What is HARM?",
 "High-Accuracy Relativistic Magnetodynamics - a conservative, stationary-grid GRMHD code from Gammie/McKinney/Tóth, specialized for single black-hole disks."),
("What is its grid?",
 "Analytic coordinate systems (e.g., Boyer-Lindquist-based or 'financial horizontal' grids) with cell volume factors; a fixed hierarchy, no AMR."),
("What is its numerics?",
 "Finite volume conservative form, HLL-family solver, MUSCL/van Leer reconstruction, constrained transport for B, and the now-generic primitive-recovery p-W system."),
("What is the 'p-W' inversion?",
 "Noble et al.'s quartic method for conservative-to-primitive - the famous HARM recovery; robust with floors and fallbacks, at moderate cost."),
("What makes HARM's disk runs cheap and canonical?",
 "Single-hole setups, modest resolutions (e.g., 256^3), semi-analytic initial tori: the standard figures of accretion literature come from it."),
("What are HARM's strengths?",
 "Simplicity, robustness, correctness on disks, and the entire community's library of initial conditions (Fishbone-Moncrief tori) validates it."),
("What are HARM's weaknesses?",
 "No AMR, limited to its analytic grids, somewhat dated C, and a steep curve to modify boundaries vs tree codes."),
("How does HARM handle the outer boundary?",
 "Outflow + floor boundary beyond the 'hot zone'; the outer radius is a free parameter (often hundreds of M)."),
("How does HARM express the stress-energy?",
 "Uses the covariant T^mu\nu with the 3+1 projections; conservative variables remain D, S, tau, B - the same contract as Athena++ GRMHD."),
("What is HARM's time integration?",
 "Second-order RK (or predictor-corrector) with a CFL-limiting step: the standard explicit Godunov marching."),
("How does HARM feed a raytracer?",
 "Dumps provide (rho, u^i, B^i, p) on the grid; the raytracer interpolates them to sample emissivity along geodesics - the exact bridge this package provides."),
("What is HARM's validation history?",
 "The standard tests: Keplerian rotating disk, Bondi-like accretion, and the M87/Millennium initial-data suite - all documented and reproducible."),
("What does HARM provide that's hard elsewhere?",
 "A minimal, legible, single-file-flavored codebase - ideal for a custom raytracer pipeline to couple to and for teaching."),
("What is HARM's status today?",
 "Though old, its algorithms are industry standard and embodied in successors (KORAL, BHAC, Athena++ GRMHD); the legacy is as a reference semantics."),
("What is the takeaway for this project?",
 "Use HARM-style conservative / recovery / static-grid discipline as the reference (even if you run Athena++), because its clean semantics map 1:1 to the raytracer scene file."),
],
"05-GRMHD/09-Primitive-Recovery": [
("What is primitive recovery?",
 "Inverting the conservative-to-primitive map (from D, S, tau, B to rho, p, u^i, B^i) after each conservative update - the bane of every GRMHD code."),
("Why does recovery fail?",
 "Physical conservations permit states outside the recoverable domain (e.g., negative pressure); their causes include floors, extreme flows, and finite-precision algebra."),
("What is the common strategy?",
 "Newton-Raphson on a 2D/3D system (e.g., W = gamma^2 rho h from p-W), with fallbacks: bisection, entropy-based, or truncation to floors."),
("What is the 'p-W' system?",
 "Noble et al.'s variables (p, W) reducing recovery to a 2x2/newtonian subsystem; the standard HARM approach."),
("What is a 1D iterative approach?",
 "A single-variable root-find on the equation c2(W) using only conserved data + the EOS - cheaper, more branches but more fragile when biting."),
("What are the failure triggers in practice?",
 "Near-vacuum cells, strong shocks, and the transition to the jet's empty core - exactly the regions where the visuals matter most."),
("What is the role of floors?",
 "Enforced minima on rho, p, b^2 keep the inverse well-posed; setting them is an art - too high erases physics (jet density), too low breaks the run."),
("How is positivity enforced?",
 "Clamp negative rho/p to floors (or a 'fix' that scales the energy); the loss in conservativity is the price of survival."),
("How does recovery interact with the EOS?",
 "A gamma-law closes W's equation; tabulated/electron-tracking EOS make the inverse loop costlier - a real bottleneck for a raytracer-coupled use."),
("What is the 'energy consistency' check?",
 "Reconstructed W, p must reproduce D, S, tau up to tolerance; the code computes a residual metric - its smallness is the correctness gate."),
("How is recovery vectorized/acclimated for GPU?",
 "Batched Newton loops with fixed iteration counts (avoids divergence) plus rescue paths - the performance-critical branch of the whole scheme on accelerators."),
("What is a well-known trap?",
 "Recovering with B in the wrong frame (lab vs fluid) silently corrupts every derived emissivity; the field must be b^mu in the fluid rest frame."),
("What does a hand-written raytracer need?",
 "The raytracer consumes primitives + B directly from dumps; recovery correctness is the simulation's job, verified once per dump."),
("How do you test recovery?",
 "Clone a full state: P2C then C2P must recover the same primitives to 1e-10; a suite of pathological (high-beta, low-density) states stresses the fallback path."),
("What is the production-level summary?",
 "Robust recovery + floors + Newton fallback: the code plays its part by keeping the innermost cells physical enough to ray-trace without artifacts."),
],
"05-GRMHD/10-Initial-Conditions": [
("What is the canonical GRMHD initial condition?",
 "A Fishbone-Moncrief (or Chakrabarti) torus in hydrodynamic equilibrium threaded by a weak poloidal field - the standard seed for disk simulations."),
("What is the torus equilibrium?",
 "An axisymmetric gas configuration with constant specific enthalpy (uniform angular momentum pattern) in the hole's potential - steady if field is ignored."),
("How is the weak seed field chosen?",
 "A poloidal loop with pressure-balanced beta (e.g., beta=100) through the torus; the MRI then amplifies it - the turbulence onset is seeded, not imposed."),
("What masses/radii are typical?",
 "Torus scale height, inner radius ~ ISCO, outer ~ 30-60M; mass normalized so Mdot is physical after scaling - all set relative to the hole's mass."),
("Why is the initial field tiny?",
 "If beta is astronomically small, MRI saturates immediately and lacks the dynamo phase; a gentle seed lets the code 'grow' its own turbulence."),
("What are the alternatives?",
 "SANE setups (weak field, saturated turbulence) vs MAD (strong field near the horizon); initial B structure decides which attractor the run reaches."),
("How do you set theta/phi discretization to match MRI?",
 "Cells must resolve the MRI's fastest-growth wavelength; the initial setup must satisfy that constraint across the disk - verified a priori."),
("What happens to a mismatched initial state?",
 "Shocks launch, the disk relaxes violently, and the transient can dominate the first 1000 M of output (the 'relaxation phase' to discard)."),
("How does the initial density profile look?",
 "A fish-tail cross-section with maximum at the pressure-support radius, tapers in/out; the code keeps density floors in the halo."),
("What is the role of the fictitious viscosity?",
 "MHD turbulence replaces it; the early transient is effectively the code's way of generating the physical stress - so discard or post-clean it."),
("How do you validate the IC?",
 "Run the torus with B=0: it must remain stationary to simulation precision - the equilibrium-russia test of the metric + grid implementation."),
("What is a common resolution-study starter?",
 "Compare two resolutions (e.g., 128^3 vs 256^3) on the same IC; MRI growth rate/max must match the fastest-growing-mode prediction."),
("What output cadence matters?",
 "Flash-low for discs: aligned analyses like Mdot need cadence < a few x M; the raytracer wants saved snapshots only at its own virtualization times."),
("How are these ICs shared/reproduced?",
 "Standard problem decks in the literature and code repos; document the seed, mass, beta, grid of every run - else results aren't publishable."),
("What is the analyst's golden rule?",
 "Every endpoint claim (Mdot, jet power, ring profile) states the IC and grid it came from; reproducibility is the code's scientific contract."),
],
"05-GRMHD/11-Resolution-and-Convergence": [
("What is resolution in GRMHD?",
 "The number of cells per dimension per characteristic scale; the practical bottleneck of the whole discipline (realistic runs are 3D and huge)."),
("What is convergence?",
 "The property that a resolution increase reduces solution error predictably; for turbulent flows, only STATISTICAL convergence is meaningful."),
("What are the canonical metrics?",
 "Accretion rate Mdot, stress alpha, MRI saturation amplitude, jet Poynting power - each quantified with its error bars vs resolution."),
("How do you establish convergence for a turbulent run?",
 "Run at 2 resolutions; compare time-and-space averaged spectra and the mean of Mdot: converge to a plateau within tolerance = accept."),
("Why is Mdot noisy?",
 "MHRIT turbulence is intermittent; measuring Mdot needs long time-averages (1000M+) to beat the noise - a common pitfall is premature claims."),
("What is the resolution-MRI link?",
 "Resolving the fastest-growing MRI wavelength ~ sqrt(v_A/Omega) regions dictates cell count in the disk midplane; under-resolution kills the dynamo and the turbulence dies."),
("What does under-resolution falsely produce?",
 "Absent turbulence -> smooth laminar accretion -> WRONG image; the death knell of a disk run is a grace-check at insufficient cells."),
("What are the AMR convergence upsides?",
 "Matching local resolution only where turbulence needs it; convergence criteria must be localized, not global (the disk vs jet have different zones)."),
("How do you quantify noise bounds?",
 "Jackknife/block bootstrap on Mdot series gives error bars; compare them across resolutions - the bar's overlap is the honest statement."),
("What is a 'converged quantity' vs a 'trend'?",
 "Local turbulent snapshots never converge (chaos), only statistics do; always label figure captions with the averaged quantities."),
("What is the cost of resolution doubling?",
 "~2^3-2^4x runtime (3D + dt from c/dx): the whole GRMHD field's economics live in this line."),
("How do grids influence apparent convergence?",
 "A log-spaced grid converges differently from uniform; state grids in convergence tests - otherwise 'resolution' claims are ambiguous."),
("What does a resolution test on images give?",
 "The ring profile stabilizes at moderate resolution (image features are macroscopic); the raytracer then sees the COVERGED state - a distinct advantage of images."),
("What is a recommended pattern?",
 "Run 2 medium grids to select a production grid, prove statistics converge on cheap runs, then commit the big one for output."),
("What is the takeaway for the raytracer?",
 "Feed the raytracer converged snapshots; the image quality belongs to the emitter's statistics, not the hole of the ray-solute - assert convergence first."),
],
"05-GRMHD/12-Output-Formats": [
("What outputs does a GRMHD run produce?",
 "Spectral dumps of (rho, u^i, B^i, p, conserved) on the grid, checkpoints for restart, and derived analysis sets (mass/energy fluxes) - the session contract."),
("What are the common formats?",
 "FITS, HDF5, or code-native binary; I/O libraries (HMPI/ADIOS) handle the scale - portability is essential for the raytracer ingestion."),
("How is the grid stored?",
 "Coordinates arrays per axis (in HARM's analytic grids) or full coordinate arrays (AMR); the raytracer's interpolation needs consistent volume/spacing info."),
("What is the cadence strategy?",
 "Full-state dumps for science; high-rate light dumps for variability; checkpoints for crash recovery - the costs differ by 100x."),
("What metadata is critical?",
 "Spacetime parameters (M, a), grid geometry, code units, simulation time, the EOS, floors, and version - the raytracer cannot be correct without them."),
("What do the fluxes include?",
 "Time-integrated Mdot, energy flux, angular momentum flux through surfaces - analysis I/O kept separate from snapshot I/O."),
("How does HDF5 serve the raytracer?",
 "The scene plugin reads rho/u/B/p plus coordinates and interpolation maps - a single strong-typed dataset per snapshot."),
("What is reproducibility metadata?",
 "The full run configuration hash (ICs, patches, code version) attached to every output - the discipline that makes results trustable."),
("How does checkpoint/restart interplay with I/O?",
 "Checks resume from dumps; I/O must be atomic (write temp, rename) or an interrupted write corrupts the run - a known failure mode."),
("What is the compression strategy?",
 "Lossless on checkpoint, lossy-capable on science dumps (HDF5 filters, e.g., bitshuffle); sizes drop 5-10x for negligible visual loss."),
("How are units converted on output?",
 "Code units -> physical via the mass scale factor (M_sun times x); both stored; the raytracer converts invasive quantities explicitly."),
("What does a raytracer scene file need?",
 "Grid parameters, cell data arrays, spacetime params, and frame data - the converter script writes the scene with every unit intact."),
("What is the I/O vs compute time?",
 "Writing full snapshots at cadence can eat 10-20% of runtime; tiered outputs (rare heavy, frequent light) fix the balance."),
("What validation on I/O?",
 "A known-state test file round-trips through writer/reader bit-exactly; the metadata header is schema-versioned to catch stub interface breaks."),
("What is the headline contract?",
 "One schema: 'GRMHD frame' with grid+fields+metadata; converters both ways - the raytracer stays a consumer of the format, and upgrades stay cheap."),
],
"05-GRMHD/13-Coordinate-Systems": [
("What coordinate systems do GRMHD codes use?",
 "Log-radius with (Boyer-Lindquist like) theta for the hole, plus curvilinear/mapped variants - chosen for accuracy and speed near the horizon."),
("What is the 'logarithmic + uniform theta' choice?",
 "r exponential to concentrate inner-grid resolution; theta can be uniform or cosine-weighted (poles) - a standard production grid."),
("What is the 'funpol' / eks-torus mapping?",
 "Analytic mapped grids (e.g., HARM's 'Boyet'/'fnoe' coordinates) that concentrate cells where needed while keeping the metric simple denominators."),
("How does the theta grid behave near the poles?",
 "Uniform theta gives enormous azimuthal cell volumes at the poles (and innermost/bity errors); codes clamp phi there - a geometric quirk to handle."),
("What is the role of a center-staggered vs cell-centered variable layout?",
 "B on face centers (for div-B control), scalars at cell centers - the standard staggered arrangement of constrained transport."),
("How do you map data to the raytracer's interpolation grid?",
 "Either interpolate on the code's native cells (trilinear in (log r, theta, phi)) or remap to a Cartesian prod mesh - the raytracer choice is O(1) lookups."),
("What is the volume element in the code grid?",
 "dVol = sqrt(-g) d^n x in code units; every density/flux reading must divide/multiply by the local volume element (cache it per cell)."),
("What is the horizon-perpendicularness requirement?",
 "For I/O in BL, the innermost cells straddle r+; crossing them stably needs the chart switch (KS) or inflow BC - the grid details encode stability."),
("What is 'concentrating' theta near the midplane?",
 "Use theta grids with dtheta ~ const/sin(theta) to keep constant physical spacing - a production trick to resolve the disk's thin scale height."),
("How do you choose the radial extent?",
 "Inner = horizon flow, outer = floor boundary beyond (e.g., 100-1000 M); the raytracer only needs up to where emission interacts significantly."),
("What nonuniformity breaks a raytracer?",
 "A raytracer that assumes uniform cells mis-weights emission near the inner grid - always use the code's volume element in the emissivity integral."),
("What is the impact of grid stretching on diff0s?",
 "Numerical dissipation is strongest where cells are largest (outer disk); claiming high precision there is unsupported - document cell sizes."),
("How do you validate the grid?",
 "Compute the total volume via the metric vs the grid's dx products: exact agreement is the grid consistency check."),
("What are the pole cells' emission pitfalls?",
 "Near theta=0 the volume element -> r^2 sin(theta) dTheta dPhi -> 0; interpolating emissivity there needs a guard so no zero-divide blows the integral."),
("What is the delivery format of a grid?",
 "Interpolants hold (r_cell, theta_cell, phi_cell, volume) arrays; the raytracer turns cell-coordinates via a precomputed lattice - the coupling contract."),
],
"05-GRMHD/14-Accretion-Physics": [
("What sets the accretion rate?",
 "The turbulent angular-momentum transport (MRI stress alpha) times the surface density; observationally, Mdot ~ alpha (H/R)^2 Omega rho-ish - the Shakura-Sunyaev scaling."),
("What is the Shakura-Sunyaev alpha-disk?",
 "The standard parametrization: viscosity nu = alpha c_s H; alpha ~ 0.01-0.1 from MRI; all disk models start from this concept."),
("How does MHD transport angular momentum?",
 "The Maxwell (B_r B_phi) and Reynolds stresses dominate over molecular; their ratio defines the effective alpha - measurable in GRMHD outputs."),
("What is the MRI (Magnetorotational instability)?",
 "The weak-field turbulence engine: differential rotation stretches and feeds springs in B, destabilizing the flow - the disk's universal dynamo."),
("What is the condition for MRI growth?",
 "The profile must satisfy the Rayleigh criterion (dOmega^2/dr < 0 region) with fast growth ~ Omega; that holds out to ISCO - the instability saturates into turbulence."),
("How does the disk evolve in the saturation?",
 "Balanced transport + inflow: surface density evolves toward the steady-state solution with accretion deluged by the turbulence - the 'steady disk' idealization."),
("What is the Novikov-Thorne standard model?",
 "The thin-disk analytic steady solution with (alpha) transport and inner edge at ISCO - the baseline brightness that GRMHD upgrades beyond."),
("What does GRMHD correct?",
 "ISCO assumption is approximate: plunging regions, magnetic fields, stress at the ISCO all alter the emission (hence image rings differ from NT)."),
("What is the role of electron temperature?",
 "The image's ring brightness depends on raising electrons above ions (Te != Tp via reconnection+electrons cooling); GRMHD outputs gas temp, emission needs the electron prescription."),
("How does Mdot connect to the raytracer?",
 "accretion flushes densities; the raytracer samples rho/B from the run, so Mdot translates into emissivity (through the magnetic field's synchrotron scaling)."),
("What is the disk's scale height H/r?",
 "The dimensionless aspect: hotter/ionized disks puff; the emissivity integration in the raytracer spans full z since H/r can be big (0.1-0.4)."),
("What is the wind/outflow balance?",
 "A fraction of the accreted mass leaves as winds/jets; the observed jet power correlates with the magnetic flux threading the horizon (MAD/explosions)."),
("What is the variability timescale?",
 "Orbital timescale ~ a few x M for the inner disk; observed flickers encode that - the raytracer's movie cadence then pictures the orbit-scale dynamics."),
("What is the observable imprint of the plunging region?",
 "Inside r<=6M the gas plunges; its density/spin structure sets the innermost ring's brightness - arguably the EHT's most exquisite probe."),
("What is the summary statement?",
 "The disk is turbulence-regulated accretion ending at a plunging inner edge; your raytracer renders exactly this plasma state - its realism derives from the simulation, not the camera."),
],
"05-GRMHD/15-Jets-and-Outflows": [
("What are jets?",
 "Relativistic outflows of plasma + Poynting flux along the poles, launched magnetocentrifugally from the spinning hole/disk - visible as the luminous spine rays in renderings."),
("How are they launched?",
 "Blandford-Znajek (BZ): spin power extracted from the hole via the magnetic field's spinning tube; Blandford-Payne (BP): centrifugal sling from the disk."),
("What is the Poynting-flux jet?",
 "Energy flux S ~ B^2/8pi * Omega accelerating plasma against the weak matter - the jet is magnetically-dominated power (low matter, high field)."),
("What distinguishes a BZ from a BP jet?",
 "BZ from the ergosphere/horizon (proportional to a^2, efficient at high spin), BP from the disk itself (proportional to rotation); observed jets blend both."),
("How does MAD vs SANE set jets?",
 "MAD threads the horizon with strong poloidal field -> powerful jets; SANE is weaker-field -> weak jets - the spin+flux combo sets the jet's power."),
("What is the jet's collimation?",
 "Magnetic tension confines; external pressure governs the opening; GRMHD computes the evolutionary collimation directly (the slender/then-parabolic shape)."),
("How does the jet appear in a raytripple?",
 "The jet's low-density high-velocity plasma emits weakly in synchrotron; images show it as the outer brightness/Doppler-boosted lobes around the funnel."),
("What is the funnel?",
 "The evacuated polar region near the hole where plasma density is at floors and the field dominates - the visual 'hidden region' the jet lives in."),
("What is the relativistic speed in jets?",
 "Jet v ~ 0.6-0.99 c via ideal MHD acceleration; beaming hence hugely contrasts the approaching vs receding jet — a striking asymmetry."),
("What is the mass-loading issue?",
 "Actual jet plasma comes from pair production, wind entrainment, magnetopause; ideal MHD with floors creates artificial loading - a known caveat for jet densities."),
("How does spin power drive observations?",
 "BZ power ~ a^2 Mdot c^2-ish; measuring jet power effectively measures a - a link the raytracer films directly through brightness asymmetry."),
("What validation checks jets?",
 "Construct a force-free field + rotating frame: the Poynting flux matches the analytic BZ formula; jet opening/beam speed follow the field geometry."),
("What do movies show about jets?",
 "The jet 'sloshes' as turbulent spikes load it; variability in the spine is a real diagnostic of disk/jet coupling - frame-to-frame features."),
("What does a renderer's jet need physically?",
 "Low-density floor with emissivity from synchrotron + beaming; the emission's polarization and shift trace the field - treat it as the field's tracker."),
("What is the summary?",
 "Jets are magnetically-driven outflows; your raytracer samples their synchrotron beaming - dominant contrast near the poles, strongest spin-dependence in the frame-to-frame morphology."),
],
"05-GRMHD/16-MAD-vs-SANE": [
("What are MAD and SANE?",
 "Two magnetic-accretion regimes: Magnetically Arrested Disk (flux-saturated near the hole) and Standard And Normal Evolution (weak flux, MRI-driven)."),
("What is the MAD state?",
 "Accretion B saturates the horizon-adjacent field, the magnetic pressure halts radial inflow, plasma moves in streams around magnetic islands - strong jets, sharp flux."),
("What is the SANE state?",
 "The field stays MRI-turbulent and weak; the disk is quasi-Keplerian with benign jets - the standard thin-disk picture of the last decade."),
("What is the MAD/SANE diagnostic?",
 "phi_B ~ magnetic flux / sqrt(Mdot) threading the horizon: MAD phi ~ 15+, SANE phi ~ <10 (in suitable normalization) - a well-tested discriminator."),
("How do you reach each state?",
 "The initial poloidal-field strength and mass supply choose the attractor; MAD needs enough flux carried in, SANE preserves the weak seed - the IC matters."),
("How does MAD change the image?",
 "The magnetically-driven inner shell makes the image ring thinner, hotter (electron heating in current sheets) and gaze-strong - a sharp, compact crescent."),
("How does MAD change variability?",
 "Flux eruptions ('flux eruptions' / MAD cycles) produce periodic blowouts - bursts in the image ring brightness - a time-domain signature."),
("How does spin interplay with MAD?",
 "High spin + high flux -> efficient BZ jets and strong frame dragging; MAD is the regime in which spin power is most visible."),
("What does SANE's image look like?",
 "Broader ring, softer profile (more volume emission), brighter extended corona - the images differ enough that M87/Sgr*A* fits discriminate fits."),
("Which is more realistic for M87?",
 "The EHT finds images consistent with strong spin+flux -> MAD-family models fit best; Sgr A* is closer to moderate/SANE - the fits decide."),
("How does the raytracer see the difference?",
 "The emissivity field (rho, B, Te) looks different: SANE's volume-filling vs MAD's thin magnetized shell - the ring profile propagates into the render."),
("What is the resolution burden?",
 "MAD's inner-shell gradients need high inner resolution; its flux tubes are thin - resolution-convergence studies matter doubly there."),
("How does MAD's accretion get into movies?",
 "MAD's intermittent flux supply makes the disk flicker on 10-100M timescales - a distinct movie signature to look for when animating."),
("What validation distinguishes the regimes?",
 "Measure phi_B vs time: the attractor must hold; crossing signals a regime change mid-run (often the IC being wrong)."),
("What is the summary?",
 "MAD vs SANE is a bifurcation in magnetic flux; your raytracer renders either state from its dumps - always label which regime the snapshot carries."),
],
}