"""Curated Q&A for 07-Numerical-Methods leaves."""
NUM = {
"07-Numerical-Methods/01-Euler-and-Midpoint": [
("What is the explicit Euler method?",
 "y_{n+1} = y_n + h f(t_n, y_n): advance using the derivative at the start of the step - simple, first-order accurate, and unstable for stiff/oscillatory systems."),
("What is the convergence order of Euler?",
 "Global error O(h) - first order; halving h roughly halves the error, which is why it is too slow for high-precision ray tracing."),
("What is the stability limit of Euler?",
 "The stability region is a tiny disk; for oscillatory photon geodesics you must keep h very small (h << 1/|imaginary eigenvalue|) or the orbit blows up."),
("What is the midpoint (modified Euler) method?",
 "y_{n+1} = y_n + h f(t_n + h/2, y_n + (h/2) f(t_n,y_n)): a predictor-corrector pair giving second-order accuracy."),
("What is the global error of midpoint?",
 "O(h^2) - second order; double resolution -> quarter error, a big improvement over Euler for a small price."),
("Why is Euler rarely used in production geodesic integration?",
 "Its phase-space precession error accumulates: long photon wanderings drift off the null surface, destroying the shadow geometry."),
("What is the Heun variant?",
 "The average of Euler-predicted and Euler-followed slopes, giving a 2nd-order method: y_{n+1} = y_n + (h/2)(k1 + k2) with k2 at the predicted point."),
("How does the midpoint method handle the null constraint?",
 "It keeps the mass-shell to second order in h; the residual H ~ O(h^2) is acceptable for short rays, marginal for ring-winding photons."),
("What is an implicit Euler?",
 "y_{n+1} = y_n + h f(t_{n+1}, y_{n+1}): uses the derivative at the END of the step; unconditionally stable but requires solving a nonlinear system per step."),
("Why would anyone choose explicit for GR?",
 "Geodesic flows are smooth and moderately stiff; explicit methods with adaptivity (RK45) are far cheaper per step than implicit solves - the pragmatic choice."),
("What is the 'symmetric' midline midpoint?",
 "A midpoint evaluated by symmetric slopes used in some symplectic low-order integrators; slightly better phase-space behavior than a one-sided midpoint."),
("How do you test order of a method?",
 "Run with h and h/2 on a circular geodesic: the error ratio (should be ~2 for 1st order, ~4 for 2nd) reveals the true achieved order."),
("What role does the midpoint method play in RK4?",
 "RK4 generalizes the midpoint idea to four carefully chosen derivative samples; midpoint is essentially its coarsest cousin."),
("Why do interpolation and integration interact?",
 "The step size h limits how finely emission samples are taken; a crude integrator forces expensive re-sampling - another reason multi-purpose RK45 wins."),
("What is the practical takeaway?",
 "Euler is for prototyping intuition, midpoint for teaching; production geodesics want at least 4th-order with adaptivity - the RK-family rules."),
],
"07-Numerical-Methods/02-Runge-Kutta-4": [
("Write the classic RK4 update.",
 "k1=f(y), k2=f(y+h/2 k1), k3=f(y+h/2 k2), k4=f(y+h k3), y_{n+1} = y + (h/6)(k1 + 2k2 + 2k3 + k4)."),
("What is RK4's order and error?",
 "Fourth-order global error O(h^4); doubling the resolution lowers the error ~16x - the sweet spot for smooth geodesic flows."),
("Why is RK4 the workhorse for geodesics?",
 "It needs only 4 derivative evaluations/step (cheap against metric+evaluations), is order 4, and is unconditionally reproducible - the classic choice."),
("How does RK4 preserve conserved quantities?",
 "Not exactly (it is not symplectic); E and L drift at O(h^4) per step. For the modest integration lengths of imaging that drift is negligible."),
("What does 'embedded' mean in RK45?",
 "Extra stages compare an order-5 solution against order-4 to ESTIMATE the error per step - the engine of adaptive stepping (Dormand-Prince)."),
("What is the derivative cost breakdown?",
 "Each stage evaluates metric + metric-derivative (+ emissivity when sampling); ~4 stages mean ~4 field evaluations per accepted step - keep those cached."),
("What is the stability region of RK4?",
 "A moderate disk in the complex plane; for the smooth non-stiff geodesic ODEs, step size is limited by ACCURACY, not stability."),
("How do you choose the initial small step in RK4?",
 "From the local derivative scale: h0 ~ M / max(|p|) is a sane first guess before the adaptive controller takes over."),
("What is the difference between step-size and accuracy for RK4?",
 "Error : h^4 means you can trade step up for error down modestly; but the error constant near the photon sphere grows steeply - adaptivity earns its keep."),
("How is RK4 vectorized on GPUs?",
 "All rays share the same h at a warp level (or independent-step), so stages are batch derivatives - the SIMT pattern is what makes million-ray batches feasible."),
("What is a common RK4 failure?",
 "Crossing the horizon (r < r+) is fine, but crossing coordinate r=0 or the poles can invalidate the metric; guard with chart-specific clamp checks."),
("How do you validate RK4 vs analytic geodesics?",
 "Integrate Schwarzschild circular orbits and compare the closed-form precession; RK4 error should scale as h^4 in the difference."),
("What is the memory cost of RK4?",
 "Stages can be computed and folded without storing: 2 state-sized buffers (yold, work) - memory is tiny next to the emissivity caches."),
("When would you pick RK4 over adaptive RK45?",
 "When step size is known a priori to be safe/small (e.g., short validation rays) - deterministic step count and no controller overhead."),
("What is the consensus for production?",
 "Adaptive Dormand-Prince (RK45) with RK4-stage reuse is the default; raw RK4 remains the clear, bug-free reference implementation."),
],
"07-Numerical-Methods/03-Adaptive-RK45": [
("What is adaptive RK45?",
 "An embedded Runge-Kutta pair (orders 4 and 5) that estimates local error from the two solutions' difference and adjusts h so error < tolerance."),
("What is the error estimate?",
 "err = |y5 - y4| scaled by atol + rtol*|y|; the controller then sets h_new = h * (tol/err)^(1/order) clamped by growth bounds."),
("What are the standard tolerance defaults?",
 "rtol=1e-9, atol=1e-12 are sane for double-precision geodesics; tighter destroys speed near the ring, looser smears the shadow boundary."),
("How does the controller avoid oscillation?",
 "Clamp h growth to x2 and sh-chrink to x10, and use a first-order (or PI) controller - naive power-law stepping oscillates uselessly."),
("What is the Dormand-Prince 5(4) pair?",
 "The classic 7-stage embedded pair (e.g., the 'RK45' in scipy) with 7 function evals per step but FSAL reuse of the last stage - near-free stages."),
("How does adaptive stepping know the photon sphere?",
 "It doesn't directly; the error estimate just forces smaller h where solution curvature is high - the ring winding naturally gets refined."),
("What is the largest step allowed?",
 "A local-bound clamp like h < 0.5 M prevents 'tunneling' through strong-field features even when the local error is tiny."),
("How does adaptivity interact with emission sampling?",
 "The same refined steps are natural quadrature points for j ds - a shared adaptive grid saves a second interpolation pass."),
("What happens to a bouncing turning point?",
 "Near r' ~ 0 the derivative magnitude drops; error-based stepping can overstep the fold - add a velocity-based min-h guard at turning points."),
("How do you measure acceptance rate?",
 "Fraction of accepted steps; production rays should accept >85% (badly-tuned tolerances sit below 60% and waste the whole budget)."),
("What is the cost of adaptivity?",
 "Rejected steps re-evaluate derivatives; but the alternative (fixed tiny h everywhere) wastes far more - adaptivity typically wins 10-50x on ring winding."),
("How do you preserve affine-parameter smoothness?",
 "Store h monotonic and the affine lambda integral; emission weighting uses dlambda reliably across adaptive steps."),
("What validation confirms the controller?",
 "Global error test: integrate a ring-winding ray; the shadow boundary must be stable to 1e-6 in impact parameter as tolerance tightens."),
("What is the tradeoff of tight tolerance?",
 "Each order-5 improvement demands ~(tol ratio)^(1/5) more steps near the ring - a 1e-9 vs 1e-8 decision can double runtime for invisible gain."),
("What is the practical recipe?",
 "Adaptive RK45 with RTOL 1e-9, h_max ~ 0.5 M, turning-point guards, FSAL stage reuse, and error-based emission sampling - the production default."),
],
"07-Numerical-Methods/04-Error-Control": [
("What is the purpose of error control?",
 "To keep the GLOBAL solution error within a defined tolerance while spending the minimum number of derivative evaluations - quality at minimum cost."),
("What is local vs global error?",
 "Local: the error committed in ONE step; global: accumulated over the whole path. Global ~ local_error * (number_of_steps)^(1/2) for random, or ~ n*local for systematic drift."),
("How do you choose atol vs rtol?",
 "atol sets the absolute floor (protects near-zero states), rtol the relative scale; geodesics use rtol-dominated settings with a tiny atol."),
("What is the 'step accepted but wrong' failure?",
 "Local error passes, but the solution has drifted off the null shell (H != 0): the null residual must be independently monitored as a physical error."),
("What is the error estimator's validity?",
 "Embedded pairs estimate LOCAL error to one order higher; using it as GLOBAL tolerance is an approximation - validate globally a few times."),
("What is the role of the null-residual monitor?",
 "Track |2H| = |p^2| along the ray; if it exceeds a bound (e.g., 1e-8 of E^2), subdivide the next step - a safeguard independent of step size."),
("How is error distributed over space?",
 "The controller makes local error uniform; regions of high curvature (ring) get more steps - this 'equidistribution' is exactly what you want for smooth imaging."),
("What is the effect of tolerance on shadow edge sharpness?",
 "Tolerances too loose blur the capture boundary (rays misclassify); tighter tolerances sharpen it at cost - a quality knob, not a physics toggle."),
("What does IEEE/roundoff impose?",
 "Roundoff ~ 1e-16 per operation; error control can't see below ~1e-14 on doubles - never ask for tighter tolerances, they silently plateau."),
("What is a 'swamp' of rejected steps?",
 "Near a steep fold the controller bounces between acceptance/rejection; a bounded step count with last-step fallback avoids wasted iterations."),
("How do you validate error control?",
 "Compare a reference high-tolerance integration against looser runs for a set of representative rays; the shadow boundary must stabilize monotonically."),
("What is the cost model of a rejection?",
 "A rejected step wastes its stages AND forces a re-evaluation - keep rejection < 15% or the adaptivity budget evaporates."),
("How does error control interact with emission?",
 "Emissivity sampled at accepted steps is consistent with the trajectory; error-controlled integration doubles as the quadrature grid - no mismatch."),
("What is the golden rule?",
 "Set error control to the worst-case NEED (ring resolution), then verify globally - never trust local control without a full-path residual check."),
("What is the summary?",
 "Error control balances accuracy and cost: local embedded estimates + null-residual monitoring + global validation - the contract of the integrator's quality."),
],
"07-Numerical-Methods/05-Stepping-in-Singular-Fields": [
("What are the singularities a geodesic integrator faces?",
 "The horizon (coordinate singularity where Delta=0), the axis/theta=0 poles, and r=0 (true curvature singularity) - each needs distinct treatment."),
("How do you integrate through the horizon?",
 "Switch to a regular chart (Kerr-Schild) AT the horizon radius, or integrate in a chart already regular there; dividing by Delta in BL is forbidden."),
("What is the 'BL freeze' symptom?",
 "In Boyer-Lindquist the radial coordinate slows near r+; naive integrators see dt/dlambda explode - the coordinate, not the path, is pathological."),
("How do you treat theta ~ 0 poles?",
 "The phi-coordinate becomes undefined; guard rhs evaluations by switching to a Cartesian-like parameterization or clamping theta minimally above 0."),
("What happens when r -> 0?",
 "The metric terms diverge (Sigma -> a^2 cos^2, Delta -> a^2); never integrate to r=0 - capture triggers at r+ but protect r < r_tiny as 'captured' too."),
("How is a coordinate singularity detected?",
 "Monitor quantities like Delta or g_rr hitting zero/tiny; the integrator flags 'chart invalid' and can switch geodesic frames mid-path."),
("What is a chart-switch (BL -> KS) transition?",
 "Convert (t, r, theta, phi) and momenta via the exact coordinate and momentum transformation formulas at a chosen r_switch > r+ - done continuously, not stepwise."),
("What is the 'horizon-crossing detector'?",
 "Bracket the sign change of r - r+ between steps; a bisection/Newton smart step locates the crossing without waiting for the next step."),
("How do you avoid near-zero division in the metric?",
 "Clamp Delta to a floor (e.g., 1e-8 M^2) in the pure-BL metric while you still use it, or better: don't use BL near the horizon."),
("What is a 'point of no return' for the integrator?",
 "Once r < r+ and p_r is definitively inward, further integration only serves the (doomed) photon's history - stop at capture to save work."),
("How do pole-crossing rays behave?",
 "A ray passing near theta=0 gets phi-severe; in Kerr-Schild or cylindrical systems this is smooth - mapping matters more than tolerance."),
("What is the affine-parameter blowup near the horizon?",
 "t grows without bound but lambda stays smooth; keep the affine parameter as the independent variable to avoid time-coordinate nastiness."),
("How do you validate singular-field handling?",
 "A radial infall in Kerr: the photon must cross r+ with finite lambda, produce the same capture flag in BL-with-switch and pure-KS - agreement is the test."),
("What is the recommended chart strategy?",
 "Integrate in Kerr-Schild from the start (or switch before r ~ 4M); keep BL only for analytic verification - singular regions simply don't arise."),
("What is the summary?",
 "Singular-field stepping means: choose charts where the metric stays regular, switch intentionally, detect horizon/pole crossings, and never chase r=0."),
],
"07-Numerical-Methods/06-Bilinear-Interpolation": [
("What is bilinear interpolation?",
 "Interpolating a 2D field using the 4 surrounding grid points: linear along x then along y - the standard cheap sampler on a structured grid."),
("Write the bilinear formula.",
 "f(x,y) = sum_{i,j} f_{ij} w_i(x) w_j(y), where weights are the fractional positions along each axis - effectively f = (1-wx)(1-wy)f00 + wx(1-wy)f10 + (1-wx)wy f01 + wx wy f11."),
("Where is bilinear interpolation used in the raytracer?",
 "Sampling emissivity/fields from the GRMHD grid in (r, theta), (log-r, theta), or image-plane interpolation - 2D slices of the 3D data."),
("What is the continuity property?",
 "Bilinear leaves the field continuous across cell edges but the DERIVATIVE (gradient) is discontinuous - the 'kink' artifact of low-order sampling."),
("What is the error of bilinear?",
 "O(h^2) in each direction for smooth fields - adequate for emissivity but visible on the ring if field gradients are sharp (resolve by grid choice)."),
("How does it compare to nearest-neighbor?",
 "Nearest is O(1) and discontinuous (pixel-crisp artifacts); bilinear is smoother at the cost of 4 fetches - the minimal smooth sampler."),
("What is the coordinate mapping requirement?",
 "The sample point's cell index and fractions must be found; on a log-r grid compute ix = log(r/r0)/dx_real, on theta uniform it is linear."),
("How is bilinear done on GPU?",
 "4 texel loads via texture units or manual gathers; texture hardware with FILTER_LINEAR handles exactly this - a free hardware accelerator."),
("How does bilinear handle field edges?",
 "Outside the grid, clamp or assign background; the outer boundary's floor density often legitimately extends flat - define the policy once."),
("What is the interplay with adaptive steps?",
 "Sampling points land anywhere in a cell; bilinear gives a smooth view even when steps are coarse - the integrator and sampler decouple."),
("What are the artifact fingerprints?",
 "Grid-aligned 2x2 corrugation of emission (visibly 'pixel-webbed') signals insufficient smoothness - telltale of bilinear on an under-resolved grid."),
("What validation checks the sampler?",
 "Interpolate a LINEAR analytic field (f = a r + b theta): bilinear reproduces it exactly - the universal sampler correctness test."),
("When do you upgrade to bicubic/trilinear?",
 "When ring brightness oscillates every other pixel (grid-scale ringing) or polar artifacts appear - the point where higher-order beat bilinear's cheapness."),
("How does bilinear drive the emission integral?",
 "The line integral's quadrature samples j at interpolated field values - the sampler IS the emissivity's accuracy backbone in thin-emission regions."),
("What is the summary?",
 "Bilinear is the pragmatic 2D sampler - smooth-enough for well-resolved grids, cheap, GPU-native, and validated by the linear-field test."),
],
"07-Numerical-Methods/07-Trilinear-Interpolation": [
("What is trilinear interpolation?",
 "The 3D extension of bilinear: interpolating a field from its 8 surrounding cell vertices using the product of the three axis weights."),
("Write the trilinear form.",
 "f = sum_{i,j,k} f_{ijk} w_i(x) w_j(y) w_k(z) - the 8-term weighted combination of the cube's corners."),
("Where is trilinear used?",
 "Sampling GRMHD fields (rho, B, T) at arbitrary points along geodesics in the 3D volume grid - the main data-sampling path of the raytracer."),
("What are its smoothness properties?",
 "Continuous across cell faces, but gradients jump at cell boundaries - acceptable on well-resolved production grids, visible otherwise."),
("What is its error order?",
 "O(h^2) for smooth fields (second-order accurate) - same as bilinear; grid resolution, not the method, dominates the residual error."),
("How is computation organized?",
 "8 fetches, 3 fractional positions, 7 lerps (or the fast 'lerp-lerp-lerp' tree) - trivially vectorizable and cheap in registers."),
("What is the GPU hardware path?",
 "Treat each field as a 3D texture with FILTER_LINEAR; hardware linear trilinear sampling beats hand-written code and keeps row caches warm."),
("How do axes map to the GRMHD grid?",
 "Typically (log r, theta, phi) as (x, y, z); compute indices+fractions per axis from the coordinate functions of each cell array."),
("What are edge/pole policies?",
 "Beyond the outermost cell clamp/away; at theta poles, average azimuthal neighbors to avoid a singular weight - document the pole convention."),
("How does it handle differently-sampled fields?",
 "rho/B/Te may live on different staggerings (cell-center vs face); species either interpolate the common centers or pre-average staggered fields once."),
("What artifacts does trilinear show on coarse data?",
 "Cell-cornered 'checks' in the emissivity map - jagged cell-boundary brightness - the sign of too few cells far more than of the sampler."),
("What validation proves logic?",
 "Interpolate a linear 3D field f = a x + b y + c z: trilinear reproduces exact values everywhere - the fundamental sampler test."),
("How does trilinear interact with octree/AMR?",
 "On uniform subgrids it is local; crossing AMR level boundaries requires the parent/child value (or a coarse blend) - an explicit boundary policy."),
("What is the cost-per-sample comparison?",
 "8 fetches vs 4 for bilinear; but for 3 physics fields the marginal cost is cache misses, not arithmetic - batch per-ray field fetches together."),
("What is the summary?",
 "Trilinear interpolation is the volume sampler of the raytracer - second-order smooth, GPU-texture-friendly, validated by exact linear-field reproduction."),
],
"07-Numerical-Methods/08-Voxel-Traversal": [
("What is voxel traversal?",
 "Efficiently walking a ray through a uniform 3D grid, visiting exactly the cells it passes - used for grid-space ray intersection and AMR sampling."),
("What is the classic algorithm?",
 "The Amanatides-Woo (DDA-style) marching algorithm: per-axis slab stepping with boundary crossing at exactly one axis per step - O(cells crossed), not O(grid cells)."),
("Describe the DDA/Amanatides-Woo traversal.",
 "From a cube, compute t_next for the next crossing along each axis via tMax update (t_cross = (boundary - pos)/dir), then step to the smallest tMax - a 3-branch loop."),
("What is a 'voxel' in the raytracer?",
 "A GRMHD grid cell (e.g., uniform in (log r, theta, phi) or physical space cells) holding interpolated field values; the ray samples along it."),
("Why traverse voxels explicitly?",
 "It gives a FREE ordered list of cells for emission accumulation, cull-by-cell skipping of empty regions, and exact cell-entry/exit for the transfer integral."),
("How does traversal handle the horizon recap?",
 "Cell-boundary axis touches determine the ray's step endpoints - the capture/disc crossing is detected when a cell face coincides with r = r+ or z = 0."),
("What are empty-cell skips?",
 "Cells below a density/emissivity threshold are skipped in two of traversal or a per-cell opacity test - real cost saving in the outer vacuum."),
("How is traversal different from stepping the geodesic?",
 "Geodesic stepping advances in affine parameter (curved path); voxel traversal assumes (nearly) straight segments between adaptive geodesic points."),
("What is the hybrid pattern?",
 "Adaptive geodesic steps produce a polyline in field space; each geodesic segment is then voxel-traversed for the quadrature - combining both worlds."),
("What is the cost model?",
 "One cell visit per cell crossed: O(n_cells) work regardless of grid size - a massive win vs brute-force 'check every cell' for large 3D grids."),
("How do you handle the log-r grid in traversal?",
 "Traversal works in CELL-INDEX space: map each point to (i,j,k), step indexes, and convert back to physical coordinates for field sampling - no metric distortion issues."),
("What are the boundary cases?",
 "Ray outside the grid (skip/adjust t-entry), ray parallel to an axis (infinite tMax - guard), and empty-cell skips near floors (avoid sub-step ghosting)."),
("What validation tests traversal?",
 "Compare cell-sequence output vs a brute-force 'all cells intersected' check for random rays on a small known grid - sequences must match exactly."),
("How is traversal vectorized?",
 "Independent rays traverse independently (batch of rays in SIMD lanes); the branch-heavy per-cell loop tolerates warp divergence thanks to short remainder."),
("What is the summary?",
 "Voxel traversal gives ordered, cheap cell visits along the ray - the efficient bridge between curved geodesics and the gridded GRMHD fields."),
],
"07-Numerical-Methods/09-Octree-Adaptive-Stepping": [
("What is an octree in this context?",
 "A hierarchical spatial partition (8 children per node) refining cells where needed - used for adaptive SPATIAL resolution of the emission field and AMR grids."),
("How does an octree speed ray tracing?",
 "Ray-vs-octree traversal prunes entire empty regions in O(log n) - only cells near the path get touched, vs scanning whole uniform grids."),
("What is the refined-geometry use?",
 "Where the emission or B-field gradient is steep (inner disk, current sheets), refined leaves give finer quadrature without global resolution cost."),
("How is an octree built from the GRMHD grid?",
 "Recursive subdivision: a node splits when the field variation over it exceeds a threshold (density/B jump); leaves store constants or small basis data."),
("What is the ray-octree probe?",
 "Descend the tree along the ray's segment: if a node's bounding box is empty (below emissivity), skip; else recurse to leaves and accumulate."),
("What is the cost vs accuracy tradeoff?",
 "Octree skips empty space (speed) but adds pointer-chasing (latency); a well-balanced tree beats uniform traversal 5-20x in the vacuum-dominated scene."),
("What is the relation to AMR simulations?",
 "The simulation's own AMR (Athena++ blocks) maps naturally into an octree-forest of blocks; the raytracer reuses that hierarchy directly."),
("How is adaptive stepping different from octree?",
 "Adaptive stepping is TEMPORAL (step size along lambda); octree is SPATIAL (grid spacing). The best codes blend both: refined cells also refine allowed steps."),
("What are the traversal pitfalls?",
 "Fractional cache misses, tree imbalance, and the box test fragility near tan boundaries - validate with the uniform-grid comparison test."),
("How do you measure the benefit?",
 "Render with and without octree culling: same output histogram, time-profile shows the skip savings - prove nothing changed but the speed."),
("What fields suit octrees?",
 "Sparse emission (compact disk + jet + vacuum): huge pruning. Uniform hot envelopes: almost no pruning - use a flat grid there."),
("How is the octree stored on GPU?",
 "Linearized breadth-first arrays (node slabs with child offsets) support GPU-friendly traversal without recursion; build once per snapshot, reuse per frame."),
("What validation confirms tree correctness?",
 "A random-ray sweep: the octree-accumulated total (input intensity) matches the brute-force uniform-grid integral to tolerance for a fixed image."),
("What is the summary?",
 "Octree adaptive sampling prunes empty space and refines hot regions - the spatial spatial-coordinate complement to adaptive geodesic stepping."),
],
"07-Numerical-Methods/10-Termination-Criteria": [
("What are the termination criteria for a ray?",
 "Four exits: HIT (reached the emission surface), CAPTURE (crossed the horizon), MISS (left the bounding domain), and BUDGET (step count exceeded) - each mapped to a pixel contribution."),
("What is the HIT condition?",
 "The ray crosses the disk/emission surface (e.g., z=0 crossing for a thin disk, or a volume emissivity threshold); refined by the bracketing/bisection finder."),
("What is the CAPTURE condition?",
 "r <= r+ (chart-dependent) with an inward component; the pixel is black (shadow) - the geometry's own cutoff."),
("What is the MISS condition?",
 "r > r_out (far boundary, e.g., 2000 M) with decreasing contribution; the pixel gets sky or the far-field integral's end."),
("What is the BUDGET condition?",
 "A safety cap on steps per ray (e.g., 50k) to bound worst-case cost near the ring - rare and flagged rather than silently truncating."),
("How do you detect the disk HIT accurately?",
 "Bracket the sign change of (z - 0) or (r - r_disk) between geodesic steps, then bisect/refine to sub-pixel accuracy without extra ODE work."),
("Why have termination at all?",
 "Without it, winding rays near the photon sphere integrate forever; explicit criteria convert 'hard to integrate' into 'correctly sampled boundary'."),
("How do you guarantee no ray 'gets stuck'?",
 "Along with BUDGET, monitor affine-parameter progress delta-lambda-per-step; if it shrinks below a floor while H>0, force a step and report it."),
("What do you record on termination?",
 "Hit (position, redshift, accumulated I/Stokes), capture (flagged), miss (sky direction or zero), and any budget warnings - the event record per pixel."),
("How do termination criteria affect quality?",
 "A too-tight BUDGET near the ring truncates winding rays -> faint outer 'echoes' of the ring - set the cap high enough that truncations stay < 1% of pixels."),
("What is the interplay with supersampling?",
 "Rays terminate independently; pixel value averages over terminating statuses - a mix of HIT/MISS at a boundary pixel is the natural blend."),
("How do you validate termination?",
 "Trace the analytic shadow: terminate exactly at b = b_crit boundary rays must land in the expected pixel class (capture vs miss) within pixel tolerance."),
("What is the far-field sky termination?",
 "r_out chosen far enough that the residual deflection is negligible (< 0.1 pixel); verified by doubling r_out and checking pixel colors unchanged."),
("What is the summary?",
 "Termination criteria are the ray's contract: hit/capture/miss/budget, each precisely defined and validated, turning infinite geodesics into finite rendering."),
],
"07-Numerical-Methods/11-Accumulation-and-Averaging": [
("What is accumulation in the raytracer?",
 "Summing per-ray contributions (intensity, Stokes) into image pixels - the pixel's value is the (weighted) sum over its rays, often with supersampling weights."),
("How does the RTE feed accumulation?",
 "Each terminated ray, ending successfully, contributes its integrated I (and Q/U/V) to the pixel; multiple rays per pixel average via their sampled directions."),
("What is supersample averaging?",
 "Averaging N rays per pixel (stratified jitters) reduces variance ~ 1/sqrt(N); the process of accumulation+division by N is the pixel estimator."),
("What is Monte Carlo variance and its control?",
 "Rays hitting the turbulent innermost region fluctuate; accumulation stores the sum AND sum-of-squares for a variance estimate - the confidence-band channel."),
("How do you accumulate weighted by the ray's importance?",
 "Importance sampling folds a probability weight into each ray; accumulation keeps the weighted sum and the total weight separately for unbiased estimates."),
("What is the accumulation format?",
 "Float or double accumulation buffers per pixel (I, Q, U, V, weight, count); doubles prevent loss near the ring where dynamic range spans 10^4."),
("How does anti-aliasing emerge from accumulation?",
 "The image-plane jitter + accumulation is exactly a box anti-alias; sub-pixel blur for the ring boundary is the practical anti-flicker."),
("What is time accumulation for movies?",
 "Frames accumulate one instantaneous snapshot each; temporal averaging (integration time) is an explicit choice in the movie generator - different from spatial averaging."),
("How do you normalize intensity to physical units?",
 "Multiply the accumulated sum by the (Jacobian/area factor)/N_rays and the reference-band flux - the calibration done once in the post-pipeline."),
("What is a stratified vs random jitter?",
 "Stratified splits the pixel into N sub-cells (Nyquist-friendly low variance); pure random is standard MC - stratified is the production choice."),
("How is the shadow's signal-to-noise computed?",
 "The variance channel per pixel -> error bars for ring and shadow diagnostics - the honest uncertainty output the analysis stage needs."),
("What is the role of the accumulate kernel on GPU?",
 "Each thread owns a (sub)pixel accumulator; the kernel atomically averages per pixel across threads for variable-ray-count pixels (atomicAdd for weight+value)."),
("What validation checks averaging?",
 "Uniform emitter: pixel RC frequency must reproduce the analytic flat profile; the sample variance must match the theoretical 1/N scaling."),
("What is the summary?",
 "Accumulation and averaging convert thousands of ray events into robust pixel estimates - weighted sums, variance channels, and stratified supersampling."),
],
"07-Numerical-Methods/12-Numeric-Precision": [
("What numeric types does the integrator use?",
 "Double (64-bit) for phase-space and metric; floats for emissivity textures and image buffers where the 6-7 digit precision suffices for display."),
("What is the roundoff limit?",
 "~ 2^-52 relative on doubles; error control can't push global error below ~1e-13 without compensated arithmetic - never request tighter tolerances."),
("What is catastrophic cancellation?",
 "Subtracting nearly equal numbers (e.g., r near r+, (r - 2M) small) loses digits; rewrite as (r - r+)*(r - r-) where possible."),
("Where does cancellation bite in GR?",
 "The Kerr metric terms (r^2 - 2Mr + a^2) and redshift ratios near the horizon - restructure formulas or the adaptive step chases ghosts."),
("What is Kahan compensated summation for the accumulation?",
 "Summing thousands of ray contributions naively drifts; Kahan/Neumaier summation keeps the running error ~machine-epsilon - a must for the pixels."),
("What is the 'epsilon drift' of conserved quantities?",
 "p_t/p_phi drift 1e-13 per step with doubles; over 10k steps the total ~1e-9 - acceptable, but monitor it as the integrator's health meter."),
("How do you choose float vs double per stage?",
 "State, metric, momenta: double; texture/emissivity data and final image: float; keep one 'precision layout' documented to avoid mixed-product surprises."),
("What is the role of long double/quad?",
 "Available as a fallback near the ring for debugging; production stays double for speed - long double is 2-4x slower and often maps to the same hardware."),
("What are the GPU precision traps?",
 "Different GPUs compute transcendentals differently; deterministic reproducibility requires fixed (sin/cos/sqrt) function selection and fmaf/FMA discipline."),
("How do you check NaN/Inf?",
 "Guard the metric and momentum updates: any NaN infects the whole frame - report the ray's initial (pixel, direction) plus step history for the debugger."),
("What is the accumulate normalization precision risk?",
 "Dividing the pixel sum by N_rays after adding floats loses small contributions; accumulate in double, convert only at I/O."),
("How is determinism validated across runs?",
 "Same input+tolerances must produce bit-identical frames; if not, audit thread-order reductions and instruction selection - reproducibility's bedrock."),
("What precision does the shadow boundary require?",
 "Pixel-scale b resolution ~ 0.1%/shadow; double with the guarded metric gives that comfortably - floats alone blur it to ~1%."),
("What is the summary?",
 "Numeric precision discipline: doubles for physics, compensated sums for outcomes, cancellation-avoiding metric algebra, deterministic GPU math - the foundation of trust."),
("How do you communicate precision settings in logs?",
 "Log precision plan + residual drift + reproducibility hash with each render - so a downstream claim of '1e-6 shadow' is actually checkable."),
],
"07-Numerical-Methods/13-Debugging-Numerics": [
("What is the first debugging move for a geodesic integrator?",
 "Reduce to M=0 (Minkowski): every geodesic must be a straight line - any bending here is a bug in the metric/initialization, not physics."),
("What is the second test?",
 "Static symmetric cases: a ray straight in/out of Schwarzschild, and the circular null orbit at r=3M - closed-form anchors for the metric+integration."),
("How do you use conserved quantities to debug?",
 "Plot E, L, Q (or H) along the ray; a sudden drift localizes the bad step (wrong Delta, wrong momentum update, chart switch glitch)."),
("What is the lopsided H test?",
 "Always print H=p^2 at key points; monotonic/step-correlated H growth indicates either step-size or algebra drift - bisect step boundaries to find the offender."),
("How do you isolate a bad field (emissivity) vs bad geodesic?",
 "Render with emissivity=constant in a known region: if the image mismatches the analytic geometry, the geodesic geometry is at fault; else the field sampling."),
("How do you inspect a specific pixel?",
 "Save one ray's full (lambda, r, theta, p_r...) log to a CSV; compare turning points against the effective-potential analytic roots - pinpoint the discrepancy."),
("What are unit tests worth in this domain?",
 "Metric round-trips (BL<->KS), geodesic deflection, shadow boundary, Doppler factor, sampler reproduction - each is a tiny, order-independent regression test."),
("What is the least-floating-point hint?",
 "Recompile with -ffp-contract=off and the same FPU; if frames change, your algebra depends on fused-multiply-add order - standardize it."),
("How do you spot grid/sampler bugs?",
 "Render a field grayscale (e.g., just rho interpolated): sharp grid-cornered edges reveal axis mapping/octree errors mis-indexed by one cell."),
("What is the golden 'M=1, a=0' baseline?",
 "Schwarzschild must produce a perfectly circular shadow at 3 sqrt(3) M and ring at the photon-sphere bands - deviation = geometry bug."),
("How do you debug the horizon crossing?",
 "Log r - r+ per step near capture; a jagged sign pattern near the boundary means the bracket detection needs tuning, not the physics."),
("What is the divergence-stuck pattern?",
 "A ray whose step count hits BUDGET while oscillating in place near a turning point: add the min-step floor or localized error-clamp the controller."),
("How do you compare against a reference CPU raytracer?",
 "Integrate the identical ray in double precision with a high-tolerance CPU RK45; the GPU kernel must match within its documented tolerance - the parity test."),
("What is the signature of a chart-mapping bug?",
 "Smooth image everywhere except a hard azimuthal seam at phi = +- pi - the classic sign flip in the phi coordinate wrap."),
("What is the summary?",
 "Debugging numerically means: analytic anchors first, conserved-residual localization, per-pixel logs, unit regressions, and a fixed FP contract - systematic and fast."),
],
"07-Numerical-Methods/14-Integrator-Performance": [
("What dominates geodesic-integration cost?",
 "The derivative evaluations - each stage recomputes metric components and (when sampling) interpolated fields; reducing stages or caching per-position values wins big."),
("What is the stage-cache trick?",
 "During one RK step, the 4-7 derivative calls share the same fields per position; reuse computed metric/e/momentum factors between stages where valid."),
("How do you batch rays for the GPU?",
 "Arrange a warp/block of rays at similar lambda; each SIMD lane integrates one ray but derivative kernels evaluate all lanes' states as a uniform vector op."),
("What is the occupancy vs latency tradeoff?",
 "High occupancy hides memory latency in field fetches, but too many resident blocks thrash the cache - tune the launch config with the profiler, not guessing."),
("What is the value of the metric-derivative cache?",
 "The 5 metric components + derivatives across ~6 distinct (r,theta) per step: precompute the common (Sigma, Delta) factors and fold them into registers."),
("How do you reduce steps overall?",
 "Larger tolerance with turning-point guards, chart switches that keep h sane, and pre-classifying empty-space skips (octree/voxel) reduce total steps 2-10x."),
("What is the role of warp-synchronous stepping?",
 "Members of a warp share a step size (best-case uniformity) so derivative kernels run in lockstep; decoupled independent steps cost divergence - batch adaptively."),
("How is memory bandwidth spent?",
 "Field texture fetches (trilinear) dominate bandwidth - keep fields in fast memory (texture/L2-resident), batch per-warp fetches, and prefetch the segment list."),
("What is the multi-frame reuse play?",
 "Static geometry (metric, chart, capture table) is identical across frames; only emissivity state changes - reuse the geodesic paths, recompute only I per frame."),
("How do you measure performance?",
 "Profile with Nsight Compute: rays/sec per kernel, occupancy, and per-stage cycles; target >50% utilization of ALU in the metric/evaluation kernels."),
("What is the batched analytic-vs-integrated decision?",
 "For symmetric/dense tokens where separation works, reduced (HJ) 1-2 ODE integration is 5-20x faster than full 8-D - invest where rings dominate the cost."),
("What is the allocation-free rule?",
 "No per-ray allocations in the hot loop: pre-size ray-state slabs, in-place queues for emission samples, and per-frame scratch reuse."),
("How do you validate that optimization didn't break physics?",
 "The optimized renderer must match the reference within its documented tolerance on the golden tests (deflection, shadow, ring) - perf claims require the parity check."),
("What is the performance target?",
 "A 2k x 2k image at 16 rays/px in C(seconds)/frame on one GPU is realistic for RK45+trilinear+reuse; under-tuned code runs 50-100x slower - measure first."),
("What is the summary?",
 "Integrator performance = fewer/eval-cheap derivatives, register-cached metric math, warp-batched stepping, empty-space culling, and frame-to-frame geodesic reuse."),
]}