"""Curated Q&A for 08-GPU-Performance leaves."""
PERF = {
"08-GPU-Performance/01-Coalesced-Access": [
("What is coalesced memory access?",
 "When threads in a warp access consecutive memory addresses, the GPU services them in one (or few) memory transactions - the single most important GPU bandwidth rule."),
("Why does coalescing matter for a raytracer?",
 "Field fetches (emission data, grid arrays) and ray-state buffers dominate memory traffic; non-coalesced access can waste 32x the bandwidth on the same data."),
("How does a warp's access become coalesced?",
 "Thread i of the warp reads address base+i*stride; the memory controller merges them into a transaction covering a contiguous segment."),
("What is the typical pattern for ray state?",
 "Structure-of-Arrays (SoA): all threads' p_r live in one array, so a warp accesses p_r[ray] consecutively; AoS scatters 8 separate cache lines per thread."),
("What is a misaligned access penalty?",
 "A warp touching 32 scattered floats faults 32 separate transactions - reducing effective bandwidth to ~3% - the pathology of naive AoS photon storage."),
("How do grid/texture fetches stay coalesced?",
 "Threads within a warp sample nearby cells (similar rays), so their texture fetches hit overlapping cachelines - spatial locality in the field array."),
("What is the role of the sector (cache line)?",
 "Memory is fetched in ~32-byte sectors; coalescing maximizes the fraction of each sector that is used - aim for full-sector utilization."),
("How do you check coalescing?",
 "Nsight Compute's memory section reports 'Memory Throughput' and 'Coalesced' metrics per kernel; a low bus-utilization fraction of theoretical bandwidth means a fix is due."),
("What is the 'vectorized' variant?",
 "Wider loads (float4) let one transaction carry 4 values per thread - if the array layout allows, the base/stripe can be widened to 16-byte requests."),
("How does coalescing interact with adaptivity?",
 "Adaptive rays of different lengths hide and draw from different buffers; a 'gather' (warp-uniform) step where all threads use the same arrays keeps it tidy."),
("What is the pitfall of dynamic indexing?",
 "Per-thread unique indices (e.g., emissivity-lookup by hit index) can scatter; reorganize so the index is a shift of threadIdx (layout restructure, not magic)."),
("What is the 'ray-index to pixel-index' mapping?",
 "If each ray corresponds to consecutive pixels (tile iteration), memory, image-level statistics, and the final write-out all stay coalesced - one decision, compounding."),
("How do you validate coalescing?",
 "Render with the profiler's 'memory workload analysis'; goal: coalesced float4 mains / peak, plus a manual inspection of warp-access traces for hot kernels."),
("What is the summary?",
 "Coalescing = warp-compact, contiguous, vectorized memory - the first habit of GPU raytracer performance; check it before micro-optimizing arithmetic."),
],
"08-GPU-Performance/02-Shared-Memory": [
("What is shared memory?",
 "On-chip SRAM per thread block, visible to all threads of the block - the fastest re-usable data beside registers, ~40-100x faster than global."),
("What does shared memory buy a raytracer?",
 "Caching a block's local grid slab (emissivity/frontier cells) so every thread's trilinear fetch reads once from global instead of 8 times."),
("What is the classic tiled use?",
 "A block processes a tile of rays over the same grid neighborhood; the neighborhood's field values load once into shared, then all rays interpolate locally."),
("What is the tradeoff of shared vs texture fetch?",
 "Shared gives explicit control and cheap reuse but uses an explicit copy; texture/L1 does implicit caching - for per-ray random-ish sampling, texture may win."),
("How big is shared memory?",
 "~48-228 KB per SM (configurable); a 256-thread block with a 64^3 field slab (1 MB) obviously won't fit - size tiles to the field's true reuse footprint."),
("What is a shared-memory pad (bank alignment)?",
 "Padding the stride (e.g., [N][N+1]) shifts row starts so threads' column accesses hit distinct banks - the antidote to bank conflicts."),
("What is the double-buffer pattern?",
 "While a tile processes slab k, the next slab's data streams into shared - overlapping load and compute hides the memory latency completely."),
("What is the 'atomics-in-shared' use?",
 "Accumulating per-cell emissivity counters or votes inside a block in shared (via shared atomics) avoids global atomic contention on hot cells."),
("When is shared memory NOT worth it?",
 "When threads touch disjoint far-apart regions (e.g., scattered octree leaves) - the reuse is zero and the copy cost pure overhead; let L1 cache instead."),
("How do you decide the tile size?",
 "Measure the reuse factor (field fetches per cell load): tiles amortize load cost when reuse > 2-4; size to occupancy (registers + shared per block)."),
("What is the occupancy interplay?",
 "Each block's shared allocation caps how many blocks fit per SM; a big slab that halves occupancy may lose more than it saves - test both directions."),
("What are the debugging pitfalls?",
 "Race conditions on initial shared fill (missing __syncthreads) corrupt the tile - use the patterns documented (fill-then-sync), never ad-hoc."),
("What is the shared-memory-by-default variant?",
 "Metrics: kernel's shared bytes per block; profiler's 'Shared Memory Bank Conflicts' and 'Occupancy' reports - the numbers tell the story."),
("What is the summary?",
 "Shared memory is for structured, reused neighborhood data within a block - tile the grid slab, pad for banks, double-buffer for latency - a measured tool."),
],
"08-GPU-Performance/03-Bank-Conflicts": [
("What is a bank conflict?",
 "Shared-memory banks (32 banks, 4-byte words) serve one word per cycle; if multiple threads in a warp hit the SAME bank, the access serializes - a 2x-32x penalty."),
("What causes conflicts in a raytracer?",
 "Interleaved field slabs with a stride that maps columns to repeated banks, or per-thread lookup tables indexed by the same lane-dependent arithmetic."),
("What is the classic conflict formula?",
 "Address i maps to bank (address/4) mod 32; a stride of 32 floats collides every lane -> 32-way serialization - one of the worst silent degradations."),
("How do you avoid them - padding?",
 "Add +1 (unused) column to each row: address = row*(N+1)+col maps columns to distinct banks, eliminating the conflict for row-major access."),
("How do you vectorize around conflicts?",
 "float4 loads spread across alignment; shared banks are 4-byte, so a 16-byte float4 strides collide differently - mixing access widths is a tuning lever."),
("What does the compiler do about conflicts?",
 "The compiler often handles broadcast (all lanes same bank, same address) for free; patterns it can't prove stay serialized - write conflict-free layouts."),
("How do you detect conflicts?",
 "Nsight Compute's 'Memory Workload Analysis' reports shared bank conflict reuses/stalls; a large 'Bank Conflict' count on the hot kernel is a smoking gun."),
("What is a compute-around strategy?",
 "Pre-transpose or store the field in column-major, or duplicate with offsets - restructuring data beats removing conflicts arithmetic-wise."),
("What about texture/surface conflicts?",
 "Texture cache has no bank conflicts (HW handles); this is why texture-based field sampling sidesteps shared-memory bank drama entirely."),
("What is the 64-bit twist?",
 "Double-precision shared arrays use 8-byte words; a warp reads 2 banks per value - stride must be 4-float-aligned to avoid 2-way conflicts."),
("What does an occupancy compromise look like?",
 "Padding to avoid conflicts increases shared usage slightly; a 1-2% occupancy loss is usually worth a 16x serialization removal."),
("What is the validation methodology?",
 "Toggle the padded layout A/B; measure kernel time and bank-conflict count in the roadmap - never assume the fixed layout, measure it."),
("What is the summary?",
 "Bank conflicts are shared-memory's silent tax - pad layouts, prefer texture sampling, and verify with Nsight - it is a 32x swing hiding in a stride."),
],
"08-GPU-Performance/04-Latency-Hiding": [
("What is latency hiding on a GPU?",
 "While one warp waits on memory/integer stalls, the SM runs OTHER available warps - the GPU's way of turning memory latency into throughput."),
("Why is occupancy the engine of latency hiding?",
 "More resident warps = more independent work to interleave - the standard rule: high occupancy hides long-latency global/texture accesses."),
("What is the arithmetic intensity?",
 "The ratio of compute to memory per item; low-intensity raytracer loops (few flops per fetch) are bandwidth-bound and rely on hiding, not raw flops."),
("How do you cap the raytracer's latency?",
 "Enough resident rays (high per-block-rays, high blocks-per-SM) so memory fetches of one warp overlap ALU work of others - the parallelism is the hiding."),
("What is the role of prefetching?",
 "Issue the next segment's field fetches before computing the current one (double-buffer in shared/registers) - explicit code-level overlap."),
("What does the profiler say about stalls?",
 "Nsight's 'Memory Stall' vs 'Execute Stall' distribution: if memory stalls dominate, add occupancy or prefetch; if execute, it's ALU time."),
("What is the target believe in occupancy?",
 "Get enough warps to cover the worst memory-stall duration (~600-800 cycles): compute needed resident warps = stall_cycles/issue_cycles."),
("How do adaptive ray paths hurt hiding?",
 "Diverged rays fetch scattered memory and amortize fewer warps; sorting rays into bins (by region/branch) keeps warps coherent and the hiding uniform."),
("What is the 'memory-to-compute overlap' benchmark?",
 "With a known field, a pure-fetch kernel's throughput vs a pure-compute kernel - the gap is exactly the latency you are (or are not) hiding."),
("What is the role of cache reuse in hiding?",
 "L1/L2 hits flip 'long latency' into 'short hits' - good spatial locality among warp rays shrinks the stall, not just covers it."),
("What are the long/life operations to hide?",
 "Trilinear field fetches, HIT refinement bisections, and octree node loads: batch as many independent fetches per thread as registers allow (ILP)."),
("How does instruction-level parallelism (ILP) help?",
 "Independent field samples (4-8 loads in flight per thread) hide each other's latency without needing more warps - a second lever beyond occupancy."),
("What is the validation loop?",
 "Vary occupancy (block/rays per block) and measure throughput; the knee of the curve is the practical hiding point - don't chase 100% occupancy blindly."),
("What is the summary?",
 "Latency hiding turns stalled time into throughput: crank occupancy, batch independent loads (ILP), prefetch, and verify that stalls are predominantly hidden in Nsight."),
],
"08-GPU-Performance/05-Occupancy-Tuning": [
("What is occupancy?",
 "The ratio of active warps to the SM's maximum possible warps; high occupancy maximizes the chance the SM has work while any warp stalls."),
("What limits occupancy in the raytracer?",
 "Registers per thread (large phase-space state), shared-memory per block (field slabs), and the block/grid limits - measure which constrains first."),
("What is the 50% vs 100% myth?",
 "Full occupancy isn't always best: a kernel needing few warps to hide its short latency loses performance to cache thrash at 100% - find YOUR sweet spot."),
("What is the field-cache vs occupancy tradeoff?",
 "Big shared tiles raise occupancy pressure but cut memory traffic; a 70%-occupancy high-reuse config can beat 100%-occupancy sparse-cache configs."),
("How do you measure achieved occupancy?",
 "Nsight Compute's 'Achieved Occupancy' (actual average) vs 'Theoretical' - divergence and tail effects drag achieved below theoretical; fix those."),
("What is the register-pressure lever?",
 "Add __launch_bounds__(threads, blocks_per_sm) hint: it limits the compiler's register budget per thread, freeing blocks/SM at the cost of spills - test it."),
("What is the tail effect?",
 "The last partial wave of rays runs with a fraction of the occupancy - balance blocks to fill warps or adaptive grids to near-full tails."),
("How do you size the ray batch per launch?",
 "Choose rays_per_block so allocated registers+shared allow e.g. 4-8 blocks/SM; grid = ceil(pixels / block_rays) keeps every SM busy."),
("What is occupancy's role in the RTE loop?",
 "The transfer sampling touches many fields; without resident warps, each field fetch becomes a full stall serialization - occupancy is the transfer's shield."),
("What is the multi-kernel story?",
 "Geodesic-step and accumulation kernels each have different register/shared needs; tune occupancy PER KERNEL, not per program - the profiler per-kernel view."),
("How does dynamic parallelism interact?",
 "Child kernels from a parent (e.g., octree refinement) inherit the parent's occupancy budget - keep grid sizing explicit, avoid surprise nesting."),
("What is the determinism effect?",
 "Block-grid scheduling order can vary with occupancy; pin the launch config and the reduction order to keep frame-to-frame reproducibility."),
("What is the validation loop for occupancy?",
 "Sweep rays/block 32..1024 and measure rays/s; plot the knee ('range of optimal') and choose the robust plateau, not the single best sample."),
("What is the summary?",
 "Occupancy tuning is the balancing of warps-resident vs per-thread resource use - measured per kernel, plateau-picked, and never assumed at 100%."),
],
"08-GPU-Performance/06-Tiling": [
("What is tiling in the renderer?",
 "Partitioning the image (or ray batch) into small tiles each handled by one thread block - the standard structure that makes coalescing, shared reuse, and occupancy coherent."),
("How big should a tile be?",
 "Common choices 8x8/16x16 pixels/block: enough for reuse and a full warp structure, small enough to keep blocks balanced and tails narrow."),
("What does tiling do for field locality?",
 "A tile's rays probe a compact area of the <real> scene (same geodesic neighborhood), so shared/tile caches hold the relevant field slab - reuse without waste."),
("What is the 'ray tile' vs 'screen tile'?",
 "Screen tile: pixels in a block (natural for output); ray tile: a batch of coherent rays (needed with supersampling/importance) - map pixels to rays once."),
("How does tiling interact with adaptive steps?",
 "A tile's rays realize similar integration difficulty; warp-uniform stepping stays coherent within the tile, minimizing divergence."),
("What is the tile-order for the write-out?",
 "Process tiles in a scanline that keeps the image write coalesced; a tiled frame is written tile-by-tile (each block its own region) - trivial with SoA."),
("What does tiling do to L2?",
 "Neighboring tiles' field fetches overlap L2 residually; an L2-friendly tile order amortizes the most-refetched ring slab across consecutive blocks."),
("What is the halo/ghost requirement?",
 "Interpolation needs neighbor cells beyond the tile's core volume; padded shared tiles carry a 1-cell halo so samples never touch global."),
("What is the balance lever (tile granularity)?",
 "Too-large tiles lose tail balance and halo efficiency; too-small tiles lose reuse and launch overhead - sweep and pick the plateau (e.g., 16x16)."),
("How do you handle the variable ray count per pixel?",
 "Each tile carries its own supersample count (static per frame); accumulation per tile is shared-local then global - no atomics on the image plane."),
("What is the validation for tiling?",
 "The tile decomposition must produce bit-identical frames (deterministic reduction); A/B tile sizes must agree on the image to machine level."),
("How does tiling serve the multi-pixel hybrid?",
 "For pixels mixing capture/miss, the tile's write-out branches; branchless indices (mask vs pointer) keep the block's store pattern uniform."),
("What is the summary?",
 "Tiling is the structural backbone: fixed-size pixel tiles make coalescing, shared reuse, halo interpolation, quiet reduction, and balanced occupancy all fall out."),
],
"08-GPU-Performance/07-Streams-and-Async": [
("What are CUDA streams?",
 "Ordered sequences of kernel launches that can OVERLAP - multiple streams execute concurrently on the same GPU when resources allow (e.g., different kernels, copies)."),
("What is the async copy path?",
 "cudaMemcpyAsync row-compressed data into pinned/special buffers overlaps the transfer with compute - the classic 'compute on frame k, transfer k+1'."),
("How do streams help a multi-frame renderer?",
 "Frame pipeline: stream A traces frame k while stream B post-processes k-1 and transfers the result k-2 - the GPU never idles on I/O."),
("What is the dependency problem?",
 "Rays of frame k+1 are independent of frame k's output - ideal stream parallelism; only the accumulation of one frame is sequential internally."),
("What is the event mechanism?",
 "cudaEventRecord/StreamWaitEvent orders cross-stream dependencies (e.g., 'wait until geometry buffer ready') without busy-waiting."),
("How does overlap interact with tiling?",
 "Independent tiles of the SAME frame run well on one stream; overlapping DIFFERENT frames on multiple streams adds concurrency beyond occupancy - a second knob."),
("What is the pinned-memory requirement?",
 "Async copies to host require page-locked (pinned) buffers - without cudaHostAlloc the 'async' copy silently serializes."),
("What does Nsight Systems show?",
 "The timeline exposes idle gaps: if the GPU is <70% busy with streams+occupancy at max, the data flow is the bottleneck - fix with more/finer streams."),
("What is the correctness hazard?",
 "Streams race unless ordered by events; image accumulation must happen before downstream reads - any 'async' optimization is validated by determinism tests."),
("When does multipl-stream hurt?",
 "Too many streams with heavy resource contention thrash and serialize again; 2-4 streams with a clear per-frame role beats 16 ad-hoc ones."),
("What is the copy-engine behavior?",
 "DMA (copy engines) run independent of SMs; overlap H2D/D2H with compute requires separate streams + events - the standard 3-stage pipeline."),
("What is the summary?",
 "Streams and async copy pipeline independent frames and I/O - the last big lever beyond occupancy for keeping a big renderer's GPU always busy."),
],
"08-GPU-Performance/08-Pinned-Memory": [
("What is pinned (page-locked) memory?",
 "Host memory allocated with cudaHostAlloc so its pages never swap - the requirement for true async (overlapping) transfers with the GPU."),
("Why can't regular host memory overlap?",
 "The copy engine needs stable physical pages; unpinned memory forces staged copies through a temporary pinned staging buffer, killing overlap."),
("What is the read-back pattern for frames?",
 "The render's image floats are written into a pinned buffer and streamed to host while the next frame renders - the overlap thread of the movie pipeline."),
("What is the pinned usage in the raytracer?",
 "Grid field upload (GRMHD data) and per-frame state are the big pinned transfers; the image result streams back pinned."),
("What is the caution (memory pressure)?",
 "Pinned memory is a scarce OS resource; over-pinning starves the system for other apps - pin only the orchestrated hot buffers."),
("What is host-side staging vs device-to-device?",
 "If data stays on device across frames (reuse), D2D copies are far cheaper than host round-trips - pin only what truly crosses the PCIe bus."),
("What are the IPC/peer features?",
 "cudaMemcpyPeer/cudaMallocManaged replace pinned for multi-GPU in the 09 module; pinned remains the async-overlap staple on one GPU."),
("What is zero-copy?",
 "Reading pinned (mapped) memory directly from kernels without explicit copies - wins for small, read-once fields; loses for repeated reads (PCIe latency)."),
("What is the ordering caution?",
 "Async writes must be ordered with events so the host-side consumer doesn't read a half-transferred frame - a classic bug when adding overlap."),
("What is the Nsight Systems signature?",
 "The transfer channels (H2D/D2H) busy while SM kernels idle (or vice versa) - the fix is pinning + streams + balance."),
("What is the size-sweet-point?",
 "Pin once, reuse many frames; amortized pinning cost across the render loop - a 100 MB GRMHD field pinned once is nothing over 1000 frames."),
("What is the summary?",
 "Pinned memory is the transport layer of async overlap - pin the hot buffers, stream via events, and keep the PCIe bus busy while SMs render."),
],
"08-GPU-Performance/09-Multi-GPU": [
("What is the multi-GPU architecture for rendering?",
 "Parallelism across GPUs: divide the image into contiguous slabs (image-parallel) or the field into spatial chunks (data-parallel) - the classic two models."),
("What is image-parallel multi-GPU?",
 "Each GPU traces its own horizontal strip of pixels with the SAME scene copy - trivial (no communication during the ray loop), perfect for tiles."),
("What is data-parallel multi-GPU?",
 "Split the GRMHD field across GPUs; rays migrate/requests cross PCIe/NVLink - harder (needed only when one GPU's memory can't hold the field)."),
("What is the P2P (peer-to-peer) path?",
 "cudaMemcpyPeer across GPU memory directly (NVLink/PCIe P2P) instead of host staging - the fast lane for border exchange in data-parallel mode."),
("What is the frame-buffer reduction issue?",
 "Each GPU's strip pixels accumulate independently; the final image is a simple concatenation/shift (image-parallel) - no cross-GPU reduction at all."),
("What is the load-balance concern?",
 "The ring sits at the image center: a center-strip GPU gets harder rays (more steps) - assign strips with estimated workload weights, not equal sizes."),
("What is the 'ray steal / dynamic tile' strategy?",
 "Dispatch tiles to GPUs as they finish (work-queue) - the simplest robust load balancer; the counter-queue is a single atomic in pinned memory."),
("How do you communicate the output?",
 "Each GPU writes its strip to its own pinned buffer; the host (or a final gather kernel) concatenates - bit-deterministic if each strip is self-contained."),
("What is NVSwitch/NVLink scaling reality?",
 "NVLink gives ~600 GB/s between GPUs: data-parallel becomes viable; PCIe 16x (~30 GB/s) is fine for image-parallel only."),
("What is the determinism contract?",
 "Strip partitioning must not change pixel values (each pixel's rays don't cross strips) - frame reproducibility holds trivially in image-parallel."),
("What does Nsight Systems show in multi-GPU?",
 "Per-GPU timelines overlap fully when balanced; a straggler (idle GPU) shows as the timeline gap — the load-balancer's scoreboard."),
("What is the scaling test?",
 "N GPUs -> wall time ~ 1/N (image-parallel) up to the strip tail; verify via a strong-scaling sweep and report speedup vs 1 GPU honestly."),
("What is the summary?",
 "Multi-GPU = image-parallel strips with a work-queue for balance, P2P only when pushing the field around, and deterministic concatenation at the end."),
],
"08-GPU-Performance/10-CUDA-Graphs": [
("What are CUDA Graphs?",
 "A complete launch DAG (kernels + copies + events) captured once and replayed with minimal CPU overhead - replacing the per-frame launch-call storm."),
("How does a raytracer become a graph?",
 "Frame pipeline: upload-state (if any), geodesic kernel, transfer/accumulate kernel, gather/boost kernel, image write - captured as a reusable graph."),
("Why do CUDA Graphs matter here?",
 "A 2k image with tile kernels launches ~10^4-10^5 calls per frame; graph replay cuts launch latency from ~5us/call to a single ~1us replay - multi-ms/frame saved."),
("What is capture semantics?",
 "cudaStreamBeginCapture, run the kernels normally, EndCapture -> graph; CPU-side gaps between launches collapse into one submitted plot."),
("What is the mutable-node benefit?",
 "Variable buffers (next frame's state) bind at launch; graph nodes refer to memory pools - update via the graph's resource handles, not re-capture."),
("What is the interplay with streams?",
 "A graph CAN embed stream semantics (dependent regions) for multi-frame overlap within one submission - stream capture + graph replay compose."),
("What does the graph do to determinism?",
 "Fixed DAG order = fixed execution order = reproducible results; one more reason graphs and fprintf-debuging work well together."),
("What is the overhead of graph capture?",
 "Capture costs ~ms (kernel launches are recorded); amortize: capture once per configuration, replay thousands of frames."),
("What is the update-safe pattern for parameters?",
 "The graph refers to device memory; parameters that change (camera, time) live in memory the graph's kernels already read - NO kernel-arg churn."),
("How does the graph speed the movie path?",
 "A 9000-frame movie with a captured frame-graph reduces the CPU-side launch overhead to nothing - purely a submission-efficiency win."),
("What is the validation for graphs?",
 "Replaying the graph must match the sequential-launch path bit-for-bit; enable a build flag to bypass graphs for debugging when it doesn't."),
("What is the summary?",
 "CUDA Graphs collapse per-frame launch chaos into one replayable DAG - the standard device-side executor of a production multi-frame pipeline."),
],
"08-GPU-Performance/11-Nsight-Compute": [
("What is Nsight Compute?",
 "NVIDIA's per-kernel profiler giving register-level metrics (occupancy, memory throughput, stalls) for each kernel launch - the micro-analyzer of GPU code."),
("How do you use it on a raytracer?",
 "Profile one representative kernel (geodesic stepping) with a small but valid launch: read its occupancy, memory, and stall sections to guide tuning."),
("What does 'Achieved Occupancy' mean here?",
 "The actual average warps active across the kernel's execution vs the theoretical cap - divergence/tail effects drop it; it's the health metric of hiding."),
("What are the memory sections?",
 "Global/Local/Shared throughput percentages, latency tables, and cache-hit stats - tells you exactly which memory path your kernel leans on."),
("What are the stall reasons?",
 "'Stall Barrier', 'Stall Long Scoreboard', 'Stall Wait' report what warps wait on - memory (scoreboard) vs sync vs dependencies - each suggests a fix."),
("What is the single-kernel flow?",
 "Profile -> identify top stall -> make one change (e.g., layout/occupancy) -> re-profile -> accept or revert - the honest, slow, reliable loop."),
("What is 'IPC' (instructions per cycle)?",
 "SM GPU throughput indicator; >3-4 is healthy for compute-heavy, raytracer loops more like 1.5-3 with memory latency - relative change, not absolute."),
("What are the metric groups to save?",
 "Save a named metric-group config (occupancy:registers, memory:workload) as a project file - every engineer reprofiles the same columns."),
("How does Nsight Compute help with determinism?",
 "It attributes per-kernel reads: the same kernel in different runs must report nearly identical metrics - a cheap determinism cross-check."),
("What is the difference from Nsight Systems?",
 "Systems = system-wide timeline (gaps, overlap); Compute = per-kernel internals (why a kernel is slow) - use Systems to spot, Compute to dig."),
("How do you avoid profiling overhead?",
 "Profile a reduced render (small resolution, few frames), never the full movie; write results to CSV for post-hoc comparisons."),
("What is the summary?",
 "Nsight Compute answers 'why is this kernel slow' at the register level - an analytical, measurement-driven companion to the design patterns."),
],
"08-GPU-Performance/12-Nsight-Systems": [
("What is Nsight Systems?",
 "NVIDIA's system-wide timeline profiler: shows kernels, copies, CPU calls, and GPU idle gaps - the 'where is time going' macro-lens of the renderer."),
("How does it help a raytracer?",
 "A multi-frame render of the whole pipeline rapidly reveals: GPU idle between frames, serialized copies, CPU launch stalls, or insufficient occupancy overlap."),
("What is the 'OS kernel launch' tracing?",
 "Nsight captures the per-launch timeline: you see straight-line gaps between kernels (CPU-bound) vs green blocks without gaps (GPU-bound)."),
("What is the classic finding here?",
 "A movie path with no CUDA Graphs shows a long tail of ~5us launch serialization per kernel = ms of CPU-latency per frame - visible proof of the graph win."),
("How do you read the copy channels?",
 "H2D/D2H rows show when transfers run; idle copy engines next to busy SMs = missed async overlap - the pinned/streams diagnosis."),
("What is the CPU-side (API) view?",
 "Per-thread CPU call stacks alongside GPU rows: a slow cudaMemcpy command or an accidental per-frame cudaMalloc shows up as a CPU stall."),
("How does it guide stream design?",
 "If the timeline shows one GPU row with recurring gaps, split frames into 2-3 overlapped streams; Nsight validates the overlap visually."),
("What is the trace scope sizing?",
 "Trace a short window (e.g., 20 frames) at the render's real settings - enough timeline to see the loop, not so long the trace takes forever."),
("What is the correlation with Compute?",
 "Systems finds the macro gap; Compute explains the kernel micro-cost - the complementary pair is the complete performance toolkit."),
("What is the determinism view?",
 "The same pipeline across runs should show near-identical timeline block lengths (within jitter); wild variance flags load-imbalance or resource contention."),
("What is the multi-GPU timeline?",
 "Per-device rows show stragglers immediately - the work-queue load balancer's effect is directly visible as balanced, overlapping rows."),
("What is the summary?",
 "Nsight Systems is the macro performance map - timeline the pipeline, spot idle/overlap gaps, and direct the micro-tuning that Nsight Compute then quantifies."),
],
"08-GPU-Performance/13-Cache-Control": [
("What does cache control mean on a GPU?",
 "Guiding L1/L2/texture behavior per access - which data stays cached, which streams - via const restrict, __ldg, inline PTX, or grid-control hints."),
("What is the read-only cache (__ldg)?",
 "Kernels read immutable field data through the read-only data cache: __ldg(&field[i]) bypasses the writable path - better hit rate for grid/texture-like arrays."),
("What is 'const __restrict__'?",
 "Marking pointer parameters const __restrict__ lets the compiler issue read-only loads and wide vector accesses - free wins on hot kernels."),
("What is the texture-path for fields?",
 "Global arrays bound as textures get dedicated caches + hardware filtering; trilinear sampling becomes fire-and-forget — the field natural home."),
("What does 'cudaFuncSetAttribute' allow?",
 "The preferred cache config (L1 vs shared split, or 'L1-only') tunes the silicon's on-chip budget to the kernel's fetches - e.g., more L1 for field reads."),
("What is the L2 policy effort?",
 "cudaStreamSetAttribute/property-based 'persisting' hints keep the hottest field slab (ring) resident in L2 across many tiles."),
("What is the directive vs reality caveat?",
 "Cache POLICIES are hints; the real eviction is hardware-driven - the only truth is measured hit rates (Compute's 'L1 Hit Rate')."),
("What is the 'hot slab' reuse pattern?",
 "The ring's field slice is touched by many tiles; keep it cached (L2-persist) while streaming the outer-disk slabs - a classic two-region memory diet."),
("What is the translation of a CPU habit (preach locality)?",
 "The GPU analog: warp-coherent accesses (same neighborhood) maximize a single cached line serving many lanes - same principle, translated."),
("What are eviction-friendly patterns?",
 "Huge, read-once arrays (e.g., per-frame emission cache) should stream and NOT pollute: load via __ldg with cache() spills or reuse small rings instead."),
("What is the deterministic hazard?",
 "Cache hints can change float ordering slightly (FMA/load scheduling) - if frames must be bit-reproducible, pin the hint set consistently."),
("What is the summary?",
 "Cache control steers the on-chip memory diet - const-restrict/read-only loads for fields, texture paths for filtering, and L2-persist hints for the hot ring slab."),
],
"08-GPU-Performance/14-Reductions": [
("What is a GPU reduction?",
 "Combining many values into one (sum, min, max of per-pixel intensities across tiles) - the classic parallel pattern a renderer uses to total a frame's flux."),
("What is the tree reduction?",
 "The standard: each thread reduces its chunk, shared-memory tree sums within a block (pairwise, synchronized), then atomics/tree across blocks - O(log n)."),
("Why are naive reductions slow?",
 "The naive 'one thread sums all, shared serial loop' is O(n) serial — trees exploit all employees in parallel, crucial for per-frame flux totals."),
("How does warp-shuffle reduce?",
 "Threads exchange values directly via __shfl_down_sync in-register (no shared) - a full warp reduction in 5 shuffle steps, the modern fastest base."),
("Where are reductions in the raytracer?",
 "Total flux per band, image moments (center, rms), per-tile statistics, and the polarization averages - any scalar summary of the frame."),
("What is the associative-precision trap?",
 "Tree/reorder changes the summation order -> results differ between runs; a SPECIFIED tree order (or per-run float prec) pins the frame's reproducibility."),
("What is the atomic slowdown hazard?",
 "A global-add per thread serializes millions of atomics; reduce within the tile's shared memory first, then one atomic per block - the standard fix."),
("What are the torn-write hazards?",
 "Simultaneous per-pixel-accumulated writes to the image buffer from multiple tiles must be exact-add atomics or tile-dedicated regions - never racy reads."),
("What does the profiler say?",
 "Nsight's 'Atomics' throughput and memory reduce coverage shows whether the reduction path is starved; a saturated atomic path is the fix signal."),
("What is hierarchical reduction for movies?",
 "Reduce per frame, accumulate per movie; the two-level aggregation keeps singles-frame totals and a running total without re-reading history."),
("What is the stochastic rejection benefit?",
 "Reductions over supersampled rays (average, variance) yield the S/N statistics — a single reduction pass provides both value and error bars."),
("What is the validation?",
 "A known brute-force sum on an analytic field must agree with the tree reduction to rounding tolerance; enforce at the test-suite level."),
("What is the summary?",
 "Reductions are the frame's scalar-stats backbone: warp-shuffles + shared trees + one atomic/block, order-pinned for reproducibility — never naive serial."),
]}