"""Curated Q&A for 09-Production leaves."""
PROD = {
"09-Production/01-CMake-Build": [
("What is the CMake build structure for the project?",
 "A modern CMake project: SBMA root, target(s) for the CUDA raytracer library and CLI, plus optional bindings and tests - with CUDA/NVIDIA flags isolated in one settings file."),
("How do you configure CUDA support in CMake?",
 "enable_language(CUDA), find_package(CUDAToolkit), set CMAKE_CUDA_STANDARD=17, and per-target CUDA_ARCHITECTURES - the proper way to target GPUs without hard-coded -arch."),
("What is the release build layout?",
 "Single CMake (not recursed) with subdirectories: src/ (raytracer lib), tools/ (cli), utils/ (converters), tests/, plus examples/ - each a small add_library target."),
("What are the compiler flags for the kernels?",
 "CMAKE_CUDA_FLAGS_RELEASE with -O3 and -use_fast_math for the render paths, but a fat default flag set that stays deterministic (no aggressive FP contraction surprises)."),
("How do you enforce a consistent FP contract?",
 "Pass -ffp-contract=off (or override with explicit fma) so floating point is bit-exact across runs and compilers - the reproducibility contract at compile time."),
("What is a 'relocatable device code' need?",
 "Unless you use separately-compiled device kernels, keep them in the same translation unit (relocatable device code off); for multi-object device linkage set CUDA_SEPARABLE_COMPILATION as needed to keep the binary coherent."),
("How do you keep GPU architectures portable?",
 "CMAKE_CUDA_ARCHITECTURES lists e.g, 86;89;90;: set via a cache variable and only compile-for-the-host's GPU in local dev ('native')."),
("What does find_package(CUDAToolkit) enable?",
 "Detection of the toolkit's nvcc/ptxas versions and headers/libraries - a single canonical place for the CUDA dependency, including the host-side libs."),
("What are the ctest hooks?",
 "add_test() over the golden tests (analytic validation, convergence, determinism) wired to ctest - `ctest` becomes the project's entrance test command."),
("How do you version and package?",
 "project(VERSION) + CPack or a simple install(TARGETS) rule; the version string flows into the CLI --version and into every log/render's metadata."),
("What is the developer loop?",
 "cmake --build build -j --target ray-cli && ctest --test-dir build -R validation - the two-command loop that keeps engineering productive."),
("What are the pitfalls of stale binary caches?",
 "GC cache and CUDA_ARCHITECTURES changes need a fresh configure; document 'delete build when changing arch' in the README."),
("What is the summary?",
 "A modern CMake build = CUDA-as-first-class language, arch-cached targets, deterministic FP flags, ctest golden suite, and a two-command dev loop."),
],
"09-Production/02-Project-Layout": [
("What is the recommended source layout?",
 "src/ (core lib: metric, geodesic, transfer, kernels), include/ (public headers), tools/ (cli: render, movie, validate), utils/ (grmhd converters), tests/ - a library-first structure."),
("Why a library + CLI split?",
 "The raytracer as a library lets tests, benchmarking, and alternate frontends link the same core; the CLI is a thin argument-parsing shell over it."),
("Where do the CUDA kernels live?",
 "src/gpu/*.cu for the device code and src/gpu/*.cuh headers; host wrappers in src/cpu/ - kernels compiled independently, host calls via a clean API."),
("What is the role of the kernel CMake target?",
 "Each .cu gets its own library target for correct arch flags; a single 'ray' top-level target aggregates - incremental compiles stay correct and fast."),
("How do you separate data formats?",
 "utils/ owns the GRMHD (HDF5/FITS) readers and the interpolated-field serialization - the core never depends on a simulation format directly."),
("Where do tests live in relation to golden data?",
 "tests/ holds the analytic golden files (shadow radius, deflection, doppler) PLUS a build-time downloader for the real GRMHD snapshot - both wired to ctest."),
("What is the include-heirarchy discipline?",
 "Internal-only headers under src/**/impl, public API headers in include/raytracer - prevents accidental cross-thread include tangles."),
("How does the CLI stay consistent?",
 "Options struct (clipp/argparse) in tools/cli parsed into a config struct consumed by the API - the CLI is data, the library is the logic."),
("Where do configs/results go?",
 "config/ holds the YAML/JSON run templates; out/ stores per-run frames + metadata - a fixed, documented out/ layout the pipeline scripts depend on."),
("What is the 'scenes' directory?",
 "data/scenes: the processed field volumes and their metadata (YAML/JSON), split by simulation and snapshot - the raytracer's consumable dataset home."),
("How do you organize ongoing experiments?",
 "A reproducible run directory per parameter set: out/<run-id>/ with the config, log, and outputs - every artifact traceable to one command."),
("What is the summary?",
 "A library-first layout: core kernels + host API as the engine, thin CLI, converters out of the core, and a fixed out/run-id hierarchy - maintenance is the product."),
],
"09-Production/03-Host-Device-Data-Flow": [
("What data flows host->device?",
 "The field volume (rho, B, Te arrays), the metric/geometry config, and per-frame camera/emission tables - uploaded once or per frame as needed."),
("How is the field uploaded efficiently?",
 "One DeviceBlob per array in SoA layout (r_gbs contiguous), uploaded via cudaMemcpyAsync on a pinned buffer during a warmup - single large transfer, not per-cell."),
("What is the device-side layout?",
 "The field as 3D arrays (log-r, theta, phi dimension) ready for texture binding, each in its own cudaArray - the trilinear sampler's natural home."),
("What crosses device->host per frame?",
 "The 2D intensity/Stokes/count buffers - small next to the field - copied out at the frame boundary for post-processing and movie encoding."),
("What is the staging (pinned) requirement?",
 "Async transfers need cudaHostAlloc (pinned) staging; the field and image buffers live in pinned/special memory dedicated to the orchestrator."),
("How is the geodesic state handled?",
 "Ray-state slabs (soA doubles) are device-side WORK, never serialized to host except for debugging one ray - keep the hot loop host-free."),
("What is the 'one upload, many frames' reuse?",
 "The geometry/field is static across a movie; upload once at startup, per-frame only the camera/quasar state tops up - the memory-flow budget."),
("How do streams orchestrate the flow?",
 "A dedicated ingestion stream overlaps H2D of frame k's small updates with the render kernels of frame k-1 - the classic three-stage pipeline."),
("What about the interpolation caches?",
 "Pre-computed interpolation weights (cell indices, fractions) for reused grid regions can be device-resident or recomputed per ray - cache only the reused parts."),
("What is the reader's memory mirror?",
 "Host keeps one copy of the field for the converter/tests; device owns its GPU copy - a mental 'two copies, one source of truth (disk)'."),
("How do you debug data flow?",
 "A '--dump-state k' option writes ray k's device state to host (debug channel) without breaking the hot loop - the flow's observability valve."),
("What is the summary?",
 "Host-device flow = one bulk field upload, streaming small per-frame updates, device-resident ray state, and pinned staging with a clean three-stage overlap."),
],
"09-Production/04-CLI-Configuration": [
("What does the CLI configure?",
 "Scene (field path or analytic), camera (position, inclination, field-of-view), sampling (res, supersample, tolerance), and rendering (bands, post) - one command per run."),
("What is the standard argument set?",
 "--scene FILE, --camera 'xi,yi,z,fov', --resolution WxH, --samples N, --tolerance 1e-9, --bands 230GHz..., --output DIR - a compact, scriptable surface."),
("Why a config file plus CLI?",
 "CLI flags for quick interactivity, a YAML config for full runs - the CLI OVERRIDES the file, preserving both brevity and reproducibility."),
("How do you guarantee validation of args?",
 "Parse into typed config structs with range-checking (resolution, tolerance bounds, camera positions) BEFORE any GPU allocation - fail fast."),
("What is a run-id convention?",
 "Every render gets an auto id (tag-counter or git-hash+seq) forming its output dirname - the master key that ties config+log+outputs together."),
("How do you expose the geometry parameters?",
 "--spin a, --mass-units M, --distance, --observer at infinity - independently tunable so the analytic validation and real-image fits share one code path."),
("How is the command surface tested?",
 "The CLI's '--help' and error paths are unit-tested (exit codes, messages) independent of rendering - a stable CLI prevents downstream breakage."),
("What are the verbosity knobs?",
 "--log-level info/debug/trace namespaces + progress bars throttled by TTY detection - never spam the stdout protocol that scripts parse."),
("What is the deterministic-trigger?",
 "--seed (for jitter of supersampling) stored in metadata: same seed+config = same frame - the CLI is the reproducibility contract's entry point."),
("How do you support batch runs?",
 "A --job JSON/YAML accepting multiple configurations in one invocation, plus stdout JSON summaries - the CI/production batch surface."),
("What is the summary?",
 "The CLI is the typed, validated front door - flags-over-file, run-ids, --seed, and machine-readable output; reproducibility starts at the prompt."),
],
"09-Production/05-Logging-and-Progress": [
("What does the logger capture?",
 "Configuration hash, per-kernel timings, integration stats (steps, rejections), warnings (tolerance reached, floors active), and the final image's checksum."),
("Why structured logging?",
 "Machine-parseable key=value/JSON lines let dashboards and the batch system summarize runs; humans skim, scripts inspect."),
("What levels exist and when?",
 "info (start/finish, params), debug (per-kernel), trace (per-ray) - the trace level is gated behind a build flag to protect the hot loop."),
("How does progress reporting work?",
 "A percent + rays/s + ETA printed to a TTY, throttled to ~1 Hz; the SAME data goes to a machine channel (JSON) for batch dashboards."),
("What is the 'checkpoint' logging?",
 "Every N frames, a short summary line including the accumulated mean/std of intensity - progress-haves in a restartable movie loop."),
("How do you correlate log with outputs?",
 "Each render's log begins with the run-id and ends with the artifact checksums - the audit trail from command line to image."),
("What are WARNING semantics?",
 "Not fatal: 'step budget hit for x% of rays', 'floor applied in region', 'ring tolerance degraded' - warnings pin candidate artifacts early."),
("What is the source-location discipline?",
 "Log a module tag (field: metric.cu:123) so a flood maps to code; the logger auto-tags unless suppressed - debugging via grep by module."),
("How do you avoid log overhead?",
 "Message formatting only happens when the level is enabled (lazy lambdas / if-gated) - the hot loop's instrumentation cost stays ~0."),
("What is the summary?",
 "Logging/progress = structured, level-gated, machine-parseable, run-id-bound - the observability duct keeping production renders debuggable."),
],
"09-Production/06-Testing": [
("What is the test pyramid for this project?",
 "Unit (metric algebra, sampler, integration order) at the base, integration (geodesic+transfer on analytic scenes) mid, golden-image/end-to-end at the top."),
("What are the analytic-unit tests?",
 "Minkowski straight lines, Schwarzschild deflection 4M/b, shadow boundary at 3sqrt(3)M, doppler factors, zero-field samplers - each a closed-form assertion."),
("What is the ensemble/golden test?",
 "A fixed analytic scene rendered at small res: compare against a checked-in golden image hash - catching refactor regressions without slow re-renders."),
("Why test determinism?",
 "The same config+seed must give bit-identical frames; a determinism test runs the same command twice and diffs the bytes - the reproducibility gate."),
("What is a convergence test?",
 "Run resolution 2x and 4x: key observables (shadow radius, total flux) must converge at expected order; the sanity that the discretization is honest."),
("How is the GRMHD suite handled?",
 "Download a small public snapshot once, defer the heavy suite behind a RUN_MOVIE_ONLY flag - CI stays fast while physics coverage stays deep."),
("What are the error-path tests?",
 "Bad filenames, out-of-range spin, missing field arrays, over-small resolution: assert clean exit codes/messages - robustness under misuse."),
("How does the sampler get tested?",
 "Linear 2D/3D field reproduction (exact), linear-RTE column, and the pole/edge policies - the three axes of the sampler contract."),
("What is the mutation-test mindset?",
 "After every refactor, the analytic suite must fail loudly if a constant slips - the tests are the code metric's guardrails."),
("How is it wired to CI?",
 "ctest runs the fast suite on every PR; the golden+GRMHD suite in the nightly; coverage reports keep untested branches visible."),
("What is the summary?",
 "Testing = layered analytic-assured coverage from metric units to golden images, with determinism + convergence + error-path gates - the physics' safety net."),
],
"09-Production/07-Analytic-Validation": [
("What is analytic validation?",
 "Comparing the renderer's output against closed-form results for simple spacetimes/materials - the scientific correctness gate, independent of any simulation."),
("What is the M=0 (Minkowski) test?",
 "With the hole turned off, every ray is a straight line: a test pattern source must render without distortion - the zero-bug-free baseline."),
("What is the Schwarzschild shadow test?",
 "A distant observer's shadow must be EXACTLY a circle of radius b=3sqrt(3)M; overlay the analytic silhouette on the render - any deviation is a bug."),
("What is the deflection test?",
 "Weak-field rays must match delta=4M/b to leading order; strong-field rays obey the exact elliptic-integral deflection - scan b and compare."),
("What is the photon-ring test?",
 "Circular null orbit at r=3M (a=0) must loop forever: a ray seeded there spins on true-radius@1e-9 - validating both metric and integrator."),
("What is the Doppler analytical test?",
 "A rigidly-rotating thin ring's intensity asymmetry vs azimuth must equal the delta^(powers) formula; flip a and the crescent flips - geometry in the pixels."),
("What is the gravitational redshift test?",
 "A static emitter's rays land at the analytic z = sqrt(1-2M/r)-ish factor at each pixel - the redshift channel validated numerically."),
("What is the RTE analytic test?",
 "Constant j/alpha columns reproduce exp(-tau) attenuation exactly; the thin-limit reduces to integral j ds - the transfer's closed forms."),
("What is the frame/beaming consistency?",
 "A static, axially-symmetric cold source emits isotropically: the render must show azimuth-INDEPENDENT brightness - Doppler bugs would break the symmetry."),
("What is the polarization analytic test?",
 "Uniform B field: the EVPA pattern and fraction match the textbook formula (fraction, angle vs k-vector) - the Stokes math's exact check."),
("What is the convergence-to-analytic criterion?",
 "As resolution/supersample grows, the render's observables approach the analytic value monotonically - the honest 'converged' claim."),
("What is the summary?",
 "Analytic validation pins every numeric layer with closed-form anchors - Minkowski, shadow, deflection, ring, doppler, RTE, polarization - the science license."),
],
"09-Production/08-CI-and-Automation": [
("What does CI run on a PR?",
 "The fast suite: build (arch-linted), unit+determinism+golden-image tests, CLI smoke tests, and a lint/sanitizer pass - under ~10 minutes."),
("What is the nightly suite?",
 "The GRMHD snapshot tests, convergence runs, and a multi-GPU scaling check - the slower physics+perf suite on a schedule, not every commit."),
("What are the GitHub Actions jobs?",
 "ci (build+test on a runner with CUDA), golden (pgm-diff of golden images), sanitizer (ASAN/UBSAN on CPU path), and docker-build (container reproducibility)."),
("How is coverage measured?",
 "gcovr/llvm-cov on the host code + a report threshold - CI fails a PR that drops untested-core below the bar without a review override."),
("What is the artifact policy?",
 "Each CI build uploads the CLI binary + test logs; releases tag a build whose tests all passed with the git hash - production deploys that exact binary."),
("What is the flakiness discipline?",
 "GPU/CPU timing tests assert RANGES not exact times; flaky tests are quarantined immediately and fixed, never re-run-and-wish."),
("How do varying GPUs stay deterministic?",
 "The determinism test runs on the CI's fixed GPU model; multi-arch runs assert the SAME tolerance but not identical pixels across GPUs."),
("What does a merge gate look like?",
 "Build+test+lint+determinism all green, plus the reviewer checkbox that the PR touches only intended layers - the contract of 'main is releasable'."),
("How are releases automated?",
 "Semver tagging triggers: build both arch sets, run the full suite, publish artifacts + a changelog entry - one tag, one reproducible release."),
("What is the summary?",
 "CI/automation = fast PR gates, nightly depth, deterministic/fixed-GPU reproducibility, artifact-pinned releases - engineering discipline as infrastructure."),
],
"09-Production/09-Multi-Frame-Rendering": [
("What is multi-frame rendering?",
 "Rendering a sequence of frames (a movie) from evolving simulation snapshots - the time dimension of the raytracer beyond a single still."),
("How are movie inputs organized?",
 "A list of snapshots (times) + per-frame camera either fixed or evolving; the renderer loops frames reusing geometry and field uploads."),
("What is frame-to-frame reuse?",
 "Static parts (metric, chart, capture table) upload ONCE; the per-frame kernel only needs the new emission state - the biggest movie-mode speedup."),
("How do you handle interpolated field evolution?",
 "Read snapshots at fixed cadence; interpolate (linear in time within a grid of snapshots or nearest-frame) to the frame's t - the time-sampler contract."),
("What is a camera path?",
 "Available as key-frames (position/orientation) interpolated per frame (spline) - orbiting/inspecting shots; the path is parameter data, not code."),
("What is the consistency-of-cadence issue?",
 "Orbital disk timescales ~ M; if frames are sampled faster than the snapshot cadence, temporal aliasing blurs - set frame dt < source dt/2 conservatively."),
("How does frame accumulation (blur) work?",
 "A 'long exposure' frame integrates several instantaneous renders (motion blur) - an explicit flag; adds realism at Nx cost, only when asked."),
("What is the per-frame state management?",
 "The render loop keeps host state (current camera/time/seed) and hands a per-frame config to the GPU kernels - no GPU re-init between frames."),
("How is a movie started/stopped?",
 "Frame indices bounded; a checkpoint/restart records completed frames so an interrupted movie resumes - the crash-resilience feature of long encodes."),
("What is the movie metadata contract?",
 "Every frame's metadata (time, camera, config hash) recorded in a manifest JSON - the movie file's provenance and the analyzer's interface."),
("What is the summary?",
 "Multi-frame rendering = reuse-everything-per-frame, temporal sampling discipline, camera paths, and checkpoint continuity - the difference between a still renderer and a movie tool."),
],
"09-Production/10-FFmpeg-Encoding": [
("What is the ffmpeg role?",
 "Encoding the rendered frame sequence (raw formats/PPM/EXR) into a playable video (mp4/webm) - the final step of the movie pipeline."),
("What is the standard encode command?",
 "ffmpeg -framerate 24 -i out/frame_%05d.png -c:v libx264 -crf 18 -pix_fmt yuv420p movie.mp4 - a lossless-ish, widely-readable mp4."),
("Why --pix_fmt yuv420p?",
 "YUV 4:2:0 gives maximum player compatibility (browsers, editors) at the cost of chroma subsampling - the price of portability; keep the source frames separately."),
("What is a lossless archive encode?",
 "ffmpeg -i frames_png -c:v ffv1 (or -crf 0) for an archival master - the frames that go into archiving, distinct from the delivery mp4."),
("How do you encode HDR/linear EXR sequences?",
 "Optionally via -pix_fmt gbrpf32le and a tone-mapping pass; the renderer writes both display-8-bit and linear-master channels - pick per pipeline stage."),
("What is the audio/silence addition?",
 "Movies mostly need no audio; if desired, -f lavfi -i anullsrc=r=48000:cl=stereo adds silent track for editors' placeholders."),
("What is the frame-rate choice?",
 "24/30 fps standard; for analysis movies often the SIMULATION time per frame (e.g., 24Hz) matters more than wall-clock - set --framerate accordingly."),
("How do you iterate quickly while editing?",
 "Encode a downscaled preview (scale=W/4) at low CRF during development, the full-quality only at the end - the dev-loop version of the pipeline."),
("What is the ffmpeg-free alternative?",
 "OpenCV/MP4Writer or a Rust/Python encoder wrapper - but ffmpeg's filters (crop, tint, overlay) make it the standard glue; keep it as a thin wrapper."),
("What is the reproducibility of encodes?",
 "ffmpeg with the same command+frames is deterministic (encoder_seed 0, static) - store the encode command line in the movie metadata."),
("What is the summary?",
 "FFmpeg is the delivery layer — lossy-yuv for play, lossless-master for archive, deterministic commands recorded — thin, pinned, and scripted."),
],
"09-Production/11-Reproducibility": [
("What does reproducibility mean for a renderer?",
 "The same version, input snapshot, config, and seed produce bit-identical frames on the same hardware - the scientist's trust contract."),
("What is the nondeterminism budget?",
 "Thread order (reductions, atomics), FP associative reordering, and driver/library version drift - each must be explicitly controlled or documented."),
("How do you control thread-order variance?",
 "Pin the reduction tree order (a defined index order), launch grids deterministically, and avoid order-dependent atomics in accumulation."),
("How do you pin floating-point?",
 "Fixed --ffp-contract / explicit-fma policy, no fast-math on the reproducible path, and a determinism test per build."),
("What is the version-hash metadata?",
 "Every output records git-hash, binary EXIF-ish stamp, CUDA runtime, driver, and the config hash - an audit trail without a special file manifest."),
("What is the input pinning?",
 "Store the snapshot's checksum + the converter version in the scene record - the 'what exact data' part of reproducibility."),
("Why separate GPU determinism from CPU-determinism?",
 "Different GPUs have different transcendental accuracy; the guarantee is per-GPU-bit-exact + cross-GPU-agrees-to-tolerance - state it explicitly."),
("What is a golden regression?",
 "Version-coded expected hashes for the analytic scenes - if a legitimate physics change bumps them, the golden file is reviewed and re-pinned."),
("How do you reproduce a third-party run?",
 "Ship the exact command from the run-id's record: bin same hash, config same, seed same - a colleague re-runs and diff-bits match."),
("What is the summary?",
 "Reproducibility = pinned seed/order/FP/version/input, captured in metadata, enforced by a determinism gate — the difference between imagery and evidence."),
],
"09-Production/12-Documentation": [
("What documentation does a scientific raytracer need?",
 "README (what/why/quickstart), a physics/derivations chapter, a build/dev guide, an API reference, and an observables/metrics glossary - a pyramid, not a monograph."),
("What is the minimal README?",
 "One page: what it renders, install/build 2 commands, run 1 command, and 2 grounding images (Schwarzschild, Kerr) - enough to orient in a glance."),
("How deep does the physics chapter go?",
 "Metric definitions, geodesic/Hamiltonian derivation, the transfer equation and synchrotron formulas - with derivations, sources, and the code's parameter names."),
("What is a beginner's run-through?",
 "A 'first movie' tutorial: install, download a public snapshot, render one frame, then a 10-line movie — the onboarding path that makes the tool usable."),
("How is the API documented?",
 "Doxygen (or docstring) on the public header API: function contract, units, thread-safety, and the error contract - the maintenance wall of the core."),
("What is the parameter glossary?",
 "Every CLI/config key: meaning, units, default, valid range - the reference index that keeps a growing option surface coherent."),
("What are the run-recipe docs?",
 "Curated examples (Schwarzschild still, Kerr movie, M87-like fit) with the exact config files - 'do this to get this' saved as reproduction recipes."),
("How do docs stay current?",
 "A CI doc-check (links, examples runnable, option names matched) plus the rule that changing a CLI key without updating the glossary is a bug."),
("What is the contributor guide?",
 "Reading order, code layout map, test running, and the golden-number philosophy - the documentation that makes growth possible."),
("What is the summary?",
 "Documentation is the interface of a tool meant to be studied, extended, and trusted - a pyramid of README, physics, API, glossary, recipes, kept alive by CI."),
],
"09-Production/13-Profiling-in-Production": [
("What is production profiling?",
 "Systematic, automated performance measurement of real render jobs - not one-off microbench, but a routine that catches perf regressions before release."),
("What metrics matter?",
 "Rays/sec, frames/hour, GPU utilization %, step-accept rate, memory throughput, and wall-time per scene - the renderer's vital signs."),
("How do you profile without disturbing the job?",
 "Nsight Systems/Compute in trace mode around a canonical small-medium scene; a 'PROFILE_MODE=1' flag that runs a shortened-but-representative render."),
("What is a regression threshold?",
 "Rays/sec must not drop >10% from a pinned baseline without review - automated CI perf job publishes a trend chart; drops abort the merge."),
("What is the 'hot loop' burn-down?",
 "If profiling shows >30% of time NOT in your kernels (copies, launch latency, CPU gaps), the pipeline structure, not the math, needs attention."),
("What is the step-cost attribution?",
 "Per-kernel timing with NVTX ranges: integrates the metric/geodesic vs transfer vs reduction - knowing WHERE the wall went."),
("What is the config-drift effect?",
 "Different tolerances/resolutions change the profile drastically; zero-length profiling is pinned to a 'reference config' and reported as such."),
("How is profiling automated in CI?",
 "A nightly job runs the reference config under Nsight, uploads the CSV summary, and alerts on outliers - production perf as a living metric."),
("What is the correlation with reproducibility?",
 "The profiled reference config is the SAME command that must pass the determinism test - profiling never touches the output's honesty contract."),
("What is the summary?",
 "Production profiling = automated, metric-pinned, regression-alerting performance — measuring the renderer's health continuously, not once."),
],
"09-Production/14-Containerization": [
("Why containerize the renderer?",
 "On-demand GPUs (cloud, research clusters) want a hermetic, reproducible environment: CUDA version, drivers, libs, and the binary all pinned together."),
("What is the base image choice?",
 "nvidia/cuda:12.x-devel-ubuntu22.04 as the builder + a slim runtime image (cuda:12.x-runtime-ubuntu22.04) for execution - build and serve artifacts separately."),
("What is the multi-stage Dockerfile pattern?",
 "Stage 1 (devel) compiles with the full toolchain; stage 2 (runtime) copies the binary + the minimal CUDA runtime libs; the image ships only execution."),
("How do you give a container GPU access?",
 "docker run --gpus all or k8s resource limits 'nvidia.com/gpu'; plus the NVIDIA Container Toolkit ('nvidia-container-runtime') - host driver meets container runtime."),
("What is the pin-versions rule?",
 "The CUDA toolkit version (e.g., 12.4), the OS, and the archive of local build deps are all pinned in the image tag - 'no floating tags in production'."),
("What about the scientific reproducibility caveat?",
 "The driver may differ from the build's toolkit minor - containerizes the runtime but not the SM/architecture; state the required arch in the image metadata."),
("How do you mount inputs/outputs?",
 "The snapshot and out/ are volumes: -v /data/scenes:/work/scenes -v /out:/work/out - the container is a compute unit, data lives on the host."),
("What is the HPC (Singularity) analog?",
 "Singularity/Apptainer runs uncompressed or the same image on clusters - the --nv flag gives GPU; a near drop-in to the Docker pattern."),
("What is the pytest/CI tie-in?",
 "The CI builds the container and runs the smoke test inside it - the exact production container is what CI tests, killing the 'works on my machine' gap."),
("What is the summary?",
 "Containerization = hermetic GPU builds, slim runtimes, pinned CUDA/OS versions, and host-volume I/O — the deployment standard for scientific rendering."),
]}