"""Curated Q&A for 02-Ray-Tracing leaves."""
RAY = {
"02-Ray-Tracing/01-Ray-Generation": [
("What is ray generation?",
 "It converts each image pixel plus the camera pose into a 3D ray (origin + direction) that the integrator follows; the mapping from pixel coordinates to direction is the camera model."),
("What does the classic pinhole ray look like?",
 "origin = camera position; direction = normalize(center + filmU*u + filmV*v - origin), where (u,v) are normalized pixel coordinates and center/filmU/filmV build the image plane."),
("How do you compute the pixel coordinates (u,v)?",
 "u = (2*(x+0.5)/W - 1) * aspect * tan(fov/2) and v = (1 - 2*(y+0.5)/H) * tan(fov/2), with the +0.5 sample at the pixel center (or jittered for AA)."),
("What is the field-of-view (fov) model?",
 "fov is the vertical angle; the vertical half-extent is tan(fov/2), horizontal = vertical * aspect; focal length in a real camera maps to fov = 2*atan(h/2f)."),
("How do you transform from camera space to world space?",
 "Build the camera basis (right, up, forward) and apply direction = forward + u*right + v*up, then normalize; moving the camera rotates/shifts that basis."),
("What is the relation between pixel sample jitter and AA?",
 "Adding a random offset to the pixel coordinate within [0,1) per sample spreads rays across the pixel area - the basis of stochastic antialiasing."),
("How do you handle the image border correctly?",
 "Clamp or remap the pixel index so the last row/column maps to the correct film extent; off-by-half-pixel errors shift the whole frame half a pixel."),
("What degenerate cases break ray generation?",
 "A zero-length direction (degenerate FOV), cameras inside the horizon, or NaN in the basis from an identity-up vector - guard the camera basis explicitly."),
("What does the camera generate for the black-hole visualizer?",
 "Rays from the camera position aimed at sky directions; rays that pass near the black hole get bent into the disk or horizon instead of the sky."),
("How is a direction stored efficiently?",
 "As float4 (dx,dy,dz, and a junk channel for the dot 'w') or a float3 struct; alignment to 16 bytes keeps RK4 steps vectorized."),
("What is the relationship between ray generation and integration?",
 "Generation creates the initial condition (x0, direction); integration evolves it; the two must agree on units (they share the geometric convention for the metric)."),
("How do you generate rays in an opaque or safe order?",
 "Row-major scan: thread index maps to pixel (y*W+x), the ray then evaluated with pure functions - order matters only for determinism, not correctness."),
("What is the role of a 'jitter-free' reference mode?",
 "Providing a deterministic square-sampled mode lets you A/B against analytic renders and debug the generator apart from the sampler."),
("How do you expose ray generation parameters?",
 "Through a Camera struct (pos, basis, fov, film size) so tests inject pose and fov numerically and compare generated directions against closed-form values."),
],
"02-Ray-Tracing/02-Camera-Models": [
("What are the camera models used in raytracing?",
 "Pinhole (infinitely sharp), thin-lens (aperture + focal plane for depth of field), orthographic, and fisheye/panoramic (equirectangular) - choose per scene intent."),
("What is the pinhole camera model?",
 "All rays pass through a single point (the pinhole) and hit the film plane; no depth of field, no distortion - the default for correctness-focused renders."),
("What is the thin-lens model?",
 "Rays originate from a lens of radius 'aperture' and are refracted to hit the focal plane at the pixel's point; defocus blur grows with aperture and distance offset."),
("What is the orthographic camera?",
 "Rays are parallel (direction fixed, origin spread over the plane) - used for technical/embedded views; it has no natural FOV."),
("What is the equirectangular (panorama) camera?",
 "Maps direction to (lon,lat) over a 2:1 image; ideal for environment backgrounds and for capturing the full lensing sky dome around the black hole."),
("How do you implement DOF on top of pinhole?",
 "Pick a random point on the lens disk, compute the focal point (where the pinhole ray hits the focal plane), and aim the new ray at it - the classic aperture jitter."),
("What are the parameters of a DOF shot?",
 "Aperture radius, focal distance, and FOV; the bokeh shape follows the aperture geometry (circular, or blades for polygons)."),
("Which camera is best for comparing to EHT images?",
 "A pinhole or mild thin-lens at effectively infinite distance - the EHT approximates a very distant observer, so the shadow geometry is the dominant effect."),
("How do you convert between camera spaces?",
 "World-to-camera via the basis matrix, then camera-to-ray via the projection; keep the two steps as separate functions so either can be unit-tested."),
("What is the 'glare cam' concept for beauty shots?",
 "Putting the camera close and tilted so the disk's bright inner edge fills the frame - a render-art choice, applied by moving basis vectors not models."),
("Why store the camera as a struct and pass by value?",
 "Each thread needs the same camera; passing by value into __constant__ or registers keeps the basis in registers rather than pulling from global each step."),
("How does the camera interact with the photon-ring scale?",
 "The ring subtends ~(10/3) GM over distance; a FOV ~ tens of arcseconds around the shadow resolves the ring - camera FOV must be chosen to frame it."),
("How do you validate a camera?",
 "Render a grid of known directions and assert the pixel angles match analytic (u,v)->direction formulas; pose gates, then every projection is exact."),
("What is the animation camera?",
 "A timed path (Catmull-Rom or keyframe interpolation) producing a moving basis; each frame re-computes generation with different pose - pure data flow."),
],
"02-Ray-Tracing/03-Intersection-Math": [
("What is ray-object intersection?",
 "Finding where a ray (o + td, t>0) meets a surface; the 't' at the hit, the normal, and (for shading) whether the hit is front/back are computed."),
("How do you solve ray-sphere intersection?",
 "Intersect |o+td - c|^2 = R^2: a quadratic in t; discriminant < 0 -> miss, else t = (-b - sqrt(disc))/(2a) and the hit normal = (hit - c)/R."),
("What is the reference-plane intersection used in disk renders?",
 "For a flat disk, intersect the ray with the equatorial plane z=0: t = -oz/dz (if dz != 0) | r(radius from the hole) decides inside/outside of the flow."),
("What is an ellipse/ellipsoid intersection?",
 "Substitute the ray into ((x-cx)/a)^2+...=1 to get a quadratic in t with the same discriminant logic - used for tilted or warped emitter surfaces."),
("What is the significance of 't>0'?",
 "t must be positive (in front); a negative t is 'behind' the origin - or for a secondary scatter, past the previous event - so every hit test clamps t to the forward domain."),
("What is the epsilon-trick in intersection?",
 "Offsetting the origin or comparing t to a small epsilon avoids self-intersection and acne at grazing contacts - where rays start exactly on a surface."),
("How do you compute simple normals for shading?",
 "Sphere: normalize(hit - center); plane: its constant normal; triangle: normalized cross product of edges - tempered by interpolation for smooth meshes."),
("What is the difference between geometric and shading intersection?",
 "Geometric answers (where? which side? which t?) vs the shading's use of that answer (position, normal, material); keep them separate functions."),
("Why is a disk emitter often approximated analytically?",
 "The accretion flow is really volumetric, but a collapsed planar + radial emissivity only reaches closed-form integration that is a perfect validation target."),
("What numerical care does intersection need in double?",
 "Quadratics with large coefficients (radius vs distance scales) lose accuracy; dividing by R^2 and solving in double prevents false misses at distant disks."),
("How do you test intersections?",
 "Fire grids of rays at known shapes (sphere radius R at origin) and assert t equals the closed form within tolerance and misses at |b|>R."),
("What are the degenerate cases for plane intersection?",
 "dz == 0 (parallel ray) - return no hit; rays from the plane (t=0) - require t>eps to avoid self-intersection feedback."),
("How does intersection feed the anisotropic disk?",
 "Hit points give radius r, azimuth phi, and orbital motion where the boosted emissivity is evaluated - intersection is the geometry gate for texture sampling."),
("What happens when the ray passes exactly through the hole center?",
 "It can produce t with dz=0 or a degenerate on-plane condition - handle as a 'miss disk, continue to sky/horizon' fallback actively."),
],
"02-Ray-Tracing/04-Reflection-and-Refraction": [
("What role does reflection play in a raytracer?",
 "Secondary rays reflect off surfaces to capture mirrored or glossy content; a secondary level adds the first taste of recursive tracing beyond the direct ray."),
("What is the reflection law?",
 "reflect = d - 2(d.n)n with |n| = 1; the outgoing ray shares the angle about the normal - implemented as a per-hit function."),
("What is Snell's law for refraction?",
 "n1 sin(theta1) = n2 sin(theta2); with ink ratio eta = n1/n2 and TIR when 1 - eta^2(1-cos^2) < 0; the refracted direction uses the ratio term."),
("What is total internal reflection?",
 "When eta^2(1-cos^2)>1 there is no refracted ray - only reflected; important for materials that enclose the light (lensing, fiber, accretion optics)."),
("What is the Fresnel effect?",
 "Reflection ratio depends on angle and index (Schlick approx: R = R0 + (1-R0)(1-cos)^5); at grazing angles most light reflects - a visible cue for the disk edges."),
("What is a rough/glossy reflection model?",
 "Perturbing the perfect reflection direction by a microfacet distribution (e.g., GGX) scatters secondary rays - the roughness controls the blur."),
("How do you prevent recursion explosion?",
 "Cap depth (bounce count), implement a Russian-roulette threshold, or trace with a budget - in the black-hole tracer the 'bounce' is the photon path through the disk."),
("What is the emission-bounce separation for the accretion disk?",
 "The disk emits from its hot plasma directly, and secondary scatters (thin disk TOA) - unless radiative transfer is modeled, we treat the first intersection as the visible emission."),
("What are the surface material properties in such a renderer?",
 "Albedo fractions (diffuse, specular), roughness, IOR, and emissive term - for plasma the material is 'emission only', so shading simplifies to transfer alone."),
("How does the normal perturb produce bump/terrain?",
 "The shading normal is offset by a height-field gradient to fake small surface detail without geometry - irrelevant for a smooth plasma but used for starfield/rings."),
("How does reflection appear in the falling-disk image?",
 "Photons that 'reflect' are those that scatter back through the disk's photosphere - only when scattering is in the transfer model does 'reflection' materialize."),
("What validation test exercises reflections?",
 "A sphere above a plane: the image must reproduce the classic reflection of the lower hemisphere with Fresnel falloff at grazing edges."),
("What is the interaction between reflection and the polarizer?",
 "Fresnel reflection carries polarization; Stokes tracking of reflected tones needs the full Mueller calculus rather than simple scalar intensities."),
("When does a raytracer NOT need explicit bounces?",
 "When every visible feature is primary light (emitting plasma, sky background) - the black hole and disk images are fundamentally a primary-ray problem."),
],
"02-Ray-Tracing/05-Shading-Models": [
("What is a shading model?",
 "The set of rules converting a surface hit + light into outgoing radiance (color); for emitting plasma it reduces to an emissivity function of the field state."),
("What are the classic shading models?",
 "Lambert (diffuse, color = albedo/pi * irradiance), Blinn-Phong (diffuse + specular pow), microfacet PBR (GGX + Fresnel), and emissive-only for self-luminous matter."),
("What is the diffuse/Lambert law?",
 "Reflectance = albedo * (irradiance/pi), so brightness falls with 1/pi and varies with the light's incidence - the flat look of matte surfaces."),
("What is ambient/independent shading?",
 "A constant term making unlit surfaces visible; in the black-hole scene the 'ambient' is emission itself, so no ambient hack is needed."),
("How is the accretion disk shaded?",
 "An emissive profile j(r) (often j ~ r^-2..-3) integrated along the ray's path in the fluid frame, then Doppler-beamed - no BRDF at all."),
("What is the difference between emissive and reflective shading?",
 "Emissive outputs radiance independently of incident light; reflective multiplies incident irradiance by a BRDF - the disk is emissive; any stars are reflective/emissive separately."),
("How do you rainbow-或 redshift the disk color?",
 "Tint the emitted spectrum by temperature (e.g., a G to L gradient) and then apply the redshift factor to the emitted frequency - color follows physics, not the palette."),
("What is the role of the color map in rendering?",
 "A log-amplitude mapping from integrated intensity to RGB, tuned so the faint ring is visible: physical values -> perceptual map."),
("How does the disk shading change with viewing angle?",
 "Edge-on hot rays see the innermost bright rim face-on (beamed); face-on views see the faint top - the apparent brightness depends on beaming factor and optical depth."),
("What is the simplest first shading test?",
 "A uniform bright sphere against a flat large disc: render a radial intensity profile and match ring/disk contrast to the known analytic emission law."),
("What is the emission + atmosphere plate model?",
 "For a thin geometrically-thin disk, emission occurs at a photospheric surface integrated once; for a thick flow, volume emission is integrated over every path segment the ray spends in the flow."),
("How do you combine disk and background shading?",
 "The ray integrates emissions along the path; when it escapes to the sky it adds the background starfield at its end - a simple 2-term composite."),
("What is tone mapping's role after shading?",
 "Shading produces unbounded radiance; tone mapping compresses the dynamic range to displayable SDR (below) - they are separate stages that must not be fused."),
("How do you validate shading numerically?",
 "Compare the integrated intensity along one known ray through a uniform slab against the analytic emissivity*pathlength result."),
("What does a good shading debug view show?",
 "Emissivity map, optical depth, beaming factor, and final intensity as four separate images - making it obvious which stage caused an artifact."),
],
"02-Ray-Tracing/06-Acceleration-Structures": [
("What is an acceleration structure?",
 "A spatial index (grid, BVH, octree) that prunes empty regions so ray-primitive tests skip space the ray never crosses - the difference between interactive and nightly renders."),
("Why does the black-hole visualizer use them?",
 "For the background starfield and disk primitives: without pruning, every ray tests every star; with a structure, rays only test tokens in crossed cells."),
("What are the two families?",
 "Grid-based (uniform/spatial hash, octree, AMR) and object-based (BVH, R-tree); grids excel at uniform scenes, BVH at varying densities."),
("How do you classify a structure by ray-time efficiency?",
 "Average intersections per ray: grid ~ build cells such that primitives per cell ~1; BVH ~ log(N) with good splitting; the metric is (traversal cost + test cost)/ray."),
("What is the build-vs-trace trade-off?",
 "Structures take build time amortized over many rays; a static sky builds once and pays off instantly, while a per-frame changing field can dominate rent."),
("When is brute force acceptable?",
 "Below ~20 primitives, direct testing wins because structure traversal (branching, memory hops) costs more than it saves."),
("What does the 'N/population' rule for grids say?",
 "Pick cell size so primitives/cell is ~1-3; too fine (many empty cells) wastes traversal, too coarse (many primitives) wastes tests."),
("What is the traversal of a grid?",
 "The 3D-DDA marches the ray cell by cell, testing primitives in each; the horizontal + vertical exit code from Amanatides & Woo handles accuracy."),
("What is a BVH node?",
 "An axis-aligned bounding box with either a primitive or two children; traversal descends both boxes the ray hits - the standard acceleration for triangle scenes."),
("What is a surface-area heuristic (SAH)?",
 "Chooses split planes minimizing estimated cost c = C(primitives) based on surface areas of child boxes - the near-optimal split for BVHs."),
("What is the pyramid/octree variant?",
 "An octree subdivides cubes adaptively into 8 children - best for adaptive plasma grids where cell density varies as it does near the horizon."),
("What is the memory cost of structures?",
 "Grids index cells (offset arrays); BVH nodes ~24-32B each; octrees bloom memory if unpruned - budget structures against the texture arrays they speed up."),
("How do structures interact with cache?",
 "Traversal chases pointers (BVH) or strides (grid); packing nodes in memory-contiguous arrays (SOA) and using 64-bit indices keeps cache lines hot."),
("What is the standard way to move structures to device?",
 "Build on host, then upload node/primitive arrays to constant/global memory; device builds are possible but host-build-then-copy is the simplest correct path."),
("How do you verify a structure?",
 "Render the same scene with and without the structure and assert pixel-identical output - accelerations must never change results, only speed."),
],
"02-Ray-Tracing/07-Spatial-Hash-Grid": [
("What is a spatial hash grid?",
 "A uniform grid whose cells are hashed into a compact array, trading a few hash collisions for memory - the building block of GPU-friendly spatial acceleration."),
("How does the grid index a ray?",
 "Compute the cell of the origin, then the 3D-DDA increments cells along the dominant axis; each visited cell maps to a bucket of primitives."),
("What are the standard grid sizes?",
 "Fixed resolution per axis or a function of scene extent; for a disk+sky, ~64^2 or 128^3 balanced by expected primitives per cell."),
("How do you lay out the bucket arrays?",
 "Two arrays: cellStart[cellCount+1] (prefix-sum offsets) and primitiveList[nPrim]; the cell's primitives are list[cellStart[c] .. cellStart[c+1])."),
("What is the build cost?",
 "O(N) hashing and a counting sort into buckets - trivial for thousands of primitives, memory-efficient because only occupied cells allocate."),
("How does the hash resolve collisions?",
 "Multiple geometric cells share a bucket; the traversal checks the actual cell coordinates before trusting the bucket, so collisions cost a test but never correctness."),
("Why is a grid better than brute force for the sky starfield?",
 "A ray traverses ~O(sqrt(depth)) cells instead of testing O(N) stars; for 10^4 stars grid traversal drops tests per ray by orders of magnitude."),
("What is the 3D-DDA (voxel traversal)?",
 "Amanatides & Woo: maintain tMax per axis (distance to next plane) and advance the smallest; visit each crossed cell exactly once in float-safe arithmetic."),
("How do you handle empty/full cells?",
 "Empty cells contribute no primitives so traversal just moves on; full cells (disk interior) push many primitives - the tracer samples the field from the grid, not primitives."),
("How does the grid serve field sampling?",
 "The same cell index maps to per-cell field data (density, temperature) used for emission - one array serves both intersection pruning and interpolation."),
("What is the trade-off of grid resolution?",
 "Too fine: traversal overhead and sparse occupancy; too coarse: many primitives per cell; tune resolution to expected ray density per cell ~1."),
("How do you handle primitives straddling cells?",
 "Insert each primitive into every cell its AABB overlaps; acceptable duplication (N*overlap), trimmed by the cell-coordinate checks during traversal."),
("How do you build grids in parallel?",
 "A counting-sort pattern: histogram primitives per cell, prefix-sum the offsets, then scatter primitives into buckets — all parallelizable with atomics or two-pass."),
("What test verifies the grid?",
 "Shoot the analytic sphere ray set, ensure every hit matches the no-grid result exactly (determinism) and that the total intersection count shrinks."),
("When would you abandon grids for another structure?",
 "When primitives are grossly heterogeneous (tiny stars + huge disk) a BVH or octree adapts better than a fixed-resolution grid."),
],
"02-Ray-Tracing/08-Bounding-Volume-Hierarchy": [
("What is a BVH?",
 "A binary tree of axis-aligned bounding boxes (AABBs) enclosing primitives; traversal descends only subtrees whose box the ray intersects, giving ~log(N) work."),
("What is the node layout for a traversal-efficient BVH?",
 "A contiguous array of 24/32-byte nodes, each storing childAABB, transformed bounds, and offset/count for leaf primitives; index 0 == root via traversal conventions."),
("How do you build a BVH top-down?",
 "Partition primitives along the largest AABB axis at the best split (SAH or median), recurse into children, emit nodes - O(N log N) typical, O(N^2) naive worst."),
("What does SAH cost estimate?",
 "c = C_traverse + (areaL/total)*cL*(countL) + (areaR/total)*cR*(countR); pick the split minimizing cost across candidate planes (binning to O(N log N))."),
("What is a primitive-partition vs spatial-midpoint split?",
 "Primitive partition: split by centroid order (balanced); midpoint: split by box mid (may imbalance). SAH bins the arbitrary of primitives best in practice."),
("How does the greedy BVH traverse?",
 "A stack: push children of a hit box; pop the nearest (distance) and test its primitives - recursion converted to an explicit stack for GPU/SIMT friendliness."),
("What is the ray-box test?",
 "slab: for each axis tmin = (min - o)/d, tmax = (max - o)/d, intersect ranges; ray hits the box iff max(tmin)>min(tmax) and within (0, tRayCap)."),
("How do you parallelize the build?",
 "Morton-code ordering (sort by 3D bit interleave of centroid) lets you build a radix-tree BVH in O(N log N) fully parallel - the GPU community standard."),
("What is the SAH cost of a static sky BVH?",
 "Built once, ~hundreds of microseconds for 10^4 stars, amortized over millions of rays - effectively free while cutting per-ray intersection tests."),
("How does the BVH fit the disk?",
 "The disk can be represented as a BVH over emissive surface patches (or a single AABB over a grid) so rays cull most cells before deep sampling."),
("What are the numerical traps in BVH traversal?",
 "NaNs when a subdivided tiny direction divides by zero; clamp d==0 to +inf or split into per-axis degree; keep t values monotonic."),
("What memory access pattern does traversal need?",
 "Depth-first node visits are local but pointer jumps; using SIMD-4 nodes (BVH4) amortizes memory latency and enables branch-minimized stackless traversal."),
("How do you test a BVH?",
 "Same golden-image rule: enabling/disabling the BVH must not change a single pixel; plus count-assurance: average touched nodes << N."),
("When is a BVH overkill for the black-hole scene?",
 "For a pure sky + disk where a grid already reaches <5 tests/ray; reconsider when you add thousands of emissive particles and star primitives."),
("What is the recommended production choice?",
 "Start grid (simplest to implement both ways), keep the interface abstraction, and swap to BVH under the same traversal contract when scenes grow."),
],
"02-Ray-Tracing/09-Antialiasing-and-Sampling": [
("What is aliasing in raytracing?",
 "Undersampling of high-frequency features (thin rings, sharp edges) produces jaggies, moire, and shimmering; antialiasing averages many samples per pixel."),
("What is supersampling (MSAA style)?",
 "Jittering the pixel center within the pixel each sample and averaging - the statistical basis of Monte Carlo AA for ray tracers."),
("How many samples does the ring need?",
 "The photon ring is a thin bright contour: ~4x4 to 8x8 samples per pixel adequately resolve it; barely-sampled rings flicker between frames."),
("What is the difference between regular and jittered sampling?",
 "Regular grid sampling aliases (repeating patterns); jittered stratified (one random sample per subcell) kills the coherent pattern cheaply - 'stratified' is the sweet spot."),
("What is stratified/`Latin hypercube` sampling?",
 "Dividing the pixel into a grid and taking one jittered sample per cell; each cell contributes and no two samples overlap - low discrepancy per sample count."),
("What is the principle of importance sampling the ring?",
 "Warping sample positions toward the bright ring (the impact-parameter range where caustics concentrate) reduces variance dramatically - a real raytracer trick."),
("What is the Monte Carlo estimate?",
 "The integral is approximated by averaging samples: I ~= (1/N) sum f(xi)/p(xi); AA is exactly MC in the pixel domain."),
("What is the variance-noise relationship?",
 "Noise ~ 1/sqrt(N); doubling samples halves noise but also halves the frame rate - the key trade-off in any sampler."),
("What is a blue-noise pattern and why use it?",
 "A sample set whose Fourier spectrum suppresses low frequencies; blue-noise jitter yields perceptually smoother images at the same N (R2/blue-noise sequences)."),
("How do you randomize the per-pixel seed deterministically?",
 "hash(pixelX, pixelY, frameIndex) as the RNG seed; same frame -> identical random draws, so re-renders are reproducible."),
("What is the interaction of AA with tone mapping?",
 "Average in linear light BEFORE tone mapping, never after - averaging nonlinear values darkens edges and shifts the ring brightness."),
("How does AA interact with temporal coherence in movies?",
 "Re-seeding RNG per frame introduces temporal noise; fixed jitter lattice (static) avoids flicker while temporal interleaving keeps it filmic - choose per look."),
("What validation proves AA works?",
 "Render the disk edge at 1, 4, 16, 64 rays/pixel; the edge RMS vs reference should fall ~1/sqrt(N) - the signature of a working integrator+sampler."),
("What is the cheapest AA improvement?",
 "Two jittered primary rays per pixel (2x2 supersample) often eliminates visible aliasing on the ring for a modest 2x cost - try that before RIP up the sampler."),
],
"02-Ray-Tracing/10-Depth-of-Field": [
("What is depth of field (DOF)?",
 "Defocus where parts of the image outside a focal plane blur - produced by sampling rays from an aperture disk instead of a single point."),
("How is thin-lens DOF implemented?",
 "For each sample: pick lens point l = randInDisk(aperture); compute focal = origin + f*dirPin; new ray: origin=l, dir=normalize(focal-l)."),
("What controls the blur amount?",
 "Aperture radius (blur scale) and focal distance (plane of sharp focus); larger aperture or farther from focus blur more - the same physics as a camera."),
("What is the bokeh shape?",
 "Disk-shaped aperture -> circular bokeh; polygonal blades (hexagons) produce matching polygon bokeh; the sample distribution inside the disk sets it."),
("Why is DOF rarely used in black-hole images?",
 "Real telescopes at Earth observe effectively at infinity with huge focal lengths, so the image is sharp - DOF is a stylistic tool, not a physical requirement."),
("How does DOF affect the photon ring?",
 "Blur spreads the ring across pixels (losing its thin signature) - it reduces the information content, a reason science renders disable it."),
("How do you sample a disk for DOF?",
 "polar: r = sqrt(rand)*R, phi = 2*pi*rand (uniform area) or polygon-index for multi-blade conform evenly; store as offset vector."),
("What is the relation between DOF and the film plane?",
 "The film plane stores the 'perfectly focused' positions; DOF perturbs origins toward those focal points - focus distance must be computed once per ray."),
("What are the focal-plane artifacts to avoid?",
 "Bad focal distance makes a black 'hole' in focus or double images; validate with a scene containing a markscaffold at known depths."),
("How is DOF combined with jitter?",
 "Each sample gets both pixel jitter (AA) and lens jitter (DOF) - independent random draws from two samplers on the same seed."),
("Do you need DOF for the disk analytic render?",
 "No - analytic thin disks render sharp; DOF belongs to cinematic sequences only, behind a camera-model switch."),
("How do you benchmark DOF cost?",
 "Each sample generates a different origin (no shared cache of rays), so DOF roughly multiplies the trace cost by samples - profile before filming."),
("What is the simplest correct DOF test?",
 "Two spheres at different depths: one in focus, one blurred; assert the focused one is unblurred and blurred one smooth vs analytic size."),
("When is DOF a visual liability?",
 "In comparison images or papers where the physical ring must not be blurred - disable it via the camera model to keep science renders honest."),
],
"02-Ray-Tracing/11-HDR-Rendering": [
("What is HDR rendering?",
 "Computing and storing radiance as real, unbounded values (typically FP32 linear) rather than 8-bit integers, so dynamic range survives to tone mapping and fusion."),
("Why must the raytracer internally use HDR?",
 "The disk's inner face is orders of magnitude brighter than faint ring; 8-bit clips both - intermediate buffers must be float throughout the pipeline."),
("What is the dynamic range of a black-hole render?",
 "Brightness ratios exceed 10^6 between the photon-ring hotspot and faint outer disk/escape flows, far beyond a displayable 8-bit range."),
("What format should internal buffers be?",
 "FP32 linear RGB (or XYZ radiometric) per pixel; 16-bit half can suffice but quantization speckles the faint ring - prefer float for validation first."),
("Why is gamma/encoding applied only at the very end?",
 "Encoding (gamma, sRGB) compresses values for display; applying it mid-pipeline destroys the energy relationships that shading and transfer rely on."),
("What is the exposure chain?",
 "auto-exposure from brightness histogram -> multiply by 2^EV -> tone map -> encode sRGB -> store 8-bit; HDR is the linear prefix of that chain."),
("How do you render a starfield in HDR?",
 "Each star is a tiny bright spot (its physical radiance); the average sky stays near-zero - the HDR pipeline keeps both within a working float range."),
("What is the log-domain trick for intensity?",
 "Integrating log(I) and exponentiating avoids underflow of tiny emission values that a linear accumulator would flush to zero - specifically useful for faint disk wings."),
("How does HDR support 4:4:4 vs raw output?",
 "HDR EXR preserves exact values for later grading; sRGB compresses for web; both are written from the same linear float buffer."),
("What is the accumulator precision requirement?",
 "FP32 summarize of up to 10^4 samples with tiny and huge contributions needs prostatic ordering; sort or Kahan-sum if drift shows."),
("How do you convert a physical intensity to an image?",
 "intensity (erg/s/cm^2/Hz) -> exposure -> map through the display lambda; keep the physics unit conversion in one place so colors are reproducible."),
("What does 'linear light averaging' mean for AA?",
 "Averaging happens over radiance values, not gamma-encoded values, so the average matches physical flux - the reason samples must be summed before tone mapping."),
("What debugging view proves HDR is working?",
 "A single map of the raw linear buffer (log-scaled) shows both the ring hotspot and faint wings on one scale - the HDR proof-of-life render."),
("How does HDR interact with the movie encoder?",
 "Frames stored as linear EXR then encoded sRGB at the end in one ffmpeg pass preserves quality; intermediate PNG (8-bit) clips HDR."),
("What is the HDR pipeline's single most common mistake?",
 "Tone mapping or gamma in the tracing kernel - keeping tone mapping OFF until after all samples are accumulated is the rule that protects HDR."),
],
"02-Ray-Tracing/12-Tone-Mapping": [
("What is tone mapping?",
 "Mapping unbounded linear radiance to a displayable [0,1] range while preserving perceptual contrast and highlights - the final stage before 8-bit encoding."),
("What is the simplest (Reinhard) operator?",
 "c_out = c/(1+c) preserving ratios (values <1 darken, >1 saturate toward 1); parameterizable by exposure and 'white point' version safe for cheap shots."),
("What is the filmic/ACES tone mapping?",
 "A response curve copied from film (ACES fit) that rolls off highlights gracefully - the standard look for cinematic renders."),
("Why apply the exposure BEFORE tone mapping?",
 "Exposure (a multiplicative gain) changes what the curve shows; the pipeline computes exposure from the histogram, multiplies, then curve-transforms."),
("What is auto-exposure?",
 "A percentile of the brightness histogram (e.g., p95) sets gain so the frame's key brightness lands mid-range; -consistency across frames needs the percentile from a tracked metric."),
("What is the brightness histogram for?",
 "auto-exposure: build log-intensity histogram, pick the high-percentile, set gain = target/percentile - robust across dynamic frames."),
("What are the standard display gamma values?",
 "sRGB EOTF (~2.2 curve, ~1/2.4 power), Rec.709 (same OETF), and D65 white point; encode to the target color space at the last step."),
("How do you preserve highlights vs clipping?",
 "A roll-off operator (film) compresses extremes without a hard clip; hard clipping at 1 loses detail in the ring's brightest fibers - visually annoying."),
("What is color grading in tone mapping?",
 "Perceptual LUTs (look, shadow/midtone/highlight) applied after the base curve - where 'style' lives, separate from the physics pipeline."),
("How does tone mapping affect the photon ring visibility?",
 "The faint outer wings gain contrast from a filmic roll-off while the bright inner ring holds - a well-identical curve changes which detail reads as 'ring'."),
("What is the dark-surround (local) tone mapping?",
 "Operators that adapt locally per-region (e.g., local Reinhard) - more contrast but halos at edges; avoid for science stills, keep for style."),
("What is the correct sequence in the pipeline?",
 "linear accumulate -> exposure -> (perceptual LUT) -> tone curve -> encode sRGB -> save PNG; never reverse the order of value transform."),
("How do you verify tone mapping is neutral?",
 "Render a mid-gray (0.18) scene: after exposure+curve it must map to ~0.18 in sRGB; a fixed gray patch test pins the operator's parameters."),
("How do you keep tone mapping parameters reproducible?",
 "Record exposure + curve name + LUT in the frame's metadata; a movie that varies exposure per frame needs the tracked percentile stored too."),
],
"02-Ray-Tracing/13-Writing-Image-Files": [
("What is the file format selection for HDR frames?",
 "OpenEXR (float, exact dynamic range) for master frames; PNG (8-bit sRGB) for previews; PPM for debug. The pipeline writes both into the same buffers."),
("Why NOT use a lossy format (JPEG) for the master?",
 "JPEG's DCT artifacts damage the exact physics pixels and re-encoding compounds - the master must stay lossless (EXR/PNG) and JPEG only at the final funnel."),
("How is the image stored in memory?",
 "A float4 buffer W*H (RGB + optional alpha), row-major, row-aligned to 16-byte; the trace kernel writes it directly, the writer flattens to the format."),
("What are the image dimensions and stride?",
 "W and H independent of alignment for output; the buffer stride = W*4 floats; PNG writer converts to 8-bit per channel with the sRGB encoding applied first."),
("How do you write EXR from CUDA?",
 "Copy the float buffer to host, then feed tinyexr or OpenEXR's API a header + pixel-array - one library call per file after the kernel completes."),
("What is the standard PNG encode path?",
 "host buffer -> stb_write_png (zlib) or libpng; both accept 32-bit RGBA and 8-bit after conversion; mind thread-safe library choice."),
("How is a movie built from frames?",
 "The renderer writes N sequential EXR/PNG frames (named frame_%05d.png) and ffmpeg x264 promises the encode - no render-time video codecs needed."),
("What is the color conversion to sRGB?",
 "Apply the linear->sRGB curve (c <= 0.0031308 ? c*12.92 : 1.055*c^(1/2.4) - 0.055) per channel, then [0-255]. Where the tone mapper already includes it, skip."),
("What alpha does the raytracer write?",
 "Blend alpha = opacity of the composite (sky + disk); for a fully opaque frame alpha=1 everywhere; keep format flexible (PNG supports alpha)."),
("How do you embed metadata?",
 "EXR/PNG chunk data (timestamp, camera config, integrator, random seeds, data hash) - enables exact reproducibility of every master frame."),
("What is the debug PPM format?",
 "P6: 'P6\\nW H\\n255\\n' + raw bytes; trivially written for tests and diffable by readers - the toilet test format."),
("How do you verify a written file?",
 "Re-read it, compare pixels to the source buffer, and assert the loop and format round-trip - catches byte-order and width/height bugs immediately."),
("What are the thread-safety concerns of writing?",
 "Only one thread writes; use a mutex or render each frame to its own buffer and write sequentially from the host after sync."),
("How does the writer interact with determinism?",
 "The file bytes must be identical across identical runs for a given config (deterministic float->int rounding) - a checksum test enforces it."),
],
"02-Ray-Tracing/14-Verifying-a-Raytracer": [
("What is verification in a raytracer?",
 "Proving the renderer is correct: unit tests on geometry, golden images, analytic solutions, and determinism - independent of subjective beauty checks."),
("What are golden images?",
 "Reference renders committed alongside code; a test re-renders the same scene and compares pixels (exact match or tight tolerance) - the regression net."),
("What does a toplevel test assert about the pipeline?",
 "End-to-end: config in -> exact file bytes out - proving import, trace, tone map, and write all round-trip consistently."),
("What analytic cases validate the geometry?",
 "Schwarzschild geodesics with known deflection angle, photon orbit radii, precession per orbit; the integrator must reproduce closed-form values."),
("What are the sphere/plain analytic tests?",
 "An offset sphere render produces a circle with the exact projected radius; a disk edge-on produces a line - the most basic correctness catches."),
("How do you validate the disk emissivity model?",
 "A spatially uniform laminar disk must have constant surface brightness along a radial line at the same viewing angle - direct transfer math check."),
("What is the determinism test?",
 "Run the identical config twice on different GPUs (or twice on one) and hash the outputs; any byte difference flags nondeterminism in RNG or reduction."),
("How do you validate the integrator error?",
 "Compute per-orbit drift of conserved quantities (E, L, Q for Kerr) and plot drift vs step size - the slope reveals the order of accuracy."),
("How do you validate with known images?",
 "Compare the photon-ring diameter and shadow boundary in your render against published figures (e.g., the 5.197 radius scaling for a distant observer) within a percent."),
("What are the diagnostics images?",
 "Dump intermediate buffers (emissivity, beaming, depth, position) as false-color images - spot which stage distorted the final picture."),
("What is fuzz testing / property testing?",
 "Random camera poses + random scenes: assert no NaNs/Infs, all t in expected tangents, no black-screen anomalies - cheap and broad."),
("What does a perceptual comparison add?",
 "An error map (reference - render)/reference per pixel; a 'pass' threshold of e.g. 1e-4 relative - quantitative, not qualitative."),
("How do you structure the test suite?",
 "Tier 1: unit (geometry, metric) TU each <20ms. Tier 2: golden images <1s. Tier 3: full scenes nightly. CI runs 1-2, nightly 3."),
("When is visual inspection sufficient?",
 "Never for correctness - only for look. All scientific claims pass through the numeric suite; visuals are the jewelry on correctness."),
("What is a regression radar?",
 "A set of 6-10 canonical renders (different spins, inclinations) with hashes; any change re-runs them all - the canaries for physics drift."),
]}