"""Curated Q&A for 06-Radiative-Transfer leaves."""
RAD = {
"06-Radiative-Transfer/01-Radiative-Transfer-Equation": [
("Write the radiative transfer equation (RTE).",
 "dI_nu/ds = j_nu - alpha_nu I_nu, where I_nu is the specific intensity, j_nu the emissivity, alpha_nu the absorption coefficient, and s the path length."),
("What is the formal solution?",
 "I(s) = I0 exp(-tau) + integral_0^s j(s') exp(-(tau(s)-tau(s'))) ds'; the emissivity integrated along the path, attenuated by optical depth."),
("What is the optical depth (tau)?",
 "tau = integral alpha ds - the dimensionless opacity along the path; tau>1 opaque (absorption dominant), tau<1 transparent (escaped)."),
("What is the interplay with emissivity?",
 "Intensity = source function S = j/alpha; in thermal equilibrium S = B_nu(T); the RTE's balance of emission vs loss sets the emergent field."),
("How does this equation show in a raytracer?",
 "The raytracer integrates j_nu along each geodesic, multiplying by the attenuation exp(-tau) and adding emission - a 'composition' of mono-frequency samples."),
("What are the standard assumptions in M87-style imaging?",
 "Optically thin synchrotron (tau ~ 0.1), so the image is dominated by integrated j along the line - simplifying the transfer callback greatly."),
("What is the difference between specific and bolometric intensity?",
 "I_nu is per unit frequency; integrated over nu gives bolometric I. The raytracer computes per-frequency to build spectra (color)."),
("How does the RTE handle scattering?",
 "Scattering adds a source term from other directions; for synchrotron (non-scattering in the relevant band) the code drops it - a tidy approximation."),
("What is the line-of-sight parameterization?",
 "s is the proper path length along the ray; the non-trivial integral uses dtau = alpha_nu ds, with the frequency shift folded in via Lorentz invariance."),
("What is Lorentz invariance of emission/absorption?",
 "j_nu/nu^2 and alpha_nu/nu are frame-invariant; the raytracer can thus integrate in the fluid rest frame and convert intensity with the right powers of delta."),
("How do you discretize the continuous RTE?",
 "Per ray segment: numerical quadrature of j and alpha using a single frequency bin per pixel; Simpson/trapezoid with adaptive density near strong signal."),
("What is the analytic thin-limit?",
 "tau << 1: I ~ integral j ds (no absorption); the treasure of synchrotron images - the code's default simplification with documented error bounds."),
("How is the image formed from many rays?",
 "Each pixel = its ray's I; the lensing/geometry routes the rays - the RTE is evaluated per ray-hit as the emitter's contribution."),
("What validation pins the integrator?",
 "Constant j, constant alpha column: exact analytic exp(-tau) and emission - the RTE kernel reproduces the closed form to tolerance."),
],
"06-Radiative-Transfer/02-Optical-Depth": [
("What is the optical depth and its ranges?",
 "tau = integral alpha ds; tau>1 means 'absorptively opaque' (shielding, reabsorption), tau<1 'transparent' (emission escapes) - the unitless ruler of transfer."),
("How does tau enter the formal solution?",
 "The attenuation factor e^-tau and the source-weight exp(-(tau-tau')) appear; tau accumulates monotonically along the ray - the RTE's clock."),
("Why is the disk often optically thin?",
 "In M87-band optically thin synchrotron the emissivity's self-absorption is weak: tau~0.1-0.01 at the ring - the transparency is the reason the image integrates volume emission."),
("What is the condition for 'thin'?",
 "tau << 1 across the line; the transmitted fraction ~ 1 - small corrections; for thick regions the transfer saturates toward the source function."),
("What does an opaque region do to the image?",
 "It obstructs background emission (eclipses the far ring) and re-emits at the local source function - a self-absorbed blob appears as a secondary ring feature."),
("How is tau accumulated in the code?",
 "Integrate alpha along the affine parameter with the frequency-shift bookkeeping: dtau = alpha_rest * (nu_obs/nu_emit) * dl - the combination that makes tau frame-true."),
("What is the tau-path relationship?",
 "For a constant-density column: tau = alpha L; in the disk, tau varies with the local B^2-dependent absorption - the radiative balance loops back in."),
("How does optical depth affect the observed ring?",
 "If the inner shell is opaque (tau>1), the visible ring is the surface where tau~1, moving the peak outward vs thin emission - a measurable offset."),
("What is the 'source function' saturation?",
 "Where tau>>1, I -> S (the local thermal source); synchrotron self-absorption drives S toward the blackbody limit of the emitting electrons."),
("How do you compute tau along a geodesic?",
 "Each ray segment accumulates alpha_nu(local rest) * (dl / frequency ratios); converting affine to physical length uses the metric components."),
("What is the frequency coupling in alpha?",
 "alpha_nu ~ n_e B^(...) nu^(-(...)) for synchrotron; the raytracer samples at the shifted frequency - the same map as the emissivity evaluation."),
("What does the floor/clamp do to tau?",
 "If a cell density floor creates spurious opacity, the image dims - report cell floors with every image (the artifact budget)."),
("What is the thin/integration validation?",
 "A homogeneous column with known j, alpha: the analytic I(tau) must match; drift of that relation is a transfer-kernel bug."),
("How does 'we see through the shadow' work?",
 "Even inside the shadow region, foreground emission (thin) contributes, so the shadow's blackness is relative to the inflow-bright background - a subtle fill."),
("What is the practical dialog with the image?",
 "Check the ring's tau map: if the sheath tau is <0.5 the thin-limit render is valid; if it crosses 1, switch the kernel to the full solution and re-render."),
],
"06-Radiative-Transfer/03-Synchrotron-Emission": [
("What is synchrotron radiation?",
 "Radiation from relativistic electrons gyrating in magnetic fields - the dominant emission process of hot accretion plasma in the visible/MIR/radio bands."),
("What sets the characteristic frequency?",
 "nu_c ~ (3/2) gamma^2 (eB/2 pi m c) - an electron at Lorentz factor gamma radiates strongly near its critical frequency."),
("Write the synchrotron emissivity form.",
 "j_nu ~ sqrt(3) e^3/(4 pi m_e c^2) B sin(theta) nu_obs-normalized via the K_{5/3} kernel; the code integrates over the electron energy distribution."),
("What is the typical electron distribution?",
 "A power law n(gamma) ~ gamma^(-p) (p~2-6, kappa or thermal); the emission then follows j_nu ~ B^((p+1)/2) nu^(-(p-1)/2) - the classic scaling."),
("What does B do to the spectrum?",
 "Higher B boosts j and shifts nu_c up; the image's color/spectrum is an effective measure of B along the line-of-sight (the emission's scanner)."),
("How do the electrons' temperatures matter?",
 "The emission sees the electron distribution function f(gamma); the code converts gas/internal energy (via a Te closure, e.g. the Rbeta prescription) to the emitting electron population."),
("What is the angular dependence?",
 "j ~ (sin theta)^((p+1)/2) with theta the angle between B and the direction; ordered-field regions thus modulate brightness - a B-visualizer."),
("What frame does the code evaluate in?",
 "The fluid rest frame (b^mu basis); the emissivity is Lorentz-invariant and converted to observer values via the delta powers - always rest-frame-first."),
("What is the thermal vs nonthermal mixture?",
 "Observations often need a hybrid: a thermal (kappa) core plus a power-law tail; the code's emissivity formula must accept the chosen distribution."),
("How does synchrotron scale with the disk observables?",
 "I ~ integral j_nu ds ~ (B^2 x n_e) - the de facto brightness map visualizes the stress/energy density; why the ring tracks the GRMHD's magnetic peaks."),
("What are the polarization observables?",
 "Linear polarization from aligned gyration axes: a fraction ~ (p+1)/(p+7/3) emerges; the raytracer's polarization integrand tracks B on the plane of sky."),
("What are the low/high tail behaviors?",
 "Low nu: optically thick self-absorbed, the spectrum turns over; high nu: thin, power-law; the raytracer's absorption treatment must engage at the turnover."),
("How do you validate synchrotron?",
 "A uniform field + monoenergetic electrons: analytic lambda profile; compare I vs the analytical curve at a reference nu - agreement at the per-milli level."),
("What is the key interplay with the GRMHD data?",
 "j_nu(B, n_e, Te) reads the snapshot fields; the raytracer must interpolate B, n_e, Te at the hit point - the correctness of the ring's map rests on these."),
("What is the summary?",
 "Synchrotron is the star of the show: its emissivity turns GRMHD fields into light, and its (nu, B, angle, distribution) dependences are your renderer's core science."),
],
"06-Radiative-Transfer/04-Synchrotron-Absorption": [
("What is synchrotron self-absorption (SSA)?",
 "The same electrons that emit also absorb photons, significant where the source is dense/bright; the process sets the turnover of the spectrum."),
("What is the absorption coefficient's form?",
 "alpha_nu ~ (1/nu^2) j_nu folding with the K_{5/3} kernel; for a power law it is alpha ~ n_e B^((p+2)/2) nu^(-(p+4)/2)."),
("What is the self-absorption turnover?",
 "Where the optically-thick and thin components cross: the spectrum peaks, and the source saturates at the brightness temperature."),
("When does the code engage SSA?",
 "In the inner ring where B and n_e peak (tau crossing ~1); thin-region sims can skip it, but faithful M87-like renders include it."),
("What does the absorption do to the image?",
 "It caps the innermost ring's intensity and shifts its peak outward - a subtle but real morphological offset; neglecting it inflates the inner flux."),
("How is the brightness-temperature limit expressed?",
 "I_nu <= 2 k T_b nu^2/c^2 with T_b ~ T_e; SSA saturates intensity to the electrons' Rayleigh-Jeans tail - a hard physical ceiling."),
("How is alpha evaluated in the code?",
 "Like j: rest-frame alpha * (delta) per frequency; the transfer accumulates dtau = alpha factor along the ray - consistency with j is unit-tested."),
("What is the relationship to Faraday?",
 "SSA absorption is handed; with Faraday rotation the polarization rotates, adding a wavelength-dependent twist - a second-order effect worth a channel later."),
("How does SSA interplay with the beaming map?",
 "The delta powers differ for thick vs thin regimes; the intensity map's contrast is modified where tau>1 - the beaming model must know which regime."),
("What is the SSA validation?",
 "Uniform B, thermal distribution: compare against the analytic optically-thick spectrum I_nu ~ nu^(5/2) - exact agreement at the turnover."),
("What are SSA artifacts to watch?",
 "Under-resolved alpha near the strongest cells produces ringing spots; the aggregation of alpha and mesh transfer both enter - grid-consistency tests catch them."),
("How does the temperature floor affect SSA?",
 "Floors inflate the density near vacuum -> spurious alpha -> darkened ring; the visual consequence of a poorly-set floor is systematic ring dimming."),
("What is the emission-absorption consistency?",
 "Einstein relations link alpha to j through the electron distribution; the code implements the Kirchhoff limit: I -> B_nu where tau>>1 - a self-consistency test."),
("How do you turn SSA on/off cleanly?",
 "A model parameter toggle; render both and the difference diagnoses whether the chosen regime (thin vs thick) is physical for the target."),
("What is the summary?",
 "Self-absorption is the thermostat of the ring: it caps, shifts, and saturates emission in the magnetized core - implement it, validate it, and render realistically."),
],
"06-Radiative-Transfer/05-Bremsstrahlung": [
("What is bremsstrahlung emission?",
 "Radiation from accelerating free electrons in the Coulomb field of ions - a thermal continuum process relevant in the hot inner-flow plasma."),
("What is the emissivity form?",
 "j_nu ~ n_e n_i T^(1/2) exp(-h nu/kT) g_ff (Gaunt factor ~1-10), with the density product and temperature power - the thermal free-free radiator."),
("When does bremsstrahlung matter in black-hole images?",
 "In the optically thin hot inflowing gas where T ~ 1e10 K; it adds a soft continuum component to the synchrotron-dominant image."),
("What is the free-free spectrum?",
 "Nearly flat below the thermal cutoff, then exponentially suppressed - very different from the power-law synchrotron - a distinguishing attribute."),
("How does the Gaunt factor behave?",
 "g_ff ~ 0.5-5 in most disk conditions; keep it ~1 or interpolate; its logarithmic variation is a percent-level correction."),
("What is the temperature scaling of the free-free?",
 "Total P_ff ~ T^(1/2) at fixed density; the hot innermost material radiates most strongly - the code's temperature-brightness relation."),
("How do bremsstrahlung and synchrotron coexist?",
 "They sum: I_tot = I_sync + I_ff; the composite decides the observed color mixing - the raytracer adds them in the line-of-sight integral."),
("What is the absorption counterpart?",
 "Free-free absorption alpha_ff ~ n_e^2 T^(-3/2) nu^(-2); thick in soft bands, handled by the same alpha channels of the transfer equation."),
("What is the code's practical handling?",
 "Compute j_ff, alpha_ff from the same cells; evaluate at the shifted frequency; accumulate all in the one line-of-sight integrator."),
("What does it look like in a render?",
 "A faint halo around the hot core; its presence distinguishes a radiating hot inflow from a purely magnetized one."),
("What validation compares?",
 "A uniform hot sphere: analytic total emission known (Rybicki & Lightman emissivity); per-nu agreement to a few percent."),
("What are the unit-mix pitfalls?",
 "n in cm^-3, T in K, nu in Hz: brittle conversions - centralize all in the radiative module's unit layer; I/O never touches coefficients."),
("How does bremsstrahlung interplay with the electron heating?",
 "The electrons' T_e prescription drives j_ff; high T_e from magnetic reconnection boosts the halo - observing the halo constrains T_e - a real closing of the loop."),
("How do frames with/without it differ?",
 "Enable a toggle: the inner core gains a soft component, the thin synchrotron ring barely changes - the difference flags both processes in a rendered panel."),
("What is the summary?",
 "Bremsstrahlung is a thermal continuum from hot free electrons; implement it as a j/alpha channel so the renderer's color science stays complete."),
],
"06-Radiative-Transfer/06-Inverse-Compton": [
("What is inverse Compton scattering?",
 "Energetic electrons scattering low-energy photons up in energy - the dominant hard-X-ray/gamma producer from hot coronal plasma."),
("What is the single-scatter energy gain?",
 "nu_out ~ gamma^2 nu_in (head-on Thomson limit), hugely boosting weak seed photons - approximated in code via the Compton kernel."),
("What is Comptonization?",
 "Multiple scatterings random-walking photon energies until escape - the 'Compton cloud' spectral feature of hard states."),
("When does it matter for black-hole images?",
 "The corona/disk boundary reprocesses disk photons into hard X-rays; relevant to spectral synthesis though secondary for optical-radio rendering."),
("How does it compare to synchrotron for the visual band?",
 "Synchrotron dominates optical-radio; IC adds keV-MeV; the renderer stays visual-dominant but the SED builder may include an IC term."),
("What is the Thomson vs Klein-Nishina regime?",
 "At high photon energy the cross section falls (K-N suppression); codes either cap via the KN factor or document the approximation's band."),
("What is the spectral signature?",
 "A power-law tail (corona) plus a soft hump (disk) - the Comptonized shape of hard-state SEDs; the renderer's SED builder can overlay it."),
("How does the temperature enter?",
 "The Compton y-parameter ~ 4 (kT_e/m_e c^2) max(tau, tau^2) sets the boost; strong y = hot, optically thick corona."),
("What validation exists?",
 "The Kompaneets equation's analytic limits for idealized coronal models match Monte Carlo codes - a reputable unit kernel."),
("What is the code's cost model?",
 "Full kinetic Compton scattering is expensive; practical renderers ignore it for the visual band with a documented domain of validity."),
("How is it observationally probed?",
 "The hard X-ray tail via X-ray telescopes; the raytracer's SED builder keeps the band open for completeness even when visuals ignore it."),
("How do IC and synchrotron connect?",
 "Synchrotron seed photons re-scattered by the same electrons barely reach the ray band; the two decouple cleanly for rendering - a realistic simplification."),
("What is the frame-sync requirement?",
 "IC involves two photon frames; the per-frequency transforms must handle the seed photon's frame - keep the seed isotropic in the fluid frame."),
("How do you add IC without overbuilding?",
 "A tabled kernel: pick the seed spectrum, run y-power shaping, add the inverse-Comptonized tail into the SED output - visuals and ring remain unchanged."),
("What is the summary?",
 "Inverse Compton is the hard-X-ray workhorse - implement it as a corner-kernel for the SED and document the band's validity for the visual render."),
],
"06-Radiative-Transfer/07-Rest-Frame-Emissivity": [
("What is the rest-frame emissivity?",
 "The emission coefficient j_nu evaluated in the fluid's instantaneous rest frame (where u^mu = 0 spatial part) - the frame in which the synchrotron formulas are simplest."),
("Why must emissivity be evaluated in the rest frame?",
 "The standard synchrotron/blackbody formulas (j, alpha) are derived for an isotropic electron gas at rest; any other frame requires relativistic corrections."),
("What is the fluid rest frame in the code?",
 "Defined by the 4-velocity u^mu from the GRMHD state; the magnetic field there is b^mu (the comoving projection), with |b| = sqrt(b^mu b_mu)."),
("How do you transform j between frames?",
 "j_nu/nu^2 is Lorentz invariant, so j_obs = (nu_obs/nu_emit)^2 j_rest - the delta-squared relation central to the whole transfer."),
("What does the Eulerian vs Lagrangian distinction mean?",
 "The observer integrates along a ray (Eulerian); the emissivity is computed at each point in the co-moving frame (Lagrangian) - the code switches frames per quadrature point."),
("How does the energy distribution enter rest-frame formulas?",
 "The electron distribution function f(gamma) is defined in the rest frame; j and alpha are integrals over gamma - all evaluated in that frame."),
("What is the relation to b^mu?",
 "The emissivity's sin(theta) factor uses the angle between b and the photon direction, both measured in the rest frame - the geometric core of the pattern."),
("What is the code's frame convention?",
 "All interpolated GRMHD fields at a point are transformed into the fluid rest frame before applying j formulas; consistency of this transform is unit-tested."),
("How is the rest-frame density normalized?",
 "The electron number density n_e and B are rest-frame quantities from the snapshot; the raytracer uses them directly (no ad-hoc Lorentz factors)."),
("What validation ensures frame correctness?",
 "A homogenous static plasma: compute j in rest frame; the observed I must match the analytic formula with delta=1 (no Doppler) - the frame sanity check."),
("What happens if you mix frames?",
 "Every emissivity mis-scalars: brightness, beaming, and colors all come out wrong - the most common subtle bug in relativistic rendering."),
("What is the heavy frame bookkeeping?",
 "Each quadrature point needs u^mu, b^mu, the photon's p_mu, and their dot products (p.u, p.b) - a small, formula-driven vector algebra block."),
("How does rest-frame emissivity link to spectra?",
 "The j_nu spectrum computed there is sampled at the emitted frequency; the observer frequency is set by the ray's redshift factor."),
("What is the key closed-loop test?",
 "Render a cold, static, optically thin fluid; intensity at each pixel must equal the integrated rest-frame j multiplied by known geometric factors - a pixel test."),
("What is the summary?",
 "Rest-frame emissivity is the 'physics core' of radiative transfer in the code - everything Doppler-flagged begins from a correct comoving-frame kernel."),
],
"06-Radiative-Transfer/08-Lorentz-Frequency-Shift": [
("What is the Lorentz frequency shift?",
 "The relation between emitted and observed photon frequencies for a moving source: nu_obs = nu_emit * delta, with delta the Doppler factor of the emitter's 4-velocity frame."),
("What is the standard form?",
 "delta = 1/(gamma (1 - beta mu)) where beta is the emitter's 3-speed and mu = cos of the angle between its velocity and the photon direction in the emitter frame."),
("How does it differ from gravitational shift?",
 "The Doppler shift comes from the emitter's motion (p.u_emit); the gravitational shift comes from the g_00 between points; total z combines them multiplicatively."),
("How does the code compute shifts?",
 "Per quadrature point: keep p_mu and the fluid 4-velocity; the ratio p.u_obs / p.u_emit gives the full factor, no separate Doppler/gravity split needed."),
("What is the sign convention?",
 "A receding (or static-with-gravity) emitter shifts to nu_emit < nu_obs (redshift, z>0); an approaching emitter blueshifts (z<0) - sign of delta tracks."),
("How does the shift affect emissivity evaluation?",
 "The rest-frame emissivity is sampled at nu_emit = nu_obs/delta; then the I_nu transfer flows with the delta^2 power - the code must apply both consistently."),
("What is the combination with the RTE?",
 "The formal solution over a path evaluates j and alpha at the REDSHIFTED local frequency at each step - the frequency tracking rides along the geodesic."),
("What does shift do to band images?",
 "At fixed observer band, a blueshifted emitter is seen at higher rest-frame nu (different spectral slope); colors and flux both change."),
("What validation checks the shift?",
 "Known emitter: analytic beta/mu reproduce the classical Doppler formula; static emitter at r reproduces sqrt(1-2M/r) - both to high precision."),
("What is the frame bookkeeping rule?",
 "Store p_mu; at each node compute u^mu from the fluid and b^mu; all dot products in the SAME (mostly - ) signature - one helper function, no ad-hoc algebra."),
("How does the shift interact with limb beaming?",
 "Same factor drives both: the direction projected onto u gives hu the Doppler - the bright approaching limb and its bluish color are the same phenomenon."),
("What is the relativistic aberration fold-in?",
 "The direction cosine mu is computed in the emitter frame with the photon direction transformed by the aberration formula - a subtle correction beyond naive 3D dot."),
("What happens at the intermediate-redshift (z~1) rows?",
 "The innermost ring's net shift flips sign across azimuth; the image's color gradient across the crescent is the visual diary of the shift."),
("How is shift accumulated in movie rendering?",
 "Each frame runs one frequency map; batches recompute the shift only for the moving fluid from the snapshot's velocity - cheap reuse of a static geometry."),
("What is the summary?",
 "The Lorentz shift is the 'color engine' of relativistic images - computed exactly as p.u ratios, applied to emissivity sampling, and validated against Doppler analytics."),
],
"06-Radiative-Transfer/09-Line-of-Sight-Integration": [
("What is line-of-sight integration?",
 "Evaluating the formal RTE solution along a geodesic by integrating emissivity (and opacity) at sampled points - the 'compose the image' step."),
("How are sample points chosen along the ray?",
 "Adaptively: fine steps where density/B gradient is large (near the disk/ring), coarse in vacuum; often tied to the geodesic integrator's own step."),
("What is the quadrature rule used?",
 "Trapezoid/Simpson in the thin limit; for alpha>0 a sub-step multiplication scheme (thick pixels handle saturation); order matches the geometry integrator."),
("How does one combine emission and attenuation?",
 "Backwards integration: start with I=0 at the observer, add j*ds and multiply by exp(-alpha*ds) per segment - walk forward or backward, consistent."),
("What is the 'first surface' vs 'volume' model?",
 "Thin-disks render one surface hit; real volume emission integrates over the whole path - the line integral is the volume generalization."),
("How does the code handle the frequency at integration?",
 "Each segment evaluates j at the emitted frequency that maps to the fixed observation bin; alpha likewise - the frequency map is threaded through the integral."),
("What are the cost drivers?",
 "The number of radiative samples per ray: adaptive density-based sampling keeps it ~O(100) per pixel even at 4k - the transfer budget is fractions of the geodesic budget."),
("What is the emitted-boost integration?",
 "The total intensity I at the observer is the sum over segments of boosted, attenuated j - mathematically the formal solution sampled."),
("What is the hit-based vs full-path integration?", "Disk shadow rendering often uses a dedicated hit; full-path is robust for volume (MHD-like) data - pick per-use-case in the pipeline."),
("How do you avoid double-counting?",
 "Sampling weights (ds proportionality) and the per-sample volume need consistent normalization - the ds measure is derived from the metric and the grid volumes."),
("What validation pins the integrator?",
 "A constant-alpha, varying-j analytic column: closed-form result matches to quadrature order; a vacuum ray returns exactly the sky background."),
("What is the polarization fold-in?",
 "Each segment also rotates/attenuates the Stokes vector (Faraday) - the line-of-sight integrator carries (I,Q,U,V) or complex amplitude per frequency."),
("How does path termination interact with integration?",
 "Capture (horizon) ends the integral; sky-miss ends with zero added intensity - both terminate cleanly, preserving the no-spurious-flux contract."),
("What is the movie-frame cache?",
 "Static-geometry frames reuse the sample-path weights; only the fluid state (thus j) changes - a large speedup for animations."),
("What is the summary?",
 "Line-of-sight integration is the transfer core - a path-weighted quadrature of j and alpha along each geodesic, adaptive, frame-true, and validated against analytic columns."),
],
"06-Radiative-Transfer/10-Disk-Photon-Sources": [
("What are the photon sources in a disk scene?",
 "The GRMHD gas volume (synchrotron/bremsstrahlung from plasma), possibly the disk surface ('photosphere'), and external background - all folded into j along the ray."),
("How is the disk's emission seeded?",
 "From the snapshot fields (rho, B, T_e): the emissivity model (e.g., thermal synchrotron with a power-law tail) maps each cell to j at the sampled frequency."),
("What does the photon source include for polarization?",
 "The synchrotron polarization fraction and angle from the B-field's sky-projected orientation - the initial Stokes vector per quadrature sample."),
("How is the vertical structure accounted for?",
 "The simulation's actual density stratification is used; the renderer doesn't assume a thin disk - volume emissivity picks up the corona, funnel, and plunging region."),
("What is the difference between photosphere and volume sources?",
 "A photosphere is a surface model (one hit per pixel); volume sources integrate the whole column - the former is cheaper, the latter physically faithful."),
("How do seed photons get their frequency?",
 "The observation band plus the local shift sets the emitted frequency; each source's SED is then sampled - consistency across the spectrum is the goal."),
("What is the treatment of foreground vs background?",
 "Attenuation along the path (alpha) decides whether a far source shines through; thick foreground dims/re-emits - the RTE's built-in ordering."),
("How does the disk's emissivity couple to B?",
 "Thermal synchrotron j ~ n_e B^(...); the B-map is the brightness driver - high-stress (high B) patches light up, the ring is the field's high-water mark."),
("What is the role of the electron temperature?",
 "T_e sets the spectrum's slope and the SSA turnover; a Te map from the GRMHD closure (Rbeta or similar) is the essential third ingredient."),
("How do you validate a disk scene source?",
 "Render one snapshot with a simple emissivity: the total flux and spectral shape must match an independent calculation (or the code's own 1-D column sanity)."),
("What is the variability source for movies?",
 "The GRMHD's turbulent density/magnetic evolution modulates j - the per-frame flicker of the ring is the simulation's physics, not a render artifact."),
("How do discrete cells become smooth emissivity law?",
 "Interpolation of (rho, B, Te) from the staggered/cell-centered grid into a smooth field (trilinear/Catmull) before computing j - smoothness directly affects image quality."),
("What is the photon-counting view?",
 "The renderer attributes each pixel's energy to the physical source contributions; diagnostics can split the map by dominate source (disk, corona, funnel)."),
("What is the summary?",
 "Disk photon sources are the GRMHD state rendered into j - density, field, and temperature driving emissivity/polarization; the fidelity of the final image rests on reading them correctly."),
],
"06-Radiative-Transfer/11-Spectrum-Synthesis": [
("What is spectrum synthesis?",
 "Building the emergent spectral energy distribution (SED) of the source by rendering over a grid of observation frequencies and integrating all pixels per band."),
("How does the code produce a spectrum?",
 "Render the image at each band nu (or sample many rays' monochromatic intensity) and integrate I over the image plane - the SED is the aggregated observable."),
("What is the per-ray spectral computation?",
 "Each ray carries (I_nu) at one observation frequency; a spectrum requires running the transfer at many frequencies - frequency is a loop dimension."),
("What is the role of the SED in imaging?",
 "It determines the color/bolometric weighting for an image; the composite (multi-band) image integrates the SED convolutionally."),
("How do you accelerate frequency sweeps?",
 "For pure-power-law emission the frequency dependence factors out of the geometry; reuse a small set of basis rays and scale by the SED - a huge speedup."),
("What is the difference between the 'monochromatic' and 'bolometric' images?",
 "Monochromatic samples one nu; bolometric integrates the SED - both are renderer outputs, the SED being the measurement most directly comparable to telescopes."),
("How is the spectrum limited by the emissivity model?",
 "Each model (power-law, kappa, hybrid) has its own spectrum; synthesis surfaces the model's assumptions - compare models at the SED level, not just images."),
("What is the SED's sensitivity to T_e and B?",
 "T_e sets the spectral slope/turnover; B sets overall level - the SED is the aggregated fingerprint of the disk's thermodynamic state."),
("What does a spectrum do for validation?",
 "Compare the code's integrated SED to the known analytic result for a simple disk/monoenergetic model - the definitive end-to-end scientific check."),
("What is the polarization spectrum?",
 "Rendering Q/U per frequency gives the polarization SED - a signature (RM, fraction) observable; run the Stokes channel wholesale."),
("How does variability show in spectra?",
 "Time-series of integrated flux at a band = the light curve - the renderer's movie frames at each band generalize to light-curve synthesis."),
("What is the anti-aliasing concern for bands?",
 "The SED must be densely sampled near spectral turnovers to avoid 'spectral ringing' - adapt frequency resolution where curvature is high."),
("How is the final SED delivered?",
 "A table (nu, I_nu integrated) plus the multi-band composite images; both feed the observer-visible science products."),
("What is the summary?",
 "Spectrum synthesis is the frequency dimension of rendering - integrate per-band images into an SED, accelerate via basis rays, and use it as the end-to-end validation channel."),
],
"06-Radiative-Transfer/12-Doppler-and-Beaming-in-Emission": [
("What is Doppler beaming in emission?",
 "The relativistic enhancement/attenuation of emitted intensity with the emitter's motion: the delta^2/(delta factors) change the observed brightness and color."),
("What is the beaming factor for synchrotron?",
 "Observed specific intensity scales as delta^2 j_rest (per frequency) - the emitter's motion preferentially brightens the APPROACHING side."),
("Why is the approaching side brighter?",
 "delta > 1 toward the motion: photons are boosted into a narrower beam, so more reach the observer - the iconic hot crescent of black-hole images."),
("How is beaming computed per ray?",
 "The delta factor comes from p.u_emit at each quadrature point; it multiplies j and rescales the frequency - all within the same frame transform block."),
("What does the shift and beaming do jointly?",
 "The intensity scales as delta^2 (for I_nu) AND shifts the frequency; together they produce brightness AND color asymmetries - two observable signatures."),
("What is the distinguishing picture of beaming?",
 "Edge-on high-beta flow: the approaching limb is a thin bright blue arc; the receding limb broad and red - the classic 'asymmetric crescent'."),
("How does beaming interact with the disk geometry?",
 "The direction cosine mu between photon and velocity sets delta; on the far side (away in the image), mu is large - beaming fades and gravitational redshift wins."),
("What is the 'apparent speed' illusion?",
 "Optically thin blobs moving near-c with mild beaming appear boosted in brightness; in movies hotter spots flash/travel - a direct beaming signature."),
("How is the intensity spectrum modified?",
 "I_nu is measured at observed nu; the emissivity at the shifted nu differs - the SED slope is 'slanted' by the beaming - visible in color maps."),
("What validation checks beaming?",
 "A rigidly rotating ring: per-azimuth intensity follows the analytic delta^2 rule; flipping spin flips the crescent - the golden beaming test."),
("What is the polarization-beaming correlation?",
 "Synchrotron polarization fraction is frame-invariant at delta; the polarization ANGLE differs via aberration - beaming affects polarized images observably."),
("How does the code separate boost from shift?",
 "In code, the same divisor drives both: the observed I_nu = delta^2 j_rest(nu/delta) ... - one formula, two effects; implement one kernel for both."),
("What is the frame-rotation subtlety?",
 "The direction mu must be computed with the aberration-transformed photon 4-vector in the emitter frame - a common hidden source of beaming bugs."),
("How does beaming manifest in variability?",
 "Orbital hot spots modulate intensity sinusoidally at the orbital frequency with a beaming peak when the spot moves toward the observer - a known light-curve feature."),
("What is the summary?",
 "Doppler beaming is the delta factor driving brightness and color asymmetry - one kernel gluing shift and boost, validated by the rotating-ring test."),
],
"06-Radiative-Transfer/13-Polarization": [
("What is synchrotron polarization?",
 "The linear polarization produced by the anisotropic gyrating radiation of aligned-helix electrons - typically 60-75% in the E-vector for a uniform B."),
("What is the polarization fraction?",
 "For a power-law electron index p: pi = (p+1)/(p+7/3); for a monoenergetic gas: 75% - the code must output this geometric fraction."),
("What is the polarization angle?",
 "The electric-vector position angle (EVPA) on the sky - measures the B-field's sky-projected direction; its pattern is the image's B-field map."),
("What is Faraday rotation?",
 "The rotation of the polarization angle with wavelength as the wave passes magnetized plasma: chi(lambda) ~ lambda^2 RM - the RM is a plasma diagnostic."),
("What is the rotation measure (RM)?",
 "RM ~ integral n_e B_parallel ds (in suitable units) - the aggregate magneto-ionic column; its sign flips with B direction."),
("How is polarization a tensor in the RTE?",
 "The transfer expands to Stokes parameters (I,Q,U,V) with emissivity/absorption matrices (absorption, rotation, conversion) - the '7-coefficient' formalism."),
("How does the raytracer handle it?",
 "Per quadrature segment, the Stokes vector is advanced: emission adds (p_JI, p_JQ, ...); Faraday rotates Q,U; absorption multiplies - integrated like I alone."),
("What is the parallel transport of polarization?",
 "The polarization basis must be parallel-propagated along the geodesic - the EVPA's orientation on the sky derives from the transported basis, not the naive image frame."),
("What does polarization add to the image?",
 "It reveals field structure invisible in intensity (kinks, loops, reconnection) - maps of fractional polarization are richer than I alone."),
("What is the stability (EVPA swing) observable?",
 "The EVPA sweeping as a spot orbits reflects both the field geometry and the beaming - a time-domain polarization probe."),
("What is the validation of the Stokes integrator?",
 "Uniform B, no Faraday: analytic fractional polarization matches; with constant RM: the lambda^2 law holds per pixel - both closed-form checks."),
("What are the numerical pitfalls?",
 "Division-by-I when computing fractional polarization near the shadow; EVPA wrap-around at 180 deg; and the basis's discontinuities at the poles - all must be handled."),
("How does the code output polarized images?",
 "Channels (I,Q,U,V) per pixel at each band, or the derived (fraction, EVPA) maps - the deliverable for both display and analysis."),
("How does polarization connect to GRMHD?",
 "The pattern of the EVPA trace-out the magnetic structure at the emission site - polarization imaging is a direct probe of the B-field the GRMHD predicts."),
("What is the summary?",
 "Polarization is the Stokes extension of the transfer - emissivity/absorption/Faraday matrices plus parallel-transported bases - turning B-maps into field diagnostics."),
],
"06-Radiative-Transfer/14-Post-Processing-Images": [
("What is image post-processing?",
 "The final pipeline that converts raw per-pixel intensity/Stokes frames into a viewable, scientifically analyzable image (fits, color, metrics)."),
("What are the common post steps?",
 "Tone mapping, color balance, denoising, deconvolving dishes (PSF), converting to physical scale, and overlaying diagnostics (contours, beam)."),
("What is the difference between raw and displayed images?",
 "Raw holds physical intensity at each pixel; display applies nonlinear scales (log/asinh), color tables, and blur - the physics stays in the raw channel."),
("How is the image convolved with a telescope beam?",
 "The true image is convolved with the PSF (e.g., a Gaussian beam) to mimic observations at a finite resolution - an essential step for realism."),
("What is image-plane rescaling?",
 "Mapping the render (in units of M/D) to physical angular size and flux units (Jy, mJy/beam) using the source distance and the SED."),
("How do you denoise a Monte Carlo image?",
 "Sample-count-based variance; higher supersampling near the ring reduces noise; denoise via conservative filters (no structures beyond the PSF)."),
("How are colors assembled?",
 "Render 2-3 bands (e.g., 230 GHz, sub-mm) and map to a color space with the SED weighting - the chromatic image blends flux and shift science."),
("What is the standard image product?",
 "A FITS datacube (I,Q,U,V; or (I, f, EVPA)) at the chosen band with full WCS metadata - the artifact telescopes can compare to."),
("What diagnostics accompany images?",
 "Total flux, image moments (center, compactness), asymmetry metrics, and the ring radius profile - quantitative summaries from the pixels."),
("How is temporal post-processing different?",
 "Movies add frame interpolation/temporal smoothing; variability metrics (rms, power spectrum) ride on filtered light curves."),
("What is the anti-burnout guard?",
 "Clamp/saturate near-dark pixels before tone mapping; the raw channel is never touched - display brightness only adjusts through the tonemapper."),
("What does a light curve require?",
 "Time-tagged flux integrations in a band across frames - the renderer emits them alongside images for the time-domain science."),
("How do you validate a post image?",
 "The circular photon-ring radius, shadow center, and known fractional-polarization (uniform-field checks) reproject onto the final image - a quantitative gate."),
("What is the deliverable contract?",
 "Raw physical intensity + metadata + display render + diagnostics, all coherent: the post-pipeline is where science meeting images meets the telescope."),
("What is the summary?",
 "Post-processing turns ray-traced physics into telescope-ready products - PSF convolution, scale, SED color, diagnostics - while keeping the raw data intact and auditable."),
]}