"""Curated Q&A for 03-Relativity leaves."""
REL = {
"03-Relativity/01-Spacetime-and-Events": [
("What is an event in relativity?",
 "An event is a point in spacetime labeled by four coordinates (t, x, y, z), or (t, r, theta, phi). It is the fundamental object: 'here-now' for a process to happen."),
("What is the difference between space and spacetime?",
 "In Newtonian physics space and time are separate, absolute arenas; in relativity they are unified into a 4-dimensional manifold where the interval between events mixes them."),
("What is a worldline?",
 "The curve an object traces through spacetime - the set of events it visits. Test particles and photons both move along worldlines; the spacetime metric decides which are allowed."),
("What is the causality structure?",
 "Light cones at each event split spacetime into causal (inside the cone - past and future) and spacelike (outside - unconnectable) regions; this ordering is absolute and frame-independent."),
("What is the interval between two events?",
 "The proper time squared ds^2 = g_mu,nu dx^mu dx^nu; for timelike separations it is proper time, for null separations zero, for spacelike separations proper distance."),
("Why do black holes have an 'elsewhere' concept?",
 "Inside the horizon the roles of t and r swap: 'forward in time' becomes 'toward the singularity', so escaping is impossible just as going back in time is - causality is warped."),
("What is an inertial observer?",
 "A freely falling observer with no proper acceleration; locally such observers see Minkowski physics (the equivalence principle). All real motion is studied against locally inertial frames."),
("How does the spacetime picture explain gravity?",
 "Mass-energy curves the spacetime, and objects follow the straightest possible paths (geodesics) in the curved geometry - 'gravity' is that geometry rather than a force."),
("What are the dimensions of spacetime in the Kerr case?",
 "Four: (t, r, theta, phi) with axial symmetry (phi) and stationarity (t) giving two Killing vectors; the resulting conserved constants frame the geodesic motion."),
("What is the topology of the exterior for an observer?",
 "The black hole's exterior is the region r > horizon (Boyer-Lindquist r+); the interior (r < r+) is not in causal contact with a distant observer."),
("What happens when you cross the event horizon?",
 "Locally nothing special happens; globally, the escape velocity exceeds c and the geometry forces future-directed motion inward - the observable signature is the boundary of the shadow."),
("How is the affine parameter defined?",
 "An affine parameter lambda parametrizes geodesics so the tangent vector's covariant derivative vanishes; for photons it is not the proper time but scales uniformly along the path."),
("What are the components of the canonical 4-velocity?",
 "u^mu = dx^mu/dtau (or dX^mu/dlambda for null); its norm u.mu u^mu = -1 for massive particles, 0 for photons."),
("What does the existence of infinity mean for rendering?",
 "'Observer at infinity' is the standard camera: boundary-condition geometry where the image plane captures the asymptotic look-back cone."),
("How do you physically picture an event inside the horizon?",
 "The 'all roads lead to r=0' picture: every direction you point ultimately points to the singularity, because the geometry rediscovers the radial direction as timelike."),
("What role do events play in the raytracer code?",
 "Each integration step moves a photon from one event to the next; the raytracer is a solver of the worldline's null condition in the chosen coordinate chart."),
],
"03-Relativity/02-Index-Notation-and-Tensors": [
("What is index notation?",
 "A compact convention where tensor components carry superscript (contravariant) and subscript (covariant) indices; repeated one-up one-down indices imply a sum (Einstein convention)."),
("What is the Einstein summation convention?",
 "Repeated indices in a term imply summation over that index: g_ab x^b means sum over b. It removes explicit summation signs from tensor equations."),
("What is a contravariant vector (index up)?",
 "Components of a tangent vector like x^mu or momentum p^mu; they transform with the Jacobian inverse of a coordinate change, guaranteeing geometric (coordinate-independent) meaning."),
("What is a covariant vector (index down)?",
 "Components of a covector (dual) like the gradient df_mu or the metric's inverse-indexed piece; they transform with the Jacobian (forward) - the pairing yields an invariant."),
("What is the metric and why is it called a tensor?",
 "The metric g_mu,nu is a symmetric (0,2) tensor defining the inner product of tangent vectors and hence the interval; being a tensor means it transforms predictably under coordinate change."),
("How do you raise and lower indices?",
 "v^mu = g^mu,nu v_nu and v_mu = g_mu,nu v^nu using the metric and its inverse; the operations turn vectors into covectors and back - central to the geodesic equations."),
("What are Christoffel symbols?",
 "Gamma^rho_mu,nu = (1/2) g^rho,sigma (g_sigma,mu,nu + g_sigma,nu,mu - g_mu,nu,sigma); the connection coefficients encoding how basis vectors change across the manifold."),
("What is the difference between a tensor and a connection?",
 "A tensor transforms covariantly; the Christoffel symbols are NOT tensors - they encode coordinate-dependent bookkeeping of how vectors are parallel transported."),
("What is the covariant derivative?",
 "A connection-graded derivative that accounts for the change of basis: nabla_v T = dT + Gamma*T terms; it is the correct generalisation of 'take derivative' on a manifold."),
("Why is the metric symmetric (g_mu,nu = g_nu,mu)?",
 "The inner product is symmetric; the metric equals its transpose by definition, which simplifies its 10 independent components (diagonal + 6 off-diagonal in 4D)."),
("How do the soldered indices work in a 3+1 split?",
 "Splitting spacetime into time + space, indices split into mu = (0, i); the metric blocks then sometimes get written with separate g_00, g_0i, g_ij pieces."),
("What is the particle Lagrangian in index form?",
 "L = (1/2) g_mu,nu x'^mu x'^nu (with '.' = d/dlambda), whose Euler-Lagrange equations are the geodesic equations - the bridge from metric to motion."),
("How do you check index correctness?",
 "Free indices must match on both sides and the same index never appears three times; the equations must hold for each index value - a mechanical, verifiable property."),
("What is the importance of the Killing vectors in index language?",
 "A Killing vector k^mu satisfies k_(mu;nu) = 0; the quantity p_mu k^mu is then conserved along geodesics - the formal statement behind E, L and Q."),
("Why do we keep using coordinate-chart indices in code?",
 "The raytracer integrates numbers in a chart (e.g., Boyer-Lindquist); index notation is the bookkeeping that keeps those 16 metric components honest."),
("What is the gut-check for any tensor equation in code?",
 "Set every off-diagonal to zero and the metric to Minkowski limit; the equations must reduce to flat-space Newtonian/Lorentz results - index code is debugged in limits."),
],
"03-Relativity/03-The-Metric-Tensor": [
("What is the metric tensor?",
 "A symmetric rank-2 tensor g_mu,nu that assigns the interval ds^2 = g_mu,nu dx^mu dx^nu to neighbouring events and encodes the geometry of the spacetime."),
("What does the metric physically mean?",
 "It determines distances and time intervals locally; curvature is measured by how the metric varies, and gravity follows from that variation through the geodesic equation."),
("Write the Minkowski metric.",
 "ds^2 = -dt^2 + dx^2 + dy^2 + dz^2 (c=1), g = diag(-1, 1, 1, 1); the prototype of vacuum spacetime with no gravity."),
("What is the signature of a metric?",
 "The pattern of signs of its eigenvalues; relativity uses (-,+,+,+) or (+,-,-,-); the choice is a convention that flips every equation's sign, so document it."),
("What is the role of the metric inverse?",
 "g^mu,nu (defined by g^mu,rho g_rho,nu = delta^mu_nu) raises indices and appears in the Christoffel formula and the Hamiltonian as the contraction rule."),
("How many independent components does g have?",
 "10 in 4D (asymmetric reduces 16 to 10); symmetry is the reason metric evaluation code stores/reads exactly those 10 values."),
("What is a diagonal metric?",
 "One with g_ty = 0 etc.; Schwarzschild is diagonal, Kerr is NOT (it has a dt dphi term from frame dragging) - a distinction that structures both the geometry and the code."),
("What is the determinant of the metric used for?",
 "Its square root gives the volume element in integrations (-g)^(1/2) d^4x and the 3-volume measure - needed for mass-energy integrals and ray-accumulation weights."),
("How does the metric encode curvature?",
 "Its second derivatives feed the Riemann tensor (hence Ricci & Weyl); the scalar curvature R = g^mu,nu R_mu,nu appears in the action and in vacuum vanishes for Kerr."),
("What is the programmatic signature of the metric in a codebase?",
 "A function metric(r, theta; M, a) -> g(diag and coupling entries) and its inverse; both are evaluated billions of times, so they must be simple, register-cached expressions."),
("How do you convert a metric to Boyer-Lindquist explicitly?",
 "g_tt = -(1 - 2Mr/Sigma), g_phi,phi = (r^2+a^2+2Ma^2r sin^2/Sigma)*sin^2, g_t,phi = -2Mar sin^2/Sigma, g_rr = Sigma/Delta, g_tt,theta = Sigma; the Kerr end-members."),
("What is the line element language for finding null geodesics?",
 "Photons satisfy ds^2 = 0, so g_mu,nu x'^mu x'^nu = 0; that single constraint is the 'null' part of the Hamiltonian that all integrators enforce."),
("How does the metric act across frames?",
 "To find the locally non-rotating observer frame (ZAMO) you solve for the 4-velocity whose angular momentum vanishes; the metric's t-phi coupling defines that frame."),
("What is coordinate singular vs curvature singular?",
 "g may blow up at coordinates with no physical singularity (horizon in Schwarzschild t,r chart); true singularities (r=0, theta=0 cone) are intrinsic - the code must tell them apart."),
("What metric sanity checks do you run?",
 "At large r, g -> Minkowski; determinant negative definite; null condition numerically holds along integrated geodesics; symmetries respected: g_t,phi(t,theta) under sign flips."),
],
"03-Relativity/04-Geodesic-Equation": [
("Write the geodesic equation in index form.",
 "d^2x^mu/dlambda^2 + Gamma^mu_rho,sigma (dx^rho/dlambda)(dx^sigma/dlambda) = 0, with lambda affine; equivalently the covariant derivative of the tangent vector is zero."),
("What does the geodesic equation mean physically?",
 "It says the tangent to the path is parallel transported along the path - the straightest possible line in curved spacetime, which free particles and photons follow."),
("How is the geodesic equation derived?",
 "From the variational principle varying the path length (or the particle action) - the Euler-Lagrange equations of L = g x' x' yield exactly this second-order system."),
("What is the first-order (Hamiltonian) version of the same physics?",
 "The Hamiltonian H = (1/2) g^mu,nu p_mu p_nu gives Hamilton's equations dx^mu/dlambda = g^mu,nu p_nu and dp_mu/dlambda = -(1/2) dg^a,b/dx^mu p_a p_b - a system of 8 first-order ODEs."),
("Why prefer the first-order form in numerics?",
 "First-order form is directly RK4-integratable, avoids computing second derivatives, and p_mu is conserved for stationary metrics - the standard integrator formulation."),
("What are the constants of the geodesic motion?",
 "For stationary axisymmetric metrics (Kerr), E = -p_t and L = p_phi are conserved; Schwarzschild adds spherical symmetry, and Kerr adds the Carter constant Q."),
("What is the role of the affine parameter?",
 "It parametrizes the trajectory so the null condition holds at every point; the integrator's independent variable is lambda, not coordinate time."),
("How does the geodesic equation treat massive vs massless?",
 "Massive particles have |u|^2 = -1, photons |u|^2 = 0; both satisfy the same geodesic equation - only the initial sign of g_pp changes."),
("What is a geodesic in terms of the tangent vector?",
 "The requirement nabla_u u = 0: u^mu u^mu;nu = 0 - the path whose tangent vector is unchanged under its own parallel transport."),
("How do you derive velocity equations for a specific metric?",
 "From H: x'^mu = g^mu,nu p_nu; plug the inverse metric of the chart (e.g., Boyer-Lindquist) - the resulting r' and theta' equations are what you integrate."),
("What are the momentum components for the photon?",
 "p_t = -E, p_phi = L; p_r, p_theta solve from the null condition; the raytracer sets these from the initial direction at the camera."),
("What is the turning point?",
 "A point where r' = 0 (or theta' = 0) - extremum of a coordinate; the geodesic bounces there rather than unreasonably crossing, folded by the effective potential."),
("How do you convert from a direction to momenta?",
 "From the initial tangent, p_mu = g_mu,nu x'^nu; x'^nu from the direction vector times an overall scale chosen to satisfy the null condition."),
("What numerical failure occurs at the turning points?",
 "The naive r' equation may flip sign discontinuously; adaptive integrators must remain smooth across the turning point - a known weakness of fixed-step naive codes."),
("How do you validate geodesics?",
 "Integrate a circular orbit: r must remain constant within tolerance for thousands of orbits and E,L drift must stay at machine level."),
],
"03-Relativity/05-Christoffel-Symbols": [
("What are Christoffel symbols?",
 "The connection coefficients Gamma^mu_rho,sigma expressing how basis vectors change across the manifold; they appear in the geodesic equation and covariant derivative."),
("Write the formula for a coordinate-derived (Levi-Civita) connection.",
 "Gamma^mu_rho,sigma = (1/2) g^mu,tau (g_tau,rho,sigma + g_tau,sigma,rho - g_rho,sigma,tau); it is symmetric in the lower indices for a torsion-free metric connection."),
("Why compute Christoffels from the metric?",
 "The Levi-Civita connection is uniquely determined by the metric, so the whole geometry follows from g's first derivatives - a raytracer needs Gamma to integrate geodesics."),
("Which Christoffels are nonzero for Schwarzschild?",
 "Only r-related and a few diagonal terms survive in the (t,r): Gamma^r_tt = M(r-2M)/r^3-ish structure, Gamma^r_rr, Gamma^r_theta,theta, Gamma^r_phi,phi, Gamma^t_rt, the theta-chi block; the t-phi block vanishes."),
("Why does the gauge/coordinate choice matter so much?",
 "Gamma is not a tensor - its components change dramatically between charts (Boyer-Lindquist vs Kerr-Schild); the machine reads whatever chart you provide, so pick a smooth one."),
("When do you bypass the Christoffel cache?",
 "For a rapidly-varying r near the horizon, recompute Gamma on the fly; the cost of the 16-ish symbols is small and avoids stale cached values."),
("What does Gamma enter in the geodesic second-order equation?",
 "x''^mu = -Gamma^mu_rho,sigma x'^rho x'^sigma; that single term is the whole gravitational 'force' seen in coordinate terms."),
("How do you derive Gamma numerically instead of analytically?",
 "Finite-difference the metric and feed the formula; good for validation of hand-derived tables but wasteful at runtime - keep the analytic table for production."),
("What is the symmetry property you exploit in code?",
 "Gamma^mu_rho,sigma = Gamma^mu_sigma,rho, so you compute/store only the distinct pairs, halving the symbol table and arithmetic."),
("How does Gamma appear in parallel transport?",
 "For a vector V, transport satisfies V^mu;nu = dV^mu + Gamma^mu_rho,nu V^rho = 0 - the building block for Fermi-Walker and polarization transport."),
("What role does Gamma play in the ZAMO/observer frames?",
 "Frame-dragging ratios derive from components of the metric and its derivatives, so Gamma's r-phi pieces set the relative speed of a locally non-rotating observer's worldline."),
("What is the standard error in hand-derived Gamma tables?",
 "Symmetric failure: Gamma^r_theta,theta vs Gamma^r_phi,phi signs and the 1/r factors - verify each nonzero symbol against the known Kerr table at M=a=1."),
("How do you optimize Gamma evaluation?",
 "Cache the 10 distinct inverse-metric-like terms and the 6 metric field derivatives, then assemble Gamma in registers - no dynamic allocation, constant-time lookup."),
("What is a geodesic drift wrapped in Gamma language?",
 "A non-trivial curvature force appears only where Gamma components are nonzero; 'drift' of a wavefront is the integrated effect of those symbols."),
("What validation pins Gamma correctness?",
 "Photons on the equator with p_theta=0 must stay on the equator (theta'=0 implies theta stays); particle orbits precess at the known perihelion rate - both driven by Gamma."),
],
"03-Relativity/06-Schwarzschild-Metric": [
("Write the Schwarzschild metric.",
 "ds^2 = -(1 - 2M/r) dt^2 + (1 - 2M/r)^-1 dr^2 + r^2 (dtheta^2 + sin^2 theta dphi^2); the unique static spherically symmetric vacuum solution, with M the mass."),
("What is the significance of r = 2M?",
 "The Schwarzschild radius (event horizon in this exterior chart): the (1-2M/r) factor flips sign inside, so t and r swap causality roles - the boundary of the region escape is impossible."),
("What happens to the metric at r = 2M in these coordinates?",
 "g_rr -> infinity and g_tt -> 0: a coordinate singularity, removable in better charts (e.g., Eddington-Finkelstein, Kerr-Schild); the horizon is not a physical wall."),
("What is the actual singularity?",
 "r = 0, where curvature scalars diverge; any chart placing r=0 is a true physical endpoint - light arriving late must terminate there through the horizon."),
("Why is Schwarzschild the validation target?",
 "Its geodesics are integrable (sep of variables), so deflection, perihelion and photon-ring results have closed forms a raytracer must reproduce."),
("What is the photon sphere for Schwarzschild?",
 "Circular photon orbits exist only at r = 3M (photon sphere); light marginally grazing there spirals, producing the thin bright ring that dominates images."),
("What is the shadow radius measured by a distant observer?",
 "The critical impact parameter unscreened to the image: b_crit = 3*sqrt(3)*M ~ 5.196 M, giving the sharp boundary of the shadow."),
("What is the effective potential picture for radial photons?",
 "V(r) = (1-2M/r)*L^2/r^2; the maximum of the potential at r=3M sets the photon ring, and its height b^2 >= 27M^2 gates which photons escape."),
("How do Schwarzschild equations reduce from Kerr?",
 "Set a = 0: the t-phi coupling and the hideous r-sigma terms vanish; p_theta then derived trivially and Carter constant is hidden in the spherical symmetry."),
("What is the gravitational deflection of light to leading order?",
 "delta = 4M/b for a ray with impact parameter b and b >> M; the classic 1.75 arcsec solar test - the raytracer must reproduce it at small M/b."),
("How does the metric behave for M -> 0?",
 "g -> diag(-1,1,1,1) exactly; that flat limit is the built-in regression: every geodesic becomes a straight line when M is zeroed."),
("What is time dilation for a stationary observer?",
 "dtau = dt*(1-2M/r)^(1/2); at the horizon it drops to zero, giving the famous 'clocks stop' observation for distant viewers."),
("Why is the Schwarzschild chart bad for the integrator?",
 "The horizon's coordinate singularity appears as infinite metric components; mainstream production raytracers switch charts (Eddington-Finkelstein or Kerr-Schild) near/below r=2M."),
("What is the ISCO for Schwarzschild?",
 "The innermost stable circular orbit for massive particles at r = 6M; matter accretion ends there - disk inner radius sits at/ near ISCO in real flows."),
("What curvature scalars matter for diagnostics?",
 "The Kretschmann scalar R_abcd R^abcd = 48M^2/r^6 diverges at r=0 and is finite at r=2M - hard evidence the horizon is not singular."),
],
"03-Relativity/07-Schwarzschild-Orbits": [
("What are the possible geodesic types around Schwarzschild?",
 "Hyperbolic (escape), parabolic (unbound grazing), and elliptical (bound) trajectories; plus the photon sphere at r=3M separating captured from scattered photon orbits."),
("Write the radial equation for a photon in Schwarzschild.",
 "r'^2 = E^2/c^2 - L^2/r^2 (1 - 2M/r) with constants E, L; the effective potential V(r) = L^2/r^2 (1-2M/r) completely determines r-motion."),
("What is the effective potential for photons?",
 "V(r) = L^2/r^2 - 2M L^2/r^3; it rises to a maximum at r=3M (the photon ring) then falls - the barrier is the ring's existence and the shadow's cause."),
("What is the impact parameter?",
 "b = L/E = the ratio of angular momentum to energy; for photons it parametrizes the orbit family (distance/line-of-sight) and the image-plane coordinates."),
("What happens at b = b_crit?",
 "The photon asymptotically approaches the unstable circular orbit at r=3M; arbitrarily small perturbations determine capture vs scatter - the origin of the critically-wound images."),
("Describe a photon orbit with b slightly above b_crit.",
 "It winds around the photon sphere several times before escaping - the 'fractal' orbital shells seen behind the disk; these produce the multiply-lensed images."),
("Describe b slightly below b_crit.",
 "The photon crosses the maximum, plunges inside, crosses the horizon radius and is captured - seen as the shadow region in images."),
("What is the perihelion precession of bound orbits?",
 "Per orbit, the periapsis advances by delta_phi = 6*pi*M/a(1-e^2); Mercury's 43 arcsec/century is the historic test - a Schwarzschild validation metric."),
("How do bound orbits around a black hole differ from Newtonian ellipses?",
 "Closed ellipses become rotating rosettes (precession); the ISCO at 6M removes stable bound orbits below it - massive infall follows."),
("What is the 'unstable' nature of photon ring orbits?",
 "They are maximum-energy orbits (the V maximum); any perturbation sends them in or out - hence the ring is bright (long lingering) yet thin on the sky."),
("How does the code integrate equatorial Schwarzschild?",
 "With theta=pi/2 fixed: reduce to 2D (r, phi) + momentum, integrate x'=g^mu,nu p_nu and p_mu' = -1/2 dg/dx^mu ... - the cleanest intro geometry."),
("What ratio tests r motion?",
 "Compare r(lambda) against the analytic turning-point formula r_min = ... (b^2*...); each orbit's turning point matches closed-form roots of (r-b*v)^2 bounds."),
("What does the photon impact parameter map to the image?",
 "In the image plane, b maps to rho (distance from shadow center); the shadow boundary is at rho = 3*sqrt(3)M for a far Schwarzschild observer."),
("What is the escape-to-capture boundary in parameter space?",
 "b < 3 sqrt(3) M captures; b > 3 sqrt(3) M escapes; exactly at threshold lamp stays eternally on the ring - the beautiful razor edge."),
("How do you demonstrate the precession visually?",
 "Render 10 orbits of a star; the perihelion sill of each loop rotates by the same angle - a striking and quantitative validation of the integrator."),
],
"03-Relativity/08-Kerr-Metric": [
("Write the Kerr metric in Boyer-Lindquist form.",
 "ds^2 = -(1 - 2Mr/Sigma) dt^2 - (4Ma r sin^2 theta/Sigma) dt dphi + (Sigma/Delta) dr^2 + Sigma dtheta^2 + ((r^2+a^2)^2 - Delta a^2 sin^2 theta) sin^2 theta/Sigma dphi^2, with Sigma=r^2+a^2 cos^2 theta, Delta=r^2-2Mr+a^2."),
("What does the spin parameter a represent?",
 "a = J/M (specific angular momentum), in units M; ranges |a| <= M for a black hole; a=0 recovers Schwarzschild, a=M is the extreme/maximal Kerr limit."),
("What is frame dragging in Kerr?",
 "The dt dphi term means even 'static' observers must rotate; a locally non-rotating observer (ZAMO) moves with angular velocity omega = -g_t,phi/g_phi,phi."),
("What are the two horizons in Kerr?",
 "The outer event horizon r_+ = M + sqrt(M^2 - a^2) and the Cauchy horizon r_- = M - sqrt(M^2 - a^2); note g_tt crosses zero at the ergosphere, not r_+."),
("What is the ergosphere (ergoregion)?",
 "The region r_+ < r < r_erg(theta) where g_tt > 0 (the Killing time-like character fails); observers there MUST co-rotate - the source of rotational energy extraction (Penrose)."),
("Why is Boyer-Lindquist singular at Delta=0?",
 "The horizon radius r_+ is a coordinate singularity where Delta=0; production code integrates in Kerr-Schild (toroidal) coordinates for smoothness through the horizon."),
("How does the Carter constant arise in Kerr?",
 "The phi-pi separability of the geodesic equation yields a fourth constant Q beyond E, L - the separation constant; without it Kerr ray tracing needs full 4-D integration."),
("What is the kerr photon sphere structure?",
 "Prograde and retrograde circular photon orbits differ: r_ph = 2M(1 + cos(2/3 arccos(-+a/M))); the ring becomes asymmetric and the shadow gets a D-like shape for |a| high."),
("How does the metric reduce for the equator?",
 "On theta=pi/2, Sigma = r^2 and the dt dphi term flows directly; many core effects (ring, ISCO shift) come from the 2D equatorial slice."),
("What does the ISCO do with a?",
 "Prograde ISCO drops from 6M (a=0) toward M (a=M); retrograde rises toward 9M - the disk's inner edge shifts with spin, changing ring geometry."),
("What is the symmetry of the Kerr metric?",
 "Stationary (independent of t) and axisymmetric (independent of phi); both symmetries give conserved E and L along geodesics."),
("How does the equatorial photon ring shift with spin?",
 "The shadow boundary is no longer a circle: prograde side at smaller radius, retrograde at larger; the crescent asymmetry is one of the probe-able observables."),
("What is the Kerr-Schild transform for r?",
 "Coordinate change (Boyer-Lindquist -> Kerr-Schild) removes the Delta division while keeping equatorial form, letting numerical integration cross r_+ cleanly."),
("What validation pins the Kerr geometry?",
 "At a=0 all Kerr results reproduce Schwarzschild; energy/angular drift measurements stay at machine level; ZAMO angular velocity matches the analytic formula."),
("Why is Kerr essential, not optional, for the visualizer?",
 "Realistic disks rotate; without spin, the Doppler asymmetry, crescent shadow, and ISCO-flavoured ring are all wrong - the images from GRMHD demand a.)"),
],
"03-Relativity/09-Horizons-and-Ergosphere": [
("What is the event horizon?",
 "The null 2-surface from which nothing can escape to future null infinity; in Boyer-Lindquist it is r = r_+ = M + sqrt(M^2 - a^2)."),
("How does the horizon differ from the ergosphere?",
 "The horizon is the causal boundary (escape impossible); the ergosphere is the larger region (r+ to r_erg) where a timelike observer cannot stay 'static' but escape IS possible."),
("What is the ergosphere boundary?",
 "Where g_tt = 0, i.e., r_erg(theta) = M + sqrt(M^2 - a^2 cos^2 theta); it touches the horizon at the poles and extends to r=2M at the equator."),
("What is the Penrose process?",
 "A particle can enter the ergosphere, split, and one fragment carries negative energy into the horizon, extracting rotational energy from the hole - a real astrophysical engine."),
("How does time behave inside the ergosphere?",
 "A 'static' observer there would move on spacelike worldlines; the Killing vector becomes spacelike where g_tt > 0 - hence motion must co-rotate with the hole."),
("What is the ZAMO (locally non-rotating observer)?",
 "An observer with zero angular momentum about the symmetry axis, still forced to rotate by frame dragging with angular velocity omega = -g_t,phi/g_phi,phi."),
("Why do photons entering the horizon cross r+ in finite affine parameter?",
 "r+ is a coordinate singularity, not a physical one; in Kerr-Schild coordinates the photon crosses smoothly and terminates at r=0."),
("What is the shadow in horizon language?",
 "Photons whose impact parameter is too small cross the horizon and never return; the image-plane set of such b is precisely the shadow."),
("What is the photon-sphere-overlap with the ergosphere?",
 "The prograde photon orbit can lie INSIDE the ergosphere (for high a), so those photons corotate with the hole - a subtle source of image asymmetry."),
("How do you numerize the horizon condition?",
 "In the integrator, detect r < r+ (with a epsilon) and mark the photon as 'captured' - terminating the ray before it spirals into the singularity numerically."),
("How does the ergosphere appear in images?",
 "It is invisible per se; but photons skimming it are dragged and Doppler-shifted, adding brightness asymmetry the renderer must associate with spin."),
("What is the 'frozen star' misconception vs horizon?",
 "Locally nothing is 'frozen'; a distant observer sees redshift z -> infinity as light leaves the horizon region - global, not local, statement."),
("What is the area theorem and its code relation?",
 "The horizon area (nondecreasing, classically) bounds extractable energy; codes that track energy flow near r+ face this constraint physically."),
("How does the horizon terminate geodesic integration?",
 "Set a capture flag when r <= r+ (or the coordinate chart's capture radius), stop stepping, record 'radial infall' that contributed zero to the image (shadow)."),
("What test verifies horizon handling?",
 "Rays aimed exactly radial inward from far out must be flagged captured in finite steps, and the shadow boundary must match the analytic b_crit to machine precision."),
],
"03-Relativity/10-Frame-Dragging": [
("What is frame dragging?",
 "The rotational dragging of inertial frames by a spinning body, encoded in gravitational waves of the metric; in Kerr it appears as the t-phi coupling term."),
("How is frame dragging quantified?",
 "By the angular velocity of inertial frames: omega = -g_t,phi/g_phi,phi; the ZAMO's omega measures how fast local space 'spins' with the hole."),
("What does the ZAMO see?",
 "Constant-radius observers with zero angular momentum at infinity still revolve with angular velocity omega - the textbook signature of frame dragging."),
("How does frame dragging affect photons?",
 "Passing photons acquire a phi-component; prograde photons are dragged inward more, retrograde less - shifting the image's ring and shadow asymmetry."),
("How does dragging shape the image?",
 "The photon ring is distorted and the shadow becomes a crescent/D-shape with the bright side dragged; the asymmetry strength scales with |a| and inclination."),
("What is the dragging radial profile?",
 "omega drops as ~2Ma/r^3 at large r (the Lense-Thirring 1/r^3 law), approaching the hole's rotation rate near the horizon."),
("What is 'frame-dragging' observable in the solar system?",
 "Lense-Thirring precession of orbiting bodies (tested by Gravity Probe B ~ -2.0e-9 rad/orbit); it is the weak-field cousin of the Kerr effect."),
("How does drag relate to the orbital plane precession?",
 "The axis node of inclined orbits precesses around the hole's spin axis; strong near the horizon, weak at large r - a first test of the metric's phi-t coupling."),
("What does dragging do to the ISCO and disk inner edge?",
 "Dragging lowers the prograde ISCO; real disks therefore truncate closer for prograde - a geometric reason for the innermost emission ring asymmetry."),
("How does the code compute the ZAMO basis?",
 "zamo 4-velocity = (1/A, 0, 0, omega)/norm; the orthonormal basis for azimuthal emission uses that frame - where emissivity beaming is evaluated."),
("How do you verify frame dragging numerically?",
 "Place a photon with p_phi=0 far out at r=r0 and r'=0; it must immediately drift in phi with dphi = omega(r) dt - a direct metric-consistent check."),
("What is the weak-field vs strong-field boundary?",
 "For r >> M, a's Lense-Thirring term scales 1/r^3; the regime where dragging is a perturbation vs the dominant geometry is the strong-field hierarchy to keep in mind."),
("Does the ergosphere make dragging compulsory?",
 "Yes - inside the ergosphere the ZAMO's own speed needed exceeds a split of the light cone; no observer can resist the hole's rotation there."),
("How does drag interplay with beaming in images?",
 "The boosted emissivity follows the fluid's 4-velocity; near the hole fluid moves partly from dragging, so the beaming map � and the media visual asymmetry � encodes a.)"),
("What validation image isolates dragging?",
 "Render a static cold shell around a spinning hole with no fluid; the resulting photon paths must follow the analytic ZAMO streamlines - puristic dragging signature."),
],
"03-Relativity/11-Conserved-Constants": [
("What are the constants of null geodesic motion in Kerr?",
 "E = -p_t (energy), L = p_phi (axial angular momentum), and the Carter constant Q - the three conserved quantities along every null geodesic."),
("Why is E conserved?",
 "Stationarity: the metric is independent of t, so the Hamiltonian is cyclic in t and p_t is constant - the Noether charge of time-translation symmetry."),
("Why is L conserved?",
 "Axisymmetry: independence of phi gives a cyclic coordinate and constant p_phi - the Noether charge of rotation about the symmetry axis."),
("What is the Carter constant Q?",
 "The separation constant for the geodesic equation in Kerr, cleanly represented as Q = p_theta^2 + cos^2 theta (a^2 (E^2 - mu^2) + L^2/sin^2 theta) for the massless case; it tames the theta-motion."),
("How do the constants constrain motion?",
 "They leave a 2D phase space (radial + polar), so a photon's fate (capture/scatter/escape) is set by the triple (E, L, Q) - the power of the constant structure."),
("How does the null condition become the Hamiltonian?",
 "H = (1/2) g^mu,nu p_mu p_nu = 0 with (E,L,Q) fixing p_t, p_phi and bounding the p_r, p_theta via the effective potentials - the basis for reduced integration."),
("What is the 'effective potential' V_r(E,L,Q)?",
 "V_r = r^2 (E^2 - p_r^2) obtained by substituting into the null condition; the turning points where V_r = 0 bound the radial motion."),
("What is the radial turning-point analysis?",
 "For given (E,L,Q) solve V_r = 0 for r; roots give the closest approach; the photon sphere corresponds to degenerate (double) roots - the razor transition."),
("How do constants change the shadow shape?",
 "The critical (E,L,Q) yielding degenerate roots trace the shadow boundary in the image plane; scanning impact parameters b and observed angle gamma traces the silhouette."),
("How do you map image-plane coordinates to (b, gamma)?",
 "For a far observer looking along the axis, b = sqrt(L^2 + Q)/E (image radius) and gamma = arctan(Q/L^2) (position angle)- the polar map of impact parameters."),
("How do constants survive the numeric integrator as diagnostics?",
 "Track p_t, p_phi and Q along the path; their drift (with double precision, ~machine epsilon per step) is the strongest integrator correctness signal."),
("What is the advantage of the reduced/Hamilton-Jacobi formulation?",
 "Instead of 8 first-order ODEs you integrate 2 effective-potential ODEs in (r, theta) plus analytic formulas for t, phi - faster and numerically stable (used in ipole-like codes)."),
("What do the constants mean for a code's initial conditions?",
 "From the camera we choose direction/b; the constants are derived and then kept fixed; integrating conserves them exactly in exact arithmetic - drift is a bug detector."),
("How do the constants constrain capture?",
 "Capture occurs iff V_r has no allowed region beyond the outer turning point (or plunges to r < r+); scoring impact parameters with this test yields the shadow analytically."),
("What is the null energy scaling?",
 "E sets an overall scale on momenta; since geodesics are scale-invariant (multiply p by any factor), only RATIOS like b = L/E matter - image structure is b-only."),
],
"03-Relativity/12-Gravitational-Redshift": [
("What is gravitational redshift?",
 "Photons climbing out of a gravitational potential lose energy; a distant observer measures a lower frequency than near the emitter - z = (nu_emit/nu_obs) - 1 > 0."),
("What is the exact formula in Schwarzschild?",
 "nu_obs/nu_emit = sqrt(1 - 2M/r_emit) for a static emitter viewed at infinity; near the horizon this ratio -> 0, so light is infinitely redshifted."),
("What is the redshift factor in the raytracer?",
 "Along each ray the ratio g = nu_obs/nu_emit accumulates as 1 + z = (p . u_obs)_in / (p . u_emit)_in'; the code tracks it as an integrator state."),
("How is redshift applied to colors?",
 "Emitted frequencies are divided by (1+z); the spectrum (thus the color) is sampled at the shifted frequency - blue inner edge, red outer - a physical color source."),
("What is the combination of Doppler and gravitational shift?",
 "The total shift factor combines the gravitational part (from the g_00 weight at the emitter) and the Doppler part (from the emitter's motion p . u) - multiplicative."),
("Why does the disk near the hole look bluer in some images?",
 "Doppler boosting from approaching, mostly-ingoing gas overcomes the gravitational redshift, producing net blueshift on the approaching side - the classic beaming asymmetry."),
("What is the relation of redshift to the image they show?",
 "The photon ring's ring edges have large total z; mapping z per pixel (a diagnostic view) exposes exactly which motions dominate the look."),
("What is the eternal time-dilation/redshift link?",
 "A clock at rest near the hole runs slow by sqrt(g_00); light emitted there is also redshifted - the same metric factor (thanks to the geometry)."),
("How is the Lorentz doppler separated from spectral lines?",
 "For a moving emitter the mono/ratio = 1/(gamma(1 - beta cos theta)); gravitational adds the metric root - the two fold multiplicatively along the path."),
("How do you compute the redshift factor along an integrated ray?",
 "Accept as state variable the combination g = (p . u_cam) ...; the code updates it at the flexible sampling point and records g at hit."),
("What is the blueshift at the innermost stable orbit?",
 "For prograde Keplerian flow the orbital beta can exceed 0.4c, boosting the approaching side by a factor of several in intensity - the dominant visible asymmetry."),
("What does z=infinity mean numerically near the horizon?",
 "The factor diverges; the raytracer must clamp/saturate the 'shifted frequency' before it underflows colors - a classic source of black pixels on the ring."),
("What validation tests redshift?",
 "A static emitter at radius r0 with known z matches sqrt(1-2M/r0); a moving equatorial emitter matches the 4-D doppler formula - both to signal precision."),
("What is the integrated vs instant redshift?",
 "Radial rays experience integrated shift spread over the path; for optically thin emission all that matters is the end-to-end z - the code uses the end value."),
("How does the code expose redshift in debug views?",
 "Render z as false color: the shadow approaches z->1, the ring approaches z maxima just outside the horizon, and the approaching side dips to negative (blueshift)."),
],
"03-Relativity/13-Time-Dilation": [
("What is time dilation in relativity?",
 "Observer-dependent passage of time: a moving or gravitational-redshifted clock runs slow relative to a static distant one; dtau = sqrt(g_mu,nu dx^mu dx^nu) for timelike paths."),
("How is dtau computed?",
 "Along a worldline, proper time dtau = sqrt(-ds^2) = sqrt(-g_mu,nu dx^mu dx^nu) integrally; it's the clock-carried elapsed time along the path."),
("What is gravitational time dilation?",
 "Clocks deep in a potential run slow by sqrt(g_00) relative to a far observer; for Schwarzschild, dtau/dt = sqrt(1-2M/r) - zero at the horizon."),
("What is kinematic (special-relativistic) dilation?",
 "A moving clock runs slow by factor 1/gamma = sqrt(1-beta^2) relative to its rest frame - combined with gravitational part when both apply."),
("How does dilation appear inside the disk?",
 "Keplerian fluid orbits at high beta and deep potential have total dilation factors ~2-3; the code records emitter dtau/dt for the beaming and emissivity weighting."),
("Why do clocks 'freeze' at the horizon?",
 "dtau/dt -> 0 as r -> r+; the distant observer sees clock pulses spaced by infinity - practically the last rays emitted near r+ are redshifted to darkness."),
("What is the ISCO redshift of the innermost gas?",
 "Gas at ISCO r=6M has (1-2/r)^(1/2) ~ 0.816 gravitational plus orbital effects; the innermost image is dominated by boosting as well as this factor."),
("How does time dilation affect simulated movies?",
 "Frame cadence in proper time of orbiting gas differs from the observer's t; movie timelines should use coordinate time for plotting while per-ray physics uses proper steps."),
("What is the observer at infinity approximation?",
 "The detector records coordinate-time-separated events with dt = 0 in its rest frame; 'redshift from infinity' is the default camera state."),
("How do you validate time dilation?",
 "For a static emitter, per-step dtau matches sqrt(g_00) dt; integrate a full circular orbit and confirm total proper time equals analytic dtau."),
("What is the difference in visible 'speed' near the hole?",
 "Orbital angular speed (omega observed) is not proper time; the image's moving blobs are seen through shift+dilation - explaining flicker movies near the ISCO."),
("What does the erf/taylor expansion say near r=2M?",
 "sqrt(1-2M/r) ~ sqrt(r-2M) cuts off linearly; the temperature/redshift product peaks in a shell - a fragile balance that renders the innermost ring."),
("How does dilation interplay with adaptive step?",
 "Near r+ the coordinate time steps grow enormous; integrating in affine parameter/maintainable intervals avoids pathological dt; the proper-time diagnostic keeps it honest."),
("What is the historical test (GPS)?",
 "GPS clocks run fast due to weak field (gravitational) and slow due to motion; the meter-level correction confirms the formulas the code implements."),
("How do you explain time dilation in one sentence?",
 "Time is the metric's business: dtau is the length of a time-like path, and curvature+motion shorten it - the code simply integrates that length."),
],
"03-Relativity/14-Light-Bending": [
("What is light bending?",
 "A photon's path curves in the curved geometry even though it has no mass; the deflection angle for a ray grazing a mass M at impact parameter b is delta = 4M/b (weak field)."),
("What is the famous solar test?",
 "Eddington 1919 measured ~1.75 arcsec for a ray grazed at the Sun's limb - matching 4GM/(R c^2), the first confirmation of general relativity."),
("How does bending produce the Einstein ring?",
 "When source, lens, and observer align, the deflection folds light into an annulus on the sky - the ring geometry reproduced in micro-images and black-hole silhouettes."),
("What is the 'fold' scale for a black hole?",
 "Near the photon sphere, bending becomes arbitrarily large: many loops around the hole before escape - the multiply-lensed images of the disk."),
("How does the code compute deflection?",
 "It doesn't invoke a formula; integrating the null geodesics naturally produces every deflection, from 4M/b asymptotes to the wildly wound photon spheres."),
("What causes the shadow's circular boundary?",
 "Impact parameters with b slightly inside the photon sphere orbit produce uni-directional capture; the boundary at b_crit projects as the shadow edge."),
("What is lensing magnification?",
 "Deflection refocuses rays: the solid angle of an image differs from the source - brightness scales with the inverse magnification, factor becoming huge near the ring."),
("How does bending warp the disk appearance?",
 "The far side of the disk is visibly pulled above and below the hole (a secondary image arch) - the 'lensed wall' that makes black-hole images unmistakable."),
("What is the 'photon ring' in lensing terms?",
 "The photon sphere's relative lensing of the disk at high orders: each additional 2pi winding produces one more thin bright ring, logarithmically spaced."),
("What is the deflection vs impact parameter plot?",
 "delta (b) rises from 4M/b asymptote to infinity at b_crit - the canonical lensing curve that validation tests reproduce numerically."),
("How do you map sky to image for a far observer?",
 "Each pixel's direction gives (b, angle); the ray's deflection is implicitly computed by tracing - the image plane is a map of impact parameters."),
("What is the strong-field version of the formula?",
 "The exact deflection involves elliptic integrals that diverge at b=b_crit (the ring) with a -log(b - b_crit) behavior - the analytic anchor for integrator tests."),
("Why does the arriving ray from behind appear bent over the top?",
 "Rays from the far disk that pass just outside the photon sphere get lifted over the hole - the cue that produces the characteristic 'arch' of the secondary image."),
("What is an image of the Einstein ring demonstration?",
 "A bright point behind the hole becomes an Einstein ring radius r_E = sqrt(4M*D_source...) - the simplest 'lensed object' the raytracer can showcase."),
("How do you validate the bending?",
 "Trace a family of rays with b = 10..100 M and check delta matches 4M/b to 1% (weak field), and compare the shadow+ring against analytic ray-fixed (Bradbury) figures."),
],
"03-Relativity/15-Tidal-Forces": [
("What are tidal forces?",
 "The difference in gravitational acceleration across an extended body, caused by the variation of the field in space; gradients of curvature pull stretch/constrain shapes."),
("How are tidal forces described in general relativity?",
 "By the geodesic deviation equation: (D^2 xi^a/dtau^2) = -R^a_bcd u^b xi^c u^d, where xi is the separation vector between free-falling neighbors."),
("What is the magnitude near a black hole?",
 "For a Schwarzschild hole, tidal acceleration across a body of length L ~ (2M/r^3) L c^2; near the horizon it's huge - 'spaghettification' for real infallers."),
("What is spaghettification?",
 "Radial stretching plus lateral compression: the radial tidal gradient pulls apart, the tangential squeezes - the classic tidal limb for a person falling into small holes."),
("Why do tidal forces matter for a raytracer?",
 "Tidal fields bend null rays and spread caustics; the disk's tidal behavior sets the ISCO and the shape of the emission region (inner licensing)."),
("What is the ISCO in tidal language?",
 "Below some radius stable orbits collapse under tides; the ISCO marks the tidal-destabilization radius where geodesic deviation grows to tearing the orbit."),
("What is geodesic deviation?",
 "The equation of relative acceleration of two nearby geodesics, controlled by curvature tensor R and their separation/velocity - the rigorous description of tides."),
("How do tides distort images?",
 "Differential light bending across a projected source smears magnified arcs; in disk images the near/far ring asymmetries partly cocomiku tidal effects."),
("What is the 'tearing' of a star near a black hole?",
 "Tidal disruption events (TDEs): stars crossing inside a critical radius are torn and accreted, lighting up transient - astrophysics the code's disk may approximate."),
("What is the ringing/caustic structure?",
 "Nested caustics form where tidal refgeometry focus light; the series of rings near the photon sphere is a magnified tidal-focus phenomenon."),
("How do you compute tidal strain in code?",
 "Evaluate R^mu_(Boyd) Ricci on the ray's basis and integrate deviation; for validation only - the renderer itself rarely tracks ξ explicitly."),
("What is the relation of tidal to the strength of bending?",
 "Strong deflection (tiny b) equals strong tidal gradients; both scale with M/r^3 near the hole - the photon ring is a 3rd-order zoom of the same force."),
("What is the tidal radius formula?",
 "The Roche-like limit for a small body of density rho: r_t ~ (M/rho)^(1/3) times constants - where self-gravity loses the tidal tug."),
("How does the disk's inner edge relate to tides?",
 "The disk material at r < ISCO plunges; tides torque the gas so emission from the plunging region is a distinct, thin signature around the ISCO radius."),
("What validation tests code's protection against tide?",
 "Divergence-free evolution of nearby geodesics (integrate deviation analytically for circular orbits) - separation must match geodesic-deviation predictions."),
],
"03-Relativity/16-Units-and-Conventions": [
("What are natural/geometric units and why use them?",
 "c = G = 1 make mass dimensionally a length (M = l = t), removing factors from formulas; the code keeps them internally and only converts at I/O boundaries."),
("How do you restore SI-ish numbers for comparison?",
 "Multiply by powers of G and c: M_solar ~ 1.477 km, t ~ 4.93 us per km, etc.; all conversions stay in one unit-conversion module."),
("What is the relationship M in geometrical units?",
 "1 solar mass = 1.4776 km = 4.925e-6 s of geometric time; the code stores M and a in those units and renders r distances in M."),
("What is the 'M' scaling of the photon ring?",
 "All key radii are pure numbers times M: horizon 2M, photon sphere 3M, ISCO 6M - so a visually scaled render is literally just the same geometry in different M."),
("What is the convention for the photon energy/frequency?",
 "p_t = -E; the redshift factor sets nu_obs/nu_emit; frequencies in Hz only enter when mapping to real spectra at I/O."),
("What is the sign of the metric (the convention trap)?",
 "(-,+,+,+) vs (+,-,-,-) flips every spatial signature; pick one, document it, and never mix - the code asserts the signature at startup."),
("What are the two common coordinate charts?",
 "Boyer-Lindquist (analytic formulas, singular at Delta=0) and Kerr-Schild (numerically smooth through the horizon); conversions between them must be exact functions."),
("What is the isometric angular convention?",
 "theta measured from the axis (0..pi), phi in [0, 2pi); the singular points at theta=0 plus the polar cap need the azimuthal index avoided there."),
("How are angular velocities normalized?",
 "The boost beta uses c=1; physical omega = dphi/dt times a conversion if output in Hz/arcsec. The ZAMO omega is dimensionless in geometric units."),
("What does 'M=1 say about the Newtonian limit?",
 "Radii in units of M: large r means b >> M is the weak-field regime; the 4M/b deflection formula is the M-small placeholder."),
("Why do colors need physical frequencies?",
 "Spectrum integration needs nu in Hz; the code keeps a scale factor (frequency unit) multiplying the geometric-unit frequencies at the transfer stage."),
("What is the gravitational radius and its significance?",
 "r_g = GM/c^2 is the natural length of the hole; EHT discusses angular sizes via r_g/D - the observational twin of the internal M-unit."),
("What is the code's unit test set?",
 "At M in one unit, the horizon radius is 2M, the photon sphere 3M, ISCO 6M, shadow 3sqrt(3)M - these four numbers are unit-correctness gates."),
("What is the rule for printing/output?",
 "Always print with explicit unit labels (M, r_g, Hz, deg); every log and metadata field carries its unit so frames are auditable."),
("What single decision most prevents unit bugs?",
 "Freezing ALL math in geometric units with c=G=1 and converting only in three named I/O functions (unitsFromSI, unitsToSI, frequenciesFromHz) - no scattered conversions."),
]}