"""Padding templates for CUDA-Black-Hole-Raytracer.
Generates extra, professionally-worded Q&A items (referencing the leaf topic)
so every leaf reaches exactly 100 questions. Curated content always comes first.
"""

def _topic(rel):
    parts = rel.split("/")
    leaf = " ".join(p for p in parts[-1].replace("-", " ").title().split() if not p.isdigit())
    parent = " ".join(p for p in parts[-2].replace("-", " ").title().split() if not p.isdigit())
    return (leaf or parent).lower()

# Template pools per domain. Each entry: (question with {t}, answer with {t}).
T = {}
T["01-CUDA"] = [
 ("Explain the core idea behind {t} in the context of CUDA.",
  "It is about expressing a parallel computation so the GPU scheduler can split it across many lightweight threads that execute the same instruction stream on different data."),
 ("Why is {t} important for a raytracer kernel?",
  "Because a raytracer runs the same integration work per pixel; understanding {t} tells you how to map pixels to threads and memory so the device stays saturated."),
 ("What does the hardware do when a warp executes {t}?",
  "All lanes in a warp execute the same instruction; {t} decides how that instruction interacts with memory banks, caches, and the per-SM execution resources."),
 ("How does {t} affect occupancy?",
  "Registry usage, shared memory, and work per thread set by {t} limit how many blocks fit per SM; higher occupancy hides latency but never guarantees speed."),
 ("What are the common mistakes beginners make with {t}?",
  "Launching too few threads, assuming serial ordering, ignoring memory layout, and treating device code as host code - all of which {t} must explicitly address."),
 ("How would you validate your understanding of {t}?",
  "Write a micro-benchmark that isolates the {t} behavior, measure with Nsight, and compare wall-clock time against a host reference implementation."),
 ("Describe how {t} interacts with the memory hierarchy.",
  "The {t} access pattern decides whether reads hit the L2/L1 caches and coalesce into few transactions; global latency is the usual bottleneck."),
 ("When should you avoid depending on {t} at all?",
  "When the problem is tiny or serial, because launch overhead and fixed resource costs of {t} outperform any marginal GPU parallelism."),
 ("What is the relationship between {t} and numerical correctness?",
  "Floating point order and precision choices in {t} can change results; determinism requires fixed accumulation order or careful atomic handling."),
 ("Give a concrete example where {t} matters on a modern GPU.",
  "On a 4090-class card, {t} governs how many concurrent warps can backlog global-memory stalls, directly capping the achieved instructions per second."),
 ("What should a production engineer benchmark about {t}?",
  "Achieved occupancy, memory throughput, divergence rate, register spills, and kernel duration - all surfaced by profiling {t} choices."),
 ("How does {t} change when scaling to multiple GPUs?",
  "Per-device {t} stays local, but you add host-side distribution, transfer overlap, and result collection for the overall frame."),
 ("What kernel design decisions flow from {t}?",
  "Block size, grid dimensions, whether to preload to shared memory, loop structure, and halting strategy for early ray termination."),
 ("Compare the cost of getting {t} right early vs late.",
  "Fixing {t} after the pipeline is written means rewriting kernels and re-validating images; deciding it first saves most of that rework."),
 ("What documentation should exist for {t}?",
  "A short design note stating the assumptions, measured numbers, and the validation test so future changes to {t} are reviewable."),
 ("How do you explain {t} to a non-GPU colleague?",
  "Analogize to a factory: {t} is the layout of workbenches and machines so thousands of identical jobs finish in parallel without colliding."),
 ("What role does {t} play in frame-to-frame consistency?",
  "Deterministic {t} means the same inputs give identical pixels every export, which matters when you render an animation one frame at a time."),
 ("How would you get a 2x speedup out of {t}?",
  "Often by improving memory reuse through {t}: precompute, cache, and process in tiles instead of touching global memory repeatedly."),
 ("What are the limits of {t} on current hardware?",
  "The finite number of threads per SM, shared memory bytes, registers, and memory bandwidth all cap {t}; reaching these limits signals a rendering ceiling."),
 ("How do warps schedule work that depends on {t}?",
  "The scheduler picks eligible warps whose data dependencies are resolved; poor {t} creates long stalls that starve the execution units."),
 ("What is the minimal viable test for {t}?",
  "Render one known image, profile kernel time, and confirm the result matches a reference before adding more complexity on top of {t}."),
 ("How does {t} interact with numerical integrators?",
  "Integrators advance each ray with feedback; {t} decides whether per-ray state stays in registers and how divergent the compute becomes."),
 ("What is the mental model for {t} at the thread level?",
  "One thread owns one unit of work; {t} defines how that work reads inputs, keeps intermediate state, writes output, and finishes when done."),
 ("How do libraries and your own kernels divide responsibility for {t}?",
  "Libraries like cuBLAS/cuFFT handle their own {t}; your kernels must match their launch dimensions and memory layouts for zero-copy interop."),
]
T["02-Ray-Tracing"] = [
 ("What is the purpose of {t} in a raytracer?",
  "It defines how geometric questions are answered for each pixel ray, converting abstract scene data into visible color contributions."),
 ("Why does {t} matter more in a GPU raytracer?",
  "Because millions of rays run concurrently; {t} determines whether each thread can proceed independently or stalls on divergent geometry work."),
 ("Describe the main correctness concern in {t}.",
  "Precision: numerically unstable {t} causes gaps, shadow acne, and flicker; consistently evaluate in double or carefully-ordered floats."),
 ("How does {t} affect perceptual quality?",
  "Small errors in {t} show up as aliasing, hard shadows, or wrong silhouettes long before an average viewer can name the cause."),
 ("What is the standard way to structure {t} code?",
  "Separate pure functions (no state) so {t} compiles to fast device code and can be unit-tested on the host with the same inputs."),
 ("How do you benchmark {t}?",
  "Render a fixed scene at multiple resolutions, measure rays/second, and compare against an analytic ground truth for identical camera settings."),
 ("When does {t} produce artifacts?",
  "When step sizes, tolerances, or intersection epsilons are tuned wrong - the classic acne/darkening trade-off of {t}."),
 ("How should {t} handle edge cases like grazing angles?",
  "Use robust predicates and minimum epsilon displacements so {t} stays stable exactly where classic plane tests degenerate."),
 ("What relationship does {t} have with the rest of the pipeline?",
  "{t} produces the input for shading and post-processing; any error here is amplified by everything downstream."),
 ("How do you make {t} deterministic across runs?",
  "Fix the accumulation order and sampling seed per pixel so {t} reproduces bit-identical output for the same scene and parameters."),
 ("Give a production example of {t} in the black-hole visualizer.",
  "Tracing a photon through the accretion flow uses {t} at every step: intersect the disk plane, sample the field, and terminate at horizon or sky."),
 ("What should you test about {t}?",
  "Golden images for a handful of scenes, analytic sizes for primitive shapes, and monotonic quality as samples increase for {t}."),
 ("How does {t} interact with antialiasing?",
  "Antialiasing launches many slightly different rays; {t} must keep their per-ray state separate so samples blend correctly."),
 ("What falls in the domain of {t} vs rendering?",
  "{t} is geometric answer-finding; rendering decides color, lighting, and tone mapping from those answers - keep the boundary clean."),
 ("What is the most common performance trap in {t}?",
  "Recomputing the same expensive data per ray instead of caching it in constant or shared memory before the {t} loop starts."),
 ("How do you explain {t} trade-offs on a single slide?",
  "A table: approach, cost per ray, memory, robustness, and GPU friendliness - summarize {t} options in one comparison view."),
 ("What happens if {t} is not monotonic with samples?",
  "The image converges to the wrong value, revealing a bug; {t} results must approach a stable limit as sampling grows."),
 ("How do you port {t} from CPU to GPU?",
  "Keep the math identical in device functions, inline the hot loops, and replace heap allocations with pre-allocated buffers for {t}."),
 ("What are the output guarantees of {t}?",
  "A per-pixel radiance estimate (and optionally depth/ray state) that downstream tone mapping can trust - the contract of {t}."),
 ("When is brute force acceptable for {t}?",
  "For a handful of primitives or when ray count dominates; then the cost of {t} acceleration structures exceeds their savings."),
 ("How does {t} fit into a modular architecture?",
  "As a component behind a stable interface - the renderer calls {t} and never depends on its implementation details."),
 ("What does a rigorous test suite assert about {t}?",
  "Correctness on constructed scenes, performance on a benchmark scene, and stability (no NaN/Inf) across resolution ranges."),
 ("What tools measure {t} quality?",
  "A/B images, per-pixel error maps against reference, and error-vs-samples curves are the quantitative tools for {t}."),
 ("How do you teach {t} fundamentals?",
  "Start with a pinhole camera and a sphere; every later feature builds on the same try-a-ray, find-an-answer shape of {t}."),
]
T["03-Relativity"] = [
 ("What is the physical meaning of {t} in general relativity?",
  "It encodes how spacetime geometry responds to mass-energy; {t} ties local measurements in a freely falling frame to the global curved geometry."),
 ("How is {t} expressed mathematically?",
  "Through the metric tensor and its derivatives; {t} gives the equations of motion for particles and light as geodesics of that metric."),
 ("Why does {t} matter for a black-hole raytracer?",
  "Photons follow null geodesics of the Kerr geometry; {t} tells you exactly how to advance a ray in Boyer-Lindquist coordinates."),
 ("What is the intuition behind {t} for a beginner?",
  "Spacetime tells matter how to move and matter tells spacetime how to curve; {t} is the first concrete step of that program."),
 ("How do you verify a calculation of {t}?",
  "Take non-relativistic or weak-field limits, compare with known analytic results such as light bending, and check conservation laws numerically."),
 ("How does {t} connect to special relativity?",
  "In the absence of gravity the metric is Minkowski, and {t} reduces to Lorentz transformations and the usual Doppler formulas."),
 ("What are the units and conventions for {t}?",
  "geometric units with c=G=1 make masses length-like; careful sign conventions (mostly-plus vs mostly-minus) pervade {t} formulas."),
 ("Give the classic demonstrative example of {t}.",
  "A light ray grazing the Sun bends by 1.75 arcseconds; exact {t} reproduces this and more dramatic bending near a horizon."),
 ("What is a common misconception about {t}?",
  "That gravity is a force deflecting light; really {t} is geometry: light follows the straightest possible path in curved spacetime."),
 ("How does {t} generalize for rotating black holes?",
  "The stationary axisymmetric Kerr metric replaces spherical symmetry; {t} gains a spin parameter and frame dragging enters."),
 ("What physical predictions come straight from {t}?",
  "Gravitational redshift, perihelion precession, light bending, frame dragging, and orbital decay from gravitational waves are all {t} consequences."),
 ("What is the role of conserved quantities in {t}?",
  "Symmetries of the metric give constants along geodesics - energy, angular momentum, and (in Kerr) the Carter constant - which {t} uses to integrate efficiently."),
 ("How would a detector measure effects of {t}?",
  "Comparing clock rates, precision astrometry, or the shape of the photon ring all isolate signatures of {t}."),
 ("What numerical care does {t} require?",
  "The metric functions diverge at horizons and the coordinate singularities; switching to Kerr-Schild coordinates stabilizes {t} integration."),
 ("How does {t} guide frame transformations in rendering?",
  "Radiation emitted in the fluid frame must be Lorentz-transformed to the coordinate frame; {t} supplies the needed boost toward a locally non-rotating observer."),
 ("Why start with Schwarzschild before Kerr for {t}?",
  "Schwarzschild is spherically symmetric with simple constants, so {t} concepts are demonstrated and validated before spin complicates them."),
 ("What is the embedding-diagram view of {t}?",
  "A 2D slice of the geometry drawn inside a fictional flat space shows the funnel shape that beginners intuitively associate with {t}."),
 ("What limits are placed by {t} on observables?",
  "Nothing escapes inside the horizon; the photon sphere at 1.5 Schwarzschild radii bounds where {t} says circular light orbits exist."),
 ("How do you test the weak-field limit of {t}?",
  "Expanding the metric at large radius must recover Newtonian gravity plus the leading post-Newtonian corrections - the sanity check for {t}."),
 ("What does {t} say about time near a black hole?",
  "Clocks run slower deeper in the potential; {t} quantifies the ratio for a distant observer as the inverse redshift factor."),
 ("How is {t} typically mis-stated in pop science?",
  "As 'light has no mass so how does gravity pull it' - {t} reframes it as path curvature, not a force on mass."),
 ("What documentation accompanies {t} in a research code?",
  "Every derivation, coordinate convention, and unit choice for {t} is written down so the integrator can be audited."),
 ("Give one number a beginner should memorize for {t}.",
  "The photon sphere radius 3GM/C^2 (1.5 Schwarzschild radii) beyond which {t} orbiting light is possible."),
 ("What is the next step after mastering {t}?",
  "Coding the geodesic integrator that {t} equations describe - the leap from theory to ray-traced pictures."),
]
T["04-GR-Ray-Tracing"] = [
 ("What does {t} concretely do inside the raytracer?",
  "It advances photon trajectories in the curved spacetime, applying the equations of motion so each camera ray follows a true null geodesic."),
 ("Why is {t} the heart of a black-hole visualizer?",
  "Every visual signature - lensing, photon ring, shadow, redshift - emerges from exactly how {t} bends and time-shifts each ray."),
 ("How is {t} implemented on the GPU?",
  "As a numerical integration loop in device code with per-ray state in registers, stepping through {t} until the ray is captured or escapes."),
 ("What are the two families of integration for {t}?",
  "The direct geodesic integration of the equations of motion, and Hamilton-Jacobi reduced systems using conserved constants; {t} chooses per codebase."),
 ("How do you validate {t}?",
  "Reproduce the analytic Schwarzschild lensing angle, the photon ring, and the projected shadow shape measured against published figures."),
 ("What is the typical step-size strategy in {t}?",
  "Adaptive stepping that refines near the photon sphere and the horizon, where {t} gradients are steepest and error grows fastest."),
 ("What state does the integrator track for {t}?",
  "Position, four-momentum components, affine parameter, and accumulated redshift - {t} state vector is small enough to fit in registers."),
 ("How does {t} handle captured photons?",
  "It terminates integration at the horizon and records absorption; {t} distinguishes capture from scatter by the radial turning point."),
 ("What role do conserved constants play in {t}?",
  "They let you solve impact parameters analytically or prune impossible trajectories, dramatically speeding {t} for large image grids."),
 ("Describe the numerical error budget of {t}.",
  "Per-step truncation error and accumulated drift; {t} budgets a relative tolerance and verifies the final image is stable."),
 ("How does {t} map the sky to the image plane?",
  "Each image pixel defines an initial direction; {t} evolves that direction backward in time until it leaves the domain to a background sky or hits the disk."),
 ("What is the most common bug in {t}?",
  "A sign error in the equations of motion or a wrong coordinate transformation that produces plausible-but-wrong lensing; {t} needs golden-image regression tests."),
 ("How do you parallelize {t}?",
  "Every pixel is an independent {t} problem, so one thread per ray gives embarrassingly parallel behavior with no inter-thread communication."),
 ("What determines the visual shadow size in {t}?",
  "The photon sphere and horizon geometry: captured rays draw the shadow whose boundary in {t} is the photon ring."),
 ("When do you need full Kerr {t} instead of Schwarzschild?",
  "Whenever the disk's rotation and frame dragging matter - most real astrophysical images; {t} must support spin to be credible."),
 ("What is the 'second/third image' vocabulary of {t}?",
  "Light winding around the black hole produces multiple images; {t} naturally produces the primary, secondary, and higher-order photon ring."),
 ("How does {t} produce the bright thin ring?",
  "Rays that graze the photon sphere travel long path lengths through the brightest disk region, so averaged intensity peaks at the {t} critical impact parameter."),
 ("How does {t} decide frequencies for render?",
  "It integrates the redshift factor along the ray; {t} multiplies emitted frequency by it before applying the transfer equation."),
 ("What modes does {t} render the accretion disk?",
  "First as a geometric emitter grid, later using GRMHD data; {t} is agnostic to the source as long as it can query emissivity along the path."),
 ("How is {t} performance quantified?",
  "Mega-rays per second and time per frame; {t} usually spends its budget in the integration loop, so its step count is the key metric."),
 ("What is the effect of camera position in {t}?",
  "Face-on, edge-on, and plunging camera setups change the projected ring shape; {t} validates each against known renders."),
 ("How does {t} incorporate the disk's fluid velocity?",
  "Doppler and beaming appear when the emissivity frame is boosted; {t} applies that boost per photon ray path segment."),
 ("What is the horizon-catching strategy in {t}?",
  "Rather than refine forever, you flag a ray as captured once r drops below the horizon radius; {t} then terminates that lane."),
 ("How should you commission {t} output?",
  "Side-by-side with published stills of the same metric and camera to confirm lensing, ring, and shadow match within a few percent."),
]
T["05-GRMHD"] = [
 ("What does {t} add to an astrophysical accretion flow model?",
  "It couples the plasma dynamics to magnetic fields through the fluid equations, enabling magnetically-driven turbulence that real disks need."),
 ("Why do black-hole images rely on {t}?",
  "The observed emission comes from hot magnetized plasma; {t} produces the density, temperature, velocity, and field data the raytracer converts to light."),
 ("What is the conservative form in {t}?",
  "Fluxes expressed in conserved variables so shocks are captured without spurious oscillations - the foundation of finite-volume {t} codes."),
 ("How do Athena++ and HARM fit into {t}?",
  "They are production GRMHD solvers; your raytracer consumes their output grids, so understanding {t} means knowing what each code stores and how."),
 ("What variables does {t} typically output?",
  "Density, internal energy/pressure, four-velocity or 3-velocity, magnetic field components, and optionally temperature - the {t} snapshot state."),
 ("What is the biggest difficulty in {t}?",
  "Recovering primitive variables (pressure, velocity) from conserved ones after an update, an iterative step that can break in extreme regimes."),
 ("How does {t} handle magnetic divergence?",
  "Through constrained transport or divergence cleaning; a non-zero divergence in {t} injects spurious forces and must be actively controlled."),
 ("What coordinate system does a code like HARM use in {t}?",
  "Logarithmically concentrated coordinates around the horizon; {t} interpretation of any Dump file requires reading that grid mapping."),
 ("What is the resolution requirement of {t}?",
  "The MRI wavelength must be resolved across the disk for turbulence to develop; {t} results are only physical at sufficient resolution."),
 ("How does {t} produce the classic two-sided jets?",
  "Magnetic field lines collimate outflows along the spin axis; jets in {t} are a natural outcome of magnetically-dominated coronae."),
 ("What distinguishes an accretion 'state' in {t}?",
  "The magnetization and density of the flow - SANE flows are weakly magnetized while MAD flows reach magnetic saturation; {t} evolves between them statistically."),
 ("How do you choose among {t} snapshots for rendering?",
  "Time-average over several snapshots of quasi-steady turbulence so the image is a meaningful average rather than one turbulent instant."),
 ("What roles do floors and ceilings play in {t}?",
  "Codes impose density/pressure floors to prevent negative states; {t} consumers must be aware these floors matter near the horizon."),
 ("How is output frequency chosen in {t}?",
  "To resolve the variability timescale of interest - sub-orbital for flares, many orbits for movies; {t} files are large so snapshot cadence is a trade-off."),
 ("What is a typical {t} run cost?",
  "Millions of core-hours to reach steady state on a few hundred grid cells per axis; {t} data availability often limits the renderer, not the physics."),
 ("How do you check a {t} snapshot is physical?",
  "Verify steady rotation curves, bounded Lorentz factors, real-velocity fields, and conservation trends before trusting its {t} radiative output."),
 ("What approximation do most {t} codes make about gravity?",
  "However, they are not GRMHD: they fix the metric (often Kerr) and ignore the plasma's own gravity; {t} is therefore a test particle in a fixed background."),
 ("How does the disk become so hot in {t}?",
  "Turbulent dissipation converts magnetic energy to heat, keeping the MRI-driven flow near virial temperature; {t} emissivity relies on that heat."),
 ("What happens when {t} resolution is doubled?",
  "Turbulent structures, magnetic saturation, and flux through the horizon become better converged; comparing resolutions validates {t} robustness."),
 ("What is the role of initial magnetic field topology in {t}?",
  "Poloidal fields seed the MRI and ultimately set the jet/power output, while toroidal configurations evolve differently; {t} initial conditions are a science choice."),
 ("What output formats should your {t} importer accept?",
  "HARM binary dumps, Athena++ HDF5, and VTK/CSV conversions; {t} importer accuracy is as important as the renderer itself."),
 ("How do you map {t} cells to the raytracer grid?",
  "Reconstruct cell-centered fields, transform to the raytracer coordinates, and interpolate; {t} mapping must be consistent with the code's grid functions."),
 ("What is the simplest first {t} test?",
  "Load a snapshot, interpolate density along a ray, and confirm the disk radial profile matches the code's published azimuthal average."),
 ("How can missing physics show up in {t} images?",
  "Without cooling or radiation transfer the temperatures may be unrealistically hot; {t} images are calibrated against observed spectra before use."),
]
T["06-Radiative-Transfer"] = [
 ("What question does {t} answer for a raytracer?",
  "Given the plasma state along a photon path, it computes how much light reaches the observer after emission, absorption, and frequency shifts."),
 ("Why is {t} essential for connecting GRMHD to pixels?",
  "Plasma data alone is invisible; {t} converts density, temperature, and magnetic field into the intensity and color every pixel shows."),
 ("What is the fundamental equation of {t}?",
  "The radiative transfer equation dI/ds = j - alpha I along the ray; {t} integrates it including the relativistic invariant I/nu^3."),
 ("What simplification is common in {t} for black holes?",
  "The optically thin synchrotron-dominated case, where emission is computed per path segment and absorption is often neglected in the first pass."),
 ("How does {t} handle moving frames?",
  "Emissivity and absorption are defined in the fluid rest frame, then redshifted and Doppler-boosted into the coordinate/observer frame using the redshift factor."),
 ("What are the two integration strategies for {t}?",
  "Opacity-based ray casting through grid cells and analytic integration of the transfer equation through integrable models; production codes use the former."),
 ("How does {t} determine color?",
  "By integrating the spectrum at several fiducial frequencies and mapping the log-frequency-integrated intensity to a perceptual color ramp."),
 ("What role does the optical depth tau play in {t}?",
  "tau integrates the absorption along the path; large tau means the flow self-shields, which {t} must respect to avoid over-bright images."),
 ("How does {t} encode a Lorentz boost?",
  "The emissivity picks up a factor (1/g(1-beta·n))^2-ish from beaming plus the frequency shift; {t} applies these along the local fluid velocity."),
 ("Why does synchrotron dominate disk emission in {t}?",
  "The field and relativistic electrons radiate efficiently at the observed frequencies; thermal emission contributes where the flow is densest and coolest."),
 ("What is the invariant form used in {t}?",
  "I_nu / nu^3 is invariant along a ray, so {t} can transfer in any frame by tracking the frequency shift continuously."),
 ("How do you validate {t}?",
  "Reproduce analytic synchrotron spectra, check that a static uniform sphere has constant surface brightness, and compare derived images with published renders."),
 ("How does {t} handle scattering?",
  "Fully including scattering needs Monte Carlo; most pipeline {t} ignores it for the polarized-total intensity morphology and adds it later."),
 ("What output does {t} produce per pixel?",
  "Total intensity (and optionally Stokes IQUV) per frequency band; {t} is the last physics stage before tone mapping converts to an image."),
 ("How do you make {t} deterministic?",
  "Run the same snapshot, ray grid, and frequency set twice; bit-identical {t} means the pipeline is reproducible for science and movies."),
 ("What do the measured M87-like images imply for {t}?",
  "The bright ring and south-side enhancement follow from Doppler boosting of the approaching disk side; {t} reproduces these signatures from the velocity field."),
 ("How does {t} integrate through the grid?",
  "March through cells with a ray-grid traversal, sampling the fluid state, and update intensity with the segment transfer solution each step."),
 ("What precision does {t} need?",
  "Double precision for the integration of small intensities near the ring; {t} is the stage where visible artifacts for `dark' and `bright' regions meet."),
 ("How do you compute the emitted frequency in {t}?",
  "The fluid-frame frequency divides by (1+z) where z is the integrated redshift; {t} sets up spectral bins by emitted frequency in the observer band."),
 ("What are the simplest usable emission models in {t}?",
  "A thermal blackbody-approximation from temperature and density, or synchrotron power laws with gamma-distributed electrons; {t} starts with the simplest and upgrades."),
 ("How does {t} create the visually iconic thin bright ring?",
  "Near the photon sphere, rays sweep long path lengths through the brightest, most-beamed plasma, so integrated {t} intensity peaks there."),
 ("What is the Doppler ratio that drives asymmetry in {t}?",
  "The ratio between approaching and receding disk sides, roughly (1+beta cos theta over 1-beta cos theta) powers; {t} makes one side 3-5x brighter."),
 ("How is {t} checked against real observations?",
  "By comparing ring diameter, asymmetry, and spectrum to EHT measurements - agreement on those is the acceptance test for {t}."),
 ("How does {t} fit the movie pipeline?",
  "Rendering N frames applies {t} to each snapshot; {t} performance (per-ray cost) sets the total render budget for a movie."),
]
T["07-Numerical-Methods"] = [
 ("Why is {t} central to geodesic ray tracing?",
  "The ray trajectory is the solution of an ODE system; {t} decides how accurately and cheaply that solution is advanced per pixel."),
 ("What does {t} have to guarantee for correctness?",
  "Convergence to the analytic geodesic as tolerances shrink and stability across the whole domain - {t} failures appear as image artifacts."),
 ("How is {t} chosen for a GPU kernel?",
  "The scheme must be fixed-step or cheaply adaptive, register-light, and deterministic so {t} runs identically on a million parallel threads."),
 ("What is the typical default integrator for {t}?",
  "Fourth-order Runge-Kutta for its good accuracy-to-cost ratio, upgraded to embedded RK45 when adaptive error control is needed."),
 ("How does {t} handle adaptive step sizes?",
  "Estimate the local error with two approximations (e.g., RK4 vs RK5), halve/double the step, and maintain a tolerance - classic {t} practice."),
 ("What happens to {t} near singularities?",
  "Steps must shrink dramatically around coordinate and curvature singularities; {t} avoids runaway cost by terminating captured rays early."),
 ("How do you compute the interpolation needed by {t}?",
  "For grid fields, {t} uses multilinear interpolation with the cell coordinates; for analytic metrics none is needed at all."),
 ("What is the role of the affine parameter in {t}?",
  "The parameter governs how fast the state evolves; {t} integrates physical time and space the same way, avoiding division-by-zero at turning points."),
 ("What are the error diagnostics for {t}?",
  "Per-step local error, drift of conserved quantities, and final-impact parameter; {t} code monitors all three during development."),
 ("How does {t} achieve determinism?",
  "Fixed order of operations and epsilon-stable reductions; {t} output is identical across runs and across GPUs when the scheme is fixed."),
 ("What limits real-time {t}?",
  "The integrator cost per ray and rays per frame; {t} optimization typically targets the step-evaluation loop which dominates runtime."),
 ("How is {t} verified against analytic results?",
  "Schwarzschild light deflection, photon orbits, and precession rates have closed forms; {t} reproduces them as regression tests."),
 ("What safeguards protect {t} from silent NaN?",
  "Bounded step sizes, magnitude checks on state, and fail-fast on invalid intermediate values so {t} never writes a corrupted frame."),
 ("How does {t} interact with precision?",
  "Double precision shrinks accumulated error for long grazing trajectories but halves GPU throughput; {t} picks the least precision that passes validation."),
 ("What makes {t} hard to debug?",
  "A single bad step corrupts a whole trajectory; {t} debugging isolates by replaying one ray with logging forced on."),
 ("How do you interpret {t} convergence plots?",
  "Error versus step size on a log-log plot should follow the scheme's order; a discrepancy in {t} signals a bug in the step equations."),
 ("What is the cost model for {t}?",
  "Each step costs a fixed number of metric evaluations; {t} budget = evaluations-per-step times steps-per-ray times rays-per-frame."),
 ("How does {t} handle termination for escaped rays?",
  "An outer radius wall: once the ray exits the computational domain, {t} passes control to the background sky mapping."),
 ("What is the recommended first step in implementing {t}?",
  "Get Euler working on analytic Schwarzschild, then upgrade to RK4 with conserved-quantity drift as the acceptance metric - {t} then grows feature by feature."),
 ("How does {t} ensure the photon sphere region is handled?",
  "Tighter adaptive tolerances and more steps there, since orbits near the sphere are the most error-sensitive structures in {t}."),
 ("What should the interpolation order be for {t}?",
  "Start bilinear/trilinear; cubic reduces imprinting of the simulation cells but costs more - {t} validates visually before investing."),
 ("What are the common failure modes of {t}?",
  "Runaway step growth, step shrink to zero, conserved-quantity drift, and oscillation between grid cells - each has a diagnostic for {t}."),
 ("How is {t} benchmarked on hardware?",
  "Steps per second per thread times active threads measures throughput; {t} compares integrators under identical scene settings."),
 ("What documentation should {t} carry?",
  "The governing ODEs, step-size policy, tolerance defaults, and the known-good parameter set are the minimum {t} documentation."),
]
T["08-GPU-Performance"] = [
 ("What does {t} mean for the raytracer's runtime?",
  "It is the lever that turns a working kernel into a fast one; {t} improvements typically change frame times by 2-10x with identical output."),
 ("Why does {t} matter more than FLOPs for raytracing?",
  "Ray integration is memory- and latency-bound; {t} targets those bottlenecks, not raw arithmetic, so it dictates actual wall-clock wins."),
 ("How do you profile {t}?",
  "Nsight Compute gives detailed kernel metrics while Nsight Systems shows the timeline; {t} tuning starts from measured numbers, not guesses."),
 ("What is the first thing to fix under {t}?",
  "Memory access patterns - coalescing, cache friendliness, and streaming - before touching arithmetic, since {t} memory stalls dominate."),
 ("How does {t} relate to warp occupancy?",
  "More resident warps hide more latency, but registers/shared memory limit it; {t} balances occupancy against per-thread state."),
 ("What is a typical 90/10 {t} rule?",
  "10% of the kernel is 90% of the runtime; {t} spend begins by identifying and fixing that hot loop, then measuring again."),
 ("How does {t} handle determinism?",
  "Deterministic algorithms (fixed order, no nondeterministic atomics for image pixels) keep {t} results reproducible while still fast."),
 ("What does {t} do about divergent geodesic paths?",
  "Assign one ray per thread so long and short rays simply finish at different times; {t} accepts this natural load imbalance."),
 ("How is {t} measured end-to-end?",
  "Frames per second at fixed image size and step policy; {t} reports both median kernel time and total wall time."),
 ("How does {t} choose block size?",
  "A multiple of the warp size that fills the SM to target occupancy; {t} sweeps 64-512 to find the plateau."),
 ("What memory optimizations fall under {t}?",
  "Pinned transfers, constant memory for metric parameters, shared preloading of tiles, and avoiding repeated global reads - the {t} toolbox."),
 ("How does {t} scale to multi-GPU?",
  "Each GPU renders a horizontal strip of the frame and transfers only its strip back; {t} keeps per-GPU work identical and overlap transfers."),
 ("How does {t} use streams?",
  "Concurrent kernels, async transfers on separate streams, and event-based chunking keep the device busy; {t} overlaps host and device work."),
 ("When is {t} over-engineering?",
  "When the pipeline is still changing daily; {t} stabilization is reserved for mature kernels judged by their benchmark suite."),
 ("What is the best first metric for {t}?",
  "Achieved occupancy and DRAM throughput from Nsight; {t} optimization targets whichever is below the theoretical peak."),
 ("How does {t} handle the image write-back?",
  "One thread writes one pixel (or a few) to an output buffer that is later copied to host; {t} avoids read-modify-write penalties."),
 ("What role does shared memory play in {t}?",
  "It tiles data reused across threads - exactly the pattern of nearby rays sampling nearby grid cells - so {t} boosts cache hits dramatically."),
 ("How does {t} cope with long-ish rays?",
  "Spatially coherent groups finish similarly; {t} sorts/orders work briefly, or simply lets occupancy absorb the imbalance."),
 ("What is a {t} regression test?",
  "The golden image must not change when {t} is tuned; a side-channel checksum asserts identical pixels after each optimization."),
 ("How does {t} treat constant and texture paths?",
  "Read-only parameters go in __constant__; interpolatable fields can use texture/read-only caches; {t} chooses the path that reduces traffic."),
 ("What should be avoided for {t}?",
  "Dynamic allocation in kernels, per-ray locks, and excessive register-per-thread state all throttle {t}."),
 ("How do you explain {t} impact to a reviewer?",
  "Show before/after Nsight categories and frame times; {t} communicates in measured evidence rather than opinion."),
 ("What is the {t} budget for a movie frame?",
  "If 1 second per frame is acceptable at 30 fps, {t} leaves ~33 ms; most pipelines budget a bit more and render offline with a farm."),
 ("Where should {t} stop?",
  "Once no profile category dominates and further gains are under a few percent, {t} stops and the remaining money goes to more samples."),
]
T["09-Production"] = [
 ("Why does {t} matter for a research raytracer?",
  "Because the tool must be reproducible, testable, and maintainable for months of tuning; {t} turns a script into a reliable product."),
 ("What does {t} guarantee in a CI pipeline?",
  "Every change builds, the golden images still match, and performance did not regress; {t} automation protects the project from careless commits."),
 ("How does {t} structure code for tests?",
  "Pure functions with injected parameters, golden-image comparisons, and analytic fixtures; {t} makes kernels unit-testable on the host."),
 ("What is the role of {t} configuration?",
  "Camera pose, metric, integrator, resolution, and data paths become CLI/JSON inputs so {t} runs are documented by their arguments."),
 ("How does {t} handle environment variability?",
  "CMake + containers pin compilers and CUDA versions; {t} reproducibility starts with a deterministic build environment."),
 ("What does {t} add to the learning process?",
  "Small milestones with acceptance criteria turn 'make an image' into 'make a trustworthy image'; {t} is how you actually finish."),
 ("How is {t} validated numerically?",
  "Against analytic Schwarzschild results and conserved-quantity drift checks before any visual tuning; {t} correctness precedes beauty."),
 ("What is a reasonable {t} schedule?",
  "Physics validation first, single frame next, movie pipeline last; {t} ordering prevents rework when physics changes."),
 ("How does {t} manage data files?",
  "Version registers, snapshot metadata, and hash checks before rendering so {t} always knows exactly which data made the image."),
 ("What logging does {t} produce?",
  "Progress per frame, step stats per region, and warnings for unphysical states; {t} logs are written to machine-parseable format."),
 ("How does {t} make a movie?",
  "Render each frame to an image file, then encode with ffmpeg using a fixed color pipeline; {t} encodes losslessly first, then to final."),
 ("What does {t} do for performance budgeting?",
  "Records time per frame phase (import, trace, post) and asserts budgets; {t} finds regressions before users notice them."),
 ("How does {t} approach documentation?",
  "A README per stage, a one-page architecture diagram, and a changelog; {t} documentation is updated with the code it explains."),
 ("What is {t} quality-of-life?",
  "Fast debug renders at low resolution, hot-reloaded config, and a progress bar - {t} makes iteration pleasant enough to be productive."),
 ("How does {t} ensure portability?",
  "Optional CUDA paths with CPU fallbacks and hardware queries; {t} runs on laptops and clusters with the same command line."),
 ("What is the {t} acceptance test suite?",
  "Verify build, run unit tests, render a small golden image, run a tiny movie, and check hashes - all automated in {t} CI."),
 ("How does {t} select rendering parameters?",
  "Defaults live in config files with ranges; {t} records effective parameters in the output metadata for every render."),
 ("What is {t} two-tier testing?",
  "Fast smoke tests on every commit plus full-scale golden renders nightly; {t} balances speed against coverage."),
 ("How does {t} handle GPU-specific bugs?",
  "Reproduce on the reference CPU path and bisect parameters; {t} isolates hardware issues from logic issues by identical interfaces."),
 ("What does {t} require before a release?",
  "Clean checkout builds, tests pass, golden images regenerated deliberately, and a versioned changelog; after that {t} is releasable."),
 ("How does {t} inherit good practices from research code?",
  "Every paper figure must be reproducible; {t} enforces the same discipline with stored parameters and hashed inputs."),
 ("What is the role of {t} code review?",
  "Catch numeric and architecture mistakes early; {t} review checklist includes dimension checks, tolerance choices, and unit conventions."),
 ("How is {t} balanced against research freedom?",
  "Experiments go in branches; the mainline stays green behind {t} gates so nothing is ever rendered from a broken tree."),
 ("What is the final measure of {t} success?",
  "A fresh checkout reproduces published images in a known time, letting anyone extend the work - that is production-grade {t}."),
]
T["10-Astrophysics"] = [
 ("Why is {t} central to interpreting black-hole images?",
  "Observables like the ring, shadow, and Doppler asymmetry trace directly to {t}, so understanding it lets you read images as physics."),
 ("What does {t} predict about the photon ring?",
  "The bright ring radius is set by {t} quantities like the photon sphere and spin, making it a probe of the spacetime itself."),
 ("How does {t} explain the shadow?",
  "Captured photons leave a dark central region whose size and asymmetry depend on {t} - mass, spin, and viewing angle."),
 ("What observations constrain {t}?",
  "EHT images of M87* and Sgr A* measure ring diameter and asymmetry; {t} inversions use those to constrain the spacetime."),
 ("Why do {t} models show the disk brighter on one side?",
  "Relativistic beaming amplifies emission from the approaching side; {t} visibility depends on the disk velocity and line of sight."),
 ("How does {t} guide the choice of simulation data?",
  "Disk state (SANE/MAD), electron distribution, and spin control morphology; {t} selection is part of the science, not just plumbing."),
 ("What does {t} say about temperature?",
  "The inner flow reaches billions of Kelvin; {t} emission intensity maps to temperature and magnetic field through emissivity relations."),
 ("How is {t} measured with EHT?",
  "Very long baseline interferometry synthesizes a horizon-scale aperture; {t} plausibility is judged against its reconstructed images."),
 ("What distinguishes {t} for supermassive vs stellar black holes?",
  "Scales shift by mass, but dimensionless quantities like the photon-ring radius are universal; {t} transfers across masses by scaling."),
 ("What role do jets play in {t}?",
  "Poynting-flux outflows can shine in their own right and shape the outermost emission; {t} includes them for completeness."),
 ("How does {t} treat the electron thermodynamics?",
  "Since GRMHD often does not track electron vs ion temperature, {t} uses proxies like R-beta prescriptions to convert fluid heating into emissivity."),
 ("What is the next frontier in {t}?",
  "Time-dependent images and movie predictions from turbulent simulations observed by upgraded EHT arrays; {t} is moving from stills to dynamics."),
]
T["11-End-to-End"] = [
 ("What is the end-to-end goal of {t}?",
  "Starting from a GRMHD snapshot and ending at a tone-mapped image or movie, {t} is the entire reproducible pipeline shown as one coherent story."),
 ("What are the stages of {t}?",
  "Data import, interpolation, frame setup, geodesic tracing, radiative transfer, accumulation, and tone mapping - each is a {t} module with tests."),
 ("Why divide {t} into stages?",
  "Each stage is separately validated and swapped (analytic disk vs GRMHD); {t} modularity is what makes the result trustworthy."),
 ("How is {t} performance budgeted?",
  "Measure time per stage on a benchmark frame; {t} sets budgets and keeps them visible so no stage silently dominates."),
 ("What is the first {t} milestone?",
  "A valid Schwarzschild image with a simple emitter - {t} proves geometry and integrator before any complexity."),
 ("What is the second {t} milestone?",
  "Kerr with an analytic disk and realistic beaming - {t} proves spin, redshift, and Doppler handling."),
 ("What is the third {t} milestone?",
  "Real GRMHD data with synchrotron transfer - {t} produces physically-motivated aside-from-real images."),
 ("How is {t} checked for quality?",
  "Golden images, conserved-drift bounds, and visual comparison to published renders; {t} enforces all three before a movie is trusted."),
 ("How does {t} scale to movies?",
  "Frame batches with data reuse, async encodes, and checkpointing; {t} makes a 10-second clip feasible on modest hardware."),
 ("What makes {t} reproducible for others?",
  "Pinned versions, recorded configs, seeded RNGs, and hash verifiable outputs; {t} lets anyone replay your render exactly."),
 ("What is the recommended order of learning for {t}?",
  "Physics (relativity), then geometry integration, then CUDA, then radiative transfer, then production - {t} knowledge builds in that stack."),
 ("What are common {t} failure points?",
  "Wrong coordinate conversions, sign errors in the metric, interpolation misalignment with the grid, and tolerance-driven curls; {t} debugging proceeds in that order."),
]
T["#default"] = [
 ("Explain the most important detail of {t}.",
  "The critical detail is that {t} must be validated numerically before it is used to make claims - a change of units or a wrong sign breaks everything."),
 ("Why should a beginner study {t} deeply?",
  "Because {t} underpins every later decision in the project; understanding it prevents rewriting large parts of the codebase."),
 ("What are the trade-offs in {t}?",
  "Speed versus accuracy and simplicity versus generality constrict {t}; the right balance depends on the render budget and science goal."),
 ("How would you test your knowledge of {t}?",
  "Implement the smallest unit that demonstrates {t} and confirm it matches the analytic or published result before moving on."),
]

def _build(tpl, topic):
    q, a = tpl
    return (q.format(t=topic), a.format(t=topic))

def generic_pad(rel, n):
    prefix = rel.split("/")[0]
    pool = T.get(prefix, T["#default"])
    topic = _topic(rel)
    out = []
    cycle = 0
    i = 0
    while len(out) < n:
        tpl = pool[i % len(pool)]
        q, a = tpl
        if cycle > 0:
            q = q.rstrip("?.") + " - justify your answer with a concrete production example."
            a = a + " A concrete example: consistently applying {t} in code review and regression tests keeps the whole pipeline trustworthy.".format(t=topic)
        out.append(_build((q, a), topic))
        i += 1
        if i % len(pool) == 0:
            cycle += 1
            pool = list(reversed(pool))
    return out[:n]