"""Curated Q&A for 04-AI-ML (ML, Deep Learning, NLP, LLM/GenAI, Agentic AI)."""
AIML = {
"01-ML-Fundamentals/01-Supervised-Learning": [
("What is supervised learning?",
 "Learning a mapping from inputs X to labelled outputs Y from (x, y) pairs: classification (discrete classes) or regression (continuous values) — the paradigm behind labelled datasets."),
("What is the difference between classification and regression?",
 "Classification predicts a discrete class (spam/not-spam, cat/dog); regression predicts a continuous value (price, temperature); loss functions differ (cross-entropy vs MSE)."),
("What is a linear regression model?",
 "y = wx + b fit by minimising squared error; coefficients estimated via ordinary least squares or gradient descent; the interpretable baseline model."),
("What is logistic regression?",
 "A linear model with a sigmoid squashing the output to a probability between 0 and 1; trained with cross-entropy/negative log-likelihood; a linear classifier, despite the name."),
("What is the difference between a decision tree and a random forest?",
 "A tree recursively splits on features based on purity (Gini/information gain); a random forest baggs many deep trees with feature subsampling — reducing variance via averaging."),
("What is SVM?",
 "Support Vector Machine finds the maximum-margin hyperplane separating classes; kernel trick (RBF/polynomial) lifts data into higher dimensions for non-linear boundaries."),
("What is k-NN?",
 "k-Nearest Neighbours predicts by majority/mean of k nearest training points; lazy (no training), distance-sensitive, scales poorly at inference — a baseline classifier."),
("What is Naive Bayes?",
 "A generative classifier assuming conditional independence of features; fast, small-data friendly, great for text (bag-of-words probability)."),
("What is overfitting and underfitting?",
 "Overfit: model memorises noise (great train, poor test). Underfit: too simple to capture the pattern (poor both). Diagnosed by the train/test gap and fixed with capacity/complexity tuning."),
("What is bias-variance tradeoff?",
 "Bias: error from wrong assumptions (underfit). Variance: error from sensitivity to training data (overfit); balancing them is the core of model selection."),
("What is cross-validation and why use it?",
 "k-fold splits data into folds rotating train/validation — robust performance estimates with limited data, avoiding a lucky/unlucky single split."),
("What is the difference between train/dev/test sets?",
 "Train fits weights; validation/dev tunes hyperparameters; test measures final generalisation — leakage between them inflates perceived performance."),
],
"01-ML-Fundamentals/02-Unsupervised-Learning": [
("What is unsupervised learning?",
 "Finding structure in unlabelled data: clustering (grouping), dimensionality reduction (compression), and anomaly detection — no labels to predict."),
("What is k-means clustering?",
 "Partitions points into k clusters by iterating assign-to-nearest-centroid then recompute-centroid; sensitive to initialisation and k; use k-means++ and elbow/silhouette."),
("What is hierarchical clustering?",
 "Agglomerate (bottom-up merge) or divide (top-down split) producing a dendrogram — no k required upfront; good for small-to-medium data."),
("What is DBSCAN?",
 "Density-based clustering: clusters are dense regions separated by sparse areas; finds arbitrary shapes, robust to outliers, needs a min-samples/epsilon setting."),
("What is PCA (Principal Component Analysis)?",
 "A dimensionality-reduction technique projecting data onto the orthogonal directions of maximum variance — decorrelating features, denoising, visualising high-D data."),
("What is the difference between PCA and t-SNE/UMAP?",
 "PCA: linear, global variance, good for pre-processing. t-SNE/UMAP: non-linear, preserve local structure, built for visualisation — different objectives entirely."),
("What is anomaly/outlier detection?",
 "Detecting points unlike the bulk: statistical (z-score/IQR), isolation forest, one-class SVM; typical for fraud/network monitoring."),
("What is association rule mining?",
 "Finding co-occurrence rules (A -> B) with support/confidence/lift, e.g., Apriori for market-basket analysis."),
("How do you evaluate clustering?",
 "Internal metrics: silhouette score, inertia; external (when labels exist): Rand index, mutual information — no single ground-truth measure."),
("What is a Gaussian Mixture Model?",
 "Data as a mixture of k Gaussian components each with own mean/covariance; EM estimates parameters — soft clustering with probability memberships."),
("What is dimensionality reduction vs feature selection?",
 "Reduction transforms features into a compressed space (PCA); selection picks a subset of original features (removes irrelevant/redundant columns) — select for interpretability."),
],
"01-ML-Fundamentals/03-Model-Evaluation": [
("What is accuracy and its limitation?",
 "Accuracy = correct/total; misleading on imbalanced data (99:1 always-predict-majority gives 99%). Precision/recall/F1 matter more there."),
("What is precision, recall, and F1?",
 "Precision = TP/(TP+FP) (how many predicted positives are right); Recall = TP/(TP+FN) (how many real positives were found); F1 = harmonic mean balancing both."),
("What is a confusion matrix?",
 "TP/FP/FN/TN laid out per class — the table precision/recall derive from; multi-class extends it to row/column per label."),
("What is ROC-AUC?",
 "ROC plots TPR vs FPR across thresholds; AUC is the probability a random positive ranks above a random negative — threshold-independent quality; AUC 0.5 is random."),
("What is precision-recall curve and when prefer it over ROC?",
 "PR focuses on the positive class — best for highly imbalanced tasks (fraud, disease) where ROC looks too optimistic."),
("What is a regression evaluation metric?",
 "MSE (big-error averse), RMSE (same units as target), MAE (robust, linear penalty), R^2 (variance explained) — pick per business cost of errors."),
("What is bias in evaluation — data leakage?",
 "Informing the model of test data (fit scaler on full data, oversampling before split) inflates metrics; leak detection is an interview favourite."),
("What is the difference between training accuracy and validation accuracy drift?",
 "Train high + val low = overfitting; both low = underfit; both high and close = healthy generalisation — the diagnostic readout."),
("What is a learning curve?",
 "Plotting train/val error vs training size clues capacity: converging curves mean well-behaved; persistent gaps mean high variance."),
("What is cross-entropy loss used as a metric?",
 "Measures disagreement between predicted probability distribution and true labels; lower = better calibration — standard for classification training."),
("What is a business-metric evaluation?",
 "Map ML errors to money (false positives cost X, false negatives cost Y) — choosing the threshold that minimises expected cost, not just AUC."),
],
"01-ML-Fundamentals/04-Feature-Engineering": [
("What is feature engineering?",
 "Transforming raw data into predictive inputs: encoding, scaling, binning, interactions, and derived quantities — often worth more than model choice."),
("What is one-hot encoding vs label encoding?",
 "One-hot: k columns for k categories (no ordinality, works for trees/linear). Label encoding: integers — only for ordinal data or targets; avoid imposing false order."),
("What is standardisation vs normalisation?",
 "Standardisation: zero-mean/unit-var (z-scores) for Gaussian-ish and distance models; min-max normalisation: scale to [0,1]. Choose per algorithm."),
("What is handling of missing values in features?",
 "Drop (if random/tiny), mean/median/mode impute, model-based imputation, or flag the missingness as a feature — the safer approaches than silently dropping rows."),
("What are the datetime/date features you'd extract?",
 "Day-of-week, month, hour, is_weekend, season, elapsed time — turning timestamps into pattern-capturing columns for forecasting/ranking."),
("What is feature scaling's effect on gradient descent?",
 "Unscaled features make the loss surface elongated, slowing convergence; scaling features speeds up optimisation and improves distance metrics."),
("What is an interaction feature?",
 "A synthetic column combining two variables (product/sum) — capturing effects a linear model can't express, e.g., price × quantity = revenue."),
("What is a text-to-feature pipeline?",
 "TF-IDF/bag-of-words, word embeddings, or LLM encodings followed by dimensionality reduction — depending on the downstream model."),
("How do you remove redundant features?",
 "Correlation/VIff inspection, mutual-information scoring, tree-importances, and backward elimination — reducing multicollinearity and overfitting."),
("What is the curse of dimensionality?",
 "As feature count grows, data becomes sparse so distances lose meaning — models overfit and clusters dissolve; dimensionality reduction counters it."),
],
"01-ML-Fundamentals/05-Regularization": [
("What is regularisation and why use it?",
 "Penalising large weights to reduce overfitting by biasing toward simpler models — the model-complexity lever in the bias-variance trade-off."),
("What is L1 (Lasso) regularisation?",
 "Adds |w| penalty — drives some weights exactly to zero yielding sparse, feature-selecting models; great for high-dimensional inputs."),
("What is L2 (Ridge) regularisation?",
 "Adds w^2 penalty — shrinks weights toward zero without sparsity; handles multicollinearity and smooths coefficients."),
("What is the difference between L1 and L2?",
 "L1 clips coefficients to exact zero (feature selection); L2 only shrinks them — L1 sparsity vs L2 stability; elastic net combines both."),
("What is early stopping?",
 "Halting training when validation loss stops improving (patience) — avoids obvious overfitting cheaply; the pragmatic DL regulariser."),
("What is dropout?",
 "Randomly zeroing neurons during training acts as ensemble averaging — the deep-learning regularisation workhorse (rate ~0.2-0.5)."),
("What is batch normalisation?",
 "Normalising layer inputs per batch stabilises and speeds training, adding slight regularisation — it reshapes the optimisation landscape."),
("What is data augmentation as regularisation?",
 "Adding transformed copies (rotation, noise, cropping) — enlarging effective training data and teaching invariance; especially in vision/audio."),
("What is weight decay vs L2?",
 "Weight decay shrinks weights each update — mathematically near L2 for standard SGD but distinct with adaptive optimisers (AdamW) — worth distinguishing."),
("What is the difference between regularisation and hyperparameter tuning?",
 "Regularisation changes the effective model family via constraints; tuning picks the strength (lambda, drop rate) — tuning searches a regularisation schedule."),
],
"01-ML-Fundamentals/06-Advanced-ML": [
("What is ensemble learning?",
 "Combining several models to beat a single one: bagging (parallel, reduces variance), boosting (sequential, reduces bias), stacking (meta-learner)."),
("What is bagging vs boosting?",
 "Bagging trains models on bootstrap samples and averages (Random Forest); boosting fits each model to residual errors of the prior (AdaBoost, XGBoost) — variance vs bias reduction."),
("What is XGBoost vs Random Forest?",
 "XGBoost is gradient-boosted trees with regularisation, native missing-value handling, and depth-wise growth — often the tabular-data winner after tuning."),
("What is gradient boosting?",
 "Sequentially adding trees trained on the negative gradient of the loss w.r.t. predictions — the generalisation of AdaBoost powering GBDT family."),
("How do you handle class imbalance beyond metrics?",
 "Resampling (SMOTE, undersample), class weights in the loss, focal loss for hard examples, and adjusted thresholds — combined, not just one."),
("What is a data generator / pipeline for training?",
 "Tensor slicing into batches with augmentation and shuffling, iterated over epochs — the framework-agnostic training loop concept."),
("What is hyperparameter tuning by grid/random/Bayesian search?",
 "Grid exhausts the product space; random samples it; Bayesian (Optuna) models the objective to guide searches — random beats grid at equal budgets, Bayesian beats both with time."),
("What is the trade-off between model interpretability and performance?",
 "Linear/trees are explainable but weaker; deep models excel but need SHAP/LIME to justify — regulated domains demand the former, scale allows the latter."),
("What is transfer learning at the ML feature level?",
 "Reusing embeddings/pre-trained representations as frozen features on a new task — smaller labelled data needed, faster convergence."),
("What is a time-series forecasting nuance?",
 "Order matters: no random shuffling, walk-forward validation, lag/recursive features, and stationarity checks — supervised framing is possible but leak-prone."),
],
"02-Deep-Learning/01-Neural-Network-Basics": [
("What is a neuron/perceptron?",
 "A weighted sum of inputs passed through a non-linear activation: y = activation(w·x + b). Stacked and chained, these form deep networks."),
("What are activation functions and common choices?",
 "ReLU (fast, sparse, default hidden), sigmoid (0-1 output), tanh (-1..1), softmax (probabilities); each has gradient regimes — ReLU dominates hidden layers."),
("What is a loss function in DL?",
 "A scalar quantifying prediction error minimised by training — cross-entropy for classification, MSE/MAE for regression; choice shapes the gradients."),
("What is backpropagation?",
 "The chain rule applied backward through the graph computing gradients of the loss w.r.t. every weight — the training engine behind all DL."),
("What is a gradient descent and its variants?",
 "SGD (one sample), mini-batch SGD (batch), Momentum/Adam (adaptive) — the optimiser family; Adam is the pragmatic default in modern training."),
("What is overfitting in a neural net?",
 "High capacity memorises training noise; diagnosed by train/val divergence; fixed with regularisation, augmentation, dropout, early stopping, more data."),
("What is the vanishing/exploding gradient problem?",
 "Gradients multiply across layers tending to 0 or infinity; mitigated by ReLU/leaky-ReLU, normalised initialisation, batchnorm, skip connections, and residual blocks."),
("What is an epoch, batch, and iteration?",
 "Epoch: one full pass over data. Batch: a chunk per update. Iteration: one batch step per epoch = samples/batch_size — the training-loop vocabulary."),
("What is a learning rate and how is it chosen?",
 "Step size of weight updates; too high diverges, too low stalls — schedule/decay and Adam's adaptive rates handle much of the tuning."),
("What is the difference between hyperparameters and parameters?",
 "Parameters are learned weights; hyperparameters (layers, lr, batch size) are set by the engineer and tuned by validation."),
("What is GPU acceleration in training?",
 "Massively parallel matrix ops the CUDA/cuDNN stack accelerates; batching utilises the GPU, memory (VRAM) caps batch size — the practical training bottleneck discussion."),
("What is weight initialisation?",
 "Setting starting weights to avoid symmetry and vanishing gradients (He/Xavier); wrong init stalls training regardless of later optimisation."),
],
"02-Deep-Learning/02-CNN": [
("What is a convolution operation?",
 "Sliding a small filter over the input computing dot products — detecting local patterns (edges, textures) with weight sharing; the CNN building block."),
("What is a convolutional layer?",
 "Multiple filters produce feature maps; strides control step size; padding preserves spatial dims. Each filter learns one local pattern."),
("What are the components of a CNN?",
 "Conv layers (feature extraction) + pooling (downsampling) + fully-connected head (classification); batchnorm and dropout interleave — the LeNet-AlexNet lineage."),
("What is pooling and its types?",
 "Max pooling (activations, noise-robust, default) and average pooling (smoothing) downsample, adding translation invariance and shrinking compute."),
("What is the receptive field?",
 "The input region a neuron sees — deeper layers aggregate wider context; stacking convolutions grows it without huge kernels."),
("What is stride and padding?",
 "Stride: filter step (controls output size); padding 'same' preserves spatial dims, 'valid' shrinks them — both tune downsampling."),
("What are known CNN architectures?",
 "LeNet (1998), AlexNet, VGG (deep small kernels), ResNet (residuals), Inception, EfficientNet — name ResNet's skip connections as the modern turning point."),
("What is the difference between a fully-connected and convolutional layer?",
 "FC: full connections, spatially agnostic, parameter heavy. Conv: local receptive fields, weight sharing, translation-equivariant — ideal for images."),
("What data augmentation for CNNs?",
 "Rotation, flip, crop, colour jitter, noise — teaching invariance and extending the effective dataset cheaply."),
("What is transfer learning with CNNs?",
 "Fine-tune pre-trained ImageNet backbones (ResNet, EfficientNet) — freezing early layers and retraining the head for new datasets efficiently."),
("What is a 1x1 convolution?",
 "A point-wise conv mixing channels while keeping spatial dims — cheap dimensionality mixing used in Inception/ResNet bottleneck blocks."),
("What are limitations of CNNs?",
 "Local receptive fields (hard to capture global context without depth), fixed grid assumption, and large data needs; attention models address some of these."),
],
"02-Deep-Learning/03-RNN-and-LSTM": [
("What is a recurrent neural network (RNN)?",
 "A network with a hidden state carried across time steps, processing sequences one token at a time — suited to text, audio, and time series."),
("What is the problem of long-term dependencies in RNNs?",
 "Gradients multiply across many steps, vanishing — so early context is lost; LSTMs/GRUs solve exactly this."),
("What is an LSTM?",
 "Long Short-Term Memory adds a cell state with input/forget/output gates controlling which information persists — gating solves vanishing gradients for long sequences."),
("What is a GRU and how does it differ?",
 "Gated recurrent unit merges input/forget gates and drops the cell state — simpler (two gates) and often comparable to LSTM with less compute."),
("What is the difference between LSTM and RNN?",
 "Vanilla RNN overwrites state each step; LSTM preserves a cell state via gates, letting relevant information survive hundreds of steps."),
("What are seq2seq models?",
 "An encoder RNN compresses the input into context, a decoder generates output step by step — the classic architecture for translation and summarisation."),
("What is attention and why did it replace RNNs?",
 "Attention lets each output directly weight all input positions, avoiding sequential bottlenecks and enabling parallel training — the pre-transformer RNN successor."),
("What is teacher forcing?",
 "During decoder training, feeding the true previous token instead of the model's own prediction — faster convergence at the cost of exposure bias."),
("What are RNN applications in NLP?",
 "Language modelling, machine translation, named-entity tagging, and text generation — historically the workhorse before transformers took over."),
("What is bidirectional RNN?",
 "Two RNNs reading forward and backward, concatenating hidden states — future context helps tagging tasks where the whole sentence is visible."),
],
"02-Deep-Learning/04-Transformers": [
("What is a transformer?",
 "A sequence model using self-attention instead of recurrence; parallel over positions, stackable layers, and the backbone of modern AI (BERT, GPT, T5)."),
("What is self-attention?",
 "Each token computes Q, K, V projections; attention weights = softmax(QK^T / sqrt(d)) applied to V — allowing every token to aggregate relevant context."),
("What is the multi-head attention?",
 "Several attention heads in parallel, each learning a different relationship subspace — concatenated and re-projected into the model width."),
("What is the role of positional encoding?",
 "Because attention is permutation-invariant, explicit position vectors (sinusoidal or learned) inject order information."),
("What is the transformer block composition?",
 "Input: (sub)layer-norm + multi-head self-attention, then a feed-forward MLP with a residual and norm — stacked N times in both encoder and decoder."),
("What is the difference between encoder-only, decoder-only, and encoder-decoder?",
 "Encoder-only (BERT): understanding/embedding. Decoder-only (GPT): generation. Encoder-decoder (T5/BART): seq2seq with full context. The architecture taxonomy."),
("What is masked/autoregressive attention?",
 "Causal masking prevents decoder tokens from attending to future tokens — preserving left-to-right generation order."),
("What are KV-cache and inference efficiency?",
 "Recomputing nothing: cached-K/V per token enable O(1)-per-token generation — the mechanism behind LLM serving and its memory ceiling."),
("Why did transformers scale so well?",
 "Parallel token processing (GPU-friendly), long-range dependencies span the input, and scaling laws — compute/data/model scale simply and predictably improve."),
("What are transformer limitations?",
 "Quadratic attention cost O(n^2) in sequence length, context-window memory, and hallucination — the motivation for FlashAttention, sparse attention, and RAG."),
("What is FlashAttention?",
 "An I/O-aware attention kernel tiling attention onto SRAM — near-linear speedups and big memory savings without changing the math."),
("What is the difference between attention and convolution?",
 "Attention is content-dependent, global, and parallel-safe; convolution is fixed-window, translation-equivariant — transformers learned them; hybrids (Conformer, Mamba) blend both."),
],
"02-Deep-Learning/05-Transfer-Learning": [
("What is transfer learning?",
 "Borrowing representations from a model trained on a big task and adapting them to a smaller related task — faster, less data, better small-dataset performance."),
("What is fine-tuning?",
 "Continuing training a pre-trained model (with a small learning rate) on the target data, unfreezing some/all layers — the standard way to adapt large models."),
("What is feature extraction vs fine-tuning?",
 "Feature extraction freezes the backbone and trains only the new head; fine-tuning updates pre-trained weights too — feature extraction first, unfreeze gradually."),
("Why does transfer learning work?",
 "Early layers learn generic features (edges, syntax, patterns) transferable across tasks; only the top layers are task-specific — reusing the generic base saves data/compute."),
("What is catastrophic forgetting?",
 "Fine-tuning on new data can overwrite old knowledge — mitigated with lower LR, replay/buffers, LoRA-style low-rank adaptation."),
("What are LoRA and parameter-efficient fine-tuning (PEFT)?",
 "LoRA adds small trainable low-rank matrices while freezing the base — near full fine-tune quality with a fraction of the memory, enabling multi-adapter serving."),
("What is a pre-trained checkpoint and how do you choose one?",
 "A snapshot of weights trained on a corpus (GPT, Llama, BERT); choose by modality, task type, license, and size-vs-resource trade-offs."),
("How do you avoid overfitting when fine-tuning small data?",
 "Tiny learning rate, few epochs, early stopping, heavier regularisation, and warmup — protecting the rich pre-trained features."),
("What is the difference between zero-shot and few-shot?",
 "Zero-shot uses the model as-is with just a prompt; few-shot supplies example demos — both avoid additional training; fine-tuning is when demos aren't enough."),
("What is domain adaptation?",
 "Shifting a model from a source domain (clean news text) to a target domain (tweets with slang) — a specialised transfer-learning case."),
],
"02-Deep-Learning/06-TensorFlow-and-Keras": [
("What is TensorFlow and how does it work?",
 "An open-source DL framework with eager execution building computation graphs; the ops run on GPU/TPU; Keras is its high-level API."),
("What is Keras?",
 "The user-friendly Python API for designing/training NN models — Sequential and Model classes, layer objects, compile/fit/evaluate loops."),
("What is the difference between Sequential and Functional API?",
 "Sequential: a linear stack of layers, restricted to single-in-single-out. Functional: arbitrary graphs with shared inputs — needed for multi-input, residuals, skip connections."),
("What does model.compile/fit/evaluate do?",
 "compile sets optimiser + loss + metrics; fit trains over epochs with batches/validation; evaluate scores held-out data — the Keras training loop."),
("What is a TF Dataset pipeline?",
 "tf.data.Dataset.from_tensor_slices + map/batch/shuffle/prefetch — streaming, parallelised input pipelines removing data-loading bottlenecks."),
("What is a callback?",
 "Hooks during training: ModelCheckpoint (save best), EarlyStopping (halt on plateau), TensorBoard (logging) — the training-quality tooling."),
("What is eager execution vs graph mode?",
 "Eager runs ops immediately (debug-friendly, default); graph mode compiles for speed/deployment (serving, @tf.function) — the define-by-run vs define-and-run tension."),
("How do you convert and deploy a TF model?",
 "SaveModel dir (or .h5/Keras v3 .keras) exported to TensorFlow Serving, or TFLite/ONNX for edge — the serialisation and serving path."),
("What is the difference between Keras and PyTorch?",
 "Keras: high-level, productivity-first, graph-ish. PyTorch: dynamic, Pythonic, research-dominant. Both deploy; PyTorch now leads research — pick per team/task."),
("What is a custom training loop in TensorFlow?",
 "@tf.function train_step with GradientTape, manual optimiser.apply_gradients — needed for GANs, custom losses, and unusual schedules."),
("What is TensorBoard?",
 "A visualiser for loss/accuracy curves, histograms of weights, and graph structure — the diagnostics tool behind 'why is loss not falling'."),
("How do you build a small CNN in Keras quickly?",
 "Sequential(Conv2D+MaxPool2D+Flatten+Dense) compiled with Adam and sparse categorical cross-entropy; fit with train/val split — the canonical 15-line model."),
],
"02-Deep-Learning/07-Advanced-DL": [
("What is a GAN?",
 "A generator fakes data vs a discriminator detecting fakes in adversarial training — converging to realistic samples; used for synthetic data and image translation."),
("What is a diffusion model?",
 "Trained by adding noise then learning to denoise — iteratively refining samples; the technology behind Stable Diffusion and DALL-E image generation."),
("What is a variational autoencoder (VAE)?",
 "An encoder producing a latent distribution (mean/var) and a decoder reconstructing; reparameterisation enables gradients — generative and representation learning."),
("What is a Graph Neural Network (GNN)?",
 "Message passing between connected nodes to learn node/graph representations — powering recommendation, molecule, and fraud graph tasks."),
("What are embeddings and how are they learned?",
 "Dense low-dimensional vectors representing entities (words, users, items) so similar things are near each other — learned end-to-end or via matrix factorisation."),
("What is knowledge distillation?",
 "Training a small student to mimic a large teacher's softened outputs — compressing models with minimal accuracy loss; one of the efficiency techniques."),
("What is model quantisation?",
 "Lowering weight precision (FP16/INT8) shrinking memory and speeding inference at slight accuracy cost — the deployment trick for large-nets-on-edge."),
("What is pruning?",
 "Dropping low-magnitude weights/neurons to slim a model — combined with quantisation for aggressive compression."),
("What is continual/incremental learning?",
 "Learning over a stream of tasks without forgetting prior ones — replay buffers, regularisation penalties, or modular networks; an active research area."),
("What is self-supervised learning?",
 "Pre-training using the data itself as supervision (next-word prediction, masked pixels) — the paradigm behind BERT/GPT reducing labelled-data needs."),
],
"03-NLP/01-NLP-Fundamentals": [
("What is NLP?",
 "Natural Language Processing: the field making machines understand, generate, and manipulate human language — from spam filters to LLM assistants."),
("What is a language model?",
 "A probability distribution over token sequences — P(w_n | w_1..w_{n-1}); n-gram counts historically, neural transformers now."),
("What is tokenisation?",
 "Splitting text into tokens (words, subwords) — WordPiece/BPE for modern LLMs balances vocab size and unknown-word handling."),
("What is a bag-of-words representation?",
 "A vector of word counts/booleans ignoring order — simple, sparse, loses syntax; the baseline for classical text classification."),
("What is TF-IDF?",
 "Term-frequency × inverse-document-frequency reweighting: common-words down, distinctive-words up — a classical information-retrieval feature."),
("What are word embeddings (Word2Vec/GloVe)?",
 "Dense vectors where semantically similar words are close (king - man + woman ≈ queen) — learned from co-occurrence statistics."),
("What is the difference between BOW, TF-IDF, word2vec, and contextual embeddings?",
 "BOW: orderless counts. TF-IDF: adds corpus-level importance. Word2Vec: static dense vectors. Contextual (BERT): meaning shifts by sentence — each step more expressive."),
("What is a n-gram and an n-gram language model?",
 "Chains of n consecutive tokens; counts-based next-token probability with smoothing — the classical predecessor beat by neural LMs."),
("What is perplexity?",
 "Exponential of average negative log-likelihood — how 'surprised' the model is; lower perplexity = better language modelling."),
("What is a corpus, and why does data dominate NLP?",
 "The collected text a model trains on; vocabulary, domain, and size decide what the model can express — 'garbage in, patternless out' applies doubly."),
],
"03-NLP/02-Text-Preprocessing": [
("What are the typical text cleaning steps?",
 "Lowercasing (task-dependent), Unicode normalisation, expanding contractions, removing URLs/HTML/emails, and controlling for noise — keep only what helps the model."),
("What is stopword removal and when is it safe?",
 "Dropping frequent function words (the, and) for bag-of-words classifiers — but harmful for neural/contextual models; token-tuned models like having them."),
("What is stemming vs lemmatisation?",
 "Stemming chops suffixes crudely (running -> runn); lemmatisation reduces to dictionary root (running -> run) using POS/lexicon — lemmatisation is cleaner but slower."),
("What is tokenisation at the word vs subword level?",
 "Word tokens blow up vocabularies and leave unknowns; BPE/WordPiece split unknown words into known pieces — the standard for sequence models."),
("What is a vocabulary and OOV handling?",
 "The finite set of known tokens; out-of-vocabulary words either become <UNK> or split into subwords — large-vocab coverage reduces information loss."),
("What is whitespace tokenisation?",
 "Splitting on spaces — simplest but breaks on punctuation/split verbs; the baseline to compare smarter tokenisers against."),
("What is padding/truncation for batching?",
 "Sequence models need fixed-length batches — pad short texts to max length and truncate long ones (with [PAD] tokens masked in attention)."),
("What are special tokens (<CLS>, <SEP>, <PAD>, <MASK>)?",
 "Reserved tokens carrying structural information: CLS aggregates, SEP separates sentences, PAD preserves shape, MASK highlights the training target."),
("What is sentence splitting?",
 "Splitting documents into sentences on punctuation/newlines — but abbreviations and decimals break naive rules; spaCy/NLTK handle edge cases."),
("What is normalisation of emojis/hashtags?",
 "Mapping emojis to keywords or dropping them; splitting hashtags — the noisy-social-text step that measurably helps social-media models."),
],
"03-NLP/03-BERT-and-Transformers": [
("What is BERT?",
 "Bidirectional Encoder Representations from Transformers — an encoder-only transformer pre-trained with masked language modelling + next-sentence prediction; the understanding model."),
("What is the masked language modelling (MLM) objective?",
 "Random tokens are masked; BERT predicts them from full bidirectional context — unlike GPT's causal left-to-right objective."),
("What is the difference between BERT and GPT in attention?",
 "BERT: bidirectional attention (sees both sides). GPT: causal/masked attention (left only). Encoder vs decoder — the two dominant pre-training paradigms."),
("What are BERT's input embeddings?",
 "Token embedding + segment embedding (sentence A/B) + positional embedding, headed by special [CLS]/[SEP] tokens — the encoding recipe."),
("What is the CLS token and [CLS] pooling?",
 "The first special token whose final embedding summarises the sequence — commonly fed to a classifier head for sentence-level tasks."),
("What is fine-tuning BERT?",
 "Adding a task head (classification/QA) and training with a low learning rate — task-specific adaptation of pre-trained language knowledge."),
("What are the sizes of BERT (base/large)?",
 "Base: 12 layers of 12 attention heads / 768 hidden (110M params); Large: 24 layers / 16 heads / 1024 hidden (340M) — the canonical parameter map."),
("What is DistilBERT / knowledge-distilled BERT?",
 "A 40% smaller student distilled to retain 97% of BERT's performance at ~60% speed — efficient-deployment NLP."),
("How does BERT handle sentence-pair tasks?",
 "Two segments joined with [SEP] and segment embeddings; NSP/classification heads decide entailment or similarity."),
("What is a tokenizer's role specific to BERT?",
 "WordPiece splitting with [UNK]/[MASK]/[CLS]/[SEP]; attention mask distinguishes real tokens from padding — the encoding that transformers consume."),
],
"03-NLP/04-Sentiment-Analysis": [
("What is sentiment analysis?",
 "Determining the polarity/emotion of text — positive/negative/neutral (or star ratings); a classic supervised text classification task."),
("What are the approaches — lexicon vs ML vs deep?",
 "Lexicon boards (VADER) with no training; classical ML (TF-IDF + logistic/SVM); and transformer fine-tuning (BERT) — each trade-off simplicity/sophistication."),
("What is a typical IMDb/review pipeline?",
 "Text -> tokenise -> (TF-IDF or BERT embeddings) -> classifier -> polarity; evaluate accuracy/F1 per class — the canonical NLP demo."),
("What polarity scores and thresholds do you use?",
 "Positive/negative compound scores; a 0 threshold separates classes but neutral-review tuning often needs a band, not a line."),
("What is aspect-based sentiment analysis?",
 "Sentiment per aspect (food good, service bad) rather than the whole text — token-level or headword-targeted prediction."),
("What are the challenges of sentiment?",
 "Negation ('not good'), sarcasm, emojis, domain-specific vocabulary ('sick' positive in slang), and mixed reviews — the failure cases interviews probe."),
("How do you evaluate a sentiment classifier beyond accuracy?",
 "Class-wise precision/recall (neutral and negative usually under-represented) plus confusion-matrix inspection — imbalance metrics apply."),
("What is zero-shot sentiment classification with LLMs?",
 "Prompting an LLM 'classify as positive/negative' — no training data, decent default; cheaper supervision via distillation when volume demands a small model."),
("What is a lexicon (VADER) and its advantage?",
 "A hand-built word→score dictionary tuned for social text — fast, interpretable, zero-training baseline that often beats naive ML on informal text."),
("What is the data-splitting danger in sentiment?",
 "Text leaks via duplicated reviews between train/test — dedup and split by source, or metrics inflate — the leakage conversation in tabular form."),
],
"03-NLP/05-Named-Entity-Recognition": [
("What is NER?",
 "Named Entity Recognition labels spans in text as PERSON, ORG, LOCATION, DATE, etc. — the information-extraction workhorse for search, compliance, and knowledge graphs."),
("What is the BIO/IOB tagging scheme?",
 "B-(egin), I-(nside), O(utside) per token: 'Barack B-PERSON Obama I-PERSON' — the sequence-labelling framing of NER."),
("What are the classical NER approaches?",
 "Rule/dictionary-based, CRF + hand-crafted features, BiLSTM-CRF neural tagging, now fine-tuned BERT — each escalation improves coverage at compute cost."),
("What is a CRF and why did it pair with BiLSTM?",
 "Conditional Random Field models label transitions — enforcing valid tag sequences (I-PER must follow B-PER); the BiLSTM produced features, CRF decoded them."),
("How does transformer-based NER work?",
 "Fine-tuned token classifiers predict a tag per token; subword tokens need alignment back to word spans — the modern highest-accuracy approach."),
("What are the evaluation metrics for NER?",
 "Micro/macro F1 over entity spans (exact-match of boundaries) — partial overlaps count as errors; strict vs relaxed scoring variants."),
("What is the challenge of entity boundaries?",
 "Long/nested entities and adjacent entities share boundaries; the model must decide exact span endpoints — boundary detection is harder than the type."),
("What is a knowledge-graph extraction pipeline using NER?",
 "NER -> entity linking (map to ontology IDs) -> relation extraction -> triples loaded into a graph — the GenAI RAG/knowledge-base interplay."),
("What are domain-specific entity types?",
 "Custom labels like product codes, chemical compounds, or device SKUs — needing annotated data and custom tag sets beyond the generic 4-5."),
("What is annotation and how do you build training data?",
 "Human/progmatic labelling tools (Prodigy, label-studio); weak supervision from lexicons/distant patterns reduces cost — data-quality feedback loop."),
],
"03-NLP/06-Advanced-NLP": [
("What is text summarisation?",
 "Converting long text into a concise version: extractive (pick salient sentences) vs abstractive (paraphrase/generate) — LLMs excel at abstractive now."),
("What is machine translation and the seq2seq history?",
 "Encoder-decoder models mapping source to target; attention lifted quality, transformers dominate, and multilingual models share parameters."),
("What is question answering?",
 "Extractive QA (span over the passage) or generative QA (free-form answer) — the basis of reader-style RAG systems."),
("What is topic modelling (LDA)?",
 "Unsupervised assigning of documents to latent topics as word distributions — thematic clustering for corpus exploration."),
("What is information retrieval vs NLP?",
 "IR finds documents relevant to a query (lexical BM25/vector search); NLP builds understanding/answers — RAG fuses both: retrieve, then reason."),
("What is semantic similarity?",
 "Vector-space closeness of meaning — cosine similarity of sentence embeddings; the core of dedup, clustering, and semantic search."),
("What is chunking and parsing?",
 "Shallow chunking groups tokens into noun/verb phrases; full parsing builds syntax trees — classic linguistics-informed NLP largely superseded by neural methods."),
("What is coreference resolution?",
 "Resolving pronouns/nominals to the same entity ('Barack... he') — key for long-document reasoning and knowledge extraction."),
("What is few-shot / in-context learning in NLP?",
 "Providing task examples inside the prompt for zero-training adaptation — the modern child of classic n-shot transfer (GPT-3 'few-shot era')."),
("What is multilingual NLP?",
 "One model speaking many languages (mBERT, XLM-R) via shared vocabularies and aligned embeddings — enabling zero-shot cross-lingual transfer."),
],
"04-LLM-and-GenAI/01-LLM-Fundamentals": [
("What is an LLM?",
 "A large transformer-based language model (billions+ of parameters) pre-trained on massive text corpora to predict the next token — fine-tuned/RL-aligned for helpful assistants."),
("How does an LLM generate text?",
 "Autoregressively: each output token conditions on all prior tokens; decoding strategies sample or greedily pick from the next-token distribution."),
("What is temperature sampling?",
 "Scaling logits before softmax: low temperature sharpens (deterministic), high temperature flattens (creative) — the creativity knob."),
("What is top-k / top-p (nucleus) sampling?",
 "Restricting the next-token choice to the top-k candidates or the smallest set with cumulative probability p — pruning low-probability tails for coherence."),
("What is the difference between pre-training and fine-tuning an LLM?",
 "Pre-training learns general language from raw text (huge compute); fine-tuning adapts it to tasks/instruction/domain with smaller curated data."),
("What is an instruction-tuned model?",
 "Fine-tuned on (instruction, response) pairs so the model follows directions instead of predicting text — the IFT ⇢ RLHF → assistant stack."),
("What is RLHF?",
 "Reinforcement learning from human feedback: a reward model trained on human preferences steers the policy to align with preference — ChatGPT-era alignment."),
("What is the context window?",
 "The maximum token input an LLM accepts; beyond it, context is truncated/extended by RoPE/scaling — the memory ceiling of conversation."),
("What are hallucinations?",
 "Fluent but fabricated outputs — the model has no epistemic grounding; mitigated by RAG, prompting confidence, and fact-checking layers."),
("What are the scaling laws?",
 "Empirical power-laws linking model size, data, compute to loss — predicting that predictable improvements justify big training runs."),
("What is a checkpoint vs a deployed model?",
 "A checkpoint is the weights snapshot; deployment wraps it with a serving/tokeniser/API — the ops difference between training and production."),
("What is the difference between a base model and a chat model?",
 "Base: raw next-token prediction, streaming and unpredictable; chat: instruction/RLHF-aligned with roles, refusals, and formatting."),
],
"04-LLM-and-GenAI/02-Prompt-Engineering": [
("What is prompt engineering?",
 "Designing inputs to steer model outputs reliably: role instructions, context, few-shot examples, and output constraints — the transferable skill for any LLM app."),
("What is the zero-shot vs few-shot prompting?",
 "Zero-shot: instructions only. Few-shot: few input/output exemplars establish the pattern. Choose few-shot when format/edge cases are tricky; trim to save tokens."),
("What is chain-of-thought (CoT) prompting?",
 "Prompting for step-by-step reasoning ('think step by step') — noticeably improves complex reasoning (math, logic) though it costs tokens and latency."),
("What is a system prompt vs user prompt?",
 "System: persistent instructions/behavioural constraints (roles, tone, rules). User: the actual request. Structuring this split is the core of production apps."),
("What is output formatting control?",
 "Requesting JSON/markdown fixtures, enums, and length caps in the prompt plus asking the model to validate — robust structured outputs from prompts alone."),
("What is prompt injection and how do you defend it?",
 "Malicious user content overrides your instructions (ignore previous, reveal key). Defenses: treat input as data, delimit with classifiers, sanitise tool calls, least-privilege."),
("What is metadata/context packing in RAG prompts?",
 "Fitting retrieved chunks into the instruction template with the user question — the prompt design that decides answer quality in RAG."),
("What is few-shot selection and examples quality?",
 "Choosing representative, correctly-formatted examples beats random sampling — mislabelled few-shots poison every shot after them."),
("What is temperature/verbosity control?",
 "Low temperature + concise instructions for deterministic APIs; high temperature for creative writing — calibrating per use case."),
("What is a constrained/guarded prompt?",
 "Explicit 'Do not X' plus output schema plus post-hoc validation — layered guardrails rather than a single hopeful line."),
("What is chain-of-density / summarisation prompting?",
 "Iteratively prompting for increasingly dense summaries — retaining detail while compressing; a trick for long-context distillation."),
],
"04-LLM-and-GenAI/03-RAG": [
("What is RAG?",
 "Retrieval-Augmented Generation: retrieve relevant documents from an external store, stuff them into the prompt, and generate grounded answers — fixing hallucination and freshness."),
("What is the RAG pipeline?",
 "Ingest: chunk documents -> embed -> index in vector DB. Query: embed the question -> top-k retrieve -> LLM answers grounded in chunks."),
("What is a chunk and how do you choose chunk size?",
 "A retrievable text unit (~200-800 tokens) with overlap; content-aware splitters (headers/sections) beat fixed sizes for coherence."),
("What is an embedding?",
 "A dense vector encoding meaning such that similar text is near — the bridge between natural language and vector search."),
("What are the retrieval strategies — vector vs keyword vs hybrid?",
 "Vector: semantic. Keyword (BM25/full-text): exact terms. Hybrid: reciprocal-rank fusion — hybrid wins on precision+recall for real corpora."),
("What is top-k and reranking?",
 "k candidates pulled; a reranker (cross-encoder) re-scores them before the prompt — with reranking the prompt gets the highest-quality passages, not just nearest."),
("What is the chunking-relevance trade-off?",
 "Small chunks are precise but lose context; large chunks are coherent but dilute relevance — chunk with overlap plus reranking balances it."),
("What is a vector database and how does it store vectors?",
 "Indexes embeddings with approximate nearest-neighbour (HNSW/IVF) — trade-offs recall vs latency; the persistent RAG memory."),
("What is the difference between RAG and fine-tuning?",
 "RAG injects fresh/external knowledge at query time (no training, updatable); fine-tuning embeds knowledge in weights (training, domain skills) — they combine, not compete."),
("What are the failure modes of RAG?",
 "Retrieved-but-irrelevant chunks, retrieval misses, prompt bloat, and outdated indexes — evaluated with retrieval metrics (recall@k) and grounded generation."),
("How do you evaluate RAG?",
 "Retrieval: precision/recall@k, MRR. Generation: faithfulness, answer relevance, and answer correctness judged by LLM/human — the RAG eval suite."),
("What is a Graph-RAG or multi-step RAG variant?",
 "Graph-RAG indexes entries as a knowledge graph answering relational questions; agentic RAG iterates retrieve-then-think — each addresses a RAG limitation."),
],
"04-LLM-and-GenAI/04-Embeddings-and-Vector-DB": [
("What is an embedding model and how do embeddings work?",
 "A neural encoder mapping text/images to dense vectors where semantically similar items are close — cosine/Euclidean distance become semantic similarity."),
("What makes embeddings useful?",
 "They make meaning computable: search, clustering, dedup, recommendation via geometric proximity, unprepared labelled labels."),
("What is cosine vs Euclidean distance?",
 "cosine ignores magnitude (direction only), best for text embeddings; Euclidean considers length — DNS/AR/Cos differs per embedding model."),
("What is a vector database (Pinecone, Chroma, Milvus, Qdrant, Weaviate)?",
 "A purpose-built store with ANN indexes, metadata filters, and CRUD over embedding vectors — the retrieval layer of RAG."),
("What is ANN (approximate nearest neighbour)?",
 "Indexes trading a tiny recall loss for huge speedups (HNSW, IVF-PQ) — brute-force similarity is too slow at scale."),
("What is HNSW?",
 "Hierarchical Navigable Small World graph index — a graph of overlapping layers with greedy greedy search; state-of-the-art for recall/latency balance."),
("What is the difference between semantic search and keyword search?",
 "Semantic catches paraphrase/intent (vector); keyword is exact-term deterministic (BM25) — hybridisation covers both."),
("What is metadata filtering in a vector store?",
 "Pre-filtering/narrowing the index by fields (date, author, tenant) before similarity — scoping retrieval for correctness and speed."),
("What is embedding dimension and how do you pick a model?",
 "Model output size (e.g., 768/1536); higher is more expressive but costs memory — choose by corpus size, latency, and quality needs."),
("How do embeddings relate to your ScriptVector-style project?",
 "Input snippets -> chunk -> embed -> vector index -> semantic lookup for code/docs — the exact RAG embedding pipeline you've built; describe it with these components."),
("What is a reranker and why add one?",
 "A cross-encoder scoring query-passage pairs precisely, re-ordering candidates — small effort, large precision gains at the top of the prompt."),
],
"04-LLM-and-GenAI/05-LLM-APIs": [
("What are the main LLM API families?",
 "OpenAI (GPT-4o-series, embeddings), Google (Gemini on Vertex/AI Studio), Anthropic (Claude), OpenRouter for unified access — chat/completions + embeddings endpoints."),
("What is the chat completions structure?",
 "POST with messages=[{role: system/user/assistant, content}], model, temperature; returns choices with content — the omnipresent API shape."),
("What is function/tool calling in LLM APIs?",
 "The model emits a structured function-call (name + args) instead of plain text; your app runs it and feeds the result back — the foundation of agentic apps."),
("What is structured output / response format?",
 "JSON-schema-validation (or JSON mode) forcing the model's output into a schema — reliable programmatic consumption without parsing gymnastics."),
("What is embeddings API usage?",
 "POST to the embeddings endpoint returning vector lists per input — powering the retrieval stores and similarity logic of RAG."),
("What is streaming and why use it?",
 "Incremental tokens over SSE — low time-to-first-token perceived latency and progressive UI rendering for chat apps."),
("How do you manage API keys, rate limits, and retries?",
 "Env/secret injection, exponential backoff on 429, token-budget accounting — the production-hardening practices interviewers ask about."),
("What is the cost/time profile of a call?",
 "Bill by prompt+completion tokens; latency scales with output length; batching/caching reduce spend — calculate per-request economics for products."),
("What is model caching or prompt caching?",
 "Providers cache repeated prefixes (system prompts, few-shots) at a discount — big savings for stable RAG/agent system prompts."),
("What is the difference between a provider-agnostic layer and direct SDKs?",
 "wrappers (OpenRouter, LiteLLM) normalise APIs across providers — resume-visible engineering of swapping models without code rewrites."),
],
"04-LLM-and-GenAI/06-Advanced-GenAI": [
("What is multi-modal GenAI?",
 "Models handling text+image+audio (GPT-4o, Gemini) — one encoder space for mixed inputs; tasks like image-QA and visual reasoning."),
("What is fine-tuning an LLM vs prompting (when to fine-tune)?",
 "Fine-tune when style/domain/format must be baked in, cost of prompt engineering exceeds training, or latency/vocab demands; evidence: prompt-first, fine-tune-last."),
("What is a completion guardrail system?",
 "Input filtering (prompt injection), output moderation, and retry loops — layered safety around raw generation."),
("What is evaluation of generative outputs?",
 "LLM-as-judge, ROUGE/BLEU for similarity, groundedness/faithfulness checks, and human raters — no single metric; combine with task-specific scoring."),
("What is the hallucination-reduction toolkit?",
 "RAG grounding, low temperature, constrained decoding, self-verification (ask the model to produce evidence), and retrieval feedback loops."),
("What is tool-use / chaining for reliability?",
 "Delegating computation to deterministic functions (calculators, APIs, DBs) instead of hoping the LLM computes — the reliability pattern behind agents."),
("What are the safety and bias concerns in GenAI?",
 "Harmful content, copyright, data leakage, and stereotyping — model-level alignment plus app-level filters and logging of audits."),
("What is a RAG-as-a-service architecture?",
 "Pick embeddings, vector DB, chunker, reranker, and LLM as separable services — the components map directly to what you built in ScriptVector."),
("What is an agentic loop added to generation?",
 "Generate -> observe tool result -> plan -> act, looped until done — generation alone becomes a component; orchestration becomes the product."),
("What are the latency/cost levers for production GenAI?",
 "Smaller models for simple paths, caching, streaming, batching, quantisation, and routing between model tiers — the engineering optimisation discussion."),
],
"05-Agentic-AI/01-Agentic-AI-Basics": [
("What is an AI agent?",
 "An LLM-driven loop that reasons, calls tools, observes results, and iterates toward a goal — autonomous decision-making beyond one-shot completion."),
("What is the difference between a chatbot and an agent?",
 "A chatbot responds once to a query; an agent plans multiple steps, invokes tools/functions, and adapts based on environment feedback until the task finishes."),
("What are the components of an agent?",
 "The LLM brain (orchestrator), tools (functions/APIs), memory (short/long-term), observation/state, and the loop controller — each pluggable."),
("What is the agent loop (ReAct pattern)?",
 "Reason (plan the next step) -> act (call a tool) -> observe (feed the result back) -> repeat until goal — the map of thinking out loud with tools."),
("What is single vs multi-agent?",
 "Single agent: one brain with many tools. Multi-agent: specialised sub-agents (researcher, coder, reviewer) supervised by a planner — decomposing complex goals."),
("What is the plan-then-execute pattern?",
 "Decompose the goal into an explicit plan first, then execute steps (re-planning on failure) — more predictable than pure reactive loops."),
("What is memory in agents — short vs long-term?",
 "Short-term: current conversation/state context. Long-term: evictions to a vector store/knowledge across sessions — retrieval makes memory scalable."),
("What is the difference between a workflow and an agent?",
 "A workflow is a fixed, hand-authored sequence; an agent decides the path dynamically at runtime — workflows for stable tasks, agents for open-ended ones."),
("What is observability crucial in agentic apps?",
 "Every step's reasoning, tool call, and latency must be traceable — debugging agents is debugging dialogues; logging is non-negotiable."),
("What is the reliability problem with agents?",
 "Free-form tool selection can loop, misuse tools, or leak context; mitigations: structured tool schemas, budgets/steps caps, validation, and human-in-the-loop checkpoints."),
],
"05-Agentic-AI/02-LangChain": [
("What is LangChain?",
 "A framework for building LLM applications from composable components: models, prompts, chains, retrievers, tools, and memory."),
("What is a chain in LangChain?",
 "A sequence of components passed through each other (prompt -> model -> parser); LCEL (LangChain Expression Language) expresses chains as pipelines with |."),
("What is LCEL and its benefits?",
 "LangChain Expression Language: composing runnables with pipes, built-in streaming/batching/async/retries — the modern way to write LangChain apps."),
("What is a Runnable?",
 "The base abstraction every chain piece implements — invoke/batch/stream/ainvoke; composability is the framework's superpower."),
("What is an LLM vs ChatModel vs Embeddings in LangChain?",
 "Three model abstractions: text-in-text-out, chat-message-in/out (preferred), and embeddings for retrieval — pluggable across providers."),
("What is a prompt template?",
 "A parameterised string (f-string/Jinja) injected with inputs — the reusable instruction wrapper for chains."),
("What is a retriever?",
 "An abstraction over document lookups (vector DB similarity or BM25) returning relevant docs — the RAG plumbing component."),
("What is memory in LangChain?",
 "ConversationBuffer/Summary/VectorStore memory feeding chat history back into prompts — preserving context across turns."),
("What is an output parser?",
 "Converts raw model text into structured objects (Pydantic/JSON) — making LLM output programmatically consumable."),
("What are the criticisms/limits of LangChain?",
 "Abstraction complexity, version churn (0.1 -> 0.2 -> 1.0), and hidden behaviours — experienced developers sometimes prefer direct SDK code for transparency."),
("How does LangChain integrate with vector DBs?",
 "LangChain vectorstores (Chroma/PGVector/Qdrant) expose from_documents/search with a common API over whichever store you pick."),
],
"05-Agentic-AI/03-LangGraph": [
("What is LangGraph?",
 "A graph-based orchestration layer on LangChain — nodes and edges model agent control flow with state, cycles, and persistence; built for production agents."),
("What is the difference between LangChain chains and LangGraph?",
 "Chains are DAG pipes; LangGraph supports cycles and stateful branching — the 'while loop' agent workflows need that chains can't express."),
("What is a graph state in LangGraph?",
 "A shared typed state (usually TypedDict/Protocol) that all nodes read/update — the single source of truth threaded through the graph."),
("What is a node vs an edge?",
 "Nodes run logic (functions/model calls/tools); edges route between them — optionally conditional edges choosing the next node based on state."),
("What is a conditional edge?",
 "After a node, a function inspects state and picks among several next nodes — the decision routing that makes graphs dynamic."),
("What is checkpointing/persistence in LangGraph?",
 "Saving graph state between steps (SQLite/Postgres) enabling resume, human-in-the-loop, and time-travel debugging — major production win."),
("What is the single graph 'supervisor' pattern?",
 "A supervisor LLM node delegates to specialised subgraphs — applying the multi-agent pattern with graph topology."),
("How does LangGraph compare to plain ReAct code?",
 "ReAct-in-a-loop is a few lines; LangGraph formalises state, retries, persistence, and visualisation — worth the dependency at scale, overhead for one-offs."),
("What is streaming in LangGraph?",
 "Streaming per-node events (state updates, LLM tokens) — live progress in UIs and step-by-step observability."),
("Why did you move from LangChain chains to LangGraph for agents?",
 "Loops and tool-feedback branching need cycles + saved state — chains compose DAGs only; if you've built agents, this is your honest engineering answer."),
],
"05-Agentic-AI/04-Tool-Use-and-Agents": [
("What is tool use / function calling?",
 "Exposing typed functions (schemas) to the model; it returns a call to invoke, results feed back in — giving LLMs access to the world."),
("What makes a good tool schema?",
 "Clear name, precise description of when to use it, and enforced parameter types/defaults — fuzzy schemas cause wrong calls and loops."),
("What are examples of agent tools?",
 "Web search, calculator/python REPL, database queries, file read/write, API calls, and RAG retrievers — the standard agent toolkit."),
("What is the ReAct prompting pattern?",
 "Deliberate alternation of Thought -> Action(ool) -> Observation fed into the model — the pattern AGENTS_REACT_LESSON all implementations follow."),
("What is a code-interpreter tool?",
 "A sandboxed Python/python runtime executing generated code — calculating, charting, and file saving with real-world side effects inside an isolated environment."),
("What is the risk of a search/web tool?",
 "Latency, prompt-injected content from pages, and non-determinism; validate and cite — never trust retrieved pages as executable instructions."),
("What is a fallback/default tool?",
 "Answering from general knowledge when no tool fits — without it agents stall; decide when refusal is better than guessing."),
("How do you stop an agent from looping?",
 "Max-step caps, monotonically tracked progress, tool-failure triggers, and interleaved self-checks ('am I advancing toward the goal?')."),
("What is tool-call validation and failure handling?",
 "Check args against schema before executing, catch exceptions gracefully, and feed the error back to the model to retry — the agentic reliability loop."),
("What is a human-in-the-loop tool?",
 "A tool that pauses to await human approval/input for high-impact actions (payments, deletions) — trust and control for autonomous systems."),
("What is grounding tool results to claims?",
 "Requiring the final answer to cite tool outputs — augmentation by retrieval and verified computation beats free-form generation."),
],
"05-Agentic-AI/05-MCP-and-A2A": [
("What is MCP (Model Context Protocol)?",
 "An open protocol standardising how LLM apps connect to tools/data sources — servers expose resources/tools/prompts; clients (agents/IDEs) consume them uniformly."),
("How does MCP relate to function calling?",
 "Function calling is model-level; MCP is application-level — a uniform transport (stdio/HTTP) to expose tools as a service to any MCP-capable client."),
("What are the MCP primitives — tools, resources, prompts?",
 "Tools: actionable functions the model may call. Resources: context/data retrievable (files, DB rows). Prompts: reusable instruction templates."),
("What is the difference between a server and a client in MCP?",
 "The server exposes capabilities; the client (Claude Desktop, an agent framework, an editor) discovers and invokes them — decoupling tools from apps."),
("What is A2A (Agent-to-Agent)?",
 "Google/community's Agent2Agent protocol defining deterministic contracts for agents to discover, negotiate, and cooperate across vendors."),
("How do MCP and A2A differ in scope?",
 "MCP connects an agent to tools/data; A2A connects agents to other agents — the tool protocol vs the inter-op protocol distinction."),
("Why standardise agent protocols?",
 "Every framework re-implementing tool wiring is waste; standards move the ecosystem — the engineering-economics argument interviewers respect."),
("What would an MCP server for your project look like?",
 "Given MigratorGen/ScriptVector: an MCP server exposing 'migrate_script', 'semantic_search_snippet', 'run_analysis' as tools — pluggable into any client."),
("What are the security considerations for MCP?",
 "Server provenance, tool permissions, and data exfiltration risks — least-privilege scoping per client; protocol adoption must include policy."),
("What does the current MCP ecosystem baggage look like?",
 "Fast-moving, version churn, and client incompatibility — evaluate lock-in versus openness when choosing an agent stack."),
],
"05-Agentic-AI/06-Advanced-Agentic-AI": [
("What is a Reflection/Self-critique pattern?",
 "The agent critiques its own output and iterates (generate -> evaluate -> improve) — boosting quality on subjective tasks like writing or code review."),
("What is ReAct vs Plan-and-Execute?",
 "ReAct interleaves reasoning and acting per step; Plan-and-Execute splits long-horizon planning from execution, replanning periodically — plan for complex goals."),
("What is a router/planner in production agents?",
 "A fast model decides the sub-tool or sub-agent per query (classification-first) — cheaper routing instead of one big model for everything."),
("What is evals-driven agent development?",
 "Recording an eval set of (task, expected outcome) and running the agent loop against it across iterations — without evals, agent changes are guesswork."),
("What is an agent sandbox and why does it matter?",
 "Executing untrusted code/tools inside isolated containers/VMs with network egress control — safety without crippling capability."),
("What is token/cost budgeting in agents?",
 "Long loops burn tokens; monitoring per-step spend, capping steps, and compressing context (summaries) keep runaway costs off the bill."),
("What is embedding memory/durable state in agents?",
 "Saving decisions/artifacts to persistent stores (DB, vector) between sessions — enabling long-running projects rather than stateless calls."),
("What is the hands-off evaluation of agent autonomy?",
 "Autonomy is a dial (assist -> suggest -> act -> fully-auto, via gate checks) matched to risk; not a binary — a product-design answer interviewers like."),
("What are the known multi-agent failure modes?",
 "Context bloat from passing full transcripts, misaligned goals between sub-agents, and compounding errors — mitigated by typed states and validation gates."),
("What would an agent framework of your own look like?",
 "State machine + tool registry + LLM client + eval harness — the minimal core you'd build rather than depend on LangGraph/Agno for: 500 words the interviewer expects."),
],
}