"""Curated Q&A for 09-Aptitude (keys are domain-relative; runner adds the 09-Aptitude prefix)."""
APTITUDE = {
"01-Quantitative/01-Number-System": [
("What is a prime number and how do you test for primes quickly?",
 "A number >1 divisible only by 1 and itself. Test divisors up to sqrt(n) only: if none divide, it is prime — O(sqrt(n)); sieve up to N gives all primes in O(N log log N)."),
("What is the divisibility rule for 11?",
 "A number is divisible by 11 if the alternating sum of its digits is a multiple of 11 (e.g., 918082: 9-1+8-0+8-2=22, divisible)."),
("What digit replaces * so that 5*91 is divisible by 9?",
 "Divisibility by 9 requires digit sum divisible by 9: 5+*+9+1 = 15+* → nearest multiple is 18, so *=3. Method: sum digits, add the shortcut."),
("What is the HCF and LCM of two numbers and its relation?",
 "HCF divides both; LCM is the least common multiple. Product rule: a*b = HCF(a,b) * LCM(a,b) — the working theorem for both calculations."),
("What is the remainder of 2^100 when divided by 5?",
 "2^4 = 16 ≡ 1 (mod 5); 100 = 4*25, so 2^100 = (2^4)^25 ≡ 1^25 = 1. Remainders cycle — the cyclic-pattern technique for powers."),
("What is a perfect square's word property?",
 "A perfect square ends only in 0,1,4,5,6,9 and its digital root is 0,1,4,7,9 — quick filters to reject candidates in elimination questions."),
("What are the common number-system formulas?",
 "Sum of first n naturals n(n+1)/2; squares n(n+1)(2n+1)/6; cubes (n(n+1)/2)^2; number of divisors via prime-factor exponents — the three formulas aptitude lean on."),
("What is the difference between 'by which' and 'of which' phrasing?",
 "'x is what percent OF y' = x/y*100; 'y is what percent MORE THAN x' = (y-x)/x*100 — read the base carefully; the base changes the answer."),
("Convert 0.125 into a fraction.",
 "0.125 = 125/1000 = 1/8. Recognise common decimal-fraction pairs (1/8, 1/4, 3/8, 5/8) as speed shortcuts."),
("What is the last two digits of 7^25?",
 "Cycles of 7^1..7^4 last two digits: 07,49,43,01 and repeat every 4; 25 mod 4 = 1 → last two digits are 07. Cycle-length technique again."),
],
"01-Quantitative/02-Percentages": [
("What is a percentage and its conversion rules?",
 "A percentage is a fraction with base 100: x% = x/100. Convert by moving the decimal two places; fractions like 25% = 1/4, 33.33% = 1/3 are the anchors."),
("What is 20% of 150 plus 10% of 250?",
 "20% of 150 = 30; 10% of 250 = 25; sum = 55. Compute percentages separately then combine — never 'add percentages of different bases'."),
("A price increases 25%, then decreases 25%. Net change?",
 "Let price = 100; after increase 125, after decrease 93.75 → net -6.25%. Equal % up then down always nets a LOSS — the classic trap answer (net is not 0)."),
("What is the difference between percentage and percentage points?",
 "Going from 10% to 15% is an increase of 5 percentage points but a 50% increase (relative) — the two vocabularies must be kept distinct."),
("Successive discounts 20% and 10% — single equivalent discount?",
 "Let price=100 → 80 → 72, so single discount of 28%. Successive discount formula: a + b - ab/100 = 20+10-2 = 28%."),
("If a number increases 12%, what is the multiplier?",
 "Final = original * 1.12; for a decrease of 12%, multiplier 0.88. Multipliers chain directly for multi-step changes (1.12 * 0.88 ≠ 1)."),
("A student scores 85% in an 80-mark paper. How many marks?",
 "Marks = 85% × 80 = 68. Percentage as fraction of total is the fundamental conversion in score-based aptitude."),
("What is 33⅓% of 90?",
 "33⅓% = 1/3, so 1/3 × 90 = 30. Common fraction-percent pairs (1/3, 2/3, 1/6, 5/6) are worth memorising."),
],
"01-Quantitative/03-Profit-and-Loss": [
("What is profit and loss?",
 "Profit = SP - CP (when SP > CP); Loss = CP - SP. Percentages computed on the cost price — the base is always CP unless stated otherwise."),
("A shopkeeper sells at 20% profit on an item costing 500. Find SP.",
 "Profit = 20% × 500 = 100; SP = 600 — or directly 500 × 1.20 = 600 (the multiplier shortcut)."),
("How do you compute profit percentage?",
 "Profit% = (SP - CP)/CP × 100. Loss% = (CP - SP)/CP × 100 — same base (CP) for both."),
("If SP = 440 with 10% loss, what is CP?",
 "SP = 90% of CP → CP = 440/0.90 = 488.89. Recover CP from SP when loss% is known using CP = SP / (1 - loss%)."),
("What is a mark-up and discount chain?",
 "Marked price = CP × (1 + markup%); selling price = marked × (1 - discount%) — profit computed on the final SP, not the marked price. Multipliers chain."),
("Two successive discounts over a 1000 item — 10% and 20%?",
 "1000 → 900 → 720; net 28% off (10+20-2). Always apply successive discounts multiplicatively, never add."),
("What is the difference between profit on SP vs CP?",
 "Profit% is on CP; some questions phrase profit as a % of SP (e.g., 'sold at 20% profit on sales') — read the base; converting: profit/SP = p → profit/CP = p/(1-p)."),
("If an article sold at 1125 gives 25% profit, find CP.",
 "CP = SP / 1.25 = 900. The SP×(multiplier) and CP×(multiplier) conversions are the two directions to master."),
],
"01-Quantitative/04-Time-and-Work": [
("What is the time-and-work formula?",
 "Work done per unit time is the rate: if a person does a job in T days, they complete 1/T per day; combined rates add. Total work is usually set to 1 (or LCM to avoid fractions)."),
("A finishes work in 12 days, B in 18. Working together, how long?",
 "Rates: 1/12 + 1/18 = (3+2)/36 = 5/36 per day; time = 36/5 = 7.2 days. Combined-rate addition is the core technique."),
("Pipes: a pipe fills a tank in 8h, another in 12h. Together?",
 "Fill rates 1/8 + 1/12 = 5/24 per hour → 24/5 = 4.8 hours. Pipes fusing rates is the classic time-and-work variant."),
("If 4 men do work in 9 days, how many days for 6 men?",
 "Total work = 4×9 = 36 man-days; 6 men → 36/6 = 6 days. Constant total work: men × days stays fixed (inverse proportion)."),
("A does 1/3 of work in 4 days; how long for the whole job alone?",
 "1/3 work in 4 days → 1 work in 12 days. Fraction-of-work-to-time conversions are the identification step in Time and Work."),
("What is the LCM method in time-and-work?",
 "Set total work = LCM of the day-counts; each person's per-day = total/days; combine and divide — avoiding fractional rates speeds up arithmetic."),
("If A+B complete in 6 days and A alone in 10, how long for B?",
 "B's rate = 1/6 - 1/10 = (5-3)/30 = 2/30 = 1/15 → B alone 15 days. Difference-of-rates recovery."),
("What are the common traps?",
 "Converting days to rates correctly, adding reciprocals (NOT adding days), and misreading 'A works alone for a while then both' set-ups — read the timeline twice."),
],
"01-Quantitative/05-Permutations-and-Combinations": [
("What is the difference between permutations and combinations?",
 "Permutations count ORDERED arrangements (P = n!/(n-r)!); combinations count UNORDERED selections (C = n!/[r!(n-r)!]) — order decides which formula."),
("How many ways to arrange letters of 'APPLE'?",
 "5! / 2! = 60 (the two P's are interchangeable) — divide by factorials of repeated letters."),
("In how many ways can a committee of 3 be chosen from 8 people?",
 "C(8,3) = 8!/(3!5!) = 56. Order doesn't matter for a committee — combination, not permutation."),
("How many 3-digit numbers can be formed from 1-9 without repetition?",
 "9×8×7 = 504 (arrange from the hundreds digit down). Use the slot-method when positions impose constraints."),
("What is the formula for circular arrangement?",
 "Circular arrangements of n distinct items = (n-1)! — fixing one item removes rotational symmetry; some variants also divide by 2 for flip symmetry."),
("How many ways to arrange 3 boys and 2 girls with girls together?",
 "Treat the 2 girls as one block: arrange 4 units (3 boys + block) = 4!, then arrange inside the block = 2! → 4!×2! = 48."),
("What is the difference between 'at least one' and 'exactly one'?",
 "'At least one' = total - none; 'exactly one' = pick it and choose the rest with none more. Translate phrases to the complement or fixed-selection method."),
("If nP2 = 30, find n.",
 "n(n-1) = 30 → n^2 - n - 30 = 0 → n = 6. Recognise the quadratic hidden in permutation variable questions."),
],
"01-Quantitative/06-Probability": [
("What is probability?",
 "P(event) = favourable outcomes / total outcomes (for equally likely outcomes) — a value in [0,1]; the complement satisfies P + P(not) = 1."),
("What is the probability of rolling an even number on a fair die?",
 "Favourable {2,4,6} out of 6 → 3/6 = 1/2. Total-outcome enumeration first, then count favourable — the standard approach."),
("Two dice: probability of a sum of 7?",
 "Favourable pairs (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6 of 36 outcomes → 1/6."),
("What is conditional probability?",
 "P(A|B) = P(A and B)/P(B) — the probability of A given B already happened; distinguished from P(A) when events depend on each other."),
("What is the difference between mutually exclusive and independent?",
 "Mutually exclusive: can't co-occur (P(A∩B)=0). Independent: one doesn't affect the other (P(A∩B)=P(A)P(B)). They are DIFFERENT concepts — never conflate."),
("A bag has 4 red and 6 blue balls. Probability of red?",
 "4/10 = 0.4. Then without replacement the next probability changes — the 'without replacement changes the branches' catch question."),
("What is expected value?",
 "E = Σ (value × probability) — the long-run average; e.g., fair die E = 21/6 = 3.5. Used in decision and game-theory aptitude."),
("At least one head in 3 coin tosses?",
 "P(at least one) = 1 - P(no heads) = 1 - (1/2)^3 = 7/8. The complement trick is a frequent shortcut."),
],
"01-Quantitative/07-Data-Interpretation": [
("What is data interpretation and what charts appear?",
 "Reading meaning from tables, bar charts, line graphs, pie charts, and caselets — computing percentages, ratios, and changes from presented numbers."),
("How do you read a pie chart?",
 "Each slice = its percentage of the total; actual values = (% × total)/100. Convert angles too: slice angle/360 × total."),
("What is the formula for percentage change from a table?",
 "(New - Old)/Old × 100 — the single most-used DI formula; watch the direction (increase vs decrease) and base year."),
("How do you compute an average from a grouped table?",
 "Sum of (value × frequency) / total frequency — weighted average when rows carry counts; also check median row position cases."),
("How do you approximate ratios quickly?",
 "Compare fractions by cross-multiplying or aligning denominators; approximate the leading digits — most DI questions allow sensible rounding (mark 'approximately')."),
("What is the difference between percentage and 'times' comparisons?",
 "'A is 25% more than B' → A = 1.25B; 'A is 0.25 times B' means A = 0.25B — small phrasing changes, correct base identification required."),
("What is a caselet and how do you read it?",
 "A paragraph of data with no chart — extract the numbers into a table first, then answer; the 'make your own structure' skill DI questions test."),
("How do you allocate time in a DI set?",
 "Skim the set, answer easy (single-lookup) questions first, and manage 'comprehension' sets last — speed on trivial reads beats accuracy slowdowns elsewhere."),
],
"01-Quantitative/08-Geometry": [
("What are the area formulas for common shapes?",
 "Square s², rectangle l×b, triangle ½×b×h, circle πr², trapezium ½(a+b)h, circumference 2πr — the six formulas aptitude lean on."),
("What is the Pythagorean theorem?",
 "a² + b² = c² for right triangles — and the triples (3,4,5), (5,12,13), (8,15,17) are worth recognising instantly."),
("What is the difference between perimeter and area on a rectangle?",
 "Perimeter 2(l+b); area l×b — units length vs area; doubling the sides ×4 the area but only ×2 the perimeter — the scaling relationship."),
("What is the area of an equilateral triangle?",
 "(√3/4)s²; its height is (√3/2)s. Recognise 30-60-90 and 45-45-90 side ratios for faster solves."),
("What is the volume of a cylinder, cube, sphere?",
 "Cylinder πr²h, cube s³, cuboid l×b×h, sphere (4/3)πr³, cone (1/3)πr²h — the volume set for mensuration questions."),
("What is the circumference-radius relationship?",
 "C = 2πr; if the circumference doubles the radius doubles; circles' area grows with r² — scaling relationships recur in geometry."),
("What is the angle sum of a triangle and an n-gon?",
 "Triangle sum 180°; general n-gon interior sum (n-2)×180° — the base for any polygon-angle breakdown."),
("What is the area of a triangle from coordinates?",
 "Area = ½|x1(y2-y3) + x2(y3-y1) + x3(y1-y2)| — the shoelace formula for coordinate geometry problems."),
],
"02-Logical-Reasoning/01-Series-and-Patterns": [
("How do you approach a number series?",
 "Check differences first; then ratios; then alternating (two interleaved series); then prime/square/cube patterns; then difference-of-differences — one systematic ladder."),
("Find the next term: 2, 6, 12, 20, 30, ...?",
 "Differences 4,6,8,10 → next +12 → 42. Alternatively n(n+1): next = 6×7 = 42 — both give the same term (pattern recognition can overlap)."),
("Find the missing term: 3, 9, 27, 81, ...?",
 "Each term ×3 → next 243. Multiplicative series are read by ratio, not difference — the quickest detection heuristic."),
("What is an alternating series and how do you spot it?",
 "Two interleaved sequences where odd positions follow one rule and even positions another — spot it by comparing positions 1,3,5 and 2,4,6 separately."),
("Find the next letter: A, C, F, J, O, ...?",
 "Gaps of 2,3,4,5 → next gap 6 → U (positions 1,3,6,10,15,21). Letter series mirror number gaps with the alphabet positions."),
("What is the difference between prime, square, and Fibonacci sequences?",
 "Prime: 2,3,5,7,11 (no simple gap); squares: 1,4,9,16 (gaps 3,5,7); Fibonacci: each term = sum of previous two — identify the family before extending."),
("How do you handle 'difference of differences'?",
 "When the first difference isn't constant, difference the differences (second differences) — quadratic series have constant second differences (e.g., 1,4,9,16)."),
("What are the common pitfalls?",
 "Multiple valid continuations exist for short series — choose the most natural rule, and verify the rule on at least two transitions before committing."),
],
"02-Logical-Reasoning/02-Puzzles": [
("What is the approach to logical puzzles?",
 "Convert statements into a structured grid/table (possessions, order, relationships), then apply elimination via definite facts — most puzzles fall to systematic constraint propagation."),
("How do you solve 'who lives in which house' (Einstein-like) puzzles?",
 "Build a table dimensioned by categories, fill definite placements, and chain implications; keep 'either/or' rows until a contradiction eliminates them."),
("There are 3 boxes: one has gold, one silver, one both. Labels are all wrong. You open one box. How do you find all?",
 "All labels wrong → open the box labelled 'both': it is silver or gold. If silver, the box labelled 'gold' must be 'both' (since it can't be gold) and 'silver' is gold — the classic wrong-label logic."),
("A ferry can hold 2; a wolf, goat, and cabbage need safe crossing. How?",
 "Take goat over; return; take wolf; bring goat back; take cabbage; return; take goat — the state-space solution to the classic crossing problem."),
("How do you solve a scheduling/order puzzle (A sits left of B)?",
 "Translate each clue into inequalities/adjacency marks; build the sequence by fixing the most constrained person first; backtrack on contradictions."),
("What is the difference between deductive and inductive puzzle solving?",
 "Deductively you PROVE with facts (all clues are certain); inductively you hypothesise and test. In puzzles the clues are usually deductive constraints."),
("How do you verify a puzzle solution?",
 "Check every clue against the final solution explicitly — each statement should be satisfied; one violated clue invalidates the answer."),
("What is the role of 'at least/at most' phrasing in puzzles?",
 "'At most one' permits zero; 'exactly one' fixes one; 'at least one' forbids zero — subtle quantifiers change the constraint sets entirely."),
],
"02-Logical-Reasoning/03-Syllogism": [
("What is a syllogism?",
 "A deductive argument with two premises (with a common 'middle' term) and a conclusion; classic form: All/most/some statements with a quantifier structure."),
("What are the four basic statement types?",
 "All A are B (universal affirmative); No A are B (universal negative); Some A are B (particular affirmative); Some A are not B (particular negative) — shown in Venn/Euler diagrams."),
("What conclusions follow from 'All A are B' and 'All B are C'?",
 "All A are C (valid); also Some A are B follows from All A are B if A is non-empty — distinguish guaranteed vs possible conclusions."),
("What is the difference between a definite and a possible conclusion?",
 "A definite conclusion holds in every Venn diagram consistent with the premises; a 'possible' conclusion holds in at least one — syllogism tests accept only definite ones."),
("Why do candidates over-infer?",
 "People import assumptions beyond the premises (e.g., assuming existence or distribution). In syllogisms, use ONLY the premises — the classic 'fanatic of the given' trap."),
("What is the 'No A are B → No B are A' conversion rule?",
 "\"No\" statements are symmetric (conversion is valid); \"All A are B\" does NOT imply \"All B are A\"; \"Some\" statements convert only if the terms are existential."),
("How do Venn diagrams help?",
 "Draw overlapping circles for the three terms; place entities from premises; the conclusion must be true in every consistent placement — diagramming beats mental juggling."),
("Give an example where a tempting conclusion is invalid.",
 "All dogs are animals; all cats are animals => 'all dogs are cats' is invalid (the common term 'animals' is the shared class, not a subset relation) — the classic trap."),
],
"02-Logical-Reasoning/04-Seating-Arrangement": [
("What is a seating arrangement puzzle?",
 "Placing people in a line or circle from directional clues (left/right, next to, opposite) — the constraint-satisfaction classic of logical reasoning."),
("What is the difference between linear and circular arrangement?",
 "Linear has definite left/right extremities; circular has no start/end (rotate freely) and 'opposite' meaning across the circle — approach the base differently."),
("How do you start a seating problem?",
 "Find the most specific clue (a fixed position or a direct adjacency), place it first, then attach the next-most-constrained clue — fixing anchors beats guessing."),
("What does 'A is second to the right of B' mean vs 'immediately right'?",
 "'Second to the right' leaves one person between; 'immediately/next to' means adjacent — one-step vs two-step phrasing changes placement."),
("How do you handle 'either/or' clues?",
 "Explore both branches; derive consequences; discard the branch that contradicts a later clue — systematic case analysis is the technique."),
("What is front-facing vs back-facing in circular puzzles?",
 "If everyone faces the centre, 'right' and 'left' are reversed for people across the table — the directionality detail that flips placements."),
("How do you verify a complete arrangement?",
 "Re-check every clue against the final diagram; a correct arrangement satisfies all of them simultaneously — efficiency from correct first placement."),
("What is the common mistake?",
 "Drifting from the diagram's directions or imagining ambiguity where there is none; redraw cleanly with an arrow for 'front' and re-verify orders."),
],
"02-Logical-Reasoning/05-Logical-Deduction": [
("What is logical deduction?",
 "Deriving a conclusion that necessarily follows from given facts/conditions — using modus ponens, contrapositives, and elimination over premises."),
("What is modus ponens and modus tollens?",
 "MP: If P then Q; P; therefore Q. MT: If P then Q; not Q; therefore not P. The two valid deductive forms — invalid forms are the catchy distractors."),
("What is the difference between 'if' and 'only if'?",
 "'P if Q' = Q → P; 'P only if Q' = P → Q — reversing them is the classic error; master the direction convention."),
("What is the contrapositive of 'If it rains, the ground is wet'?",
 "'If the ground is not wet, it didn't rain' — the contrapositive is always logically equivalent; the converse ('wet ground → rain') is NOT."),
("What is the difference between conditional and biconditional?",
 "Conditional (→) one direction only; biconditional (↔) both directions — 'if and only if' phrases signal equivalence."),
("What is the principle of least commitment?",
 "Never infer more than the premises force — a conclusion must hold in every model of the premises, so only necessary consequences are valid."),
("Give an example of an invalid conclusion that sounds correct.",
 "All cats are mammals; some mammals are pets => 'some cats are pets' is possible but NOT guaranteed — the quantifier ambiguity trap."),
("How do you approach multi-premise deduction?",
 "Chain conditionals (A→B→C gives A→C), collect contrapositives, and mark consistent inconsistent literals — structured chaining yields the conclusions."),
],
"03-Verbal/01-Reading-Comprehension": [
("How do you approach a reading-comprehension passage?",
 "Skim the passage for the main idea and structure first (topic sentences, emphasis keywords), then read questions and locate evidence — global then detail."),
("What is the difference between the main idea and a supporting detail?",
 "The main idea is the passage's central claim; details support/evidence it — questions distinguish 'author's primary purpose' from 'which detail is mentioned'."),
("How do you identify the author's tone?",
 "Look at word choice: authoritative vs tentative, critical vs celebratory — tone words (title, 'unfortunately', 'clearly') signal attitude."),
("What does 'according to the passage' question style imply?",
 "The answer must be IN the text, not inferred outside it — re-read the exact line; 'inference' questions legitimately extend the text."),
("How do you handle vocabulary-in-context questions?",
 "Read the surrounding sentence for the correct sense (the word may be used figuratively); replace the word in the sentence mentally to test the option."),
("How do you avoid trap answers?",
 "Absolute words (always, never) are often wrong; overly clever rewording that overreaches the text; and options that are true globally but not supported by this passage — mark them."),
("What is the two-pass strategy under time pressure?",
 "Pass 1: 1-2 min skim for structure. Pass 2: answer questions with targeted re-reads of relevant lines — no full slow reading on timed attempts."),
("How do you build RC vocabulary and stamina?",
 "Daily short passages on varied topics with timed drills — the base for both speed and comprehension accuracy in the assessment."),
],
"03-Verbal/02-Grammar": [
("What are the eight parts of speech?",
 "Noun, pronoun, verb, adjective, adverb, preposition, conjunction, interjection — the taxonomy every grammar question references."),
("What is the difference between a subject and a predicate?",
 "Subject: who/what the sentence is about; predicate: the verb + everything said about the subject — every complete sentence needs both."),
("What is subject-verb agreement?",
 "A singular subject takes a singular verb; plural takes plural — the classic trap: phrases between subject and verb ('a box of apples IS') confuse the number."),
("What is the difference between past perfect and simple past?",
 "Past perfect (had done) signals an action completed BEFORE another past action; simple past states a past fact — order matters for choosing."),
("What is an article and the a/an/the rules?",
 "a/an for indefinite (first mention, sound-based 'an hour'), the for definite (already known/specific); omit for generality — the three-article system."),
("What is the difference between direct and indirect speech?",
 "Direct quotes the exact words; indirect reports them shifting tense, pronouns, and time words ('I am' → 'he said he was') — shifting rules are frequently tested."),
("What are common pronoun errors?",
 "Ambiguous antecedents, and case errors: 'between you and me' (object), 'he and I went' (subject) — the me/I selection is the classic one."),
("What is the difference between 'affect' and 'effect'?",
 "affect is usually a verb (to influence); effect is usually a noun (result) — the confusable pair most vocab/grammar sections use."),
],
"03-Verbal/03-Vocabulary": [
("How do you build vocabulary efficiently for placements?",
 "Learn roots/prefixes/suffixes plus word families, review with spaced repetition, and read actively — meaning comes from usage, not lists alone."),
("What is the difference between synonyms and antonyms questions?",
 "Synonyms test closest meaning; antonyms the opposite — both need precision over approximate recall ('abandon' ≠ 'consign')."),
("What is a word in context strategy?",
 "If you don't know a word, use the surrounding context (contrast like 'but', definition clauses, examples) to infer the sense before guessing."),
("What does 'meticulous' mean and its context?",
 "Showing great care/attention to detail — a synonym for scrupulous/precise; often appears in character-description vocabulary items."),
("What is the difference between 'recipient' and 'precipient' trap pairs?",
 "Groups of similar-looking words (recipient vs recipient, quite vs quiet) are designed to trap — read the exact spelling and match the intended meaning."),
("What are the most tested word families in placement papers?",
 "Adjectives of quality (conscientious, pragmatic), formal verbs (facilitate, mitigate), and abstract nouns (paradigm, inference) — the interview-grade vocabulary set."),
("How do you answer 'odd one out' vocabulary questions?",
 "Compare meanings precisely, not first impressions; the odd word usually differs in nuance (e.g., a concrete vs abstract term) — deliberate over rushing."),
("What is collocation and why does it matter?",
 "Words that naturally co-occur (heavy rain, strong coffee) — matching common collocations avoids awkward-sounding answers in fill-in-the-blank sections."),
],
"03-Verbal/04-Sentence-Correction": [
("What is a sentence-correction question?",
 "Spotting the grammatical/usage error in a sentence and choosing the corrected version — testing agreement, tense, parallelism, idioms, and modifiers."),
("How do you spot subject-verb agreement errors?",
 "Find the verb, find its subject (skipping prepositional phrases), and match number — 'The group of players run' → 'runs' (subject 'group')."),
("What is parallelism and how do you fix it?",
 "Listed items must match grammatical form: 'to swim, jogging, and to cycle' → 'to swim, to jog, to cycle' — the parallel structure rule."),
("What is a dangling modifier?",
 "A modifier with no clear subject: 'Running to the bus, my shoe fell off' → the shoe didn't run; rewrite to 'As I ran...' — attach modifiers to their subject."),
("How do you use the correct tense in a sentence?",
 "Match the time context: 'She said she will come' → 'would come' (backshift); 'By next year, I will have graduated' (future perfect) — sequence signals the tense."),
("What is the difference between 'between' and 'among'?",
 "between for two items; among for three or more — the classic preposition rule; 'among the three of us' vs 'between you and me'."),
("What is an idiom error?",
 "Fixed phrases used wrongly: 'different than' → 'different from'; 'comply to' → 'comply with' — recognise the standard-preposition pairs."),
("What is the fastest way to correct a sentence?",
 "Identify the error TYPE first (agreement, tense, modifier, parallelism, idiom), then eliminate options that don't fix it — pattern diagnosis beats reading options as sentences."),
],
}