"""Curated Q&A for 01-DSA/01-Arrays leaves."""
ARRAYS = {
"01-Arrays/01-Basics": [
("Define an array and state how elements are stored in memory.",
 "An array is a linear, homogeneous data structure storing elements in contiguous memory locations. Element i is at address base + i*element_size, which gives O(1) random access by index."),
("Why does an array give O(1) access time?",
 "Because index maps directly to a memory address via base + index*size; the CPU does one addition and one multiply, no traversal needed."),
("Compare a Python list with a classic C array.",
 "C arrays are fixed-size, homogeneous, contiguous raw memory. A Python list is a dynamic array of PyObject pointers: it can mix types, resizes automatically (amortised O(1) append), and supports slicing/negative indexes."),
("What is the time complexity of appending to a Python list?",
 "Amortised O(1). When full, CPython allocates a larger buffer (~1.125x growth) and copies elements, spreading that O(n) cost across appends."),
("How does list.insert(0, x) compare with list.append(x)?",
 "append is amortised O(1); insert(0,x) is O(n) because every element shifts right by one. For frequent head insertions use collections.deque (O(1) both ends)."),
("Explain array slice semantics: arr[1:4].",
 "Returns a NEW list containing elements from index 1 up to (not including) index 4; original unchanged. Slicing copies references, so it costs O(k) time and memory."),
("What is the result of arr[::-1]?",
 "A new list with the array reversed — the step -1 traverses from the end to the start. It never mutates the original."),
("Why is complexity analysis of array problems critical in the SP/DSE online round?",
 "Constraints (n up to 10^5/10^6) make O(n^2) solutions time out; partial scoring means passing 60-100% hidden cases hinges on optimal or near-optimal solutions."),
("Write code to find the second largest element in an array.",
 "Track largest and second_largest in one pass: if x>mx: sec=mx; mx=x; elif sec<x<mx: sec=x. Return sec; handle n<2 as error or -inf."),
("How do you find the third maximum (distinct) element?",
 "Keep three running variables for 1st/2nd/3rd max, skipping duplicates; if fewer than 3 distinct values exist, return the maximum instead (per problem statement)."),
("What is Kadane's algorithm?",
 "Maximum subarray sum in O(n): cur = max(x, cur + x); best = max(best, cur). It works because any subarray straddling a negative prefix can be dropped."),
("What is the subarray vs subsequence distinction?",
 "Subarray is contiguous (n(n+1)/2 possibilities); subsequence preserves order but skips elements (2^n possibilities). Algorithms and complexity differ drastically."),
("How do you reverse an array in place?",
 "Two-pointer: swap arr[l] and arr[r], then l++, r--, until l>=r. O(n) time, O(1) space. Python also has arr.reverse()."),
("How do you rotate an array by k positions?",
 "k%=n; reverse(0,n-k-1); reverse(n-k,n-1); reverse(0,n-1). O(n) time O(1) space. This reversal rotation is the canonical answer."),
("Explain the missing-number problem (array 1..n missing one).",
 "Sum formula: expected n*(n+1)//2 minus current sum. XOR variant: XOR all indices+values, duplicates cancel. Both O(n) time, O(1) space."),
("How do you find duplicates in an array of length n with values in [1,n]?",
 "Cycle-detection/negative-marking: if values allowed in range, set nums[nums[i]-1] to negative as marker; the duplicated index resurfaces. Or use a set for O(n) space."),
("Explain Boyer-Moore voting for the majority element.",
 "Pair off different elements; the element surviving cancellation is the only possible majority, then verify by count. O(n) time, O(1) space, requires majority (>n/2)."),
("Why does the majority candidate need a verification pass?",
 "Voting only guarantees no OTHER majority exists; it never asserts the candidate actually is majority. A second pass counting occurrences confirms it."),
("What is a prefix-sum array and its main use?",
 "prefix[i] = sum of arr[0..i]. Range query sum(l,r)=prefix[r]-prefix[l-1] in O(1) after O(n) preprocessing. Core tool for subarray-sum problems."),
("Given prefix sums, how do you detect a zero-sum subarray?",
 "If any prefix value repeats (or equals 0), the stretch between the two occurrences sums to zero. Track seen prefix values in a set/dict."),
("What is a suffix or postfix array used for?",
 "Stores aggregates from the right (e.g., suffix max). Pairing prefix+suffix lets you compute 'element excluding range' answers, like Product of Array Except Self, in O(n)."),
("Write Product of Array Except Self in O(n) with O(1) extra space.",
 "First pass: res[i]=product of all left elements using a running product. Second pass from right: multiply by running right product. Output array itself is not counted as extra space."),
("How do you merge two sorted arrays into a third sorted array?",
 "Two-pointer merge comparing heads; append smaller, advance that pointer, then drain the remaining tail. O(m+n) time, O(m+n) space."),
("How does the in-place Merge Sorted Array (LeetCode 88) work?",
 "Work backwards: i=m-1, j=n-1, k=m+n-1. Put the larger of nums1[i], nums2[j] at k, decrement; no overwriting of unprocessed data."),
("How do you find the majority of an array using a hash map?",
 "Count frequencies in a dict, then return the key whose count > n//2. Simple, O(n) time and O(n) space; Boyer-Moore improves space to O(1)."),
("Explain the two-pointer move-zeros technique.",
 "Write-index w and scan i; if arr[i]!=0, assign arr[w]=arr[i] and w++. After the pass, fill 0 from w onward. Preserves relative order, O(n) time O(1) space."),
("What is the maximum subarray sum when the window is circular?",
 "Compute max subarray via Kadane and min subarray via inverted Kadane; circular_max = max(kadane, total - min_subarray). Edge case: if all negative, return max element."),
("How do you find the Kth largest element?",
 "Options: sort+index O(n log n); min-heap of size k O(n log k); quickselect O(n) avg. For SP/DSE, quickselect or heap demonstrates depth."),
("What is quickselect and its worst-case complexity?",
 "Variation of quicksort that partitions and recurses only into the side containing the kth element. Average O(n), worst O(n^2) with bad pivots; use random pivot in practice."),
("How do you count inversions in an array?",
 "An inversion is a pair i<j with arr[i]>arr[j]. Modified merge sort counts inversions while merging: when right element is placed, add remaining left count. O(n log n)."),
("Explain the concept of a monotonic stack and where it is used.",
 "A stack that keeps elements in increasing/decreasing order; used for next-greater/smaller element, largest rectangle in histogram, trapping rain water. Each element pushed/popped once, O(n)."),
("How do you find the next greater element for each index?",
  "Monotonic decreasing stack storing indices. While arr[stack.top()] < arr[i], pop and record arr[i] as NGE. Remaining stack elements have no NGE.",),
],
"01-Arrays/02-Two-Pointers": [
("What is the two-pointer approach on arrays?",
 "Using two indices — often from opposite ends or differing speeds — to scan an array in O(n) instead of O(n^2) nested loops, exploiting sortedness or monotonicity."),
("How do you solve two-sum on a sorted array with two pointers?",
 "l=0, r=n-1: sum < target → l++; sum > target → r--; equal → return pair. O(n) time, O(1) space, unlike the hash-map solution on unsorted input."),
("How do you find if a pair with a given sum exists in an unsorted array?",
 "Use a hash set: for each x, check if target-x is already seen, else add x — O(n) time, O(n) space. State the two-pointer variant only when sorted."),
("How do you reverse an array in place with two pointers?",
 "Swap arr[l] and arr[r], then l++, r-- until they cross — O(n) time, O(1) space; the same idea reverses subarrays for rotation problems."),
("How do you remove duplicates from a sorted array in place?",
 "Slow pointer keeps the next unique position; fast scans; write arr[slow++]=arr[fast] whenever a new value appears — O(n), O(1)."),
("What is the container-with-most-water two-pointer solution?",
 "Start l=0, r=n-1; track max area; move the SHORTER line inward (the only move that can increase the bound) — O(n), O(1)."),
("When does two pointers fail and you need another approach?",
 "When there is no monotone ordering — e.g., arbitrary target sums without sortedness — the hash set/map is safer; justify the choice per problem."),
("Give the three-pointer / Dutch flag technique.",
 "For three-way partition (0s, 1s, 2s) keep low, mid, high: mid swaps and advances according to arr[mid] — one pass to sort the trio."),
("Why is the two-pointer scan O(n) total?",
 "Each pointer only moves in one direction, visiting each element at most once — the total work is bounded by 2n, making even nested loops feel linear."),
("What is the merge step of merge sort as a two-pointer pattern?",
 "Two sorted halves merged by comparing their fronts at i and j — the pointer-at-each-sequence technique generalises to k-way merges."),
],
"01-Arrays/03-Sliding-Window": [
("What is the sliding-window technique?",
 "Maintaining a contiguous window of the array with two indices and updating an aggregate incrementally — turning O(n^2) subarray recomputation into O(n)."),
("How do you find the maximum sum subarray of a fixed size k?",
 "Compute the first window's sum, then slide: sum += arr[r] - arr[l]; track the max — O(n) time, O(1) space."),
("What is the difference between fixed and dynamic windows?",
 "Fixed: constant size k, straightforward slide. Dynamic: the window expands/shrinks while a constraint holds (e.g., longest subarray with sum ≤ target)."),
("Give the general dynamic sliding-window loop.",
 "while r < n: include arr[r]; while (condition violated): exclude arr[l], l++; update answer; r++ — the canonical two-pointer-in-loop skeleton."),
("How do you count distinct elements in each window of size k?",
 "Keep a frequency counter; on slide decrement the leaving element and remove the key at zero, tracking distinct count — O(n) overall."),
("Why is the sliding window always linear?",
 "Each element is added once (by r) and removed at most once (by l) — the inner while never makes the total loop exceed O(n) work."),
("How does sliding window address the 'minimum window substring'?",
 "Expand r until the window contains all needed chars, then shrink l while still containing them, recording the minimum — the flagship application."),
("How do you handle negative numbers in window-sum problems?",
 "Fixed-size sums still slide cleanly; dynamic 'sum ≤ target' needs care since adding a negative can be beneficial — the naive while-shrink pattern can miss valid windows."),
("What is the monotonic-deque variant?",
 "For max/min in every window of size k, a deque holding candidate indices (maintained decreasing for max) yields answers in O(n) total."),
("What edge cases do sliding-window solutions need?",
 "k > n, k = n, all-equal elements, empty array, and windows that never satisfy the constraint — every one changes return semantics."),
],
"01-Arrays/04-Sorting": [
("State the common array sorting algorithms and complexities.",
 "Bubble/Insertion O(n^2); Merge O(n log n) stable; Quick O(n log n) average (O(n^2) worst with bad pivots); Heap O(n log n) in-place; Counting/Radix O(n+k) for bounded domains."),
("What is the difference between stable and unstable sorting?",
 "Stable sorting preserves the relative order of equal elements (merge, insertion, bubble); unstable does not (quick, heap). Stability matters for multi-key sorts."),
("Explain merge sort.",
 "Divide the array in half, sort each side recursively, then merge the two sorted halves with the two-pointer merge — O(n log n) time, O(n) auxiliary space, stable."),
("Explain quick sort and how to pick a pivot.",
 "Pick a pivot, partition so smaller elements go left and larger right, recurse; average O(n log n). Random/median-of-three pivots avoid the O(n^2) worst case on sorted input."),
("What is the difference between quicksort and mergesort?",
 "Quick sorts in place (O(1) extra space, average O(n log n), not stable, cache-friendly); merge is stable but needs O(n) auxiliary space. Choose per requirements."),
("How does counting sort work?",
 "Count element frequencies over the value range, then place elements in order — O(n + k) where k is the range; only works for bounded integers."),
("What is radix sort?",
 "Sort by each digit place (LSD to MSD) using a stable sub-sort (counting) — O(d × (n+k)) — bypassing the comparison lower bound for integer inputs."),
("What is the best/worst-case of insertion sort and when is it used?",
 "O(n) best (nearly sorted), O(n^2) worst; ideal for tiny or nearly-sorted inputs and part of hybrid sorts (Timsort uses it for small runs)."),
("Why is O(n log n) the comparison-sort lower bound?",
 "There are n! permutations and each comparison splits the decision tree in two — height must be at least log2(n!) = Ω(n log n). Known as the comparison lower bound."),
("What is a custom sort key in Python?",
 "sorted(arr, key=lambda x: x[1]) or key=operator.itemgetter, plus reverse=True — Python's Timsort is stable, so multi-key sorts chain correctly."),
],
"01-Arrays/05-Searching": [
("What is binary search and its precondition?",
 "Halving a sorted array each step by comparing mid — O(log n) time, O(1) space; requires the array (or a monotone predicate) to be sorted."),
("Write the binary-search loop invariant.",
 "While lo <= hi, compute mid = lo + (hi-lo)//2; if arr[mid] == target return mid; < → lo=mid+1; > → hi=mid-1; otherwise return -1 — the invariant keeps the answer inside [lo,hi]."),
("How do you find the first occurrence of a value?",
 "On a match, record it and still move hi = mid-1 to keep searching left; the last recorded match is the first occurrence — the boundary variant."),
("What is search in a rotated sorted array?",
 "Compare arr[mid] with arr[lo] to detect which half is sorted, then decide which side might contain the target — O(log n). One of the trickier search problems."),
("What is binary search on the answer?",
 "When a monotone predicate 'is answer ≤ x feasible?' exists, binary search the answer VALUE — e.g., minimum largest subarray sum, kth smallest median."),
("What is exponential (galloping) search?",
 "Probing indices 1,2,4,8,... to bracket the target, then binary search within — O(log i) where i is the target index; used in infinite/unknown-length arrays."),
("What is interpolation search?",
 "Estimating the next probe by linear interpolation instead of the middle — O(log log n) average on uniformly distributed data but O(n) worst."),
("What are the pitfalls in binary-search implementations?",
 "Infinite loops when hi=lo, off-by-one on the midpoint convention, overflow of lo+hi in fixed-width languages, and wrong inclusive/exclusive ranges — test 1-2 element cases."),
("What is the complexity of linear search and when use it?",
 "O(n) time; preferred for unsorted, small, or one-off lookups where sort-and-search costs more; binary search only pays off once sorting amortises."),
("How does ternary search relate to binary search?",
 "Ternary splits into thirds comparing two mids — O(log_3 n) but more comparisons per step; generally slower in practice than binary for the same problem."),
],
"01-Arrays/06-Dynamic-Programming-on-Arrays": [
("What is dynamic programming on arrays?",
 "Computing array problems by combining overlapping subarray solutions stored in a DP table — classic examples: maximum subarray, stock problems, LIS, and subarray sums."),
("What is the maximum subarray (Kadane's) problem?",
 "Track best sum ending at i: dp[i] = max(arr[i], dp[i-1]+arr[i]); answer = max(dp) — O(n) time, O(1) space using a running variable."),
("What is the longest increasing subsequence and its DP?",
 "dp[i] = length of LIS ending at i = 1 + max(dp[j]) over j<i with arr[j]<arr[i] — O(n^2); the patience-sorting variant uses binary search to reach O(n log n)."),
("What is the house-robber pattern?",
 "dp[i] = max(dp[i-1], dp[i-2]+arr[i]) — take-or-skip recurrence; the two-state rolling-variable version drops space to O(1)."),
("What is the jump-game take-or-skip question?",
 "Reachability DP from the last index: can_reach[i] = min over jumps reaching a reachable index — or the greedy O(n) max-reach variant; state both."),
("How do you count subarrays with a given property using prefix sums?",
 "prefix[r] - prefix[l] == target ⇔ prefix[r] == target + prefix[l]; count with a hash map of seen prefix sums — O(n) for sum-related subarray counts."),
("What is the maximum profit stock (single transaction) question?",
 "Track min-so-far and profit = max(profit, price - min_so_far) — a single-pass O(n); multiple transactions use the state-machine (hold/sold) DP."),
("How do you decide a DP state for an array problem?",
 "Ask: 'does the answer at i depend on subanswers at i-1/i-2 (1D) or on a pair of indices (2D range) or a previous state like 'holding'?' — the state definition drives the recurrence."),
("What is the difference between greedy and DP on arrays?",
 "Greedy (jump game II, stock once) makes a single best local choice each step; DP evaluates both options via subproblem references — use DP when greedy lacks a proof."),
("What are the space-optimisation tricks?",
 "Store only the last two DP values where each step only reads dp[i-1]/dp[i-2]; use rolling arrays for 2D grids — dropping space without changing time."),
],
"01-Arrays/07-Matrix-Operations": [
("What are the common matrix traversal patterns?",
 "Row-major loops, spiral traversal (boundary shrinking), diagonal traversal, and BFS/DFS on 2D grids with directional arrays — the interview matrix toolkit."),
("How do you transpose a matrix?",
 "For square matrices swap (i,j) with (j,i) for j>i; for rectangles build a new matrix swapping dimensions — O(mn) time with a new allocation."),
("How do you rotate a matrix 90 degrees?",
 "Transpose, then reverse each row (for clockwise) — O(mn) two passes in place; or rotate layers by four-way swaps — the classic interview rotation."),
("How do you search in a row-and-column-sorted matrix?",
 "Start at top-right: if target < cell move left, if > move down — O(m+n), the classic staircase search avoiding O(log) overcomplication."),
("How do you flatten a matrix in spiral order?",
 "Shrink the boundaries (top, bottom, left, right) as you traverse; stop when they cross — printing the four edges each cycle, O(mn)."),
("How does BFS work on a grid (shortest path in matrix)?",
 "A queue of (r,c) with a distance array and four-direction moves — unweighted grid shortest paths in O(mn); the standard islands/caves framework."),
("What is the difference between DFS and BFS on a grid?",
 "DFS reaches deep first (recursion/stack, useful for island-count and connected components); BFS guarantees shortest steps (distance problems). Pick by target metric."),
("How do you compute the number of islands?",
 "Scan all cells; on each unvisited '1', BFS/DFS flood-fill it to '0' and increment count — O(mn); the flagship matrix-graph problem."),
("What is matrix multiplication and its naive cost?",
 "C[i][j] = Σ_k A[i][k]*B[k][j] costs O(mnp) for dims (m,n)×(n,p); Strassen improves to ~O(n^2.807) for large square matrices — the flat answer vs the deep one."),
("What are the common pitfalls in matrix problems?",
 "Off-by-one in boundary conditions, reading rows vs columns, accidentally revisiting cells (needs a visited set for flood-fills), and treating the grid as a graph without directions."),
],
"01-Arrays/08-Hashing-and-Maps": [
("What is hashing and why use it in array problems?",
 "Mapping keys to array indices via a hash function for O(1) average lookup — trading space for speed in counting, dedup, and pair-finding problems."),
("What is the difference between a hash set and a hash map?",
 "Set stores unique keys (membership); map stores key→value pairs (counts, indices, metadata). Array-driven interview problems usually need the map."),
("How does collision resolution work?",
 "Separate chaining (linked lists/buckets per index) or open addressing (linear/quadratic probing) — maintain the search-slots invariant; Python dict uses open addressing with perturbed probing."),
("What is the load factor?",
 "The ratio of entries to buckets; growing/rehashing the table once it exceeds a threshold (Python ~2/3) keeps the average probe count near O(1)."),
("How do you find the first non-repeating character using hashing?",
 "Two passes: count frequencies, then rescan for the first char with count 1 — O(n) time, O(1) space for bounded alphabets."),
("How do you find a pair with target sum using a map?",
 "One pass storing value→index; on each element check target-x in the map — the canonical two-sum hash solution, O(n)."),
("What is a perfect hash and array-index trick?",
 "When keys are dense small integers, a plain array of size max+1 acts as a perfect hash — no collisions, O(1) always; the counting-sort bucket idea."),
("How do you detect duplicates in O(n) with hashing?",
 "Insert into a set while scanning; the first element already in it is a duplicate — replacing the O(n^2) nested compare."),
("What are the worst-case weaknesses of hashing?",
 "A bad hash function or a crafted collision flood degrades to O(n) per op — the reason language runtimes randomise hashes for security (hash-flooding defence)."),
("How does hashing apply to sliding-window distinct counts?",
 "A map of char→frequency tracks the window's contents; increment the entering, decrement the leaving, drop keys at zero — keeping distinct count O(1)-able."),
]}

def arrays_more():
    return ARRAYS