"""Curated Q&A for 02-CS-Fundamentals/04-Operating-Systems and 05-Computer-Networks."""
CS = {
"04-Operating-Systems/01-Process-Management": [
("What is a process?",
 "A program in execution: code, data, heap, stack, registers, and state. Each process gets its own isolated address space; the OS schedules it, allocates resources, and switches between them."),
("What is the difference between a process and a thread?",
 "Process: independent memory space, heavier to create/switch, isolated. Thread: lightweight unit within a process, shares the process's memory, cheaper context switch, prone to races."),
("What are the process states?",
 "new → ready → running ↔ waiting/blocked → terminated (plus suspended/stopped variants). The diagram question — state transitions and what causes them."),
("What is a process control block (PCB)?",
 "The kernel's record per process: PID, state, program counter, registers, memory info, open files, scheduler priority — everything needed to suspend and resume a process."),
("What is context switching?",
 "Saving one process's state (into its PCB) and loading another's — the overhead of multitasking; frequent switches hurt throughput and cache locality."),
("What is the difference between preemptive and non-preemptive scheduling?",
 "Preemptive: the scheduler can interrupt a running process (time quantum). Non-preemptive: the process runs until it blocks or finishes. Real-time systems care deeply."),
("What is a zombie process?",
 "A child that has exited but whose parent hasn't yet called wait() — its PCB lingers to let the parent read the exit status. Parent must reap or the OS eventually orphans/reaps."),
("What is an orphan process?",
 "A running process whose parent has exited first; it gets reparented to init (PID 1) in Unix, which reaps it when it finishes."),
("What is fork()?",
 "The Unix system call that clones the current process (COW memory); children get a copy of memory, PID differs, and fork() returns 0 to the child and the child's PID to the parent."),
("What are the components of a process address space in memory?",
 "Text (code), data (initialised/static), heap (grows upward via malloc), stack (grows downward for calls). Layout questions define memory-management depth."),
],
"04-Operating-Systems/02-Memory-Management": [
("What is virtual memory?",
 "Faking a large logical address space backed by physical RAM + disk: each process sees a contiguous address space; pages map via the page table; the OS swaps pages in/out."),
("What is paging?",
 "Dividing memory and the address space into fixed-size frames/pages; the page table maps virtual pages to physical frames — enabling demand paging and protection."),
("What is a page fault?",
 "A referenced page is not in RAM → trap to the kernel, which loads it from disk and updates the page table. Frequent faults (thrashing) destroy performance."),
("What is a TLB (translation lookaside buffer)?",
 "A small cache of recent virtual→physical page mappings that avoids walking the page table on every access — the CPU's speed-up for address translation."),
("What is segmentation?",
 "Dividing an address space into variable-size logical segments (code, data, stack) with a segment table carrying base and limit — simpler than paging but causes external fragmentation."),
("What is the difference between internal and external fragmentation?",
 "Internal: wasted space inside allocated fixed-size blocks (paging). External: free chunks too small to satisfy requests scattered between allocations (segmentation)."),
("What is a memory allocation strategy (first-fit, best-fit, worst-fit)?",
 "First-fit: first block big enough. Best-fit: smallest sufficient (minimises waste, slower). Worst-fit: largest block (leaves bigger gaps). Covered in classic OS interviews."),
("What is thrashing?",
 "The working set exceeds RAM so the system spends more time paging than executing; the CPU utilisation collapses — fix by increasing RAM/reducing processes or improving locality."),
("What is demand paging?",
 "Loading pages only when referenced, not upfront — processes start instantly and pay lazily; page faults on first touch."),
("How does memory in Python relate to the OS concept?",
 "Python allocates small objects from arenas (pymalloc) and maps large ones via malloc/OS pages; memory safety is tied to the runtime, not the OS directly."),
],
"04-Operating-Systems/03-File-Systems": [
("What is a file system?",
 "The OS layer organising and storing data on devices: inodes/directories in Unix, NTFS' MFT in Windows — providing namespaces, permissions, persistence."),
("Explain the Unix inode concept.",
 "An inode stores metadata (size, mode, owner, timestamps) and block pointers to the file's data; file names live in directories pointing to inodes. Hard links share an inode."),
("What is a hard link vs symbolic (soft) link?",
 "Hard link: another directory entry for the same inode (same file); can't cross filesystems/directories, increments link count. Symlink: a separate inode holding a path string — can point anywhere, may dangle."),
("What is a file descriptor?",
 "An integer the process uses to reference an open file/stream; the kernel keeps an open-file table (mode, offset, buffers). Standard: 0 stdin, 1 stdout, 2 stderr."),
("What is sequential vs random file access?",
 "Sequential reads the stream order (buffered efficiently); random jumps offsets (seek). Database workloads are heavily random → page-cache and index design matter."),
("How does the OS cache file reads?",
 "Page cache keeps recently-read disk blocks in RAM, with dirty pages written back lazily — read/write performance improve dramatically; fsync forces durable flush."),
("What is journaling in file systems?",
 "Logging metadata changes before committing them so a crash replays the journal and recovers consistency — ext4/APFS use it; trade-off: some write overhead."),
("What are file permissions in Linux?",
 "r/w/x bits for owner/group/others (e.g., 755); applied via chmod/chown — the 'RWX 754' question every Linux-themed interview asks."),
("How do you list files with sizes in Linux?",
 "ls -lah, du -sh *, df -h; find -size for criteria — practical admin commands used in DevOps interviews."),
("What is the difference between a file system and a database?",
 "FS: unstructured bytes/files with path lookup. DB: structured, indexed, transactional, queryable data. Applications pick per need (blobs in FS, records in DB)."),
],
"04-Operating-Systems/04-Deadlocks": [
("What is a deadlock?",
 "A cycle of waiting where each process holds a resource another needs and none can proceed — e.g., two transactions each lock a row the other awaits."),
("What are the four necessary conditions for deadlock?",
 "Mutual exclusion (resources non-shareable), hold-and-wait (hold one while waiting for another), no preemption (can't forcibly take a held resource), circular wait (cycle of allocations)."),
("How do you prevent deadlock?",
 "Break one of the four: allow resource sharing (no mutex), acquire all resources at once (no hold-and-wait), allow preemption, or impose a global lock ordering (no circular wait)."),
("How do you avoid deadlock dynamically?",
 "Banker's algorithm: only grant requests that keep the system in a safe state (simulate worst-case completion). Resource-allocation-graph checks detect wait cycles."),
("How do you detect and recover from deadlock?",
 "Wait-for graph cycle detection; recovery by killing a process or preempting resources (rollback). Practically: DB timeouts and app retry insertions."),
("Give a real-life deadlock example from PLs/concurrency.",
 "Thread A locks resource1 then waits for resource2; Thread B locks resource2 then waits for resource1 — the classic two-thread lock-order deadlock taught in OS."),
("How does the OS usually handle deadlocks in practice?",
 "Most systems detect-and-kill or use timeouts rather than prevention (banker's is rarely used) — pragmatic avoidance with retry semantics."),
("What is the difference between deadlock, livelock, and starvation?",
 "Deadlock: no progress (blocked forever). Livelock: processes keep responding but make no progress. Starvation: some processes never get resources while others proceed."),
("What is deadlock in a database context?",
 "Two transactions hold row locks the other needs; the DB detects the cycle, aborts one, and the app retries — the exact real-world scenario."),
("How do you apply consistent lock ordering in code?",
 "Always acquire locks in the same global order (e.g., lock by ID ascending) — prevents circular wait and is the standard practical prevention."),
],
"04-Operating-Systems/05-Scheduling-Algorithms": [
("What is a scheduler and what metrics matter?",
 "The OS component choosing which ready process runs next; metrics: throughput, latency, turnaround time, waiting time, response time, fairness, and CPU utilisation."),
("Explain FCFS (First-Come First-Served).",
 "Processes run in arrival order (non-preemptive). Simple, fair-ish, but convoy effect — a long process delays everything behind it, hurting response times."),
("Explain SJF (Shortest Job First) / SRTF.",
 "Runs the shortest remaining job: SJF non-preemptive, SRTF preemptive. Minimises average waiting time but needs job lengths (unrealistic) and starves long jobs."),
("Explain Round Robin.",
 "Each process gets a time quantum; a FIFO queue cycles — fair, responsive, great for time-sharing. Quantum too small → context-switch overhead; too big → FCFS-like."),
("Explain priority scheduling.",
 "Runs the highest-priority process; low-priority can starve (ageing fixes it). Preemptive or not; the classic real-time/priority discussion."),
("Explain Multilevel Queue / Multilevel Feedback Queue (MLFQ).",
 "Multiple queues with priorities; processes move between queues based on CPU bursts (aging). MLFQ balances responsiveness (interactive) vs throughput (batch) — Linux's CFS sibling."),
("What is the difference between preemptive and non-preemptive scheduling?",
 "Preemptive can interrupt CPU-bound tasks (time-slice based), improving responsiveness; non-preemptive waits for voluntary yield or block — simpler but slower reaction."),
("What is the convoy effect?",
 "FCFS where one long CPU-bound process holds the CPU, so many short interactive jobs wait behind it; increases average wait and hurts responsiveness."),
("What is turnaround vs waiting vs response time?",
 "Turnaround = completion - arrival. Waiting = total time in ready queues. Response = first CPU grant - arrival — the three timing metrics for scheduling questions."),
("Which scheduling does Linux use in practice?",
 "CFS (Completely Fair Scheduler): a red-black tree of vruntime, aims at proportional fairness; newer kernels use EEVDF. State CFS's fairness concept in interviews."),
],
"04-Operating-Systems/06-Synchronization": [
("What is a critical section?",
 "A code region accessing shared data that must not be concurrently modified — protected by locks/mutex so at most one thread executes it at a time."),
("What is a mutex?",
 "A mutual-exclusion lock: lock() before the critical section, unlock() after. Only the holder can unlock — prevents two threads entering concurrently."),
("What is a semaphore and its types?",
 "A counter for signalling/mutual exclusion: binary semaphore ≈ mutex-like; counting semaphore tracks available resources. wait() decrements, signal() increments."),
("What is the producer-consumer problem?",
 "Threads produce/consume from a bounded buffer using semaphores: empty/full counters + mutex — the canonical synchronization problem demonstrating graceful waiting."),
("What is a race condition?",
 "Uncontrolled concurrent access where the outcome depends on scheduling order (e.g., counter++ losing updates). Fix: atomicity via locks/CAS."),
("What is a deadlock vs a race?",
 "Race = nondeterministic incorrect results from shared access. Deadlock = threads permanently blocked waiting on each other. Both come from concurrency; fixed differently."),
("What is a lock vs. an atomic operation?",
 "Lock: coarse, blocks other threads. Atomic: hardware-guaranteed single instruction (compare-and-swap / GIL-protected op) with no blocking — atomicity vs mutual exclusion nuance."),
("What is the GIL and how does it affect Python threads?",
 "The Global Interpreter Lock allows only one thread to run Python bytecode at a time — boosting single-threaded speed and memory safety but limiting CPU-bound parallelism; I/O-bound threads still benefit; multiprocessing bypasses it."),
("What is another common naming: monitor / condition variable?",
 "Condition variables let threads wait for a predicate (notify/notify_all), avoiding busy-wait; monitors combine mutex + condition — higher-level primitives for signalling."),
("How does asyncio differ from threads in Python?",
 "asyncio multiplexes tasks in one thread via an event loop (cooperative I/O); threads are preemptive OS parallelism (blocked by the GIL for CPU work). Choose loop for I/O-bound, processes for CPU-bound."),
],
"04-Operating-Systems/07-Advanced-OS": [
("What is the difference between a real-time and general OS?",
 "RTOS guarantees deadlines/preemptive priority schedules; general-purpose aims for throughput/fairness. Hard vs soft real-time distinctions matter for embedded systems."),
("What is virtual memory working set?",
 "The set of pages a process actively references; if the working set fits RAM, paging stays low — Denning's theory underlies thrashing explanations."),
("What is copy-on-write?",
 "Fork/mmap pages are shared until written, then duplicated — huge fork() speedups and the mechanism behind COW in fork(), mmap, and virtualization."),
("What is memory-mapped I/O / mmap?",
 "Mapping files into the address space so reads/writes are plain memory access — zero-copy performance for large files (like SQLite mmap or data loaders)."),
("What is a kernel module vs a driver?",
 "Modules are loadable kernel components; drivers are modules controlling hardware. Linux loads .ko modules into the running kernel — a systems-admin depth question."),
("What is an interrupt vs a poll?",
 "Interrupt: hardware signals the CPU asynchronously (efficient). Polling: CPU repeatedly checks status (busy). Interrupts dominate event-driven I/O."),
("What is the difference between concurrency and parallelism?",
 "Concurrency = multiple tasks making progress (interleaved, one CPU). Parallelism = simultaneous execution (multiple cores/CPUs). Python threads = concurrency (GIL); multiprocessing = parallelism."),
("What is NUMA and why does it matter?",
 "Non-uniform memory access: some memory is closer to a CPU than others; schedulers and allocators pin for locality — high-performance databases tune for this."),
("What is a system call and how does it differ from a library call?",
 "A syscall jumps into kernel mode (privileged) via a handler; a library call is user-space. Read/write/fork are syscalls; printf wraps a write syscall."),
("What is the difference between kernel space and user space?",
 "Kernel: privileged code (everything critical/trusted). User space: application code — isolated; transitions happen via syscalls. Security boundaries rely on this split."),
],
"05-Computer-Networks/01-OSI-and-TCP-IP": [
("List the 7 OSI layers and their function.",
 "Physical (bits/wiring), Data Link (frames/MAC), Network (IP routing), Transport (TCP/UDP ports/segments), Session (dialog orchestration), Presentation (encoding), Application (HTTP/SMTP) — memorise top-to-bottom for the roster question."),
("How do the layers compare to the TCP/IP model?",
 "TCP/IP merges: Application (7-5), Transport (4), Internet (3), Network Access (1-2). The 4-layer model is the practical derangement most interviews use."),
("What is encapsulation in networking?",
 "Each layer wraps the upper payload with its own header: data → TCP header → IP header → Ethernet frame — the onion model; empty middle term is where your packet lives."),
("What is a MAC address and how does it differ from an IP address?",
 "MAC: 48-bit hardware address on the NIC, layer-2, usually burned in. IP: 32/128-bit logical address, layer-3, assigned — the router uses IP, the switch uses MAC."),
("What is the difference between a hub, switch, and router?",
 "Hub: broadcasts at layer 1. Switch: forwards frames by MAC at layer 2, isolates collisions. Router: forwards packets by IP across networks at layer 3."),
("What is ARP?",
 "Address Resolution Protocol maps an IP to a MAC on a LAN — the cache stores IP↔MAC mappings; ARP poisoning is a known attack."),
("What is the purpose of the Transport layer?",
 "End-to-end delivery: segmentation, port numbers, reliability (TCP) or best-effort (UDP), flow/congestion control — layer 4 is TCP/UDP territory."),
("What is the Network layer responsible for?",
 "Logical addressing and routing: IP packets, subnetting, routing protocols (OSPF/BGP), and fragmentation between MTUs."),
("What happens when you type a URL and hit Enter?",
 "DNS resolution → TCP handshake → TLS handshake → HTTP request → server processing → HTTP response → rendering. The full-stack answer spanning every layer."),
("Why do we model networks in layers at all?",
 "Modularity: each layer has a defined interface, can change independently, and is testable in isolation — the engineering argument interviewers probe."),
],
"05-Computer-Networks/02-HTTP-and-HTTPS": [
("What is HTTP and what are its request methods?",
 "A request/response application protocol: GET (read), POST (create), PUT (replace), PATCH (partial), DELETE, HEAD (headers only), OPTIONS (capabilities)."),
("What is the difference between GET and POST?",
 "GET is idempotent, reads, parameters in URL, cacheable, history-clean; POST sends data in the body (non-idempotent), used for creation/state change."),
("Is DELETE idempotent?",
 "Yes — repeating a DELETE returns the same effect (gone) with no additional side effect; idempotency is a key REST design property."),
("What are the HTTP status code classes?",
 "1xx informational, 2xx success (200 OK, 201 Created, 204 No Content), 3xx redirection (301 Moved, 304 Not Modified), 4xx client error (400, 401, 403, 404, 429), 5xx server error (500, 502, 503, 504)."),
("What is the difference between 401 and 403?",
 "401 Unauthorized = no/invalid credentials (authenticate). 403 Forbidden = authenticated but denied permission. Getting these mixed is a classic API interview slip."),
("What is a cookie?",
 "A small name-value token the server sets via Set-Cookie; the browser echoes it on subsequent requests — maintaining sessions and personalisation over stateless HTTP."),
("What is a session vs a token/JWT?",
 "Session: server-side state referenced by a session ID cookie. JWT: self-contained signed token, stateless verification on the server. Sessions revoke easily; JWTs scale better."),
("What is HTTP caching and cache-control headers?",
 "Cache-Control (max-age, no-cache, private/public) tells proxies/browsers how long to reuse responses — reducing load and latency; ETag/If-None-Match add validation."),
("What is the difference between HTTP and HTTPS?",
 "HTTPS wraps HTTP in TLS (encryption, authentication, integrity). Provides confidentiality, authenticity (certs), and tamper-protection over plaintext HTTP."),
("What happens during a TLS handshake?",
 "Client Hello → Server Hello + Cert → key exchange (diffie-hellman) establishing session keys → Finished. Both sides verify the cert chain and derive keys."),
("What is CORS and why do browsers enforce it?",
 "Cross-Origin Resource Sharing: the server declares which origins may call it; the browser enforces it to prevent malicious cross-origin reads — configure headers on your FastAPI backend."),
("What is a REST endpoint vs a WebSocket?",
 "REST: request/response over HTTP, stateless calls. WebSocket: persistent bidirectional connection for real-time push (chat, live dashboards) — the architectural choice differs."),
],
"05-Computer-Networks/03-IP-Addressing": [
("What is an IP address and its classes?",
 "IPv4 is 32-bit dotted decimal (192.168.1.1); classes A (1-126), B (128-191), C (192-223) with fixed /8,/16,/24 defaults — though CIDR superseded classes in practice."),
("What is a subnet mask?",
 "A 32-bit mask separating network bits (1s) from host bits (0s) — e.g., /24 = 255.255.255.0; it defines how large a network is and which hosts share a broadcast domain."),
("What is CIDR notation?",
 "Classless Inter-Domain Routing (e.g., 10.0.0.0/24) — prefix length replacing classful routing for efficient address allocation."),
("What is the difference between a public and private IP?",
 "Public: globally routable. Private ranges (10.x, 172.16-31.x, 192.168.x) are for internal LANs, mapped to public via NAT."),
("What is NAT?",
 "Network Address Translation maps private IPs to one public IP for internet access — also applies port-mapping for inbound services. IPv4 exhaustion's main mitigator."),
("What is localhost / 127.0.0.1 and 0.0.0.0?",
 "127.0.0.1 is the loopback to the local machine; 0.0.0.0 means 'bind on all interfaces' — the uvicorn --host choices in FastAPI."),
("What is IPv6 and why do we need it?",
 "128-bit addressing (fe80::/10 link-local etc.) solving IPv4 exhaustion, with auto-configured addresses; adoption driven by growth of connected devices."),
("How does a DNS query work?",
 "Browser → resolver → root → TLD → authoritative server chain returning the A/AAAA record; cached at each level. The mapping of names to IPs underpins everything."),
("What is DNS caching and TTL?",
 "Queries cached locally/resolver-side for the record's TTL (time-to-live) — reducing latency and load; mis-set TTLs cause propagation delays."),
("What are the common record types?",
 "A (IPv4), AAAA (IPv6), CNAME (alias), MX (mail server), TXT (verification/SPF), NS (authoritative nameservers) — the DNS record roster."),
],
"05-Computer-Networks/04-Routing": [
("What is routing and the difference from forwarding?",
 "Routing = building the next-hop table (control plane). Forwarding = using the table to move each packet (data plane). Routers do both."),
("What is a routing protocol's job?",
 "Sharing reachability info to converge on correct routes — interior (OSPF, RIP) vs exterior (BGP). Convergence speed and scalability trade-offs matter."),
("What is OSPF (link-state)?",
 "Each router floods link states and runs Dijkstra per router to compute shortest paths — fast convergence, used inside an autonomous system."),
("What is BGP and why is it special?",
 "The internet's exterior routing protocol (path-vector) advertising reachable prefixes between ASes, prioritizing policies over pure shortest-path — BGP is the backbone glue."),
("What is static routing vs dynamic routing?",
 "Static: manual routes, predictable, no convergence cost but no adaptation. Dynamic: protocols detect topology changes automatically — chosen for reliability at scale."),
("What is the default gateway?",
 "The router to send packets whose destination isn't in a local subnet — the '0.0.0.0/0' catch-all route in host tables."),
("What is a routing table's longest-prefix match?",
 "When multiple routes match a destination, the most specific (longest prefix) wins — routers pick the longest match, not the first found."),
("What is ICMP and its use?",
 "Internet Control Message Protocol: error and diagnostic messages — ping (echo) and traceroute (TTL) rely on ICMP."),
("How does traceroute work?",
 "Sending packets with incrementing TTLs; each router in the path responds 'time exceeded', revealing hops until the destination — delineating the path and latency."),
("What is asymmetric routing?",
 "Packets take different paths to and from a destination — common on the internet, complicating stateful firewalls/NAT — a networking depth flag."),
],
"05-Computer-Networks/05-Security": [
("What are the CIA triad properties?",
 "Confidentiality (no unauth access), Integrity (no unauth modification), Availability (stays up) — the foundational security objectives every design must weigh."),
("What are the common types of attacks?",
 "DDoS, SQL injection, XSS, CSRF, MITM, phishing, brute force, and social engineering — know the mechanism and the mitigation for each."),
("What is a firewall and its types?",
 "A device filtering traffic by rules; packet-filter (layer 3/4) and stateful (tracks connections). Next-gen adds app-layer inspection."),
("How do you protect an API?",
 "Authentication (OAuth2/JWT), rate limiting, input validation, least-privilege scopes, TLS, CORS lockdown, and logging/monitoring — the exact controls you built into FastAPI."),
("What is symmetric vs asymmetric encryption?",
 "Symmetric: one shared key (AES) — fast. Asymmetric: key pairs (RSA/ECC), slower — used for key exchange/digital signatures; TLS uses both in a hybrid."),
("What is a hash vs encryption?",
 "Hash: one-way, fixed-length, deterministic (SHA-256) for integrity/storing passwords. Encryption: reversible with a key for confidentiality. They are not interchangeable."),
("What is a Man-in-the-Middle (MITM) attack and its mitigation?",
 "Attacker impersonates both ends, intercepting/modifying messages. Mitigations: TLS with certificate validation, pinned certs, mutual TLS."),
("What is SQL injection and how do you prevent it?",
 "Attacker injects SQL via input to manipulate queries. Prevention: parameterised queries/bind placeholders, ORMs, input validation, least-privilege DB users."),
("What is XSS and its types?",
 "Injecting client-side scripts to steal data; stored/persistent, reflected, DOM-based. Prevention: escaping output, CSP headers, sanitising input."),
("What is a CSRF attack and its mitigation?",
 "Forcing a logged-in user to perform unintended requests; mitigation: CSRF tokens, SameSite cookies, double-submit cookies."),
("What is a DDoS attack?",
 "Overwhelming a service with traffic (volumetric/application-layer) to make it unavailable (breaks availability). Mitigation: load balancing, rate limiting, CDN/WAF, mitigation services."),
("What is defence in depth?",
 "Layering independent controls (network, app, data, monitoring) so failure of one doesn't expose the system — the overall security architecture principle."),
],
"05-Computer-Networks/06-Advanced-Networking": [
("What is load balancing and its algorithms?",
 "Distributing traffic across servers: round-robin, least-connections, weighted, IP-hash, consistent hashing — each with trade-offs for state locality."),
("What is a reverse proxy vs forward proxy?",
 "Forward proxy: client-side intermediary. Reverse proxy: server-side front (nginx) hiding backends, adding TLS termination, caching, and routing."),
("What is a CDN?",
 "A content delivery network caching copies of static content at edge PoPs near users — cutting latency and origin load; the key to fast global sites."),
("What is WebSockets vs Server-Sent Events?",
 "WebSockets: full-duplex persistent channel (both directions). SSE: one-way server→client over HTTP stream — simpler, auto-reconnect; choose per channel use-case."),
("What is mTLS?",
 "Mutual TLS authenticates BOTH client and server via certificates — the zero-trust mode for service-to-service security in microservices."),
("What is HTTP/2 vs HTTP/1.1?",
 "HTTP/2 multiplexes streams over one connection (head-of-line mitigated at stream level), header compression (HPACK), server-push; HTTP/1.1 opens many connections and serialises responses."),
("What is QUIC / HTTP/3?",
 "UDP-based transport integrating TLS 1.3 and connection migration — reducing handshake latency (0-RTT) and improving loss recovery (HTTP/3 over QUIC)."),
("What is a message queue's role in a distributed network?",
 "Decoupling producers/consumers asynchronously (Kafka/RabbitMQ) — absorbing bursts, enabling retries, and isolating failure domains between services."),
("What is the role of an API gateway?",
 "A single entry point aggregating routing, auth, rate limiting, logging, and aggregation for microservices — central policy enforcement."),
("How do you design for network reliability?",
 "Redundancy (multi-AZ, multiple routes), health checks, retries with exponential backoff, circuit breakers, and load shedding — the SRE-flavoured answer."),
],
}