"""Curated Q&A for 02-CS-Fundamentals/02-DBMS and 03-SQL."""
DBMS = {
"02-DBMS/01-Database-Basics": [
("What is a database and a DBMS?",
 "A database is an organised collection of data; a DBMS is software to create, manage, query, and secure databases (e.g., PostgreSQL, MySQL). It enforces constraints, transactions, and concurrency."),
("What is the difference between a database and a DBMS?",
 "Database = the stored data itself; DBMS = the software system managing the data (storage, retrieval, integrity, concurrency). One DBMS can manage many databases."),
("What is a relational database?",
 "A database storing data in tables (relations) with rows (tuples) and columns (attributes), linked by keys, queried with SQL, guaranteed by ACID transactions — e.g., PostgreSQL."),
("What is a NoSQL database? Give types.",
 "Non-relational, schema-flexible, horizontally scalable stores: document (MongoDB), key-value (Redis), columnar (Cassandra), graph (Neo4j). Chosen for scale/velocity/flexibility."),
("What is a primary key?",
 "A column (or combination) that uniquely identifies each row — non-null and unique. It is the relational backbone for foreign-key references and fast lookup."),
("What is a foreign key?",
 "A column referencing the primary key of another table, enforcing referential integrity — ensuring a child row always points at an existing parent."),
("What is a candidate key vs super key?",
 "Super key: any set of columns that uniquely identifies rows. Candidate key: a minimal super key (no column can be removed). Primary key = chosen candidate key."),
("What is a composite key?",
 "A primary/unique key formed by two or more columns jointly identifying a row (e.g., (student_id, course_id) in enrollment)."),
("What is a unique key vs primary key?",
 "Both enforce uniqueness; primary key is non-null and only one per table; unique keys allow a single NULL, and a table may have several."),
("Explain entity, attribute, and relationship.",
 "Entity = a thing stored in its own table; attribute = a property column; relationship = an association (one-to-one, one-to-many, many-to-many)."),
("What is a view in SQL?",
 "A virtual table defined by a stored SELECT query. It presents a logically filtered/projected subset without duplicating data, hiding complexity and enforcing row/col security."),
("Data types: INT, VARCHAR, DATE — when to use each?",
 "INT for whole numbers/counter keys; VARCHAR(n) for bounded variable text; DATE/TIMESTAMP for time-based logic. Choose the tightest correct type to save storage and index size."),
("What is the difference between TRUNCATE and DELETE?",
 "TRUNCATE removes all rows quickly by deallocating pages, can't be filtered, resets identity, and is not per-row logged like DELETE; DELETE is DML, filterable, with WHERE and triggers."),
("What is a DROP vs DELETE vs TRUNCATE?",
 "DROP removes the whole table (structure+data) permanently; TRUNCATE empties the data quickly, keeps structure; DELETE removes specific rows and can be rolled back with a transaction."),
("What is data integrity?",
 "Correctness and consistency guaranteed by constraints: entity (PK), referential (FK), domain (types/CHECK), user-defined — the DBMS enforces them on write."),
("How does PostgreSQL differ from SQLite?",
 "PostgreSQL is a client-server DB with advanced features (full-text, JSONB, MVCC, extensive indexing, concurrency); SQLite is an embedded file-based engine — zero admin, single-file, lighter concurrency."),
("What is a snapshot isolation / MVCC at a high level?",
 "Multi-version concurrency control gives each reader a consistent snapshot of committed data without locks — writers don't block readers; PostgreSQL uses this."),
("What is database connection pooling?",
 "Reusing a cache of open DB connections rather than creating/freeing them per request — dramatically reduces latency and server load in API backends."),
("What is an ORM and why use it?",
 "A library mapping tables to objects (SQLAlchemy, Django ORM) so application code uses Python objects instead of raw SQL strings — safer, portable, but must watch for N+1."),
("What is the N+1 query problem?",
 "Loading a collection, then fetching one extra query per row (N queries) instead of one joined query — a classic performance trap; solve with eager loading/joins."),
("Explain database normalization in one sentence.",
 "Organising schema to minimise redundancy and dependency anomalies by splitting tables according to normal forms — a central Infosys DBMS question."),
("What is denormalization and when is it used?",
 "Intentionally merging/duplicating data to reduce JOINs or reads at scale (reporting, caching) — trading write overhead and consistency for read speed."),
("What is a stored procedure?",
 "Precompiled SQL logic stored and executed on the server (loops, transactions, business checks) — reduces network chatter and centralises rules."),
("What is a trigger?",
 "Server-side code automatically executed on INSERT/UPDATE/DELETE events — used for audits, cascades, and integrity constraints without app changes."),
("What is a transaction?",
 "A unit of work executed atomically with ACID guarantees (BEGIN...COMMIT/ROLLBACK) — the fundamental safety unit a bank transfer demonstrates."),
],
"02-DBMS/02-Normalization": [
("What is normalization?",
 "A process of organising tables to reduce redundancy and avoid update/insertion/deletion anomalies by progressively moving to higher normal forms."),
("What is 1NF (first normal form)?",
 "Every column holds a single atomic value; no repeating groups or arrays — each cell stores one value, each column stores values of one type."),
("What is 2NF?",
 "1NF plus no partial dependency — every non-key attribute must depend on the entire composite key, not a part of it. Resolve by splitting the table on the partial dependency."),
("What is 3NF?",
 "2NF plus no transitive dependency — non-key attributes must not depend on other non-key attributes (they must depend only on the key)."),
("What is BCNF (Boyce-Codd Normal Form)?",
 "Stricter 3NF: for every functional dependency X→Y, X must be a superkey. Handles anomalies 3NF misses when there are overlapping candidate keys."),
("What is 4NF/5NF briefly?",
 "4NF removes multi-valued dependencies; 5NF (project-join) handles join dependencies — rarely tested beyond naming in Infosys DSE interviews."),
("Why is normalization important?",
 "Eliminates redundant storage, prevents update anomalies (inconsistent data), insertion anomalies, and deletion anomalies — ensuring data integrity and consistency."),
("Give an example of an update anomaly.",
 "If customer address repeats in many order rows, updating the address once leaves other copies stale — a redundancy-driven inconsistency normalization removes."),
("What is a functional dependency?",
 "X→Y means for every two rows with equal X values, Y is the same — the formal rule normalization reasons about (X determines Y)."),
("What is the normalization process in practice?",
 "1NF (atomic columns) → 2NF (no partial deps on composite keys) → 3NF (no transitive deps) — for each step split tables and move dependent columns into new tables with proper keys."),
("What is denormalization's place after 3NF?",
 "For heavy-read analytics, selectively re-join duplicate data for speed — consciously trading the guarantees you took care to normalise."),
("What normalization level is production schema usually at?",
 "3NF is the common production target — enough to kill the big anomalies without over-splitting into performance-killing joins (BCNF+ occasionally)."),
],
"02-DBMS/03-ACID-Properties": [
("What does ACID stand for?",
 "Atomicity, Consistency, Isolation, Durability — the transaction guarantees that keep relational databases reliable."),
("What is atomicity?",
 "A transaction executes all-or-nothing: every operation commits or every one rolls back on failure — no partial effects survive. A bank transfer that debits must credit."),
("What is consistency?",
 "A transaction moves the database from one valid state to another, preserving all constraints (PK, FK, CHECK) — invalid intermediate states never become permanent."),
("What is isolation?",
 "Concurrent transactions execute as if run serially — one transaction's incomplete changes are invisible to others; levels (READ COMMITTED, REPEATABLE READ, SERIALIZABLE) trade strength for speed."),
("What is durability?",
 "Once committed, changes survive crashes/power loss — achieved by writing to disk/WAL records before acknowledging the commit."),
("Give the classic bank transfer explanation.",
 "Transfer ₹500 A→B: debit A, credit B. Atomic: both or none. Consistency: balances stay ≥ 0 per constraint. Isolation: another read never sees a half-transfer. Durability: after COMMIT the change survives a crash."),
("What is COMMIT vs ROLLBACK?",
 "COMMIT makes a transaction's changes permanent durably; ROLLBACK undoes all its changes back to the last commit, restoring the before-image — the atomicity mechanism."),
("What is a WAL (write-ahead log)?",
 "A log written before the actual data changes; on crash recovery the DB replays the WAL — the standard durability mechanism behind PostgreSQL."),
("What are the isolation levels?",
 "READ UNCOMMITTED (dirty reads), READ COMMITTED (no dirty reads), REPEATABLE READ (no non-repeatable reads), SERIALIZABLE (full serial order) — each loosens concurrency for speed."),
("What is a dirty read, non-repeatable read, phantom read?",
 "Dirty: reading another txn's uncommitted change. Non-repeatable: same row re-reads differently within a txn. Phantom: a query's result set gains/loses rows within a txn due to another commit."),
("Explain ACID with a real project example.",
 "In an API with an orders table and a payments ledger, wrapping insert+update in one transaction with a constraint check models the same atomicity/consistency you'd write in SQL."),
],
"02-DBMS/04-Indexing": [
("What is a database index?",
 "A structure (typically B+tree) that speeds up lookups on a column by maintaining sorted key pointers — the trade-off is write cost and storage."),
("How do B+tree indexes work at a high level?",
 "Leaves hold sorted key→rowid pointers, internal nodes are the search tree — O(log n) lookups, range scans in sorted order, good locality for disk pages."),
("What is the difference between clustered and non-clustered index?",
 "Clustered: the table's rows are physically ordered and stored with the index key (data in the leaf) — at most one per table (often the PK). Non-clustered: separate structure holds key + row pointers."),
("When should you NOT use an index?",
 "On rarely-queried columns, columns updated frequently, small tables (full scan cheaper), or columns with low selectivity (e.g., a boolean) — index overhead outweighs gains."),
("What is a composite index and the leftmost-prefix rule?",
 "An index on multiple columns (a,b,c). Queries can use prefixes (a), (a,b), (a,b,c) — the rule: conditions must match from leftmost column to benefit worthily."),
("What is a covering index?",
 "An index containing every column the query needs, so the DB answers entirely from the index without table lookup — the query never touches the table."),
("How do you debug a slow query (index check)?",
 "EXPLAIN (ANALYZE) to see seq-scan vs index-scan and row estimates; verify the index is actually used, check selectivity, and rewrite predicates to match index order."),
("What is index selectivity?",
 "The fraction of rows an index value matches; high selectivity (unique-ish values) makes indexes useful; low selectivity nullifies the benefit — B-tree index on a gender column is often useless."),
("What is a hash index?",
 "O(1) equality lookups but unusable for range queries — good for exact-match key lookups; B+tree supports both equality and ranges, so it dominates."),
("How does a primary key affect the physical layout?",
 "In PostgreSQL/InnoDB the PK index is the table (clustered) — rows are stored in PK order, so a sequential PK yields append-friendly inserts and fast point lookup."),
("What is an index scan vs a full table scan?",
 "Index scan: walks the B+tree to find matching row pointers — fast for selective queries. Full scan: reads all pages — fine for small tables or when most rows match."),
("How many indexes is too many?",
 "Every index slows INSERT/UPDATE/DELETE and takes space; keep only those matching the hot query paths — a rule of thumb: under ~5 per table unless measured otherwise."),
],
"02-DBMS/05-Transactions": [
("What is a transaction?",
 "A logical unit of work composed of one or more statements executed with ACID guarantees; it either commits fully or rolls back fully."),
("How do you start/end a transaction in SQL?",
 "BEGIN (or BEGIN TRANSACTION) starts; COMMIT ends successfully; ROLLBACK aborts. Nested via savepoints (SAVEPOINT sp; ROLLBACK TO sp)."),
("What is a savepoint?",
 "A named checkpoint inside a transaction; you can roll back to a savepoint without aborting the whole transaction — fine-grained error recovery."),
("What is a lock and why needed?",
 "A mechanism restricting concurrent access to a row/table while a transaction holds it, ensuring isolation — shared (read) and exclusive (write) locks are the basics."),
("What is a deadlock?",
 "Two transactions each hold a lock the other needs and wait forever. DBs detect cycles and abort one offender (rollback) — retry logic on the app side is expected."),
("What is a lost update?",
 "Two concurrent transactions both read a value and write back, the second overwriting the first's change without seeing it — avoided by locking or MVCC."),
("How does MVCC prevent blocking reads?",
 "Each transaction works on its own snapshot/version of rows; writers don't block readers and vice versa (PostgreSQL). Conflicts surface as version conflicts at commit."),
("What is optimistic vs pessimistic locking?",
 "Optimistic: read without locks, verify the version at write (raise conflict if changed). Pessimistic: acquire locks upfront (SELECT ... FOR UPDATE). Optimistic scales better under low conflict."),
("What happens if the app loses connection mid-transaction?",
 "The DB (or driver) rolls back the uncommitted transaction; app-level retry should re-execute idempotently — a distributed-systems interview point."),
("How do you test transaction behaviour?",
 "Open two sessions; one inserts without committing; assert the other can't see the change (READ COMMITTED); commit; assert it appears — this is the practical isolation check."),
],
"02-DBMS/06-Stored-Procedures": [
("What is a stored procedure?",
 "A named block of SQL (with control flow: IF/LOOP, variables) stored on the server, executed by CALL/EXEC — precompiled for reuse and reduced network traffic."),
("Advantages of stored procedures.",
 "Performance (precompiled plan), reuse, centralised business logic near data, security (grants only on the proc), and atomicity across statements."),
("Disadvantages of stored procedures.",
 "Hard to version/debug, ties logic to the DB (tight coupling), migration pain, and weaker testing tooling compared to app code."),
("What is the difference between a stored procedure and a function in SQL?",
 "Functions return a value and can be used inside queries (SELECT f(x)); procedures are called standalone, support transactions and OUT params, and can't be used in expressions."),
("What is a trigger and difference from a procedure?",
 "A trigger fires automatically on DML events (INSERT/UPDATE/DELETE); a procedure must be called explicitly. Triggers enforce cross-table integrity and audits."),
("When should you store logic in the app vs the DB?",
 "DBA-visible rules, column-level defaults, and cross-SESSION integrity belong in the DB; business workflows, presentation, and policy belong in the app — keep the DB a data layer."),
("How do you guard against SQL injection in all these?",
 "Use parameterised queries/bind variables everywhere — stored procedures with user input must be called with bound parameters, never string-concatenated."),
("How do you debug a slow stored procedure?",
 "EXPLAIN inside the procedure's queries, check for accidental Cartesian joins, index usage on hot columns, and plpgsql-statistics-like profiling."),
],
"02-DBMS/07-Database-Design": [
("Walk me through designing a database for a blog platform.",
 "Tables: users, posts (user_id FK), comments (post_id FK, user_id FK), tags + post_tags (many-to-many), likes. Normalise to 3NF, index on post_id/created_at, and keep counters denormalised only if profiling demands."),
("How do you model a many-to-many relationship?",
 "A junction table holding two FKs (e.g., student_course(student_id, course_id) with composite PK) — the standard relational solution."),
("How do you design an e-commerce schema?",
 "Customers, products, orders (header), order_items (line details, product FK, order FK), payments, addresses. Order totals can be derived; keep immutable line items intact."),
("What is a soft delete and when do you use it?",
 "Marking rows deleted (is_deleted flag/deleted_at) instead of removing them — preserves audit/history; query filters must exclude them; can slow scans if not partitioned."),
("What is a UUID vs auto-increment PK?",
 "Auto-increment: compact, ordered, but exposes counts and has global collisions across distributed shards. UUID: global uniqueness, unguessable, but larger and scattered (use UUIDv7 for time-ordering)."),
("What is schema migration and why it matters?",
 "Version-controlled changes to schema applied in order (Alembic for SQLAlchemy). Without them, deploy-time divergence and data loss are guaranteed."),
("How do you decide SQL vs NoSQL for a feature?",
 "SQL: strong consistency, ACID, relational queries. NoSQL: scale-out, flexible schema, high write throughput. Polyglot persistence — pick per workload, not globally."),
("What is database sharding?",
 "Splitting data across multiple DB instances by key (user_id hash/range) to scale writes; complicates joins and transactions — done at scale after vertical scaling saturates."),
("What is a time-series design option?",
 "Store event rows with (event_time, metric) and partition by time; PostgreSQL range partitioning or dedicated TSDBs (TimescaleDB/InfluxDB) — index and archive hot/warm tiers."),
("What is the CAP theorem and its DB choice implications?",
 "Consistency, Availability, Partition tolerance — pick two under network partition. Relational DBs lean CP; AP systems like Cassandra choose availability; the partition is unavoidable in distributed systems."),
],
"02-DBMS/08-Advanced-DBMS": [
("What is a materialized view?",
 "A view whose result set is physically stored and refreshed (manually/scheduled) — precomputed aggregates for fast reads at the cost of staleness."),
("What is query optimisation and what does a query planner do?",
 "Planner estimates costs of plans (index/full scan, join order, hash vs nested loop) and picks an execution plan; stats quality and indexes steer it. EXPLAIN shows the chosen plan."),
("What are join algorithms?",
 "Nested loop (small/inner), hash join (equi-join on moderate tables), merge join (sorted inputs) — the DB picks based on stats; knowing them helps you write joinable queries."),
("What is partition pruning?",
 "The planner skipping partitions that can't contain matching rows (via WHERE on the partition key) — crucial for huge time-series tables."),
("What is a JSONB column and when would you use it?",
 "PostgreSQL's binary JSON — flexible nested data with GIN indexing; use for naturally flexible/occasionally-queried shapes instead of over-splitting schema."),
("What is a database paradigm 'ACID vs BASE'?",
 "ACID = strict consistency; BASE (Basically Available, Soft state, Eventually consistent) = NoSQL's relaxed model for scale — the trade-off spectrum in distributed stores."),
("What is replication and its types?",
 "Copying data to replica DBs: synchronous (strong) vs asynchronous (eventual lag), streaming replication for read scaling and failover."),
("What is a deadlock's resolution strategy?",
 "Consistent lock ordering, timeouts (lock_timeout / innodb_lock_wait_timeout), and DB-level deadlock detection aborting one victim with retry."),
("What is a database connection vs a connection pool size tuning?",
 "Opening a connection is expensive (auth, memory); a pool resizes per workload. Oversized pools waste memory; undersized pools throttle — monitor active/inactive."),
("How do you handle time zones in a DB?",
 "Store TIMESTAMPTZ (UTC), convert on display; never store local time in a TIMESTAMP column — the classic silent-bug."),
],
"03-SQL/01-SQL-Basics": [
("What does SQL stand for and what are its sub-languages?",
 "Structured Query Language. DDL (DEFINE structure), DML (MANIPULATE data), DQL (SELECT), DCL (control access GRANT/REVOKE), TCL (transactions COMMIT/ROLLBACK) — the classification Infosys loves."),
("Write a basic SELECT with WHERE and ORDER BY.",
 "SELECT name, salary FROM employees WHERE department='IT' ORDER BY salary DESC; — read columns, filter rows, order results."),
("What does DISTINCT do?",
 "Removes duplicate rows from the result (SELECT DISTINCT dept FROM emp returns each department once)."),
("What are the arithmetic and comparison operators in SQL?",
 "Arithmetic: + - * / %; comparison: =, <>, !=, <, >, <=, >=, BETWEEN, IN, LIKE, IS NULL — the SQL toolbox for expressions."),
("What is the difference between WHERE and HAVING?",
 "WHERE filters rows before grouping; HAVING filters groups after GROUP BY. WHERE can't reference aggregates; HAVING can (HAVING COUNT(*) > 5)."),
("What is NULL and how does comparison affect it?",
 "NULL means unknown/missing. Comparisons with = are never true (result unknown) — use IS NULL / IS NOT NULL, and COALESCE/NULLIF for safe arithmetic."),
("What is the difference between <= and <> with NULL?",
 "Neither works with NULL: any comparison with NULL yields UNKNOWN and rows are filtered out — the classic 'WHERE col <> 5' missing-NULLs bug."),
("How do you limit the number of rows?",
 "LIMIT n in PostgreSQL/MySQL; TOP n in SQL Server; FETCH FIRST n ROWS ONLY in standard SQL. Combined with ORDER BY to get the 'top N' rows."),
("What is an alias and why is it useful?",
 "Renaming columns/tables in the query (SELECT e.name AS employee_name FROM emp e) for readability and disambiguation in joins/subqueries."),
("Write a query to get the second-highest salary.",
 "SELECT MAX(salary) FROM emp WHERE salary < (SELECT MAX(salary) FROM emp); alternative: ORDER BY salary DESC LIMIT 1 OFFSET 1."),
("What is COALESCE?",
 "Returns the first non-NULL argument from a list — COALESCE(middle_name, 'N/A') gives a default when a value is missing; the ISO standard 'first non-null'."),
("What is the difference between COUNT(*) and COUNT(column)?",
 "COUNT(*) counts all rows; COUNT(column) counts non-NULL values in that column — a subtle but critical SQL distinction."),
("What is the difference between IN and EXISTS?",
 "IN compares against a list/subquery result; EXISTS tests whether rows exist and short-circuits — EXISTS often faster on large correlated subqueries."),
("What is LIKE and its wildcards?",
 "Pattern matching: % matches any number of chars, _ matches exactly one. 'LIKE a%' → starts with 'a'; escape %% when a literal % is needed."),
("What is the difference between UNION and UNION ALL?",
 "UNION combines results and removes duplicates (sorting); UNION ALL keeps all rows (faster). UNION requires matching column counts/types."),
],
"03-SQL/02-JOINs": [
("What is a JOIN and why use it?",
 "Combining rows from two tables based on a related key — the core of relational querying (e.g., join orders to customers on customer_id)."),
("Explain INNER JOIN.",
 "Returns only rows where the join condition matches in both tables — unmatched rows are dropped. SELECT * FROM orders o INNER JOIN customers c ON o.cust_id = c.id."),
("Explain LEFT JOIN (LEFT OUTER).",
 "All rows from the left table, matched rows from the right, NULLs where there's no match. Used to keep 'every customer even without orders'. "),
("Explain RIGHT and FULL (OUTER) JOINs.",
 "RIGHT: all rows from the right table. FULL: all rows from both with NULLs on the missing side — symmetric outer variants."),
("What is a CROSS JOIN?",
 "Cartesian product of both tables — every row of A paired with every row of B; use deliberately for pair-expansion problems."),
("What is a SELF JOIN?",
 "Joining a table to itself — e.g., employees to managers: SELECT e.name, m.name FROM emp e LEFT JOIN emp m ON e.manager_id = m.id. (The classic manager query.)"),
("Write the query 'employees earning more than their manager'.",
 "SELECT e.name FROM emp e JOIN emp m ON e.manager_id = m.id WHERE e.salary > m.salary; — a textbook self-join."),
("What is an equi-join vs non-equi-join?",
 "Equi-join uses = on keys; non-equi-join uses <, >, BETWEEN (e.g., joining salary values into grade ranges)."),
("What is a natural join?",
 "Joins on all columns with equal names automatically (deprecated generally) — avoid in production; explicit ON is clearer and safer."),
("How do you filter with multiple tables efficiently?",
 "Prefer explicit INNER JOIN with ON predicates; always scope columns (t.col) — and keep the join order/cardinality in mind for bigger tables."),
("What is the difference between JOIN ON with WHERE filters?",
 "ON filters rows at the join moment (before producing outer rows); WHERE applies after — for outer joins, WHERE can change which rows survive (e.g., IS NULL) vs ON semantics."),
("How do you join three tables?",
 "Chain joins: FROM a JOIN b ON a.x=b.x JOIN c ON b.y=c.y — the intermediate join must keep the column alignment you rely on."),
("What is a semi-join vs anti-join expressed in SQL?",
 "Semi-join: EXISTS/IN (rows in A that have a match in B, no B columns). Anti-join: NOT EXISTS / NOT IN (rows in A with no match)."),
],
"03-SQL/03-Subqueries": [
("What is a subquery?",
 "A query nested inside another query — in SELECT (scalar), FROM (derived table), or WHERE (IN/EXISTS/comparison). Runs once for uncorrelated, per-row for correlated."),
("What is a correlated subquery?",
 "Refers to the outer row (e.g., WHERE x = outer.x) and re-runs for each outer row — slow if not indexed; EXISTS-style anti/semi-joins benefit."),
("Write a query with a subquery to find employees above average salary.",
 "SELECT name FROM emp WHERE salary > (SELECT AVG(salary) FROM emp); — scalar aggregate subquery."),
("What is a derived table (subquery in FROM)?",
 "A named subquery used as a table: SELECT ... FROM (SELECT dept, AVG(sal) a FROM emp GROUP BY dept) t WHERE a > 100 — must be aliased."),
("What is a CTE (WITH clause) and its benefit?",
 "WITH cte AS (SELECT ...) SELECT ... — a named temporary result set improving readability, modularity, and recursion (WITH RECURSIVE)."),
("When would you use NOT IN vs NOT EXISTS?",
 "NOT EXISTS is usually safer/faster (handles NULLs correctly); NOT IN fails when the subquery contains NULL (result unknown) — a famous trap."),
("What is the difference between IN and EXISTS performance-wise?",
 "Modern optimisers often choose the same plan; historically, IN materialises the list, EXISTS short-circuits per row — test with EXPLAIN rather than guess."),
("How do you write a subquery that returns multiple columns (row subquery)?",
 "WHERE (a,b) = (SELECT x,y FROM ...) — a row-value comparison; supported in PostgreSQL, used for pair-matching."),
("What is the difference between a scalar, table, and row subquery?",
 "Scalar returns one value (usable in expressions); table subquery returns a result set (in FROM); row subquery returns one row with several columns (for row comparisons)."),
("How do you debug a correlated subquery?",
 "Break it down: run the inner query with a fixed outer value; confirm indexes on the correlation column; then reintroduce the outer loop."),
],
"03-SQL/04-Window-Functions": [
("What is a window function?",
 "Computes a value across a set of rows (the window) related to the current row WITHOUT collapsing them into groups — ROW_NUMBER, RANK, SUM() OVER(...) etc."),
("What is OVER and PARTITION BY?",
 "OVER defines the window; PARTITION BY splits rows into partitions per key; the function computes per partition while each row remains in the result."),
("What is ORDER BY inside a window (frame)?",
 "ORDER BY defines the row order within a partition and default frame (ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW for running aggregates)."),
("What is ROW_NUMBER vs RANK vs DENSE_RANK?",
 "ROW_NUMBER gives unique sequential numbers even for ties; RANK gives equal ties with gaps; DENSE_RANK gives equal ties without gaps (1,2,2,3 vs 1,2,2,4)."),
("What is NTILE?",
 "Divides the partition into N buckets of as-equal-as-possible size; NTILE(4) assigns 1-4 per row — used for quartile analysis."),
("What is LAG and LEAD?",
 "Access a row's value n positions before (LAG) or after (LEAD) in the ordering — for trends and differences (price vs previous day)."),
("What is the difference between aggregate with GROUP BY and window?",
 "GROUP BY collapses rows to one per group; window keeps every row and attaches the computed value — the one-line distinction to state first."),
("Write a query for the nth highest salary using a window.",
 "SELECT DISTINCT salary FROM (SELECT salary, DENSE_RANK() OVER (ORDER BY salary DESC) r FROM emp) t WHERE r = 2;"),
("What is a frame clause (ROWS vs RANGE)?",
 "ROWS counts actual rows; RANGE aligns by value (peers). Default frame with ORDER BY is RANGE UNBOUNDED PRECEDING TO CURRENT ROW — a gateway to subtle bugs."),
("How do window functions solve running totals?",
 "SELECT date, amount, SUM(amount) OVER (ORDER BY date) FROM txn; — the running total per row."),
("When doesn't a window function help?",
 "When the value depends only on a group arrow the GROUP BY/aggregate is the right tool, or when overall percentiles need NTILE/PERCENT_RANK but the query shape favours joins."),
],
"03-SQL/05-Group-By-and-Aggregation": [
("What does GROUP BY do?",
 "Collapses rows into groups sharing the same values of the listed columns; aggregates then compute per group (COUNT, SUM, AVG, MIN, MAX)."),
("Write 'count of employees per department'.",
 "SELECT dept, COUNT(*) FROM emp GROUP BY dept; — the canonical aggregating query."),
("What is the rule about selecting non-aggregated columns?",
 "In strict SQL, columns in SELECT must be in GROUP BY or wrapped in aggregates (PostgreSQL enforces this) — picking a bare non-grouped column is invalid."),
("What is HAVING vs WHERE again?",
 "WHERE filters pre-group rows; HAVING filters post-aggregation groups — use HAVING COUNT(*) > 3 or HAVING AVG(sal) > 4000."),
("Write departments whose average salary is above 50000.",
 "SELECT dept, AVG(salary) a FROM emp GROUP BY dept HAVING a > 50000;"),
("How do you count distinct values per group?",
 "GROUP BY col; SELECT COUNT(DISTINCT other_col) — distinct counted within the group."),
("What is the difference between GROUP BY and PARTITION BY?",
 "GROUP BY collapses rows; PARTITION BY (window) preserves rows while computing per group — a favourite clarifying question."),
("How do you get the department with the maximum total salary?",
 "SELECT dept FROM emp GROUP BY dept ORDER BY SUM(salary) DESC LIMIT 1; — aggregate then order."),
("What is the order of execution in a SQL query?",
 "FROM/JOIN → WHERE → GROUP BY → HAVING → SELECT → DISTINCT → ORDER BY → LIMIT — knowing this lets you reason about which clause can use which expression."),
("How do you handle NULLs in aggregates?",
 "COUNT(col) ignores NULLs; SUM/AVG ignore NULLs but AVG over all-NULL returns NULL; COALESCE before aggregating when a default is needed."),
],
"03-SQL/06-DDL-DML-DCL": [
("What is DDL? Name the commands.",
 "Data Definition Language: CREATE, ALTER, DROP, TRUNCATE, RENAME — defines and manages schema objects. Auto-commits in many DBs."),
("What is DML? Name the commands.",
 "Data Manipulation Language: INSERT, UPDATE, DELETE — manipulates data inside tables, filterable and transactional (WHERE clauses apply)."),
("What is DQL?",
 "Data Query Language: SELECT — reads data; often grouped with DML for convenience but formally separate."),
("What is DCL and TCL?",
 "DCL: GRANT/REVOKE (permissions). TCL: COMMIT, ROLLBACK, SAVEPOINT — transaction control."),
("Write an INSERT and an UPDATE.",
 "INSERT INTO emp(name, dept) VALUES ('Aayush','AI'); UPDATE emp SET salary = 100 WHERE name='Aayush'; — the two bread-and-butter DML statements."),
("What is the difference between UPDATE and DELETE with a WHERE missing?",
 "UPDATE without WHERE changes EVERY row; DELETE without WHERE deletes ALL rows — the DML foot-guns. Always validate predicates."),
("What happens on an ALTER TABLE ADD column?",
 "Schema change adds a column (default fill per rules); existing rows get NULL (or the DEFAULT); the table's structure is altered — a DDL statement."),
("How do you drop a table with cascading?",
 "DROP TABLE orders CASCADE (PostgreSQL) drops dependent objects (views/FKs) too; WITHOUT CASCADE it errors when dependencies exist."),
("What is the difference between DELETE and TRUNCATE for auto-increment?",
 "TRUNCATE resets the auto-increment counter and is faster; DELETE keeps the counter where it is (gap continues) — a practical DDL/DML distinction."),
("How do you grant and revoke privileges?",
 "GRANT SELECT ON emp TO alice; REVOKE SELECT ON emp FROM alice; — the DCL pair governing who can do what on which object."),
],
"03-SQL/07-Advanced-SQL": [
("What is a recursive CTE?",
 "WITH RECURSIVE cte AS (base UNION ALL recursive-step) — builds trees, hierarchies, and series in SQL. The classic example: employees up the reporting chain."),
("Write a recursive CTE for a number series.",
 "WITH RECURSIVE t(n) AS (VALUES (1) UNION ALL SELECT n+1 FROM t WHERE n < 10) SELECT n FROM t; — materialises 1..10."),
("What is a PIVOT/unpivot?",
 "Rotating rows into columns (PIVOT) or columns into rows (UNPIVOT); PostgreSQL uses FILTER/conditional aggregation — SELECT ... SUM(CASE WHEN ...) for pivot-in-SQL."),
("What is the difference between GROUPING SETS, CUBE, ROLLUP?",
 "ROLLUP produces hierarchical subtotals, CUBE all combinations, GROUPING SETS explicit subsets — SQL analytics for totals and subtotals."),
("What is a LATERAL join?",
 "A correlated FROM-subquery that can reference the join's left side row-by-row: FROM orders o, LATERAL (SELECT ... WHERE ... o.id) x — powerful for per-row computations."),
("What is the MERGE (UPSERT) statement?",
 "MERGE INTO/INSERT ... ON CONFLICT (col) DO UPDATE inserts or updates deterministically — PostgreSQL's UPSERT pattern avoids race-prone check-then-write."),
("How do you select rows with the latest timestamp per group?",
 "DISTINCT ON (group) ... ORDER BY group, timestamp DESC (PostgreSQL) or ROW_NUMBER() OVER (PARTITION BY ...): the window version is standard SQL."),
("What is the difference in reading JSONB operators?",
 "->> extracts text, -> extracts JSON, @> containment, ? exists — PostgreSQL's JSON operations for semi-structured queries."),
("Write a query to remove duplicate rows keeping one.",
 "DELETE FROM emp WHERE id NOT IN (SELECT MIN(id) FROM emp GROUP BY name, dept); — keep one per group: the classic dedupe cleanup."),
("What is EXPLAIN ANALYZE and what does it tell you?",
 "Shows the chosen execution plan with actual rows/time — a sequence scan vs index scan, join method, and filter estimates — the first step to optimisation."),
],
"03-SQL/08-SQL-Optimization": [
("List the common causes of slow queries.",
 "Missing/inefficient indexes, table scans on large tables, SELECT *, heavy joins without stats, functions on indexed columns, the N+1 pattern, and lock contention."),
("How do you improve a slow SELECT?",
 "Add covering/sargable indexes, rewrite predicates to use them, avoid functions on columns (WHERE sal*2 vs WHERE sal), reduce columns returned, and check the query plan."),
("What is sargability?",
 "A predicate is sargable when the indexed column stands alone (col = ?, col >= ?); wrapping it (YEAR(col) = 2024 or col+1 = x) disables the index — a favourite optimisation answer."),
("What is an index's role in ORDER BY?",
 "An index matching the ORDER BY columns lets the planner return rows already sorted — avoiding a sort phase; covering indexes make it even cheaper."),
("What is a query cache as opposed to an index?",
 "Database/main tools caching result sets or query plans, bypassing reprocessing — differs from indexes (storage structures speeding reads). Only prudent when staleness is acceptable."),
("How does SELECT * hurt performance?",
 "Brings unneeded columns → wider scans, more I/O, breaks covering indexes, and hard-codes schema — always select only needed columns."),
("How do you reduce JOIN cost?",
 "Index the join keys (FKs), filter early with WHERE, keep the join order from small to large, and use exists that prevents oversized intermediate results."),
("What is the effect of a high page miss on prepares?",
 "Repeated identical queries benefit from prepared statements/plan caching — the DB skips planning; for dynamic predicates re-plans keep stats current."),
("When is a full table scan acceptable?",
 "Small tables, or predicates matching most rows (a full scan beats an index whose selectivity is low) — the planner decides; forcing with hints is an anti-pattern."),
("How do you test the improvement?",
 "EXPLAIN ANALYZE before/after with the same parameters and dataset — compare actual time and rows; verify the index is used and not just created."),
],
"03-SQL/09-Complex-Queries": [
("Write a query to find departments with fewer than 3 employees.",
 "SELECT dept FROM emp GROUP BY dept HAVING COUNT(*) < 3; — group + having aggregates."),
("Write a query for the running total per customer ordered by date.",
 "SELECT customer_id, amount, SUM(amount) OVER (PARTITION BY customer_id ORDER BY date) running FROM txn;"),
("Find employees who joined in the last 6 months.",
 "SELECT * FROM emp WHERE join_date >= CURRENT_DATE - INTERVAL '6 months'; — date arithmetic in PostgreSQL."),
("Find customers who never placed an order.",
 "SELECT c.id FROM customers c LEFT JOIN orders o ON c.id = o.cust_id WHERE o.id IS NULL; — the anti-join via LEFT JOIN."),
("Write a query to get the top 3 earners per department.",
 "SELECT name, dept, salary FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary DESC) r FROM emp) t WHERE r <= 3;"),
("Write a single query that groups by both month and department.",
 "SELECT dept, EXTRACT(MONTH FROM date) mon, COUNT(*) FROM sales GROUP BY dept, mon ORDER BY dept, mon; — multi-column grouping."),
("How do you compute the month-over-month growth rate?",
 "WITH monthly AS (SELECT date_trunc('month', d) m, SUM(amt) s FROM sales GROUP BY 1) SELECT m, s, (s - LAG(s) OVER (ORDER BY m)) / LAG(s) OVER (ORDER BY m) FROM monthly;"),
("Write a query using a CASE to bucket ages.",
 "SELECT CASE WHEN age < 18 THEN 'minor' WHEN age < 60 THEN 'adult' ELSE 'senior' END bucket, COUNT(*) FROM people GROUP BY 1;"),
("Find products ordered at least 5 times.",
 "SELECT product_id, COUNT(*) c FROM order_items GROUP BY product_id HAVING c >= 5;"),
("Write a semi-join for employees whose manager is also an employee.",
 "SELECT e.name FROM emp e WHERE EXISTS (SELECT 1 FROM emp m WHERE m.id = e.manager_id); — the EXISTS anti-semi-join pattern."),
],
"03-SQL/10-SQL-Interview-Problems": [
("Write a query to find duplicate emails/records.",
 "SELECT email, COUNT(*) FROM users GROUP BY email HAVING COUNT(*) > 1; — the exact Infosys duplicate-records question."),
("Write a query for the nth highest salary using OFFSET.",
 "SELECT DISTINCT salary FROM emp ORDER BY salary DESC LIMIT 1 OFFSET 2; — for the 3rd highest (n-1 offset)."),
("How do you find people with the same name?",
 "SELECT name, COUNT(*) FROM emp GROUP BY name HAVING COUNT(*) > 1; — group-count then filter on count."),
("Write a query to update salary with a percentage hike only for a department.",
 "UPDATE emp SET salary = salary * 1.10 WHERE dept = 'Engineering'; — transaction-worthy DML."),
("Find departments with above-average headcount.",
 "SELECT dept, COUNT(*) c FROM emp GROUP BY dept HAVING c > (SELECT AVG(c2) FROM (SELECT COUNT(*) c2 FROM emp GROUP BY dept) t); — group + subquery."),
("Write a query to rank students by score.",
 "SELECT student, score, RANK() OVER (ORDER BY score DESC) FROM results; — window ranking."),
("How do you list employees and their managers (including those without)?",
 "SELECT e.name, m.name AS manager FROM emp e LEFT JOIN emp m ON e.manager_id = m.id; — self-outer-join."),
("Write a query to delete rows older than a year.",
 "DELETE FROM logs WHERE created_at < NOW() - INTERVAL '1 year'; — date-based DML with a transaction wrapping."),
("Find the total spent per customer with at least one order.",
 "SELECT c.id, COALESCE(SUM(o.amount),0) FROM customers c LEFT JOIN orders o ON o.cust_id = c.id GROUP BY c.id HAVING COUNT(o.id) > 0;"),
("Write a query to transpose department counts into columns.",
 "SELECT SUM(CASE WHEN dept='HR' THEN 1 ELSE 0 END) hr, SUM(CASE WHEN dept='IT' THEN 1 ELSE 0 END) it FROM emp; — pivot via conditional aggregates."),
],
}