"""Curated Q&A for 06-DevOps (Docker, Git, CI-CD, Linux)."""
DEVOPS = {
"01-Docker/01-Docker-Basics": [
("What is Docker?",
 "A containerisation platform packaging an app + its dependencies/images into isolated, reproducible units that run anywhere Docker does."),
("What is a container vs a virtual machine?",
 "Container: shares the host kernel, process-level isolation, MB-sized, seconds to start. VM: full guest OS on a hypervisor, GB-sized, heavier — containers are lighter and more portable."),
("What is an image vs a container?",
 "An image is the immutable build artifact (layers + config); a container is a running instance of that image with its own writable layer."),
("What are the benefits of containerisation?",
 "Reproducibility (same image everywhere), dependency isolation, resource efficiency vs VMs, and standardised deploy targets for CI/CD."),
("What are the core Docker concepts?",
 "Image, container, Dockerfile, registry (Docker Hub), volume, network, docker-compose — the vocabulary for every Docker interview."),
("How does Docker isolation work at a low level?",
 "Linux namespaces (PID, net, mount, user...) + cgroups (CPU/memory limits) + union filesystems (layer sharing) — the kernel primitives under the hood."),
("What is the lifecycle of a Docker container?",
 "Created -> running -> paused -> stopped (exit) -> removed; docker run creates+starts; rm cleans up on exit."),
("What is the difference between docker run, start, and exec?",
 "run creates from an image and starts; start restarts an existing container; exec runs a command inside a running container — the operational three."),
("What is a Docker registry?",
 "A store for images (Docker Hub or private); docker pull/push moves them; image names encode registry/repo/tag (user/app:tag)."),
("What is the container port mapping?",
 "-p host:container binds the host port to the container's internal port — making services reachable; networking inside is isolated otherwise."),
("What is Docker's 'everything immutable, state external' rule?",
 "Containers are disposable — writes are lost unless mounted as volumes; persistence belongs in volumes/DBs, not the container filesystem."),
],
"01-Docker/02-Dockerfile": [
("What is a Dockerfile and its key instructions?",
 "The build recipe: FROM (base), WORKDIR, COPY, RUN (build-time), ENV, EXPOSE, CMD/ENTRYPOINT — a declarative image definition."),
("What is the difference between CMD and ENTRYPOINT?",
 "ENTRYPOINT is the fixed process (can't be overridden casually); CMD supplies default args — combine (ENTRYPOINT + CMD) for a default-and-overridable command."),
("How do you build and tag an image?",
 "docker build -t myapp:1.0 . — the build context (.) is sent to the daemon; tag format repo:tag for registry push."),
("How do you pass build-time vs runtime config?",
 "ARG for build-time (FROM versions, build args), ENV for runtime; different use cases and caching implications."),
("What is a multi-stage build and why use it?",
 "Chaining FROM statements: one stage compiles (huge toolchains), the final stage copies only artifacts into a slim runtime image — dramatically smaller, safer images."),
("Why is the order of instructions important for layer caching?",
 "Docker caches layers; COPY requirements.txt before the rest, then RUN pip install — so dependency installs cache unless requirements change; frequent-changers last."),
("What makes an image slim?",
 "Slim base (python:slim/distroless/scratch), multi-stage builds, removing caches (pip --no-cache-dir apt lists), and non-root users — the size-optimisation checklist."),
("What is the best practice of running as non-root?",
 "USER appuser in the Dockerfile — containers running as root escalate host risk; security best practice shouted at interviews."),
("How do you handle secrets at build vs runtime?",
 "Never bake secrets into images — build args/COPY embed them, leaking in layers; inject via env/compose/K8s secrets at runtime."),
("What is a healthcheck instruction?",
 "HEALTHCHECK CMD tells Docker to probe the app (curl/health endpoint) — orchestrators/LB decide readiness from the result."),
("What is .dockerignore and why is it critical?",
 "Excluding .git, venv, __pycache__, caches from the build context — faster builds, smaller contexts, and no accidental secret copying."),
("What is the difference between RUN vs CMD in building the app?",
 "RUN executes during build (results become layers); CMD runs at container start — confusion here is a classic Docker interview trap."),
],
"01-Docker/03-Docker-Compose": [
("What is docker compose?",
 "A YAML orchestration file (docker-compose.yml) defining multi-container apps — services, networks, volumes — with one `docker compose up`."),
("How do you define a service in compose?",
 "services: {name: {image or build, ports, env, volumes, depends_on, healthcheck}} — the declarative unit of the app."),
("What is the difference between image and build in a service?",
 "image pulls a ready artifact; build builds from a Dockerfile (context) — combine build + image to use the built tag."),
("How does compose networking work?",
 "An implicit bridge network lets services resolve each other by service name (myapi) — internal DNS instead of IP juggling."),
("How do volumes persist in compose?",
 "Named volumes (declared under volumes:) survive container recreation; bind mounts (./host:path) share host files — the persistence mechanism."),
("How do you set environment/config in compose?",
 "environment: inline vars, env_file: for files, and ${VAR} interpolation — externalising config without editing YAML per env."),
("What does depends_on do vs health gates?",
 "depends_on orders start; real readiness needs condition: service_healthy with healthchecks — start-order isn't app-readiness."),
("What is the difference between compose for dev and prod?",
 "Dev: bind mounts for live reload + debug ports. Prod: built images, healthchecks, restarts — separate compose files override with -f."),
("How do you scale a compose service?",
 "docker compose up --scale api=3 (with ports mapped) — simple horizontal scaling for dev-stage, but production scale is orchestration (K8s) territory."),
("How do you tear down without losing data?",
 "docker compose down removes containers/networks; --volumes wipes named volumes — associate persistence with volume declarations."),
("How would you compose an AI stack?",
 "Services: API (FastAPI), Postgres, Redis, and a vector DB (Chroma) — each with healthchecks and internal-network links; the exact local RA stack."),
],
"01-Docker/04-Advanced-Docker": [
("What is Docker networking — bridge, host, none?",
 "bridge (default, NAT isolation), host (shared host network), none (isolated), plus overlay for swarm — choose per exposure needs."),
("What is Docker volume vs bind mount?",
 "Volumes: managed, portable, stored by Docker. Bind mounts: host path mounted directly (dev). Volumes win for prod data; binds for config dev."),
("What is an ephemeral vs persisted container?",
 "Ephemeral: all config/state passed in, safe to recreate. Persisted: volumes house DB/upload data — the stateless-container principle in practice."),
("What is the Docker lifecycle for garbage collection?",
 "docker system prune (dangling images/containers/networks) and volume prune — housekeeping that keeps hosts from filling up."),
("What are the resource limits you can impose?",
 "--memory, --cpus, and runtime quotas enforce a container's cgroup limits — preventing one app starving the host."),
("What is Docker's relationship to Kubernetes?",
 "Docker builds/run containers; K8s orchestrates them across nodes — scheduling, service discovery, scaling, self-healing; the packaging vs platform distinction."),
("What is containerd/runc and where do they sit?",
 "runc creates containers from OCI specs; containerd is the daemon managing runc; Docker uses both underneath — the modern runtime stack."),
("How do you optimise docker build caching?",
 "Layer order, multi-stage, and BuildKit features (cache mounts for pip) — hitting the cache avoids re-downloading dependencies every build."),
("What is BuildKit?",
 "The modern Docker build engine — parallel stages, better caching, SSH/secret mounts, and provenance; enabled by default in Docker 23+."),
("What is the security surface of Docker?",
 "Non-root users, read-only rootfs, minimal images, secret handling, registry trust, and SBOM — from OS hardening to supply-chain hygiene."),
("What is docker diff and debugging a container?",
 "docker exec -it container sh (inspect), docker logs (stdout), and docker top/inspect — the diagnosing toolkit when something misbehaves."),
],
"02-Git/01-Git-Basics": [
("What is Git and how does it track history?",
 "A distributed version control system storing snapshots of the repository tree as commits — immutable history, each sha-1 pointing to tree+parent(s)."),
("What is a commit?",
 "A snapshot (tree hash + parent + author/message) — your atomic 'saved state'; amend/rebasing rewrites only unpublished history."),
("What is the difference between working directory, staging, and repository?",
 "Working tree: your files. Staging (index): files `git add`-ed for the next commit. Repository: committed history — the three-state model."),
("What is git add, commit, and status?",
 "add stages changes, commit records a snapshot with a message, status shows what's modified/staged/untracked — the daily trio."),
("What is a HEAD?",
 "A pointer to the current commit/branch — your working position; moving it (checkout/reset) changes what you see and commit onto."),
("What is a remote and how do you interact?",
 "Remote repositories (origin) — clone pulls, push sends commits, fetch pulls without merging, pull = fetch+merge — the sync vocabulary."),
("What is the duty of .gitignore?",
 "Patterns telling Git to exclude untracked junk (venv, caches, .env, build/) — keeping the repo clean and secrets out."),
("What is git log and reading history?",
 "git log --oneline --graph shows the commit DAG; blame/reflog reveal who changed what and recovery paths."),
("What does git diff show?",
 "Uncommitted differences (working vs index) or commit-to-commit changes — the review surface before staging."),
("What is the difference between git status and git log?",
 "status = working/staging state; log = committed history — living changes vs recorded history."),
("What is a detached HEAD and how dangerous is it?",
 "Checking out a raw commit leaves HEAD detached; new commits become unreachable — fine to inspect, recover via a branch name is the safe pattern."),
],
"02-Git/02-Branching": [
("What is a branch in Git?",
 "A movable pointer to a commit — cheap, lightweight parallel lines of work; the mechanism of feature isolation and teamwork."),
("What is the difference between a branch and a tag?",
 "Branch: evolving pointer moving with commits. Tag: immutable label on a commit (release v1.0) — time-travel markers vs moving lines."),
("What is the checkout vs switch?",
 "git checkout changes branches/history position; git switch (newer) only changes branches — cleaner separation of concerns."),
("What is the main/master convention?",
 "The default stable line; feature branches diverge and merge back — the trunk-and-branches shape of most projects."),
("What are the common branching strategies?",
 "GitFlow (develop/release/hotfix branches), GitHub Flow (short-lived feature branches to main), trunk-based (stack on main continuously) — choose by release cadence."),
("How do you create, list, merge and delete a branch?",
 "git branch name, git branch -a, git merge name, git branch -d name — the branch lifecycle commands."),
("What is the difference between a local and remote-tracking branch?",
 "Local: your line of work. remote-tracking (origin/main): cached remote position — push/pull sync them; branches disappear remotely without syncing."),
("How do you pick a good branch name?",
 "feature/login-flow, fix/payment-timeout — type/name conventions make history navigable and CI matching simple."),
("What happens when you switch branches with uncommitted changes?",
 "Git keeps them if they don't conflict; otherwise you must stash/commit first — the two common friction points of switching."),
("What is git stash?",
 "Temporarily shelving uncommitted changes (git stash pop to restore) — the 'I need to switch but not lose work' tool."),
("What is the danger of long-lived branches?",
 "Divergence → merge pain, integration surprises, and unreviewed drift — short-lived, frequently-integrated branches keep conflicts small."),
],
"02-Git/03-Merging-and-Rebasing": [
("What is merging in Git?",
 "Combining branches by creating a merge commit (or fast-forward) that reconciles the histories — history shows the branch topology."),
("What is a merge conflict and how do you resolve it?",
 "Both branches changed the same lines — Git marks <<<<<<< / ======= / >>>>>>> blocks; you edit, decide, git add + commit the resolution."),
("What is fast-forward merging?",
 "When the target branch hasn't moved, merging just moves its pointer forward — linear history without a merge commit; --no-ff forces a record instead."),
("What is rebasing?",
 "Re-applying one branch's commits on top of another's tip — a clean linear history at the cost of rewritten commit IDs (never rebase shared history)."),
("What is the difference between merge and rebase?",
 "Merge preserves topology with a merge commit (safe for shared branches); rebase flattens into a linear story (clean, but rewrites order/IDs)."),
("What is cherry-picking?",
 "Applying a single commit from elsewhere onto the current branch without bringing the whole history — targeted hotfix transfer."),
("What is git revert vs reset?",
 "revert creates an inverse commit (safe, keeps history, good for public branches); reset moves HEAD backwards discarding commits (rewrites — private/feature only)."),
("What is the golden rule of rebasing?",
 "Never rebase commits you've pushed/shared — rewriting public history breaks collaborators; revert instead on shared branches."),
("How do you resolve a conflict during a rebase?",
 "Stop, edit conflicted files, git add, then git rebase --continue — or --abort to bail out; each step re-applies the next commit."),
("What is an interactive rebase used for?",
 "git rebase -i lets you reorder, squash, fixup, or reword local commits — cleaning a messy feature branch before merge."),
("What is squash merging?",
 "--squash collapses all feature commits into one on merge — concise history at the cost of loss of the detailed journey."),
],
"02-Git/04-Advanced-Git": [
("What is the git object model?",
 "blobs (file content), trees (directories), commits (snapshots), tags — hashed by content; everything recoverable from the hashes."),
("What is the git reflog?",
 "A local log of WHERE HEAD has been — the rescue tool to recover after a reset/rebase mishap; it's your undo for nearly everything."),
("What does git reset --soft vs --mixed vs --hard do?",
 "--soft: move HEAD, keep staged; --mixed (default): move HEAD, keep working files unstaged; --hard: discard everything — the danger ladder."),
("What is git bisect?",
 "Binary-search through history to find the commit that introduced a bug (git bisect start + good/bad + run) — a superpower for regressions."),
("What is a submodule and its issues?",
 "A git repository pinned inside another — separating dependency repos, but updates/version-skew and cloning friction are notorious."),
("What is git worktree?",
 "Multiple working directories for the same repo (a branch each) — parallel builds/hotfix contexts without stashing churn."),
("What is hooking — pre-commit?",
 "Client-side hooks (commit-msg, pre-push) automate lint/format checks before commit; husky/pre-commit frameworks manage them."),
("What is signing commits (GPG)?",
 "Signing verifies you authored the commit — supply-chain trust; GitHub flags verified status for signed commits."),
("What is shallow cloning and its cost?",
 "--depth 1 fetches only the latest snapshot — fast CI clones, but no full history for blame/branches (mitigated by --depth+--no-single-branch when needed)."),
("What is a bare repository used for?",
 "A repo without a working tree (git init --bare) — the server-side storage for hosts; you push to it, never edit in it."),
("What is git gc and why does it run?",
 "Garbage collecting unreachable objects packing efficiency — automatically triggered; manual gc --aggressive cleans pathological repos."),
],
"03-CI-CD/01-GitHub-Actions": [
("What is GitHub Actions?",
 "GitHub's CI/CD platform running jobs from YAML workflows in .github/workflows — triggers on push/PR, on a schedule, or manually."),
("What is a workflow vs a job vs a step?",
 "Workflow: the YAML file. Jobs: parallel stages on runners. Steps: sequential commands within a job — the three-level hierarchy."),
("What are events and how do you trigger workflows?",
 "push, pull_request, schedule (cron), workflow_dispatch (manual), and paths/branches filters — trigger precision avoids CI noise."),
("What is a matrix build?",
 "Testing across OS/python-version combinations (matrix: {'os': [...], 'python': [...]}) — parallel coverage of versions."),
("What are actions and where do they come from?",
 "Reusable composites (checkout, setup-python) from the Marketplace; you can also inline run: steps or publish your own action."),
("How do you pass secrets and environment to jobs?",
 "secrets.X from repo/org settings (never printed), env: per-job variables, and concurrency to cancel stale runs — secret hygiene is the core skill."),
("What is a cache in Actions?",
 "actions/cache persists pip/uv caches between runs — cutting install time from minutes to seconds; the speed win every pipeline needs."),
("How do you run tests and lint in CI?",
 "steps: install deps -> run pytest -> upload coverage — any red job fails the build; quality gates wired into the merge path."),
("How do you build and push an image in CI?",
 "docker/login-action + build-push-action with tags derived from the ref and version — the containerised release path."),
("What is a workflow_dispatch vs scheduled trigger?",
 "manual vs cron — the two 'not every push' flavours you'll add for deploys and nightly jobs."),
("How do you deploy from Actions?",
 "After tests pass: SSH/cloud-deploy action or kubectl/helm — the CD half of CI/CD, with environment protection rules on main."),
],
"03-CI-CD/02-Pipeline-Design": [
("What is a CI/CD pipeline?",
 "An automated series of stages: lint -> test -> build -> package -> deploy, run on every change — shipping small, verified increments."),
("What are the stages of a typical pipeline?",
 "1) Checkout 2) Lint/format 3) Unit tests 4) Build artifacts/images 5) Integration/e2e 6) Deploy to env — each gate before promotion."),
("What is the difference between CI and CD?",
 "CI: integration/verification on every commit (tests, builds). CD: deployment automation after CI passes — continuous delivery (staged) vs continuous deployment (auto-prod)."),
("What are the top pipeline quality gates?",
 "Lint, unit tests, coverage thresholds, dependency audit (pip-audit/dependabot), and image scanning — failing early is the point."),
("How do you handle failing pipelines?",
 "Fast feedback messages, flaky-test quarantining, and required-checks on merge — red pipelines are the team's canary, not a nuisance."),
("What are environment promotion rules?",
 "Dev -> staging -> prod with approvals at boundaries; secrets per environment; immutable versioned artifacts move up, not rebuilds."),
("What is the difference between a build and a release?",
 "Build: compiler/container artifact. Release: a tagged, immutable, deployable instance of a build (semver + changelog)."),
("What is trunk-based vs feature-branch CI?",
 "Trunk: everyone merges to main frequently, CI runs on every commit — smaller diffs, less merge pain. Feature branches: longer-lived, larger merges."),
("How do you make pipelines fast?",
 "Caching, parallelism (independent stages), and only run the checks affected — CI velocity is the developer-experience metric."),
("What is the value of pipeline-as-code?",
 "Versioned YAML with reviewable diffs — configuration follows the same review/rollback discipline as application code."),
("How would you pipeline a Python ML project?",
 "Lint+pytest, train-validation step, model packaging, and a deploy step with model-version metadata — every step's artifacts tracked immutably."),
],
"03-CI-CD/03-Deployment-Strategies": [
("What are the deployment strategies?",
 "Recreate, rolling, blue/green, canary, and feature-flag/shadow — each trades deploy risk against speed and infrastructure cost."),
("What is a rolling deploy?",
 "Instances upgrade one-by-one while the service stays up — simple, no extra capacity, but partial-incompatibility window during the roll."),
("What is blue/green deployment?",
 "Two full environments; switch traffic atomically on the new (green) set — instant rollback to blue, at the cost of doubled capacity."),
("What is a canary deployment?",
 "Sending ~5-10% of traffic to the new version, watching metrics, then ramping to 100% — incremental trust with real-world verification."),
("What is the rollback strategy and how does it work?",
 "Every deploy should roll back: previous image is one command away; automated rollback triggers on error-rate/health degradation."),
("What is a zero-downtime deploy?",
 "Combining readiness probes/before-registration with rolling or blue-green so users never see 503s — the availability standard for production paths."),
("What is database migration's special deploy risk?",
 "Schema changes must be additive/backwards-compatible (expand-contract); deploys and migrations sequence separately to avoid breaking running versions."),
("What is immutable infrastructure?",
 "Servers/containers are never patched in place — deployments replace them wholesale with new images; drift is impossible by construction."),
("What is a feature flag and why does it decouple deploys?",
 "Code ships dormant behind flags, toggled at runtime — releasing features without redeploying and enabling instant kill-switches."),
("What is a shadow deploy?",
 "Writing the new version side-by-side, mirroring traffic without acting on it — comparing behaviour before exposing users (an advanced technique)."),
("What metrics gate a deploy?",
 "Error rate, latency percentiles, CPU, and business metrics — auto-rollback thresholds are set before, not after, the deploy."),
],
"04-Linux/01-Linux-Basics": [
("What is Linux and its architecture?",
 "An open-source OS with a kernel managing hardware, scheduling, and system calls; user-space tools (GNU coreutils) sit on top — the server OS of choice."),
("What are the most common Linux commands?",
 "ls, cd, pwd, cp, mv, rm, mkdir, grep, find, chmod, ps, top, ssh — the everyday toolbox everyone must rattle off."),
("What is the difference between absolute and relative paths?",
 "Absolute: /home/user/file, from root. Relative: ../file, from cwd — the path semantics of navigation."),
("What is the directory structure (/bin, /etc, /var)?",
 "/bin binaries, /etc config, /var variable logs/data, /home users, /tmp temp, /proc virtual-kernel files — the FHS layout maps."),
("What are file permissions and how do you change them?",
 "r/w/x per owner/group/other as octal (755); chmod sets them, chown changes ownership — the access-control basics."),
("What is the difference between a hard link and symlink in Linux?",
 "Hard link: additional name for the same inode. Symlink: a shortcut path (may break). ln file hard, ln -s target sym — reuses the OS concepts."),
("What is stdout, stdin, stderr?",
 "Standard streams: input (0), output (1), error (2); redirect with >, >>, 2>, and pipe with | — the shell plumbing."),
("What does grep find?",
 "Text search in files/streams: grep pattern file, -i ignore case, -r recursive — the pattern-matching reviewer."),
("What is the difference between find and grep?",
 "find locates files by name/type/time; grep searches content of files — two different axes of the filesystem."),
("How do you check disk space, memory, CPU?",
 "df -h (disks), free -h (RAM), top/htop (live processes), uptime (load) — the health-check command quartet."),
("What is a package manager?",
 "apt/yum/dnf install, update, and remove software from repos — the dependency management of the OS itself."),
("How do you edit/search history in the shell?",
 "history, !! (last), ctrl-r reverse search — shell productivity, the fastest editing shortcuts."),
],
"04-Linux/02-Shell-Scripting": [
("What is a shell script and its shebang?",
 "A text file of shell commands with #!/bin/bash on top — executable after chmod +x; scripting the OS."),
("What is the difference between bash and sh?",
 "sh is the POSIX baseline; bash adds arrays, [[ ]], process substitution; on Linux bash is the default interactive shell — write POSIX for mobility."),
("How do you define and use variables?",
 "myvar='value' (no spaces!), reference with $myvar or ${myvar}; $(cmd) captures command output — assignment/pipeline basics."),
("What is a conditional in bash?",
 "[ condition ] or [[ ... ]] with -gt/-eq/-f/-d tests; if/then/elif/else/fi — file and numeric logic of the shell."),
("What is a for loop over files?",
 "for f in *.txt; do echo \"$f\"; done — iterating lists including globs; the batch-operation idiom."),
("What is the difference between $@ and $*?",
 "Both are script arguments; '$@' preserves each argument's boundaries, '$*' joins them into one string — quoting matters."),
("What is exit status and $??",
 "Every command exits 0 (success) or non-zero; $? holds the last status; set -e exits the script on any failure — error propagation control."),
("What is the difference between && and ;?",
 "cmd1 && cmd2 runs cmd2 only if cmd1 succeeds; cmd1; cmd2 always runs cmd2 — conditional chaining vs sequential."),
("What is a function in a shell script?",
 "name() { commands; } — reusable blocks; exit vs return differentiate the shell-level from the function-level result."),
("What is redirection in a script?",
 "> file, >> append, 2> err, 2>&1 merge; pipe | chains stdout to the next command — directing data flow precisely."),
("What are the pitfalls of quoting in bash?",
 "Unquoted $var splits on whitespace/globs; \"$var\" preserves it as one word — the most common script bug, worth pointing out explicitly."),
],
"04-Linux/03-Process-Management": [
("What is a process in Linux?",
 "A running program instance with PID, state, and address space — listing ps aux shows every one; the OS-process concepts applied."),
("What is the difference between ps and top?",
 "ps is a static snapshot; top/htop is live, updating CPU/memory per process — diagnose-at-a-moment vs observe-over-time."),
("What is a daemon?",
 "A background process detached from terminals, started at boot (systemd units) — persistent services like web servers and DBs."),
("How do you manage processes (kill)?",
 "kill PID sends a signal (SIGTERM graceful, SIGKILL force, SIGSTOP pause); pkill / killall match by name — the terminate vocabulary."),
("What is the difference between foreground and background jobs?",
 "Foreground occupies the terminal; background (cmd &) returns it; jobs/fg/bg manage them — the job-control model."),
("What is a process tree and parent/child?",
 "Every process has a parent (PPID); init/systemd (PID 1) reaps orphans — the process hierarchy mirrors the OS concepts."),
("What does the state column in ps show?",
 "R running, S sleeping, Z zombie, D uninterruptible, T stopped — diagnosing stuck or leaked processes."),
("What is nohup and why use it?",
 "nohup cmd & detaches the process from the terminal so it survives logout — running long tasks on servers without sessions."),
("How do you find and kill a port-bound process?",
 "ss -tlnp or lsof -i:8000 to find the PID, then kill — the 'port already in use' remediation for devs."),
("What is a trap in a script?",
 "trap 'handler' SIGINT/SIGTERM executes cleanup on signals — graceful shutdown handling instead of ugly interruption."),
("What is systemctl and the systemd lifecycle?",
 "systemctl start/stop/restart/status and enable persist across boots — the modern service orchestrator (vs System V init)."),
],
"04-Linux/04-Networking-Commands": [
("What is the local-network diagnostic kit?",
 "ping (reachability), ip/ifconfig (interfaces), ss/netstat (sockets), dig/nslookup (DNS), curl (HTTP), traceroute (path) — the network debugger arsenal."),
("What does ping check?",
 "ICMP echo reachability and round-trip latency — the first test whether a host is up, but ICMP can be filtered."),
("What does curl do?",
 "Transfers data over protocols: -X GET/POST, -H headers, -d data, -o output — the universal API/HTTP tester."),
("How do you find which process listens on a port?",
 "ss -tlnp or lsof -i :8000 show the socket + PID — resolving 'port is taken' instantly."),
("What is the difference between ss and netstat?",
 "netstat is the legacy utility; ss (socket statistics) is faster and the modern replacement — both show listening/established sockets."),
("What does DNS resolution look like?",
 "getent hosts or dig show A/AAAA records; /etc/resolv.conf nameservers — the name-to-IP resolution used by every app."),
("What does traceroute trace?",
 "Hop-by-hop path to a destination via incrementing TTL — diagnosing where packets stall."),
("How do you test a local service?",
 "curl http://localhost:8000/health or nc -zv localhost 8000 — verifying a bound listener works before blaming the network."),
("What is SSH and how do you use key auth?",
 "ssh user@host; public-key auth via ~/.ssh/authorized_keys and ssh-keygen — passwordless, secure server access."),
("What is the difference between TCP and UDP at the command level?",
 "TCP guarantees delivery (ssh/http); UDP is low-latency best-effort (DNS, streaming) — the protocol conversation that connects to OS networking."),
("What is iptables/firewall?",
 "The kernel packet-filtering rule chain — allowing/dropping ports and hosts; cloud security groups are its managed cousin."),
("How do you capture traffic?",
 "tcpdump -i eth0 port 80 captures packets; tshark is its Wireshark-CLI sibling — the deep-dive debugging tool."),
],
}