"""Curated Q&A for 01-DSA/07-Dynamic-Programming leaves."""
DP = {
"07-Dynamic-Programming/01-1D-DP": [
("What is dynamic programming and its two core properties?",
 "DP optimality at a state comes from overlapping subproblems (reused) and optimal substructure (best from best). Store solutions to subproblems; avoid recomputing — the Fibonacci memoisation is the canonical example."),
("Explain memoisation (top-down) vs tabulation (bottom-up).",
 "Memoisation: recurse and cache results (lazy). Tabulation: fill a table iteratively (eager). Same answer; tabulation avoids recursion depth and is often asked for its O(m)/O(n) space."),
("How do you climb stairs / reach step N with Fibonacci-like recurrence?",
 "Ways(n)=ways(n-1)+ways(n-2) with ways(1)=1, ways(2)=2; iterate storing two suffixes — O(n) time, O(1) space. Recursion without memo is O(2^n)."),
("What is the house-robbor (max non-adjacent sum)?",
 "dp[i]=max(dp[i-1], dp[i-2]+nums[i]); use two rolling variables. O(n) time O(1) space. This exact pattern recurs across SP/DSE tests."),
("How do you approach a new 1D DP in an interview?",
 "Define state meaning, write the recurrence, define base cases, verify on a small example, then optimise space; always climb the 4-step ladder aloud."),
("How do you solve coin-change (minimum coins for amount)?",
 "dp[a]=min over coins (dp[a-c]+1); dp[0]=0; fill amount ascending. Watch for unreachable amounts (infinity). O(amount·coins)."),
("How do you solve the number-of-ways coin change?",
 "Count combinations: dp over coins outer and amounts inner (or use unbounded-knapsack counting) — avoids counting permutations twice. O(amount·coins)."),
("What is the frog-jump / min-cost on stairs variant?",
 "Min energy to top: cost[i]+=min(cost[i-1],cost[i-2]) brick-by-brick; the answer accumulates at the last two steps. O(n)."),
("How do you solve the longest increasing subsequence (LIS)?",
 "dp[i]=1+max dp[j] for j<i and nums[j]<nums[i]; O(n^2). The O(n log n) variant uses a patience-sorting 'tails' array — know both."),
("What is 'decode ways' and its DP?",
 "Ways to decode digits as letters: dp[i] = (s[i] valid 1..9 ? dp[i-1]:0) + (two-digit 10..26? dp[i-2]:0). Watch '0' edge cases. O(n)."),
("How do you count ways to partition integers (integer break)?",
 "Max product of split: dp[n]=max(i*(n-i), i*dp[n-i]) over splits; classic product-vs-sum optimisation. O(n^2) or formulas."),
("What is the 'palindromic partitioning min cuts'?",
 "dp[i]=min cuts for prefix i; with palindrome check table O(n^2). The answer counts the fewest cuts. O(n^2) time."),
("How do you solve the 'perfect squares' min-count?",
 "dp[n]=1+min over squares dp[n - sq^2]; fill ascending. O(n·sqrt(n)) — a classic one-dimensional DP applied to numbers."),
("How do you handle large N with 1D DP?",
 "Keep only needed rows/variables; use modulo for counting problems; use integer overflow care; and prefer tabulation for arrays of size ≥10^5."),
("What is the bitmask trick for 'subset XOR pairs' style 1D DP?",
 "Some count-DPs track parity/mask state rather than position; the 'state' definition transcends 1D-position and is subtly a 2D state machine."),
],
"07-Dynamic-Programming/02-2D-DP": [
("When do you need a 2D DP table?",
 "When the state has two independent dimensions (position in two strings, (i,j) cell, row+column, left+right subarray). The classic instances are grid paths and string DPs."),
("How do you solve unique paths on a grid?",
 "dp[i][j]=dp[i-1][j]+dp[i][j-1]; first row/column are 1. O(rows·cols); can compress to O(cols) with a 1-row sweep."),
("How do you solve min-path-sum on a grid?",
 "dp[i][j]=grid[i][j]+min(dp[i-1][j], dp[i][j-1]); handle first row/column specially. O(n·m) with O(n·m) or O(n) space."),
("Explain the 0/1 knapsack DP.",
 "dp[i][w]=max(dp[i-1][w], dp[i-1][w-wt[i]]+val[i]); either skip or take item i. Fill weights ascending per item; optimise to 1D descending."),
("How do you compress the knapsack table to one array?",
 "For 0/1 knapsack iterate weight capacity DOWNWARD so each item is used once; for unbounded knapsack iterate UPWARD so items repeat. This is the classic dimension-trick."),
("What is the 'edit distance' DP and its transitions?",
 "dp[i][j]=min(insert dp[i][j-1]+1, delete dp[i-1][j]+1, replace dp[i-1][j-1]+(0/1)); matches chars carry the diagonal. O(n·m)."),
("What is the 'longest common subsequence' recurrence?",
 "If a[i]==b[j]: dp[i][j]=dp[i-1][j-1]+1 else max(dp[i-1][j], dp[i][j-1]). Base row 0/col 0 = 0. O(n·m)."),
("What is the 'longest common substring' recurrence?",
 "dp[i][j]=dp[i-1][j-1]+1 only when chars match; reset to 0 otherwise; track global max — adjacent runs differ from subsequence."),
("How do you solve 'maximal square of 1s'?",
 "dp[i][j]=1+min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1]) for '1' cells; track max side squared for area. O(n·m)."),
("How do you solve 'surrounded regions / matrix DP with boundaries'?",
 "DP over cells with boundary conditions; often the transform is dynamic on edges — run corner-propagating DP or union-find boundary flood first."),
("How do you reconstruct the solution path in 2D DP (e.g., LCS sequence)?",
 "Backtrack from dp[n][m]: if chars equal move diagonal and record; else move toward the higher DP neighbour. Collect reversed. O(n+m)."),
("How do you solve 'word break' (dictionary segmentation)?",
 "dp[i]=true if any dp[j] and s[j:i] in dict; scan ends. O(n^2) with set lookup. Follow-up often wants a word count or all segments."),
("What is the 'partition equal subset sum'?",
 "Reduce to target = total/2; boolean knapsack with 1D descending-window; true iff reachable. O(n·target)."),
("How do you solve 'target sum' (± assignment)?",
 "Rewrite as subset-sum on (sum+target)/2 with positivity guard; count ways via knapsack DP. O(n·target)."),
("How do you solve 'interleaving string' DP?",
 "dp[i][j] true if s3[:i+j] is interleaving of s1[:i], s2[:j]; transition consumes s1 or s2 when character matches s3. O(n·m)."),
("What is the 'minimum path sum with obstacles'?",
 "Same DP with blocked cells forced to 0 (or INF); the first cell sets the seed. O(n·m)."),
("How do you solve 'palindromic partitioning' (min cuts) with 2D palindrome table?",
 "First precompute isPal[i][j] via DP (s[i]==s[j] and (j-i<=1 or isPal[i+1][j-1])), then dp-cuts over prefixes. O(n^2)."),
("How do you handle grid DP with obstacles in count-of-paths?",
 "Paths through blocked cells become 0; otherwise dp[i][j]=dp[i-1][j]+dp[i][j-1]; seed dp[0][0] only when open."),
("What is the 'minimum cost to make two strings identical' (delete ops)?",
 "cost = (n+m-2*LCS) as in delete-operation-for-two-strings; or a custom cost matrix — the LCS form is the standard."),
("What is the 'max profit with at most k transactions' 2D DP?",
 "dp[t][d]=max(dp[t][d-1], prices[d]+max_{j<d}(dp[t-1][j]-prices[j])) — maintain a running best-sell; O(k·n) with the sell-day DP."),
],
"07-Dynamic-Programming/03-Knapsack-Variants": [
("What is 0/1 knapsack vs unbounded?",
 "0/1: each item taken at most once — iterate capacity descending. Unbounded: items unlimited — iterate capacity ascending. Both are classics with the code-shape differing by loop direction."),
("How do you solve 'partition equal subset sum' as 0/1 knapsack?",
 "Care only about reachable sums: dp bool of size total/2; for each num iterate descending; dp[s]=dp[s] or dp[s-num]. O(n·sum/2)."),
("How do you solve 'subset sum' counting?",
 "dp[s] = count of ways; dp[0]=1; for each num, for s descending: dp[s]+=dp[s-num]. Careful with large answers (mod)."),
("How do you solve 'target sum' (± signs)?",
 "pos=(sum+target)//2 must be integer and ≥0; run subset-sum counting. The classic renormalisation trick."),
("What is the 'minimum subset difference' / split array problem?",
 "dp reachable sums of one side; answer = min over sums of abs(total-2*s). Equivalent to partition DP min-diff. O(n·total)."),
("How do you solve 'coin change minimum' vs 'coin change ways' key difference?",
 "Min coins: dp[a]=min(dp[a-c]+1) over coins per amount. Ways: dp over coins outer to avoid permutations. Both O(amount·coins); enumerate the difference carefully."),
("How do you solve the 'combination sum IV' (order counts)?",
 "dp[a] += dp[a-c] for all coins per amount ascending — permutations counted. Unbounded + order-agnostic needs the outer-coin loop."),
("What is the 'bounding types of items (multiple-choice knapsack)'?",
 "Group each type with its items; transition either skip the group or pick exactly one item — dp[group][cap]=max(dp[g-1][cap], val_i+dp[g-1][cap-wt_i])."),
("How do you reconstruct the items taken in 0/1 knapsack?",
 "Backtrack from dp[n][W]: if dp[i][W]==dp[i-1][W] skip item i else take and W-=wt[i]. Track chosen indices."),
("How do you solve 'last stone weight' variants?",
 "Map to subset-difference: min abs(total-2*s) reachable; simulate the optimal splitting. O(n · total/2) but with pruning often passes."),
("How do you handle knapsack with mod counting and huge sums?",
 "Take modulo at every addition; keep sums bounded; often the 'ways' DP uses mod 10^9+7 explicitly in SP/DSE problems."),
("What is the 'word break' as a knapsack-of-strings?",
 "dp[i] reachable prefix; for each reachable i and word w add suffix — the string-knapsack analogy— O(n^2 · L)."),
],
"07-Dynamic-Programming/04-String-DP": [
("List string-DP classics.",
 "LCS, edit distance, longest palindromic substring/subsequence, interleaving strings, regex/wildcard matching, palindrome partitioning, word break — every one appears in SP/DSE tests."),
("How do you compute the length of the longest palindromic subsequence?",
 "dp[i][j]= (s[i]==s[j]? dp[i+1][j-1]+2 : max(dp[i+1][j],dp[i][j-1])) over increasing length windows. O(n^2)."),
("How do you find the longest palindromic substring with DP?",
 "Base length-1/length-2, then dp[i][j]= (s[i]==s[j] and (j-i<=1 or dp[i+1][j-1])); track the longest true interval. O(n^2)."),
("How does the edit distance transition table work?",
 "Fill i rows for s, j cols for t; dp[i][j] accumulates insert/delete/replace costs or carries diagonal on match. O(n·m) cells."),
("What is the recurrence for min insertions to make a string palindrome?",
 "minInsertions = len(s) - LPS(s); the characters not matched inside the LPS need mirrored insertion. O(n) after O(n^2) LPS."),
("How do you solve 'delete operations for two strings'?",
 "result = len(a)+len(b)-2*LCS(a,b). Only deletions; everything kept must be a common subsequence."),
("How do you solve 'minimum window substring' (not exactly DP but hybrid)?",
 "Sliding-window + counter; the DP flavour is the rolling frequency state. Use left/right pointers; track required vs found. O(n)."),
("How do you check if string can be built by concatenating dictionary words?",
 "Word-break DP: dp[i]=or over words of dp[i-len] and s[i-len:i] in dict. Extend method for all splits. O(n^2 · L)."),
("How do you count distinct subsequences of s equal to t?",
 "dp matching-count: if s[i]==t[j] include dp[i-1][j-1] + dp[i-1][j]; else carry dp[i-1][j]. O(n·m) mod-heavy."),
("How do you solve 'shortest common supersequence'?",
 "Length = n+m-LCS; reconstruction merges the two strings skipping LCS overlaps. A classic LCS-extended question."),
("How do you solve 'regex matching' with '.' and '*'?",
 "dp[i][j]: match-dependent — '.' passes any, 'c*' counts 0 (dp[i][j-2]) or repeats (dp[i-1][j]). Watch index translation to 1-based. O(n·m)."),
("What is the wildcard pattern matching transition?",
 "dp[i][j] = dp[i][j-1](* empty) or dp[i-1][j](* eats one) or char equality; '?' is one-of. O(n·m) — greedy two-pointer variant also exists for a booleam answer."),
("How do you solve 'longest happy string with no three same' (string DP-ish greedy)?",
 "Greedy largest-count-first with the rule never adding the third same; runs faster than DP — a good example of when DP isn't needed."),
("How do you reconstruct the actual LCS string?",
 "Backwards walk from dp[n][m]; on match record char and move diagonal; else move the larger neighbour; reverse at the end."),
],
"07-Dynamic-Programming/05-Tree-DP": [
("What is tree DP (DP on trees)?",
 "DP state per node computed from children's DP values— commonly post-order (children first), storing e.g., height, size, or maximum independent set, in O(n) total."),
("How do you compute the size of every subtree?",
 "Post-order: size[u]=1+sum(size[child]); answers queries about subtree aggregates. O(n)."),
("How do you compute the diameter of a tree (DP flavour)?",
 "Post-order track the two largest child heights; diameter = max(1+top1+top2); propagate the best height upward. O(n)."),
("How do you solve 'binary tree maximum path sum' as tree DP?",
 "Return the best single arm (u + best child arm) while tracking global max including both children. O(n)."),
("What is tree rerooting (change of root DP)?",
 "Compute answers for all roots in O(n): first root DP, then a second pass recomputing each child's value from its parent's value (reroot formula), often called 'tree up-down DP'."),
("How do you solve 'minimum cameras to cover a binary tree'?",
 "Three states per node (camera here / covered by child / needs coverage) with a greedy recursive return — a leaf-favouring DP formulated in code."),
("What is the 'sum of distances in a tree' problem (all-pairs via rerooting)?",
 "First compute distances from node 0 (BFS/DFS + size), then reroot: dist[child]=dist[parent] - size[child] + (n - size[child]). O(n)."),
("How do you find the maximum independent set on a tree?",
 "dp[u][0]=sum dp[child][1] (skip u), dp[u][1]=1+sum dp[child][0] (take u) — classic tree DP on unweighted trees. O(n)."),
("How do you detect 'balanced binary tree' with DP-style height postorders?",
 "Return -1 (imbalance) up immediately when |hl-hr|>1, else propagate height; O(n)."),
("How do you decorate a tree with subtree sums to answer ancestor-descendant queries?",
 "Precomp subtree sizes + Euler-tour ranges let you test ancestry (subtree range containment) in O(1) after O(n) DFS. Standard technique."),
],
"07-Dynamic-Programming/06-Interval-DP": [
("What is interval DP and its canonical state?",
 "dp[i][j] describes an optimal result over the contiguous segment [i,j]; transitions split segments (dp over k between i and j) or extend edges; fill by increasing length. O(n^3) typical."),
("How do you solve 'burst balloons'?",
 "dp[i][j]=max over k of dp[i][k-1]+dp[k+1][j]+nums[k]*nums[i-1]*nums[j+1] with padded coins; fill by length ascending. O(n^3)."),
("How do you compute 'matrix chain multiplication' min operations?",
 "dp[i][j]=min over k (dp[i][k]+dp[k+1][j]+dims[i-1]*dims[k]*dims[j]); O(n^3). Canonical interval DP."),
("How do you solve 'scramble string' or 'interleaving cut problems'?",
 "Interval over substrings: split at k and test both orientations — dp/I is the subarray pair feasibility. O(n^4) worst with straightforward formulation."),
("How do you solve 'palindromic cuts (palindrome partitioning II)'?",
 "dpcuts[i]=min over palindromic j..i of dpcuts[j-1]+1; with the precomputed isPal table. O(n^2)."),
("How do you solve the 'minimum score triangulation' ?",
 "dp[i][j]=min over k of dp[i][k]+dp[k][j]+values[i]*values[k]*values[j] — triangle DP over polygon vertices. O(n^3)."),
("How does the length-ascending fill order avoid using unfilled states?",
 "Each larger interval depends only on strictly smaller intervals; filling by length guarantees sub-intervals are already computed — the key implementation detail."),
("How do you solve 'egg drop' via interval/int-based DP?",
 "dp[k][m] moves using k eggs and m moves -> max floors tested; or dp over floors with binary-search k. The formula-based DP drastically reduces states."),
("How do you reconstruct an optimal tree from matrix-chain DP?",
 "Record split k during DP; backtrack to print parenthesisation. Same store-the-decision trick used across interval DPs."),
("How do you identify an interval-DP problem in an interview?",
 "When the answer involves breaking subarrays/substrings into parts and combining, or the recurrence uses a split index — think interval DP."),
],
"07-Dynamic-Programming/07-State-Machine-DP": [
("What is state-machine DP?",
 "DP where the state encodes a phase/status (e.g., holding stock, cooldown, k transactions used), with transitions between statuses — tracking more than a scalar DP value."),
("How do you solve 'best time to buy-sell with cooldown'?",
 "States: rest, holding, sold — transitions between them after each price; the DP arrays (or four vars) encode the max profit by state. O(n)."),
("How do you solve 'best time to buy-sell with transaction fee'?",
 "States hold/cash: cash[i]=max(cash[i-1], hold[i-1]+price[i]-fee); hold[i]=max(hold[i-1], cash[i-1]-price[i]). O(n)."),
("How do you solve 'best time with at most k transactions'?",
 "dp[t][d]=max(dp[t][d-1], prices[d]+sellOffset) where sellOffset=best dp[t-1][j]-prices[j]; two-dimensional states. O(k·n)."),
("How do you formulate 'house robber' as state DP?",
 "states of rob or skip: rob=prevSkip+nums[i]; skip=max(prev). Two rolling vars; the status is the binary take/skip. O(n) O(1)."),
("What is the 'two statuses of the same variable' pattern?",
 "Any problem tracking both a value and whether the current element was chosen (include/exclude) — the generic 0/1 skip-or-take has a state-machine reading."),
("How do you solve 'decode ways with zero rules' via status DP?",
 "dp[i] carries whether a valid single/double take happened; the status distinguishes the two digit cases. O(n)."),
("How do you solve 'maximum alternating subsequence sum'?",
 "States even/odd index with sign multiplier; dpOdd= max(dpOdd, dpEven-num), etc. — pure sign-state machine. O(n)."),
("How do you solve 'ugly number / counting with states'?",
 "Usually arithmetic; the DP status is the smallest multiplier index per prime; simpler than a state machine but shows how status improves greedy."),
("How do you combine state-machine DP with constraints?",
  "Add constraint variables to the state (transactions used, stocks held). State explosion == dimension increase — communicate the trade-off to the interviewer."),
]}