"""Curated Q&A for 01-DSA/10-13 leaves: Greedy, Segment/Fenwick, Two Pointers."""
GREEDY = {
"10-Greedy-Algorithms/01-Greedy-Fundamentals": [
("What is a greedy algorithm?",
 "A greedy algorithm makes the locally optimal choice at each step, hoping it leads to a global optimum. It works only when the problem has the greedy-choice property and optimal substructure."),
("How do you prove a greedy algorithm correct?",
 "Use the exchange argument: take any optimal solution, show you can swap in the greedy choice without losing optimality, so the greedy solution is optimal. Or show matroid-like structure."),
("Give examples where greedy is optimal.",
 "Coin change with canonical denominations, Huffman coding, Kruskal/Prim MST, Dijkstra (non-negative), fractional knapsack, activity selection — each has a proven greedy property."),
("When does greedy fail?",
 "When a locally optimal choice harms future options — e.g., 0/1 knapsack, some coin systems, coin returning with arbitrary denominations, and coin change for amount where local max fails."),
("How do you decide 'Is this greedy or DP?' in an interview?",
 "Test a small counterexample. If a locally optimal step is always safe, greedy; if choices constrain later optimality, DP. State both and choose deliberately."),
("What is the exchange argument in one line?",
 "Show swapping the greedy step into any optimal solution preserves optimality, so there exists an optimal solution matching greedy at every step."),
("Explain the fractional vs 0/1 knapsack distinction.",
 "Fractional knapsack allows fractional items → sorted by value/weight ratio, greedy optimal. 0/1 doesn't → DP required; greedy ratio fails."),
("Name an Infosys-grade greedy problem.",
 "Minimum platforms, jump game, candy distribution, gas station, merge intervals, and task scheduling with deadlines are all SP/DSE frequent greeds."),
],
"10-Greedy-Algorithms/02-Activity-Selection": [
("State the activity selection problem.",
 "Given start and end times, select the maximum number of non-overlapping activities. The greedy: sort by end time and always pick the earliest-finishing activity."),
("Why does sorting by end time (and picking the first that fits) yield the maximum count?",
 "The earliest finish leaves the maximum remaining timeline for future activities; by exchange, any optimal solution can be transformed to include the earliest-finishing activity."),
("How do you solve 'maximum meetings in one room'?",
 "Same activity-selection: sort by end (tiebreak by start/end), greedily schedule when start >= last_end. O(n log n)."),
("How do you schedule tasks with deadlines maximizing profit?",
 "Sort by profit descending; for each task place it at the latest free slot before its deadline using a disjoint-set 'next free' or sorted set. O(n log n)."),
("What is the 'minimum platforms' / train station problem?",
 "Count max simultaneous overlaps: sort arrivals and departures and merge them with two pointers, keeping the running overlap maximum. O(n log n)."),
("What is the 'merge intervals' greedy for minimum, and is it greedy or sweep?",
 "Sort by start; merge overlapping intervals in one pass; count non-overlapping merges. It is a greedy decision that merging all overlaps is safe. O(n log n)."),
("How do you formulate 'maximum sum of non-overlapping intervals'?",
 "Greedy fails because interval values matter; use DP over sorted intervals (dp[i]=max(dp[i-1], value+dp[before edge])). Recognition matters."),
("How does 'gas station' reduce to a greedy insight?",
 "If total gas >= total cost, a valid start exists; find the index where running balance reaches its minimum — the greedy restart point. O(n)."),
("What is 'minimum arrows to burst balloons'?",
 "Sort by end; fire an arrow at the earliest end, which bursts all balloons overlapping it; count arrows. Greedy with the right variable chosen. O(n log n)."),
("How does activity selection with weighted activities differ?",
 "Unweighted → greedy by end works. Weighted → DP: sort by end, dp[i] = max(dp[i-1], weight_i + dp[last non-overlap]). Exponential naive, polynomial DP."),
],
"10-Greedy-Algorithms/03-Huffman-and-Encoding": [
("What is Huffman coding?",
 "A lossless prefix code minimizing expected codeword length. Build a binary tree by repeatedly merging the two lowest-frequency characters; codes are the root-to-leaf paths."),
("How do you build a Huffman tree with a min-heap?",
 "Push (freq, char) nodes; while >1 node: pop two smallest, create parent with summed weight, push back; the final node is the tree root. O(n log n)."),
("Why is the Huffman code optimal?",
 "It realizes the proof of optimal prefix codes: always merging the two smallest ensures the smallest combined path leaves regardless — exchange argument establishes optimality."),
("What is a prefix code and why does it enable decoding?",
 "No codeword is a prefix of another, so concatenated bitstreams unambiguously split at code boundaries; decoding walks the tree from the root."),
("Is the Huffman code unique?",
 "No — ties yield multiple optimal trees; different choices of equal-frequency merges produce different but equally-optimal codes."),
("How do you build the Huffman decoding tree from an encoded stream?",
 "Use a Node class with left/right; walk bits: left→0, right→1; at a leaf emit its character and reset. O(total bits)."),
("What is the entropy bound on Huffman compression?",
 "Expected length is between H and H+1 where H is the source entropy — the practical limit of character-level compression."),
("How do you handle a single-character stream in Huffman?",
 "If only one distinct symbol, the code length would be 0; the special-case is a 1-bit code for the single char (or store just the char)."),
("Where is Huffman actually used?",
 "Deflate (zlib/gzip/PNG), JPEG (with RLE), and fax standards. Mentioning real usages shows seniority."),
("What distinguishes Huffman from arithmetic coding?",
 "Huffman assigns whole-bit symbols; arithmetic codes fractional bits, approaching the entropy bound more tightly for skewed distributions."),
],
"10-Greedy-Algorithms/04-Advanced-Greedy": [
("What makes a greedy problem 'advanced'?",
 "Hidden monotonic structure, exchange proofs, combining greedy with a heap (e.g., task scheduler), or matching with sorting and interval constraints."),
("How do you solve the 'task scheduler' problem (letters, cooldown n)?",
 "Max-frequency first; answer = max((maxFreq-1)*(n+1)+countMax, len(tasks)) — a clever closed form. Prove by arranging the heavy letter in slots."),
("How do you solve 'candy distribution' (ratings)?",
 "Two passes: left-to-right (candy[i] = +1 if rating>left) then right-to-left adjusting; sum. O(n)."),
("How do you solve the 'jump game II' minimum jumps?",
 "Greedy: farthest reachable while within a step's window; count one jump per window. O(n). The greedy avoids DP's O(n^2)."),
("How do you solve 'IPO' / 'best profit with capital'?",
 "Two heaps: affordable projects by capital (max-heap of profit) and remaining sorted by capital — the greedy selection at each stage. O(n log n)."),
("How do you solve 'maximum width ramp' style?",
 "Monotonic stack of strictly decreasing values then scan right; O(n)."),
("How do you solve 'minimum deletion to make string good (no 3 same adjacent)'?",
 "Greedy count current run; reset at 3. O(n)."),
("How do you solve 'maximum cows with a scaling k' (watch-out problems)?",
 "Binary search answer k, greedy check feasibility; the answer is monotone in k so the search is over the count. This 'binary search + greedy check' fusion is common."),
("How do you prove jump-game-style greediness?",
 "Exchange/invariant: at every index maintain the union-reach invariant and show greedy never worsens it — agree max reach is monotone, so the greedy jump is safe."),
("How does the 'gas station' greedy actually prove correctness?",
 "If total>=cost, the chain sums stay non-negative after going from the global-min index — a single index always works; prove by prefix-sum minima."),
],
"11-Segment-Trees-and-Fenwick/01-Segment-Tree-Basics": [
("What is a segment tree?",
 "A tree over an array answering range queries (sum, min, max, gcd) and supporting point/range updates in O(log n). Leaves store array elements; internal nodes store aggregates of children."),
("State the time complexity of segment tree operations.",
 "Build O(n), query O(log n), point-update O(log n), range-update with lazy O(log n). Space O(4n) with the standard 1-indexed flat array."),
("How does query-range work?",
 "If the node's range is fully inside [l,r] return its aggregate; if disjoint return identity; else split and combine children. O(log n) with canonical decomposition."),
("How do point updates propagate?",
 "Recursively update the leaf, then recompute the parent as combine(left,right) on unwind. O(log n). Only ancestors need fixing."),
("How do you choose the size of the segment tree array?",
 "4*n is the safe estimate for the recursive implementation; iterative (array of 2*size with padding to power of two) uses exactly 2*size — state both."),
("When would you use a segment tree over a Fenwick tree?",
 "Segment trees handle MIN/MAX and range-update (lazy) natively; Fenwick trees are faster and simpler for point-update + prefix-query (sum-like)."),
("What is a lazy propagation and why is it needed?",
 "Deferring a range update to children until it is queried; without it, a range update is O(n). Lazy tag on each node records pending updates — query/update both push tags. O(log n)."),
("How do you implement 'range sum with range add' (lazy)?",
 "Each node stores sum and a lazy-add; push before descending modifies children sums; applying a lazy to a full-covered node updates sum += tag*len covering the range. O(log n)."),
("How do you build the tree recursively?",
 "build(node, l, r): if l==r store arr[l]; else mid, build children, tree[node]=combine(tree[left],tree[right]). O(n) nodes visited."),
("How do you combine two aggregate types (min, count)?",
 "For 'min + count' store a pair; combine chooses the smaller (or sums counts when equal). Structure that: -  relative to the OPERATOR the combine must implement."),
],
"11-Segment-Trees-and-Fenwick/02-Range-Queries": [
("What range queries are typical with segment trees?",
 "Range sum, min/max, gcd/lcm, mode (with merge making it subtle), OR/AND/XOR, and kth-element find — all over ± static or updatable arrays."),
("How do you handle range max with point updates?",
 "Segment tree store max; query uses max as the combine; point update recomputes leaf then ancestors. O(log n) per op."),
("How do you answer Range Minimum Query with a segment tree vs sparse table?",
 "Segment tree supports updates and O(log n) queries; sparse table precomputes O(n log n) and answers RMQ in O(1) but no updates — choose by update presence."),
("How does range GCD query work?",
 "Store gcd at nodes; combine = math.gcd(l,r); query over the range with identity 0. O(log n). GCD properties survive the canonical decomposition."),
("How do you handle range XOR queries?",
 "XOR aggregate with identity 0 and segment-tree support; combined with lazy XOR lets you flip ranges quickly — used in advanced updates."),
("How do you merge counts of elements within ranges (online, updates)?",
 "Wavelet tree / merge-sort tree; or store per-node sorted buckets and answer count-in-range via binary search. O(log^2 n) query — a common extension."),
("How do you combine segment-tree with DS like a Fenwick for 2D?",
 "Fenwick of segment trees (or vice versa) answers 2D range updates/queries in O(log^2 n) — the nested-DS pattern for grid problems."),
("What is the 'kth missing / kth-1 index' on a segment tree?",
 "Walk the tree tracking how many elements lie left; descend left if accumulated+k ≤ left count else right — O(log n) 'find by order'. A classic descendant query."),
("How do you compute prefix sums with a segment tree?",
 "prefix(l) = query(1..l); or store each node's aggregate and navigate. Fenwick (BIT) does prefix sums faster, but segment tree is general."),
("When is a sparse table better than a segment tree?",
 "Immutable arrays needing O(1) RMQ — sparse table precomputes; for updates it's useless — segment tree wins."),
],
"11-Segment-Trees-and-Fenwick/03-Lazy-Propagation": [
("What does lazy propagation solve?",
 "Range additions/assignments on a segment tree in O(log n) instead of touching all leaves — defer the update record to children until needed."),
("Explain the lazy-tag mechanics with range-add.",
 "Node stores sum and lazy add value. If a range fully covers the node, apply sum += tag*len and record lazy += tag for children; when a partial query/update descends, push the tag first to children."),
("What is the 'push' function?",
 "push(node,l,r): if lazy[node]!=0 then propagate to children (update child sums and child lazy), clear current lazy. Called before descending for partial updates/queries."),
("What are the pitfalls of combining multiple lazy ops (multiplier + add)?",
 "Apply composite transforms in the correct order — (add then mul) vs (mul then add) differs; store both and update in the right sequence. Test with simple cases."),
("How does lazy range assignment (not add) work?",
 "Overwrite semantics: on full-cover, set sum=tag*len and mark an assign-flag; push clears descendant assignment; combine must respect assignments over inherited tags."),
("Why do you push before reading children?",
 "The parent's pending update must reach descending children first, or the query sees stale child values. Order: push → descend → recompute on unwind."),
("What is the memory footprint of a lazy tree?",
 "Two arrays (tree + lazy) of size 4n each; lazy could be int64 for modulo-heavy updates — roughly 2*4*n*8 bytes at 64-bit."),
("How do you apply lazy on segments with negative adds?",
 "The same arithmetic works: sum can decrease; record lazy add (can be negative); combining rules unchanged."),
("When is lazy NOT needed?",
 "Point-only updates or pure static queries — lazy is only for range updates; Fenwick trees also support range-add via two BITs without lazy tags."),
("How do you test a lazy tree quickly?",
 "Brute force against naive per-element updates on random small arrays — property-based verification catches tag-order bugs."),
],
"11-Segment-Trees-and-Fenwick/04-Fenwick-Tree": [
("What is a Fenwick tree (BIT) and its operations?",
 "A compact data structure for prefix queries and point updates in O(log n): update(i,delta) on ancestors i+=lowbit(i), query prefix by subtracting lowbit. Build O(n)."),
("How does a Fenwick tree update work?",
 "update(index, delta): while index<=n: tree[index]+=delta; index += index & (-index). Where lowbit = index & -index isolates the least significant set bit."),
("How does a Fenwick query work?",
 "sum(index): while index>0: res+=tree[index]; index -= index & (-index). Returns prefix sum of first index elements in O(log n)."),
("How do you build a Fenwick tree in O(n)?",
 "Initialize tree from the array, then for each i: j=i+lowbit(i) ≤ n → tree[j]+=tree[i] — the accumulation chain. O(n) total."),
("How do you do point update + range query with BIT?",
 "Prefix sums support range sum(l,r)=prefix(r)-prefix(l-1); point updates change a single index. That pair is the canonical BIT usage."),
("How do you do range update + point query with BIT?",
 "Store the difference array in the BIT; range-add(l,r,x) does update(l,x), update(r+1,-x); point query = prefix(diff at index). Same tree reversed."),
("How do you do range update + range query with two BITs?",
 "Maintain BIT1 for diff and BIT2 for i*diff; prefix_sum(i)= (i+1)*BIT1.query(i) - BIT2.query(i). The two-tree displacement trick is classic."),
("How do you find the kth order statistic with a BIT?",
 "Binary lift: start at largest power of 2, accumulate the tree indices while sum < k (k subtract), end at index+1 = the kth smallest. O(log n)."),
("How do you count inversions with a Fenwick tree?",
 "Process elements right-to-left; each invocation queries the count of smaller-seen-so-far via BIT on compressed ranks; update rank. O(n log n)."),
("Compare Fenwick vs segment tree.",
 "Fenwick: ~half memory, simpler/faster code, no lazy/handles only associative prefix-combine. Segment tree: min/max, range-update with lazy, and arbitrary aggregates — choose by capability."),
],
"12-Two-Pointers/01-Fundamentals": [
("What is the two-pointer technique?",
 "Two indices into a sequence—either moving inward from both ends or at different speeds—process the array in one or two passes to reach a solution in O(n) that naive nesting needs O(n^2) for."),
("What is a classic 'two pointers from ends' problem?",
 "Pair-sum for a target on a sorted array: l=0,r=n-1; shrink by the comparison — O(n). Kinds: 'two sum sorted', 'three sum', container with most water."),
("What is the 'slow-fast' two-pointer pattern (linked lists)?",
 "Slow advances one per step, fast two— detecting cycles, finding middles, or palindrome checks in linear time with O(1) space."),
("When do you NEED sorted input for two pointers?",
 "Pair-sum, closest-pair, count-pairs-under-target: sorting first (O(n log n)) gives the monotonic guarantee that holes the algorithm exploits. Mention the sort cost."),
("How do you remove duplicates / move zeros with two pointers?",
 "A write (slow) index and a scan (fast) index: copy or skip causing an in-place compaction in O(n) with O(1) space."),
("How does the 'container with most water' greedily move the smaller line?",
 "Moving the smaller line can only improve or keep area (its own wall caps the area); moving the larger can't improve. O(n) — proof by elimination."),
("How does 'trapping rain water' with two pointers work?",
 "Maintain running left/right max before the pointers; the side with the smaller max has its trap known — accumulate water and step in. O(n) O(1)."),
("What problems are two-pointer-naive vs two-pointer-correct?",
 "Palindromes, pair sums, bounded windows, enable a linear pass; but if pointer movement can't be justified by monotonicity/comparison, the approach must be designed carefully."),
("When would you use three pointers (Dutch National Flag)?",
 "3-way partition sorts 0/1/2 in O(n) with low/mid/high — the canonical tri-pointer algorithm and a direct two-pointer extension."),
("How do you debug a two-pointer loop?",
 "Trace indices at a boundary condition (empty array, all equal, at target edge), confirm pointer convergence including when l==r, and check the off-by-one termination condition."),
],
"12-Two-Pointers/02-Container-Problems": [
("State 'Container With Most Water' and its two-pointer solution.",
 "Maximize area between two vertical lines: two pointers at both ends, track max area, move the shorter line inward. O(n)."),
("How does the cold-storage problem (water trapped) map to pointers?",
 "Cold storage = same trapped-water: two-pointer with running left/right maxima computes trapped volume O(n), exactly the 'trapping rain water' formula."),
("What is the formula for area in container problems?",
 "area = min(height[l], height[r]) * (r-l). Maximizing it is solved by pointer movement that never skips the optimum — argue via monotonicity."),
("What variants exist (wrapped containers)?",
 "Circular traps, obstacles in between, or plates (density) add conditions — the pointer proof extends when movement preserves monotonic feasibility."),
("How do you compute the maximum water with k platforms?",
 "Stack/segment-tree based solutions or sweep order by plate height; often O(n log n) — the bucket-moving insight changes."),
("How do you solve 'max volume between buildings' (histogram water)?",
 "'Trapping rain water' exactly: by bar heights; two-pointer or stack. Summarise both."),
("What is the 'largest rectangle in histogram' vs 'container'?",
 "Histogram: find the largest rectangle — a monotonic stack O(n). Container: largest area between two chosen bars — two pointers. Distinguish correctly."),
("How do you solve the 'cold storage' matrix variant (2D water)?",
 "3D water trap: priority queue seeded at boundary, relax interior with the current water level (BFS + min-heap). O(nm log nm)."),
("Why does moving the taller line break the two-pointer invariant?",
 "The taller line may externally enable a better partner; removing it prematurely forfeits that — the invariant relies on moving the limit."),
("How do you verify container correctness on edge cases?",
 "Test empty (0), one line (0), all equal (max area = n-1 in width), descending, and negative-in-line reject — the boundary checks an interviewer wants."),
],
"12-Two-Pointers/03-Pair-Sum-Problems": [
("How do you find if two numbers sum to target in a sorted array?",
 "Two pointers l/r; if arr[l]+arr[r]==target return, if< then l++, else r--; O(n). If unsorted, sort first or use hash set for O(n) with O(n) space."),
("What is the two-sum 'count pairs' variant?",
 "Use a multi-set hash to count complement occurrences — O(n). With duplicates the count bookkeeping matters; state both sorted-pointer and hash approaches."),
("How do you find exactly k pairs with absolute difference d?",
 "Sort then two pointers counting pairs by walking both pointers; or a frequency counter. O(n log n) dominant."),
("How does the three-sum problem use two pointers?",
 "Fix the first element i, then two-pointer over the rest for -nums[i]; skip duplicates. O(n^2) total."),
("How do you find the closest pair sum to a given value?",
 "Sorted two-pointer; track the minimal |arr[l]+arr[r]-target| while moving towards the target from both ends. O(n)."),
("How do you check pairs with sum greater/less than k?",
 "Sorted: if l+r>k count valid ending combos as (r-l) with right pointer moves; else left pointer moves; O(n)."),
("How do you handle duplicates in three-sum?",
 "Skip the same first value and same second value after the loop (while-loops advancing past equals) — dedupe triples explicitly."),
("What is a 'pair with product k' search?",
 "Use a hash set of visited numbers checking k/x when x!=0, or two-pointer after sort — the product variant flips comparisons."),
("How do you find pairs whose squares or abs sum to k?",
 "Same pointer logic but with squared/absolute values: compare (l^2+r^2) to k and move accordingly — still monotone."),
("How do you answer 'count pairs with xor k'?",
 "Hash map of seen numbers: for each x count seen[x^k]; xor hashes make it O(n) — a two-pointer immaterial case; mention the distinction."),
],
"12-Two-Pointers/04-Advanced-Two-Pointers": [
("What makes a two-pointer problem advanced?",
 "Movement depends on multiple monotonic measurements, pointer order is dynamic, or the two pointers combine with hashing/heaps (max area of wind-mills, minimum windows)."),
("How do you solve the 'minimum window substring' with two pointers?",
 "Expand right to satisfy all required chars, then shrink left to minimise while retaining feasibility — a dynamic-window two-pointer. O(n)."),
("What is the 'longest substring without repeating chars' pointer trick?",
 "A window with a set/dict; advance right adding char, pop lefts until no duplicate. O(n)."),
("How do you solve the 'k-best pairs from two arrays' with a heap + two pointers?",
 "Seed (a[0]+b[j]) in a min-heap, pop the smallest, push next (a[+1]+b[j]) — combining pointers with a heap makes the k-Pairs problem tractable. O(k log k)."),
("What is the 'median of two sorted arrays' pointer hybrid?",
 "Merge with two pointers tracking the middle (even/odd) — O(n+m); or binary search partition — O(log(min(n,m))). Prefer the latter for the 'expected' answer."),
("How do the pointers in 'kth smallest sum in sorted matrices' work?",
 "The matrix of pair sums is sorted by rows and columns; k-way, heap-merge is the clean path, but the monotonic structure enables pointer search — the interviewer probes your data-structure decision."),
("How do you blend two-pointer with, binary search?",
 "Binary search the answer (e.g., kth-smallest distance), check feasibility with a two-pointer count — the pairing recurs across SP/DSE hard problems."),
("What is the 'maximum pair sum same prefix' (fixed arrays) hybrid?",
 "Sort second array; for each first-array element use binary search or two-pointer to find the bound — O(n log n) building blocks composed."),
("When does two-pointer worst out?",
 "When the endpoint movement is ambiguous (multiple monotone targets) or the array is not sorted/hashing is cheaper — always confirm the invariant before committing."),
("How do you memoise/stream with two pointers?",
 "For streaming inputs, keep the window/pair pointers persistent across chunks to avoid rescanning — a favourite production-systems answer."),
],
}

def datALLC():
    return {**GREEDY}