"""Curated Q&A for 01-DSA/06-Graphs leaves."""
GRAPHS = {
"06-Graphs/01-Graph-Representations": [
("Define a graph and its kinds.",
 "A graph is a set of vertices (V) and edges (E). It can be undirected or directed, weighted or unweighted, connected or disconnected, acyclic (trees/DAG) or cyclic."),
("What are the common representations of a graph?",
 "Adjacency matrix (V×V, O(V^2) space, O(1) edge check), adjacency list (dict of lists, O(V+E) space), and edge list (list of (u,v,w)). For sparse graphs adjacency lists dominate."),
("Why is an adjacency list preferred for competitive problems?",
 "Space O(V+E) not O(V^2); fast iteration over neighbours in BFS/DFS; simple dict/set of neighbours in Python."),
("When would you use an adjacency matrix?",
 "Dense graphs (E ~ V^2), frequent O(1) edge-existence queries, and small V (≤ few thousand). Used in Floyd-Warshall style all-pairs."),
("How do you store a weighted graph?",
 "Adjacency list of (neighbour, weight) tuples; matrix stores weights; edge list stores (u,v,w). Represent INF for absence in matrix form."),
("What is the edge list and when is Kruskal used with it?",
 "Edge list is a flat list of edges — ideal for Kruskal's MST (sort by weight, union-find) and for algorithms needing sorted edges. O(E log E) sort."),
("How does Python typically express an adjacency list?",
 "graph = defaultdict(list); graph[u].append(v) with weights as tuples graph[u].append((v,w)). Used with 'from collections import defaultdict'."),
("What is an adjacency-set and its benefit?",
 "Set of neighbours per vertex gives O(1) membership (edge existence) at the cost of iteration order; useful when edge-existence queries dominate."),
("Why is undirected representation duplicated?",
 "An undirected edge (u,v) is stored twice — once in u's list and once in v's list — so traversal can move both ways."),
("What is a DAG? Give examples.",
 "A directed acyclic graph: directed with no cycles. Examples: dependency graphs, build pipelines, topological-order problems, SP/DSE scheduling questions."),
("What is a strongly connected component (SCC)?",
 "Maximal set of vertices where each can reach every other via directed paths. Found by Tarjan or Kosaraju in O(V+E); condenses a graph into a DAG."),
("How do you read graph constraints and choose representation?",
 "n≤10^5, m≤10^5 → adjacency list; n≤10^3 dense → matrix fine; verify memory before designing the algorithm."),
("What is an implicit graph (grid as graph)?",
 "A grid where each cell is a node and up/right/down/left are neighbour edges; BFS/DFS over (r,c) with boundary checks is graph traversal without building lists."),
("How do you detect that a traversal is correct on disconnected graphs?",
 "Iterate all vertices; run BFS/DFS from each unvisited; the outer loop guarantees every component processed even when the start is arbitrary."),
("Explain complexity of building a graph from input.",
 "Reading E edges and storing in adjacency list costs O(E) time and O(V+E) space — typically dominated by the algorithm that follows."),
],
"06-Graphs/02-BFS-and-DFS": [
("Explain BFS and its data structure.",
 "Breadth-first search visits level by level using a queue. Starting from a node, it discovers all neighbours, then their neighbours, guaranteeing shortest-path (fewest edges) in unweighted graphs."),
("What is the time and space complexity of BFS?",
 "O(V+E) time with adjacency lists; O(V) space for the visited set and queue (frontier can be O(V) at one level)."),
("Explain DFS with recursion and stack.",
 "DFS follows one branch as far as possible before backtracking; recursive implementation uses the call stack, or an explicit stack, marking visited on entry. O(V+E)."),
("Distinguish BFS vs DFS use-cases.",
 "BFS: shortest path in unweighted graphs, level-order, connectivity between two nodes at min hops. DFS: cycle detection, topological sort, connected components, path existence, backtracking."),
("How do you detect a cycle in an undirected graph with DFS?",
 "While DFS from u, if a neighbour v is visited and v != parent[u], a cycle exists. Parent distinction prevents treating the back-edge to origin as a cycle. O(V+E)."),
("How do you detect a cycle in a directed graph?",
 "Use three-colour marking (unvisited/on-stack/done); encountering a grey (currently on recursion stack) node indicates a back-edge → cycle. O(V+E)."),
("How do you count connected components?",
 "Outer loop over vertices; each unvisited start increments the count and its BFS/DFS marks that component. O(V+E)."),
("How do you find the shortest path in an unweighted graph?",
 "BFS from source tracking parent array; distance = level. Reconstruct path by backtracking parents. This is the canonical Infosys 'shortest path BFS' answer."),
("How do you check if a path exists between two vertices?",
 "Run BFS/DFS from source; true iff the target is visited. If both in same component this is decided by component membership."),
("What is a bipartite check and how is it done?",
 "A graph is bipartite if its vertices can be coloured 2-colour so that edges always join different colours. BFS colouring: neighbours must be the opposite colour or the answer is False. O(V+E)."),
("What is 0-1 BFS and when is it used?",
 "Edge weights in {0,1}; use a deque pushing 0-weights to the front and 1-weights to the back, achieving O(V+E) shortest paths instead of Dijkstra's O(E log V)."),
("What is topological ordering?",
 "A linear ordering of a DAG where every edge u→v has u before v. Kahn's algorithm (indegree-0 queue) or DFS finishing-time reversal produce it in O(V+E)."),
("How does Kahn's algorithm detect a DAG?",
 "Process indegree-0 nodes; decrement neighbours; if processed < V nodes, a cycle exists (remainder have nonzero indegree). O(V+E)."),
("How do you find the number of islands (grid BFS/DFS)?",
 "Scan cells; on encountering an unvisited '1', increment count and flood-fill (BFS/DFS) over adjacent land marking visited. O(rows×cols). This was literally asked in SP/DSE."),
("What are flood-fill variations used for?",
 "Image fill, islands, largest island, regions bounded by water, and matrix-connectivity problems — all apply BFS/DFS over 4-direction neighbours."),
("How do you get all paths from source to target?",
 "DFS tracking current path and visited; when target reached, copy path. Reuse of vertices is forbidden inside a single path unless revisits allowed. Exponential worst case."),
("What is multi-source BFS?",
 "Seed the queue with all sources at distance 0 (e.g., all rotten oranges); the first BFS wave assigns minimal distance from ANY source — classic 'rotting oranges'."),
("How do you find the shortest transformation (word ladder)?",
 "BFS over word states; neighbours are words differing by one letter. Precompute wildcard patterns or neighbours to keep transitions cheap. BFS gives hops."),
("What is the 'min steps to eat all cheese / nearest 0' style?",
 "Multi-source BFS computes distance from all targets simultaneously; the cellular-automaton trick gives distances to nearest target in O(V+E)."),
("How do you detect if BFS results are level order for trees vs graphs?",
 "In graphs, BFS level = shortest edge-hops only if unweighted; in weighted graphs you must use Dijkstra or 0-1 BFS — not plain BFS."),
],
"06-Graphs/03-Shortest-Path": [
("State Dijkstra's algorithm and its use.",
 "Dijkstra finds single-source shortest paths in graphs with non-negative weights using a min-priority-queue, relaxing edges from the min-distance vertex. O((V+E) log V)."),
("Why does Dijkstra fail with negative edges?",
 "A vertex's distance is finalised on extraction, but a later negative edge could reduce it — therefore it must not rely on 'extracted = final' when negative weights exist."),
("What is the Bellman-Ford algorithm and its complexity?",
 "Relaxes all edges V-1 times guaranteeing shortest paths even for negative weights; detects negative cycles on the V-th pass. O(V·E)."),
("What is the Floyd-Warshall algorithm?",
 "All-pairs shortest paths using DP over intermediate vertices k: dist[i][j] = min(dist[i][j], dist[i][k]+dist[k][j]). O(V^3); handles negative weights but not negative cycles."),
("When do you choose each shortest-path algorithm?",
 "Unweighted → BFS; non-negative → Dijkstra; negative weights → Bellman-Ford; all-pairs or small V → Floyd-Warshall; 0/1 weights → 0-1 BFS. Match the constraint set first."),
("How do you find the shortest path with a printed route?",
 "Run the chosen algorithm with a parent/predecessor array, then backtrack from the destination to the source and reverse the list. O(path length) for reconstruction."),
("What is the 'cheapest flight within K stops' problem?",
 "Modified DP/Bellman-Ford: loop k times relaxing edges with a temp array; answer is the reachable min after K iterations — prevents reusing the same edge within one batch."),
("How do you solve 'network delay time'?",
 "Dijkstra from source; result = max of reachable distances; if some vertex unreachable, return -1. Tests Dijkstra mastery directly."),
("What is the path-with-max-probability variant?",
 "Negate to log/sum problem: maximise sum of log(prob) = shortest path on transformed weights via Dijkstra. Common probabilistic-graph interview twist."),
("How do you handle weighted adjacency in Dijkstra with negative like zero?",
 "You cannot — Dijkstra requires non-negativity. Reframe weights (offset) or switch to Bellman-Ford if any negative edge exists."),
("What is the two-constraint shortest path pattern?",
 "When the path has two resources (cost + time), DP over one dimension with minimised other (e.g., dp[vertex][cost]=min time) is common — as in 'Cheapest Flights within K stops'."),
("How do you compute the number of shortest paths?",
 "During Dijkstra/BFS, topK-counters: if relaxed strictly, reset count; if equal, add counts. Track modulo for large answers."),
("What is the negative-weight-cycle consequence?",
 "If reachable, distances are −∞ (can loop indefinitely to reduce cost); detected by a further relaxation change — the classic Bellman-Ford pass V."),
("How do you apply A* and when does it help?",
 "A* is Dijkstra plus a heuristic h(n) ≤ true cost toward the goal; with an admissible heuristic it expands fewer nodes for single-target search (map routing)."),
("What is the space/time profile for Floyd-Warshall?",
 "O(V^3) time and O(V^2) space for the distance matrix — feasible only for modest V (≤ 1000)."),
],
"06-Graphs/04-MST-and-Union-Find": [
("What is a minimum spanning tree (MST)?",
 "A spanning tree of a weighted graph minimising total edge weight; it has V-1 edges and connects all vertices. Only defined for connected undirected graphs."),
("How does Kruskal's algorithm work?",
 "Sort edges ascending; add each edge if its endpoints are in distinct components (union-find); stop when V-1 edges added. O(E log E)."),
("How does Prim's algorithm work?",
 "Grow the tree from a seed vertex using a min-heap of frontier edges, adding the cheapest edge connecting visited to unvisited. O((V+E) log V)."),
("When would you choose Kruskal over Prim?",
 "Kruskal: sparse graphs, edge list input, or when sorting edges is natural. Prim: dense graphs, adjacency list, or when growing from one source is convenient."),
("Define union-find (disjoint set) and its operations.",
 "Data structure tracking partitions with find(x) (root) and union(a,b) (merge). Used for connectivity, cycle detection in Kruskal, and dynamic components."),
("Explain path compression and union by rank.",
 "Path compression flattens trees during find (make nodes point to root); union by rank joins shorter tree to taller. Together they give near-constant amortised (inverse-Ackermann) operations."),
("How do you implement union-find with cycle detection for undirected edges?",
 "For each edge (u,v): if find(u)==find(v) a cycle exists; else union. This validates the MST candidate in Kruskal. O(α) per edge."),
("What is the 'number of provinces / friend circles' problem?",
 "Build union-find over N people and union friendly pairs; count distinct roots = number of connected components. Classic Infosys graph question."),
("How does union-find handle dynamic connectivity questions?",
 "Each union decreases the component count by 1; after all unions, the number of roots answers 'how many groups remain' in O(α) amortised."),
("What is the minimum cost to connect all points (Manhattan MST)?",
 "Build candidate edges using a grid of neighbours, run Kruskal: O(n log n) with pruning — the LeetCode 'min cost to connect all points' solution."),
("How do you assign 'accounts merge' style graphs to union-find?",
 "Map emails to an id; union emails sharing an account; then group emails by root. Classic union-find in an interview setting."),
("What is the 'redundant connection' problem?",
 "Process edges, union endpoints; the first edge whose endpoints are already connected is the redundant edge — direct union-find application."),
("Can union-find be used for weighted connectivity (min bottleneck)?",
 "Sort edges ascending and union until first/last connects the target pair — the weight of that edge gives the minimum-maximum-edge path."),
],
"06-Graphs/05-Topological-Sort": [
("What is topological sort and its precondition?",
 "A linear order of vertices of a DAG where u precedes v for every edge u→v. It exists iff the graph is acyclic; multiple valid orders usually exist."),
("Explain Kahn's algorithm (BFS-based toposort).",
 "Compute indegrees; enqueue all indegree-0; dequeue u, append to order, decrement neighbours, enqueue those that hit 0. O(V+E); leftover nodes mean a cycle."),
("How do you topologically sort with DFS?",
 "Run DFS, append a node to the order AFTER exploring its descendants (postorder), then reverse at the end. The reverse-finish list is the topological order. O(V+E)."),
("Why does DFS toposort require reversal?",
 "A node is finished after its dependencies, so finishing order is dependency-first; reversing makes dependents appear after dependencies — the required ordering."),
("How do you detect a cycle with Kahn's?",
 "If processed count < V, the remaining vertices form a cycle (all have indegree>0). Return an error / empty order in that case."),
("What are classic toposort application problems?",
 "Course schedule (can finish all), course schedule II (the order), build-system dependency ordering, compiler header ordering, and task scheduling with prerequisites."),
("How do you solve 'Course Schedule'?",
 "Build adjacency (prerequisites), run Kahn's; return whether processed == numCourses. If yes, all courses can be finished without circular prerequisites."),
("How do you produce a lexicographically smallest toposort?",
 "Replace the plain queue with a min-heap of indegree-0 vertices so the smallest available label is always taken — O(V log V + E)."),
("What is the link between toposort and longest-path in DAGs?",
 "Processing vertices in topological order allows DP over predecessors: longest/shortest distance and counts are computable in O(V+E) — no Dijkstra needed in a DAG."),
("How does toposort determine the total time of a build?",
 "DP on topological order: end_time[u] = max over prerequisites (end_time[prereq] + cost[u]); the max is the minimal finish time — the scheduling answer."),
("Why can't undirected graphs be topologically sorted?",
 "Edge u—v would require u before v and v before u simultaneously, which is impossible unless degenerate; toposort is defined only for directed structures."),
("How do you find all topological orders?",
  "Backtracking Kahn's (each choice of an indegree-0 vertex branches); exponential output — report count or list carefully."),
]}