"""Curated Q&A for 07-HR-Preparation — answers personalised to Aayush's resume (SP DSE, Infosys)."""
HR = {
"01-Behavioral-Questions/01-Introduction-and-Self": [
("Introduce yourself.",
 "I'm Aayush Gid, a final-year B.Tech ECE student (2022-26) with a strong software engineering profile: I build AI/ML applications on Python — agentic AI at my internships, RAG systems like ScriptVector, and open-source contributions to Agno — and I'm applying because I love turning complex problems into reliable systems, which is what the SP DSE role is about."),
("Tell me about yourself in one minute.",
 "Script it in 3 beats: (1) education + current status, (2) the two things that show depth — my AI/MLE work (Krip AI, Clone Futura, NullClass) and my shipped projects (MigratorGen, ScriptVector, OpenRTL ai), (3) why Infosys SP DSE (scale, data engineering challenges, structured growth). Practice it out loud until it's 55-60 seconds."),
("Walk me through your resume.",
 "Group by time: internships (Krip AI — Agentic AI; Clone Futura — AI Agent Developer; NullClass — Data Science), then projects (MigratorGen, ScriptVector, OpenRTL ai), then achievements (SIH 2024 finalist, Techfest top-5, IEEE conference paper). For each: what problem, what you built, what result."),
("What are your strengths?",
 "Deep, applied engineering: I can take a GenAI concept (RAG, agents, evaluations) and ship a working, testable API on it (FastAPI + Docker + CI/CD), which I proved across three internships and open-source PRs to Agno."),
("What are your weaknesses?",
 "Pick a truthful, non-fatal one and show remediation: e.g., 'I sometimes dive deep into implementation before clarifying requirements — I now write a one-page spec and get it reviewed before coding, which saved rework in my script-migration project.'"),
("What is your biggest achievement?",
 "Being an SIH 2024 national finalist and publishing an IEEE conference paper — but frame your favourites: the IEEE paper shows research rigour, the finalist shows working under pressure on a real problem."),
("Where do you see yourself in five years?",
 "Growing from a strong engineer into a technical lead on data/AI platforms — I want to master industrial-scale data engineering and ML systems first, which the SP DSE role's breadth enables at Infosys."),
("Tell me about your family background.",
 "Be brief and positive — family support for your engineering journey, values of discipline and learning; keep it to 3-4 sentences; interviewers ask to gauge personality, not personal data."),
("What is your favourite subject and why?",
 "Data structures and machine learning — because both reward clean reasoning: DSA gives provable efficiency, ML gives systems that learn from evidence; my DSA fundamentals and AI internships both trace back to that."),
("What are your hobbies/interests?",
 "Open-source contribution (I've had PRs merged into Agno) and building side projects — frame hobbies as evidence of self-driven learning rather than just recreation."),
("Describe your daily routine / time management.",
 "I block my day: deep work in the morning (projects/learning), internship/collab work in the afternoon, and evenings open-source/reading — consistent habits, not just during exam season."),
("How did you prepare for this interview?",
 "Three tracks: (1) DSA revision on arrays/DP/graphs (SP DSE's known focus), (2) a deep-dive on my ML/GenAI projects so I can explain architecture and trade-offs, (3) Infosys research — its Data & Analytics practice to speak the company's language."),
],
"01-Behavioral-Questions/02-Team-Work": [
("Describe a time you worked in a team.",
 "Use my SIH 2024 finalist project: a 4-member team built a full solution from ideation to demo under a deadline — my role covered the AI/backend, and we soured by merging modules daily (Git), not at the end."),
("How do you handle disagreements in a team?",
 "I separate ego from evidence: discuss the constraint (time vs correctness vs cost) rather than the person, write down both options' trade-offs, and if it's not urgent, prototype the cheaper option to decide with data — e.g., choosing between prompt engineering vs fine-tuning for a demo."),
("How do you handle a teammate who isn't pulling their weight?",
 "First: clarify if it's a blocker or motivation (ask, don't accuse). Next: reassign scope to their strengths and offer pair sessions. If it persists, escalate with facts — a professional, non-personal approach interviewers want to hear."),
("What role do you usually take in a group?",
 "I'm naturally the systems person — I build the integration layer (APIs, data flow, CI) that makes everyone else's work composable; but I've also learned to step back and let specialists lead their part to avoid being a bottleneck."),
("How do you divide tasks in a project?",
 "By ownership boundaries, not arbitrary files: each person owns a module with a defined interface, integrations happen on a shared branch with CI tests — the git workflow is itself the coordination mechanism."),
("Tell me about a team achievement you're proud of.",
 "ScriptVector shipped end-to-end by turning the 'suggest relevant snippets' idea into a RAG pipeline (Gemini embeddings + Agno + SQLite) — the team contribution was my embedding/index design that made it fast enough to feel usable."),
("How do you give constructive feedback?",
 "Situation-Behaviour-Impact: specific example, the behaviour, the consequence — then a concrete suggestion. Framed as 'let's improve the outcome', never as blame."),
("How do you onboard a new team member?",
 "A short architecture walkthrough, a starter issue with a clear contract, and pairing on the first merge — I've done this informally at internships and it accelerates everyone."),
("How do you keep the team motivated under crunch?",
 "Visible progress: a shared board with small wins, slicing tasks into shippable chunks, and celebrating checkpoints — momentum beats coercion on a deadline."),
("Have you led a group? How?",
 "I've led technical workstreams — I set the architecture, distributed tasks by strengths, and unblocked failures — while remaining hands-on; leadership for me is coordination + accountability, not authority."),
],
"01-Behavioral-Questions/03-Conflict-Resolution": [
("Describe a conflict you faced at work or college.",
 "A real script: during the SIH project, two members disagreed on the tech stack (quick demo vs scalable). I proposed a spike to evaluate both under time constraints, we picked on evidence, and both agreed after seeing the numbers — conflict resolved by data, not hierarchy."),
("How do you handle a conflict with your manager?",
 "Respect the reporting line but disagree with reasons: prepare the facts and trade-offs, request a short discussion, and if overruled implement the direction without undermining it — documented, professional, then move on."),
("What if a teammate contradicts your technical decision?",
 "Listen for the constraint I missed; if I still disagree, I isolate the disagreement to a small comparison (benchmark, PoC) so we can decide by measurement — this resolved real debates in my agentic work."),
("How do you manage conflict in a deadline crisis?",
 "Re-scope together, make the priority call explicit, communicate the change to stakeholders, and keep the team aligned on the single top priority — conflict under pressure is really a prioritisation failure."),
("How do you apologise professionally?",
 "Take responsibility immediately, state the exact cost, and name the fix you'll implement to prevent a repeat — then do it; accountability is a differentiator in freshers."),
("How do you handle being criticised in a review?",
 "Treat it as free diagnostic data: ask for the specific case or metric behind it, test whether it's true, and respond with a change in behaviour — then briefly follow up that you've addressed it."),
("What if a client/lead demands something you believe is wrong?",
 "Unpack what they actually need under the demand, propose the safer path with evidence, and escalate only after a clear discussion — most 'wrong' demands are about unmet communication, not bad intent."),
("How do you resolve a dispute between two juniors?",
 "Meet them separately for facts, then together for the decision, keeping it about the outcome — I'd apply the same mediation rhythm to any peer pair."),
("What do you do when a conflict repeats?",
 "Identify the pattern (usually ambiguous ownership, unclear requirements, or status mismatch) and fix the root cause structurally — e.g., add a written interface contract rather than relitigating the same argument."),
("Can you handle criticism constructively in code review?",
 "Yes — I've had Agno reviewers push back on my PRs; I treated each comment as an improvement to land, not a judgment, and the merged PR got better for it. That's the disposition I keep."),
],
"01-Behavioral-Questions/04-Leadership": [
("Have you ever taken a leadership role?",
 "Technically yes — I led the AI/backend workstream in my SIH team and drove open-source PRs to completion: I set the architecture, assigned tasks, and owned integration risk end-to-end."),
("What does leadership mean to you?",
 "Raising the team's output by removing ambiguity: clarity of goal, clarity of ownership, and psychological safety to fail fast. Not rank — responsibility."),
("How do you motivate teammates?",
 "By making the work make sense — connecting tasks to the end goal, giving early wins, and letting people own their modules; motivation is mostly autonomy and clarity."),
("What would you do as a new lead in your first week?",
 "Listen before deciding: one-on-ones, map the existing codebase and pipelines, find the top bottleneck (usually the CI/deploy pain), and fix one visible thing quickly to earn trust."),
("How do you assign work to a team you don't know yet?",
 "Start with a skills/stakes mapping conversation, assign by strengths and growth goals, and add code-reviews as a safety net until I learn each person's quality bar."),
("Describe a time you influenced without authority.",
 "In the SIH team I convinced peers to adopt a shared Git workflow for integration — I demonstrated the benefit with a five-minute demo and got buy-in voluntarily, without being the 'leader'."),
("How do you handle a hard deadline as a lead?",
 "Work backwards from the deadline: freeze scope, parallelise by module boundaries, gate promotions by tests, and communicate risk honestly earlier — panic doesn't ship software."),
("What is the difference between a leader and a manager?",
 "A manager administers scope, process, and performance; a leader sets direction, removes blockers, and models the standards — I'd aim to blend both, weighted by situation."),
("How do you celebrate a win as a lead?",
 "Attribute it loudly to the team by name and log what worked (retro note) so the next project benefits — wins are fuel and documentation at once."),
("What would your team say about you as a lead?",
 "That I'm clear about what 'done' means, that I code beside them rather than above them, and that I take the final responsibility for integration failures — that's the reputation I build."),
],
"01-Behavioral-Questions/05-Failure-and-Learning": [
("Describe a time you failed.",
 "A strong, genuine script: an early version of Mapie or ScriptVector's retrieval returned poor relevance because I picked naive chunking — I had to re-architect the chunking + reranking, and it taught me to prototype retrieval quality before building the full app."),
("What is your biggest mistake and what did you learn?",
 "Ship-too-late perfectionism: I over-engineered before validating the core assumption. Lesson: validate the riskiest assumption first with a 2-day spike — I now do exactly that before building."),
("Have you ever missed a deadline?",
 "If asked, answer honestly with root cause (over-optimistic estimates), the mitigation you added (buffer + earlier comms), and end with the time you turned a near-miss into an on-time delivery."),
("What do you do when you don't know something?",
 "I say 'I don't know yet' and name the plan to find out (docs, experiment, ask a senior), then follow through — honesty plus a learning loop, not bluffed silence."),
("What is your biggest technical challenge?",
 "Making RAG retrieval reliable for code snippets — semantically similar but contextually different code collides in embedding space; I learned to combine embeddings with metadata filters and a reranker."),
("How do you learn from failure?",
 "A personal post-mortem: what was the assumption, where did it break, what's the new rule — I keep these notes and they become my interview stories because they're structural, not anecdotal."),
("Tell me about a bug that took long to fix.",
 "Chose an honest story: an LLM pipeline producing subtly wrong outputs because of prompt-cache/token-order issues — I added structured logging and traced the actual payload, not the assumption."),
("How do you handle rejection?",
 "Ask for specific feedback, separate my work quality from the outcome, and target one concrete improvement next — SIH/Techfest rounds and rejected PRs all taught this."),
("What do you regret or would do differently?",
 "I'd have started contributing to open source and doing internships earlier — the compounding value of real code under review is the biggest accelerator I've found."),
("How do you stay updated as technology changes?",
 "A learning stack: official docs for depth, release notes for signal, and building something weekly for retention — I learned LangChain/LangGraph/Agno the same way; curiosity is a habit."),
],
"01-Behavioral-Questions/06-Stress-Management": [
("How do you handle pressure?",
 "I convert pressure into a tight plan: define the smallest shippable step, protect my sleep and focus blocks, and communicate early when estimates slip — calm comes from structure."),
("Describe a stressful situation you handled well.",
 "SIH 2024 finals: a demo-critical integration broke hours before. I split the team — one fixed the pipeline, one prepared a fallback demo — prioritised impact over instinct, and we delivered. Structure beat panic."),
("How do you manage multiple deadlines?",
 "A single ranked list by impact-and-deadline, time-blocked in my calendar, with buffer between them; I re-rank daily. Tools (boards, checklists) keep the stress out of my head."),
("What do you do to de-stress?",
 "Exercise, focused breaks, and stepping away from the screen — I've learned that a walk clears an LLM or regex bug faster than staring at it; interviewers are listening for maturity, not hobbies."),
("How do you handle unclear requirements?",
 "I ask targeted questions and write a 1-page interpretation for confirmation — ambiguity shrinks fast when you make assumptions explicit early."),
("How do you respond to urgent requests during deep work?",
 "Acknowledge immediately, give a realistic ETA, and negotiate scope; I minimise context switching by batching such requests rather than dropping everything mid-task."),
("What if you are too overloaded to finish on time?",
 "I surface it early with the data (what's done, what remains, options), propose re-prioritisation or help, and never silently miss — early honesty is the professional move."),
("How do you keep quality high under a tight deadline?",
 "Cut scope deliberately before cutting quality: freeze the essential contract, defer nice-to-haves to a follow-up, and keep tests on the critical path — quality of what ships matters most."),
("How do you cope with repetitive or monotonous tasks?",
 "Automate what's automatable (scripts, templates) and batch what isn't; productivity tricks keep monotony from becoming a quality risk — my scripting background helps here."),
("What makes you anxious at work and how do you manage it?",
 "Honest example: presentating/demos — I prepare ruthlessly (dry runs, fallbacks) until over-preparation neutralises anxiety; acknowledging the trigger and building a system is the answer they want."),
],
"01-Behavioral-Questions/07-Problem-Solving-Scenarios": [
("A client changes requirements mid-project. What do you do?",
 "Assess impact (scope, time, cost), discuss options with trade-offs, get an explicit decision, then communicate the revised plan to the team — change is data, not a crisis."),
("Your code works locally but fails in production. How do you debug?",
 "Controlled comparison: environment differences (versions, filesystem, DB), log the actual failure, reproduce in a prod-like container, and bisect assumptions — I'd start with env drift since that's the usual culprit."),
("A junior asks for help every 10 minutes. How do you respond?",
 "Help them learn, not just complete: ask what they've tried, walk the reasoning together, and point to a reference to build independence — while carving one quiet deep-work block before they return."),
("A new hire disagrees with your code structure. What now?",
 "Ask for their rationale — a fresh perspective often catches real issues; if there are trade-offs, compare them concretely on a small example and decide with the team's standard, not ego."),
("Production breaks at 2am and you're on call. What's your process?",
 "1) Stop the bleed (rollback/feature-flag), 2) gather evidence (logs, metrics, trace), 3) find root cause, 4) fix with a test, 5) post-mortem. Fix forward with escalation only if the fix is risky."),
("Your team is split 50/50 on an approach. How do you break the tie?",
 "Frame a falsifiable comparison: pick the cheapest experiment that discriminates (benchmark, spike, survey of users), set a time box, and let measurement decide — consensus isn't required when data exists."),
("Your senior makes a technical recommendation you strongly disagree with. What do you do?",
 "Prepare the specific evidence for my view, raise it respectfully once with the fuller context in mind, and if still overruled, implement their direction well — while making the outcome measurable so the right call shows."),
("A stakeholder gives you vague praise but no concrete feedback. How do you improve?",
 "Ask for one specific example of what went well and one thing to try next; convert vague signals into a targeted experiment — feedback is a requirement you should be expected to clarify."),
("You find a severe security issue in a shipped feature. What's your process?",
 "Severity assessment, immediate containment (disable/rollback), notify the right people without delay, then root-cause and fix with a regression test — in that order; secrecy is not the same as prudence."),
("You inherit a messy legacy codebase. How do you start?",
 "Read the entry point and core data flow, map documented behaviour before changing anything, add a characterisation test on the riskiest path, then refactor in small verified steps — understand before improving."),
],
"02-Infosys-Specific/01-About-Infosys": [
("What do you know about Infosys?",
 "Infosys is a global digital services and consulting leader (founded 1981, Bengaluru; ~300k+ employees). It runs practices across AI/Data, cloud, digital engineering, and consulting — and its Infosys Topaz AI platform and Data practice are where the SP DSE role sits. Answer with 3 planks: scale, innovation, and culture."),
("What are Infosys's main service lines?",
 "Data & Analytics, AI (Topaz), Cloud & Infrastructure, Digital Experience, Enterprise Solutions (ERP), and Cybersecurity — data/AI is strategically central, which is exactly the SP DSE growth path."),
("Who is the CEO and why does it matter?",
 "Salil Parekh leads Infosys (since 2018); knowing this shows genuine interest — and you can tie it to Infosys's AI-first strategy under his tenure."),
("What is Infosys Topaz?",
 "Infosys's AI-first offering — platform, frameworks, and solutions to industrialise AI across its clients; mentioning it shows you've done current research on the company you're joining."),
("What is Infosys's business model?",
 "IT services and consulting: design, develop, and operate technology for enterprise clients (banking, retail, telecom, healthcare) with global delivery centres — including India as the delivery talent hub."),
("What are Infosys's strengths vs competitors?",
 "Breadth of scale and delivery models, strong data/AI investments (Topaz), robust training infrastructure, and a global distributed engagement model; the SP DSE path taps that training depth."),
("What do you know about Infosys's campus or training?",
 "Infosys runs one of the industry's largest training programmes ('Train–Hire–Deploy' with world-class training centres in Mysuru etc.), known for structured conversion of freshers into client-ready consultants."),
("Why is Infosys considered a strong fresher destination?",
 "Structured onboarding, global project exposure, clear career tracks (Specialist) and scholarships, plus the scale to encounter real enterprise data problems — a strong launchpad for a DSE."),
("Name Infosys's major client industries.",
 "Banking & financial services, energy, retail/CPG, telecom, healthcare, and public sector — speak to one (banking) with a data/AI angle to show domain awareness."),
("What values does Infosys promote?",
 "Client value, leadership by example, integrity & transparency, fairness, and excellence ('Infosys 5 values') — mirror them in your answers and delivery approach."),
],
"02-Infosys-Specific/02-Why-Infosys": [
("Why do you want to join Infosys?",
 "Three specific reasons: (1) Infosys's data & AI scale gives SP DSE exposure to industrial datasets and pipelines I can't see anywhere else, (2) the structured specialist growth path matches my plan to deepen into data engineering + ML, (3) a company investing in Topaz/AI means my GenAI skills meet real enterprise problems immediately."),
("Why Infosys and not another IT services company?",
 "Compare deliberately, not dismissively: Infosys's Topaz AI-first push, its training depth for freshers, and its data practice breadth fit my AI/ML profile better than a more general services or product role."),
("Why should we hire you over other candidates?",
 "Because I bring shipped AI work, not just coursework: three internships in agentic/DS, projects like ScriptVector and MigratorGen, merged open-source PRs to Agno, and SIH finalist discipline — plus the Python/DSA/DBMS fundamentals SP DSE needs."),
("What attracts you to the SP DSE role specifically?",
 "It combines exactly what I like: solving real data problems (DSA + SQL + data pipelines) in a specialist stream with Infosys's training and project variety — a structured path from data structures to data engineering."),
("How do you align with Infosys's transformation to an AI-first company?",
 "I've lived the AI lifecycle — RAG, agentic frameworks, evaluation — and I can bring that into data engineering work; joining a company explicitly investing in Topaz means my skills are a current asset, not a future one."),
("What is your 2-year vision at Infosys?",
 "Year 1: master the SP DSE core — DSA, databases, data engineering tools — on real client projects. Year 2: specialise into data engineering/AI pipelines and start contributing to internal engineering IP and knowledge-sharing."),
("Why are you choosing services over a product company?",
 "Services offer breadth: different domains, datasets, and techniques on a fast cycle — early-career breadth I value more than product depth right now; I can always deepen later."),
("What do you know about Infosys's specialist (SP) path?",
 "Infosys Specialist Programme tracks distinguish top freshers into specialised streams (Data Engineering/System/Digital etc.) with dedicated training, mentors, and faster growth — SP DSE means I'm committing to a technical stream, not a generic bench."),
("Why DSE — why not System or other specialist tracks?",
 "DSE is the intersection of my two loves — data structures and applied AI: I want to build the pipelines and platforms that make AI real, and DSE is the direct route to that craft."),
("Are you open to roles different from what you applied for?",
 "Yes — my fundamentals (Python, DSA, SQL) transfer; I'd say I'm flexible on role as long as it's in the data/AI direction, and I'll bring the same energy to whatever the business needs."),
],
"02-Infosys-Specific/03-SP-DSE-Role-Specific": [
("What does a Data Services/Data Engineering Specialist do?",
 "The SP DSE role sits in Infosys's Data practice: building data pipelines (ingestion, transformation, quality), database systems, and the data foundations that feed analytics and AI — combining DSA thinking, SQL, scripting, and engineering discipline."),
("What skills does a DSE need?",
 "Programming (Python — my core), databases (PostgreSQL/SQLite) and SQL, data pipelines and ETL thinking, data structures for performance, debugging, and basic ML once data flows — exactly the stack I already work in daily."),
("How is DSE different from a generic developer role?",
 "The emphasis is on data: volume, quality, movement, and storage correctness — DSE engineers are the ones making data computable and trustworthy before anyone models on it."),
("What will you contribute in your first project?",
 "Reliability from day one: clean ETL scripts, tested data transformations, clear SQL, and documentation — I'll bring the discipline of writing tested code to data pipelines immediately."),
("What do you know about data pipelines?",
 "Ingest (batch/stream) -> validate -> transform -> store -> serve; orchestration, idempotency, and monitoring — I can map my RAG ingestion pipeline (chunk->embed->index) as a mini data pipeline and scale that understanding."),
("Why do DSA skills matter for a DSE?",
 "Real pipelines hit performance walls: joining millions of rows, hash-partitioning, windowing, index design — the same complexity reasoning as DSA, applied to data at scale."),
("How does your ML background help in a DSE role?",
 "ML is downstream of data quality — understanding what features/embeddings need (clean, typed, well-split data) makes me a better data engineer, not just a better model-builder."),
("What is your comfort level with large datasets?",
 "I've processed datasets with pandas/NumPy and built pipelines for code corpora (ScriptVector) and scripts (MigratorGen); comfortable with batch processing, and eager to learn the true scale tooling — Spark/data lake — that enterprises use."),
("What tools do you want to learn first in this role?",
 "Spark/Hadoop for scale, a workflow orchestrator (Airflow), and cloud data services — I'd map each to what I already know (pandas/ETL patterns) so the ramp is fast."),
("How do you stay productive as a DSE on a long project?",
 "Tests, documentation, and incremental delivery: pipelines decompose into unit-testable stages — the same habits that keep ML projects honest; plus observability (logging, data-quality checks) from the start."),
],
"02-Infosys-Specific/04-Training-and-Growth": [
("How do you feel about the initial training period?",
 "I see training as an investment I'd optimise: I'd go beyond the curriculum — practise extra problems, learn the tools deeply, and help peers — and enter the project phase stronger than the minimum."),
("What do you expect from Infosys's training programme?",
 "Structured foundations in the stack (Data Engineering tooling, DSA, databases), mentoring, and real project simulation — I expect to absorb the discipline as much as the content."),
("How do you handle learning a new technology quickly?",
 "My method: official quickstart for 30 minutes, build a tiny end-to-end example, then a real-ish task with tests — I've ramped on LangChain, LangGraph, Streamlit, and FastAPI exactly this way."),
("Are you willing to relocate/work from any Infosys location?",
 "Yes — flexibility is part of the deal and I'm eager to work from Infosys campuses and client sites: I've prepared for relocation as part of the specialist onboarding."),
("How do you plan your growth in the first 3 years?",
 "Specialist track: master the DSE craft (pipelines, databases, quality), earn internal certifications, take on harder modules, and eventually mentor juniors — growth by deepening, not hopscotching."),
("What certifications are you willing to pursue?",
 "Cloud (AWS/azure data certs), database (PostgreSQL), and data engineering certs — relevant, employer-aligned, and compatible with project work."),
("How do you handle a role that starts simpler than your expectations?",
 "With humility and intent: every production codebase has depth — I'd master the simplest module completely before asking for more; credibility is built before ambition is granted."),
("What does career growth look like at Infosys?",
 "From Specialist to Specialist Lead/Architect tracks via performance, certifications, and increasingly complex ownership — I've researched the SP path so my answer shows I'm planning, not just hoping."),
("How open are you to switching domains within Infosys later?",
 "Open — data engineering, analytics, or AI consulting later; the common thread is the data/AI direction, and I'd follow the work that challenges me most."),
("What will make you successful in a consulting environment?",
 "Consulting is delivery discipline: understanding the client's business driver, coding to the contract, communicating progress early — the exact behaviours I've built shipping products against deadlines."),
],
"02-Infosys-Specific/05-Company-Culture": [
("Why do you fit Infosys's culture?",
 "Infosys values client value, integrity, and continuous learning — I model continuous learning (open source, internships), communicate transparently (early risk-raising), and take ownership of outcomes, all of which match."),
("How do you feel about working in a large organisation?",
 "Productively: large orgs mean strong processes, diverse projects, and mentorship I'd use well; I'm organised enough to thrive amid the process, not fight it."),
("What is your understanding of Infosys's 'Client Value' principle?",
 "That output means nothing unless it moves the client's business — I bring that by asking 'what does this deliver?' and wiring data work back to business outcomes."),
("How would you handle a situation where a client request conflicts with Infosys policies?",
 "Raise it with the account lead with a professional explanation, document the concern, and follow the escalation path — integrity is a deliverable too."),
("How do you work with global, distributed teams?",
 "Written clarity over verbal shortcuts: documented decisions, timezone-aware async communication, and clear ownership — I've worked asynchronously on open source and remote internships."),
("What do you know about Infosys's sustainability efforts?",
 "Infosys has been carbon-neutral in its operations for years and runs 'Infosys Zero' initiatives — mentioning it shows research depth and value alignment beyond money."),
("How do you view teamwork across cultures?",
 "As a skill: different timezones and communication norms are just another interface to engineer — I ask, assume good intent, and write things down so alignment holds."),
("What work environment do you prefer?",
 "One with feedback loops and ownership: clear scope, honest reviews, and the autonomy to debug my own failures — that's what Infosys's project teams provide."),
("How do you handle a senior colleague's differing work style?",
 "Adapt my interface to theirs (detail vs big-picture, sync vs async) without changing my technical standards — working styles are constraints, not threats."),
("What does integrity mean to you in software?",
 "Saying 'I don't know', logging what actually happened, not misrepresenting progress, and owning mistakes — the technical translation of Infosys's integrity value."),
],
"03-Salary-and-Negotiation/01-CTC-Understanding": [
("How is CTC different from in-hand salary?",
 "CTC includes employer-paid components — basic, HRA, allowances, PF/gratuity, insurance, and variable pay; in-hand is what actually lands monthly after deductions — citing this distinction shows you understand offer letters."),
("What is a variable pay or bonus component?",
 "Performance-linked pay paid periodically (often annual) based on individual and company performance — not guaranteed monthly; treat it as upside, not base."),
("What fixed vs variable split should you expect?",
 "Fresher offers are mostly fixed with a small variable/performance component; I'd ask the recruiter for the exact split and the variable's frequency and threshold before signing."),
("What deductions are standard in Indian offers?",
 "Employer PF + employee PF, gratuity, and professional tax reduce gross; the rest largely reaches your account — a quick deduction walkthrough shows financial literacy."),
("What is the difference between gross and net salary?",
 "Gross = total earnings before deductions; net = what's banked after PF/gratuity/professional tax — always compute net before committing to expenses."),
("How would you evaluate an offer beyond CTC?",
 "Effective hourly rate, training quality, role growth, project exposure, work location, and benefits (insurance, learning budget) — CTC alone overvalues less-critical-per-kg offers."),
("What is joining bonus vs retention bonus?",
 "Joining bonus is paid at onboarding (usually clawed back if you leave within a window); retention bonus rewards staying — two different incentives to read carefully."),
("What salary range would be acceptable for your role?",
 "State a researched, confident-but-flexible range for SP DSE — anchor on market rates for Infosys specialist freshers and say the primary driver is learning and role fit — never say 'whatever you give'."),
("How do you plan your expenses with a variable income?",
 "Budget on fixed in-hand, treat variable pay as savings/investment, and keep an emergency buffer — a disciplined answer shows maturity in stability and planning."),
("What is the employer's perspective on Fresher compensation?",
 "They price in training cost, deployment velocity, and market bands — so negotiating leverage comes from demonstrated skills, not needs; I'd negotiate on evidence, not urgency."),
],
"03-Salary-and-Negotiation/02-Negotiation-Tips": [
("How do you negotiate as a fresher?",
 "Ask for clarity first, negotiate on evidence (projects, achievements, competitive offers), and separate needs (base) from wants (variable, benefits) — then anchor with a researched range, not an ultimatum."),
("What is your expected salary?",
 "A polished EN: 'I'm primarily interested in the role and growth; based on my research and my AI/ML project experience, I'd expect a fresher specialist band like INR X-Y, and I'm open to a fair market offer.' — flexible but confident."),
("Should you disclose other offers?",
 "Only if it's true and you're prepared to walk — a verified competing offer is legitimate leverage; inflating it risks credibility you can't afford in this industry."),
("How do you respond to a lower-than-expected offer?",
 "Thank them, ask for the reasoning (band structure, min-max), restate your value with one concrete line, and counter with a researched number — always professional, never resentful."),
("What would you do if salary is non-negotiable?",
 "Negotiate the rest: joining bonus, certification budgets, location preferences, or earlier review dates — total package negotiation beyond the number."),
("How does negotiation work for campus/rollover offers?",
 "Individually varied — when eligible, negotiate on asymmetric strengths (internship performance, strong project portfolio, certifications) and be genuinely prepared to decline on principle."),
("What is the single most useful negotiation tactic?",
 "Silence and specifics: present a researched anchor, then stop talking — the next person to speak often concedes; and never negotiate emotionally."),
("What factors other than money would you negotiate?",
 "Learning budget, project assignment preference, onboarding time, and relocation support — durable value often sits outside the CTC line."),
("How do you avoid a salary negotiation backfiring?",
 "Keep the tone collaborative ('help me understand the band'), never issue ultimatums without a brick-and-mortar alternative, and know your walk-away number in advance."),
("What is the walk-away point concept?",
 "The minimum offer under which you'd decline — decided BEFORE negotiation so emotion doesn't decide it — the discipline behind professional negotiation."),
],
"04-Common-HR-Questions/01-Classic-HR-Questions": [
("Tell me about yourself.",
 "Same structured intro: education -> AI/ML engineering evidence (internships, projects, open source) -> why SP DSE/Infosys — trimmed to ~60 seconds, rehearsed to sound spontaneous."),
("Where do you see yourself in 5 years?",
 "Technical deepenening: from specialist to a data/AI technical lead — but with a growth-oriented framing: 'I want to be someone they trust with harder and harder data problems'."),
("What are your strengths and weaknesses?",
 "Strength: applied engineering (shipping GenAI products with tests/CI). Weakness: over-researching before building — mitigated by time-boxed spikes. Always pair weakness with the fix."),
("Why should we hire you?",
 "Because I combine AI/ML depth (internships, projects, IEEE paper, SIH) with software fundamentals (DSA, DBMS, Python) — the exact blend the SP DSE role needs, and I've proven I can ship."),
("Why do you want to work with us?",
 "Reference their specifics: Infosys's data/AI scale, Topaz, the SP DSE specialist track, and global projects — companies hire people who did homework."),
("What do you know about our company?",
 "Give 3 researched facts you can defend: founded 1981, ~300k+ employees, data/AI-first strategy, training scale, key industries — no vague fluff."),
("Are you willing to travel or relocate?",
 "Yes, enthusiastically, with a reason (learning from global teams) — and confirm flexibility on location as part of onboarding."),
("What are your salary expectations?",
 "A researched range with flexibility and a stated interest in the role over the number — rehearsed so it doesn't catch you off-guard."),
("Why are you interested in this position?",
 "Because SP DSE mixes DSA/SQL/data engineering with the AI trajectory I've been building toward — it's the intersection of what I'm good at and where I want to grow."),
("What is your long-term career vision?",
 "Technical excellence with leadership: become a data/AI expert whom teams trust to design the pipeline and explain it to clients — built on the specialist track and deepened skills, not title-chasing."),
("Tell me about a time you showed initiative.",
 "Merged open-source PRs to Agno without being asked, and built ScriptVector/MigratorGen as self-driven projects — initiative demonstrated by shipped, public work."),
("What motivates you?",
 "The moment a difficult system works end-to-end — a pipeline, an agent, a benchmark — and the visible user value it creates; evidence-backed motivation reads better than adjectives."),
],
"04-Common-HR-Questions/02-Unexpected-Questions": [
("If you were a vegetable, which would you be?",
 "A light one that still shows character: 'a potato — versatile, works in any stack, and becomes something amazing when prepared properly' — answer smoothly and briefly, don't overthink it."),
("Tell me a joke.",
 "Keep it clean and quick — a short one-liner; the point isn't the laugh, it's your composure under a deliberately weird prompt. Have 1-2 ready."),
("If you could meet anyone, dead or alive, who would it be?",
 "Pick someone tied to your field (e.g., a pioneer of AI/software systems) and say why one conversation with them would change your practice — shows intellectual curiosity, not celebrity."),
("What would you do if your interviewer disagreed with you in this interview?",
 "Respectfully probe their view, share my reasoning without insisting, and acknowledge if the stronger argument is theirs — demonstrating the disagreement-handling answer in real time."),
("Describe a time someone changed your mind.",
 "A technical example: peer criticism of my retrieval approach in ScriptVector — I benchmarked their suggestion, saw it won on relevance, and switched; shows adaptable, evidence-driven thinking."),
("If you won a lottery today, would you still work?",
 "Yes — the point of work for me is mastery and impact, not necessity; I'd choose harder, self-directed engineering goals sooner but still build things for real users."),
("What is something you have no talent for?",
 "Pick something harmless (e.g., sketching/painting) and note you respect it — it shows humility and self-awareness without compromising professional perception."),
("How would you explain your project to a five-year-old?",
 "Use the ScriptVector example: 'I built a robot that remembers hundreds of code tricks, and when you ask it a question it finds the best trick to answer' — a clear, simple mental model communicates depth."),
("Which animal represents your work style?",
 "Pick one with a story: 'an owl watching then diving precisely' (or a bee — systematic) — any answer is fine as long as you attach the reasoning quickly."),
("If you had a superpower, what would it be?",
 "Something work-relevant: 'perfect recall, so I never forget a stack trace or a design decision' — self-deprecating + professional beats generic flying."),
("What would you do differently if you were the interviewer?",
 "Ask one candidate question I wish I'd been asked — I'd ask about a time they handled ambiguous requirements, since that predicts delivery quality more than most other questions."),
("What are the five things in your pocket right now?",
 "Humour with honesty: phone, wallet, earbuds, a notebook, and confidence — demonstrate calm creativity under a purposefully absurd prompt; do not freeze."),
],
"04-Common-HR-Questions/03-Questions-to-Ask-Interviewer": [
("What would a typical first 6 months look like for a new DSE?",
 "Show intent to onboard well: training scope, first-project assignment, and mentorship structure — also signals you're planning, not just landing."),
("What does success look like in this role after one year?",
 "You're asking about measurable expectations — the strongest single question to align your effort with the team's definition of 'good'."),
("What is the team's current data/AI focus and biggest challenge?",
 "Data practice at Infosys is investing hard in AI — this question shows you see the big picture and are already thinking about contribution."),
("How does the SP DSE path progress into a specialist lead/architect?",
 "Shows you understand the specialist programme and are career-planning within the organisation, not hopping at the first chance."),
("What are the growth opportunities for someone with an AI/ML background?",
 "Positions you to be placed where your strengths fit, and shows confidence in your differentiation — while staying in the data track."),
("What are the current technical challenges the data team faces?",
 "A team-solving question: you're asking to be useful, not just employed — interviewers remember candidates who think about work before joining."),
("What would make a candidate stand out in this team's eyes?",
 "A direct, low-risk way to hear how they'd want you to perform — and any answer you get becomes your onboarding roadmap."),
("How is feedback and performance review structured here?",
 "Shows you want to improve measurably (matches Infosys's development culture) and are comfortable with honest evaluation."),
("What technologies does the data practice currently standardise on?",
 "Evidence of real interest in the craft — and it lets you map your skills (Python, SQL, pipelines) onto their stack immediately."),
("What advice would you give someone starting here?",
 "Respectful, open-ended, and relationship-building — and it hands them the chance to mentor you before you've even started."),
],
}