"""Curated Q&A for 01-DSA/03-Linked-Lists and 04-Stacks-and-Queues."""
LL = {
"03-Linked-Lists/01-Singly-Linked-List": [
("Define a singly linked list node.",
 "Each node holds data and a pointer/reference to the next node; the list is traversed from a head pointer. Insertion/deletion at the head is O(1); access by index is O(n)."),
("Why is linked-list access slower than array access?",
 "No contiguous memory, so random access is impossible; you must follow next pointers from the head, giving O(n) worst-case element access."),
("How do you insert a node at the head of a singly linked list?",
 "nxt = head; head = Node(val); head.next = nxt. Constant time O(1), no reallocation needed."),
("Write code for inserting into the middle (after a given node).",
 "new.next = prev.next; prev.next = new. O(1) given the previous node reference; otherwise find it first (O(n))."),
("How do you delete a node given only a pointer to it (no head)?",
 "Copy the next node's value into the current node, then delete the next node (skip it). This works only when node is not the tail."),
("How do you reverse a singly linked list iteratively?",
 "prev=None; while curr: nxt=curr.next; curr.next=prev; prev=curr; curr=nxt; return prev. O(n) time, O(1) space."),
("What recursion pitfalls arise when reversing a linked list?",
 "Deep recursion could stack-overflow on long lists; also be careful to set head.next=None to avoid cycles. Iterative is preferred for interviews unless asked for recursion."),
("How do you find the middle node using two pointers?",
 "slow += 1, fast += 2; when fast or fast.next is None, slow is the middle (upper-middle for even length). O(n)."),
("How do you detect and find the start of a cycle (Floyd's)?",
 "slow/fast collide -> cycle exists. Reset one pointer to head; advance both one step; their meeting point is the cycle's start node. O(n)."),
("How do you find the length of a cycle?",
 "Once Floyd detects a meeting point, keep one pointer fixed and walk the other around until it returns; count steps. That length is the cycle length."),
("How do you remove the Nth node from the end?",
 "Advance a fast pointer n steps, then move slow and fast together; when fast reaches end, slow's next is the node to delete. Single pass, O(n)."),
("How do you merge two sorted linked lists?",
 "Dummy head + two-pointer: attach the smaller of l1/l2 and advance; drain the remainder. O(n+m) time, O(1) space (reuses nodes)."),
("How do you merge k sorted lists (priority-queue approach)?",
 "Push all list heads into a min-heap; repeatedly pop the smallest, append, and push its next. O(total * log k)."),
("How do you find if two linked lists intersect?",
 "Align lengths (advance the longer by the difference) or swap pointers after each hits its tail; the node where they meet is the intersection. O(n+m)."),
("How do you find the Kth node from the end without extra space?",
 "Move a first pointer k steps ahead; then walk both until first is null — second now sits at the kth-from-end. O(n) single pass."),
("What is the dummy-head technique and why is it useful?",
 "A sentinel node precedes the real head, so insertions/deletions at the front don't need special cases; return dummy.next at the end."),
("How do you check if a linked list is a palindrome?",
 "Find the middle, reverse the second half, compare halves node-by-node; optionally restore the list. O(n) time, O(1) space."),
("How do you remove duplicates from a sorted linked list?",
 "Walk comparing node.val with node.next.val; if equal, skip the next node. O(n). For unsorted, use a seen-set (O(n) space)."),
("How do you remove all nodes equal to a given value?",
 "Dummy head + prev pointer; if node.val == val, skip; else advance prev. Handles head deletion cleanly. O(n)."),
("How do you add two numbers represented by reversed linked lists?",
 "Iterate both lists with carry; create a node for each digit sum%10, carry=sum//10; drain remaining plus final carry. O(n)."),
("How do you rotate a linked list right by k?",
 "Compute length, k%=len; if 0 return. Find tail and (len-k)th node; relink tail to head and split there; update head. O(n)."),
("How do you reorder a list (L0,Ln,L1,Ln-1,...)?",
 "Find middle, reverse the second half, then interleave the two halves at the head. O(n)."),
("How do you detect a cycle with O(1) space other than Floyd?",
 "Floyd's is the classic O(1)-space option. Alternative: reverse traversal marking is destructive and invalid; so Floyd's is the answer for the space constraint."),
("How do you split a circular linked list into two halves?",
 "Find the middle (slow/fast) and the tail; break links and close each half into its own circular list. O(n)."),
("When would you use a linked list over a dynamic array?",
 "Frequent insertions/deletions in the middle or head at scale, no random access needed, and when memory must not be wasted pre-allocating. Trade-off: cache-unfriendly pointers."),
("Why are linked lists cache-unfriendly?",
 "Nodes are scattered in memory, defeating CPU cache prefetching; arrays exploit spatial locality, so in practice arrays often win even when asymptotics look worse."),
("How do you delete a middle node given only current node?",
 "value copy + skip the successor is the standard 2-step; this is the 'Delete Node in a Linked List' problem."),
("How do you swap nodes in pairs?",
 "Iterative: prev/dummy + first/second; relink pairs: second.next=first, first.next=rest, prev.next=second. O(n)."),
("How do you reverse nodes in k-group?",
 "Count k nodes; if present, reverse the group and recurse/iterate on the remainder; otherwise leave as-is. O(n)."),
("Explain insertion sort on a linked list.",
 "Build a new sorted list by inserting each node at its sorted position using dummy head comparisons. O(n^2) worst but O(1) space."),
("How do you partition a linked list around a value x?",
 "Build two lists (less-than and greater-or-equal), connect them, ensure the tail is None. Stable partition, O(n)."),
("What is a self-looped linked list and a dangerous consequence?",
 "A cycle or wrong tail references; infinite traversal loops and memory leaks in releases. Always terminate loops on None checks."),
],
"03-Linked-Lists/02-Doubly-Linked-List": [
("Define a doubly linked list node.",
 "A node holds data, a next pointer, and a prev pointer. Traversal works both directions; deletion of a known node is O(1) without needing its predecessor."),
("What is the extra cost of a doubly linked list?",
 "One extra pointer per node (memory and cache pressure), plus more pointer updates on insertion/deletion compared to singly linked lists."),
("How do you insert at the head of a DLL?",
 "new.prev=None; new.next=head; if head: head.prev=new; head=new; also update tail for empty list. O(1)."),
("How do you delete a node known by pointer in a DLL?",
 "node.prev.next = node.next; node.next.prev = node.prev; then free. O(1) because both neighbours are reachable — this is the DLL's key win over singly."),
("How do you implement a LRU cache with a DLL + hash map?",
 "Hash map key -> node. Get: move node to head. Put: if exists update+move; else add at head, evict tail when full. O(1) for both using head/tail sentinels."),
("Why are sentinels (dummy head/tail) standard in DLL code?",
 "They eliminate null-checks on prev/next during removal and movement, reducing edge-case bugs substantially in LRU-style problems."),
("How do you reverse a doubly linked list?",
 "Swap each node's prev and next while traversing; at the end, swap head and tail. O(n)."),
("How do you remove the last element (tail) O(1)?",
 "Given tail pointer: tail = tail.prev; tail.next = None. Guard for single-node lists. LRU eviction uses exactly this."),
("Name the classic DLL-based problems.",
 "LRU Cache, LFU Cache (with frequency buckets), design of text editors / undo, browser navigation history, and union/find-adjacent operations."),
("How do you convert a DLL to a circular DLL?",
 "Connect head.prev = tail and tail.next = head. Afterwards traversal can wrap; mark clearly during algorithms to avoid infinite loops."),
],
"03-Linked-Lists/03-Circular-Linked-List": [
("Define a circular linked list.",
 "The tail node's next pointer points back to the head (or the list has no null terminator). Advantage: from any node you can reach the whole list."),
("What distinct advantage does a circular list offer over linear?",
 "Round-robin scheduling, playlist rotation, and continuous iteration without resetting; head deletion can be O(1) since tail->head is known."),
("How do you traverse a circular linked list safely?",
 "Start at head and iterate until the pointer returns to head (compare with the starting node reference) — never rely on None."),
("How do you split a circular list into two equal halves?",
 "Use slow/fast to find the middle, locate the node before it, break the link, and reconnect each half into its own circle. O(n)."),
("How do you insert at the end of a circular list when only head known?",
 "Walk to the tail (node.next==head), set tail.next=new, new.next=head. Without a tail pointer this is O(n); keep a tail pointer for O(1)."),
("How do you implement Josephus elimination with a circular list?",
 "Count steps and remove every kth node until one remains; update neighbours before deleting. O(n*k) naive, or index arithmetic for large k."),
("How do you detect whether a singly list is actually circular?",
 "Floyd's slow/fast pointers — if they meet, there's a cycle; or compare with the expected tail condition tail.next==head."),
("How do you reverse a circular linked list?",
 "Reverse pointers exactly like singly, then reconnect: new head becomes old tail (its next now points back to the new tail), preserving circularity."),
("Where does the circular list beat queus in implementation?",
 "Implementing a ring buffer: with a fixed array plus modulo index the circular structure gets used directly for audio streams and caches."),
],
"03-Linked-Lists/04-Fast-and-Slow-Pointer": [
("Explain the fast-and-slow (tortoise-hare) pointer pattern.",
 "Two pointers traverse at different speeds — typically 1x and 2x — so a cycle makes them collide while a linear list lets fast reach the end first."),
("Which classic problems use fast-slow pointers?",
 "Middle of the list, cycle detection, cycle-start finding, cycle length, palindrome; also in arrays for duplicates (Floyd on the value graph)."),
("Why does Floyd's cycle detection always terminate on a cycle?",
 "Each step reduces the gap between pointers by 1; inside a cycle the gap eventually reaches 0, guaranteeing collision without extra memory."),
("How do you find the middle using fast-slow and why does it stop correctly?",
 "fast moves 2, slow moves 1. When fast hits the end (or fast.next), slow is at the midpoint — the geometry always lands within bounds."),
("How do you find cycle-start after collision?",
 "Reset one pointer to head, move both one step — the meeting point is the cycle start. Mathematically distance head->start == meeting-wrap distance."),
("How do you prove the collision pointer meeting logic with modular arithmetic?",
 "Position after k steps mod L; equality of congruence holds, so chosen speeds always meet inside the cycle; math holds for all L>0."),
("How do you detect the duplicate in an array using Floyd (cycle on values)?",
 "Treat nums[i] as the next index; the value-duplicated index becomes a cycle-entry node-value; apply slow/fast then reset like list cycle start. O(n) time, O(1) space."),
("How do you check palindrome on a linked list using fast-slow?",
 "Find mid via pointers, reverse the tail, then two-pointer compare from both ends — using the same pattern end-to-end."),
("When would a 2x speed fail or need a variant?",
 "On self-loops and for special cases x!=2 works too mathematically, but 2x is chosen for simplicity; for finding length of a cycle with x,y horseshoe you adjust both speeds equally."),
],
"03-Linked-Lists/05-Merge-and-Split": [
("State the recursion for merging two sorted linked lists.",
 "Base: if one is None return the other. If l1.val<=l2.val, l1.next=merge(l1.next,l2), return l1; else symmetric. Tail-recursive but iterative version used often."),
("How do you merge k sorted lists optimally?",
 "Min-heap of k heads (O(log k) per pop/push) yields O(total log k). Better for interviews than merge-pairing (O(total log k) too but clunkier)."),
("How do you split an odd/even list (alternating nodes)?",
 "Walk and attach each node to the appropriate odd/even list; truncate both tails. O(n)."),
("How do you split a singly list into halves cleanly?",
 "slow/fast find middle, save second = slow.next, then slow.next=None to break. Handles even/odd lengths."),
("How do you merge two lists alternately (zebra pattern)?",
 "Interleave a1.next=a2head... with pointer advance through both; when one exhausts, attach the remainder. Used in 'merge in between' style."),
("How do you merge sorted lists in place without allocating nodes?",
 "Reuse existing nodes by relinking. Works because merge only reorders references; O(1) extra space beyond recursion."),
("What is the 'merge two sorted lists' complexity?",
 "O(n+m) time and O(max(recursion depth)) for recursive, O(1) extra space iterative. Both linear in input size."),
("How do you partition a list into three groups (less/equal/greater)?",
 "Three dummy-headed lists, per-node compare, then concat less+equal+greater avoiding null tails. Stable. O(n)."),
("How do you split a circular linked list into two without loss?",
 "slow/fast to middle; cut at the point before slow; reconnect each cycle — both halves remain circular and whole."),
("How do you merge two sorted lists of different lengths?",
 "Two-pointer drains both; when one empties, attach the remaining tail of the other directly — no extra copying."),
],
"03-Linked-Lists/06-Advanced-LL-Problems": [
("What makes an advanced linked-list problem?",
 "Multi-pointer relocation, cycle math, reversing sub-ranges, or combining LL with recursion/hashing/problems like reorder list, k-group reverse, rotate."),
("How do you reverse a linked list between two given positions (left-right)?",
 "Dummy + prev; skip to left, then reverse the sub-range tail-by-tail inserting each after prev; fix the start's next to the remaining tail. O(n)."),
("How do you reverse nodes in alternating k-groups?",
 "Track group order; reverse odd groups, skip even groups; reuse k-group reverse on the effective remainder. O(n)."),
("How do you find the starting node of the intersection of two linked lists?",
 "Length-align or two-pointer swap-tails approach; intersection node equals where the two pointers converge after swapping. O(n+m)."),
("How do you add two huge numbers as lists without consuming (no big ints)?",
 "Reverse both lists, add with carry; reverse the result. O(n) time and O(n) output space."),
("How do you flatten a multi-level doubly linked list?",
 "DFS over child pointers: splice each child sub-list between current and next; maintain child's tail to last. O(n) overall.This mirrors real problems asked in product interviews."),
("How do you copy a linked list with each node having random pointers?",
 "Three passes: interleave clones, set random pointers via next-of-original's random, then unweave. O(n) time, O(n) space (or hash map)."),
("What is the 'odd-even linked list' problem?",
 "Segregate nodes by index parity into odd and even lists, then connect odd-tail to even-head. O(n), single pass."),
("How do you sort a linked list in O(n log n)?",
 "Merge sort with slow/fast split and merge — the only guaranteed O(n log n) LL sort. Quicksort suffers pivot/pointer overhead."),
("How do you remove duplicates from an unsorted linked list without a set?",
 "Nested loops comparing each node against its suffix (O(n^2)); required when space is bound. A hash set reduces to O(n) time."),
("How do you detect if a linked list is a palindrome with O(1) space?",
 "Mid + reverse-second-half + compare; optionally restore. This is the accepted in-place dictation answer."),
("How do you find the fractional (n/k-th) node from the end?",
 "Advance one pointer k steps or use slow/fast ratio; for 1/k from the tail, use a block-based two-pointer."),
("How do you join two sorted lists and merge duplicates?",
 "Merge then dedupe adjacent equal values in a final pass; or dedupe during merge by skipping equal nexts. O(n+m)."),
],
"04-Stacks-and-Queues/01-Stack-Fundamentals": [
("Define a stack.",
 "A LIFO (last-in-first-out) data structure with push (add top), pop (remove top), and peek (view top); all operations are O(1) with an array-backed implementation."),
("State the LIFO property with a real example.",
 "Undo in editors, function call stack, recursion, and matching parentheses — the most recent item is consumed first."),
("How is a stack implemented with an array?",
 "Maintain top index; push increments top after writing; pop reads then decrements. Overflow when top == capacity; resizing used in dynamic arrays."),
("When should you use a stack over a queue?",
 "Stack for nesting/matching/backtracking; queue for FIFO ordering (BFS, request queues). Choice is dictated by the ordering requirement."),
("What is the monotonic stack and when do you use it?",
 "Keeps elements in strictly increasing/decreasing order; the classic tool for next-greater/smaller element, rain-water trapping, and largest-rectangle problems."),
("How do you implement two stacks in one array?",
 "Grow from both ends: stack A at index 0, stack B at index n-1; they collide when top_A + 1 == top_B."),
("How do you evaluate an infix to postfix conversion using a stack?",
 "Operands output directly; operators pushed after popping higher/equal precedence; '(' pushed, ')' pops until '('. Classic compiler-style question."),
("Explain stack overflow/underflow handling.",
 "Underflow: pop/peek on empty raises error or sentinel. Overflow: dynamic stack resizes instead of crashing; in C fixed stacks return error."),
("How do you check balanced parentheses with a stack?",
 "Push openers; on closer, pop and verify the matching type; at the end stack must be empty. O(n)."),
("Implement min-stack (get minimum in O(1)).",
 "Keep a second stack storing running minima, or store (value, current_min) tuples; top of min-stack is O(1) min."),
("How do you implement a queue using two stacks?",
 "Push side (enqueue) and pop side (dequeue); when popping and pop-side empty, transfer all elements, reversing order — amortised O(1) per op."),
],
"04-Stacks-and-Queues/02-Queue-Fundamentals": [
("Define a queue.",
 "A FIFO (first-in-first-out) structure with enqueue (rear) and dequeue (front); used wherever order of arrival must be preserved."),
("How do you implement a queue with a circular array?",
 "front/back indices with modulo; enqueue at rear, dequeue at front; full when (rear+1)%cap == front. Avoids shifting costs of a naive array queue."),
("How do you implement a queue using two stacks?",
 "Enqueue pushes into stack A; dequeue pops from stack B, filling B from A when empty. Amortised O(1) behaviour."),
("What is a deque and why is it the preferred Python queue?",
 "Double-ended queue — O(1) append/pop at both ends; collection.deque is implemented as a doubly-linked block structure, ideal for sliding windows and BFS."),
("Compare BFS's queue usage with DFS's stack usage.",
 "BFS explores level by level (FIFO queue); DFS explores depth-first (LIFO stack or recursion); both are O(V+E) but ordering differs."),
("How does a priority queue differ from a normal queue?",
 "Serves the highest (or lowest) priority element first, not FIFO; implemented with binary heaps giving O(log n) insert/delete-min."),
("What is a blocking queue and where is it used?",
 "Blocks enqueue when full and dequeue when empty; used in producer-consumer patterns and thread pools (Python queue.Queue)."),
("How do you check if two queue lookalikes (stack vs queue) by operations?",
 "Distinguish by observing removal order: if results preserve insertion order it's a queue, if reversed it's a stack."),
("How many nodes does BFS visit at max, and what's the space complexity?",
 "Space is O(W) for the frontier, worst O(V) — since all vertices could be enqueued; time O(V+E) with adjacency lists."),
("What are the common queue applications in OS/network stacks?",
 "Process scheduling (FIFO/round-robin queues), packet buffer queues, print spooling, message queues — all preserve order and smooth bursts."),
],
"04-Stacks-and-Queues/03-Monotonic-Stack": [
("What is a monotonic stack and what invariant does it keep?",
 "A stack whose elements are in strictly monotonic order (increasing or decreasing) from bottom to top. The invariant is maintained by popping elements that violate the order before each push."),
("How do you find the next greater element with a monotonic stack?",
 "Scan left to right with a decreasing stack (values decreasing). On value x, while stack top < x, pop and record x as that index's NGE; push x. O(n)."),
("How do you compute the nearest smaller to the left/right?",
 "Nearest smaller left: increasing stack while sliding left->right; nearest smaller right: same scan right->left, or reverse. O(n) each; used in histogram (area = height * width between smaller bounds)."),
("How do you solve the largest rectangle in a histogram?",
 "For each bar, width = distance to nearest smaller on left and right; area = height*width; hence the monotonic stack computes the whole answer in one pass, O(n)."),
("How does the monotonic stack handle rain water trapping (two-pointer alternative)?",
 "Stack-based: within decreasing heights, each pop computes a trapped unit layer bounded by min(left bar,right bar); the two-pointer version is O(1) space but same idea."),
("What problems follow the pattern 'nearest greater/smaller bound'?",
 "Sum of subarray minimums/maximums, largest rectangle, maximal rectangle in matrix, next-greater-element, daily temperatures, stock span, skyline silhouette."),
("Define the daily temperatures problem and its stack algorithm.",
 "Return the days until a warmer temperature; process right-to-left, pop while stack holds colder temps; next-index - i = answer, push i. O(n)."),
("What is the stock span problem?",
 "Consecutive days the price is ≤ today's: monotonic decreasing stack holds indices with strictly greater prices; span = i - index of nearest greater (or i+1). O(n)."),
("How do you find the sum of subarray minimums with a monotonic stack?",
 "For each element compute nearest smaller to left (L) and right (R); contribution = arr[i] * (i-L) * (R-i). Summation O(n)."),
("When should you NOT use a monotonic stack?",
 "When order isn't significant and hashing/sorting suffices — monotonic stacks are only needed when the answer depends on the nearest boundary with a monotonic property."),
],
"04-Stacks-and-Queues/04-Advanced-Stack-Problems": [
("How do you evaluate a postfix expression using a stack?",
 "Push numbers; on operator pop two operands, compute, push result. At the end the single remaining value is the answer. O(n)."),
("How do you convert infix to postfix with a stack?",
 "Operands out; operators pushed after popping ≥ precedence; '(' pushed, ')' pops to '('. Handle unary minus and right-associativity explicitly."),
("How do you implement a basic calculator with parentheses and +, -?",
 "Operand stack + sign stack; '(' pushes current result/sign; ')' pops and combines; accumulate on '+'/'-'. Do NOT convert to eval — interviewers test parsing logic."),
("How do you implement an undo/redo with two stacks?",
 "Undo-stack stores previous states; redo-stack receives popped states on undo; a new action clears redo. Both are O(1) push/pop."),
("How do you validate stack sequences (pushed/popped order)?",
 "Simulate: push from pushed; while stack top == popped[j], pop and j++. Valid iff stack empties. O(n)."),
("How do you find the Largest Rectangle in a Matrix of 1s?",
 "Treat each row as histogram heights; run monotonic-stack largest-rectangle for each row — O(m*n) total."),
("How do you design a stack that supports getMin, push, pop in O(1)?",
 "Pair stack or min-stack as described; for eager min, keep both value and running-minitude in parallel."),
("How do you implement a two-layer 'backspace' behaviour using stacks?",
 "Push chars, pop on '#', at end join the stack. Handles consecutive backspaces without index gymnastics."),
("What is the 'trapping rain water' stack solution?",
 "While current height > stack top, pop mid; trapped = (min(left bound,right bound) - mid) * distance. O(n) time/space; two-pointer version uses O(1) space."),
("How do you simulate browser back/forward with two stacks?",
 "Back stack of visited pages, forward stack cleared on new visit; back pops into forward, forward pushes back. Classic stack interview scenario."),
],
"04-Stacks-and-Queues/05-Priority-Queue-and-Heap": [
("Define a binary heap and its properties.",
 "A complete binary tree stored in an array where parent ≤ children (min-heap) or ≥ (max-heap); heap[0] is the extreme. Height O(log n), operations on root path."),
("State the complexity of heap operations.",
 "Insert O(log n), extract-min/max O(log n), peek O(1), build-heap O(n) (down-heap from first non-leaf)."),
("How do you implement heapify (sift-down)?",
 "Compare node with children, swap with the extreme child violating order, recurse down until heap property restored. Called on indices n/2-1..0 to build in O(n)."),
("What is the difference between a heap and a priority queue?",
 "A priority queue is an interface (insert element with priority, delete the extreme); a heap is the usual array-backed implementation. Same concepts, different abstraction layers."),
("How do you find the K largest elements with a heap?",
 "Min-heap of size k: push, and when size>k pop the smallest; the heap holds the k largest. O(n log k) time, O(k) space."),
("How do you merge k sorted arrays with a heap?",
 "Push (value, listIdx, elemIdx) into a min-heap; repeatedly pop min, place in result, push next element from that list. O(N log k)."),
("How do you implement a median-of-stream using two heaps?",
 "Max-heap for the lower half, min-heap for the upper; rebalance so sizes differ by ≤ 1; median is top of bigger (or average). O(log n) per number."),
("How do you find the top-k frequent elements?",
 "Counter frequencies, then a min-heap of k (keyed by frequency) or bucket sort by frequency count. O(n log k) or O(n)."),
("What is heap sort and its complexity?",
 "Build max-heap then repeatedly swap root to end and heapify the shrinking prefix — O(n log n) worst, O(1) extra space, NOT stable."),
("How do you implement a priority queue in Python?",
 "heapq provides min-heap on lists; push/pop pairs of (priority, item) for custom priorities; a counter disambiguates ties. queue.PriorityQueue adds thread-safe locking."),
("How do you implement a max-heap in Python?",
 "Negate keys (heapq.min-heap with -value), or wrap entries in a class with __lt__ inverted. No dedicated max-heap exists in heapq."),
("What is a 'd-ary heap' and its trade-off?",
 "Each node has d children: faster key-decrease (O(log_d n)) but slower each child scan; used in Dijkstra optimisations for dense graphs."),
("How do you find the K smallest pair sums?",
 "Min-heap seeded with (a[0]+b[i]) for each i; pop, push next by advancing a-pointer; dedupe with visited set. O(k log k)."),
("What is a Fibonacci heap and why is it advanced?",
 "Supports decrease-key O(1) amortised, used in optimised Dijkstra/Prim; complex pointer-based structure rarely required in interviews but shows depth."),
("How does a heap enable Huffman coding?",
 "Merge the two smallest-frequency symbols repeatedly using a min-heap; the tree's leaves encode variable-length optimal prefix codes. O(n log n)."),
],
}