"""Curated Q&A for 02-CS-Fundamentals leaves."""
OOP = {
"01-OOP/01-Classes-and-Objects": [
("What is a class and what is an object?",
 "A class is a blueprint/template that defines attributes (data) and methods (behaviour). An object is a concrete instance of that blueprint, with its own memory and state."),
("Explain state, behaviour, and identity of objects.",
 "State = the values of an object's attributes; behaviour = the methods it can execute; identity = the unique reference that distinguishes it even if two objects have equal state. == vs is captures this."),
("What is a constructor? When is it called?",
 "A special method (__init__ in Python) invoked automatically when an object is created, to initialise the object's attributes. Default constructors exist when none is defined."),
("Difference between __init__ and __new__ in Python?",
 "__new__ creates and returns the instance (rarely overridden); __init__ initialises the returned instance. __new__ runs first; __init__ runs after if __new__ returns an instance of the class."),
("What is a default constructor vs parameterised constructor?",
 "Default has no parameters (or all have defaults); a parameterised constructor accepts arguments to initialise specific attribute values — Python just uses default arguments for both."),
("What is the self parameter in Python methods?",
 "self is the reference to the current instance passed automatically as the first argument to instance methods. Naming it self is a convention, not a keyword."),
("What is a class variable vs an instance variable?",
 "A class variable is shared across all instances (defined in the class body); an instance variable is per-object (set via self). Changes to class vars can affect all instances."),
("What is an instance method, class method, and static method?",
 "Instance method receives self and can use instance state; class method receives cls and works at class level (@classmethod); static method receives neither (@staticmethod) — utility function attached to the class."),
("How do you define properties (getters/setters) in Python?",
 "Use @property decorator for getter and @x.setter for setter; allows validation and computed values while keeping attribute-style access (obj.x)."),
("Explain the `is` vs `==` for objects.",
 "== compares value equality (calls __eq__); is compares identity (same memory address). Two equal but distinct objects are not `is`."),
("What is encapsulation at the object level?",
 "Binding data and the methods that operate on it inside the object, hiding internal details; Python signals privacy with _single and __double underscores (name mangling)."),
("How does Python memory work for objects (ref counting)?",
 "Every object has a reference count; when it reaches zero the object is freed (CPython). Cyclic references are reclaimed by the cyclic garbage collector."),
("What is a shallow vs deep copy of an object?",
 "Shallow copy duplicates the top object but references the same nested objects; deep copy recursively duplicates everything (copy.deepcopy). Mutating nested data behaves differently."),
("Give a real example of objects from your projects.",
 "In FastAPI services I modeled API request/response objects and repository classes; in the LLM pipeline, prompt, document, and agent objects encapsulated state and behaviour."),
("What is the lifecycle of an object?",
 "Creation (constructor) → state changes through methods → dereferenced/out of scope → garbage collected. Interviewers like the full journey described accurately."),
],
"01-OOP/02-Inheritance": [
("What is inheritance and why use it?",
 "Creating a new class that reuses and extends an existing class's attributes/methods, promoting code reuse and establishing an is-a relationship."),
("Explain single vs multiple inheritance.",
 "Single: one base class. Multiple: a class inherits from several bases, merging attribute/method resolution (MRO). Python supports both; Java/C# support only single (plus interfaces)."),
("What is method overriding?",
 "A subclass redefines a base-class method with the same signature, changing behaviour; the call dispatches to the subclass version at runtime (polymorphism in action)."),
("What is method overloading and does Python have it?",
 "Multiple methods with the same name but different signatures. Python doesn't support compile-time overloading; use default arguments or *args/**kwargs to emulate it."),
("What is super() in Python?",
 "super() returns a proxy that delegates calls up the MRO, letting a subclass call the parent's version of a method — essential for cooperative multiple inheritance."),
("What is the MRO (Method Resolution Order)?",
 "The order in which Python searches base classes for an attribute/method, computed by C3 linearisation. Check via ClassName.__mro__."),
("What is the diamond problem?",
 "In multiple inheritance, when two bases share a common ancestor, the ancestor's method could be called twice; Python's C3 MRO resolves it so the shared ancestor runs once, in priotised order."),
("What is an abstract class?",
 "A class that may have abstract methods (declared but not implemented) and cannot be instantiated directly; subclasses must implement abstract methods (abc module)."),
("What is the difference between extends (is-a) and contains (has-a)?",
 "Inheritance models is-a; composition models has-a (an instance held as an attribute). Composition is preferred for flexibility (favour composition over inheritance)."),
("When should you NOT use inheritance?",
 "When the relationship is has-a rather than is-a, when only one method needs reuse, or when deep hierarchies make the code rigid — prefer composition or interface-based design."),
("What is a mixin?",
 "A class providing reusable behaviour meant to be combined via multiple inheritance, not instantiated alone (e.g., to provide extra methods to various unrelated classes)."),
("What is `object` in Python?",
 "The root of the class hierarchy — every class implicitly inherits from object, providing __str__, __repr__, __eq__, __hash__ defaults."),
("What is method resolution in a subclass that doesn't override?",
 "The attribute lookup walks the MRO and uses the first match; so unoverridden methods are inherited from the nearest ancestor that defines them."),
("How do you verify type relationships (issubclass, isinstance)?",
 "issubclass(Derived, Base) and isinstance(obj, Base) check inheritance relationships — isinstance returns True for any class in the MRO."),
],
"01-OOP/03-Polymorphism": [
("What is polymorphism?",
 "The ability of objects of different types to respond to the same method call in their own way. It allows writing code that works on a common interface without caring which concrete type is running."),
("Give a classic real-world example.",
 "A media play() method: AudioFile.play() plays sound, VideoFile.play() shows video — same call, different implementations — the classic polymorphism analogy interviewers love."),
("What is duck typing?",
 "If it walks and quacks like a duck, treat it as a duck: Python calls methods without checking types, relying on the object having the required method/attribute."),
("What is runtime vs compile-time polymorphism?",
 "Runtime: method overriding — resolved when the call executes. Compile-time: overloading (Python emulates with defaults) resolved by the compiler/interpreter at call site."),
("How do you implement polymorphism in Python?",
 "Through method overriding in subclasses, protocols, abstract base classes, and duck typing — the isinstance/type checks are avoided in favour of behaviour-based dispatch."),
("What is operator overloading?",
 "Giving operators (+,-,==,<) new meaning for custom types via dunder methods like __add__, __eq__, __lt__ — a form of polymorphism at the operator level."),
("What is the difference between polymorphism and inheritance?",
 "Inheritance is a mechanism for sharing code; polymorphism is a design pattern where a unified interface dispatches to type-specific implementations — inheritance is one way to achieve it."),
("Explain polymorphic method dispatch with a Python example.",
 "Calling shape.area() where shape appears the same type at the call site; at runtime, Python invokes Circle.area or Square.area depending on the actual object — late binding."),
("What is the 'strategy pattern' and how is it poly?",
 "Swap the algorithm at runtime by supplying any object implementing the same interface — behavioural polymorphism enabling algorithms to be replaced without touching callers."),
("How do protocols formalise duck typing?",
 "typing.Protocol allows static typing while preserving runtime duck typing — an object's conformance to an interface is structural, not nominal."),
],
"01-OOP/04-Encapsulation-and-Abstraction": [
("What is encapsulation?",
 "Binding data and the functions that manipulate it inside one unit (class) while restricting outside access to internals, exposing safe interfaces instead — e.g., a capsule hiding medicine."),
("How does Python implement encapsulation?",
 "Naming conventions: _private (convention) and __private (name mangled as _ClassName__private). True enforcement is by convention; Python trusts the developer."),
("What is abstraction?",
 "Hiding implementation complexity and exposing only essential features — e.g., a car accelerator abstracts the engine: you press the pedal, not the fuel injectors."),
("What is the difference between encapsulation and abstraction?",
 "Encapsulation bundles and controls access to internals (a mechanism); abstraction hides complexity at the design level (a concept). Encapsulation is used to implement abstraction."),
("Why hide data (benefits of encapsulation)?",
 "Protects invariants, prevents accidental corruption, allows changing the implementation without breaking callers, and centralises validation in setters."),
("What are getters/setters and when do you use them?",
 "Methods that expose or mutate attributes with checks. In Python, @property plus @x.setter gives controlled attribute access while keeping clean syntax."),
("What is information hiding?",
 "The design principle that details not needed by callers stay hidden, minimising coupling — critical in module/API design and a close cousin of abstraction."),
("Give an example where you used abstraction in your projects.",
 "In the RAG pipeline I wrapped embedding/vector-store/LLM behind a RetrievalService interface so downstream code didn't need to know which provider was in use — classic abstraction."),
("What are the risks of over-encapsulation?",
 "Too many layers and getters/setters bloat code and hurt performance/readability; balance by exposing only what changes."),
("What is the principle of least privilege in OOP terms?",
 "Expose the minimum interface needed — correlates with private members and well-scoped public APIs, reducing the attack surface and coupling."),
],
"01-OOP/05-SOLID-Principles": [
("What are the SOLID principles?",
 "Single Responsibility, Open-Closed, Liskov Substitution, Interface Segregation, Dependency Inversion — five principles for maintainable OO design."),
("Explain Single Responsibility Principle.",
 "A class should have one reason to change — one responsibility. Splitting concerns keeps classes focused and testable (e.g., separate data access, business logic, presentation)."),
("Explain Open-Closed Principle.",
 "Software should be open for extension but closed for modification — add new behaviour via inheritance/strategies rather than editing existing class code."),
("Explain Liskov Substitution Principle.",
 "Subtypes must be substitutable for their base types without breaking behaviour — a derived class must not weaken the base's contract (override that throws exceptions is a classic violation)."),
("Explain Interface Segregation Principle.",
 "Clients should not be forced to depend on methods they don't use — prefer several specific interfaces over one fat interface."),
("Explain Dependency Inversion Principle.",
 "High-level modules should not depend on low-level modules; both should depend on abstractions. Inject dependencies rather than hard-coding implementations (e.g., pass an LLM client, don't import one)."),
("How do the SOLID principles apply to a FastAPI service?",
 "Separate routers/controllers, service (business) layer, repository (data) layer; abstract external clients behind interfaces so they can be swapped or mocked."),
("Give an example of LSP used properly.",
 "If Rectangle has area(); Square extended from it would break expectations — the famous design smell. Use a Shape abstraction instead — each provides area() consistently."),
("What is 'favour composition over inheritance'?",
 "Build behaviour by composing objects (has-a) instead of deep inheritance — more flexible at runtime and avoids fragile base-class coupling."),
("How would you refactor a god class with SRP/OCP?",
 "Extract each responsibility into its own class (SRP), expose them through an interface (ISP), and enable extension via strategy/injection (OCP/DIP)."),
],
"01-OOP/06-Design-Patterns": [
("What are design patterns?",
 "Reusable, well-tested solutions to recurring design problems, categorised as creational, structural, or behavioural — not code, but templates of structure and interaction."),
("Name common creational patterns.",
 "Singleton, Factory Method, Abstract Factory, Builder, Prototype — each controls how objects are created in some way."),
("What is the Singleton pattern and when is it used?",
 "Ensures a class has exactly one instance with a global access point (e.g., DB connection pool, config loader). Implement in Python via __new__ control or module-level instance."),
("What is the Factory pattern?",
 "A method/class creating objects without exposing instantiation logic; callers get an instance of an interface, the subclass decides the concrete type."),
("What is the Builder pattern?",
 "Constructs complex objects step by step, separating construction from representation — used for configs with many optional parameters (e.g., building an HTTP client)."),
("What is the Observer pattern?",
 "One-to-many dependency where objects subscribe to another and are notified on state change (pub-sub, event listeners). Used in UI and event-driven systems."),
("What is the Strategy pattern?",
 "Encapsulates an interchangeable family of algorithms behind an interface, letting the caller swap them at runtime (e.g., choosing sorting or embedding strategy)."),
("What is the Adapter pattern?",
 "Converts the interface of a class into another interface clients expect — bridging incompatible APIs (e.g., adapting a third-party SDK to your service interface)."),
("What is the Decorator pattern?",
 "Adds responsibilities to objects dynamically by wrapping them — the Python decorator syntax is a structural realisation used for logging, caching, retries."),
("What is the Repository pattern and why is it popular?",
 "Mediates between the domain and data-mapping layers, hiding data-source specifics behind an interface — the go-to persistence pattern in FastAPI/Flask projects."),
("How do patterns relate to SOLID?",
 "Patterns encode SOLID-friendly structures — Factories support OCP, inverceon of Strategy supports DIP, Adapters support ISP — the principles guide when to apply them."),
],
"01-OOP/07-OOP-in-Python": [
("What makes Python's OO model special?",
 "Everything is an object; classes are objects too; dynamic attribute addition, multiple inheritance with C3 MRO, duck typing, and dunder-method protocol — the runtime is deeply object-oriented."),
("Explain dunder methods and why they matter.",
 "Special methods like __init__, __len__, __getitem__, __eq__ are hooks Python calls for syntax/operators; implementing them makes your objects behave like built-ins."),
("How do you make an object iterable?",
 "Implement __iter__ returning an iterator (or yield in a generator) and optionally __next__ for a self-iterator; then for x in obj works."),
("How do you make objects comparable/sortable?",
 "Implement __lt__ (and __eq__), or total_ordering to fill the rest; then sorted() and min/max use them consistently."),
("What is `__repr__` vs `__str__`?",
 "__repr__ is the unambiguous developer-facing representation (ideally eval-able); __str__ is the readable user-facing string. print() and str() use __str__; repr() uses __repr__."),
("How is dynamic attribute assignment handled?",
 "Python objects store attributes in instance __dict__ (and class __dict__); __setattr__/__getattr__ hooks let you intercept reads/writes — powerful metaprogramming."),
("What is `__slots__`?",
 "Declares allowed instance attributes, preventing per-object __dict__, saving memory and speeding attribute access — useful for many small objects."),
("What are class decorators and dataclasses?",
 "Dataclasses auto-generate __init__, __repr__, __eq__ from annotations reducing boilerplate; class decorators transform the class object at definition time."),
("How do you implement a private attribute truly (name mangling)?",
 "__attr at class level becomes _ClassName__attr — a convention-based restriction, not real privacy; external code can still access it if it knows the mangled name."),
("How do you write a custom collection?",
 "Inherit from collections.abc.MutableSequence/Sequence and implement the required abstract methods; the mixin provides the rest."),
],
"01-OOP/08-OOP-in-Java": [
("What are the four pillars of OOP and how does Java enforce each?",
 "Encapsulation (private + getters), Inheritance (extends/implements), Polymorphism (overriding/interfaces), Abstraction (abstract classes/interfaces) — Java enforces via keywords and type system."),
("What is the difference between an interface and an abstract class in Java?",
 "Abstract class: may hold state, constructors, some implemented methods, single inheritance. Interface: contract of abstract methods (default/static allowed), multiple can be implemented. Java 8+ allows default methods in interfaces."),
("What is a HashMap vs a TreeMap in Java?",
 "HashMap: O(1) average get/put, unordered, allows one null key. TreeMap: O(log n) navigation, sorted by key via Comparable/Comparator — the exact Infosys Hashmap vs Treemap question."),
("What is a ConcurrentHashMap?",
 "Thread-safe hash map with finer-grained locking (CAS + segments) — safe for concurrent reads/writes without external synchronisation; never allows null keys/values."),
("Explain ArrayList vs LinkedList vs Vector.",
 "ArrayList: dynamic array, O(1) index access, O(n) middle insertion. LinkedList: doubly-linked, O(1) ends. Vector: array like ArrayList but synchronized (legacy, slow)."),
("What are access modifiers in Java?",
 "private (same class), default/package-private, protected (package + subclasses), public (anywhere) — the toolkit for Java encapsulation enforcement."),
("What is the `final` keyword?",
 "final class (no subclass), final method (no override), final variable (cannot be reassigned) — Java's immutability/constancy marker."),
("What is runtime polymorphism in Java?",
 "When the actual object type (not the static reference type) selects the method at runtime; classic: Animal a = new Dog(); a.makeSound() runs Dog's version — late binding."),
("What are Java generics and their use?",
 "Type parameters at compile time (List<String>) providing type safety without runtime cost; erased at runtime (type erasure) to Object."),
("What is a Java exception hierarchy?",
 "Throwable → Exception (checked/unchecked) and Error. Checked exceptions must be handled or declared; unchecked (RuntimeException) thread logic bugs — understanding helps designing robust services."),
],
"01-OOP/09-Real-World-OOP-Problems": [
("Model a Bank Account in OOP.",
 "Class Account with balance encapsulated, deposit/withdraw validating state (encapsulation), subclasses Savings/Current overriding interest logic (inheritance + polymorphism), methods as the only state change path."),
("Design a Vehicle hierarchy.",
 "Vehicle base with start()/stop(), Car/Bike/Truck subclasses override behaviour; an interface Drivable could decouple callers — showing is-a via inheritance and polymorphic use."),
("Design a notification system (email/SMS/push).",
 "NotificationSender interface; EmailSender/SmsSender/PushSender implement send(); a NotificationService depends on the interface (DIP) — the classic OOP system design."),
("Model an e-commerce cart with discounts.",
 "Cart (composition of items), Strategy discount strategies (percentage/flat/coupon), price computed polymorphically — cleanly demonstrates composition + strategy."),
("Design a library management system.",
 "Loan, Member, Book classes; Repository for persistence, Service for business rules, Controller/CLI for interaction — layering maps to real FastAPI service structure."),
("What are the common OOP code smells in these problems?",
 "God classes (bloated responsibilities), deep inheritance, leaked invariants (exposed state), and duplicated logic — fixing these with SOLID restores clean design."),
("Design an AI-agent pipeline with OOP.",
 "Agent base with run(); Tool interface; RAGRetriever, LLMHandler as components injected into the agent — matches your Agno/LangChain-styled code."),
("Model a chess game.",
 "Piece abstract with canMove()/value(); each piece class overrides; Board manages squares; Move validation dispatches polymorphically — a favourite OOP design exercise."),
("Design a hotel booking system with overlapping bookings.",
 "Room entity, Booking with check-in/out, overlap detection via interval logic, validation in setters — encapsulation + service-layer validation."),
("Design a payment processing system supporting multiple gateways.",
 "PaymentGateway interface, RazorpayGateway/StripeGateway adapters, PaymentService using the interface — Adapter + Strategy + DIP combined."),
],
"01-OOP/10-Advanced-OOP-Concepts": [
("What are lazy object creation and dependency injection?",
 "Lazy creation defers object construction until first use; DI passes dependencies in rather than creating inside — makes services testable and swappable, aligning with DIP."),
("What are protocols and structural typing in Python?",
 "typing.Protocol defines a structural interface; any object with matching methods satisfies it without inheritance — strong duck typing with type hints."),
("What is metaprogramming in Python?",
 "Writing code that manipulates classes/functions at runtime — metaclasses, class decorators, __getattr__/__setattr__, and dynamic code generation."),
("How do you build a metaclass?",
 "A class whose instances are classes; custom __new__/__init__ control class creation (e.g., auto-registering subclasses or validating attributes)."),
("What is cooperative multiple inheritance?",
 "All classes in an MRO chain call super().method(), passing control along the MRO — super().__init__ chains must be designed cooperatively to avoid skips."),
("What is the descriptor protocol?",
 "Implementing __get__/__set__/__delete__ on an attribute object gives custom attribute behaviour — the engine behind @property and ORM column fields."),
("What is introspection vs reflection?",
 "Introspection reads an object's types/attributes at runtime (type(), dir(), vars()); reflection (dynamic) additionally modifies behaviour (setattr, dynamic dispatch)."),
("How do you achieve immutability in Python objects?",
 "Frozen dataclasses (frozen=True), overriding __setattr__ to raise, exposing via properties without setters — Java-like final but via runtime conventions."),
("What is composition root?",
 "The single startup point where the object graph is wired (dependencies injected) — with module-level wiring in FastAPI lifespan, enabling clean testing."),
("How do ORMs map classes to tables (the magic)?",
 "SQLAlchemy models use declarative mappings with descriptors/metadata so columns become attributes — metaclass/descriptor magic applied at class definition."),
],
}