"""Curated Q&A for 08-Coding-Patterns (keys are leaf names; runner adds top-level prefix)."""
PATTERNS = {
"01-Frequency-Counter": [
("What is the frequency-counter pattern?",
 "Using a hash map to count occurrences of elements in O(n) time and O(n) space, replacing nested-loop comparisons — the first optimisation to reach for when a naive solution is O(n^2)."),
("When do you recognise that a frequency counter applies?",
 "Problems asking 'count occurrences', 'find duplicates', 'anagram validation', 'are two arrays permutations', or 'most frequent' — whenever tracking appearances beats re-comparing pairs."),
("How do you solve anagram-check with a counter?",
 "Count chars of both strings (or increment for one, decrement for the other) and require all counts == 0 — a linear-time replacement for the O(n^2) pairwise check."),
("How do you find the frequency of elements in a list?",
 "collections.Counter(list) builds counts in one pass; .most_common(k) returns top-k — the Python idiom for this exact pattern."),
("What is the difference between using a set and a dict in this pattern?",
 "A set proves existence; a dict also stores counts or the paired value — use the dict when you need the multiplicity or the value bound to each key."),
("What is the complexity of counting frequencies?",
 "O(n) time, O(n) space (in the worst case every element unique); trades memory for speed compared to O(n^2) pairwise comparisons."),
("How does the frequency counter handle the 'same frequency' variant?",
 "Compare Counter(a) and Counter(b) for equality, or compare their own frequency maps when asking whether groupings match — the extended form."),
("What is the memory trade-off when counts are from a huge range?",
 "A dict keyed by value grows with distinct elements; if values are bounded integers, a plain array indexed by value gives O(1) access and O(range) memory instead."),
("Give a pair-sum problem that uses a frequency counter.",
 "Find two numbers summing to target: store each value's index/frequency in a dict while scanning, and check `target - x` in the same pass — classic one-pass solution."),
("What is a counting sort's relationship to this pattern?",
 "Frequency counting over a bounded range IS counting sort's core — read the value, increment its bucket, then reconstruct in sorted order."),
("How do you use a frequency counter to detect duplicates in O(n)?",
 "Insert into a set/dict while scanning; the first element already present is the duplicate — vs nested-loop checking at O(n^2)."),
("What is the sliding-frequency variant for fixed-size windows?",
 "Keep a running Counter over a moving window, decrementing the element leaving and incrementing the entering element — O(n) across all windows."),
],
"02-Sliding-Window": [
("What is the sliding window pattern?",
 "Expanding/shrinking a contiguous subarray with two pointers, incrementally updating the aggregate — converting many O(n^2) subarray problems to O(n)."),
("When does sliding window apply?",
 "Problems over contiguous subarrays/substrings with a constraint on the window (max sum size-k, longest substring with at most k distinct, min window containing all) — fixed or variable size."),
("What is the difference between fixed and dynamic windows?",
 "Fixed: window size constant, slide one element at a time. Dynamic: size varies, right pointer expands and left shrinks while a condition holds."),
("Give the framework for a variable-size window.",
 "while r < n: add a[r]; while (condition violated): remove a[l], l++; update answer with (r-l+1); r++ — the canonical loop skeleton."),
("Why is the sliding window O(n) instead of O(n^2)?",
 "Each element enters once via the right pointer and leaves at most once via the left — total work is O(n) even though it looks like nested loops."),
("What is the classic maximum-sum-subarray-of-size-k problem?",
 "Compute the first window's sum, then slide subtracting a[l] and adding a[r+1], tracking the max — O(n) instead of recomputing each window."),
("How does the window maintain 'at most k distinct characters'?",
 "Right extends the window while distinct-count increases; when it exceeds k, shrink from the left until the constraint holds — each character tracked by a frequency counter."),
("What is the difference between this and the two-pointer pattern?",
 "Two pointers usually work on sorted arrays with a monotonic comparison; sliding window maintains a contiguous range under a constraint. Overlap: every sliding window is two pointers."),
("What edge cases do sliding-window implementations need?",
 "Empty input, window size > array length, all-equal characters, and the window never satisfying the constraint (return sentinel) — test all four."),
("How do you find the minimum window substring?",
 "Expand r until all required chars are inside; shrink l while still containing them, tracking the min length — the flagship 'sliding window with a need/count map' problem."),
("What is a monotonic deque's role in some window problems?",
 "For min/max over each window, a deque of candidates with windowed indices gives O(1) per element — sliding window with a deque (e.g., sliding window maximum)."),
],
"03-Two-Pointers": [
("What is the two-pointer pattern?",
 "Two indices scanning the array — often from both ends or at different speeds — with a monotonic decision, achieving O(n) on sorted inputs."),
("When is two pointers applicable?",
 "Sorted arrays (pair sums, removing duplicates), palindrome checks, reversing in place, and merging sorted sequences — anywhere a monotone decision lets you skip comparisons."),
("What is classic two-sum with sorted input?",
 "l=0, r=n-1; if sum < target move l right, if > move r left — O(n), versus the hash-map O(n) that also works unsorted; state both approaches."),
("What is the key invariant of the two-pointer scan?",
 "Once you move past a position, you never need to revisit it because the ordering makes the current choice irrelevant — the proof that skipping is safe."),
("When must input be sorted for this pattern?",
 "For pair/monotone problems such as two-sum and container-with-most-water, sortedness (or a known ordering) justifies moving one pointer — without it, the pattern may discard valid answers."),
("How does two pointers remove duplicates in-place?",
 "Slow pointer writes the next unique element; fast pointer scans; when fast value != previous, advance slow and write — O(n) time, O(1) space."),
("What is the three-pointer / Dutch national flag problem?",
 "Three-way partition (0s,1s,2s) with low/mid/high pointers — scanning once to sort in place; a direct extension when one comparison isn't enough."),
("What is the fast-and-slow relationship?",
 "Fast-and-slow is a two-pointer variant: pointers move at different speeds (cycle detection, middle-of-linked-list) rather than from the ends."),
("What is the complexity and when does it degrade?",
 "O(n) time, O(1) space when sorted; degrades only if you slip into nested scans or the input isn't actually monotone — justify sortedness explicitly."),
("Give a real-world analogy.",
 "Two scouts walking from opposite ends of a sorted line and meeting in the middle, discarding the region that provably cannot contain the target — each step eliminates a range."),
],
"04-Fast-and-Slow-Pointer": [
("What is the fast-and-slow pointer pattern?",
 "Two pointers traverse a linked list at different speeds — the fast one advances 2 nodes, slow 1 — enabling cycle detection, middle finding, and palindrome checks."),
("How do you detect a cycle in a linked list (Floyd's)?",
 "If slow and fast ever meet, a cycle exists; a cycle-free list lets fast hit None first — O(n) time, O(1) space."),
("How do you find the start of the cycle?",
 "After the meeting point, reset slow to head and move both one step — they converge at the cycle's start because the distances match (Floyd's second phase)."),
("How do you find the middle node with two pointers?",
 "Advance slow by 1 and fast by 2; when the fast pointer reaches the end, slow is the middle — finding the split point for linked-list problems."),
("What is the pattern's complexity guarantees?",
 "O(n) time, O(1) extra space — which is why it beats hash-set cycle detection (O(n) space) for memory-constrained interview solutions."),
("How does the pattern verify a linked list is a palindrome?",
 "Find the middle with slow/fast, reverse the second half, then compare halves node by node — O(n) time, O(1) space."),
("What is the hare and tortoise analogy?",
 "If two runners go around a track and one is twice as fast, they must eventually meet if the track is cyclic — the physical intuition for Floyd's algorithm."),
("What are the edge cases to test?",
 "Empty list, single node, cycle at the head, cycle at the tail, and 2-node lists (which cycle if tail->head) — the boundary set interviewers probe."),
("How does this pattern differ from two pointers on arrays?",
 "Arrays allow random access and end-based pointers; linked lists need speed-mismatch traversal to achieve the same detection/boundary results."),
("What is the proof that slow/fast meet in O(n)?",
 "Once both are in the cycle, the distance between them shrinks by 1 each step — guaranteed collision within a cycle of length k after at most O(k) steps, bounded by O(n) total work."),
],
"05-Merge-Intervals": [
("What is the merge-intervals pattern?",
 "Sort intervals by start, then greedily merge overlapping ones by extending end — converting many interval problems into one sorted linear pass."),
("What is the standard merge-intervals algorithm?",
 "Sort by start; iterate keeping current; if next.start <= current.end merge (end = max), else push current and start a new one — O(n log n) overall."),
("How do you define two intervals as overlapping?",
 "a and b overlap iff max(a.start,b.start) <= min(a.end,b.end); merging produces (min(a.start,b.start), max(a.end,b.end))."),
("How do you handle intervals that touch exactly?",
 "Overlap when end == next.start (depending on the definition): inclusive intervals merge ([1,2],[2,3]) -> [1,3]; state your assumption explicitly."),
("What is 'insert interval' and how is it different from merge?",
 "Insert keeps sorting justified (already sorted): find the position, merge the overlapped block, and append the rest — O(n) instead of a re-sort."),
("What is the interval-overlap-count problem (meeting rooms)?",
 "Maximum active overlaps = the peak overlap; solved by scanning start+1/end-1 difference events, or a min-heap of active meetings — O(n log n)."),
("What are the three classic interval variants?",
 "Merge all overlaps; find free gaps between merged intervals; compute maximum concurrent overlaps (min platforms) — master the merge then diff variants."),
("Why must intervals be sorted first?",
 "Greedy merging is only safe when you visit intervals by start — sorting turns an arbitrary set into a monotone scan where later intervals cannot start before earlier ones."),
("What edge cases are common?",
 "Empty input, single interval, intervals fully contained ([1,10],[2,3]), adjacent endpoints, and an interval that touches nothing — each must merge for the right direction."),
("How does interval logic map to calendar/scheduler systems?",
 "A calendar is a set of intervals; 'merge' finds free blocks, 'overlap count' builds the meeting-load curve, and 'insert' places a meeting — the same pattern, real product."),
],
"06-Top-K-Elements": [
("What is the top-k pattern?",
 "Finding the k largest/smallest/most-frequent elements efficiently — heap-based O(n log k) selection that beats full sorting when k is small."),
("What is the min-heap approach for top-k largest?",
 "Maintain a min-heap of size k; for each element, push it and pop the smallest when size exceeds k — the heap always holds the current top-k, O(n log k) total."),
("When would you sort instead of heap?",
 "When k is comparable to n (sorting is O(n log n) same order) or you need the full order; heap wins decisively when k << n (e.g., top-10 of 1M)."),
("How do you find top-k frequent using a Counter plus heap?",
 "Build counts via Counter (O(n)), then push (count, element) into a min-heap keeping size k — O(n log k); compare with bucket sort for O(n) when k ~ categories."),
("What is the quickselect alternative?",
 "Hoare-partition selection on the array of scores, discarding the half that can't contain the answer — O(n) average time, O(1) space but not stable."),
("What is the priority queue key ordering convention?",
 "Python heapq is a min-heap on tuples lexicographically — (count, item) keeps lowest count on top as desired, or use negative keys for max behaviour."),
("What is the difference between this and the heap-pattern?",
 "The top-k pattern IS the heap pattern applied to selection; the heap pattern additionally covers merge-k-sorted and sliding-window-maximum style applications."),
("How do you return the k closest points to origin?",
 "Push (squared-distance, point) into a max-heap of size k and evict the farthest — equivalently a min-heap with negatives; O(n log k)."),
("What is the time/space profile?",
 "O(n log k) time, O(k) space for heap approaches — vs O(n log n)/O(n) for sort; giving both and justifying the choice is the expected interview behaviour."),
("What edge cases need handling?",
 "k == 0, k >= n (return everything sorted), duplicates and ties in frequency, and negative values (they sort normally but ordered-heap keys need consistent polarity)."),
],
"07-K-Way-Merge": [
("What is the k-way merge pattern?",
 "Merging k sorted lists/arrays in O(n log k) using a heap of k heads — extending the standard two-way merge to arbitrary k inputs."),
("What is the algorithm?",
 "Push each list's head (value,list_index) into a min-heap; repeatedly pop the min, add it to output, and push that list's next element — O(n log k)."),
("What is the complexity and why?",
 "Each output element costs O(log k) for one push/pop; with n total elements it's O(n log k) time and O(k) heap space — versus O(nk) naive scanning."),
("When does k-way merge beat flatten-and-sort?",
 "When inputs are already sorted (very often in interview problems): merge is O(n log k), sort is O(n log n) — win when k << n and inputs are ready."),
("How do ties and duplicate values across lists get handled?",
 "Heap tuples compare lexicographically — include the list index in the tuple so equal values from different lists both emerge in stable order."),
("What is merge-k-sorted-lists's classic solution?",
 "A min-heap holding one node per list; pop-min appends to result, then push that list's next node — the canonical LeetCode 23 solution, O(n log k)."),
("How does this connect to external merge sort?",
 "In disk sorting you merge many sorted runs with an external k-way merge — the same heap frontier, bounded by run buffers instead of RAM."),
("What is the two-way merge relationship?",
 "k=2 reduces to the classic merge step of merge sort — the pattern generalises it; combining batched merges (divide-and-conquer pairwise) gives the same O(n log k)."),
("What are the edge cases?",
 "Empty lists among the k inputs, a single non-empty list, k == 0, and lists of drastically different lengths — skip empties upfront."),
("When would you NOT use a heap?",
 "When k is small and lists are tiny — a flattened sort (O(n log n)) or pairwise merges may be simpler and faster in constants; state the trade-off."),
],
"08-Topological-Sort": [
("What is topological sort?",
 "A linear ordering of a DAG such that every edge (u,v) puts u before v — existence requires a DAG; used for dependency/graph ordering problems."),
("What is the Kahn (BFS in-degree) algorithm?",
 "Count in-degrees, put zero-in-degree nodes in a queue, repeatedly remove one and decrement its neighbours; if output length < node count a cycle exists — O(V+E)."),
("What is the DFS-based topological sort?",
 "A post-order DFS push: after visiting all neighbours, push the node; reverse the pushes (or push while unwinding forward) to get a valid order — O(V+E) with a visited/recursion stack."),
("How do you detect a cycle with either algorithm?",
 "Kahn: leftover nodes with non-zero in-degree. DFS: encountering a node already grey (on the current path). Cycle presence invalidates any topological order."),
("What are the classic applications?",
 "Course scheduling/prerequisites, build systems (make), task dependency graphs, and package resolution — any 'what must complete before what' problem."),
("What is the course-schedule problem as topo sort?",
 "If the prerequisite graph is a DAG you can finish all courses — schedule = topological order; asking 'can you finish' becomes 'is there a cycle'."),
("What is the difference between BFS and DFS approaches?",
 "Kahn gives a natural order from linear dependencies and trivial cycle detection via count; DFS gives a recursive order — Kahn is often simpler to reason about and to code."),
("What is the space complexity?",
 "O(V+E) for the adjacency list plus O(V) for in-degrees/queue or recursion depth — the memory profile of the representation, which interviews may probe."),
("Why must the graph be a DAG?",
 "A cycle means each node depends on another in the cycle — no valid order exists; that's why cycle detection is embedded in both algorithms."),
("How would you schedule tasks with durations?",
 "Add weighted 'finish times' along dependency edges — longest-path/topological DP over the order — the natural extension beyond bare ordering."),
],
"09-Binary-Search": [
("What is binary search?",
 "Halving a sorted search space each step via a mid comparison — O(log n) time, the canonical divide-and-conquer search algorithm."),
("What is the standard invariant?",
 "Before every iteration, the answer is known to lie in [lo, hi]; comparing mid decides which half to discard while preserving the invariant — the proof that we never lose the answer."),
("What are the boundary and index conventions?",
 "Lo = 0, hi = n (exclusive) vs hi = n-1 (inclusive) — pick one and be consistent: inclusive [lo,hi] with lo<=hi and mid=(lo+hi)//2 is the popular variant."),
("How do you avoid overflow computing mid?",
 "In Python there's no int overflow, but the general idiom mid = lo + (hi - lo)//2 teaches the skill for fixed-width languages."),
("How do you find the first (or last) occurrence of a value?",
 "Continue searching left after a match (first) or right (last) instead of returning early — binary search over 'where does the true region start'."),
("What is binary search on the answer?",
 "When a predicate is monotone over a numeric range (is this chunk size feasible?), binary search the value, not an index — e.g., minimum capacity or max of k-subarrays."),
("What is the difference between finding a value and finding a boundary?",
 "Value search returns on equality; boundary search (lower/upper bound) keeps searching until lo crosses hi, always maintaining the invariant — the harder-but-standard variant."),
("What are the edge cases?",
 "Empty array, single element, value smaller/larger than all, duplicates, and the boundary at index 0 or n-1 — tests that expose off-by-one."),
("What is the time/space complexity and why is it unbeatable here?",
 "O(log n) comparisons, O(1) space — necessary because each comparison catches (kills) at most half of a sorted candidate set."),
("What is the binary-search pattern in real systems?",
 "Inverted-index ranked retrieval, database low/high bounds, version bisection (git bisect), and any monotone feasibility check — the same O(log n) core everywhere."),
],
"10-Backtracking": [
("What is backtracking?",
 "A systematic search building candidates incrementally and abandoning ('pruning') partial candidates that cannot lead to a solution — DFS with state restoration."),
("What is the general backtracking framework?",
 "for candidate in choices: choose; recurse; un-choose (undo) — with base cases for valid/complete solutions and pruning when constraints are violated."),
("What is the difference between backtracking and brute force?",
 "Brute force enumerates everything; backtracking prunes branches as soon as they violate constraints — same worst case worst-case exponential, far fewer explored on real inputs."),
("What is the classic subset generation?",
 "At each index, decide include-exclude and recurse — each element doubles the branch; adding sum/len constraints prunes heavily (e.g., subsets with target sum)."),
("How do permutations differ from combinations in code?",
 "Permutations care about order (swap-based recursion or used[] set); combinations enforce a start index so subsets stay ordered — the one-line difference interviewers look for."),
("What is the N-Queens problem skeleton?",
 "Place a queen per row, tracking occupied columns and both diagonals; recurse on next row and revert (remove column/diagonal marks) at each undo — an RNQ classic."),
("What is a Sudoku solver's backtracking pattern?",
 "Find an empty cell, try digits 1-9 that are legal in row/col/box, recurse; revert the cell if the branch fails — the canonical full-search-with-revert example."),
("What is time complexity and when is memoisation possible?",
 "Worst case O(choices^depth) — exponential; when overlapping subproblems exist (subset sum), memoisation or DP outperforms pure backtracking; state the distinction."),
("What are the pruning techniques?",
 "Check constraint early (column/diagonal sets), bound partial sums (only recurse if remaining budget possible), and sort/order choices to hit valid solutions earlier."),
("How do you avoid duplicate permutations from repeated elements?",
 "Skip a value equal to the previous sibling (after sorting) unless the previous identical value was already used in this position — a subtle deduplication guard."),
("What is the role of state restoration?",
 "Because branches share data structures, every undos must restore exactly what choose did — forgetting one line leads to the classic cross-branch contamination bug."),
("When would you prefer BFS over backtracking DFS?",
 "When the goal is nearest/min-steps (word ladder) — BFS gives shortest paths in unweighted state spaces; backtracking finds any/all solutions."),
],
"11-Dynamic-Programming-Patterns": [
("What is the dynamic programming pattern?",
 "Solving problems by combining solutions to overlapping subproblems, storing them in a table — beating exponential recursion by avoiding recomputation."),
("What are the two implementation styles?",
 "Top-down (memoised recursion: recursive call + cache) and bottom-up (iteration filling a table in dependency order) — equivalent results; pick by clarity and recursion limits."),
("How do you recognise a DP problem?",
 "Optimal substructure (the best solution uses best solutions of subproblems) + overlapping subproblems (same subproblem solved repeatedly) — the two required properties."),
("What is the standard DP framework?",
 "1) Define state (what am I computing?), 2) recurrence/transition (how to express state in smaller states), 3) base cases, 4) answer location, 5) complexity — in that order."),
("What is the difference between DP and greedy?",
 "Greedy makes a locally optimal choice once with no backtracking; DP evaluates all choices via subproblem optimums — valid only when greedy's simple rule provably works."),
("What are the classic 1-DP patterns?",
 "Climbing stairs, house robber (take/skip with state), longest increasing subarray — single-array transitions ending 'at i' — the entry point to recurrence design."),
("What is the knapsack (0/1) pattern?",
 "State dp[i][w] = best using first i items within capacity w; transition take/skip; the template for subset-sum, partition, and coin-change constrained variants."),
("What is the 2D-grid DP pattern?",
 "dp[i][j] from dp[i-1][j] and dp[i][j-1] (paths) or dp[i-1][j-1] (edit distance) — the matrix-problem template with row-major bottom-up filling."),
("What is the state-machine DP pattern?",
 "Maintain a few states per step (hold/sold/cool) transitioning between them — multi-state 1-DP that handles buy-sell-stock and sequential-decision problems."),
("What is the time/space trade-off in DP?",
 "Full tables are O(states) space; many transitions only need the previous row — rolling arrays cut space to O(1) or O(n) while keeping time equal."),
("When does DP fail?",
 "When subproblems aren't overlapping (divide-and-conquer instead) or the optimal substructure doesn't hold — e.g., longest simple path — and when state space explodes (your choice vs greedy/backtracking)."),
],
"12-Trie-Based": [
("What is a trie (prefix tree)?",
 "A tree where each node stores a character edge, with end-of-word flags — enabling prefix operations in O(word length), independent of corpus size."),
("What is the basic trie interface?",
 "insert(word): walk/create nodes and mark end; search(word): walk confirming end flag; startsWith(prefix): walk without needing the end flag — the three canonical methods."),
("What are the complexities?",
 "Insert/search/startsWith each cost O(L) where L is the word/prefix length; space is O(total characters over all words), trading memory for prefix speed."),
("What is a trie vs a hash set for word lookup?",
 "Hash set finds exact words in O(L) with O(1) hashing but cannot answer prefix queries; the trie answers startsWith in O(L) regardless of how many words share the prefix."),
("What is the autocomplete pattern?",
 "Traverse the prefix, then DFS from the node collecting all words with the accumulated char sequences (bounded by k results) — a direct product of search in the trie."),
("What is a compressed trie / radix tree?",
 "Nodes with single children collapse into one edge — reducing size and nodes while keeping prefix semantics; used in IP routing tables and string dictionaries."),
("What is a ternary search tree?",
 "A 3-way branching trie variant (less/greater/equal) with BST-like balance — comparable prefix search with different memory/balance trade-offs."),
("What applications use tries?",
 "Autocomplete/search suggestions, spell checkers, IP/route longest-prefix matching, word-break with dictionary, and text-pattern indexing — mention any you've applied."),
("How does a trie help the 'word break' problem?",
 "Checking dictionary membership for all substrings near the gap index — a trie accelerates the many-words-starts-with queries vs repeatedly scanning a set."),
("What is the edge case set for tries?",
 "Empty word (root's end flag), a word that is a prefix of another ('the' vs 'them'), and searching to a node that never existed — each decides between search/startsWith semantics."),
],
"13-Union-Find": [
("What is Union-Find (disjoint set)?",
 "A data structure tracking partition membership with near-O(1) amortised find/union — the workhorse for connectivity and dynamic-grouping problems."),
("What are the core operations?",
 "find(x) returns the root/representative; union(a,b) merges two sets; often also connected(a,b) = find(a) == find(b) — maintained in O(alpha(n)) amortised."),
("What are path compression and union by rank/size?",
 "Path compression flattens nodes to their root during find; union by size/rank attaches the smaller tree to the larger — together they give the inverse-Ackermann bound."),
("Why is the union-find so fast?",
 "Both heuristics make trees nearly flat—so find is essentially O(1)—and the amortised bound is O(alpha(n)), effectively constant for all practical inputs."),
("What are the classic applications?",
 "Graph connectivity (is there a path?), number of connected components, detecting cycles in Kruskal's MST, and dynamic equivalence queries — the standard roster."),
("How does union-find detect cycles in undirected graphs (Kruskal)?",
 "Before adding an edge, if find(u) == find(v) the edge creates a cycle — skip it; otherwise union. That single check powers Kruskal's MST algorithm."),
("What is the difference between union-find and BFS/DFS for connectivity?",
 "Union-find supports dynamic connections and incremental queries without re-traversal; BFS/DFS gives an O(V+E) one-shot answer when the graph is static."),
("What is the number-of-provinces problem?",
 "Union-find over nodes; after processing all connections the number of components = distinct roots — a direct application with a child/rank implementation."),
("What is the implementation shape in Python?",
 "parent = list(range(n)); rank = [0]*n; find with while-parent-loop + path compression; union compares ranks then attaches — about 15 lines, tested on classic inputs."),
("What are the edge cases?",
 "n == 0 or 1, disconnected nodes, self-loops, duplicate edges, and nodes added after unions — the boundary set that finds off-by-ones in init/tracking."),
("When is union-find NOT the right choice?",
 "When you need path details (the actual route), shortest distances, or weighted ordering — BFS/Dijkstra/MST handle those; union-find only answers membership queries."),
],
"14-Monotonic-Stack": [
("What is the monotonic stack pattern?",
 "A stack kept monotonic (increasing or decreasing) by popping earlier elements when they're dominated — solving 'next/previous greater/smaller' in O(n)."),
("When does the monotonic stack apply?",
 "Next-greater-element problems, largest rectangle in a histogram, daily temperatures, and trapping rain water — whenever you need to know the nearest larger/smaller neighbour."),
("What is the next-greater-element algorithm?",
 "Iterate right-to-left; pop while the stack top is <= current, then stack top is the answer; push current — O(n) since each element pops at most once."),
("Why is the monotonic stack O(n)?",
 "Every element enters and leaves the stack exactly once — a total of O(1) amortised work per element, so the sequence is linear, not O(n^2)."),
("What does the stack store — values or indices?",
 "Usually indices (so you can compute distances/widths); values are available via the array. The interview follow-up is storing indices for gaps like daily-temperatures."),
("How do you find the next smaller element instead?",
 "Flip the condition: pop while the top is >= current (strictly smaller target) — the mirror-image rule for the opposite ordering."),
("How is the largest rectangle in a histogram solved?",
 "For each bar, the width extends between the previous smaller on the left and next smaller on the right — a monotonic increasing stack computes both boundaries in one pass."),
("What is the trapping-rain-water connection?",
 "A bar's water = min(left max, right max) - height; monotonic stack computes left/right maxima on the fly in O(n) with O(n) space (or O(1) with two pointers)."),
("What is the difference between a monotonic stack and a priority queue?",
 "A stack preserves arrival order with a monotone ordering, perfect for immediate-neighbour dominance; a heap selects the global extreme but can't answer 'nearest greater' directly."),
("What edge cases need testing?",
 "Strictly increasing, strictly decreasing, all-equal, single element, and empty — each changes how pops fire and reveals the <= vs < boundary decision."),
("What is the 'next greater in a circular array' variant?",
 "Process 2n elements (index % n) with the same stack, ignoring pushes beyond n — demonstrating the one-pass trick for circular next-greater problems."),
],
"15-Heap-Pattern": [
("What is a heap?",
 "A complete binary tree stored in an array where each node dominates its children (min-heap: parent <= children) — O(log n) push/pop, O(1) peek of the extreme."),
("How is a heap implemented in Python?",
 "heapq: a list with heappush/heappop — min-heap by default; max-behaviour by negating keys; heapify converts a list to a heap in O(n)."),
("What is `heap` vs `priority queue`?",
 "A priority queue IS the abstract interface (insert + extract-min/max); a binary heap is its classic array-based implementation — they're often used interchangeably."),
("What are the heap's core operations and complexities?",
 "peek O(1), push/pop O(log n), heapify O(n), decrease-key O(log n) — the four numbers every heap answer starts with."),
("When is a heap the right choice?",
 "Repeatedly extracting the extreme or merging streams (top-k, merge-k-sorted, running median, Dijkstra/Kruskal) — any 'always need the current worst/best' workload."),
("What is the running-median problem?",
 "Two heaps (max-heap of lower half, min-heap of upper half) rebalanced on each insert — O(log n) per insert and O(1) median retrieval."),
("What is the difference between a heap and a sorted array?",
 "A sorted array has O(1) exact extremes but O(n) insert; a heap gives O(log n) both — pick by whether insert frequency dominates."),
("What is a heap-based k-way merge vs iterative min scanning?",
 "A heap of k heads gives O(n log k) vs O(nk) scanning all k lists each step — the same selection as the k-way-merge pattern."),
("How does a heap implement Dijkstra's frontier?",
 "A min-heap over (distance, node) with lazy deletions pops the nearest unvisited node each step — the classic shortest-path priority queue."),
("What is 'decrease-key' and when do you need it?",
 "In Dijkstra/A*, reducing a node's key after a better path is found; Python heapq lacks decrease-key — workaround: push a duplicate entry and skip stale pops by confirming the distance."),
("What are the edge cases?",
 "Empty heap (guard pops/peeks), duplicate priorities (add a counter tiebreaker), interleaved operations, and large dashes of pushes/pops (verify heap invariants via inspection)."),
("What is heapify's O(n) magic?",
 "Building from the bottom up costs a sum over subtree heights — mostly O(1) per node, O(n) total — versus O(n log n) for n consecutive pushes."),
],
}