"""Curated Q&A for 03-Python (Basics, Advanced, for-DSA, FastAPI, Flask, Libraries)."""
PYTHON = {
"01-Python-Basics/01-Variables-and-Data-Types": [
("What primitive/immutable vs mutable types exist in Python?",
 "Immutable: int, float, bool, str, tuple, frozenset. Mutable: list, dict, set, bytearray. Immutables can be hashed (dict keys), mutables can be changed in place."),
("What is the difference between == and is?",
 "== compares values (equality); is compares object identity (same memory address). Common trap: small ints and interned strings may compare is True by CPython internment."),
("What is dynamic typing vs static typing?",
 "Python infers types at runtime and rebinds any name; C/Java fix types at compile time. Type hints (PEP 484) only aid tools/mypy, they are never enforced at runtime."),
("What are None and how do you check it?",
 "None is Python's null single object; check with `x is None` (never ==). Functions without return implicitly return None."),
("What is type coercion / implicit conversion in Python?",
 "Operators implicitly convert: int + float -> float, comparisons across int/str fail; use int(), float(), str(), bool() to convert explicitly."),
("What is the scope: LEGB rule?",
 "Name resolution order: Local -> Enclosing -> Global -> Built-in. A name is looked up in that order; assigning creates a local unless declared global/nonlocal."),
("What is integer precision in Python?",
 "Python ints are arbitrary precision (big ints) with no overflow — a common contrast to Java/C where ints wrap or overflow."),
("What is a float and its precision caveat?",
 "IEEE 754 double with ~15-17 significant digits; 0.1 + 0.2 != 0.3 due to binary representation — use Decimal for money, or round for display."),
("What is a boolean in Python?",
 "bool subclasses int; True==1, False==0. Truthiness: empty containers, 0, None, empty str are falsy; everything else truthy."),
("What is the difference between type() and isinstance()?",
 "type(x) gives the exact class; isinstance(x, cls) checks the whole MRO including subclasses — always prefer isinstance for hierarchy checks."),
],
"01-Python-Basics/02-Control-Flow": [
("What is the difference between if/elif/else and a switch statement?",
 "Python has no switch/case (until match case); elif chains evaluate sequentially. match/case (3.10+) provides structural pattern matching."),
("How do for and while loops work?",
 "for iterates over any iterable (list, range, dict, generator); while repeats while a condition is truthy; else on a loop runs if no break occurred."),
("What does break, continue, and pass do?",
 "break exits the innermost loop, continue skips to the next iteration, pass is a no-op placeholder (also used in empty classes/functions)."),
("What is a list comprehension?",
 "A concise constructor: [expr for x in iterable if cond]; equivalent to nested for + append. Prefer comprehensions for readability and speed."),
("What is the ternary conditional expression?",
 "value_if_true if condition else value_if_false — a compact branch; avoid nesting multiple ternaries for readability."),
("What is zip() used for in loops?",
 "Pairs iterables element-wise: for a,b in zip(xs,ys); stops at the shortest; zip_longest (itertools) pads instead."),
("What is enumerate()?",
 "Yields (index, element) pairs in a loop — better than manual range(len(x)) indexing for most cases."),
("What is short-circuit evaluation?",
 "and/or evaluate left to right and stop early: `None or value` returns value, `x and f(x)` never calls f when x falsy — guards avoid errors."),
("What does a for/else or while/else clause mean?",
 "The else block runs only when the loop completes without break — a concise 'didn't find it' flag for search loops."),
("What is a walrus operator (:=)?",
 "Assignment expression binding a value inline: while (line := f.readline()): — Python 3.8+, reduces duplicate calls in conditions."),
],
"01-Python-Basics/03-Functions": [
("What is a function and its components in Python?",
 "A callable block with parameters, body, and optional return. def defines it; the def line runs at definition time binding a name."),
("What is the difference between positional and keyword arguments?",
 "Positional: matched by order. Keyword: name=value matched by name — order-free and self-documenting; both can be combined (positional first)."),
("What are *args and **kwargs?",
 "*args collects extra positional args into a tuple; **kwargs collects extra keyword args into a dict; also used for unpacking when calling (*iterable, **mapping)."),
("What are default arguments and the mutable-default pitfall?",
 "Defaults evaluated once at def time; a mutable default (list/dict) persists across calls — the classic shared-state bug. Fix: use None and create inside."),
("What is a lambda?",
 "An anonymous single-expression function: lambda x: x*2; limited to expressions, no statements/annotations — use for short callbacks (sorted key)."),
("What is the difference between return and yield?",
 "return ends the function giving one value; yield suspends it making a generator — each yield produces one value across multiple next() calls."),
("What is a closure?",
 "A nested function capturing free variables from its enclosing scope, which persist after the outer returns — the basis of decorators and factory functions."),
("What is the difference between positional-only, keyword-only params?",
 "/ marks positional-only; * marks keyword-only. def f(a, /, b, *, c) forces a positional, b either, c keyword — for clear APIs."),
("What is pure function / side effects?",
 "Pure: same input -> same output, no external mutation. Side effects: I/O, global mutation, prints. Pure functions are testable and cacheable."),
("How do you type-hint a function?",
 "def add(x: int, y: int) -> int: — annotations are metadata (not enforced); checked by mypy/pyright. Optional[T], list[T], Callable[...] cover richer signatures."),
("What is the difference between shallow and deep copy related to functions?",
 "Passing a list into a function passes the reference — mutations leak out. Use copy.copy (shallow) or copy.deepcopy to decouple objects."),
],
"01-Python-Basics/04-Lists-and-Tuples": [
("What is a list?",
 "A mutable, ordered sequence of heterogenous objects — O(1) append/pop at end, O(n) insert/remove, supports slicing, indexing, and iteration."),
("What is a tuple and when prefer it over a list?",
 "Immutable ordered sequence — used as dict keys, to return multiple values, and to signal fixed data; slightly cheaper and hashable."),
("What is the difference between list.append, extend, and insert?",
 "append adds one element; extend merges an iterable's items; insert(index, x) places x at a position shifting the rest."),
("How does list slicing work?",
 "lst[start:stop:step] returns a new list (shallow copy of references); negative indices count from the end; lst[::-1] reverses."),
("What is the time complexity of common list ops?",
 "Index O(1), append/pop O(1) amortised, insert/delete middle O(n), membership `in` O(n), copy O(n), sort O(n log n)."),
("What is list comprehension vs map/filter?",
 "Comprehensions are idiomatic and faster than map/filter with lambdas; `[str(x) for x in nums]` reads better than `map(str, nums)` for most developers."),
("How do you flatten a nested list?",
 "[x for sub in nested for x in sub]; generic recursion or itertools.chain.from_iterable for one level."),
("What is a namedtuple?",
 "A tuple subclass with named fields — tuple immutability plus attribute access; used for lightweight records (Point(x=1,y=2))."),
("What are sorting keys?",
 "sorted(lst, key=len) sorts by the key function without touching items; use reverse=True and operator.itemgetter for multi-field sorts."),
("What is a deque and when use it over a list?",
 "collections.deque gives O(1) appendleft/popleft — ideal for queues/undo stacks; lists are O(n) at the front."),
],
"01-Python-Basics/05-Dictionaries-and-Sets": [
("What is a dict and how is it implemented?",
 "An ordered (since 3.7) key→value mapping implemented as a hash table with open addressing; O(1) average lookup/insert/delete."),
("What makes an object usable as a dict key?",
 "It must be hashable — immutable types by default; custom classes are hashable by identity unless __eq__ is defined (then __hash__ must be set to a new rule)."),
("What is the difference between a dict and a set?",
 "dict maps keys to values; set is an unordered collection of unique hashable keys. Both are hash tables; sets support O(1) membership."),
("What is dict.get and setdefault?",
 "get(key, default) returns default instead of raising; setdefault(key, default) inserts only if missing — building counters/grouping without KeyError."),
("What is a defaultdict?",
 "collections.defaultdict(factory) auto-creates missing keys with the factory: defaultdict(list) for appends, defaultdict(int) for counters."),
("What is an OrderedDict vs dict?",
 "dict is insertion-ordered already (3.7+); OrderedDict additionally supports move_to_end/reorder operations used when order changes matter."),
("What is a Counter?",
 "collections.Counter is a dict subclass counting hashables; most_common(k) returns top-k — the canonical frequency tool in interviews."),
("How do you merge two dicts?",
 "d3 = {**d1, **d2} and d1 | d2 (3.9+) merge shallowly with later values winning; update() mutates in place."),
("What is dictionary comprehension?",
 "{k: v for ...} builds a dict in one expression — mapping/reversing dicts (e.g., {v:k for k,v in d.items()})."),
("What is the difference between removing with pop vs del?",
 "dict.pop(key, default) returns the value or default; del d[key] raises KeyError if missing. popitem removes the last inserted item."),
("What is Counter.most_common and its complexity?",
 "Returns sorted-by-count list; O(n log k) via heap if k given, O(n log n) otherwise. The standard answer for top-k frequent elements."),
],
"01-Python-Basics/06-String-Operations": [
("What is a string in Python?",
 "An immutable sequence of Unicode characters; concatenation/sub/replace produce new objects; also sliceable, iterable, and hashable."),
("What is the difference between str methods find and index?",
 "both locate a substring; index raises ValueError, find returns -1 on missing — choose find for probing, index when absence is an error."),
("What are the main string methods?",
 "split/join, strip/lstrip/rstrip, replace, lower/upper, startswith/endswith, count, find/index, format/f-strings — the interview roster."),
("How do you check if a string is a palindrome?",
 "s == s[::-1] after cleaning (lowercase, strip non-alphanumerics). The one-liner every interviewer accepts."),
("What is f-string formatting?",
 "f'{name}, score={score:.2f}' — inline interpolation with format specifiers; Python 3.6+ and the recommended style (faster than % and .format())."),
("What is the difference between split() and split(' ')?",
 "split() splits on ANY whitespace runs and drops empties; split(' ') splits on single spaces preserving empties — a notorious edge case."),
("What is join() and its efficiency?",
 "'-'.join(items) builds one string in one pass — far faster than '+' in a loop (which creates many intermediates)."),
("What are raw strings and regular expressions interplay?",
 "r'\\d+' keeps backslashes literal so regexes write naturally; without r, '\\d' becomes the escape rule of Python strings."),
("What is a substring check and longest-common-prefix approach?",
 "sub in s returns boolean in O(n). For longest common prefix: compare char-by-char across strings, stop at first mismatch — vertical scan."),
("What is str.isdigit vs str.isnumeric?",
 "isdigit covers 0-9 and digit subclasses; isnumeric adds other numeral scripts (roman digits); both ignore minus signs/dots — use carefully on user input."),
("How do you handle Unicode/special characters?",
 "Python strings are Unicode; encode to bytes via .encode('utf-8'), handle normalisation (NFC) for equivalence; len() counts code points, not bytes."),
],
"01-Python-Basics/07-File-Handling": [
("How do you open and read a file?",
 "with open('f.txt','r') as f: data = f.read() — the with block guarantees closing, even on exceptions; modes r/w/a and binary variants."),
("What are the file modes?",
 "r read, w write (truncates), a append, x exclusive create, + for read/write; b for binary ('rb'). Every mode question starts here."),
("What is the difference between read, readline, readlines?",
 "read(size) reads the whole/limited bytes; readline() reads one line with newline preserved; readlines() returns a list of lines — iterate the file object for lines lazily."),
("What is the purpose of the with statement?",
 "Context manager protocol: __enter__/__exit__ run before/after the block, closing the file even on exceptions — the correct resource idiom."),
("How do you write to a file?",
 "f.write(text) writes once; f.writelines(seq) writes many without adding newlines; open with 'w' truncates — use 'a' to append."),
("What is a CSV/JSON read pattern?",
 "csv.reader iterates rows; json.load(fp) parses whole documents; both are stdlib — the data-format handling interviewers ask about."),
("What is seek and tell?",
 "tell() returns the current offset; seek(offset, whence) moves it — used for random access and binary file parsing."),
("What is the difference between buffered and unbuffered I/O?",
 "Text files are line-buffered by default; binary can be buffered (default) or unbuffered (mode buffering=0); flush() forces writes. Performance trade-off."),
("How do you append vs overwrite?",
 "open(...,'a') appends to the end preserving content; open(...,'w') truncates — the classic distinction for log files."),
("How do you iterate a large file efficiently?",
 "for line in open(path): processes line by line streaming from disk — never read() a huge file into memory whole."),
],
"01-Python-Basics/08-Exception-Handling": [
("What is try/except/else/finally?",
 "try runs risky code; except catches specified exceptions; else runs only if no exception; finally always runs (cleanup) — the full block layout."),
("What is the difference between an exception and an error?",
 "Exception: a recoverable runtime fault (ValueError, KeyError, custom). SystemExit/KeyboardInterrupt they are BaseExceptions, not errors — catch carefully."),
("How do you catch multiple exception types?",
 "except (TypeError, ValueError) as e: — one handler for several classes; catch specific types first, Exception last."),
("What is raise and how do you propagate exceptions?",
 "raise ValueError('msg') throws; bare `raise` re-raises the current exception preserving the traceback — idiomatic propagation."),
("What is a custom exception and when define one?",
 "class MyError(Exception): pass — gives callers a stable, semantic type to catch; always subclass Exception, never BaseException."),
("What is the BaseException hierarchy?",
 "BaseException -> Exception -> (ValueError, TypeError, ...); KeyboardInterrupt/SystemExit inherit BaseException directly — a bare except: captures even those (don't do it)."),
("What is an assertion?",
 "assert cond, 'msg' raises AssertionError if false; typically disabled with -O — for invariants, not input validation in production."),
("What is the difference between logging vs printing errors?",
 "Logging (logging module) records structured, configurable, timestamped messages; print goes to stdout. In production use logging.exception in except blocks."),
("What is the with-exception interplay?",
 "Context managers' __exit__ can swallow or re-raise exceptions — allowing resource cleanup plus error suppression where intended."),
("What is the try/finally purpose without except?",
 "finally guarantees cleanup (close files, release locks) even on error, letting the exception propagate — the old pattern the with statement automates."),
],
"02-Python-Advanced/01-OOP-in-Python": [
("What is a class attribute vs instance attribute?",
 "Class attributes are shared across instances (defined in the class body); instance attributes live per-instance (set in __init__). Assignment to self.x shadows the class attr."),
("What is __init__ vs __new__?",
 "__new__ constructs/allocates the instance (called first, classmethod); __init__ initialises it. Override __new__ for immutable subclasses or custom allocation."),
("What is self?",
 "The instance reference passed automatically as the first argument; `self.custom_method()` is `Klass.custom_method(self)` under the hood."),
("What is inheritance and MRO?",
 "A class inherits attributes from its bases; the MRO (method resolution order) via C3 linearisation decides which attribute wins in diamond patterns — use Klass.__mro__."),
("What is super()?",
 "super() returns a proxy to the next class in the MRO — enabling cooperative multiple inheritance and correct __init__ chaining."),
("What is the difference between overloading and overriding?",
 "Override: redefine a method in a subclass (Python supports). Overload: same name multiple signatures — Python has none; emulate with *args/defaults or typing.overload stubs."),
("What is an abstract base class?",
 "abc.ABC + @abstractmethod forces subclasses to implement methods; instantiation is blocked — enforcing an interface contract."),
("What is a property and @classmethod/@staticmethod?",
 "property makes methods look like attributes with get/set/del logic; classmethod receives cls (alternate constructors); staticmethod has no implicit first arg."),
("What is __slots__?",
 "Declaring allowed attributes replaces the per-instance dict with descriptors — less memory and faster attribute access, at the cost of flexibility."),
("What is duck typing and when is isinstance reasonable?",
 "If it walks and quacks treat it as a duck: rely on behaviour, not type. isinstance(x, abc) is acceptable against ABCs for clear contracts."),
("What is composition vs inheritance?",
 "Composition (has-a: hold another object) is flexible and preferred; inheritance (is-a) couples hierarchies — the design discussion for maintainable OOP."),
],
"02-Python-Advanced/02-Decorators": [
("What is a decorator?",
 "A callable that takes a function/class and returns a modified version: @deco is syntactic sugar for f = deco(f). Used for logging, timing, auth, caching."),
("How do you write a decorator preserving metadata?",
 "@functools.wraps(f) copies __name__, __doc__, signature from the original onto the wrapper — essential for debugging and introspection."),
("What is the difference between a decorator taking args and one that doesn't?",
 "A plain decorator receives the function; a parametrised producer (@retry(3)) is a function returning the real decorator — three nested levels."),
("What is a functools.lru_cache decorator?",
 "Memoises a function's results by arguments — turning recursive Fibonacci/DP calls from exponential to linear with one line."),
("How do decorators interact with methods?",
 "On methods the decorator sees the (self + args) tuple; classmethod/staticmethod/property themselves are decorators."),
("What is a class-based decorator?",
 "A class implementing __call__ acts as a stateful decorator — handy when the decoration needs its own attributes and methods."),
("What is decorator stacking/order?",
 "@a then @b means a(b(f)): decorators apply bottom-up, wrappers execute top-down — remember for layered middleware-style decorators."),
("What is a property decorated getter/setter?",
 "@property makes accessor logic look like attribute access; @x.setter captures assignment — clean encapsulation with validation."),
("How do you time a function with decorators?",
 "Wrapping the call in time.perf_counter() and printing the delta — the canonical decorator example used for profiling bottlenecks."),
("What is a @singledispatch decorator?",
 "Generic function dispatch on first-argument type: @singledispatch registers @f.register(int) implementations — polymorphism without isinstance chains."),
],
"02-Python-Advanced/03-Generators-and-Iterators": [
("What is the difference between an iterator and an iterable?",
 "Iterable has __iter__ returning an iterator (list, dict, str); iterator has __next__ producing values until StopIteration — every iterator is iterable of itself."),
("What is a generator?",
 "A function with yield that suspends and resumes — producing a sequence lazily without building a list; memory-efficient streaming."),
("What is the difference between yield and return in a generator?",
 "yield suspends and returns one value, resuming at the next next(); return raises StopIteration with an optional value (in StopIteration.value)."),
("What are generator expressions?",
 "(x*x for x in range(n)) — lazy counterpart of a list comprehension; no list materialised until consumed; sum/any/all accept them."),
("What is the itertools module and its key functions?",
 "chain, product, permutations, combinations, groupby, count, islice, takewhile — lazy composition tools for iteration logic."),
("How do you iterate two lists in lockstep efficiently?",
 "zip(it1, it2) (generator-like) or zip_longest for unequal lengths; avoids manual index bookkeeping."),
("What is a potential infinite generator?",
 "def naturals(): n=0; while True: yield n; n+=1 — must be consumed with islice/takewhile to avoid unbounded loops."),
("What is StopIteration and how do you manually iterate?",
 "The signal that a sequence is exhausted; manual pattern: item = next(it, sentinel) to avoid the exception."),
("What is the producer-consumer with generator.send()?",
 "send() injects values back into a running generator (co-routines pre-async); throw()/close() control lifecycle — the advanced generator API."),
("What is the performance benefit of generators for big data?",
 "Constant memory: process a chunk, discard it. Loading a 10GB file line-by-line (generator) vs whole list — the core streaming argument."),
],
"02-Python-Advanced/04-Context-Managers": [
("What is a context manager?",
 "An object with __enter__/__exit__ used with `with` — guaranteeing setup and teardown (files, locks, connections) even on exceptions."),
("What does __exit__ receive?",
 "(self, exc_type, exc_val, exc_tb); returning True swallows the exception, False propagates it — precise error policy in cleanup."),
("How do you write a context manager with a function?",
 "@contextlib.contextmanager: yield splits enter/exit; code before yield is setup, after is teardown; try/finally inside handles exceptions."),
("What are common built-in context managers?",
 "open(), threading.Lock, decimal context, socket closing, subprocess.Popen, tempfile.TemporaryDirectory — the stdlib roster."),
("How do you manage multiple resources at once?",
 "with A() as a, B() as b: — or contextlib.ExitStack for a dynamic, unknown-at-write-time number of resources."),
("What is contextlib.redirect_stdout?",
 "Temporarily replaces sys.stdout to capture output — used in CLI testing without patching globals manually."),
("What is the difference between a context manager and a decorator?",
 "Context managers wrap a block's lifetime with enter/exit; decorators wrap function calls — complementary: timing can be done either way."),
("What is a database transaction context example?",
 "A context manager that opens a connection, commits on success, rolls back on exception, and always closes — the transactional wrapper pattern."),
("How do you make an object usable in a with statement?",
 "Implement __enter__ returning the managed object and __exit__ doing cleanup; or use @contextmanager to wrap setup/teardown functions."),
("What is suppress vs catch-and-ignore?",
 "contextlib.suppress(FileNotFoundError) swallows specified exceptions around a block — clearer than a bare except for expected absence cases."),
],
"02-Python-Advanced/05-Multithreading": [
("What is a thread?",
 "A lightweight unit of execution sharing the process's memory; Python threads enable concurrency for I/O-bound tasks but not CPU parallelism (GIL)."),
("What is the GIL and its consequences?",
 "The Global Interpreter Lock allows one thread to execute Python bytecode at a time — safe but serial; CPU-bound work needs processes (multiprocessing) or native extensions."),
("What is the threading module's basic API?",
 "threading.Thread(target=fn, args=...), .start(), .join(); lock.acquire/release; Event for signalling; current_thread() for identification."),
("What is a race condition in Python threads?",
 "Two threads read-modify-write a shared variable concurrently; without a lock, updates can be lost — non-atomic += on a list of shared ints is the classic demo."),
("What is a Lock and how do you use it?",
 "lock = threading.Lock(); with lock: guards the critical section; a RLock can be re-acquired by the same thread safely."),
("What is the difference between Lock, Condition, and Event?",
 "Lock: mutual exclusion. Condition: wait/notify on a predicate. Event: a one-shot flag threads wait on — pick per coordination need."),
("What is a Semaphore?",
 "A counter allowing at most N threads in a section simultaneously (rate-limiting concurrent downloads); primitives from the OS concepts apply."),
("How do threads share data safely?",
 "Locks, queues.queue (thread-safe FIFO), threading.local() for per-thread data; ThreadPoolExecutor simplifies bounded parallelism."),
("When are threads preferable to asyncio or processes?",
 "Threads: blocking I/O without rewriting code as async (though GIL shares the core). Processes: true CPU parallelism. asyncio: many concurrent I/O tasks."),
("What is ThreadPoolExecutor?",
 "concurrent.futures.ThreadPoolExecutor maps calls over a fixed pool — collecting results in order while bounding concurrency; the pragmatic parallelism API."),
],
"02-Python-Advanced/06-AsyncIO": [
("What is asyncio and the event loop?",
 "A library for concurrent I/O via coroutines: an event loop schedules awaitables, multiplexing blocking waits with selectors — one thread, many tasks."),
("What is a coroutine?",
 "An async def function that runs until an await, suspending the task; awaited via await or scheduled with asyncio.create_task."),
("What is the difference between async def and a normal function?",
 "Calling an async def returns a coroutine object (nothing runs) until awaited; a normal function executes immediately — the fundamental async distinction."),
("What is await and blocking calls inside coroutines?",
 "await yields control to the loop; blocking (time.sleep, requests.get) inside a coroutine stalls all tasks — always use async.sleep/async HTTP clients (httpx/aiohttp)."),
("What is asyncio.gather?",
 "Runs multiple awaitables concurrently awaiting all results: asyncio.gather(*tasks, return_exceptions=True) — the default parallel fan-out pattern."),
("What is asyncio.create_task vs awaiting directly?",
 "create_task schedules in the background for parallel progress; direct await runs sequentially — create_tasks to fire-and-wait multiple I/Os at once."),
("What is an async generator (async for)?",
 "async def __aiter__ using await and yield per item — streaming from a database cursor or websocket without blocking the loop."),
("What is asyncio.run?",
 "asyncio.run(main()) creates a new loop, runs the coroutine, and closes it — the entry point replacing manual loop handling in scripts."),
("What is to_thread?",
 "asyncio.to_thread(fn, ...) runs the blocking function in a worker thread freeing the loop — bridging sync libraries into async code simply."),
("How does async compare with threading in Python?",
 "async: cooperative, one thread, huge fan-out for I/O; threading: preemptive, GIL-bound; async avoids thread-safety and overhead but requires async libraries throughout."),
],
"02-Python-Advanced/07-Memory-Management": [
("How does Python manage memory?",
 "Reference counting for immediate deallocation plus a generational garbage collector for reference cycles; CPython uses per-size-class arenas (pymalloc)."),
("What is reference counting?",
 "Each object tracks how many references point to it; at zero the object is freed immediately — the primary CPython reclamation mechanism."),
("What is the cyclic reference problem?",
 "Two objects referencing each other never hit zero refcount; the generational GC detects such cycles and collects them — IDs/frames are notable cycle sources."),
("What is the generational GC?",
 "Objects are tracked in 0/1/2 generation buckets; young objects are scanned more often — tuning thresholds trades pause time vs reclaimed garbage."),
("What is the difference between del and the GC?",
 "del just removes a name (decrementing refcount); the GC only matters for cycles — resource classes often need __del__ to complement."),
("What is weakref and when use it?",
 "weakref.ref(obj) observes an object without keeping it alive, turning None once collected — for caches/observers that shouldn't leak."),
("What is memory profiling?",
 "tracemalloc and objgraph quantify per-line allocations and object growth — used to find leaks and large temporaries."),
("What does sys.getrefcount(x) show?",
 "The current reference count (including the temporary from the argument pass) — a debugging peek at an object's popularity."),
("What is the id() and the difference between object identity and equality?",
 "id(obj) is the CPython address (unique while alive); two equal values ('a' and 'a') may share one interned object — but that's implementation detail, not guaranteed."),
("How do you reduce memory for large datasets?",
 "__slots__, generators, array module, NumPy for typed arrays, avoiding list-of-dicts, and streaming processing — the pragmatic performance playbook."),
],
"02-Python-Advanced/08-Meta-Programming": [
("What is meta-programming in Python?",
 "Code that generates/manipulates code at runtime: decorators, descriptors, __getattr__, metaclasses, __new__/__init_subclass__, inspect, eval/exec."),
("What is a metaclass?",
 "The class of a class — type by default; a metaclass controls class creation/extraction (before __init__ of the class object). Used for registering subclasses, enforcing interfaces."),
("How does type() create a class dynamically?",
 "Klass = type('Klass', (Base,), {'attr': 1, 'method': fn}) — building classes at runtime without class statements."),
("What is __getattr__ vs __getattribute__?",
 "__getattr__ is called only when normal lookup fails (missing attrs); __getattribute__ intercepts ALL attribute access — implement proxies/Mock-style objects."),
("What is a descriptor?",
 "An object with __get__/__set__/__delete__ controlling attribute access; property/classmethod/staticmethod are descriptors — the mechanism behind properties."),
("What is class-level registration pattern?",
 "A metaclass or __init_subclass__ auto-registers every subclass in a registry — used in plugin frameworks and DB ORMs (declarative models)."),
("What is inspect module used for?",
 "Introspecting signatures, source code, class hierarchies, and stack frames — powering debuggins, frameworks, and CLI tools."),
("What is __new__ used for in classes beyond allocation?",
 "In metaclasses/immutables, __new__ runs before __init__, enabling cache-keyed singletons, singleton enforcing, and subclass filtering."),
("What is the difference between class methods and metaprogramming by decorators?",
 "Decorators manipulate callables; metaclasses manipulate classes themselves — choose decorators for functions, metaclasses when you control class construction."),
("What is dataclasses and how is it meta-programmed?",
 "@dataclass auto-generates __init__, __repr__, __eq__ from annotations — a pragmatic everyday example of code generation without metaclass verbosity."),
],
"03-Python-for-DSA/01-Implementing-Data-Structures": [
("Which built-in containers map to classic data structures?",
 "list = dynamic array; tuple = persistent array; dict/set = hash table; deque = queue/deque; heapq = binary heap; str = char sequence — all ready in stdlib."),
("How do you implement a stack in Python?",
 "A list with append()/pop() gives O(1) LIFO; or collections.deque for thread-safety. The stack interview primitive."),
("How do you implement a queue in Python?",
 "collections.deque with append()/popleft() (O(1) both ends); queue.Queue is a thread-safe blocking wrapper. A single list head is O(n) — avoid."),
("How do you implement a min-heap?",
 "import heapq; heapq.heappush(h, x); heapq.heappop(h) — Python's heapq IS a min-heap binary tree in a list; use -values for max-heap behaviour."),
("How do you implement a binary-search tree (BST)?",
 "A Node class with left/right and insert/search/delete traversals; Python's recursion rebuilds nodes (3.12) or iterative pointer walking avoids recursion limits."),
("How do you implement a linked list in Python?",
 "class Node: __init__(self, val, next=None); maintain head reference with iterative loops and dummy-node sentinel for edge cases."),
("How do you implement a hash table from scratch?",
 "Array of buckets + hash() of keys + separate chaining or open addressing; Python's dict does this natively but interviews test the theory."),
("How do you implement a graph adjacency list?",
 "dict: node -> list/set of neighbours (or dict of weights); 30 lines take you through BFS/DFS/Dijkstra — the foundational interview representation."),
("What is a Trie and how to implement it?",
 "A tree of characters; children dict per node with an end-of-word flag — prefix queries in O(len) using sum/any/all and set of `words` termination."),
("How do you implement LRU cache in Python?",
 "collections.OrderedDict move_to_end/popitem(last=False), or linked list + dict manually — the classic system-design-on-whiteboard pair."),
("How do you implement a disjoint-set (Union-Find)?",
 "parent array + rank/size, find with path compression, union by size — near O(alpha(n)) inverse Ackermann for connectivity problems."),
("How do you implement a segment tree?",
 "A 4n array tree of range aggregates; build, point update, range query — O(log n); iterative version avoids recursion."),
],
"03-Python-for-DSA/02-Python-Specific-Tricks": [
("What is the fast input/output idiom in competitive Python?",
 "import sys; data = sys.stdin.buffer.read().split(); iterate tokens — dramatically faster than input() for large competitive datasets."),
("How do you do a 2 sum with a dictionary?",
 "seen = {}; for i,x in enumerate(nums): if target-x in seen: return [seen[target-x], i]; seen[x] = i — O(n) one-pass."),
("What is the Counter-based group count for anagram grouping?",
 "sorted(item) or tuple(sorted(item)) as the group key groups anagrams in O(n * k log k); Counter keys enable O(nk)."),
("How do you reverse a list/string/subarray?",
 "nums.reverse() or nums[::-1]; two-pointer swap for in-place subarray reversal — the O(n)/O(1) idiom."),
("How do you zip and transpose a matrix?",
 "list(zip(*matrix)) transposes a rectangular grid; for (r,c) loops still matter for in-place matrix problems."),
("What is the heap-based top-k idiom?",
 "heapq.nlargest(k, iterable) / nsmallest; or push k then replace for streaming — the one-liner for Top-K questions."),
("How do you handle big integers in Python DSA?",
 "Python ints are arbitrary precision so no overflow — but that means you can be tempted into constant-time-complexity cheating; clarify time bounds with the interviewer."),
("What is the bitwise fast exponentiation?",
 "pow(base, exp, mod) is O(log exp); or manual loops shifting the exponent — modular arithmetic for count-ways problems."),
("What is the trick for sorting by a complex key?",
 "sorted(items, key=lambda x: (-x[1], x[0])) sorts by frequency desc then name asc — two-field orderings in one key tuple."),
("How do you avoid O(n^2) string concatenation in loops?",
 "Collect parts in a list then ''.join(parts) — concatenating in a loop is quadratic; join is a single linear pass."),
("What is the in-place swapping trick?",
 "arr[i], arr[j] = arr[j], arr[i] — Python's tuple-assignment swap; the bread-and-butter for partition/pointer algorithms."),
("How do you convert between int and string bases?",
 "int(s, 16), hex(255), format(n, 'b') for binary — quick numeral-system conversions for interview problems."),
],
"03-Python-for-DSA/03-Time-and-Space-Complexity": [
("What is Big-O notation?",
 "An asymptotic upper bound characterising how runtime/memory scale with input size: O(1), O(log n), O(n), O(n log n), O(n^2), O(2^n) — ignoring constants and lower-order terms."),
("How do you compute the complexity of nested loops?",
 "Multiply the iteration counts when inner counts are independent; when inner depends on outer, sum them (e.g., 1+2+...+n = O(n^2))."),
("What is amortised analysis and why are append/pop O(1)?",
 "Occasional costly resizing is spread over the many cheap operations; dynamic arrays have amortised O(1) append — the 'average over a sequence' view."),
("What is the difference between O(n) and Omega(n)?",
 "O is an upper bound (worst-case-ish), Omega a lower bound, Theta the tight bound; interviews mostly probe O, but explaining worst vs average vs expected is a win."),
("What is the time complexity of sorting algorithms?",
 "Quick/Merge/Heap O(n log n) worst (merge/heap guaranteed); Bubble/Insertion O(n^2); Counting/Radix O(n + k) for restricted domains."),
("What is the space complexity of recursion?",
 "Each active frame occupies O(depth); DFS recursion depth n -> O(n) stack space; converting to iteration or DP usually drops that."),
("How do you analyse a two-pointer algorithm?",
 "Each pointer moves at most once across the array -> O(n) total even with a nested-ish look — the linear-time argument for sliding-window/2sum-sorted."),
("What does O(log n) usually come from?",
 "Halving each step: binary search, balanced BST depth, divide-and-conquer merges — logarithmic behaviour signals a halving structure."),
("What is a complexity blow-up example in recursion?",
 "Naive Fibonacci is O(2^n); memoisation collapses the DAG of overlapping subproblems to O(n) — the cleanest DP motivation interviewers use."),
("What is the trade-off of memoisation/bi-time?",
 "DP/caching trades memory (O(state) table or dict) for speed; hash collisions keep true worst case O(n) per op but average O(1)."),
],
"04-FastAPI/01-FastAPI-Basics": [
("What is FastAPI and why is it popular?",
 "A modern Python web framework built on Starlette + Pydantic; async support, automatic OpenAPI docs, type-driven validation, high performance, and minimal boilerplate."),
("How does FastAPI handle request validation?",
 "Pydantic models (type-annotated) validate the request body; Query/Path/Header/Body parameters type-validate inputs — 400s returned automatically on mismatch."),
("What is the difference between a query and a path parameter?",
 "Path parameters are part of the URL (/users/{id}); query params follow ?key=value. FastAPI maps both via the function signature."),
("How do you define a GET vs POST endpoint?",
 "@app.get('/items') vs @app.post('/items') with a Pydantic body model; method decorators map HTTP verbs to handlers cleanly."),
("What is the automatic OpenAPI/swagger documentation?",
 "FastAPI generates /docs (Swagger UI) and /redoc from type annotations — interactive API docs without configuration."),
("What is the difference between sync and async endpoints?",
 "def endpoints run in a threadpool; async def run on the event loop — use async for I/O-bound work, sync for CPU-bound/blocking libs."),
("What is the FastAPI dependency injection system?",
 "Depends() resolves function dependencies per request — shared DB sessions, auth checks, and pagination params with automatic cleanup."),
("What is the app factory / lifespan pattern?",
 "lifespan context manager (FastAPI 0.93+) wires startup/shutdown — opening DB pools or model caches once at app boot."),
("How do you run FastAPI?",
 "uvicorn app.main:app --reload — the ASGI server; options --host 0.0.0.0 --port 8000; gunicorn with uvicorn workers in production."),
("How does FastAPI compare to Flask?",
 "FastAPI: async, auto-docs, Pydantic validation, performance. Flask: synchronous, minimal, WSGI, mature ecosystem. Choose FastAPI for new APIs, Flask for simplicity/legacy."),
],
"04-FastAPI/02-Request-Handling": [
("How do you read query parameters in FastAPI?",
 "Annotate plain args: def search(q: str, limit: int = 10) — validated and auto-documented; Query(...) adds constraints (min_length, regex)."),
("How do you read path parameters?",
 "def get_item(item_id: int) — path matching with type coercion; a bad int returns 422 automatically."),
("How do you read a JSON request body?",
 "A Pydantic model param: def create(item: Item) — FastAPI parses and validates into the model; nest models for complex payloads."),
("How do you send a file upload?",
 "UploadFile or bytes param with Python-multipart installed; Python's file object streams to disk without loading everything in memory."),
("How do you return custom status codes and headers?",
 "Return Response(status_code=201) or use the response_model and status_code decorator args; JSONResponse/PlainTextResponse give low-level control."),
("What is response_model and why does it matter?",
 "It filters/validates the OUTGOING payload — hiding sensitive fields and guaranteeing the API contract; also documents OpenAPI responses."),
("How do you handle errors/404s?",
 "HTTPException(status_code=404, detail='...') raises the response; custom exception handlers via @app.exception_handler(MyError)."), 
("How do you handle CORS?",
 "CORSMiddleware with allow_origins/allow_methods/allow_headers — configure per environment; critical for web frontends calling the API."),
("What is a middleware and how do you add one?",
 "Code running before routing for every request (logging, auth, timing); use @app.middleware('http') or BaseHTTPMiddleware class."),
("How do you do request logging?",
 "A middleware logs method, path, status, and duration with the logging module — observability without touching each endpoint."),
],
"04-FastAPI/03-Database-Integration": [
("How do you connect FastAPI to PostgreSQL?",
 "SQLAlchemy engine + sessionmaker with a DATABASE_URL ('postgresql+psycopg' or asyncpg for async); SQLAlchemy models map tables to classes."),
("What is SQLAlchemy ORM vs raw SQL?",
 "ORM maps Python classes to tables with sessions and query builders; raw SQL (psycopg/asyncpg) gives full control — ORM for productivity, raw for hot paths."),
("What is the dependency-injected DB session pattern?",
 "def get_db(): db = SessionLocal(); try: yield db; finally: db.close() — Depends(get_db) gives each request an isolated session."),
("How do you run migrations?",
 "Alembic generates versioned migration scripts (autogenerate from model diffs), upgraded via alembic upgrade head — the schema-evolution standard."),
("What is SQLite vs PostgreSQL in local dev?",
 "SQLite: file-based, zero-config, good for tests/prototyping. PostgreSQL: server, concurrency, JSONB, production. Use SQLite for devs, PG for deployment — the ResumeSQLite->PG path."),
("How do you handle async database access?",
 "asyncpg/SQLAlchemy async or FastAPI's Depends with an async session; synchronous sessions work automatically in threadpool endpoints."),
("What is a transaction in a FastAPI endpoint?",
 "Session wraps statements in one transaction; commit on success, rollback on exception — ACID compliance via the ORM session pattern."),
("How do you prevent SQL injection?",
 "SQLAlchemy parameterised queries / bound parameters; never f-string interpolate raw SQL — validator + ORM layers make injection a non-issue."),
("What is connection pooling?",
 "psycopg2 pool or asyncpg pool reused across requests instead of opening per-request connections — bootleneck-free concurrency under load."),
("How do you seed/init a database on startup?",
 "lifespan handler runs create_all/seed scripts once at boot — or Alembic handles it in deployment; testing uses fresh in-memory SQLite."),
],
"04-FastAPI/04-Authentication": [
("What are the common auth flows for a FastAPI API?",
 "OAuth2 + JWT bearer tokens; session cookies for browser apps; API keys for machine clients — choose by client type and revocation needs."),
("How do you implement JWT auth in FastAPI?",
 "python-jose/pyjwt to sign {sub, exp, scopes}; an OAuth2PasswordBearer dependency decodes and validates the token for protected routes."),
("What is the AuthUser dependency pattern?",
 "def get_current_user(creds=Depends(oauth2_scheme)): validate JWT then load the user — injected into every protected endpoint."),
("How do you store passwords safely?",
 "bcrypt/passlib hash + salt; never plaintext. Compare with bcrypt.checkpw; cost factor tuned for security vs latency."),
("What is OAuth2 and the password flow?",
 "Client trades credentials for a token via the /token endpoint; scopes limit what the token may do — the standard for third-party access."),
("What is the difference between an access token and a refresh token?",
 "Access: short-lived JWT on each request. Refresh: long-lived secret exchanged for new access tokens when they expire — enhancing revocation."),
("What are scopes and role-based access?",
 "JWT 'scope' claims map to permissions; dependencies check scopes/roles before serving — RBAC at the endpoint level."),
("How do you protect against token theft?",
 "HTTPS only, short access-token lifetimes, secure HttpOnly cookies, refresh-token rotation, and rate limiting on /token."),
("What is the difference between Basic, Bearer, and API-key auth?",
 "Basic: username:password base64 (TLS-required). Bearer: a token in Authorization header — JWT flows. API key: static per-client — simple machine access."),
("What is CORS and CSRF interplay with auth?",
 "CORS limits which origins may call the API; cookie-based auth needs CSRF tokens; bearer tokens are origin-agnostic — trade-offs per auth style."),
],
"04-FastAPI/05-Deployment": [
("How do you containerise a FastAPI app?",
 "Dockerfile: python:3.11-slim, pip install from requirements, uvicorn command — multistage builds shrink image size for prod."),
("What is the production run command for FastAPI?",
 "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app — multiple processes balancing async workers; or uvicorn directly for small apps."),
("What is the .dockerignore / .env handling?",
 "Exclude __pycache__, .venv, .env from the image; forward DATABASE_URL/SECRET_KEY via environment/compose — never bake secrets into images."),
("What does the HEALTHCHECK endpoint do?",
 "GET /health returning 200 when the app is up — used by load balancers and container orchestrators to decide instance health."),
("How do you approach zero-downtime deploys?",
 "Rolling updates (multiple instances restaged), readiness probes, and tagging immutable images — standard release engineering for APIs."),
("What is uvicorn vs gunicorn vs daphne?",
 "uvicorn: ASGI server (async). gunicorn: WSGI process manager wrapping uvicorn workers for CPU scaling. daphne: Django-specific ASGI."),
("How do you manage environment configuration?",
 "pydantic-settings BaseSettings reading env vars / .env files with typed defaults — config moving safely between dev/staging/prod."),
("What is a reverse proxy + TLS termination?",
 "nginx/traefik or a cloud LB terminates HTTPS and proxies to uvicorn on localhost — offloading certs and adding buffering."),
("How do you set up CI/CD for the API?",
 "GitHub Actions: run pytest + lint, build/push image, then deploy to the cluster/server on merge — the pipeline you listed on your resume."),
("What metrics/logging do you ship?",
 "Structured JSON logs via logging, request latency/error-rate metrics, and /metrics (Prometheus format) — observability prerequisites."),
("How do you debug a crashed production instance?",
 "Read structured logs, check health/readiness events, inspect resource metrics, reproduce locally with the same image/version — the SRE rundown."),
],
"04-FastAPI/06-Advanced-FastAPI": [
("What is background task processing in FastAPI?",
 "BackgroundTasks (run after response) for emails/reports; heavier jobs go to Celery/RQ with a broker — decide by durability needs."),
("What are WebSockets in FastAPI?",
 "@app.websocket('/ws') with WebSocket accept/send/receive — real-time bidirectional streaming for chat/live dashboards."),
("What is rate limiting on FastAPI?",
 "slowapi or a middleware using Redis counters per IP/user — protecting public endpoints from abuse (the DBMS/network security interplay)."),
("How do you paginate results?",
 "Query params limit/offset (or cursor) backed by SQL LIMIT/OFFSET; response_model returns total too — the standard read-API pattern."),
("What is a caching layer for FastAPI responses?",
 "In-process TTL cache, Redis, or CDN for GET endpoints; invalidate on writes — reducing DB load for hot reads."),
("What is request validation beyond types?",
 "Pydantic validators, Field(min/max)/regex, and custom validation in model @field_validator — enforcing business rules at the boundary."),
("How do you version an API?",
 "URL prefixes (/v1/...) or header negotiation; keep old versions live during a deprecation window — graceful evolution."),
("What is the difference between a dependency and a middleware?",
 "Dependencies are per-endpoint resolution (auth, DB); middleware wraps the whole app (logging, CORS) — distinct but complementary layers."),
("How do you add OpenAPI customisation?",
 "title/version/description on the app, tags per router, and response examples — documentation quality as a selling point."),
("What is the repository/CRUD pattern in FastAPI apps?",
 "Routers (HTTP) -> services (business logic) -> repositories (data access) separation — testability and maintainability at scale."),
],
"05-Flask/01-Flask-Basics": [
("What is Flask and its design philosophy?",
 "A micro web framework with just routing/request/response core; extensions add DB, auth, forms — simple and explicit, WSGI-based."),
("What is the app object and application factory?",
 "Flask(__name__) creates the WSGI app; a create_app() factory builds and returns it — supporting configurations per environment and testability."),
("What is the difference between a route decorator and a route with rules?",
 "@app.route('/user/<int:user_id>') maps paths with converters (int, string, float) — Flask's URL parameter handling."),
("How does Flask serve requests?",
 "The built-in dev server (app.run) is for development; production uses gunicorn/waitress/uWSGI — WSGI servers, not threaded toy servers."),
("What is the Flask request/response cycle?",
 "WSGI hands the environ -> Flask builds a request context -> view function -> response -> WSGI returns it; teardown frees the context."),
("What are Flask blueprints?",
 "Modular route/staticmethod groups registered on the app — organising large apps into features instead of one monolithic file."),
("What is the Jinja2 relationship to Flask?",
 "Flask's default template engine — server-side rendering variables, loops, conditions, and template inheritance for HTML pages."),
("What is the app context vs request context?",
 "App context: app-wide globals (current_app). Request context: per-request data (request, session). Both push/pop around request handling."),
("How do you configure Flask?",
 "app.config from dicts/env files; SECRET_KEY, DEBUG, DATABASE_URL — configuration segregation across environments."),
("How does Flask compare to FastAPI?",
 "Flask: simple, sync, WSGI, huge plugin ecosystem. FastAPI: async, typed, auto-docs. Migrating adds async loudly only where needed."),
],
"05-Flask/02-Routing": [
("How do you define routes with dynamic segments?",
 "@app.route('/items/<int:item_id>') — converters parse path segments; unmatched types give 404 automatically."),
("How do you read query strings in a view?",
 "request.args.get('q', '') — werkzeug MultiDict handles duplicate keys; request.values merges form + args."),
("How do you accept POST/form data?",
 "request.form for urlencoded, request.json (or request.get_json()) for JSON — method='POST' on the route controls access."),
("What are HTTP methods on a single route?",
 "@app.route('/', methods=['GET','POST']) with request.method branching inside, or separate functions per method via a dispatch."),
("How do you build URLs / redirects?",
 "url_for('view_name', arg=1) generates URLs by endpoint name; redirect(url_for(...)) sends 302 — reverse routing keeps links stable."),
("What is a 404 handler?",
 "@app.errorhandler(404) customises the not-found page/JSON — building friendly errors audiences expect."),
("What are route names and how does Flask look them up?",
 "Each view's name becomes an endpoint; blueprints prefix it (bp.view); url_for uses that full name — naming discipline matters in templates."),
("How do you handle trailing slashes?",
 "Flask redirects /path/ -> /path depending on route definition strict_slashes — a common gotcha in mounting."),
("What is before_request vs after_request?",
 "@app.before_request hooks run pre-route (auth, db); @app.after_request post-route (headers, caching) — Flask's middleware-style hooks."),
("What is an errorhandler exception type?",
 "@app.errorhandler(MyError) custom exception -> response mapping; combining with raise lets views fail cleanly."),
],
"05-Flask/03-Templates": [
("What is template inheritance?",
 "A base.html with {% block content %} regions; child templates {% extends 'base.html' %} and override blocks — DRY page layout."),
("What is the Jinja2 variable escaping?",
 "{{ user.name }} auto-escapes HTML by default to prevent XSS; use |safe only for trusted content — the security-critical detail."),
("How do you loop and branch in templates?",
 "{% for item in items %} ... {% endfor %} and {% if cond %}: template control flow mirroring Python minus the colons."),
("How do you pass context to templates?",
 "render_template('x.html', name=name) exposes variables; global template utils (config, url_for) are always available."),
("What are template filters?",
 "|lower, |date('%Y-%m-%d'), |default('n/a') post-process values in the template — keep formatting in the view layer."),
("What is a macro in Jinja2?",
 "{% macro input(name) %} reusable template fragments with parameters — rendering components without a JS framework."),
("How do you avoid duplicate HTML with partials?",
 "{% include '_item.html' %} reuses a snippet; macros parametrise it further — componentising server-rendered pages."),
("What is the difference between {{ }} and {% %}?",
 "{{ expression }} prints a value; {% statement %} executes logic (if/for/extends/block) — the two Jinja syntactic classes."),
("How does template rendering relate to XSS?",
 "Auto-escaping neutralises injected <script>; the |safe escape hatch reopens it — never mark user input safe."),
("How do you internationalise templates?",
 "Jinja2 i18n extensions with gettext-style translations and locale selection — not every app needs it, but the pattern exists."),
],
"05-Flask/04-Database": [
("What is Flask-SQLAlchemy?",
 "The Flask extension wrapping SQLAlchemy with db = SQLAlchemy(app) — models subclass db.Model; sessions bound to request contexts."),
("What is db.create_all vs migrations?",
 "create_all builds tables from models (dev/tests only); Flask-Migrate (Alembic) version-migrates in production — never create_all against real data."),
("How do you query in Flask-SQLAlchemy?",
 "Model.query.filter_by(...).all(), .filter(Model.col == x), .order_by(desc(Model.date)), .limit(10).offset(0) — the CRUD query vocabulary."),
("How do you insert/update/delete rows?",
 "db.session.add(obj) / commit; obj.col = new; commit; db.session.delete(obj); commit — the ORM session/transaction unit."),
("What is lazy loading in SQLAlchemy?",
 "Relationships load on first access (default) unless eager_loaded with .options(joinedload(...)) — N+1 queries are the main SQLAlchemy perf trap."),
("What is the N+1 query problem?",
 "Loading N parents then accessing a relation issues N more queries; fix with selectinload/joinedload or explicit joins — a must-know ORM efficiency point."),
("How do you write raw SQL alongside the ORM?",
 "db.session.execute(text('SELECT ...')) for complex queries — the pragmatic escape hatch when the ORM abstracts too much."),
("What is a backref and relationship?",
 "db.relationship('Post', backref='author') gives two-way access Post.author and author.posts — concise relational mapping."),
("How do you handle transactions in Flask?",
 "Each request gets a session; commit at the end or rollback on 500; flask-shell propagates exceptions requiring explicit savepoints for partial success."),
("What is the JSON column vs normalised tables?",
 "JSON for flexible/semi-structured data; normalised tables for queryable relations — the schema-space trade-off in design discussions."),
],
"05-Flask/05-Advanced-Flask": [
("How do you secure a Flask API?",
 "JWT/Flask-JWT-Extended for tokens, password hashing (bcrypt), rate limits, HTTPS, and input validation — the same trust boundary as FastAPI routes."),
("How do you run Flask asynchronously?",
 "Flask is sync WSGI; async views exist but the threading model stays — gunicorn with gevent/eventlet workers for concurrent I/O at scale."),
("What is a Flask extension you'd recommend and why?",
 "Flask-SQLAlchemy, Flask-Migrate, Flask-Login, Flask-Session, Flask-CORS — the standard batteries for CRUD apps and APIs."),
("How do you structure a large Flask application?",
 "Blueprints per feature + app factory + service/repository layers + config module — the scaling structure micro-frameworks require by hand."),
("How do you implement caching in Flask?",
 "Flask-Caching with in-memory or Redis backend, cached() route decorators, and key invalidation — reducing DB chatter for hot endpoints."),
("How do you send background email in Flask?",
 "Celery/RQ tasks with a broker (Redis), queued from the view and processed by workers — offloading slow side-effects from the request."),
("How do you write tests for Flask?",
 "app.test_client() with GET/POST calls, assert status_code/data; separate test DB; pytest fixtures rebuild schema — the unittest discipline you have."),
("What is Flask deploy monitoring?",
 "Structured logs, request metrics, health endpoints, and error trackers (Sentry) — observability requirements mirror FastAPI deployment."),
("How do you handle file uploads in Flask?",
 "request.files['file']; validate secure_filename(); stream to storage; never trust client filenames — upload security patterns."),
("What is Flask session vs cookies?",
 "session is a signed cookie (client-side store, validated server-side); Flask-Session moves it server-side — the auth-state design discussion."),
("How do you version Flask APIs?",
 "Blueprint per version (/api/v1, /api/v2) or Accept header; keep old versions during deprecation — the same API-evolution guidance as FastAPI."),
],
"06-Python-Libraries/01-Pandas": [
("What is a DataFrame?",
 "A labelled 2D table with Series columns (typed, indexable) — pandas' core structure for tabular data manipulation."),
("What is a Series?",
 "A one-dimensional labelled array (index + values) — the column primitive underlying DataFrames; ops vectorise like NumPy."),
("What is the difference between loc and iloc?",
 "loc selects by label (df.loc['row','col']), iloc by integer position — mixing them is a classic bug; both support slices."),
("How do you filter rows?",
 "Boolean masks: df[df['age'] > 30]; combine with & | ~ (use parentheses); .query() writes it as a string expression."),
("How do you group and aggregate?",
 "df.groupby('category')['amount'].sum() / .agg(['sum','mean','count']) — the pandas analogue of SQL GROUP BY."),
("How do you handle missing values?",
 "df.isna().sum() to inspect; df.dropna() and df.fillna(value / method='ffill') — choosing per analysis, never by default."),
("How do you merge two DataFrames?",
 "pd.merge(a, b, on='key', how='inner'/'left') maps SQL JOINs; pd.concat stacks rows/columns when concatenating."),
("What is the difference between apply, map, and applymap?",
 "Series.map maps values; df.apply applies row/column-wise functions; applymap applies elementwise on a DataFrame — pick per axis."),
("How do you read data from various formats?",
 "pd.read_csv, read_json, read_excel, read_sql(query, engine) — parsing datasets directly into DataFrames for analysis."),
("What is the vectorisation benefit over Python loops?",
 "NaN-safe column ops execute in C; a group-level calculation that loops 100k rows in Python is a 100x slowdown compared to pandas idioms."),
("How do you reshape data?",
 "df.pivot_table(values=..., index=..., columns=...) and df.melt(id_vars=...) flip wide/long — the tidy-data operations."),
("How do you compute salary/aggregate stats for a report?",
 "df.groupby('dept')['salary'].mean().sort_values(ascending=False) — chaining groupby-agg-sort, the analysis idiom interviewers want to hear."),
],
"06-Python-Libraries/02-NumPy": [
("What is NumPy and its core object?",
 "A library for fast numeric arrays; the ndarray — homogeneous typed data in contiguous memory enabling vectorised C-speed computation."),
("What is the difference between a NumPy array and a Python list?",
 "ndarray: fixed-size, homogeneous, vectorised ops, broadcasting; list: heterogeneous, dynamic, Python objects, loops — arrays dominate numeric workloads."),
("What is vectorisation and why does it matter?",
 "Operators run over whole arrays without Python-level loops: arr * 2, arr1 + arr2 — speed and cleaner code for element-wise math."),
("What is broadcasting?",
 "NumPy implicitly stretches a smaller array across a larger one (shape rules) — arr + 5 or (3,1) + (1,4); knowing the rules avoids shape errors."),
("How do you create arrays common ways?",
 "np.array(list), np.zeros, np.ones, np.arange, np.linspace, np.random.rand, np.eye — the instantiation roster for interviews and data work."),
("What is the difference between reshape, resize, and flatten?",
 "reshape returns a new view (or copy) with the same data; resize mutates in place; flatten/flatten always copies; ravel may view — memory behaviour differences."),
("What are boolean mask indexing?",
 "arr[arr > 5] returns the elements satisfying a condition — fast filtered selection powering pandas' masks underneath."),
("What is the axis concept?",
 "axis=0 is down rows (columns aggregated), axis=1 is along columns (rows aggregated); np.sum(arr, axis=1) sums each row — the classic confusion point."),
("What is the performance story of NumPy vs pure Python?",
 "C implementation, cache-friendly contiguous memory, no per-op Python overhead — 10-100x speedups on elementwise/linear-algebra workloads."),
("What is np.where?",
 "np.where(cond, x, y) vectorised select; np.where(cond) returns indices — the array-level if-else function."),
("How do you compute a mean/std in NumPy?",
 "arr.mean(), arr.std(), np.percentile(arr, 90), np.argmax(arr) — the aggregate statistics arsenal for ML feature pipelines."),
("What is a dot product and its use?",
 "np.dot(a, b) / a @ b computes matrix products — the linchpin for linear algebra in ML/statistics (regressions, embeddings)."),
],
"06-Python-Libraries/03-Requests-and-HTTP": [
("What is the requests library?",
 "The de-facto HTTP client for Python — params, headers, JSON bodies, sessions, and timeouts wrapped in a clean API."),
("How do you make a GET request with parameters?",
 "requests.get(url, params={'q': 'x'}) — params auto-encodes into the query string; headers= sets auth/accept."),
("How do you handle a POST with JSON?",
 "requests.post(url, json={'key': 'value'}) — json= serialises, sets Content-Type: application/json; data= sends form-encoded."),
("What is the difference between response.text, .json(), and .content?",
 ".text decodes str; .json() parses JSON (raises on invalid); .content is raw bytes — choose based on the payload format."),
("What is check_for_status?",
 "resp.raise_for_status() raises HTTPError for 4xx/5xx — forcing explicit error handling instead of silent partial data."),
("What is a requests.Session and why reuse it?",
 "Session persists cookies and TCP connections across calls — performance and state (login tokens) for multi-request flows."),
("How do you set timeouts and what are their layers?",
 "timeout=(connect_timeout, read_timeout) — without it, requests can hang forever; the interview answer for 'why did my script stall'."),
("How do you send a file or multipart upload?",
 "requests.post(url, files={'file': ('x.csv', open('x.csv','rb'))}) — multipart/form-data for typical upload APIs."),
("What is a Basic-auth and Bearer-token header?",
 "requests.get(url, auth=('user','pass')) builds Basic; headers={'Authorization': f'Bearer {token}'} for JWT — the API protocol companions."),
("How do you retry requests robustly?",
 "urllib3 Retry with backoff_factor and status_forcelist — the resilient-client pattern (used under LangChain/Agno HTTP tools too)."),
("How do you handle JSON errors in a response?",
 "Checks status then resp.json(); wrap in try/except for spec drift — graceful degradation whenever a third-party API changes shape."),
],
"06-Python-Libraries/04-Python-Testing": [
("What is pytest and how does it differ from unittest?",
 "pytest: function-based tests, plain asserts, fixtures, parametrise, plugins — less boilerplate and richer diagnostics than unittest's class-based style."),
("How do you write a basic test?",
 "def test_add(): assert add(2,3) == 5 — functions named test_* are discovered automatically; failing asserts show diff-friendly output."),
("What is a fixture?",
 "@pytest.fixture yields shared setup/teardown (DB, client, model) with scopes (function/module/session) — dependency injection for tests."),
("What is parametrisation?",
 "@pytest.mark.parametrize('x,y,expected', [(1,1,2),(2,2,4)]) runs the same test over cases — covering edge inputs without duplication."),
("What is mocking and when do you use it?",
 "unittest.mock.patch replaces external calls (HTTP, DB) with controlled fakes — testing logic without network/flakey dependencies."),
("What is the difference between assert, and testing exceptions?",
 "with pytest.raises(ValueError): validates that code raises — the negative-path test habit recruiters love."),
("How do you test a FastAPI/Flask app?",
 "FastAPI: TestClient (httpx) with monkeypatched dependencies; Flask: app.test_client() — both exercise the full request stack."),
("What is the testing pyramid?",
 "Many unit tests (fast, isolated) -> fewer integration tests (real DB/HTTP) -> few end-to-end tests — proportioning coverage cost/confidence."),
("What is code coverage and how do you use it?",
 "pytest --cov=app --cov-report=term-missing shows uncovered branches — a metric, not a goal; 100% isn't the point."),
("How do tests integrate into CI?",
 "GitHub Actions job runs pytest on each PR, failing merges on red — the quality gate wired into your CI/CD pipeline on the resume."),
("What is a golden/snapshot test?",
 "Storing expected output and comparing — great for serialisation/AI outputs where you freeze known-good behaviour."),
],
}