"""Curated Q&A for 01-DSA/08..12 leaves."""
REC = {
"08-Recursion-and-Backtracking/01-Recursion-Fundamentals": [
("What is recursion?",
 "A function solving a problem by calling itself on a smaller instance, combined with a base case that stops the chain. Every recursive problem can be written iteratively with an explicit stack."),
("What are the two mandatory parts of a correct recursive function?",
 "A base case that terminates without recursing, and a recursive case that moves toward the base. Omitting or corrupting the base case causes infinite recursion / stack overflow."),
("Explain the recursion call-stack model.",
 "Each invocation pushes a frame (parameters, locals, return address); the deepest call resolves first and unwinds — the LIFO call stack. Depth is bounded by stack memory."),
("How do you find the factorial / Fibonacci recursively?",
 "fact(n)=n*fact(n-1), fact(0)=1. fib(n)=fib(n-1)+fib(n-2), fib(0)=0, fib(1)=1 — plain recursion is O(2^n); memoisation fixes it."),
("What is the recursion depth limit in Python and how do you raise it?",
 "sys.getrecursionlimit() default ~1000. sys.setrecursionlimit(n) can raise it, but the C stack can still segfault — prefer iteration for very deep recursion."),
("How do you prevent exponential blow-up in recursion (memoisation)?",
 "Cache results per state (dict). Fibonacci becomes O(n) instead of O(2^n). Memoisation is the bridge between recursion and DP."),
("Give real examples of natural recursion.",
 "Tree traversal, quicksort/mergesort, backtracking (permutations, N-Queens), parsing nested expressions, and divide-and-conquer — all fit recursion cleanly."),
("How do you convert an iterative algorithm to recursion and back?",
 "Identify the explicit loop state and the base condition. Recursion: function(state)->call(state+1) duplicate the loop body. Iteration: replace recursion with a stack, pushing each call's parameters."),
("What is tail recursion and why does Python not optimise it?",
 "Tail recursion returns only the recursive call's result with no remaining work. CPython intentionally does not perform tail-call optimisation, so deep tail recursion still overflows."),
("How do you write a recursive power function (fast power)?",
 "pow2(x,n): n==0→1; n even→pow2(x,n//2)^2; n odd→x*pow2(x,n//2)^2. O(log n) — the divide-and-conquer exponential."),
("What is a recursive helper payload pattern?",
 "Wrap the recursion with an outer function holding a shared accumulator/visited set, so the recursive helper can mutate shared state without exposing it."),
("When should you choose recursion over iteration in an interview?",
 "When the structure is naturally recursive (trees, nested) or the state is combinatorial; otherwise iteration avoids stack limits. Defend the choice with complexity and depth constraints."),
],
"08-Recursion-and-Backtracking/02-Permutations-and-Combinations": [
("What is backtracking and its general framework?",
 "Recursively build a candidate incrementally; if the partial candidate is invalid or can't lead to a solution, backtrack (undo last choice). Enumerate all valid configurations."),
("How do you generate all permutations of a string/array?",
 "Swap-based: for each position i, swap with each future j and recurse on i+1, swapping back after — O(n!). Dedupe with a set for repeated characters."),
("How do you generate all subsets (powerset)?",
 "Bitmask for small n (2^n) or recursive pick/skip. Both O(2^n); the recursive one naturally orders lexicographically if choices sorted."),
("How do you generate combinations of size k?",
 "Recur(index, combination): for i from index..n-k+len; add, recur(i+1), remove — prune when the remainder can't fill the size. O(C(n,k))."),
("How do you solve N-Queens with backtracking?",
 "Place a queen per row; validity checks via column and two diagonals (sets/boolean arrays prevents attacks). Backtrack on conflict. O(n!) worst-case but with pruning."),
("How do you solve Sudoku?",
 "Choose an empty cell with smallest candidates (MRV heuristic), try candidate digits, validate row/col/box, recurse; backtrack on dead-ends. Worst-case exponential but pruned heavily."),
("What is the key to deduplicating permutations with repeated elements?",
 "Sort the input and skip reusing the same value at the same position in one level of the loop (e.g., if i>pos and nums[i]==nums[i-1]: continue) — a classic dedupe suffix."),
("How do you find all combinations that sum to a target?",
 "Sort, recur with pick/skip; skip duplicate values at the same level; allow reuse by calling back at the same index for unbounded, and i+1 for 0/1 usage."),
("How do you generate phone-letter combinations?",
 "Digit-character map; depth-first over the digits appending choices; base case when index == len(digits). O(4^n · 3^m) outputs."),
("What is the meeting-point between backtracking and DFS?",
 "Backtracking = DFS over an implicit decision tree with constraint pruning. The tree is not materialised; the recursion conducts the search with state restore."),
("How do you solve 'word search' with backtracking?",
 "For each start cell run DFS in 4 directions building the word, marking the current cell as visited in-situ and restoring after — a board-DFS."),
("How do you solve the 'letter tile possibilities' count?",
 "Count arrangements from a multiset: recur over distinct characters with remaining counts = freq loop; total counts all length permutations. O(unique · 2^n) states."),
("When does backtracking become intolerant of large inputs?",
 "Whenever the search space is exponential in n (permutations/combinations/subset); the problem sets typically cap n ≤ 10-12 for brute-force backtracking."),
("How do you generate parentheses combinations?",
 "Recur(open, close, cur): add '(' if open < n, add ')' if close < open — pruning invalid prefix; base when len==2n. Catalan-bounded output."),
("How do you solve 'combination sum with limited repetitions'?",
 "Cap counts per value with a freq array; extended pick/skip respecting remaining copies — a bounded-unbounded hybrid."),
],
"08-Recursion-and-Backtracking/03-Subsets": [
("How do you generate all subsets recursively?",
 "Pick/Include or skip/exclude each element; results are 2^n. Base case when index reaches n adds the accumulating subset."),
("What is the bitmask method for subsets?",
 "For mask in range(1<<n): elements where bit set are in the subset. Simple, O(n·2^n) to materialise; order is unordered — mention both approaches."),
("How do you generate subsets without duplicates from a multiset?",
 "Sort; use choose-skip with 'skip repeats at the same depth' so equal elements only produce contiguous selections. O(2^n) distinct."),
("How do you find the subset with sum to target (valid subset existence/count)?",
 "DP subset-sum for count/existence in O(n·target); enumerate via backtracking to actually list subsets. Know when to answer count vs list."),
("What is 'subset with given XOR' (count mod)?",
 "DP over cumulative-xor states (2^bits) — a masked-state DP; or linear-algebra Gaussian elimination for exact counting."),
("How do subsets, sequences and subarrays differ in LeetCode terminology?",
 "Subsets: any subset (order irrelevant). Subsequences: preserve order. Subarrays: contiguous. Their counts are 2^n, 2^n, n(n+1)/2 — state the distinction to avoid misanswers."),
("How do you prune subset search for large arrays?",
 "Sort and stop deep recursion when the partial exceeds the bound (e.g., sum>target) or when adding the smallest remaining can't fix — branch-and-bound."),
("How do you find the maximum product subset?",
 "Consider zero/negative handling: product of all non-zero; if negative count odd, divide out the smallest-magnitude negative; empty → 0/1 per rules. O(n)."),
("What is the subset-XOR-of-all-subsets aggregate?",
 "Each element appears in 2^(n-1) subsets; XOR aggregates simplify via parity of appearances — knowing this avoids brutal enumeration."),
("How do you enumerate subsets of a fixed size k?",
 "Recur pick-skip with index bounds so remaining length matches; or bitmask with popcount==k filter. Both fine; recur is cleaner."),
],
"08-Recursion-and-Backtracking/04-Maze-Problems": [
("How do you find a path in a maze with DFS?",
 "DFS from start, moving 4-directional within bounds, marking visited and restoring; on reaching the end, record the path. O(MN) for a single path."),
("How do you count all paths in a maze from (0,0) to (m-1,n-1)?",
 "dp[i][j]=dp[i-1][j]+dp[i][j-1] with obstacles zeroed — the grid-DP formula; BFS-alternative counts work for many obstacles too."),
("How do you find the shortest path in a binary maze?",
 "BFS from start tracking distance; answer is the distance of the end. Obstacles skip; O(MN)."),
("How do you detect a valid staircase/stair in a word maze?",
 "Model as graph traversal with directional constraints — check cell content vs constraints and track visited states. O(MN)."),
("How do rat-in-a-maze variants handle 'can revisit' vs not?",
 "Standard: cells not revisited (visited set). Variants allow revisits → search becomes unbounded and needs constraints (must use DP with state including position only)."),
("How do you solve 'paths with max collect' (maze with black/white)?",
 "DP on a grid collecting rewards with the monotonic property; value at cell accumulates max of predecessors. O(MN) using DP not DFS."),
("How do you handle huge mazes (10^4 cells)?",
 "Iterative BFS/DP avoids recursion overflow; space stays O(MN) for distances but avoid full visited matrix when directions constrain (use distance array)."),
("What do you do when the maze has teleporters / portals?",
 "Each portal adds extra directed edges; BFS/Dijkstra over the augmented graph takes teleports as 0-cost transitions. O(V+E)."),
("How do you solve the 'robot return to origin' style (path verification)?",
 "Only coordinate deltas matter: track x,y accumulating (x+=1 etc.), return True iff both zero. O(n) — not really a graph algorithm."),
("How do you solve the 'unique-path with exactly K steps' (grid)?",
 "DP over steps: dp[steps][r][c] summing predecessor paths; or matrix exponentiation for many steps. O(k·MN)."),
],
"08-Recursion-and-Backtracking/05-Advanced-Backtracking": [
("What counts as advanced backtracking?",
 "Combinatorial enumeration with tight pruning, bitmask states, symmetry-breaking, memoised-tallies, and NP-hard problems solved heuristically (N-Queens > 20, exact cover)."),
("How do you solve 'word squares' with backtracking + trie?",
 "Backtrack placing words; validate each column prefix against a trie; prune when any column prefix has no candidates. O(words·2^L) pruned."),
("What is bitmask-n-queens (positions as bits)?",
 "Cols/diag1/diag2 as integers; candidate positions = free bits; recur for each set bit with updated masks — O(n!) but extremely fast/pruned."),
("What is the exact-cover problem and algorithm X / dancing links?",
 "Exact cover selects rows covering each column exactly once using a DLX structure; the underlying backtracking enumerates feasible row sets."),
("How do you do symmetry-breaking in cutting problems?",
 "Always place a piece in the top-left empty cell (canonical placement) to halve the branching — a key pruning for tiling/rectangle-cutting."),
("How do you solve 'k-partition with equal sums'?",
 "Sort descending, place elements into k buckets via backtracking, prune when a bucket exceeds target or when equal remaining bucket state recurs. O(k^n) with pruning."),
("What is branch-and-bound in backtracking?",
 "Prune a branch when a fast-computed bound shows it can't beat the incumbent — used in TSP and scheduling to avoid exhaustive search."),
("How do you combine backtracking with memoisation (e.g., count of partitions)?",
 "State = (mask, last, ...); cache counts by state; the memoised recursion computes tallies exponentially faster than enumerating."),
("How do you design a correct backtracking skeleton?",
 "Parameters hold partial solution + remaining resources; loop choices; apply choice, recurse, undo; each early exit checks feasibility; base case records the solution. Test a tiny input first."),
("How do you solve 'remove invalid parentheses' with BFS/backtracking?",
 "Generate candidates by deleting one paren at a time (BFS levels) returning the max valid length — or DFS reporting min deletions. O(2^n) worst but prunes fast."),
],
"09-Sorting-and-Searching/01-Sorting-Algorithms": [
("List the comparison-based sorting algorithms and their complexities.",
 "Bubble O(n^2), selection O(n^2), insertion O(n^2), merge O(n log n), quick O(n log n) avg / O(n^2) worst, heap O(n log n). Stable variants differ per algorithm."),
("Explain merge sort.",
 "Divide into halves, recursively sort each, merge two sorted halves with two pointers. O(n log n) time guaranteed, O(n) space for the merge buffer. Stable."),
("Explain quicksort and its partition step.",
 "Pick a pivot; partition so smaller elements precede it and larger follow; recurse on each side. Average O(n log n), worst O(n^2) for bad pivots; in-place but unstable."),
("How does heap sort work?",
 "Build a max-heap, repeatedly swap the max to the end and heapify the shrinking prefix. O(n log n), O(1) extra space, not stable. It uses the heap data structure."),
("Compare merge sort vs quicksort.",
 "Merge: guaranteed O(n log n), stable, needs O(n) space. Quick: in-place, faster constants, unstable, worst O(n^2) — choose by guarantee vs speed requirement."),
("What is counting sort and when is it applicable?",
 "Non-comparison sort over integer keys in range k: counts→prefix→place. O(n+k) time/space; linear only when k is small and keys are integers/naturals."),
("What is radix sort?",
 "Sorts integer keys by digit positions (LSD first) with a stable counting sort per digit. O(d·(n+k)); linear when digits are few."),
("What is bucket sort?",
 "Distributes elements into n buckets, sorts each (usually insertion), concatenates. O(n) average for uniformly distributed keys — used in floating-point and histogram problems."),
("What is Timsort (Python's sort)?",
 "Hybrid of merge+insertion optimised for real data: finds natural runs, merges with galloping; stable, adaptive O(n) on already-sorted data."),
("How do you sort with a custom comparator in Python?",
 "key=lambda x: expr computes a sortable key; for multi-criteria use tuples; for order-reversal negate numerics or use functools.cmp_to_key for comparison semantics."),
("What does stability mean and why does it matter?",
 "Stable sorting preserves the relative order of equal elements — needed when sorting by multiple keys where earlier sorts must not be scrambled (e.g., radix LSD)."),
("How do you sort nearly-sorted arrays efficiently?",
 "Insertion sort is O(n·k) for k-offset arrays; or use a k-size heap for the heap-sort variant. Expected from the interviewer: recognise near-sortedness."),
("How do you detect if a sorted array is a valid non-descending sequence?",
 "One pass checking arr[i] <= arr[i+1] for all i; any violation returns false. O(n)."),
("How do you sort strings by frequency?",
 "Count via Counter, then sort keys by (-count, char); or bucket by frequency. O(n log n) or O(n) with buckets."),
("What is the difference between stable unstable examples?",
 "Stable: bubble, insertion, merge, counting, Timsort. Unstable: quick, heap, selection (with naive swaps). State this — interviewers ask directly."),
],
"09-Sorting-and-Searching/02-Binary-Search-Variants": [
("Explain classic binary search and its complexity.",
 "On a sorted array, repeatedly halve the range comparing mid. O(log n) time, O(1) space — the textbook example of logarithmic search."),
("When can binary search be used beyond arrays?",
 "On any monotonic predicate: answer-space binary search (search on answer), rotated arrays, floating-point search, and 'first/last true' boundaries."),
("How do you find the first and last occurrence of target?",
 "Binary search with equality handling: first occurrence keeps moving right on equal; last moves left on equal — or use bisect_left/bisect_right. O(log n) each."),
("How do you search in a rotated sorted array?",
 "Compare mid with the low pointer to identify the sorted half, check if target lies in it, then walk the half. Handles duplicates with high-- fallback. O(log n) typical."),
("How do you find the rotation point (min element)?",
 "If arr[mid] > arr[high] the pivot is in the right half, else the left — a modified binary search. For duplicates, shrink boundary carefully. O(log n)."),
("What is binary search on answer?",
 "When the answer is numeric and feasible(x) is monotone, binary search the answer space: e.g., kth smallest, minimum max-speed to within deadline. O(log(range)·cost(feas))."),
("How do you find the square root (integer and floating precision)?",
 "Binary search the answer: lo=0, hi=n; while feasible(hi-lo)>eps, mid; ans = greatest m*m<=n. Floating version uses epsilon. O(log n)."),
("How do you find the kth smallest pair distance?",
 "Sort, binary search the distance answer, count pairs with distance <= x via a two-pointer counter — the count is monotonic in x. O(n log MAX)."),
("What is the 'ship within D days', 'koko bananas', 'minimum capacity' family?",
 "Binary search the capacity (answer); check feasibility by greedy simulation; because capacity-monotonic, binary search works — SUPER popular in SP/DSE rounds."),
("How do you search in a 2D sorted matrix (rows and cols sorted)?",
 "Start at top-right; move left if target < cell, down if >. O(n+m). Or treat as flattened sorted if row-major fully sorted — then plain binary search."),
("How do you find a peak in a bitonic array?",
 "Compare mid with mid+1; rising→peak to the right, falling→left. The bitonic-peak binary search = variant of monotone peak in arrays. O(log n)."),
("How do you find the inserted position (lower_bound)?",
 "bisect_left returns the first index where x could be inserted to keep order; bisect_right the last. These are your O(log n) building blocks in Python."),
("How do you handle duplicates correctly in rotated search?",
 "When arr[low]==arr[mid]==arr[high], we can't decide the side; decrement high and continue — worst-case O(n) but averages O(log n)."),
("What are integer-overflow-safe binary search midpoints?",
 "mid = lo + (hi-lo)//2 avoids lo+hi overflow in languages with fixed ints (C++/Java). Python ints don't suffer it, but state the practice anyway."),
("How do you check if binary search replaces a linear scan in interviews?",
 "Whenever the problem asks for min/max/given a bound with a monotonic checker, or sorted arrays, reach for binary search and justify O(log n) over O(n)."),
],
"09-Sorting-and-Searching/03-Search-on-Answer": [
("What is 'search on answer' and when is it used?",
 "Binary-search an integer or float ANSWER because feasibility is monotone; the check runs a separate greedy/count/DP. Time = O(log(hi-lo) · check)."),
("How do you use it for 'minimum time to reach target speed'?",
 "Binary search speed; feasible(s) = total time of segments ≤ limit. margin = speed is monotonic. O(log range · n)."),
("How do you find the 'kth smallest sum of two arrays' via search-on-answer?",
 "Binary search the value x, count pairs with sum ≤ x via two pointers; if count ≥ k the answer is ≤ x. O(n log MAX)."),
("How do you check range-content equality for a binary-searched median?",
 "Counting smaller-than-mid elements across arrays is monotonic; binary search the median value and count — the classic '4th smallest' formulation."),
("When does search-on-answer fail?",
 "When feasibility is not monotone (count crosses 0 then comes back) or when the predicate has plateaus with non-monotonicity; always verify monotonicity first."),
("How do you parallelise the monotone check?",
 "Precompute per-range contributions and binary search with cumulative counting — the check stays O(n) but independent checks are vectorised/hidden-test friendly."),
("What is the precision requirement convention in float search-on-answer?",
 "Run while high-low > 1e-9 or a fixed iterations count (~60 iterations for double range) to avoid infinite loops; guard against last-digit flips."),
("Give a real Infosys-style search-on-answer problem.",
 "'Minimum max time to watch all N movies with M hours per day' or 'dividing an array into k subarrays to minimise max sum' — both use feasible(limit) + binary search."),
("How does 'split array largest sum' fit?",
 "Binary search largest-sum; feasible = can split into k parts each ≤ sum with greedy; answer = smallest feasible bound. O(n log sum)."),
("How do you combine search-on-answer with graph algorithms?",
 "Binary search the answer (edge weight threshold) and check reachability with BFS/DFS under the threshold — common in 'cheapest path within budget'."),
],
"09-Sorting-and-Searching/04-Advanced-Sorting": [
("What is the '3-way quicksort' variant?",
 "Dutch-flag partition splits into <, ==, > pivot groups, recursing only on < and >. Linear for many duplicates — a great optimisation answer."),
("How do you find the kth smallest with quickselect?",
 "Partition like quicksort; recur into the side containing k. Average O(n), worst O(n^2); introselect mixes medians for worst-case guarantee."),
("What is the 'sort permutation with inversions count' phrase?",
 "Counting inversions = number of pairs out of order; solved by merge-sort counting, or Fenwick/order-statistics. O(n log n) is the optimal comparison bound."),
("How do you sort very large files (external sort)?",
 "Split into runs that fit RAM, sort each, then k-way merge with a heap; I/O-bound so block size and buffering matter. The heap-merge is the crux."),
("How does the phrase 'stable sort of tuples by second then first' work?",
 "Sort by the least significant key first, then by the more significant (stable merge/insert) so equal ties preserve the earlier key order — used in radix-land."),
("What is topological 'sorted order' via Kahn when multiple valid orders?",
 "If a specific (e.g., lexicographic) order is needed, replace the plain queue with a min-heap of zeros — 'smallest latinum edges first'."),
("How do you sort a nearly-sorted list in O(n log k)?",
 "k-size min-heap scanning; pop-min into output, push next where i+k in range. O(n log k) with k the max displacement."),
("What is a 'stable bucket/insertion for floats'?",
 "Scale floats via bucket ranges; each bucket sorted by insertion; concatenation preserves global order — the classic float-bucket-sort."),
("How do you implement an in-place merge without sacrificing asymptotics?",
 "Use in-place rotational merges (block merge / timsort's galloping) — the classic boundary-then-inplace trick, or accept the stable O(n) space when simpler."),
("How do you know sorting is the right pre-processing in a problem?",
 "When the problem benefits from adjacency comparisons, two-pointer merging, or binary search — sorting (O(n log n)) unlocks those; always mention the trade-off."),
],
}