"""Curated Q&A for 01-DSA/02-Strings leaves."""
STRINGS = {
"02-Strings/01-Basics-and-Manipulation": [
("Define a string and explain immutability in Python.",
 "A string is an immutable sequence of characters. In Python every operation creating a modified string allocates a new object; in-place edits are impossible. This drives O(n) costs for concatenation in loops."),
("Why is string concatenation in a loop inefficient and how do you fix it?",
 "s += ch rebuilds the whole string each iteration => O(n^2). Fix: collect parts in a list and ''.join(list) once, which is O(total)."),
("Explain the difference between str.replace, split and join with examples.",
 "replace(old,new) substitutes all occurrences; split(sep) returns a list of substrings; sep.join(list) fuses the list back into one string. They are the bread-and-butter of text processing."),
("What are character frequency counts and where are they used?",
 "A dict/array mapping each character to its count; used for anagram checks, first non-repeating char, permutations, and substring problems that care about multiset equality."),
("Write code to reverse a string.",
 "s[::-1] returns a reversed copy. Iterative: build list then join reversed. There is no in-place reverse because strings are immutable (mutable alternative: bytearray)."),
("How do you check whether two strings are anagrams?",
 "Compare sorted(s)==sorted(t) (O(n log n)) or verify equal character frequency counts (O(n)). Both must be used with length-equality precheck."),
("Explain palindrome checking on a string.",
 "Two pointers from both ends comparing characters after lowercasing and skipping non-alphanumerics if the problem allows; return False on first mismatch. O(n) time, O(1) space."),
("What are common string slicing pitfalls?",
 "Negative indices, step semantics, s[:0] being empty, and forgetting that slicing does not mutate. Also, substring searches like s.find are O(n) per call."),
("Explain how to build a frequency map for a string in Python.",
 "collections.Counter(s) builds a multiset in O(n); alternatively dict with get(key,0)+1. Counter supports arithmetic (+, -) which is handy for anagram windows."),
("What is a prefix of a string? Give a use case.",
 "A prefix is any leading contiguous substring (including empty and full). Prefix hashes / trie structures store prefixes to answer prefix queries in O(1)/O(k)."),
("How do you count vowels and consonants in a string?",
 "Iterate characters, check membership in a vowel set, else consonant if alphabetic. Simple O(n). Accounts of case-insensitivity are required."),
("Explain string immutability benefits.",
 "Safety (strings can be dict keys/hashed safely), thread-safety, and cheap sharing of constants; the cost is allocation for every derived value, which CPython mitigates with interning/small-string caches."),
("What is string interning?",
 "CPython interns small constant strings (reserved identifiers/names) so they share one object and can be compared with 'is'. Do not rely on it for logic; use ==."),
("How do you find the first non-repeating character?",
 "Two passes: build Counter, then rescan to return the first char with count 1; else -1. O(n) time, O(26/256) space."),
("Explain str.format vs f-strings.",
 "f-strings are the modern, fastest, and most readable interpolation; .format is older, still supported, useful when the format template must be a variable."),
("How do you pad or truncate strings (center, ljust, zfill)?",
 "Methods: s.zfill(width) pads zeros left, s.ljust/rjust/center pad spaces (or given char); string slicing s[:n] truncates. Used in formatting output widths."),
("What is UTF-8 encoding and why does it matter?",
 "UTF-8 encodes Unicode codepoints into 1–4 bytes and is the dominant web/filesystem encoding; ord()/chr() convert between char and codepoint; len() counts characters, encode('utf-8').__len__ counts bytes."),
("How do you detect if a character is alphanumeric?",
 "str.isalnum() True for letters+digits; isalpha() letters only; isdigit() digits. Used when filtering inputs prior to palindrome/anagram checks."),
("Explain the 'longest common prefix' problem.",
 "Vertical scan char by char across all strings until mismatch, or sort and compare first and last strings. O(S) total characters scanned; O(m+n) with sort where m,n are extrema lengths."),
("How do you check if one string is a rotation of another?",
 "Concatenate s with itself and test whether t is a substring of s+s (lengths must be equal first). Substring search via KMP keeps it O(n)."),
("What is the difference between a character and a byte offset?",
 "In Unicode text, index positions are characters; byte offsets depend on encoding (ASCII=1, others vary). Slicing by character index uses Python's implicit decoding — safe but slower for huge strings."),
("Explain the StringBuilder pattern in Python.",
 "Python lacks StringBuilder; the idiomatic equivalent is ''.join(list_of_parts), or io.StringIO for large streaming builds. Avoid s += in long loops."),
("How do you split a string into words?",
 "s.split() splits on any whitespace and drops empty tokens; s.split(sep) splits on the exact separator. Extract words with regex re.findall(r'\\w+', s) when punctuation must be removed."),
("What is a trie (prefix tree) and why is it suited to strings?",
 "A tree where each node holds one character and children are the next characters. Lookup/insertion is O(L) regardless of the number of strings; great for autocomplete, prefixes, and word-breaking."),
("How would you implement a trie insert and search?",
 "Node = dict of children + is_end flag. Insert: create nodes char by char. Search: walk nodes, check is_end. Prefix walk finds all words with that prefix."),
("How do you check if a string can be formed by repeating a substring?",
 "Key trick: if s = sub^n and len(s)%len(sub)==0, then s appears in s+s skipping the first char. Return whether s in (s+s)[1:-1] — the LeetCode 459 pattern."),
("Explain the sliding-window approach to length-of-longest-substring-without-repeating.",
 "Expand right pointer, add char to a set/dict; while a duplicate exists, shrink left pointer. Track max window. O(n) with two pointers + hash."),
("How do you find all anagrams (permutations) in a string?",
 "Sliding window of length len(p) maintaining a character frequency map; compare with Counter(p) each step using count comparisons — O(|s|) amortised."),
("What is Z-algorithm and what does its array mean?",
 "Z[i] = length of longest substring starting at i that equals the prefix. Computed in O(n); used in pattern search and string-period problems."),
("What is KMP and its failure function?",
 "KMP precomputes the LPS (longest proper prefix that is also suffix) array in O(n); pattern search avoids re-scanning matched characters — O(n+m) total."),
("What is the Rabin-Karp algorithm?",
 "Uses rolling hash to compare substrings' hashes in O(1) after preprocessing; hash collisions are resolved by direct comparison. Average O(n+m), worst O(nm)."),
("What is the shortest palindrome / Mannacher's algorithm context?",
 "Manacher finds the longest palindromic substring in O(n) using center expansion with symmetry mirroring — the standard advanced-string answer for palindrome substrings."),
("How do you capitalise/transform word cases in Python?",
 "s.upper(), s.lower(), s.title(), s.capitalize(), s.swapcase(). Choose based on exact requirement; beware title() capitalising inside acronyms."),
("Explain how to validate a substring is contained in a string.",
 "Use 'needle in haystack'(O(n) substring search via fastsearch), str.find returning index or -1, or KMP when doing many searches on the same needle."),
("What does ord('a') return and how is it useful?",
 "ord('a') returns 97, the ASCII value. Shifting ord(ch)-97 gives 0..25 for 'a'..'z', the classic index into a counting array for lowercase Latin alphabet."),
("How do you count distinct characters in a string?",
 "len(set(s)). Ordered-first-distinct: build a dict (insertion-ordered) and take keys. For 26-lowercase, a 26-bit integer mask is a space-free set."),
("Explain the 'defanging / replacing' style sanitisation questions.",
 "Systematic substitutions with .replace() or regex aim to neutralise input (IPs, URLs). The interview intent is string manipulation + edge handling, not security theory."),
("How do you sort characters of a string by frequency?",
 "Counter(s).most_common() then expand; if equal frequencies, order by char (sort by (-freq, char)). O(n log n)."),
("What is the lexicographical comparison rule in Python?",
 "First differing character decides; if all equal, shorter precedes longer. Tuples/lists compare the same way, which helps in sorting composite keys."),
("How do you encode/decode URL components?",
 "urllib.parse.quote/unquote percent-encode reserved characters; ensures data survives transport. Encoding/decoding mismatches are a classic bug source."),
("Explain 'string to integer (atoi)' implementation steps.",
 "Skip whitespace, read optional sign, accumulate digits with overflow clamping; stop at first non-digit. Follow the exact spec of the problem (LeetCode 8)."),
("What are raw strings and f-strings escaping rules?",
 "r'...' keeps backslashes literal (regexes, paths). f'...' interpolates expression results; braces are escaped by doubling. Mixing both is invalid — decided by the r prefix type."),
("How do you find the longest palindromic substring (centre expansion)?",
 "For each centre (n odd + n-1 even centres), expand while chars match; track the longest. O(n^2) time, O(1) space; Manacher does O(n)."),
],
"02-Strings/02-Pattern-Matching": [
("What is string pattern matching and when do naive checks fail?",
 "Finding a pattern P in text T. Naive tries P at every position costing O(n*m); it degrades badly on repetitive text. Advanced algorithms (KMP/Rabin-Karp/Z) run O(n+m)."),
("Explain the KMP failure function conceptually.",
 "lps[i] = length of the longest proper prefix of P[0..i] that is also a suffix. On mismatch, instead of restarting, the algorithm resumes from lps[prev] — each char is processed O(1)."),
("State KMP time and space complexity.",
 "O(n+m) time and O(m) space for the lps array; it is the canonical optimal single-pattern matcher."),
("Explain Rabin-Karp rolling hash and collision handling.",
 "Hash a window using base + modulo; slide by removing outbound char and adding inbound. On hash match, verify with direct compare to guard collisions; average O(n+m)."),
("What is Z-array and how is it computed in linear time?",
 "Z[i] is the longest substring starting at i matching the prefix. Maintain [L,R] box; reuse internal comparisons. Compose as P+'#'+T, pattern found where Z[i] == len(P)."),
("When would you prefer Boyer-Moore in a real system?",
 "Boyer-Moore skips ahead using bad-character and good-suffix heuristics, excelling on large alphabets and long text; used in grep-like search engines for patterns."),
("How do you implement wildcard matching (* and ?)?",
 "DP over (i,j): '?' matches one char, '*' matches empty or any sequence (dp[i][j]=dp[i-1][j] or dp[i][j-1]). Greedy two-pointer version also exists. O(n*m) time."),
("How do you implement regular expression matching supporting '.' and '*'?",
 "DP with states (i,j): '.' matches any char; 'x*' can match zero (dp[i][j-2]) or more copies. O(n*m). This exact problem frequently enters SP/DSE coding tests."),
("How do you find all occurrences of a pattern?",
 "Run KMP and record every index where j == m (then j=lps[j-1] to allow overlaps). Rabin-Karp records hash matches after verification."),
("Explain string hashing and why collisions matter.",
 "Hash text windows to compare prefix equality in O(1); collisions make the algorithm incorrect unless verified, so use double hashes or check equality directly."),
("How would you count distinct substrings of a string?",
 "Suffix array + LCP: total = n(n+1)/2 - sum(LCP). Or a trie of all suffixes. O(n^2) worst on trie; suffix-array sort gives O(n log n)."),
("What is the suffix automaton and its advantage?",
 "A minimal DFA accepting all substrings of a string. Built in O(n) with 2n states; answers substring-presence and occurrences in O(1)/O(occ)."),
],
"02-Strings/03-Dynamic-Programming-on-Strings": [
("Overview of DP on strings and standard state design.",
 "State is typically (i,j) = position in string A and string B. Transitions come from char match/mismatch, gap, or replace choices — forming LCS, edit-distance, palindromes and interleaving problems."),
("How is Longest Common Subsequence defined and solved?",
 "LCS keeps order without adjacency. Recurrence: if a[i]==b[j]: dp[i][j]=dp[i-1][j-1]+1 else max of dp[i-1][j], dp[i][j-1]. O(n*m) DP; reconstruct by backtracking."),
("Explain edit distance (Levenshtein).",
 "Min ops (insert/delete/replace) to turn a into b. dp[i][j]=min(insert, delete, replace). If chars equal, carry dp[i-1][j-1]. O(n*m)."),
("How do you find the longest palindromic subsequence?",
 "LCS of s with reversed(s), or DP palindrome recurrence: if s[i]==s[j]: dp[i][j]=dp[i+1][j-1]+2 else max(dp[i+1][j],dp[i][j-1]). Fill by increasing length."),
("How do you find the minimum insertions to make a string a palindrome?",
 "Insertions needed = len(s) - longest_palindromic_subsequence(s). The complement of already-matching characters is what must be added symmetrically."),
("How do you check if a string is an interleaving of two others?",
 "dp[i][j] True if s3[0:i+j] is an interleaving of s1[0:i] and s2[0:j]; transitions consume from s1 or s2 when chars match s3. O(n*m)."),
("What is a substring edit-distance variant (segment change)?",
 "Common variants restrict operations (e.g., only delete), early-exit when distance>k, or ask for distinct edits — adapt states accordingly and add pruning."),
("How do you compute edit distance with O(m) space?",
 "Roll dp arrays: only two rows are needed because transitions reference i-1 row only. From row to row, keep prev and current. O(n*m) time, O(m) space."),
("How does the 'delete operation for two strings' problem work?",
 "Min deletions to make s and t equal = n + m - 2*LCS(s,t). Only delete operations allowed means unchanged parts are exactly the common subsequence."),
("How do you find the longest common substring?",
 "DP where dp[i][j]=dp[i-1][j-1]+1 only when chars match (reset on mismatch). Keep global max. O(n*m) time; suffix array gives O(n log n)."),
("How do you build all distinct LCS (or DP backtracking) answers?",
 "Backtrack through equal-value transitions collecting paths; dedupe with a set. Exponential worst-case output, so report count or all with memoised sets."),
("What is the shortest common supersequence problem?",
 "SCS(a,b) length = n+m-LCS(a,b). Reconstruction merges a and b avoiding duplicate overlap of the LCS portion. Classic interview follow-up to LCS."),
("How do you solve 'longest repeating subsequence'?",
 "LCS with i!=j constraint: apply LCS recurrence but only carry dp[i-1][j-1]+1 when a[i]==b[j] and i!=j (same string). O(n^2)."),
("How do you count distinct palindromic substrings (Manacher-based DP)?",
 "Count centres O(n) with Manacher's radius array; total distinct substrings via set of all palindromes found in O(n) radius scan."),
("Explain memoisation vs tabulation on string DP problems.",
 "Memoisation (top-down recursion + cache) is intuitive and skips unreachable states; tabulation (bottom-up loops) is iterative and faster. Both give identical answers; choose by clarity in interviews."),
("How do you handle large strings in DP without timeouts?",
 "Use O(1)-space row compaction, prune unreachable states, early-exit when result threshold reached, and avoid slicing strings inside loops (index instead)."),
],
"02-Strings/04-Anagrams-and-Permutations": [
("Define anagram and the two standard detection techniques.",
 "Anagrams have identical character multisets: same length and same frequency map. Techniques: sorted equality or Counter equality — both O(n) after prechecks."),
("Group a list of strings into anagram groups.",
 "Map key = tuple(sorted(s)) or a 26-count tuple (O(26n)) to the group list. Return grouping. O(n*26) with count-key avoids sorting."),
("How do you find all anagram-start indices of p in s?",
 "Sliding window of length len(p) with a running frequency map; compare against target Counter with equality of lengths of non-zero entries or full equality. O(|s|)."),
("Explain permutations of a string via recursion/backtracking.",
 "Swap-based: fix each position, recurse on remainder; or pick/remove approach. Complexity O(n!) worst, dedupe with set when characters repeat."),
("How do you generate the NEXT lexicographic permutation of a string?",
 "Find the longest decreasing suffix, pivot before it; swap pivot with the smallest greater character in the suffix; reverse the suffix. That is std::next_permutation logic, O(n)."),
("What is the kth permutation problem?",
 "Build factorial number system: for position i, group size = factorial of remaining; pick block = k//group, set k%=group. Skip used chars. O(n^2) with list removal."),
("How do you check if one word can be formed by letters of another?",
 "Ensure requirement chars are a sub-multiset: for every char, need[ch] <= have[ch]. Counter supports Counter(a)<=Counter(b)."),
("How do you find the minimum window substring for a target multiset?",
 "Sliding window tracking required vs found counts; expand to satisfy, then shrink to minimise length. O(n) with two pointers; classic 'minimum window substring'."),
("Explain word pattern / isomorphic strings checks.",
 "Both map characters/words consistently: build dicts for bijection and check both directions to avoid two keys mapping to one value. O(n)."),
("How do you check if two strings are anagrams ignoring case/spaces?",
 "Filter to alnum, lower both, compare Counters. Separating preprocessing from comparison makes the intention explicit."),
("How do you count distinct permutations with repeated characters?",
 "Permutations = n! / (product of factorials of each character count). Demonstrates combinatorial reasoning with multiplicities."),
("How do you check permutation existence larger than given string?",
 "Easiest: sort all candidates and compare; or sliding-window multiset equality plus greedy for lexicographic order. Clarify which criterion with the interviewer."),
("What is a valid-anagram-as-palindrome condition?",
 "A string can be rearranged into a palindrome iff at most one character has an odd count. From that test derive suitability for palindrome permutations."),
("How do you find all unlocked-and-mutual anagram words (word squares)?",
 "This is a backtracking + prefix check problem: build a trie of prefixes; place words row by row ensuring column prefixes exist — as in 'Word Squares'."),
],
"02-Strings/05-Substring-Problems": [
("What is a substring and how is it distinguished from subsequence?",
 "Substring is contiguous; subsequence can skip. Substring enumeration is O(n^2) pairs; substrings = n(n+1)/2."),
("Write the sliding-window maximum problem (max of each k window).",
 "Deque of indices maintaining decreasing values; pop smaller than incoming, and expired from the front. O(n) amortised."),
("How do you find the longest substring with at most k distinct characters?",
 "Sliding window with dict of counts; shrink while distinct>k; track max length. O(n) time."),
("How do you find the longest substring with two unique characters (fruit problem)?",
 "Same as atMost(2) distinct; a dict tracks counts and a left pointer shrinks until only two distinct remain. O(n)."),
("How do you find 'minimum window substring' covering every letter of T?",
 "Two-pointer window; when all required chars satisfied, shrink left to minimise; record each feasible window. O(n)."),
("How do you find the concatenation-of-words substring problem?",
 "Group words into a freq map; slide in word-sized steps, counting window word frequencies over O(n*step). Track valid starts."),
("Explain how to find the longest substring of balanced parentheses (or valid brackets).",
 "Stack-based valid-parentheses scan tracking start index; or DP marking balanced chunks. Cumulative length of maximal balanced region = answer."),
("How do you find all substrings that are palindromes efficiently?",
 "Centre expansion from n odd + n-1 even centres with expansion while equal. For all distinct ones, add to a set. O(n^2) worst."),
("How do you find repeating substrings / longest repeated substring?",
 "Binary search length + rolling hash to detect repeats, or suffix array+LCP. O(n log n) with hash; the suffix approach is exact."),
("How do you split a string into substrings of equal balanced count?",
 "Greedily cut at each point where running balance returns to zero (balanced parentheses). Count the segments — each cut preserves validity."),
],
}