"""Curated Q&A for 05-System-Design."""
SYS = {
"01-Fundamentals/01-Scalability-Basics": [
("What is scalability?",
 "A system's ability to handle growth — more users, data, and traffic — without redesign; split into vertical (bigger machine) and horizontal (more machines) scaling."),
("What is vertical vs horizontal scaling?",
 "Vertical: add CPU/RAM to one server (simple, single point of failure, hard cap). Horizontal: add more servers behind a load balancer (complex but elastic and fault-tolerant)."),
("What is the difference between scaling up and scaling out in practice?",
 "Up: hardware upgrade; Out: replicas/shards. Modern cloud apps scale out with stateless services and state pushed to managed stores."),
("What is a bottleneck in a system?",
 "The component capping throughput — the DB write path, a single queue, or shared lock; profiling identifies it; caching/indexing/partitioning relieve it."),
("What is the difference between throughput and latency?",
 "Throughput: requests/second the system sustains. Latency: time for one request round-trip. They trade off (more parallel work often raises per-request tail latency)."),
("What is a load test and why does it matter?",
 "Simulating realistic traffic to find the saturation point — capacity planning and performance regression detection before users find them."),
("What is the CAP theorem's relevance?",
 "In a distributed store, partition tolerance is forced — you choose consistency or availability per partition; most systems pick available+eventually-consistent (or strong-consistent DBs)."),
("What is idle application health — the 503/error budget?",
 "Error budget = acceptable failure time from SLOs (e.g., 99.9% = ~43min/month); the ops discipline of engineering reliability consciously."),
("What is a serverless vs containerised deployment?",
 "Serverless: managed scale-to-zero, billed per invocation — great for spiky event loads. Containers: you control instances — predictable steady-state workloads."),
("How would you make a monolithic API scale?",
 "Stateless replicas behind a load balancer, caching reads, DB read replicas, queues for heavy side-effects — the classic first-scale-out move."),
],
"01-Fundamentals/02-Load-Balancing": [
("What is load balancing?",
 "Distributing incoming requests across multiple backend instances; improves availability and throughput and is the backbone of horizontal scaling."),
("What are the load-balancing algorithms?",
 "Round-robin (even distribution), least-connections (busy-aware), weighted (capacity-aware), IP/consistent-hash (sticky) — pick by workload shape."),
("What is a layer-4 vs layer-7 load balancer?",
 "L4 balances on IP/port (fast, opaque); L7 inspects HTTP (routing, headers, sticky sessions, TLS termination) — L7 powers modern APIs."),
("What is a health check in load balancing?",
 "Periodic probes (TCP/HTTP) to mark instances up/down — the LB only routes to healthy nodes, enabling rolling deploys."),
("What is session affinity / sticky sessions?",
 "Pinning a user to one instance via cookie/hash — avoids re-login but couples to instance state; stateless sessions (external store) remove the need."),
("What is a reverse proxy vs load balancer?",
 "A reverse proxy fronts backends for one app (nginx: TLS, caching, routing); an LB distributes across many — often the same server does both."),
("What is consistent hashing and its role?",
 "A hash ring assigning keys to nodes so adding/removing a node only remaps a fraction of keys — essential for cache shards and hash-key affinity."),
("What happens when a backend dies mid-request?",
 "Retries on another healthy instance with timeout + idempotency keys — the resilience requirement of distributed request handling."),
("What is a global (DNS/geo) load balancer?",
 "Routing users to the nearest region's LB via DNS policies (latency/geo-based) — cutting cross-region latency for global apps."),
("How do you test a load-balancer setup?",
 "Synthetic load through the LB, health-check flapping tests, and rolling instance kills — verifying re-routing and failover behave under adversity."),
],
"01-Fundamentals/03-Caching": [
("What is caching?",
 "Storing frequently-read results closer to the request — in-memory, CDN, or at the DB — to cut latency and reduce downstream load."),
("What is caching at which layers of a web app?",
 "Browser caching (HTTP headers), CDN (static), app/in-memory (Redis/memcached for hot reads), DB query cache — each layer offloads the next."),
("What is a cache-aside (lazy) pattern?",
 "Read: check cache, on miss load from DB and populate. Write: update DB, invalidate the cache. Simple and eventually consistent — the most common pattern."),
("What is write-through vs write-back caching?",
 "Write-through: every write goes to cache then DB (stronger consistency, higher latency). Write-back: accumulate writes and flush (fast, risk of loss on crash)."),
("What is cache invalidation and the classic problems?",
 "Stale reads after DB updates — solved by TTL, explicit invalidation, or versioned keys; invalidation bugs cause the meanest production bugs."),
("What is a TTL and why set it?",
 "Time-to-live expires entries automatically — bounding staleness; choose per data volatility (config: minutes, user profile: hours, posts: seconds)."),
("What is a cache stampede (thundering herd)?",
 "A hot key expires and N requests all hit the DB — mitigated by locks/single-flight, stale-while-revalidate, or probabilistic expiry."),
("What is an LRU cache?",
 "Least-Recently-Used eviction: remove the oldest entry when capacity is exhausted — the standard in-memory eviction policy (Redis/LRU, your C++ LRU)."),
("What is Redis and its use as a cache?",
 "A fast in-memory data store (strings/hashes/ttl) shared across instances — the backbone cache/queue/session store for scaled apps."),
("What is the local vs distributed cache trade-off?",
 "Local: zero network, per-instance duplication. Distributed (Redis): shared, consistent, one more failure domain — pick by scale and consistency needs."),
("What do you cache in an AI API product?",
 "Prompt/system prefixes, retrieved chunks, and generated response hashes — massive latency/cost savings in RAG and LLM products."),
],
"01-Fundamentals/04-Microservices-vs-Monolith": [
("What is a monolith?",
 "One deployable containing all features — simple to build/debug/start, but it scales as one unit and couples teams' releases."),
("What is microservices?",
 "Independent services, each owning its data, communicating over HTTP/messages, deployed separately — scalable, fault-isolated, and team-aligned."),
("What are the trade-offs of microservices?",
 "Pros: independent scaling/deploys, organisational alignment, tech freedom. Cons: distributed debugging, network latency, data consistency, ops complexity."),
("What are the patterns for microservices communication?",
 "Synchronous REST/gRPC for request-response; async message queues/events (Kafka) for decoupling; each has consistency and failure semantics."),
("What is the database per service principle?",
 "Each service owns its schema — no shared DB access, preserving autonomy; cross-service reads use APIs/events/eventual consistency."),
("What is an API gateway's role?",
 "Single entry: routing, auth, rate limiting, and aggregation for a family of services — the facade of the microservice mesh."),
("What is service discovery?",
 "Dynamic location of service instances via registries (Consul/etcd/cloud DNS) since IPs change with auto-scaling — the glue of distributed calls."),
("What is the difference between orchestration and choreography?",
 "Orchestration: a central coordinator drives steps (simple, single point of failure). Choreography: services react to events independently (decoupled, harder to trace)."),
("How do you decompose a monolith?",
 "Start from boundaries: bounded-context seams (order vs inventory), extract the most-failed/hottest service first, and use the strangler pattern to incrementally replace."),
("What is observability across services?",
 "Distributed tracing (trace IDs across hops), structured logs, and metrics — joining a request across services; without it microservices are unoperable."),
("When would you keep a monolith?",
 "Small team, small company, exploratory stage, or strong domain cohesion — microservices' benefits only pay off past a scaling/org threshold."),
],
"02-API-Design/01-REST-APIs": [
("What is REST?",
 "Representational State Transfer: an architectural style using HTTP verbs over resources — stateless, cacheable, standardised; each URL names a resource."),
("What are the core REST principles?",
 "Resource-based URLs (nouns, plural), HTTP methods mapping to verbs (GET/POST/PUT/PATCH/DELETE), statelessness, and standard status codes."),
("What is the difference between POST and PUT?",
 "POST creates (or triggers an action) non-idempotently; PUT replaces a known resource idempotently — the correctness of retries hinges on this."),
("What makes an API RESTful vs just HTTP?",
 "RESTful: resources, uniform interface, HATEOAS optionally, cacheability, statelessness — HTTP endpoints alone aren't necessarily REST."),
("What is idempotency and why does it matter?",
 "Repeating an operation yields the same result — PUT/DELETE and POST-with-idempotency-key enable safe client retries on network failures."),
("What is pagination in REST?",
 "limit/offset or cursor-based tokens keep list endpoints bounded — plus total counts and next-page links for UX."),
("What is the REST API error envelope?",
 "A consistent JSON error shape ({error: {code, message, details}}) with the right HTTP status — making errors parseable by clients."),
("What is HATEOAS?",
 "Hypermedia as the engine of application state — responses link to related actions; rarely implemented but historically core-rest."),
("What is a REST resource design for /items/{id}/reviews?",
 "Nested sub-resources for one-to-many: reviews of an item; each is addressable, CRUD-able, and cachable — the usual nesting guideline."),
("What is OpenAPI (Swagger)?",
 "A standard JSON/YAML contract describing endpoints, schemas, and responses — auto-generating clients, docs, and validation; FastAPI emits it for free."),
("How do you version a REST API?",
 "URL paths (/v1/items) or Accept headers; keep old versions served during deprecation — the compatibility contract with consumers."),
("What is gRPC vs REST?",
 "gRPC: binary protobuf over HTTP/2 with generated stubs — fast, typed, streaming; REST over JSON: universal and debuggable — pick inner-service vs public API."),
],
"02-API-Design/02-GraphQL": [
("What is GraphQL?",
 "A query language where clients request exactly the fields they need in one round trip — a single endpoint with a typed schema."),
("What is the core difference between REST and GraphQL?",
 "REST: resources + server-defined shapes + multiple round trips. GraphQL: client-defined query shapes + one endpoint + a schema enforced by the server."),
("What is a query vs a mutation in GraphQL?",
 "query reads data (parallelisable, cacheable); mutation writes (executed serially) — the read/write separation of the schema."),
("What is a resolver?",
 "The function resolving each field — retrieving/transforming data; GraphQL composes a tree of resolvers per query."),
("What is the N+1 problem in GraphQL?",
 "A list query triggers a resolver per item hitting the DB N+1 times — solved with Dataloader batching/batching per field."),
("What is schema-driven development?",
 "The schema is the contract defined first; clients and servers type-generate from it — the collaboration pattern teams adopt."),
("What are the trade-offs of GraphQL vs REST?",
 "GraphQL: precise payloads, fewer round trips, but complex caching, DoS via nested queries, and a harder learning curve — REST simpler and cacheable."),
("What is a GraphQL subscription?",
 "A subscription is a persistent stream of updates (over WebSocket) — real-time push as opposed to query/mutation's request-response."),
("How do you protect a GraphQL API?",
 "Query-depth and complexity limits (cost analysis), persisted-queries allowlists, and rate limiting — preventing deeply-nested abusive queries."),
("When would you choose GraphQL?",
 "Dashboards/mobile apps with differing field needs, many clients — but avoid it if caching/simplicity or a broad REST ecosystem dominates your use case."),
],
"02-API-Design/03-API-Versioning": [
("What is API versioning and why is it needed?",
 "Changing the contract without breaking existing clients — consumers upgrade at their own pace, not when you redeploy."),
("What are the main versioning strategies?",
 "URI versioning (/v1/users), query param (?v=1), custom header (X-API-Version), content negotiation (Accept: application/vnd.x.v1+json)."),
("What are the trade-offs of URI vs header versioning?",
 "URI: explicit, cacheable, universal support, but pollutes URLs. Header: cleaner URLs but invisible in logs and caches — choose by who consumes it."),
("What is the difference between major and minor version changes?",
 "Major: breaking (field removal, behaviour change) — new version with migration path. Minor: additive (new fields, endpoints) — backwards compatible."),
("What is the deprecation lifecycle?",
 "Announce -> mark Deprecated headers/Sunset -> serve both -> migrate users -> remove old version — with documented removals dates."),
("What is default-versioning risk?",
 "Routing to a 'latest' version silently re-binds clients to future behaviour on deploy — pinning explicit versions avoids breakage surprises."),
("How do you keep old versions alive cheaply?",
 "Version-specific route modules/blueprints, shared schemas where stable, and regression tests against the old contract — CI guards the transition."),
("What does versioning mean for internal vs public APIs?",
 "Internal: aggressive change with coordinated deploys. Public: strict compatibility windows and long deprecation periods — trust capital."),
("What is an API changelog?",
 "A documented list of what changed per version — clients plan upgrades; publishing one is the professional touch interviewers notice."),
("How does GraphQL do versioning instead?",
 "Evolving schemas with deprecation directives rather than versioned endpoints — a philosophical advantage of schema-first contracts."),
],
"02-API-Design/04-API-Security": [
("What are the security layers of an API?",
 "Transport (TLS), authentication (who), authorisation (what they may do), rate limiting (abuse), input validation, and logging/monitoring."),
("What is authentication vs authorisation?",
 "Authentication proves identity (JWT, API keys, OAuth). Authorisation decides permissions (roles/scopes) — the authN/authZ distinction is a classic interview question."),
("What is OAuth2 and its flows?",
 "An authorisation framework — authorization-code for user apps, client-credentials for server-to-server, password for first-party — issuing scoped tokens."),
("What is different about a JWT (structure)?",
 "Header.payload.signature (base64url + HMAC/RSA signature) — stateless verification once you trust the issuing key and check exp/aud/iss."),
("What is an API key vs a JWT?",
 "API key: static secret for machine clients (revocable, simple). JWT: self-contained claims, exp, scopes — dynamic and standardised."),
("What is rate limiting and the common algorithms?",
 "Token bucket, fixed/rolling window, sliding log/counter — usually Redis-backed, per key/IP/user; protects against bursts and abuse."),
("What is input validation preventing?",
 "Injection (SQL/XSS/command), malformed payloads, and schema attacks — Pydantic/validation layers plus ORM param binding handle most."),
("What is the least-privilege principle in APIs?",
 "Each token/role gets the minimum scopes needed; scopes are checked per endpoint, not globally — damage is bounded when a token leaks."),
("What is a security header set for APIs?",
 "CORS restrictions, Content-Security-Policy (when serving HTML), and HTTPS-only + HSTS — hardening beyond the request itself."),
("What is an audit log and where do you log?",
 "Authenticated actions with user, action, IP, and result — the evidence trail for breaches and the compliance requirement for enterprise APIs."),
("What are OWASP API risks you'd list?",
 "Broken object-level auth, excessive data exposure, and injection remain the top three — name them first, mitigation second."),
],
"03-System-Design-Problems/01-URL-Shortener": [
("Design a URL shortener — core requirements?",
 "Shorten (long URL -> tiny slug), redirect (tiny -> long), high throughput/read-heavy, and collision-free. Capacity tuning: ~100x more reads than writes."),
("How do you generate the short code?",
 "Base62-encode a monotonically increasing ID (or hash with collision check) to a 6-8 char slug — choose base62/Counter over random for no collisions."),
("What is the write path?",
 "Client POST long URL -> generate slug -> store (id, slug, long_url, created_at) -> return short link; DB keyed by slug."),
("What is the read path and why is it cached?",
 "GET slug -> cache lookup (Redis) -> DB on miss -> 301/302 redirect to long_url; ~80% cache hit cuts DB traffic massively."),
("What database would you choose?",
 "Relational (PostgreSQL/MySQL) for transactional writes + unique indexes, or a KV store — the read-heavy profile favours an in-memory cache in front."),
("What is a 301 vs 302 redirect for a shortener?",
 "301 is permanently cached by browsers (harder to change); 302 transient — analytics-driven shorteners pick 302 so every click counts."),
("How do you scale reads and writes?",
 "Stateless app replicas behind an LB, read replicas/cache for reads, and DB sharding by slug hash if writes grow — the horizontal scaling playbook."),
("What about custom aliases and expiry?",
 "Optional user-provided slug (collision check) and TTL cleanup via scheduled scans or lazy deletion on access."),
("How do you monitor such a system?",
 "Redirect latency, cache hit rate, error rate, and click analytics per link — the observability surface for a read-heavy API."),
("What are edge cases?",
 "Very long URLs, reserved slugs, expired links, and abuse (spam URLs) — design decisions announced in the interview, redeemed in ops."),
],
"03-System-Design-Problems/02-Rate-Limiter": [
("Design a rate limiter — what does it enforce?",
 "Max requests per unit time per client (e.g., 100/min per API key) — protecting the service from abuse and runaway clients."),
("What are the classic algorithms?",
 "Token bucket, fixed window, sliding window log, and sliding window counter — each trades memory, accuracy, and burst tolerance."),
("Explain token bucket.",
 "A bucket of tokens refilled at rate r, capacity b; a request consumes one token or is rejected — allows bounded bursts, simple, and the most common (used by APIs)."),
("What are the pros/cons of a fixed window?",
 "Simple counters per window — but the boundary spike: a client doubles its quota by straddling window edges."),
("What is a sliding window counter?",
 "Weighting the current and previous windows by overlap — accurate near sliding-window with counter-only memory; the modern hybrid choice."),
("Where does the limiter live?",
 "Client (weak), API gateway/server (request path), or a shared Redis layer (consistent across instances) — distributed enforcement needs a shared store."),
("What happens to rejected requests?",
 "HTTP 429 with Retry-After header — clients back off instead of thundering again; distinguish from a client error by status codes."),
("What is per-user vs global limiting?",
 "Per-key/tenant limits plus global caps protect against one tenant exhausting shared capacity — layered policy, not one rule."),
("How do key expiry and memory work at scale?",
 "Redis hashes keyed by user+window with TTL; memory bound by active clients — a realistic cost model for millions of keys."),
("How do you test a rate limiter?",
 "Burst, boundary-window, and distributed-consistency tests — under exact limits and overshoot, verifying the 429 path and retry semantics."),
],
"03-System-Design-Problems/03-Notification-System": [
("Design a notification system — the core requirements?",
 "Send notifications to users via push, email, SMS; high volume, low latency, retries, and per-channel failure tolerance."),
("What is the architecture?",
 "Producer services emit events -> message queue -> notification workers dispatch -> channel adapters (APNS/FCM/SMTP/SNS) with retry/dead-letter queues."),
("Why is a message queue central?",
 "It buffers bursts, decouples production from delivery, and enables retries — spikes (campaign time) don't crash receivers."),
("How do you deduplicate notifications?",
 "Idempotency keys per notification (unique event ID) and a short dedup window in Redis — preventing double-sends on worker retries."),
("How do you handle per-channel failures?",
 "Per-channel retry with backoff, dead-letter queues for poison messages, and channel-priority fallbacks — the resilience layer of delivery."),
("What is fan-out and how do you avoid n+1 sends?",
 "Batching, template rendering once, and aggregating duplicates per user — sending 1M campaign emails needs producer batching, not 1M individual tasks."),
("What are push vs pull notifications?",
 "Push reaches the device via provider (FCM/APNs, needs device token, real-time); pull (fetch) is app-initiated — push preferred for alerts, pull for sync."),
("How do you store notification history?",
 "A notifications table (user_id, type, status, created_at) plus an in-app feed service — history, retries, and analytics share the store."),
("How do you ensure ordering?",
 "Most systems accept best-effort ordering; strict ordering needs per-user sequence numbers and per-key queues — a deliberate semantics trade."),
("How do you monitor delivery?",
 "Per-channel success/error rates, queue depth, latency percentiles, and undeliverable-token hygiene (FCM feedback) — delivery SLOs."),
],
"03-System-Design-Problems/04-Chat-System": [
("Design a chat system — the core features?",
 "One-to-one and group messaging, message persistence, delivery order, presence, and online/offline synchronisation — over WebSockets."),
("What is the transport for real-time messages?",
 "WebSockets for bidirectional push; REST for history/records; the connection is long-lived via load-balanced gateway endpoints."),
("How do you store messages?",
 "A messages table keyed by conversation_id with (sender, ts, content, status); Power-of-2-style chat isn't needed here — timestamp-ordering IDs are."),
("How do you order messages correctly?",
 "Server-assigned sequence numbers (or snowflake-style IDs) per conversation, applied at the server, not the client clock — network clocks lie."),
("What happens to delivery when a user is offline?",
 "Outbox/queue per user; on reconnect, sync missing messages since last_seq — the pull-on-reconnect pattern preserves ordering and durability."),
("What is the read receipt / delivered model?",
 "Delivery = pushed to gateway; read = user opened the conversation; both are separate status transitions recorded and broadcast."),
("How do you scale WebSocket connections?",
 "Stateless WebSocket gateways behind an LB (connection-sticky), presence tracked in Redis — rooms shard across gateways with pub/sub broadcasting."),
("What is a pub/sub for chat rooms?",
 "Redis pub/sub or Kafka per conversation fan-out: server sees one publish, sends to all connected members of that room — the broadcast primitive."),
("What are the consistency vs availability trade-offs?",
 "Online senders see others' messages via optimistic UI; offline sync reconciles — eventual consistency in ordering is acceptable and standard."),
("How do you test a chat system?",
 "Concurrent-message ordering, reconnection replay, and large-room fan-out load tests — plus presence flapping under network churn."),
],
"04-Design-Patterns/01-Creational": [
("What are creational design patterns?",
 "Patterns controlling object creation — decoupling instantiation from the code that uses objects: Singleton, Factory, Abstract Factory, Builder, Prototype."),
("What is a Singleton?",
 "Ensures one instance of a class globally (via __new__ in Python or a module-level object) — the config/cache connection pattern, but thread-safety and testability are its cost."),
("What is a Factory method?",
 "A method or class creating objects of a family without exposing construction logic — callers get an interface, internals choose the concrete class."),
("What is the difference between Factory and Abstract Factory?",
 "Factory: one product family via a method. Abstract Factory: a family of related factories creating related products — one level more abstraction."),
("What is a Builder pattern?",
 "Step-wise construction of complex objects (chained .with_xxx() in Python) — separating assembly from representation; useful for complex config objects."),
("What is a Prototype pattern?",
 "Creating new objects by cloning a template (copy.deepcopy) instead of rebuilding — expensive init avoided; the copying idiom in Python."),
("What is the trade-off of returning Singletons in web apps?",
 "Shared state across requests is a bug source — use dependency-injected modules instead; the design conversation is about lifecycle."),
("How do creational patterns show up in FastAPI?",
 "Dependency injection and Depends() factories are construction decoupling by the framework — your endpoints receive built collaborators instead of creating them."),
("What is the trade-off between patterns and simplicity today?",
 "Python idioms (module singletons, dataclasses as builders) often replace explicit GoF scaffolding — know the intent, not just the UML."),
("What is lazy instantiation?",
 "Creating the object on first use rather than at startup — saving cost when it's rarely used (a classic singleton variant)."),
],
"04-Design-Patterns/02-Structural": [
("What are structural design patterns?",
 "Patterns composing objects and classes into larger structures while keeping them flexible: Adapter, Decorator, Facade, Proxy, Composite."),
("What is an Adapter?",
 "Wrapping an incompatible interface into one the client expects — the 'translate' layer between APIs, DBs, and third-party SDKs."),
("What is a Decorator?",
 "Wrapping an object to add behaviour without changing its class — Python implements it natively for functions (decorators); classes add fields/methods."),
("What is a Facade?",
 "A simplified unified interface over a complex subsystem — hiding internals from callers; your service-layer over routers/repositories is a facade."),
("What is a Proxy?",
 "A stand-in controlling access to the real object — lazy init, caching, auth checks, logging before the expensive/privileged call."),
("What is a Composite?",
 "Treating individual objects and compositions uniformly (tree structure) — the foundation of recursive UI and file-system models."),
("What is the difference between Adapter and Facade?",
 "Adapter single-class interface harmonising; Facade system-wide simplified face — scope is the distinction."),
("How does Python's functools/caching relate to Proxy?",
 "lru_cache is a transparent proxy with memoisation — the pattern borrowed where Python users rarely name it."),
("What is composition over inheritance?",
 "Wrapping/what-a objects instead of deep extends — flexibility at test time; the design recommendation you should state confidently."),
("How do structural patterns help LLM tooling?",
 "Each tool adapter implements a uniform interface; a proxy guards rate limits/auth; a facade hides provider differences — your agent tool registry is this."),
],
"04-Design-Patterns/03-Behavioral": [
("What are behavioral design patterns?",
 "Patterns managing communication/responsibilities between objects: Strategy, Observer, Command, State, Template Method, Iterator."),
("What is a Strategy pattern?",
 "Encapsulating interchangeable algorithms behind an interface — swapping behaviour at runtime (sort key callables in Python are strategies)."),
("What is an Observer pattern?",
 "Objects subscribing to events and being notified on change — pub/sub in GUIs and message systems; in Python, event callbacks or asyncio signals."),
("What is a Command pattern?",
 "Encapsulating an action as an object with execute/undo — enabling queues, retries, and undo history (the pattern behind task queues)."),
("What is a State pattern?",
 "An object changing behaviour when its internal state changes — vs if/else chains; token flows in agents map here."),
("What is a Template Method?",
 "A base class defining the skeleton of an algorithm with overridable steps — subclasses specialise steps; frameworks use this daily."),
("What is the relationship of Observer to message queues?",
 "A queue is the distributed, decoupled realisation of observer semantics — producers don't know consumers; classic patterns scale into systems."),
("What is the Iterator pattern in Python?",
 "Iterators are language-native (__iter__/__next__); generators implement lazy iteration — the pattern is so absorbed Python developers know it implicitly."),
("How do behavioral patterns map to agent frameworks?",
 "Strategy = pluggable planning; Observer = event hooks; Command = tool invocation objects with retries — the vocabulary transfers directly."),
("When should you avoid formal patterns?",
 "Over-applying 'four framework diagnosis' adds indirection; use them where future change/tests justify — judgment over syllabus."),
],
}