"""Curated Q&A for 01-DSA/05-Trees leaves."""
TREES = {
"05-Trees/01-Binary-Tree-Basics": [
("Define a binary tree.",
 "A hierarchical data structure where each node has at most two children, conventionally labelled left and right. It has a root, and every non-root node has exactly one parent."),
("What are the properties of a binary tree (levels, height)?",
 "Level of root = 0; height = max edges from root to leaf; a tree with n nodes has at most n-1 edges, and height can range from ~log2(n) (balanced) to n-1 (skewed)."),
("Name the basic types of binary trees.",
 "Full (each node 0 or 2 children), complete (all levels full except possibly last, filled left-to-right), perfect (all levels full), balanced (height O(log n)), and skewed."),
("How do you count the number of nodes in a tree?",
 "Recurrence: size(node)=size(left)+size(right)+1, base node is None returns 0. O(n)."),
("How do you compute the height of a tree?",
 "height(node)=1+max(height(left),height(right)), None returns -1 (edges) or 0 (nodes) depending on convention. O(n)."),
("What is the time complexity of traversals and why?",
 "Preorder/inorder/postorder/level-order each visit every node once: O(n) time; recursion stack or explicit queue adds O(h)/O(w) space."),
("How do you identify leaves and internal nodes?",
 "Leaf: left and right both None; internal: has at least one child. Check node.left is None and node.right is None."),
("What is a 'skewed tree' and its traversal cost?",
 "Each node has one child; height = n-1; recursion depth hits n which can overflow the stack for large trees — an interviewer favourite edge case."),
("Explain the recursive base-case discipline for tree functions.",
 "Always handle None first (the base case), then combine results of left/right subproblems. Every tree DFS follows this shape; forgetting the None check causes crashes."),
("How do you check if a tree is balanced (height-balanced)?",
 "Post-order: compute heights while verifying |hl-hr|≤1 at every node; propagate -1 on violation. O(n) time."),
("What is the diameter of a binary tree and how to compute it?",
 "Longest path between any two nodes (may pass through root). Post-order: track max(1+hl+hr) while returning height; O(n)."),
("How do you find the deepest/max-depth node?",
 "Recurrence max_depth = 1 + max(depth(left), depth(right)) — same as height. For the Node value, carry it alongside."),
],
"05-Trees/02-Binary-Search-Tree": [
("Define a binary search tree (BST).",
 "A binary tree ordered so that all values in the left subtree < node < all values in the right subtree (keys distinct per convention). Supports O(log n) expected search."),
("What is the expected vs worst-case height of a BST?",
 "Balanced: O(log n). Unbalanced insertion order (sorted input) makes it degenerate to O(n) height — the reason AVL/Red-Black trees exist."),
("How do you search in a BST?",
 "Compare target with root; go left if smaller, right if greater; None means absent. O(h), best O(log n). Recursion or iteration both work."),
("How do you insert into a BST?",
 "Walk like search; attach the new node at the None spot. Recursive returns the new subtree root; O(h) time."),
("How do you delete a node from a BST? (3 cases)",
 "Leaf: remove directly. One child: replace with the child. Two children: replace value with inorder-successor (leftmost of right subtree), delete that successor. O(h)."),
("What is the inorder successor of a node?",
 "The smallest value greater than node's value: if right child exists, leftmost in that subtree; else walk ancestors until taking a left turn. O(h)."),
("How do you validate whether a tree is a BST?",
 "Pass (lo, hi) bounds down recursion: every node must satisfy lo<val<hi. Do NOT just compare at children. O(n)."),
("How do you convert a sorted array to a balanced BST?",
 "Pick the middle element as root, recurse on left/right halves; yields a balanced tree O(n). This is a classic SP/DSE question."),
("What is the Kth smallest element in a BST?",
 "Inorder traversal produces sorted order; the Kth visited element is the answer — iterative stack for O(h+k). Or augment nodes with subtree sizes for O(h)."),
("What does the TreeMap analogy imply in the Infosys question?",
 "In Java, TreeMap is a red-black BST: operations O(log n), sorted iteration, comparison-based. HashMap is O(1) average but unordered — that is the exact 'HashMap vs TreeMap' answer."),
("How do you find the lowest common ancestor in a BST?",
 "Walk from root: if p,q both smaller go left; both larger go right; otherwise current is the LCA. O(h)."),
("How do you compute the sum/range queries on BST values?",
 "Range sum [lo,hi]: recursive pruning — go left only if val>lo, right only if val<hi, include node if in range. O(h + nodes touched)."),
("What is the 'two nodes swapped' BST recovery problem?",
 "Inorder traversal to detect two out-of-order neighbours (one violation possibly two) and swap their values to restore the BST. O(n)."),
("How do you make a BST from preorder traversal?",
 "Stack-based construction using the strictly-increasing upper bounds (or recurse with bounds across preorder indices). O(n)."),
("What is the difference between a BST and a heap?",
 "BST orders left<root<right (searchable), heap orders parent vs children extreme only (extreme-fast, no general search). BST supports order statistics; heaps support extreme queries."),
],
"05-Trees/03-Tree-Traversal": [
("List the three DFS traversals and their order of visiting.",
 "Preorder (node,left,right), inorder (left,node,right), postorder (left,right,node). All O(n); concurrency of order tells reconstruction stories in interviews."),
("Write the recursive inorder traversal.",
 "def inorder(n): if n is None: return; inorder(n.left); visit(n); inorder(n.right). Simple; recursive visits keep natural ordering in BSTs (sorted)."),
("Write the iterative inorder traversal using an explicit stack.",
 "Stack algorithm: push left chain; on pop, visit node, then move to right child and repeat. Avoids recursion depth limits; O(n) time, O(h) space."),
("Write the iterative preorder traversal.",
 "An easy one: push root, then while stack: pop node, visit, push right then left (right first so left pops first). O(n)."),
("Write the iterative postorder traversal.",
 "Either two-stack (push root; pop node into result, push left,right) then reverse result — or a single-stack with lastVisited tracking. O(n)."),
("How does level-order (BFS) traversal work?",
 "Queue of nodes with levels: dequeue, visit, enqueue children. Track level by queue-size snapshot for level-wise results. O(n) time, O(w) space."),
("How do you detect zigzag (spiral) level ordering?",
 "Queue with a direction flag; at each level, reverse collection order on odd levels. O(n)."),
("How do you compute left-view and right-view of a tree?",
 "Level-order or DFS recording the first node of each depth (left-view) / last node (right-view). O(n)."),
("How do you find bottom view / top view of a binary tree?",
 "BFS with horizontal distance (hd): keep map hd->value, updating for bottom (or first for top) at each hd. Use deque with hd tracking. O(n)."),
("What is Morris traversal and its advantage?",
 "Inorder with O(1) space using threaded pointers (temporary right links from inorder predecessor to node). Non-trivial; shows rare depth."),
("How do you reconstruct a tree from two traversals?",
 "Inorder + preorder (or + postorder): recursively split inorder by the root taken from pre/post; ++index each level. O(n) with hash map of inorder positions."),
("What is the iterative vs recursive DFS space tradeoff?",
 "Recursive DFS uses O(h) call-stack memory; iterative avoids stack overflow on pathological depth at the cost of explicit bookkeeping."),
("How do you perform a perfect-level sum or average per level?",
 "Level-order with per-level accumulation (sum/count) then average; O(n)."),
],
"05-Trees/04-Tree-Construction": [
("How do you construct a binary tree from preorder and inorder arrays?",
 "Preorder's first element is root; locate it in inorder (hash map O(1)), left section = left subtree, right section = right subtree; recurse with advancing preorder index. O(n)."),
("How do you construct a tree from postorder and inorder?",
 "Postorder's LAST element is root; locate in inorder, recurse right-subtree first (because postorder lists right before root-end), then left. O(n)."),
("Can you reconstruct uniquely from preorder and postorder alone?",
 "No — a node with one child makes pre+post ambiguous. Pre+inorder or in+postorder give unique trees; pre+post need extra info (like child marks)."),
("How do you serialise and deserialise a binary tree?",
 "Serialize: preorder with 'None' markers into a list/string. Deserialize: consume markers reconstructing recursively. O(n). This was a classic hard SP question."),
("How do you build a complete binary tree from a level-order list?",
 "Index-based: node at i has children at 2i+1 and 2i+2 (0-indexed) — build nodes array, attach children when index exists. O(n)."),
("How do you build a BST from a sorted linked list?",
 "Find mid via slow/fast, make it root, recurse on the two halves (bottom-up possible using size and global head). O(n log n) naive, O(n) bottom-up."),
("How do you build a BST from a sorted array (balanced)?",
 "Middle element = root, recurse on left/right halves. O(n) total; guaranteed balanced since halves are equal size."),
("How do you build a Cartesian tree from an array?",
 "Root is the minimum element; left/right children are Descartes trees of the subarrays. Stack construction O(n); links arrays + nearest smaller bounds."),
("What is a segment-tree-like fixed construction over arrays?",
 "Recursive build over range [l,r] from arr: node stores aggregate; parent = combine(children). O(n) build where n leaves (use padding to power of 2 if using arrays)."),
("How do you determine uniqueness constraints for reconstruction questions?",
 "Ask whether 'distinct values' is guaranteed — with duplicates reconstruction becomes non-unique; the same inorder position may appear in both subtrees."),
],
"05-Trees/05-Advanced-Tree-Problems": [
("How do you find the maximum path sum in a binary tree?",
 "Post-order returning max 'arm' (node + best single child path) while tracking global max including both children: candidate = node + leftarm + rightarm. O(n)."),
("How do you check if two trees are symmetric / mirror?",
 "Recursive check that left.left mirrors right.right and left.right mirrors right.left with equal values; None on both sides is the base. O(n)."),
("How do you check if a tree is a subtree of another?",
 "DFS on main tree checking isSameTree for each candidate root, with null-safe comparisons. O(m*n) naive; KMP on serialised traversal improves to O(m+n)."),
("How do you flatten a binary tree into a linked list (preorder)?",
 "Morris-like: for each node, connect inorder predecessor's right to current.right, move left to right. O(n) time O(1) extra space."),
("How do you find the kth largest element in a BST?",
 "Reverse-inorder (right,node,left) counting to k, or subtree-size augmentation. O(h+k)."),
("How do you find the closest value to a target in a BST?",
 "Walk left/right based on comparison, tracking best at each node. Closest = minimum absolute difference. O(h)."),
("How do you find the lowest common ancestor in a binary tree (not BST)?",
 "DFS: if root None or matches p/q return root; else collect left/right LCA results; if both non-None current is LCA, else return the non-None side. O(n)."),
("How do you count nodes in a complete binary tree faster than O(n)?",
 "Use the height property: if left and right heights equal, left subtree is perfect (2^h - 1); else recurse on right and imperfect side. O(log^2 n)."),
("How do you find the boundary traversal of a tree?",
 "Left boundary (excluding leaf), then leaves (inorder order), then right boundary reversed. Avoid duplicate corner nodes. O(n)."),
("How do you verify identical trees?",
 "Compare both None (equal), one None (not equal), values equal, then recurse on left and right simultaneously. O(n)."),
("What is the 'binary tree maximum width' problem?",
 "Treat tree as heap-indices array; BFS tracking index = 2*i, 2*i+1; width = last - first + 1 per level. Watch overflow with huge indices — use relative indices."),
("How do you find all root-to-leaf paths?",
 "DFS with path list; when leaf reached, copy the path to results; backtrack on return. O(n * path copies)."),
("What is the 'sum of root-to-leaf numbers' problem?",
 "DFS carrying cur = cur*10 + val at each node; at a leaf, add to total. Standard recursion test. O(n)."),
("How do you convert a binary tree to its mirror?",
 "Swap left/right children recursively (post-order swap); the tree becomes its mirror in place. O(n)."),
("How do you find a node's inorder successor with parent pointers?",
 "If right child exists: leftmost of right subtree; else climb until coming from a left child (node == parent.left). O(h)."),
],
"05-Trees/06-N-ary-Trees": [
("Define an N-ary tree and its typical node structure.",
 "A general tree where each node can have up to N children (in practice any number); node stores a list of children. Traversals generalise from binary counterparts."),
("How do DFS traversals change for N-ary trees?",
 "Preorder visits node then each child recursively; postorder visits children then node; there is NO natural inorder for N-ary trees (ambiguity of 'middle')."),
("How do you implement level-order on an N-ary tree?",
 "Same queue approach as binary: dequeue node, enqueue its children list. Children processed left-to-right. O(n)."),
("What is the maximum depth of an N-ary tree?",
 "depth(node)=1+max(depth(child)) over all children; None→0. Run on each child list; recursion or iterative stack. O(n)."),
("How do you serialise an N-ary tree?",
 "Preorder with a child-count marker per node (e.g., value, child_count, then children) enables unambiguous rebuild. O(n)."),
("How do you find the diameter of an N-ary tree?",
 "Post-order track the two largest child heights; diameter = max(1 + top1 + top2); return top height upward. O(n)."),
("What is a 'nested integer list' problem and why is it tree-like?",
 "The nested structure is an N-ary tree; weighted sum problems recursively flatten with depth. recursion + depth multiplier is the pattern. O(total integers)."),
("How do you clone an N-ary tree?",
 "Recursive: create new node, recurse cloning each child. O(n). Classic on LeetCode-style 'clone graph too'."),
("How do you represent a 'general tree as binary tree' (left-child right-sibling)?",
 "Left pointer = first child, right pointer = next sibling. This canonical representation lets binary-tree algorithms work on general trees."),
("How do you check subtree isomorphism for unrooted N-ary trees?",
 "AHU algorithm: recursively compute sorted tuple-of-child-codes; two trees are isomorphic iff root codes equal. Polynomial time."),
],
}